### ISSUE TITLE
add contract registers guidance to OCDS documentation?

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#1001]
@jpmckinney should this document be referenced in our improved implementation guidance: https://docs.google.com/document/d/10uHezdNkrdHtbIl6Uh3JZo7BlGm5T1qlCntqYGSVFg4/edit

It probably fits more in the main documentation guidance than in the EU profile documentation?

**Comment by jpmckinney** [comment]
I've added it to the 1.1.5 milestone.

**Comment by jpmckinney** [comment]
I'm not sure that it fits in the documentation – unless we create a "Resources" section that lists other similar resources that are currently posted on the OCP website.

I recommend working with Karolis and Georg to add it here first: https://www.open-contracting.org/resources/

In a future redesign of the docs, we will consider what additional information from the OCP website we should integrate.
