### ISSUE TITLE
Implementation guidance outstanding issues

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1009]
Outstanding issues from #986

**General:**

- [x] Add a 'publication plan' sub-heading to the design stage and link to that from the other stages, rather than linking to the template repeatedly.

**Design phase:**

- [ ] (Set your goals and priorities) Add link to [Guide to User Research](https://drive.google.com/file/d/10-4rTGmpXk4oRoyg7ccuv4Jga_6B_lpI/view) once document sharing settings updated.
- [x] Publish [Guide to OCDS Procurement Indicators](https://docs.google.com/document/d/1vSJk9-qWSTQEx9ZZc7BUhQZMHvTRcyDYVS2sl8HB__k/edit?usp=sharing) in resources section of OCP website and update link.
- [x] Publish [Spreadsheet mapping common objectives and indicators to OCDS](https://docs.google.com/spreadsheets/d/1nG7e52E1CXOXoUjz6pimW4Z7er9u3DJSs98QKdJJioE/edit#gid=110864222) in resources secction of OCP website and update link.
- [x] Re-order content in 'set your goals and priorities' section for better flow, consistent language and to link actions to supporting resources (identify stakeholders, then set goals, then determine data needs).

**Build phase:**

- [x] Publish [spreadsheet input template](https://docs.google.com/spreadsheets/d/1Py2Ki88TeerEToK8dIWcyU8rF5p6-jXhD7tx1W92m2g/edit#gid=956894726) as a resource on the OCP website and update link.
- [x] Add link to [technical case studies report](https://www.open-contracting.org/resources/technical-case-studies-ocds-implementation-insights/)
- [x] Publish remainder of series on prototyping OCDS data using spreadsheets (currently linked from the guidance, but only the first blog is published)
- [ ] Add link to packaging worked example under 'establish your publication formats and access methods', once ready.
- [x] Reorganize 'build your data pipeline' section into low tech capacity/infrastructure and high tech capacity/infrastructure.
- [x] Discuss required updates to 'Establish your publication formats and access methods' section and sub-pages, based on notes from OCDS retreat:
  * Put more emphasis in https://standard.open-contracting.org/latest/en/implementation/hosting/ ?
  * Revisit the guidance on bulk downloads and API filters
    1. We should strongly encourage the availability of bulk downloads in CSV format.
    2. We should encourage bulk downloads in JSON format, to avoid having to scrape the API to get the full dataset.
    3. We should encourage endpoints to get a single release (in a release package) by release id, and a single record (in a record package) by record ocid.
    4. Publishers might prefer to return a search response that only lists a bit of metadata about each contracting process; the user/client would have to then follow links to get the full details of the contracting process.
    5. Improve API guidance to describe API designs that would allow users to retrieve only new data, e.g. the user can pass a “since” parameter or a cursor.
- [x] Discuss whether 'keep users in mind as you build' can be removed, since it duplicates content under 'establish access methods and publication formats'

**Publish phase:**

- [x] Add action/link to self-assess against new quality criteria, once published.

**Comment by jpmckinney** [comment]
Other follow-up from #986:

* [x] Decide whether to delete licensing.md and publication_policy.md
* [x] I added hidden toctrees so that the docs build properly. We should add links to these pages.
* [x] design.md: The Publication Plan Template resources appears without introduction.
* [x] design.md: "scoping study" is not explained. Original text for comparison:

    > You can find the answers by following, adapting, or commissioning a report based on our [methodology for open contracting scoping studies](https://www.open-contracting.org/resources/methodology-open-contracting-scoping-studies/).

**Comment by odscrachel** [comment]
Actions still outstanding that involve resources becoming available:

- [ ] (Set your goals and priorities) Add link to [Guide to User Research](https://drive.google.com/file/d/10-4rTGmpXk4oRoyg7ccuv4Jga_6B_lpI/view) once document sharing settings updated.
- [ ] Add link to packaging worked example under 'establish your publication formats and access methods', once ready.
- [x] Add action/link to self-assess against new quality criteria, once published.

I'll raise a separate ticket regarding the action points about better API guidance, as it's currently unclear what we want to do here.

**Comment by jpmckinney** [comment]
I don't think OCP ended up publishing Reboot's guide to user research, and I don't think we have a worked example for packaging, so those can't be completed.

>  Add action/link to self-assess against new quality criteria, once published.

https://standard.open-contracting.org/latest/en/guidance/publish/#perform-final-checks
