### ISSUE TITLE
Clarify that org-id.guide registrations for OCDS publishers need to go through OCDS Helpdesk

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1015]
… rather than through org-id.guide directly, given that additions by that route are on hiatus.

From http://org-id.guide/about:

> We are not currently adding new, unsolicited entries to org-id while we focus our efforts on improving the service. Some open data standards have made arrangements to add fully researched org-id entries. Requests from those organisations will be dealt with under those arrangements.

(OCP's understanding is that fully researched org-id entries are covered under helpdesk contracts.)

If changes need to be made to normative content (documentation or schema), then a separate PR starting from the 1.1.5-dev branch needs to be made.

**Comment by duncandewhurst** [comment]
> (OCP's understanding is that fully researched org-id entries are covered under helpdesk contracts.)

Yes, that's correct.

For reference, we have been processing OCDS related requests which come directly into the org-id Github repo. We have also recently updated the org-id issue template to remind requestors to mention the data standard their request relates to, to make sure we can identify these, though on reviewing the documentation I see a few more places where that needs to be mentioned.

The implementation guidance for the [map phase](https://standard.open-contracting.org/1.1-dev/en/guidance/map/#mapping-organization-identifiers) already refers implementers to the helpdesk to request new org-id entries.

So I think the only update required is to the [organization identifier scheme codelist reference](https://standard.open-contracting.org/1.1-dev/en/schema/codelists/#organization-identifier-scheme):

> For information on how to get new additions made to this list, see the org-id.guide handbook

**Comment by jpmckinney** [comment]
Closed in #1036.
