### ISSUE TITLE
Update parties identifier/url fields to primary state register  

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#1028]
In the [Reference/Identifiers/Organization Identifiers](https://standard.open-contracting.org/1.1-dev/en/schema/identifiers/#organization-ids) section, the `identifier/url` might be better as the URL from [Companies House](https://beta.companieshouse.gov.uk/company/06368740), the primary state company register, since this is implied by the text in the worked example box. This also means updating the text below referring to Open Corporates.

This also requires updating the `identifier/url` fields in the organization identifiers [worked example](https://standard.open-contracting.org/1.1-dev/en/guidance/map/organization_identifiers/)

Also fictional example OCDS 1.1 [parties don't have an `identifier/url` field set](https://github.com/open-contracting/sample-data/blob/master/fictional-example/1.1/ocds-213czf-000-00001-04-award.json).

**Comment by jpmckinney** [comment]
@pindec Good point. Can you prepare a PR?

**Comment by pindec** [comment]
Noting [fictional sample OCDS data](https://github.com/open-contracting/sample-data/blob/main/fictional-example/1.1/ocds-213czf-000-00001-01-planning.json) uses `http://data.companieshouse.gov.uk/doc/company/[id]` as the `uri`, not `https://find-and-update.company-information.service.gov.uk/company/[id]`, so we should be consistent.
