### ISSUE TITLE
Integrate and improve tools directory

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1030]
Right now there is just a link at: https://standard.open-contracting.org/1.1-dev/en/support/#ocds-tools

The Engine Room shared some suggestions for improvements: [OCP_Airtable.pdf](https://github.com/open-contracting/standard/files/4749007/OCP_Airtable.pdf)

**Comment by LindseyAM** [comment]
Is this something the software product manager could lead?

**Comment by jpmckinney** [comment]
Sure, it all depends on priority, budget, etc. – might just be a small contract to a design firm.

**Comment by jpmckinney** [comment]
Will instead do #1076 only. (Slack thread: "Tools/Inspiration galleries")
