### ISSUE TITLE
Signing Officers

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/standard#1037]
In Prozorro they are modelling bank accounts and signing officers for those. Ukraine's taxation system is also based on type of organization rather than goods being sold, making this a necessary part of the model in that context. Account Identification was also necessary.

We suggested #705 to model the bank accounts, and *signatory* in this context is for the contract but is usually the same person as a bank account signatory as well. They also have an *Authority Document* which states what document permits signatory to act on behalf of the organization e.g. a charter or articles of incorporation. According to Oleh, producing a codelist of these is not feasible due to the number of different types of docments for different types of organizations.

There were additional considerations around the nominative and genetive cases for certain bits of information, so fields for these are included in the below model and named appropriately following style guides.

For signatories the proposed model was to create a new `signingOfficer` property capturing the necessary information.

```json
{
  "bankAccount": {
    "accountIdentification":[
      {
        "scheme": "IBAN",
        "id": "UAZZYYYYYYXXXXXXXXXXXXXXXXXXXX"
      }
    ]
  },
  "signingOfficer": {
    "name": "Петренко Іван Іванович",
    "genetiveName": "Перенка Івана Івановича",
    "position": "директор",
    "genetivePosition": "директора",
    "authorityDocument": "статут",
    "genetiveAuthorityDocument": "статуту"
  },
  "taxationMode": {
    "scheme": "UA",
    "id": "vat20",
    "description": "платник ПДВ 20% на загальних підставах"
  }
}
```

**Comment by jpmckinney** [comment]
ProZorro is somewhat unique as it is transparent about low-level details like signing officers, whereas most jurisdictions are transparent about higher-level details of the contracting process.

Closing as the issue has not garnered sufficient interest in several years to inform a standardized model.
