### ISSUE TITLE
In-line policies that are stored in Google Docs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1038]
To version control the normative/non-normative policy and the language policy.

* [x] Update links in standard-development-handbook from [Google Docs](https://docs.google.com/document/d/1xjlAneqgewZvHh6_hwuQ98hbjxRcA2IUqOTJiNGcOf8/edit) to new page

**Comment by jpmckinney** [comment]
Although this can be done in a 1.1.6, I think we will freeze 1.1, and only make changes in 1.2.0.

**Comment by duncandewhurst** [comment]
@jpmckinney can a PR be prepared for this issue (following the steps in the [process note](https://docs.google.com/document/d/1vBn4HFaczjcCur19kSwEMwk2uciFCdNgm9S9Ue_LnjY/edit#) for converting Google Docs to markdown)?

**Comment by jpmckinney** [comment]
Yes, and I figure they would be new pages under the Governance section.
