### ISSUE TITLE
Update links to CPV documentation

### ISSUE THREAD

**Issue by romifz** [open-contracting/standard#1040]
In the [codelist reference](https://standard.open-contracting.org/1.1.5-dev/en/schema/codelists/#item-classification-scheme) in the OCDS documentation, the link to the CPV documentation contains the URL below that redirects to the SIMAP's landing page:

http://simap.europa.eu/codes-and-nomenclatures/codes-cpv/codes-cpv_en.htm

I think this means the URL does not exist anymore. Maybe we should use this URL instead?

https://simap.ted.europa.eu/web/simap/cpv

**Comment by jpmckinney** [comment]
Good spot! I created a PR to fix this and any other issues that come up.

**Comment by yolile** [comment]
@jpmckinney in https://standard.open-contracting.org/1.1-dev/en/support/#ocds-community the "development" word is duplicated, should I create a new issue for that?

**Comment by jpmckinney** [comment]
I'll fix it directly on the same PR :)

**Comment by yolile** [comment]
in https://standard.open-contracting.org/1.1-dev/en/guidance/map/award_notices_decisions/#example-modelling-award-notices-with-multiple-decisions in the last paragraph it says:

>  for example, in Paraguay a combination of the award notice identifier and the supplier name is used, however, this approach is only appropriate as long as there can only be one supplier per award decision and each supplier can only appear once per notice.

But actually, besides the award notice id and supplier name, there is also a consecutive number (you can see it at the end of the award id) in case the same supplier is awarded more than once in the same process, so it could be changed to:

>  for example, in Paraguay a combination of the award notice identifier, supplier name, and a consecutive number is used.

**Comment by yolile** [comment]
and the link to the Paraguay API should be updated to https://contrataciones.gov.py/datos/api/v3/doc/ocds/record/ocds-03ad3f-340885-1

**Comment by jpmckinney** [comment]
Fixed sentence and link in PR and pushed to Transifex.

**Comment by yolile** [comment]
https://standard.open-contracting.org/1.1-dev/en/guidance/build/system_architectures/#separate-ocds-datastore

> It is possible to merge an centralize data from more than one systems in a single datastore.

should it be

> It is possible to merge **and** centralize data from more than one **system** in a single datastore.

?

**Comment by jpmckinney** [comment]
Yes, I'll fix the English.

**Comment by jpmckinney** [comment]
Sorry, I forgot to run `make extract` before the `tx push -s --no-interactive -r open-contracting-standard-1-1....` commands. The resources should now be updated in Transifex (and you should be able to reuse the translation from the translation memory).
