### ISSUE TITLE
Add 'software developer' to list of roles in implementation guidance

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1049]
The [build your team](
https://standard.open-contracting.org/1.1-dev/en/guidance/design/#build-your-team) section of the design guidance includes 'data expert' and 'system architect' roles, but not 'software developer'.

I suggest adding:

* A **software developer**, or developers, who will write the code for publishing OCDS data. They can be an internal team member or an external consultant. If you're updating an existing system, ideally the developer should be familiar with that system, or at least the relevant technologies, frameworks, and programming languages.

**Comment by jpmckinney** [comment]
Sounds good to me!
