### ISSUE TITLE
documentType: Add ''unsuccessfulDetails" to the codelist

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1052]
Similiar to https://github.com/open-contracting/standard/issues/202. For the tender 'cancelled' status we have a 'cancellationDetails' document to detail the cancellation related information, the suggestion is to add a 'unsuccessfulDetails' code to fit with the tender 'unsuccessful' status

cc @antonioherrera @jpmckinney

**Comment by jpmckinney** [comment]
Although this can be done in a 1.1.6, I think we will freeze 1.1, and only make changes in 1.2.0.

**Comment by yolile** [comment]
closed by #1336
