### ISSUE TITLE
Integrate blog post into serialization guidance

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1058]
https://www.open-contracting.org/2016/08/08/open-contracting-data-structure-spreadsheets/

Let's have a dedicated tabular formats page, as the serialization page will otherwise be quite long. Once that's done, we'll have to decide what to do with the remaining JSON content. Right now it has some "getting started" content (what is JSON) and some data-use content (Open Refine, etc.), both of which might fit better elsewhere. The last part of the page repeating the need for packages should already be covered elsewhere.

**Comment by duncandewhurst** [comment]
The tabular formats page should include clearer guidance and examples on representing arrays (using the `/0/`, `/1/` etc. array syntax in column headers) and on constructing multi-table representations (including `ocid` and `id` in all sheets, including the `id` field of the parent object for properties of objects in arrays)

**Comment by jpmckinney** [comment]
Merging into #1555 1555
