### ISSUE TITLE
Document availability period

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1059]
The [Himachal Pradesh Govt Tenders Information System](https://hptenders.gov.in/nicgep/app) specifies the period during which the tender documents can be downloaded.

Examples

tender/documentDownloadPeriod/startDate | tender/documentDownloadPeriod/endDate
-- | --
2017-05-10T11:00:00Z | 2017-05-31T10:00:00Z
2020-05-21T17:00:00Z | 2020-05-28T10:00:00Z

**Comment by jpmckinney** [comment]
I think "availability period" (`tender.documentAvailabilityPeriod`) is more appropriate. We can wait for evidence of other jurisdictions tracking this information. Tagging as an extension for now.

**Comment by jpmckinney** [comment]
If there is a use case in which different documents are available in different periods, this might be better as a field on the Document object.

**Comment by jpmckinney** [comment]
Closing as no additional evidence collected.

I assume many systems publish documents for only a limited time and take them offline (e.g. after an award is made) as part of an archival policy. However, I don't see the value in tracking this information in that scenario.
