### ISSUE TITLE
Amendment handling - confusing and inconsistent

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#106]
"I'm not clear on when a contract would be an amendment. Shouldn't amendments be a property on the contract being amended? It doesn't seem possible right now to answer the question, "What amendments exist, if any, for this contract?" Putting the property on the contract being amended would make this much easier."

From @jpmckinney #61

**Comment by andrewlorien** [comment]
I know this is a million years old, but to support Tim's last comment about legal significance above:
in [AusTender](https://tenders.gov.au), only Contracts are amended.  And they can either be a "material amendment", which is a change to a specific set of fields (eg the value), or a "non-material amendmend", which is a change to any other field (eg a phone number).
