### ISSUE TITLE
Clarify uniqueness of `parties/id` and document guidance on publishing data without organization ids

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1060]
Niether the schema nor the [identifiers reference](https://standard.open-contracting.org/latest/en/schema/identifiers/#identifiers) are clear on the unqiueness of `parties/id` and by extension `buyer/id`, `awards/suppliers/id` etc. My understanding is that these fields are local identifiers, unique within the scope of the `parties` array / contracting process.

When a data source only contains the name of an organization, publishers often get confused about how to populate `parties/id` and try to put a unique value in there. In practice, if the only identifier for an organization is its name, it would be better just to use a fixed or sequential identifier in `parties/id` so that users are not misled into thinking it can be relied on as an organization identifier.

We could:

1. Update the description of `parties/id`, e.g. 

> The ID used for cross-referencing to this party from other sections of the release. This field **need only be unique within the scope of the contracting process, but** may be built with the following structure {identifier.scheme}-{identifier.id}(-{department-identifier}) **where an organization identifier is available.**

2. Add a section to the [Identifiers reference page](https://standard.open-contracting.org/latest/en/schema/identifiers/#identifiers) to clarify the purpose and unqiueness constraints of `parties/id` and `OrganizationReference/id`.

3. Add a page to the guidance describing how to populate `parties/id` and `OrganizationReference/id` when your data source only includes names for organizations.

**Comment by jpmckinney** [comment]
I'm happy for all three to be pursued.
