### ISSUE TITLE
Fix description of awardCriteriaDetails

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1071]
awardCriteriaDetails is described as:

> Any detailed or further information on the award or selection criteria.

However, as mentioned in #162, award criteria are not selection criteria. Previous to #162, the description was:

> Any detailed or further information on the selection criteria.

So, "award or" was added. The correct change would have been to remove "selection".

Originally identified in https://github.com/open-contracting/standard/issues/901#issuecomment-693584325

**Comment by ColinMaudry** [comment]
@jpmckinney What's missing to close this?

**Comment by jpmckinney** [comment]
Nothing - GitHub only closes issues automatically once the relevant PR is merged to the main branch, which is presently 1.1-dev. The PR was merged to 1.2-dev (which is correct), but it didn't auto-close this issue.
