### ISSUE TITLE
Contact person details when registering prefix. Minor change. 

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/standard#1077]
When registering an OCID prefix we need to know who the contact person will be, and their email address. It doesn't state this on the standard website resulting in the helpdesk often having to email back to ask/clarify. 
I suggest we add this [here](https://standard.open-contracting.org/latest/en/guidance/build/#register-an-ocid-prefix) as a minor change to speed up the process for publishers.

**Comment by jpmckinney** [comment]
@odscrachel Sounds good!
