### ISSUE TITLE
max and min vs. maximum and minimum

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard#1078]
In the core schema, we have `tender.minValue`.

In the techniques extension we have `frameworkAgreement.maximumParticipants` and `frameworkAgreement.minimumParticipants`.

I think we should decide whether we want to use a short or a long prefix for minimum and maximum values.

**Comment by jpmckinney** [comment]
We should avoid abbreviations going forward. I added to the style guide here: https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#field-and-code-names

> Don’t abbreviate words, e.g. minimumParticipants not minParticipants.
