### ISSUE TITLE
Improving API guidance 

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/standard#1095]
In ticket #1009 there was an action to 'Revisit the guidance on bulk downloads and API filters' that included

- Improve API guidance to describe API designs that would allow users to retrieve only new data, e.g. the user can pass a “since” parameter or a cursor.
- We should encourage bulk downloads in JSON format, to avoid having to scrape the API to get the full dataset.
- We should encourage endpoints to get a single release (in a release package) by release id, and a single record (in a record package) by record ocid.
- Publishers might prefer to return a search response that only lists a bit of metadata about each contracting process; the user/client would have to then follow links to get the full details of the contracting process.

Some of this seemed a bit vague to me, so I wanted to check peoples thoughts about what our API advice should be? This is outside my area of expertise, but I'm happy to implement the changes once we have decided on them. 

Current advice is [here](https://standard.open-contracting.org/latest/en/guidance/build/hosting/)

**Comment by jpmckinney** [comment]
At the 2020-02 OCDS Retreat, I think this was mostly discussed by @juanpane and @duncandewhurst.

**Comment by yolile** [comment]
Noting that the [current documentation](https://standard.open-contracting.org/latest/en/guidance/build/hosting/) title is "Data files and APIs" but it barely describes APIs

**Comment by yolile** [comment]
and the other mention of APIs is here https://standard.open-contracting.org/latest/en/guidance/build/system_architectures/#additional-considerations

**Comment by duncandewhurst** [comment]
Closed by https://github.com/open-contracting/standard/pull/1526

**Comment by yolile** [comment]
The PR was merged against 1.2-dev instead of 1.1-dev

**Comment by jpmckinney** [comment]
We can cherry pick the commits into 1.1-dev. I can then merge that new PR.

**Comment by yolile** [comment]
closed by #1553
