### ISSUE TITLE
Link to extension explorer for OCDS extensions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1096]
The [BudgetBreakdown reference](https://standard.open-contracting.org/infrastructure/latest/en/reference/schema/#budgetbreakdown) includes links to the Github pages for the Budget Breakdown and Budgets and Spend extensions.

We should instead link to the extension explorer pages for these extensions and any other extensions referenced in the documentation.

**Comment by odscrachel** [comment]
Changed links I could find in general guidance text in #1299. Note that links still need changed [here](https://raw.githubusercontent.com/open-contracting/extension_registry/main/build/extensions.json) which populates the reference page via the extension_registry repo

**Comment by jpmckinney** [comment]
Thanks!

All URLs in the registry JSON file now use the Extension Explorer.

Also, Duncan's link is for OC4IDS. Please open a similar issue there if it doesn't exist yet.
