### ISSUE TITLE
itemClassificationScheme: Add codes for SDG and SDGTarget

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1098]
The [Himachal Pradesh Health Procurement Performance Index](https://hp.openbudgetsindia.org/#/procurement/analysis) tags contracting process with the SDG targets they relate to.

To model this in OCDS they are using the [tender classification extension](https://extensions.open-contracting.org/en/extensions/tenderClassification/master/) with `.scheme` set to 'SDG' or 'SDGTarget', depending on whether the contracting process is tagged with a goal or a target.

**Proposal**

Add 'SDG' and 'SDGTarget' to the itemClassificationScheme codelist (since https://github.com/open-contracting/standard/pull/1033 this codelist can be used in contexts other than items):

Code | Title | Description | Source | Category
-- | -- | -- | -- | -- 
SDG | Sustainable Development Goals | The Sustainable Development Goals are a collection of 17 interlinked goals set by the United Nations General Assembly and designed to be a "blueprint to achieve a better and more sustainable future for all". | https://sdgs.un.org/goals | contractingProcess
SDGTarget | Sustainable Development Goal Targets | The Sustainable Development Goal Targets are specific targets for each Sustainable Development Goal. | https://sdgs.un.org/goals | contractingProcess

There's an Excel sheet of the goals, targets and indicators available at https://unstats.un.org/sdgs/indicators/indicators-list/, so that might be a better source to reference than the main SDGs site.

cc @pindec

**Comment by duncandewhurst** [comment]
Recording the example shared in CRM-6407 here for posterity:

```
{
  "tender": {
    "classification": {
      "description": "By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases and combat hepatitis, water-borne diseases and other communicable diseases",
      "id": "3.3",
      "scheme": "SDGTarget"
    },
  }
}
```

And in CSV:

| tender/classification/scheme | tender/classification/id | tender/classification/description |
| - | - | - |
| SDGTarget | 3.3 | By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases and combat hepatitis, water-borne diseases and other communicable diseases |

**Comment by jpmckinney** [comment]
OC4IDS added these schemes, so I think it's fair to include them in OCDS as well.

https://github.com/open-contracting/infrastructure/blob/3a309e9c3fa9cb0b8300185cb1e1d89cd11eecbb/schema/project-level/codelists/classificationScheme.csv#L2
