### ISSUE TITLE
Extension for dealing with inflation

### ISSUE THREAD

**Issue by tdavis9** [open-contracting/standard#1099]
We would recommend adding some of the extensions we have created to deal with values/amounts that may change in certain countries due to inflation.

https://github.com/devgateway/ocds_currentValue_extension
https://github.com/devgateway/ocds_openingValue_extension
https://github.com/open-contracting-extensions/ocds_exchangeRate_extension

The problem with those countries (note: for DNV Argentina we had almost 50% of inflation in 2018, so if we had taken the signed value we wouldn't be able to create any chart for different year comparison e.g: Top ten awards, biggest winners, etc), is that it will become difficult to compare amounts from one year to another. 
The extensions  above tend to add more information to the standard and allow amount comparison between contracts that were held in different moments of time or to understand why the disbursements of some contracts are bigger than planned.

**Comment by jpmckinney** [comment]
Thanks, @tdavis9. Can you contribute to the discussion in #988?

We generally aren't in favor of an approach like `currentValue`. To populate `currentValue` with the actual current value would require continuously re-publishing values as exchange rates or inflation changes. It seems much simpler to just state the date of the original value, and allow data consumers to perform the conversion using whichever rates they prefer (spot rates, etc.). I also note that the extension adds the field at the top-level of the release, which I don't think is the intention.

That said, I'm happy to continue the discussion on the best approach in #988!

**Comment by jpmckinney** [comment]
As for `openingValue`, I am not clear on its semantics. In OCDS, the initial value of any `value` field is considered to be its "opening value". Could you clarify?

Also, for the inflation `coefficient`, any coefficient needs to be with respect to a specific date – the inflation coefficient from 1900 is different from 2000, etc. – so I am not clear how the user is expected to interpret that value.
