### ISSUE TITLE
Items in the Planning Section

### ISSUE THREAD

**Issue by tdavis9** [open-contracting/standard#1100]
We found that it is useful to have items in the planning section of the OCDS. We’ve created an extension for that 

https://github.com/devgateway/forms-makueni/tree/master/persistence-mongodb/src/main/resources/extensions/planning_items

**Comment by jpmckinney** [comment]
Thanks, @tdavis9. Can you contribute to the discussion in #794, where both this extension and an identical extension by Paraguay's DNCP are discussed?
