### ISSUE TITLE
Add Target Group to Organization Metadata

### ISSUE THREAD

**Issue by tdavis9** [open-contracting/standard#1102]
We found it useful to have the target groups of organizations included in the organization metadata. Also, tenders sometimes do have target groups included in their definition. Thus we have created the Target Groups extension to add this information to Organizations and Tender elements

https://github.com/devgateway/forms-makueni/tree/master/persistence-mongodb/src/main/resources/extensions/target_groups

**Comment by jpmckinney** [comment]
@tdavis9 Can you clarify the semantics of "target group"? Is it the group that is expected/desired to bid on the opportunity (e.g. some UK tenders are advertised as interesting to SMEs, but not reserved to SMEs)? Or are the semantics that the opportunity is restricted to/reserved for those groups?

In #711, we created an [organization classification extension](https://extensions.open-contracting.org/en/extensions/organizationClassification/master/) to allow different publishers to describe organizations using their own classification system for target groups, etc.

What's new in this issue, then, is to have a way to indicate which of those groups is targeted by a particular procurement. One option is to use the [tender classification extension](https://extensions.open-contracting.org/en/extensions/tenderClassification/master/) to classify the tender as targeting that group.

Like #891, this issue might motivate merging both those extensions into the release schema.

**Comment by jpmckinney** [comment]
If the semantics are "restricted to/reserved for these target groups", then from @ColinMaudry's work on the [OCDS for EU profile](https://standard.open-contracting.org/profiles/eu/master/en/), we have an [other requirements extension](https://extensions.open-contracting.org/en/extensions/otherRequirements/master/), which adds a `tender.otherRequirements.reservedParticipation` array, whose values are strings from an open codelist, and whose semantics are:

> The types of organizations to which participation is reserved.

**Comment by jpmckinney** [comment]
@LindseyAM @pindec In the cases we previously discussed for organization classification in #711 (Nepal, etc.), were classifications only used to describe organizations, or were they also used to describe which tenders were targeted to those groups?

**Comment by pindec** [comment]
@jpmckinney the previous discussion only covered cases where publishers wanted to describe organizations. 

In Kenya, there is a "legal requirement for women, youth and persons with disabilities to access 30% of Government Procurement opportunities" (registration determined by legal ownership of a particular organization) via the [AGPO programme](https://agpo.go.ke), which means tenders are "set aside" for these organizations. 

From [the about AGPO pages](https://agpo.go.ke/pages/about-agpo): "A procuring entity shall allocate at least thirty percent of its procurement spend for the purposes procuring goods, works and services from micro and small enterprises owned by youth, women and persons with disabilities.", and "a procuring entity shall implement the requirement through its budgets, procurement plans, tender notices, contract awards and submit quarterly reports to the Authority.". That page also mentions "preference and reservations schemes", which implies both are in operation. 

It's not clear whether the tenders listed on the AGPO site are:
* **reserved** for them (a procuring entity has to award to an AGPO organisation); or
* **targeted** at them (a procuring entity would prefer that they were awarded to an AGPO organization).

There are [no results](https://agpo.go.ke/pages/tenders?tender_type=Restricted+Tender) for Tender Type > Restricted.
Some tenders listed look like they are related to [infrastructure projects](https://agpo.go.ke/tender/id/519) and therefore are likely to be unsuitable for micro and small enterprises.

@tdavis9 is the intention for this extension to support AGPO monitoring?

**Comment by pindec** [comment]
Also noting that [Kenya's PPIP](https://www.tenders.go.ke/website) homepage presents the number and total value of contracts reserved for AGPO by financial year.

Evidence of a procuring entity asking for relevant suppliers to register with them for AGPO opportunities in [this tender](https://tenders.go.ke/website/tender/TenderDocument/42542).

**Comment by jpmckinney** [comment]
[UNCITRAL glossary](http://www.uncitral.org/pdf/english/texts/procurem/ml-procurement-2011/Glossary-e.pdf) defines:

ID | Term | Definition | References
-- | -- | -- | --
21 | Domestic procurement | Defined in article 2 of the Model Law as “procurement limited to domestic suppliers or contractors pursuant to article 8 of this Law”. For the explanation of the terms “procurement” and “supplier or contractor”, see ## 58 and 85 below. | - agreed exclusions from national treatment and non-discrimination (the 2012 WTO GPA, article V:4) - national competitive bidding (the World Bank procurement guidelines, provision 3.3)
22 | Domestic suppliers or contractors | In the context of a particular State, suppliers or contractors registered as legal entities in that State. For the explanation of the term “supplier or contractor”, see # 85 below. |  
23 | Domestically produced goods | In the context of a particular State, goods manufactured locally (legislation usually indicates the minimum percentage of required local content (labour, raw material, and components) for goods to qualify as such). For the explanation of the term “goods”, see # 35 below. | - domestic products (the 1994 WTO GPA, para. 2 of the preamble and articles III(1)(a) and XIII(4)(b)) - goods manufactured in the country of the Borrower (the World Bank procurement guidelines)

**Comment by duncandewhurst** [comment]
> That page also mentions "preference and reservations schemes", which implies both are in operation.

In the [Public Procurement and Asset Disposal Act 2015](http://ppra.go.ke/download/ppda2015/):

> * "preference" means the right or opportunity to select a tenderer  from  an  identified  target  group  that  is  considered more desirable than another;
> * "reservations" means exclusive  preference  to  procure goods,  works  and  services  set  aside  to  a  defined  target group of tenderers within a specified threshold or region;

The act also mandates the 30% budget allocation mentioned in https://github.com/open-contracting/standard/issues/1102#issuecomment-721679891, but leaves the actual preferences applicable to micro and small enterprises owned by youth, women and persons with disabilities to be prescribed elsewhere:

> 156. (15) The Cabinet Secretary shall prescribe the preferences  that  shall  facilitate  the  attainment  of  the  quota specified in subsection (10) in order for the State to achieve the objectives of Articles 55 and 227(2) of the Constitution.

The [THE PUBLIC PROCUREMENT AND ASSET DISPOSAL REGULATIONS, 2020](http://ppra.go.ke/download/the-public-procurement-and-asset-disposal-regulations-2020/) includes some detail on preferences for locally owned companies and locally manufactured goods:

![image](https://user-images.githubusercontent.com/19265814/141374733-aa6e6e89-32b5-4f67-ac2a-5bb59502f4c4.png)

However, I could not find where the preferences applicable to micro and small enterprises owned by youth, women and persons with disabilities are prescribed.

So it seems like reservations can be expressed using the [other requirements extension](https://extensions.open-contracting.org/en/extensions/otherRequirements/master/) and, where sufficient detail is available, preferences may be able to be expressed as [price coefficients](https://github.com/open-contracting/standard/issues/574). 

@tdavis9 - are the target groups subject to a preference or is the procurement reserved for them?

**Comment by duncandewhurst** [comment]
> What's new in this issue, then, is to have a way to indicate which of those groups is targeted by a particular procurement. One option is to use the tender classification extension to classify the tender as targeting that group.

Similar to the idea of targeting (rather than reserving) a tender at a particular group or type of organization, the UK's Contracts Finder system records whether tenders are suitable for SMEs and Voluntary, Community and Social Enterprises.

**Comment by duncandewhurst** [comment]
The UK wishes to use 3-value logic for tender suitability, e.g. a tender can either be suitable for SMEs, not suitable for SMEs or of unknown suitability for SMEs.

As such, we settled on adding `.vcse` and `.sme` boolean fields, grouped under `tender.suitability`.

**Comment by yolile** [comment]
The UK local extension is here https://github.com/Crown-Commercial-Service/ocds_tender_suitability_extension

**Comment by yolile** [comment]
Note that Paraguay DNCP will use the UK's suitability extension too.

**Comment by jpmckinney** [comment]
There is an extension that will be published soon that includes `tender.suitability.sme` (but not vcse from the UK): https://github.com/open-contracting-extensions/ocds_suitability_extension/pull/1

Other options included using https://extensions.open-contracting.org/en/extensions/otherRequirements/master/ and https://extensions.open-contracting.org/en/extensions/tenderClassification/master/

It seems like there is still work to do in order to standardize the model for this concept, but that is unlikely to occur for OCDS 1.2. So, closing with the preference to work out the model through extensions, which can be candidates for merging back into OCDS in 1.3/2.0.

Noting that the draft extension was https://github.com/devgateway/forms-makueni/tree/master/persistence-mongodb/src/main/resources/extensions/target_groups
