### ISSUE TITLE
Move unit to definitions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1107]
`unit` is currently defined as a property of `Item`.

The [metrics extension](https://extensions.open-contracting.org/en/extensions/metrics/master/) repeats the definition and [Moldova's eOCDS-eAuction](https://github.com/eOCDS-Extensions/eOCDS-eAuction) extension will do the same.

It would be better to have a definition for `unit` which can be referenced by extensions.

**Proposal**

1. Move the definition of `unit` to the definitions section of the schema.
2. Update the metrics extension to reference the definition, rather than repeat it.

cc @PaulBoroday

**Comment by jpmckinney** [comment]
Agreed. This is a simple refactor of the schema.

**Comment by jpmckinney** [comment]
@yolile for the metrics extension, we can rename master to 1.1 (and update the registry), and then add a 1.2 branch that references the Unit definition.

**Comment by yolile** [comment]
Closing in favor of https://github.com/open-contracting/ocds-extensions/issues/179 as the part related to the schema was done in #1240
