### ISSUE TITLE
Items: Add more detailed fields

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1110]
from discussion with @micayael from DNCP Paraguay

In #751 a dynamic "attributes" array was added to the item object as a local extension. This allowed the DNCP to disclose specific information about their items, such as product packaging, brand, and for some kind of products, as computers their specific characteristics as RAM Memory, etc.

Although they are including all the possible attributes of the items here, they consider that there are some of them that can be included in the item object itself, as those are always in all the items no matter what the item is. 

Specifically, they consider that the product packaging and unit of measure of the packaging are key fields to include in order to be able to compare and analyses items' unit prices. 

Another key field to include is the product packaging and unit of measure with which the tenderers can present their bids, this can be more than one. (for example, the tenderer only sells pencils in boxes of 100 units therefore he can only make his offer by boxes and not by unit)

The final use case is being able to compare and analyze items' unit prices in the most accurate way

**Comment by jpmckinney** [comment]
Sounds good to me! Related to #1050. Could you share draft JSON Schema or example JSON data?

**Comment by yolile** [comment]
For including the packaging and its unit (maybe the same can be applied to medicines form/dosage? from #1050):
(I'm not sure about the "packaging" name, but I couldn't find any existing schemas describing the package/form of products eg http://www.heppnetz.de/ontologies/goodrelations/v1#SomeItems , https://schema.org/TypeAndQuantityNode,  https://schema.org/Product, https://schema.org/Demand)

### Schema

```json
{
    "definitions": {
        "Item": {
            "properties": {
                "packaging": {
                    "title": "Packaging",
                    "description": "A description of the package in which the supplies are provided (e.g. box, bag) and its relation with the unit of measure.",
                    "type": "object",
                    "properties": {
                        "name": {
                            "title": "Name",
                            "description": "Name of the package.",
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "unitsPerPackage": {
                            "title": "Unit",
                            "description": "A description of the unit in which the supplies package is provided and its quantity per package.",
                            "type": "object",
                            "properties": {
                                "scheme": {
                                    "title": "Scheme",
                                    "description": "The list from which identifiers for units of measure are taken, using the open [unitClassificationScheme](https://standard.open-contracting.org/1.1/en/schema/codelists/#unit-classification-scheme) codelist. 'UNCEFACT' is recommended.",
                                    "type": [
                                        "string",
                                        "null"
                                    ],
                                    "codelist": "unitClassificationScheme.csv",
                                    "openCodelist": true
                                },
                                "id": {
                                    "title": "ID",
                                    "description": "The identifier from the codelist referenced in the `scheme` field. Check the [unitClassificationScheme](https://standard.open-contracting.org/1.1/en/schema/codelists/#unit-classification-scheme) codelist for details of how to find and use identifiers from the scheme in use.",
                                    "type": [
                                        "string",
                                        "null"
                                    ],
                                    "versionId": true
                                },
                                "name": {
                                    "title": "Name",
                                    "description": "Name of the unit.",
                                    "type": [
                                        "string",
                                        "null"
                                    ]
                                },
                                "uri": {
                                    "title": "URI",
                                    "description": "The machine-readable URI for the unit of measure, provided by the scheme.",
                                    "format": "uri",
                                    "type": [
                                        "string",
                                        "null"
                                    ]
                                },
                                "quantity": {
                                    "title": "Quantity",
                                    "description": "The number of units the package contains.",
                                    "type": [
                                        "number",
                                        "null"
                                    ]
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
### Examples

#### Paraguay

https://contrataciones.gov.py/licitaciones/adjudicacion/contrato/386468-super-familia-s-a-1.html#itemsLote 
"150 units of noodles in packages of 5 kilograms each"

```json
{
    "items": [
        {
            "id": "q5+xy7XWFLE=",
            "description": "Fideo",
            "quantity": 150,
            "unit": {
                "name": "Unidad",
                "id": "UNI",
                "value": {
                    "amount": 25000,
                    "currency": "PYG"
                }
            },
            "packaging": {
                "name": "PAQUETE",
                "unitsPerPackage": {
                    "name": "Kilogramos",
                    "id": "KG",
                    "quantity": 5
                }
            }
        }
    ]
}
```

#### Chile
https://www.mercadopublico.cl/Procurement/Modules/RFB/DetailsAcquisition.aspx?qs=1fcOt9lqIDGakvsmE6FnVg== 
"3000 packages of spaghetti in packages of 400 grams each"

```json
{
    "items": [
        {
            "description": "SPAGUETTI N°5",
            "quantity": 3000,
            "unit": {
                "name": "Paquete",
            },
            "packaging": {
                "name": "Paquete",
                "unitsPerPackage": {
                    "name": "Gramos",
                    "id": "gr",
                    "quantity": 400
                }
            }
        }
    ]
}
```

#### Uruguay
https://www.comprasestatales.gub.uy/consultas/detalle/mostrar-llamado/1/id/832031
"24 kilograms of noodles in packages of 1 kilogram each"

```json
{
    "items": [
        {
            "id": 3,
            "description": "FIDEOS",
            "quantity": 24,
            "unit": {
                "name": "Kilogramos",
            },
            "packaging": {
                "name": "PAQUETE",
                "unitsPerPackage": {
                    "name": "Kilogramos",
                    "id": "KG",
                    "quantity": 1
                }
            }
        }
    ]
}
```

**Comment by jpmckinney** [comment]
@yolile It looks like the model might be better expressed as below (using UN/CEFACT Common Codes for Units of Measurement):

```json
{
    "items": [
        {
            "id": "q5+xy7XWFLE=",
            "description": "Fideo",
            "quantity": 150,
            "unit": {
                "name": "PAQUETE",
                "id": "UNI",
                "value": {
                    "amount": 25000,
                    "currency": "PYG"
                },
                "weight": {
                  "value": 5,
                  "unit": "KGM"
                }
            }
        }
    ]
}
```

```json
{
    "items": [
        {
            "description": "SPAGUETTI N°5",
            "quantity": 3000,
            "unit": {
                "name": "Paquete",
                "weight": {
                    "value": 400,
                    "unit": "GRM"
                }
            }
        }
    ]
}
```

```json
{
    "items": [
        {
            "id": 3,
            "description": "FIDEOS",
            "quantity": 24,
            "unit": {
                "name": "PAQUETE",
                "weight": {
                    "value": 1,
                    "unit": "KGM"
                }
            }
        }
    ]
}
```

Applications can translate the unit of the weight – It's not OCDS' responsibility to store that.

There's a little information loss compared to your example but `"name": "Unidad"` isn't informative anyway.

**Comment by yolile** [comment]
Sure! Yes, you are right `weight` fits better, I wanted to reuse the `unit` object but I think it is ok to just include it as a name. 

However, the items can appear at the tender, bid, and award levels. Talking with the DNCP team, they brought up that at the tender level, the buyer can specify more than one weight for the requested item, to not limit the competition (eg a supplier could have only boxes of 1.5 KGM instead of 1 KGM). The DNCP suggestion is to add a specific field like "quotation form" or "bid unit" etc to indicate the allowed forms of bid for each item.
I'm not sure if this should be modeled at the item level or maybe using the [requirements extension](https://extensions.open-contracting.org/en/extensions/requirements/master/)?

**Comment by jpmckinney** [comment]
Yes, the requirements extension (which doesn't fully implement the CCCEV model, but we can improve that) seems appropriate, since it can express both AND and OR criteria.

**Comment by jpmckinney** [comment]
NB: #1125 was reverted in #1481. #1343 proposes a different approach to this issue, where there is an `immediatePackaging` object to describe the packaging (instead of a `unit` with a name of `Paquete`). This object itself has a `capacity` object, which has `unit` and `value` fields, to be able to say the packaging has a capacity of 400g, etc.
