### ISSUE TITLE
Guidance: Add link to training request form

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1116]
http://bit.ly/OCP-Training as used on this page: https://www.open-contracting.org/data-standard/documentation

**Comment by Ravf95** [comment]
@jpmckinney I think we can close this because the page already has a training request button
![image](https://user-images.githubusercontent.com/16477965/175995677-b089f1fb-10f8-41dc-bf6c-e9194e23fc89.png)

**Comment by yolile** [comment]
The idea is to add the link to the standard documentation page https://standard.open-contracting.org/latest/en/guidance/, probably after _"Do you have questions or need assistance? Contact the [OCDS Helpesk](https://standard.open-contracting.org/latest/en/support/)."_

**Comment by Ravf95** [comment]
I misunderstood, thanks for the suggestion, we can put it there
