### ISSUE TITLE
Guidance: Add videos and slides relating to extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1118]
[Creating OCDS extension webinar video](https://youtu.be/1uTik92PWfo)
[Webinar slide deck](https://docs.google.com/presentation/d/16poTfulCN1oYctfWnMJ9YDRrX1GJMi1MuOmFlOJMC5w/edit)

https://standard.open-contracting.org/latest/en/guidance/build/#build-your-extensions

**Comment by dulceareco** [comment]
Hi @jpmckinney @yolile 

Following up on this issue, we could add the link to the [video](https://www.youtube.com/watch?v=1uTik92PWfo) where it says "develop your own extensions" ([Build your extensions paragraph](https://standard.open-contracting.org/latest/en/guidance/build/#build-your-extensions)) and add a short text like "We also have a slides version of the video that you can check" or "Creating an OCDS extension slides" with the [link](https://docs.google.com/presentation/d/16poTfulCN1oYctfWnMJ9YDRrX1GJMi1MuOmFlOJMC5w/edit) to it if that's okay.

**Comment by jpmckinney** [comment]
We can just follow the `**Resource:**` format as used in other sections instead of adding a short text.
