### ISSUE TITLE
letsencrypt moves away from cross signing, dropping support for old Androids

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#1124]
https://letsencrypt.org/2020/11/06/own-two-feet.html

Versions of Android prior to 7.1.1 are affected. The user has a work around of installing Firefox Mobile.

This changes by default from January 11, 2021, and you can explicitly request a cross sign until September 2021.

Do we need to do anything for the OCDS websites? I'm sure you have a better idea of how important supporting these devices is. And, there's people we could ask about how problematic this may be in various country contexts (e.g. CDS).

**Comment by jpmckinney** [comment]
Thanks for sharing!

I had a look at Google Analytics, and under the Open Contracting property (includes OCDS documentation), in the last week, there were 2805 users, 333 on Android (12%), 40 on versions under 7.1.1 and 4 with unknown version (so 1.4 to 1.6%). These users mostly produced pageviews on www.open-contracting.org. Only 15 pageviews on standard.open-contracting.org, and none on the other apps/services. I think that's small enough to not matter.
