### ISSUE TITLE
unitClassificationScheme: Consider codes

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1127]
QUDT cross-references many other schemes, though it's not clear if any of them are likely to be used in a procurement context (this concern includes QUDT): https://github.com/qudt/qudt-public-repo/issues/30

It references:

* IEC61360: https://en.wikipedia.org/wiki/IEC_61360
* UCUM: https://ucum.org/
* OM: http://www.ontology-of-units-of-measure.org
* ISO80000
* SWEET
* BODC P06
* Wikipedia
* DBpedia

**Comment by jpmckinney** [comment]
Noting that UCUM came up in the context of the medicine extension.  UCUM is more like a standard way to specify units (e.g. "kg/l" not "kg per L" etc.), than a full list of units:

> “Since the space of possible unit terms is infinite in theory and very large in practice, no attempt has been made on a systematic coverage of possible units.” https://ucum.org/ucum.html 

For one list, see https://github.com/lhncbc/ucum-lhc/blob/master/data/ucum.csv linked from https://ucum.nlm.nih.gov/ucum-lhc/demo.html  linked from https://ucum.org/trac

**Comment by jpmckinney** [comment]
Another potential scheme to add is [international unit (IU)](https://en.wikipedia.org/wiki/International_unit) / [WHO international reference preparations](https://www.who.int/teams/health-product-and-policy-standards/standards-and-specifications/catalogue).

**Comment by duncandewhurst** [comment]
I can't find any evidence of these other schemes being used in a procurement context. Shall we just add UCUM for now and add the others as we see demand or evidence?

**Comment by jpmckinney** [comment]
Yes, let's just add UCUM.

**Comment by jpmckinney** [comment]
Actually, it's not even clear that UCUM is used. For the medicine extension, we use UNCEFACT. So, closing until there's demand.
