### ISSUE TITLE
unitClassificationScheme: Update QUDT URL

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1128]
QUDT has a better browser now, and a newer version: http://qudt.org/edg/tbl/qudt_units.editor

**Comment by yolile** [comment]
That URL requires a user account, should we use it anyway?

**Comment by jpmckinney** [comment]
Well, it was working without login before 😆 . The current link is for version 1.0.0, which is very old. They seem to only have versioned links. We can just link to http://qudt.org instead.

**Comment by yolile** [comment]
Closed by #1381

**Comment by jpmckinney** [comment]
Looks like we have a surviving reference to https://www.qudt.org/qudt/owl/1.0.0/unit/ in reference.md
