### ISSUE TITLE
Common metrics in milestones.

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#113]
From asadleir on v0.3.2

Are there some common metrics that could be included as optional values here? eg. hours of effort expended/remaining for services. These may be contained in the milestone reports but would good to expose as machine readable.

**Comment by timgdavies** [comment]
This is likely to be explored as part of PPP extension work

**Comment by timgdavies** [comment]
The updates to milestones in #373 introduce a new ```code``` element to tag particular kinds of milestones. 

The extensions mechanism can be used to manage further application-specific data on milestones.
