### ISSUE TITLE
Adding keywords to EU profile link

### ISSUE THREAD

**Issue by odscrachel** [open-contracting/standard#1131]
I noticed when searching for the [link to the EU profile](https://standard.open-contracting.org/latest/en/guidance/map/extensions/#profiles) within standard guidance, that it was difficult to find. A publisher also recently contacted the helpdesk to ask for the details. 

I suggest we add the keywords 'TED' and 'EU' to the text to allow users to find it in the search.

**Comment by jpmckinney** [comment]
Sounds good! Feel free to make a PR.
