### ISSUE TITLE
Guidance: Align language in build phase with language in map phase

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1139]
The [map guidance](https://standard.open-contracting.org/latest/en/guidance/map/) uses 'data source' to describe systems which capture and store contracting data, but the [system architecture](https://standard.open-contracting.org/latest/en/guidance/build/system_architectures/) guidance uses 'live system'.

We should use 'data source' throughout to be consistent.

**Comment by jpmckinney** [comment]
What changed in the PNG files? I'm not sure why they are part of the PR.

**Comment by nativaldezt** [comment]
The PNG files had the text Live System too, so I change it to Data Source.

**Comment by jpmckinney** [comment]
Closed by #1150
