### ISSUE TITLE
Add tender.standstillPeriod field

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1142]
[UNCITRAL glossary](http://www.uncitral.org/pdf/english/texts/procurem/ml-procurement-2011/Glossary-e.pdf) defines:

Term | Definition | Reference
-- | -- | --
Standstill period | Defined in the Model Law as: “Period starting from the dispatch of a notice as required by paragraph 2 of article 22 of this Law, during which the procuring entity cannot accept the successful submission and during which suppliers or contractors can challenge, under chapter VIII of this Law, the decision so notified.” For the explanation of the term “procuring entity”, see # 62 above. For the explanation of the terms “successful submission” and “supplier or contractor”, see ## 84 and 85 below. | N/A

Its addition will depend on its availability among potential publishers.

Related to #205

**Comment by jpmckinney** [comment]
If we add this field, we might want to add a worked example similar to #1344 in which an award is challenged during a standstill period. Whether we just need `statusDetails` or a new status code is to be determined.

**Comment by odscrachel** [comment]
Just a note that this came up in modelling conversations with the UK Cabinet Office.

**Comment by duncandewhurst** [comment]
According to the World Bank's [Benchmarking Infrastructure Development 2020](https://bpp.worldbank.org) database, the following countries' procurement legislation includes a standstill period. The data covers 40 countries and is based on applying the case study assumptions described in the [methodology](https://bpp.worldbank.org/methodology), essentially a competitive tender for a 'traditionally procured' (i.e. non-PPP) $50m infrastructure project. In most cases, it looks like the same standstill period provisions apply to all types of procurement, although in one or two the provisions are infrastructure-specific. In some cases the standstill period must be set out in the notice of intention to award and, in others, not.

Economy | Standstill period set out in the notice of intention to award
-- | --
Azerbaijan | No
Burkina Faso | No
China | No
El Salvador | Yes
Ethiopia | No
Georgia | No
Italy | Yes
Kenya | No
Kyrgyz Republic | No
Madagascar | No
Peru | No
Romania | No
Russian Federation | No
Spain | Yes
Turkey | No
Uganda | No
Ukraine | No
United Kingdom | Yes

I've extracted the relevant data into a [spreadsheet](https://docs.google.com/spreadsheets/d/1HFHIyaf9087fbkcjYfcs0OHymUlxwLXrU2uf-buQ-4k/edit#gid=1890964663), which includes details of the legal/regulatory provisions.

If we want more data, the World Bank's [Benchmarking Public Procurement 2017 : Assessing Public Procurement Regulatory Systems in 180 Economies](https://openknowledge.worldbank.org/handle/10986/32500) covers 180 countries and includes data on standstill periods, but the report is only available in PDF format and the data is difficult to extract.

I also checked the [1.2 implementation research field usage data](https://docs.google.com/spreadsheets/d/1HJbqmgoM1wOFyQfmv7WZXjvyyO6hzKpquiMwtMFo8AE/edit#gid=1299987550) and the latest data from all the sources available in [OCDS Downloads](https://ocds-downloads.opendata.coop/) to identify whether any existing publishers publish a field with 'standstill' in the field path. None do.

@jpmckinney should we go ahead with adding the field, or should we check some notices for a sample of the above countries to see if/how data on standstill periods is structured?

**Comment by jpmckinney** [comment]
A standstill period is fairly predictable, as it is usually the same rule for all procurements, with maybe occasional exceptions. 

That said, since it can sometimes differ (e.g. infrastructure-specific provisions), it's still relevant to disclose in the data.

We know that many countries have this information, and since it's a fairly significant deadline, it's useful to disclose, even if we cannot find any countries that currently express it in data.

However, I'm not sure whether it ought to be modelled as a period or as a single date deadline. That's because a standstill period presumably always starts with the announcement of the (intention to) award.

So, it'd be useful to find a few samples first.

**Comment by yolile** [comment]
> So, it'd be useful to find a few samples first.

In Paraguay, according to the Public Procurement Law ([page 77](https://www.contrataciones.gov.py/documentos/download/marco-legal/40162), Art. 79 and Art. 66), the bidders can present a complaint against any award up to ten workdays after the award decision was made.

**Comment by duncandewhurst** [comment]
Here's a couple of examples of notices of intention to award from the UK, one uses a starting date plus a duration and one uses and single-date deadline:

[Letter to unsuccessful tenderers, Charnwood Borough Council](https://www.charnwood.gov.uk/files/documents/alcatel_successful_notification_letter/Alcatel%20award%20%28successful%29.doc)

> In accordance with Regulations 85 to 87 of the Public Contracts Regulations 2015 and procurement best practice, the Council cannot formally award the contract to you until a minimum of 10 calendar days have passed, starting from **(insert date of 1 day after the date of this letter, if the final 10th day of the standstill falls on a weekend day you must extend the standstill period to the next available working day).  [Note to buyer: This 10-day period assumes that the correspondence has been sent electronically.  Should this not be the case, and the letter is to be sent through the post a period of 15 calendar days will apply. ]**

[Intention to Award Letter, procurementtemplates.co.uk](http://procurementtemplates.co.uk/intention-to-award-letter-template/)

> A mandatory “standstill” period is now in force pursuant to of the Regulations; this period
will end at midnight on **[inset date 10 days after the award letter has been issued, date letter is
issued is day zero and ends on midnight].**

In terms of modelling, the `Period` object might be best, that way a publisher could disclose the `durationInDays` of the standstill period when the tender is published and later update the `startDate` and/or `endDate` when the award decision is made.

**Comment by jpmckinney** [comment]
Sounds good to use periods, since we need to support both durations and specific dates.

**Comment by JachymHercher** [comment]
> According to the World Bank's Benchmarking Infrastructure Development 2020 database, the following countries' procurement legislation includes a standstill period.

Probably no news here, but all EU countries have the standstill period. We considered it for eForms, but a) since there is no notice published after an award, i.e. the time when the standstill period starts; b) it is always the same length, there was no reason to add it.
