### ISSUE TITLE
Supplier - definition ("awarded or contracted")

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1149]
In https://github.com/open-contracting/standard/issues/903#issuecomment-728178107, I questioned whether the definition of 'Supplier' ("An entity awarded or contracted to provide goods, works or services.") requires both "awarded" and "contracted".

> As long as the definition includes "awarded", if a buyer awards a contract to supplier A, then supplier B goes to court, then a new award goes to supplier B, you have two suppliers (as long as the original award isn't cancelled, but just doesn't lead to a contract). I'm not sure this is ideal.

> On the other hand, since OCDS only has 'suppliers' in Award, perhaps "awarded" needs to stay as the centrepiece. However, it might be clearer if "contracted" stems out of "awarded", something like "An entity to which the buyer or procuring entity has decided to award a contract".

To clarify, the point of the first paragrah was that if we mention "awarded", then non-intuitive things can sometimes happen. The point of the second paragraph was that maybe having "awarded" is unavoidable, because in OCDS, suppliers are referenced in `Award`, not `Contract`. However, in that case, let's still avoid having two verbs at the same level ("awarded or contracted") and instead have only one verb ("awarded"). Since "awarded" as the only verb might be unclear (e.g. if the definition was "An awarded entity" or "An entity listed in an award"), we should also mention a contract (but not as a verb of its own, but as an object of the main "awarded" verb) and for readability purposes also the subject that awards the contract. Thus the proposed: "An entity to which the buyer or procuring entity has decided to award a contract".

However, thinking about it again and looking at the definition of "Award" in https://github.com/open-contracting/standard/issues/895#issuecomment-720684175 (including https://github.com/open-contracting/standard/issues/895#issuecomment-747835840), I would actually propose to avoid both verbs - "awarding" and "contracting". Instead, let's use a definition reusing the terms from the definition of an award: "An entity with which a buyer or a procuring entity wishes to conclude a contract."

**Comment by jpmckinney** [comment]
From the [glossary](https://docs.google.com/spreadsheets/d/1Nh_HjyYuNk8wuu_Tb0kcPDyV6j8pAMgXqJ3MgwpXZjQ/edit#gid=1183552086):

* OCDS 1.1: The suppliers awarded this award. If different suppliers have been awarded different items or values, these should be split into separate award blocks.
* MAPS: A party that supplies goods, works, or services, i.e. in this context, “supplier” implies contractors and service providers that include consulting firms or others.
* UNCITRAL: Supplier or contractor | Defined in the Model Law as: “According to the context, any potential party or any party to the procurement proceedings with the procuring entity.” For the explanation of the term “procuring entity”, see # 62 above.
* EBRD: Also includes potential suppliers or contractors
* eForms: Winner | Additional information about the winner, tenderer or subcontractor.

So, only eForms matches OCDS' semantics: the others use "suppliers" in the sense of "suppliers in the market". I think the other sources have a word for the contracted supplier, but not for the (merely) awarded supplier.

How about this for a definition:

> An entity with which a buyer or a procuring entity intends to conclude a contract as a result of a contracting process.

I made those slight changes, to avoid confusion with respect to direct awards, where a buyer might wish to conclude a contract with a supplier before the contracting process even exists.

**Comment by JachymHercher** [comment]
> So, only eForms matches OCDS' semantics: the others use "suppliers" in the sense of "suppliers in the market"

eForms rather avoids the use of "supplier" altogether - the definition in the act re-uses the Directives' term "successful tenderer". 

(By the way: the previous procurement directive 2004/18/EC says the following: "The terms ‘contractor’, ‘supplier’ and ‘service provider’ mean any natural or legal person or public entity or group of such persons and/or bodies which offers on the market, respectively, the execution of works and/or a work, products or services. The term ‘economic operator’ shall cover equally the concepts of contractor, supplier and service provider. It is used merely in the interest of simplification.")

> How about this for a definition:
An entity with which a buyer or a procuring entity intends to conclude a contract as a result of a contracting process.

wishes --> intends is probably better, we should use it also in https://github.com/open-contracting/standard/issues/895. 

Concerning the addition "as a result of a contracting process", I'm not sure. If we need it here, then we should also have it in the [definition of "award"](https://github.com/open-contracting/standard/issues/895), e.g. "Decision, _resulting from the contracting process_, by the buyer or procuring entity on the supplier with whom it ~~wishes~~ _intends_ to conclude a contract, including the items the supplier should supply and their price. [...]" or "_Official_ decision by the buyer..." 

However, this adds some uncertainty (what does "resulting", "result" mean? Isn't the only result of a contracting process a contract? Or is it an award? What does "official" mean, etc.) What about:

_"An entity with which a buyer or a procuring entity intends to conclude a contract. Suppliers are known only after an award has taken place."_

**Comment by ColinMaudry** [comment]
I like how we move towards using key concepts via nouns instead of verbs. This is helpful to improve consistency across definitions.

**Comment by jpmckinney** [comment]
We're avoiding terms like "winner" and "successful tenderer" to be able to use Award objects to represent unsuccessful awards (e.g. due to a complaint), correct?

> 1. An entity with which a buyer or a procuring entity wishes to conclude a contract.
> 1. An entity with which a buyer or a procuring entity intends to conclude a contract as a result of a contracting process.
> 1. An entity with which a buyer or a procuring entity intends to conclude a contract. Suppliers are known only after an award has taken place.

In the end, I prefer the original suggestion (with "intends"). (3) just raises more questions. (What does it mean for an award to take place? Mustn't the supplier be "known" in order for the buyer to intend to conclude a contract with it?)

**Comment by ColinMaudry** [comment]
A supplier is a "tenderer" whose proposal has been accepted by the buyer. I'd consequently go for 3) as long as we refine the definition of "award".

My understanding is that an OCDS Award object is created when the buyer has finished studying some sort of proposal (bid, contest application, selection phase, etc.) and publishes the result.

Award: here is what the buyer has decided based on what the "tenderers" (in a broad sense) provided.

**Comment by ColinMaudry** [comment]
The difficulty with "after an award has taken place" is that we use the word award in its narrow definition (awarding a contract). But the way the Award object is used in OCDS is broader.

We consequently need to:

1. refine the definition of Award (or at least review it with its relationship with supplier in mind)
2. either
  - paraphrase the definition of Award in the definition of Supplier (e.g. "Suppliers are known when the buyer has communicated its decision"), or 
  - refer to the OCDS Award object (broad semantics) instead of the typical award, to avoid confusion

**Comment by ColinMaudry** [comment]
Or we rename Award and Supplier to reflect their broad semantics, e.g. Decision and Contractor.

**Comment by jpmckinney** [comment]
For the definition of award, see #895. For context, the proposed definition is:

> Decision by the buyer or procuring entity on the supplier with whom it intends to conclude a contract, including the items the supplier should supply and their price. Typically, this decision leads to a contract, but not always (e.g. the award is appealed at court or the supplier refuses to sign the contract). Depending on the jurisdiction, a single decision may concern a single supplier, item and value; or batches of suppliers and/or items and/or values. Similarly, sometimes the award is published as soon as it is made and sometimes only together with a contract (including only being implicitly covered by the contract). As far as possible, the award should be published at the most granular level (i.e. a given supplier will deliver a given item at a given value) and as soon as it is made.

**Comment by jpmckinney** [comment]
> My understanding is that an OCDS Award object is created when the buyer has finished studying some sort of proposal (bid, contest application, selection phase, etc.) and publishes the result.
> 
> Award: here is what the buyer has decided based on what the "tenderers" (in a broad sense) provided.

👍 

> A supplier is a "tenderer" whose proposal has been accepted by the buyer. I'd consequently go for 3) as long as we refine the definition of "award".
> 
> The difficulty with "after an award has taken place" is that we use the word award in its narrow definition (awarding a contract). But the way the Award object is used in OCDS is broader.

If we replace "after an award has taken place" with "after the decision has taken place" then this clause is just repeating the first clause, unless we draw a fine line between an intention and a decision:

> An entity with which a buyer or a procuring entity intends to conclude a contract. Suppliers are known only after an award decision has taken place.

So, my preference is for (1).

**Update:** Actually we can change (1) a bit to use "decided" instead of "intends", to match the use of "decision" in the award definition:

> > An entity with which a buyer or a procuring entity decided to conclude a contract.

**Comment by ColinMaudry** [comment]
> If we replace "after an award has taken place" with "after the decision has taken place" then this clause is just repeating the first clause, unless we draw a fine line between an intention and a decision:

We can do that, but the relationship between the Award and Supplier is not explicit, as the verb "decide" is not necessarily bound to Award. I see the way a tenderer becomes a supplier in an OCDS process is documented in the guidance for [Award](https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts_buyers_suppliers/?highlight=supplier%20award#award) and [Supplier](https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts_buyers_suppliers/?highlight=supplier%20award#suppliers).

**Comment by jpmckinney** [comment]
Can you quote the sentences from the linked page that you think should inform the definition of supplier?

**Comment by ColinMaudry** [comment]
From the [Award guidance](https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts_buyers_suppliers/#award):

> In OCDS, the Award object is intended to communicate a direct relationship between items, suppliers, and values. It ought to be possible to know, at the award stage, in OCDS data, which items will later be supplied by which suppliers, and what the value of those contracts will be.

From the [contract guidance](https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts_buyers_suppliers/#contract):

> Contracting processes can result in different types of contract between buyers and suppliers

> In OCDS, the Contract object is intended to communicate a legally binding agreement between a buyer and suppliers to provide items. This excludes agreements to set-up a structure through which contracts are later awarded to provide items, for example: a contract to set up or add suppliers to a framework agreement or dynamic purchasing system.

**Comment by jpmckinney** [comment]
@JachymHercher I remember you were going to review that particular guidance in light of this issue and other semantic issues. Does the guidance align with the proposals, or do we need to edit the guidance?

**Comment by JachymHercher** [comment]
Both the Award and Contract guidance are being replaced by the new definitions ([award PR](https://github.com/open-contracting/standard/pull/1175/files#diff-b14b10bfc661f1e53dc8755e219078cb33c957719cbee5d0a92842ad02255fb2) and [contract PR](https://github.com/open-contracting/standard/pull/1208/files#diff-b14b10bfc661f1e53dc8755e219078cb33c957719cbee5d0a92842ad02255fb2), respectively), so no new changes needed on the basis of this issue.
