### ISSUE TITLE
Review additions to open codelists by extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1157]
After review, the new codes can be merged into the standard itself, including:

* [x] ocds_enquiry_extension: [partyRole.csv](https://github.com/open-contracting-extensions/ocds_enquiry_extension/blob/master/codelists/%2BpartyRole.csv)
* [x] ocds_legalBasis_extension: [itemClassificationScheme.csv](https://github.com/open-contracting-extensions/ocds_legalBasis_extension/blob/master/codelists/%2BitemClassificationScheme.csv)
  * #1210
  * https://github.com/open-contracting-extensions/ocds_legalBasis_extension/pull/6
* [x] ocds_organizationClassification_extension: [itemClassificationScheme.csv](https://github.com/open-contracting-extensions/ocds_organizationClassification_extension/blob/master/codelists/%2BitemClassificationScheme.csv) ('COFOG' only)
  * #1218
  * https://github.com/open-contracting-extensions/ocds_organizationClassification_extension/pull/3
* [x] ocds_tariffs_extension: [documentType.csv](https://github.com/open-contracting-extensions/ocds_tariffs_extension/blob/master/codelists/%2BdocumentType.csv)
  * https://github.com/open-contracting/standard/pull/1219
  * https://github.com/open-contracting-extensions/ocds_tariffs_extension/pull/30
* [x] [ocds_eu_extension](https://github.com/open-contracting-extensions/ocds_eu_extension/tree/master/codelists)
  * #1225
  * https://github.com/open-contracting-extensions/ocds_eu_extension/pull/10
* [x] [ocds_ppp_extension](https://github.com/open-contracting-extensions/ocds_ppp_extension/tree/master/codelists)
  * #1243

Included for completeness, but not to be merged:

* ocds_procurementMethodRationaleClassifications_extension: [itemClassificationScheme.csv](https://github.com/open-contracting-extensions/ocds_procurementMethodRationaleClassifications_extension/blob/master/codelists/%2BitemClassificationScheme.csv) (TED-specific)
* ocds_tenderClassification_extension: [itemClassificationScheme.csv](https://github.com/open-contracting-extensions/ocds_tenderClassification_extension/blob/master/codelists/%2BitemClassificationScheme.csv) (TED-specific)

**Comment by ColinMaudry** [comment]
@jpmckinney  When they are merged into the standard, the codelists are also removed from the extensions, right?

**Comment by jpmckinney** [comment]
Yes, they would be removed. We might start tagging releases of extensions, so that OCDS 1.1 users can refer to a version of the extension that contains the codelist.

**Comment by ColinMaudry** [comment]
@jpmckinney What's the benefit of merging the codes from extensions into the standard, but not the schemas?

**Comment by ColinMaudry** [comment]
@jpmckinney May I use this opportunity to sort codes in alphabetical order in the impacted codelists CSVs? I believe it will improve their usability.

**Comment by ColinMaudry** [comment]
I'll do PRs for legalBasis so that we agree on the wording and the procedure, then I'll do the others.

(the case of the enquiry extension was straightforward as it was [already implemented](https://github.com/open-contracting/standard/commit/20c8e216621063f3a64dbfbdaf7799deecf0392b) in the standard)

**Comment by jpmckinney** [comment]
> @jpmckinney May I use this opportunity to sort codes in alphabetical order in the impacted codelists CSVs? I believe it will improve their usability.

Let's create an issue to do this right before the release of OCDS 1.2.0. If we do it now, it could cause unnecessary merge conflicts.

Also, some codelists have a chronological order (status codelists) or other logical order (e.g. method is ordered by degree of openness). The documentType codelist is also sorted by Category (which maybe we want to remove) and Section.

So, in the new issue, we should describe the appropriate order for each codelist.

**Comment by ColinMaudry** [comment]
There's no rush, I'll take care of this issue when we're closer to release 1.2.

**Comment by jpmckinney** [comment]
> @jpmckinney What's the benefit of merging the codes from extensions into the standard, but not the schemas?

For **open** codelists, OCDS can add new codes at any time. As such, the only reason to modify the codelists in extensions is if the OCDS process is too slow. Since we're currently upgrading OCDS, we might as well add the codes to OCDS itself.

Adding fields to the schema, however, always requires a minor version, and requires more discussion. That topic is the subject of #1179.

**Comment by jpmckinney** [comment]
> There's no rush, I'll take care of this issue when we're closer to release 1.2.

I think the addition of codes can be done now. The only thing that should wait is the sorting of codes, which deserves its own issue, since it's not related to this issue.

**Comment by ColinMaudry** [comment]
Steps to have two release branches in extension repos:

- branch 1.1 out of master
- make the default branch 1.1 (instead of master)
- create a new 1.2 branch with the new commits
- delete the master branch

> Requests to the `master` branch will return the default branch (1.1) (GitHub returns the default branch for non-existent branches). Once 1.2 is released, we can change the default branch to 1.2, so that `master` returns that branch instead. In the meantime, we won't disrupt any users expecting the 1.1 version on `master`.

==> https://github.com/open-contracting-extensions/ocds_legalBasis_extension/pull/6#issuecomment-778516885

**Comment by ColinMaudry** [comment]
@jpmckinney Do we add codes from the `documentType.csv` codelist of the ppp extension to the standard? That's[ 44 codes](https://github.com/open-contracting-extensions/ocds_ppp_extension/blob/master/codelists/documentType.csv) and the columns differ from the standard codelist. The tariff codes are in it.

**Comment by jpmckinney** [comment]
That codelist is a bit of a challenge, because it entirely replaces the OCDS codelist (no `+` at the beginning of the filename), so we need to resolve that in the PPPs profile/extension first, for which I'll involve @duncandewhurst.

**Comment by ColinMaudry** [comment]
> That codelist is a bit of a challenge, because it entirely replaces the OCDS codelist (no + at the beginning of the filename), so we need to resolve that in the PPPs profile/extension first, for which I'll involve @duncandewhurst.

Dedicated issue: https://github.com/open-contracting-extensions/public-private-partnerships/issues/253

**Comment by ColinMaudry** [comment]
All the identified open codelists have been processed. OK to close @jpmckinney?
