### ISSUE TITLE
Worked example: Move discussion of contracting process out of unsuccessful tenders

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1159]
The worked example was merged in #1007 based on [this outline](https://docs.google.com/document/d/1bIOMCC1sQjrz2UO5bkc2PcHtTaDA2C1W7jeXRRqGjfE/edit).

However, it spends the first half explaining what a contracting process is.

This content should be moved/removed, since #866 will define a contracting process.

**Comment by JachymHercher** [comment]
This issue should be resolved by https://github.com/open-contracting/standard/pull/1216, which splits the unsuccessful tenders into map/contracting_planning_processes and map/unsuccessful_processes.

**Comment by jpmckinney** [comment]
Agreed. Okay to close after #1216.
