### ISSUE TITLE
Add doctests

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#116]
I'm not sure we're going to have time to do this before the launch, but it would be great to have tests that run against all the markdown that ensure that any json in there is valid.

**Comment by timgdavies** [comment]
@kindly Could you have a look at what tests we have in already, and if there is more we should do on this?

**Comment by kindly** [comment]
We should probably test the [examples](https://github.com/open-contracting/standard/tree/1.0/standard/example) in the docs, to see if they validate.  I think it will too hard to write a parser for markdown to grab the other example jsons out of the docs directly.

**Comment by timgdavies** [comment]
Agreed. All examples should now come from the examples directory anyway.

**Comment by jpmckinney** [comment]
Closing in favor of:

* https://github.com/open-contracting/standard-maintenance-scripts/issues/7
* https://github.com/open-contracting/standard-maintenance-scripts/issues/9
