### ISSUE TITLE
ContactPoint: add an .address field

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard#1164]
As discussed in https://github.com/open-contracting-extensions/european-union/issues/75#issuecomment-728140642, it would be convenient to add an `address` field to the ContactPoint object.

cc @benccs

**Comment by ColinMaudry** [comment]
> Okay, I'm fine with modelling the information service as an organization. (It seems like we might need to relax the constraints around "party" anyway, since a few issues relate to wanting to put more information in that array.)

https://github.com/open-contracting-extensions/european-union/issues/75#issuecomment-761850540

Since we don't use ContactPoint for `informationService`, I guess we don't need to add `address`. OK to close @jpmckinney ?

**Comment by jpmckinney** [comment]
Indeed. Solved!
