### ISSUE TITLE
Contract.items: update description to avoid repeating identical tender items

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1166]
From CRM-6426 and a JSON example from Nuevo Leon @alexramosnj http://si.nl.gob.mx/acceso/DatosAbiertos/DocumentosPublicos/000007/SINL-CPE-007-2019//ocds-7wj9x5-SINL-CPE-007-2019-RCPv001-contract.json

There are some cases where a contracting process only has one award and one contract with the same items as the tender. For those cases, we should update the current contract.items description:

> Note: If the items are the same as the award do not repeat.

to include tender items as well. This is to avoid publishing big JSON files that could be harder to manage.

**Comment by ColinMaudry** [comment]
Related to https://github.com/open-contracting/standard/issues/911.

**Comment by ColinMaudry** [comment]
Current documentation is here: https://standard.open-contracting.org/latest/en/guidance/map/mapping_awards_contracts/

**Comment by ColinMaudry** [comment]
@yolile Do you mean something like this?

> Note: If the items are the same as the award or the tender, do not repeat.

**Comment by yolile** [comment]
Yes! But also mention that this only applies if there is only **one award and one contract** with the same items as the tender

**Comment by ColinMaudry** [comment]
I have read it somewhere, but I don't remember where: @yolile what's wrong with repeating the items?

**Comment by yolile** [comment]
@ColinMaudry I've updated the issue description to clarify, but it is mainly to avoid big JSON files with repeated information.

**Comment by odscjen** [comment]
The current 1.2 description for `contract.items` includes the sentence "If the items contracted are identical to the items awarded, this field should be omitted." which appears to address this issue, can it be closed or is a further change required?

**Comment by jpmckinney** [comment]
I think @yolile means something like:

> If the items contracted are identical to the items awarded and/or the items tendered, this field should be omitted.
