### ISSUE TITLE
Organization classifications worked example: correct JSON example and link to extension

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1168]
[Example 2.2 disclosing data using a local scheme](https://standard.open-contracting.org/latest/en/guidance/map/organization_classifications/#example-2-2-disclosing-data-using-a-local-scheme) uses `parties/details/classifications/name` when it should use `parties/details/classifications/description`.

The link to the organization classification extension in the introductory paragraph links to the Github repo rather than the extension explorer page.

**Comment by ishubham21** [comment]
Hi, I would like to work on fixing this. Could you please assign it to me?

**Comment by jpmckinney** [comment]
Hi @ishubham21, my GitHub notifications somehow got misconfigured. Please feel free to prepare a pull request.

**Comment by Ravf95** [comment]
We can close this issue (see https://github.com/open-contracting/standard/pull/1448 and https://github.com/open-contracting/standard/pull/1299)

**Comment by yolile** [comment]
True! closed by #1448 #1299
