### ISSUE TITLE
Options for publishers interested in modelling machine-readable documents

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#1169]
A partner today mentioned that while the OCDS calls for the publication documents (https://standard.open-contracting.org/latest/en/schema/reference/?highlight=documents#document), it doesn't specify that documents should be published in a machine readable format and requested that this clarification be added.

**Comment by jpmckinney** [comment]
We allow PDF documents, e.g. for the actual contractual documents. Such documents aren't machine-readable.

Which documents, more specifically, would make sense in machine-readable formats?

**Comment by ColinMaudry** [comment]
Machine-readable usually actually means machine-understandable, meaning data in an open serialization: XML, JSON, CSV... ideally in a documented format. A machine can process it and automatically take action based on its content.

HTML, PDF and other text documents are digital documents, they can be opened with software by a "machine", but only a human can understand its content.

**Comment by mgifford** [comment]
We definitely need to move away from PDFs.  This is what the UK Government is proposing for documents - https://www.gov.uk/guidance/publishing-accessible-documents

OpenDocument Format might be good too. Mind you if you have a well structured JSON format and can separate content & presentation then you could have the flexibility to design the formatting of the RFP check out https://jsonresume.org/

**Comment by jpmckinney** [comment]
Merging #1202 here:

Some partners want to model the contents of documents as structured data. While some metadata contained in documents belongs in OCDS (deadlines, criteria, etc.), there is a lot of content in documents that is difficult to standardize (e.g. liability clauses), or for which there is a marginal benefit compared to reading the document itself.

If there is demand, we could add guidance pointing to standards like [OASIS LegalDocumentML](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=legaldocml) (LegalDocML).

**Comment by mgifford** [comment]
I think at the moment the first stage is to highlight to procurement teams that this is an option. I don't think that many are aware that there are alternatives to PDFs to consider. 

Definitely worth taking time to describe the advantages. Accessibility should be one improvement, but the output of OASIS LegalDocumentML (or whatever) would need to be considred. 

Huge opportunities though in terms of transparency. Could be a big win for machine learning with both clients and vendors. 

Much of the metadata currently presented in the HTML document that holds the PDF could just be extracted from the structured RFP document. 

Might be possible to save money by more effectively re-using contracts elements. Would also cut down some of the art of drafting RFPs.

**Comment by jpmckinney** [comment]
Yes, there are quite a few companies like https://cognitivplus.com which extract information from otherwise unstructured documents. In the world of legislative transcripts, I've seen effective use of document styles (in Word, etc.) to add semantics to the content. The same can be done for procurement documents to label elements. However, since document generation is quite distributed, I'm not sure that it's an easy target for standardization.

**Comment by jpmckinney** [comment]
The standards used for procurement documents is outside the scope of OCDS.

As Colin and Mike noted, there are many standards like HTML (see #1292), ODF, PDF, etc. for representing digital documents, that are human readable but not "machine readable".

Without some clear standards to recommend, this issue has no action, so closing.
