### ISSUE TITLE
Standarize Documents descriptions

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1188]
The description of `Planning/Tender/Award/Contract/Contract.Implementation.Documents` is not standard across blocks, see below. 

I would suggest:
- Standardizing the phrasing, e.g. "Documents related to the [block name] (for example [block-related examples]." Glad for second opinions on whether the descriptions should start with "All" and whether we need the examples.
- The standardization consists mainly of:
    - Removing "attachment" (not used anywhere else in the schema, covered by "document") and "reports" (covered by "document").
    - Removing "A list" (We typically don't mention that arrays are lists, even though, beyond documents, this is also done for additional identifiers, milestones and transactions and should perhaps be removed there as well?)
    - "Including any notices" - can be mentioned in the examples section

#### Overview

`Planning.Documents`
_A list of documents related to the planning process._ 

`Tender.Documents`
_All documents and attachments related to the tender, including any notices. See the documentType codelist for details of potential documents to include. Common documents include official legal notices of tender, technical specifications, evaluation criteria, and, as a tender process progresses, clarifications and replies to queries._

 `Award.Documents`
_All documents and attachments related to the award, including any notices._ 

 `Contract.Documents`, 
_All documents and attachments related to the contract, including any notices._

 `Contract.Implementation.Documents`, 
_Documents and reports that are part of the implementation phase e.g. audit and evaluation reports._

**Comment by jpmckinney** [comment]
Yes, I am in favor of adopting a consistent structure and wording, as proposed.

**Comment by jpmckinney** [comment]
Closed by #1229
