### ISSUE TITLE
[MyST] Convert H2 titles to H1

### ISSUE THREAD

**Issue by choldgraf** [open-contracting/standard#1191]
In MyST markdown, you should start your markdown files with an H1 header (aka, with a single `#`). It seems like several of the pages here start with an H2 title instead (`##`). 

For example: https://raw.githubusercontent.com/open-contracting/standard/1.1-dev/docs/getting_started/contracting_process.md

@jpmckinney is there a reason for this? Are they being "included" in other files or something? Any reason we can't change them to `#`?

**Comment by jpmckinney** [comment]
Yes, we can change them to `#`. They are accidental.

For this change, can you use 1.1-dev as the base branch? We can then merge 1.1-dev into 1.2-dev.

**Comment by jpmckinney** [comment]
Done as part of #1213.

**Comment by jpmckinney** [comment]
The reason this was not noticed earlier, is because recommonmark re-sets the heading levels based on hierarchy, rather than based on the number of `#` marks. (MyST-Parser does, too, but it warns if there's misalignment.)
