### ISSUE TITLE
Document type codelist: Update completionCertificate description

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1196]
https://github.com/open-contracting/infrastructure/issues/273 clarifies the distinction between a completion certificate and a payment certificate (OC4IDS introduces a document type code for the latter).

**Proposal**

Update the description of 'completionCertificate' to make the distinction clearer, and:

* align with the structure of the description of 'paymentCertificate' in OC4IDS
* remove the repetition of the code title
* put the description in the present tense

Current description:

> A completion certificate issued by a relevant authority providing evidence that works were completed to a certain level of quality. Completion certificates might only be relevant for particular kinds of contracting processes.

Proposed description:

> A document issued by a relevant authority certifying that the work specified in the contract is complete to a certain level of quality. Completion certificates might only be relevant for particular kinds of contracting processes.

**Comment by yolile** [comment]
closed by #1377
