### ISSUE TITLE
documentType: Check that there are codes for all documents referenced by the UNCITRAL Model Law

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1203]
Model law: https://uncitral.un.org/sites/uncitral.un.org/files/media-documents/uncitral/en/2011-model-law-on-public-procurement-e.pdf

**Comment by yolile** [comment]
From "Article 25. Documentary record of procurement proceedings", I think we could add:

|#| Description in the Law                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Proposed document type                                     |
|-| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
|1| (d) In procurement proceedings in which the procuring entity, in accordance with article 8 of this Law, limits the participation of suppliers or contractors, a statement of the reasons and circumstances relied upon by the procuring entity for imposing such a limit;<br>(e) If the procuring entity uses a method of procurement other than open tendering, a statement of the reasons and circumstances relied upon by the procuring entity to justify the use of such other method;                                                                                                                                                                                                                                                                                                         | procurementMethodDetails/ procurementMethodRationale       |
|2| (f) In the case of procurement by means of an electronic reverse auction or involving an electronic reverse auction as a phase preceding the award of the procurement contract, a statement of the reasons and circumstances relied upon by the procuring entity for the use of the auction and information about the date and time of the opening and closing of the auction;<br>(g) In the case of a framework agreement procedure, a statement of the reasons and circumstances upon which it relied to justify the use of a framework agreement procedure and the type of framework agreement selected;<br>(j) If no standstill period was applied, a statement of the reasons and circumstances relied upon by the procuring entity in deciding not to apply a standstill period; | techniquesDetails, techniquesRationale                     |
|3| (o) If a supplier or contractor is excluded from the procurement proceedings pursuant to article 21 of this Law, a statement to that effect and the reasons and circumstances relied upon by the procuring entity for its decision;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | not sure if already covered by the existing code "bidders" |

**Comment by jpmckinney** [comment]
Seems reasonable! Tagging @JachymHercher for an opinion.

**Comment by JachymHercher** [comment]
1. Looking at Art. 8, I understand Art. 8(1) as for example "because of national security, the supplier must be from my country", and 8(2) as, maybe, "only sheltered workshops can bid". It is closely related to Art. 9, which is about exclusion grounds and selection criteria, which we already have covered by 'eligibilityCriteria' (which should be replaced by 'exclusionGrounds' on the basis of https://github.com/open-contracting/standard/issues/901) and 'evaluationCriteria'. I see two possible approaches:
    a. Recording the information from Art. 8 under 'exclusionGrounds'. 
    b. Introducing a new code with a bit more concrete meaning, e.g. 'otherRequirements' or 'otherParticipationRequirements'. This would correspond to eForms' Other Requirements (BT-705), which contains, most prominently, reservations for sheltered workshops, the need to have a security clearance, etc. However, if we add the code, I think we should also add a field `Tender.otherRequirements` along the existing `exclusionGrounds` and `selectionCriteria` as well as appropriately expand the description of 'evaluationReport' (FYI @ColinMaudry). 

    I guess option b. is better because it's more systematic and better aligned with both UNCITRAL and eForms.
2. Looks good, I'd just split it into three specific codes. Something like 'auctionDetails', 'frameworkAgreementDetails', 'standstillJustification'. (Details vs. justification is based a bit more on my opinion that acutions and frameworks are quite normal, albeit sometimes complicated, things to do and you would probably use the documents to explain how exactly they will work; while avoiding standstill sounds like something very simple that needs a strong justification).  
3.  Hmm, so this essentially is "excluded because he tried to bribe me / has a conflict of interest". In the EU, both of these fall under exclusion grounds (Art. 18(4c) and 18(4e) of Directive 2014/24/EU). If they don't fall there, they could fall under `otherRequirements`. Consequently, there fulfillment could then be documented in 'evaluationReport', so I wouldn't add a new code for this. 

(In the codes' descriptions, we'll need to use our terminology (e.g. "buyer or procuring entity" instead of "procuring entity"), avoid references to the law, etc.)

**Comment by yolile** [comment]
@JachymHercher 1. But what about 

> "(e) If the procuring entity uses a method of procurement other than open tendering, a statement of the reasons and circumstances relied upon by the procuring entity to justify the use of such other method; "

For me, this is about the reason why using eg 'direct' instead of 'open'. For example, in some countries during the pandemic, the entities needed to disclose an official document that allows them to use direct process instead of open, for being in an emergency, eg an official decree or similar. This sounds like a procurementMethodRationale for me

2 and 3 sounds good

**Comment by JachymHercher** [comment]
Ah, sorry, you're right - what I wrote concerns just d), I skipped e). My bad. I think we should deal with them separately.

 For e), 'procurementMethodRationale' (or maybe rather 'procurementMethodJustification'?) sounds good. 

(In the EU, you need a justification just for 'direct', but in earlier legislation you also needed it for 'limited'. I hope the name 'procuremenMethodRationale' doesn't sounds like you need to justify any procedure, but that can be explained in the description and saying something like 'closedProcurementMethodRationale' is probably too heavy.)

**Comment by yolile** [comment]
We already have a `procurementMethodRationale` field, which description is "Rationale for the chosen procurement method. This is especially important to provide a justification in the case of limited tenders or direct awards."

So for the new `procurementMethodRationale` code the description could be "Documentation of the rationale for the chosen procurement method in case it is other than 'open'"

I'm rethinking 2 and trying to find an existing example of some who would actually use these new document types. For the details of the framework agreement and auction, we could use the existing 'biddingDocuments' one, and for 'standstillJustification', I'm not sure if that exists without changing the procurement method. 
With that said, I'm happy to only include `procurementMethodRationale` for now.

**Comment by jpmckinney** [comment]
Regarding other requirements from TED/eForms, we have this extension https://extensions.open-contracting.org/en/extensions/otherRequirements/master/

(d) I agree on 'otherRequirements' (matches the field) or 'otherParticipationRequirements' (is clearer on its own; the `otherRequirements` field occurs in the context of `tender`, where it's clearer that it's about participation).
(e) I think 'procurementMethodRationale' is fine, though the description shouldn't refer to the 'open' code. The description should be understandable without reference to OCDS fields/codes.
(f) (g) As Jachym wrote, these are common techniques, and like Yohanna, I am not sure that governments regularly justify their use (except maybe using the same, boilerplate reasons). I am also not sure who is interested in such reasons. So, I think it's okay to skip these for now. They serve a different purpose than biddingDocuments, though.
(j) I think it needs to be 'noStandstillPeriodJustification'; otherwise, it reads as the justification for having such a period.
(o) I agree that 'evaluationReports' is sufficient.

**Comment by yolile** [comment]
Closed by #1419
