### ISSUE TITLE
"Contract notice" in OCDS vs. EU, warning and consistency

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1206]
In `documentType`, 'contractNotice' is a document on a contract being concluded. By contrast, in the EU, "contract notice" is a document on the contracting procedure being lauched (a "call for competition"). 

1) I'm afraid this might be a common point of confusion for EU OCDS publishers, so I suggest adding a warning note in https://standard.open-contracting.org/profiles/eu/master/en/.  

2) https://standard.open-contracting.org/latest/en/guidance/map/pre-qualification/ gives examples coming from the UK and uses "contract notice" in the EU's sense, not the OCDS sense. (By contrast, everywhere else in the OCDS, i.e. `documentType`, `amendments.description` and https://standard.open-contracting.org/latest/en/guidance/map/amendments/, "contract notice" is used correctly in the OCDS sense.) Perhaps that's clear from context, perhaps we should explain it.

**Comment by jpmckinney** [comment]
I agree that the code is confusing.

In addition to your suggestions, we can change its `Title` to "Contract Signature Notice". Similarly, we might change the title of `awardNotice` to "Contract Award Notice".

**Comment by JachymHercher** [comment]
> In addition to your suggestions, we can change its Title to "Contract Signature Notice". 

(1) Changed and updated in `documentType`, `amendments.description` and the schema.

> Similarly, we might change the title of awardNotice to "Contract Award Notice".

(2) Not changed, because then the 'award notice' would have the same name as the EU's "contract award notice"; but the EU's contract award notice corresponds to "contract signature notice". While this is probably mainly a problem of the EU, I think changing it could cause unnecessary confusion.

____

(3) I updated the descriptions of all the notice codes in `documentType`: 'plannedProcurementNotice', 'tenderNotice', 'awardNotice', 'contractNotice'.

The changes consist mainly of consistency (articles, structure) and adding synonyms. In case of 'awardNotice', I clarified the relationship with 'contractNotice', as it seemed somewhat confusing. Are there actually any jurisdictions that publish "Award notice", where "notice" is in the sense of "being publish in an official gazzette"? 

In 'tenderNotice', I also replaced "submit a request for participation, a bid, or both" with "submit a bid", because we do not distinguish requests from bids anywhere else in the schema (e.g. in `procurementMethod` we only mention bids; in `tenderPeriod` we just talk about "submissions", but not "requests to participate" vs. "bids" vs. "expressions of interest").  

Section | old description | new description
-- | -- | --
'plannedProcurementNotice' | A notice published by the procuring entity regarding their plans for   future procurement, also known as a prior information notice. The procuring   entity can use the notice of planned procurement as a tender notice. | Notice published by the buyer or procuring entity regarding their plans   for future procurement. This notice is called a notice of planned procurement   (for example in the WTO's General Procurement Agreement), a planning notice,   a prior information notice or a periodic indicative notice (for example in   the EU). In some cases, the buyer or procuring entity can use the notice of   planned procurement as a tender notice.
'tenderNotice' | The notice published by the procuring entity inviting interested   suppliers to submit a request for participation, a bid, or both. | Notice published by the buyer or procuring entity inviting interested   suppliers to submit a request for participation, a bid, or both. This notice   is called a tender notice, a notice of intended procurement (for example in   the WTO's General Procurement Agreement), an opportunity notice, a   competition notice or a contract notice (for example in the EU).
'awardNotice' | The formal notice that gives details of the contract award. This can be a   link to a downloadable document, to a web page, or to an official gazette in   which the notice is contained. | Notice published by the buyer or procuring entity giving details of the   contract award. This notice is published after a contract has been awarded   but before it has been signed, for example for the purposes of starting the standstill   period. Once the contract has been signed, a contract signature notice is   typically published.
'contractNotice' | The formal notice that gives details of a contract being signed and valid   to start implementation. This can be a link to a downloadable document, to a   web page, or to an official gazette in which the notice is contained. | Notice published by the buyer or procuring entity giving details of the   contract being concluded (for example signed). This notice is called a contract   signature notice, a result notice or a contract award notice (for example in   the EU), or a contract notice (for example in Australia).

____

(4) I removed the following text from the description of 'awardNotice' and 'contractNotice': 
> ~~This can be a link to a downloadable document, to a web page, or to an official gazette in which the notice is contained.~~  

It isn't specific just to these types of documents and seems unnecessary given the description of `Document`: 

> Links to, or descriptions of, external documents can be attached at various locations within the standard. Documents can be supporting information, formal notices, downloadable forms, or any other kind of resource that ought to be made public as part of full open contracting.

____

(5) I removed the synonyms from https://standard.open-contracting.org/latest/en/guidance/build/change_history/, as they are now part of the definitions and they don't seem particularly linked to the examples at hand:

>  ~~This is also known as *prior information notice*, or *future opportunity notice*.~~

> ~~This is also known as *contract notice* or *opportunity notice*.~~

____

> I'm afraid this might be a common point of confusion for EU OCDS publishers, so I suggest adding a warning hint in https://standard.open-contracting.org/profiles/eu/master/en/.

(6) Since we have renamed the notices and added explanations, and since notice names are not that crucial to EU - OCDS mapping, I have not added a warning note. If we added such a note, it would need to be a broader one on terminological differences between the EU and OCDS, but I think it might end up being too bloated/theoretical. 

___

(7) Should we note somewhere that in OCDS 2.0, we also want to change some of the `documentType` codes, not just the titles?

**Comment by jpmckinney** [comment]
> (2) Not changed, because then the 'award notice' would have the same name as the EU's "contract award notice"; but the EU's contract award notice corresponds to "contract signature notice". While this is probably mainly a problem of the EU, I think changing it could cause unnecessary confusion.

I had thought that EU notices were published before signature. How do suppliers know to complain during the standstill period if the contract is already signed?

> Are there actually any jurisdictions that publish "Award notice", where "notice" is in the sense of "being publish in an official gazzette"?

I don't know - but this will be removed in the PR.

> (7) Should we note somewhere that in OCDS 2.0, we also want to change some of the documentType codes, not just the titles?

No. Prospective statements tend to be forgotten in the documentation (and there's no clear way to decide which ideas go in and which don't). They belong on GitHub instead.

**Comment by JachymHercher** [comment]
> I had thought that EU notices were published before signature. How do suppliers know to complain during the standstill period if the contract is already signed?

That's the Commission's "official" interpretation of the relevant provision ("Not later than 30 days after the conclusion of a contract or of a framework agreement, following the decision to award or conclude it, contracting authorities shall send a contract award notice on the results of the procurement procedure.") and the eForms work with that. I'm aware though that with the current forms, at least in some EU countries, this is not always done accordingly. 

The tenderers are informed directly (and in many countries un-publicly) by the buyer about the outcome of the procedure. ("Contracting authorities shall as soon as possible inform each candidate and tenderer of decisions reached...", see Art. 55 of Directive 2024/24/EU. No mention of notices.)

> No. Prospective statements tend to be forgotten in the documentation (and there's no clear way to decide which ideas go in and which don't). They belong on GitHub instead.

Yep, I meant on github here, e.g. should we tag this issue also 2.0 and leave it open; should I open a placeholder 2.0 issue?

**Comment by jpmckinney** [comment]
2.0 will have a comprehensive review of terms (e.g. "buyer" and "supplier" don't make much sense for sales of state assets), so I prefer to not create new issues at this time, since we would likely want one new issue per group of terms (buyer/supplier, document types, etc.), which will just leave a lot of open issues.
