### ISSUE TITLE
Value fields: remove "total"

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1207]
Value fields in OCDS often use the term "total". I am not sure what it means and I think it might be misleading, e.g. because a "total" value field might be tax-less (see https://github.com/open-contracting/standard/issues/817) or represent just a single award, contract a lot from a contracting process that contains more of them. 

I would suggest replacing: 
- "total estimated value" with "estimated value" in `tender.value` 
- "total value" with "value" in `award.value` and `contract.value`.

**Comment by ColinMaudry** [comment]
I think "estimated" is important, otherwise data publishers may think the field only supports a fixed value.

**Comment by jpmckinney** [comment]
@JachymHercher I support the changes to award.value and contract.value.

For tender.value, did you mean to delete "total" instead of "estimated"?

**Comment by JachymHercher** [comment]
Yes, corrected, sorry.

**Comment by JachymHercher** [comment]
(To avoid unnecessary conflicts, I will create the PR for this issue once https://github.com/open-contracting/standard/pull/1208 is merged (it moves around some value fields).)
