### ISSUE TITLE
Tag: Open the codelist

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1214]
Following from #792 and #1184, we will open the `tag` codelist.

In terms of guidance, we can recommend that a code from the codelist be used wherever possible, but that additional codes can be used based on the publisher's use cases. The additional codes can closely map the notice types (in a notice-based or paper-based system) or the event types (in an electronic records-based system).

**Comment by ColinMaudry** [comment]
@jpmckinney On top of modifying the schema, does it make sense to reflect this change in the documentation?

We could update:

- https://standard.open-contracting.org/latest/en/getting_started/releases_and_records/
- https://standard.open-contracting.org/latest/en/guidance/build/easy_releases/
- https://standard.open-contracting.org/latest/en/schema/reference/

**Comment by jpmckinney** [comment]
What changes would you make to those pages? Getting started is being rewritten (#1239) and guidance on tags is probably too low-level for the primer/getting started section.

**Comment by ColinMaudry** [comment]
In the sections that mention release tags, II would advertise the fact that one can use their own codes to stick to their internal process.

**Comment by jpmckinney** [comment]
> In the sections that mention release tags, II would advertise the fact that one can use their own codes to stick to their internal process.

I don't think tagging is fundamental to the worked example at https://standard.open-contracting.org/latest/en/guidance/build/easy_releases/, so it's not necessary to explain this there.

The new Primer (replacing Getting Started) doesn't discuss tags at all. (The Primer focuses on the concepts needed to understand the rest of the docs. Tags are a more narrow topic that can be addressed later.)

I'll review the PR to see where to include this in the reference section.

**Comment by ColinMaudry** [comment]
With #1244 merged, the only guidance is in reference/codelists.md  and it mentions the fact that one can use their own tags:  https://github.com/open-contracting/standard/pull/1244/files#diff-d6958c79ed9293ec0b969c4db1ebbeeeeb6542bc6d2124e25b01769896e5b7fcR25

I can't think of another section in reference were we could mention this possibility.
