### ISSUE TITLE
Replace "submit a tender" with "submit a bid"

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1230]
In most of OCDS, we use the term "bid", but in (at least) three cases we use "tender" instead: 
- `Method` codelist, 'open', "All interested suppliers can submit a tender."
- `Method` codelist, 'selective', "Only qualified suppliers are invited to submit a tender."
- `partyRole` codelist, 'tenderer', "All entities who submit a tender". 

I suggest replacing "tender" with "bid". Are you aware of any other instances of incorrect use of "tender"? (I searched for "submit a tender" and "a tender" and found the above.)

**Comment by jpmckinney** [comment]
I'm not aware of others, but we can fix them when we find them. Okay to go ahead with these fixes.

**Comment by JachymHercher** [comment]
The PR is ready. Besides the above, I also searched for "tender submission" which returned a couple more occurrences. ("submitting a tender" and "submission of a tender" did not).

**Comment by jpmckinney** [comment]
I've checked for `a tender\b(?! (process|release))|submi(\S+ ){1,10}tender(?!er)|tender submi` across extensions and fixed a few instances.
