### ISSUE TITLE
Download link for schema broken in "Browsing the schema" box

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#1236]
Link to download the schema in the "Browsing the schema" box on the [Release schema page](https://standard.open-contracting.org/latest/en/schema/release/) is currently showing as ```{download}JSON Schema <../../build/current_lang/release-schema.json>```

![image](https://user-images.githubusercontent.com/1897475/109779918-5d2be700-7bfe-11eb-8b95-839d7d7b74e4.png)

**Comment by jpmckinney** [comment]
Fixed in #1221. Example: https://standard.open-contracting.org/staging/eval-rst/en/schema/release/

**Comment by jpmckinney** [comment]
Deployed. FYI @duncandewhurst
