### ISSUE TITLE
Season of Docs wiki page: Contact information

### ISSUE THREAD

**Issue by joelbyronbarker** [open-contracting/standard#1263]
Looking at https://github.com/open-contracting/standard.wiki.git and wanting to follow up to help out, I can not locate directions to reach out and show interest. Can that be added to the doc?

**Comment by jpmckinney** [comment]
Sorry - my GitHub notifications somehow became misconfigured, so I missed this issue. It was added to the doc on April 20. https://github.com/open-contracting/standard/wiki/Google-Season-of-Docs-2021-Project-Ideas/_compare/3109006849721ce10f35551afa295c337eda9aaa...1205c1be417c0c3aea6c4845e45801475532b627
