### ISSUE TITLE
Navigation: Move Governance above History

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1265]
I agree with @JachymHercher's suggestion:

> shouldn't we put Governance above History? The current ordering makes Governance look like an afterthought + I would expect Governance to be a more common use case.

**Comment by ishubham21** [comment]
Hi, I wish to work on this issue. Can you please assign it to me?

**Comment by jpmckinney** [comment]
Done - thank you, @ishubham21 !

**Comment by ishubham21** [comment]
Hi @jpmckinney, can you help me with setting up the project?
I'm referencing this (https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/build.html) document to run it on my local machine, but I'm facing some issues. 
It would be really nice if you could help by providing me some resources to get started.

Problems:
1. Getting an error with the 'make' command as specified in the above document. (Make not defined, I've tried searching StackOverflow and other forums and have installed MinGW) 
2. There is no such folder called build present in the repository. as specifies in the above link. I guess it has something to do with the make command, right?

**Comment by jpmckinney** [comment]
What operating system do you use?

**Comment by ishubham21** [comment]
> What operating system do you use?

Windows 10

**Comment by jpmckinney** [comment]
@pindec If I remember correctly, you are familiar with installing dependencies in a Windows environment?

@ishubham21 For this issue, you can make a pull request with the necessary changes without building the documentation locally. Building the documentation locally would just allow you to preview the results.

**Comment by ishubham21** [comment]
Okay @jpmckinney, I'm doing it. 
Thank you.

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting/standard/pull/1285
