### ISSUE TITLE
Inconsistent guidance on fields without a value

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1267]
https://standard.open-contracting.org/latest/en/schema/reference/#empty-fields:

> Fields that are not being used, or that have no value, should be excluded in their entirety (key and value) from a published file.

https://standard.open-contracting.org/latest/en/guidance/build/merging/#updates-and-deletions

> If you don't have a value to assign to a field, simply omit the field from the JSON, **or assign an empty value like "", [] or {}**.

**Comment by ishubham21** [comment]
Hi, can I work on this issue?

**Comment by jpmckinney** [comment]
@ishubham21 Sorry, my GitHub notifications had become misconfigured. Yes, you can work on this issue.

**Comment by duncandewhurst** [comment]
To clarify, the task is to update the guidance to match the reference.

**Comment by yolile** [comment]
closed by #1375
