### ISSUE TITLE
Add BODS reference to Linked Standards

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1276]
Mention Beneficial Ownership Data Standard in the Linked Standards section and create a worked example about the different approaches to link BODS with OCDS or including BODS data in OCDS with the [Shareholders](https://extensions.open-contracting.org/en/extensions/shareholders/master/) extension

**Comment by Aut0R3V** [comment]
@yolile I'm interested in working on this.

**Comment by jpmckinney** [comment]
Hi @Aut0R3V, if you're looking to contribute to OCDS, please have a look at our [Contributing guide](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/contributing.html). Then, we've tagged some issues as ["quick"](https://github.com/open-contracting/standard/issues?q=is%3Aissue+is%3Aopen+label%3Aquick), which are good first issues. This particular issue is fairly complex (the issue description doesn't capture all the relevant details).
