### ISSUE TITLE
Create a public process to support publishers checking extensions

### ISSUE THREAD

**Issue by mrshll1001** [open-contracting/standard#1291]
Based on [CRM #6624](https://crm.open-contracting.org/issues/6624).

We currently have an [internal process for reviewing extensions](https://docs.google.com/document/d/1bRhVVkuTPXw6acE2opKD-Yj80y0lvAsfAqDjG632nNY/edit) involving both automated and manual quality checks. With some tweaking this process could be made more suitable for the public to support publishers performing the checks on their own local / community extensions.

It was suggested that [this](https://standard.open-contracting.org/latest/en/guidance/map/extensions/#developing-new-extensions) might be a good location in the standard docs to put the guidance, alongside some content that is yet to be integrated into the Extension Explorer.

**Comment by jpmckinney** [comment]
See also #1571, where a lack of guidance on how to publish extensions leads to some extension files only being available via APIs (which requires extra logic in the Data Review Tool and Extension Registry Python Package to handle).

**Comment by jpmckinney** [comment]
Closing in favor of #1571.
