### ISSUE TITLE
Add a recommendation to link to HTML versions of notices

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1292]
Several implementations use OCDS releases to represent notices that are otherwise available as HTML pages. For example, Contracts Finder, Find a Tender Services, AusTender and NSW e-Tendering.

None of the above implementations include a link to the HTML page for the notice in their OCDS data. It is possible to construct the links from the values of fields in OCDS data, but none of the above implementations document how to do this, and it often requires using part of the value of a field. For example, in AusTender you need to get the second part (after the `-`) of the value in `awards/id` and append it to `https://www.tenders.gov.au/Cn/Show/`.

Users who are interested in identifying bidding opportunities need a link back to the HTML version of notices so they can follow up on opportunities they are interested in. For example, by submitting a bid or subscribing for notifications.

Users who are interested in building tools and services that aggregate bidding opportunities need links back to the HTML versions of notices so that their own users can follow up on opportunities they are interested in.

Can we include a recommendation on this somewhere in the standard and/or implementation guidance?

I think the best approach is to add a link to the relevant `documents` array, e.g. `tender/documents` for tender notices, `awards/documents` for award notices etc.

Once agreed, we can also add a check to the data feedback template.

We might also want to look at a recommendation to ensure that whatever references or identifiers that are used in the HTML pages appear in a consistent place in the OCDS data.

**References**

* https://crm.open-contracting.org/issues/7187#note-6 contains a description of how construct the URLs for AusTender, e-Tendering and Contracts Finder.
* https://crm.open-contracting.org/issues/6856#note-36 contains links to feedback reports with more details on matching HTML notices to OCDS releases in Contracts Finder and Find a Tender Service

cc @odscrachel

**Comment by yolile** [comment]
Related to #928 ?

**Comment by duncandewhurst** [comment]
Ah yes, I hadn't seen that issue. As suggested there, I think `documents` make the most sense for this use case.

**Comment by jpmckinney** [comment]
For individual notices, the specific `documents` arrays make sense, since they generally fit those semantics.

For a web page whose semantics are of representing the procedure as a whole, #928 might be more appropriate.

**Comment by jpmckinney** [comment]
The question of how to link documents that span stages came up in #1228.

**Comment by jpmckinney** [comment]
Moving to 1.2 because recommendations are normative.

**Comment by duncandewhurst** [comment]
Noting that https://github.com/open-contracting/standard/issues/928#issuecomment-1181829761 settled on using `tender.documents`.

**Comment by duncandewhurst** [comment]
The descriptions of the various `documents` fields already mention notices as an example:

Path | Description
-- | --
`planning.documents` | Documents related to the planning process (for example, notices, needs assessments and market studies).
`tender.documents` | Documents related to the tender stage (for example, notices, technical specifications, evaluation criteria, questions and clarifications).
`awards.documents` | Documents related to the award (for example, notices, bids, evaluation reports).
`contracts.documents` | Documents related to the contract (for example, notices, signed contracts).

To reduce repetition, I think the [`Documents` sub-schema reference](https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#document) is probably the correct place to add a normative recommendation. Since this issue only applies to certain types of documents, I figure the recommendation should be added after the existing content, which applies to all types of documents. I propose adding the following text:

> If an alternative representation of the data in an OCDS release exists, a link should be provided in the relevant `.documents` array. For example, if the data in an OCDS award release is also available as an HTML page, a link to the HTML page should be provided in `awards.documents`. Links to alternative representations of an entire contracting process should be provided in `tender.documents`.

To address the use case in the issue description, I think that we should also signpost the recommendation in the implementation guidance because I expect that implementers likely won't think of the HTML versions of notices as documents and so might skip over reading the field descriptions and sub-schema reference for documents if they don't otherwise have documents to publish.

We could either add a sub-heading to the [map](https://standard.open-contracting.org/staging/1.2-dev/en/guidance/map/) guidance, e.g. "Link OCDS with alternative representations", or add a new worked example page under [map the hard cases](https://standard.open-contracting.org/staging/1.2-dev/en/guidance/map/#deal-with-the-hard-cases).

I'm leaning towards the former option because I don't think this is a particularly hard case that requires a worked example, rather it is something that implementers just don't think of.

@jpmckinney happy for me to prepare a PR based on the above?

**Comment by jpmckinney** [comment]
Good suggestions! I agree with your assessment of the best places to feature this content.

Edit: Happy for you to prepare a PR.
