### ISSUE TITLE
Linking release reference and worked examples 

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#1297]
It would be helpful for people reading the [release reference](https://standard.open-contracting.org/latest/en/schema/reference/) to link to relevant [worked examples](https://standard.open-contracting.org/latest/en/guidance/map/#mapping-the-hard-cases), just as links are given to relevant extensions.

For example, in the [parties reference](https://standard.open-contracting.org/latest/en/schema/reference/#parties), the `details` field notes that extensions can provide detailed classification of parties, and the party details extensions are linked. It would also be helpful to link to the [organization classifications](https://standard.open-contracting.org/latest/en/guidance/map/organization_classifications/) worked example.

**Comment by jpmckinney** [comment]
We can create a simple Sphinx extension, where we add either Markdown frontmatter or a simple directive on the worked example, and then list the marked pages in the reference section.

Possible implementation inspiration is the example `todolist` directive: https://www.sphinx-doc.org/en/master/development/tutorials/todo.html

**Comment by duncandewhurst** [comment]
At the same time we can make the changes suggested in https://github.com/open-contracting/standard/pull/1434#discussion_r759687627:

> ...we want all content except the extensions list above the jsonschema directive, as otherwise it's easy to miss.)
> 
> I think we might start using a simpler format of "seealso ... How to [do X]" when linking to guidance.

**Comment by jpmckinney** [comment]
> At the same time we can make the changes suggested in [#1434 (comment)](https://github.com/open-contracting/standard/pull/1434#discussion_r759687627):
> 
> > ...we want all content except the extensions list above the jsonschema directive, as otherwise it's easy to miss.)
> > I think we might start using a simpler format of "seealso ... How to [do X]" when linking to guidance.

@yolile Can you create a new issue for this above?

**Comment by yolile** [comment]
Closed by #1466 and created follow up issue #1467
