### ISSUE TITLE
External project identifier

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#130]
From Nepal and Mexico field missions:

"In our analysis, we worked to link tenders and awards with specific donor-funded projects. We were only able to make this connection for a small percentage of contracts. But donors, civil society and other are keen to understand how development funds are used by government agencies to accomplish distinct development goals. If tenders or awards are funded by a donor project, this should be clearly listed in a unique field."

This suggests demand for a 'related project ID'.

Use cases suggest the main requirement for this is at the **Contracting Process** level, so it could sit within the header of a release/record.

Using our current id block could be adapted for this. 

## Worked example (fictional)

A Contracting Process is taking place to deliver a project which is funded by an aid donor. Through the International Aid Transparency Initiative it has an identifier of 'GB-3-ABC-MEX-000065'. The project is also listed in a government register of major projects with ID 'ABC12563' 

```json
{
    "ocid": "abckskgjejslgha-12312521234",
    "relatedID": [
       { 
           "scheme": "http://iatistandard.org/activity-standard/overview/iati-identifier/",
           "id":"GB-3-ABC-MEX-000065",
           "relationship":"fundingProject"
       },
       { 
           "scheme": "http://mexico.gov/major-projects/",
           "id":"ABC12563",
           "relationship":"parentProject"
       },
    ]
}
```

Learning/questions from the worked example:

* Do we need the relationship field (we would need to define an initial list of relationship types here), or can this be inferred from the scheme of the relatedID?
* Should scheme be a URI? Or a codelist value?

**Comment by timgdavies** [comment]
Between relatedProcess (#371) and the budget level ability to refer to an external project (#378) this issue should be addressed.
