### ISSUE TITLE
Deprecate transaction.source

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard#1304]
@jpmckinney `Budget.source` was deprecated in 1.1, but not `Transaction.source`, although they have the same description. Do you know why?

`deprecated.description` for `Budget.source`:

> The budget data source field was intended to link to machine-readable data about the budget for a contracting process, but has been widely mis-used to provide free-text descriptions of budget providers. As a result, it has been removed from version 1.1. budget/uri can be used to provide a link to machine-readable budget information, and budget/description can be used to provide human-readable information on the budget source.

Discussed with in https://github.com/open-contracting/standard/issues/378, but deprecating `Transaction.source` was never mentioned. @duncandewhurst is `Transaction.source` used correctly? That would explain why it's not deprecated.

**Comment by duncandewhurst** [comment]
> Discussed with in #378, but deprecating `Transaction.source` was never mentioned. @duncandewhurst is `Transaction.source` used correctly? That would explain why it's not deprecated.

According to the 1.2 research, `Transaction.source` was only used by one publication: Mexico Jalisco. Unfortunately, that publication lapsed so I can't check its use of the field. I think the reason for not deprecating the field was because we hadn't seen it being widely misused. Even if one publication misused it, we would likely need more evidence of misuse to deprecate it for that reason.

**Comment by jpmckinney** [comment]
`Transaction.source` serves a purpose. An individual transaction might not have a unique URI, but there might still be a dataset that contains the transaction (the `source`). 

`Budget.source`:

> Used to point either to a corresponding Budget Data Package, or to a machine or human-readable source where users can find further information on the budget line item identifiers, or project identifiers, provided here.

`Transaction.source`:

> Used to point either to a corresponding Fiscal Data Package, IATI file, or machine or human-readable source where users can find further information on the budget line item identifiers, or project identifiers, provided here.

The field description doesn't make much sense, but there isn't a good reason to deprecate the field.

I'll change the issue to be about improving the description.

**Comment by duncandewhurst** [comment]
@jpmckinney let me know what you think of the following description:

> A link to a dataset that contains this transaction.

**Comment by jpmckinney** [comment]
> An individual transaction might not have a unique URI, but there might still be a dataset that contains the transaction 

I'm not sure it makes sense to have such a field at this level. It would mean potentially having an identical URL for every transaction. Counter what I said earlier, the field at this level only makes sense if it is unique to the transaction.

However, we don't know any cases where a publisher has such URLs.

We don't typically deprecate fields simply for being unused (in principle, such fields should not be added in the first place). However, I think this field is strangely-defined enough to warrant removal (deprecation).

**Comment by duncandewhurst** [comment]
Sounds good. I suppose a link to a transaction dataset could be included in `contracts.implementation.documents`, if it comes up in the future.

I'll prepare a PR to deprecate the field.
