### ISSUE TITLE
Clarify "globally unique identifiers" example

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#1325]
Two publishers have recently interpreted the [globally unique identifiers](https://standard.open-contracting.org/latest/en/schema/identifiers/#globally-unique-identifiers) worked example that uses "Two government publishers (Town A and Town B)" to mean that each *procuring entity* should have a different OCDS prefix because it refers to town-level publication.

We should update the example to clarify, e.g. to use "Country A" and "Country B" instead of "Town A" and "Town B".

See [CRM#6950](https://crm.open-contracting.org/issues/6950#note-44) for context.

**Comment by jpmckinney** [comment]
Hmm, in some countries, local governments run their own procurements, in which case they would each have prefixes. In other countries, procurement is centralized, and all procurements are reported to/run through a central system, in which case there would only be one prefix in such countries.

We can change the words, but it then might cause local governments in the first scenario to think that prefixes are "country" prefixes, and that they all need to use the same prefix.

So, we might instead need a paragraph or a note to explain that OCID prefixes are related to the publication, not related to the organizations it covers.

Another option is to just say that no publisher needs more than one OCID prefix - which will also solve the original issue.

**Comment by pindec** [comment]
> might cause local governments in the first scenario to think that prefixes are "country" prefixes, and that they all need to use the same prefix

Ah, yes, good point. Should we therefore: 
1. Make the worked example cover both scenarios:
 * clarify that the Town A / Town B example applies where local governments run their own procurements
 * add a brief example to cover the centralised case. 
2. Also note both your points that:
  * OCID prefixes are related to the publication, not related to the organizations it covers; and
  * no publisher needs more than one OCID prefix

**Comment by jpmckinney** [comment]
Instead of adding another example and giving the user more to read, we can update and clarify the current example. The scenario can be more specific, e.g. a named country with a named state/province. We would add a sentence to explain that the country and province operate independently; they do not use a centralized system. Then the rest of the worked example is essentially the same.

Then, when making the point about OCID prefixes being related to the publication, we can maybe clarify that, if the country and province used the same procurement system, then the publication related to that system would use the same prefix for all its processes.

**Comment by duncandewhurst** [comment]
@jpmckinney following the updates to the identifiers reference page, I think this issue can be resolved by adding a paragraph to the [OCID prefix](https://standard.open-contracting.org/staging/1.2-dev/en/schema/identifiers/#ocid-prefix) section along the lines of:

> OCID prefixes are related to a publication, not to the organizations that it covers. For example, if two buyers use the same centralized procurement system, then the publication related to that system would use the same prefix for all its processes. Therefore, no publisher needs more than one OCID prefix.

Sound good?

**Comment by jpmckinney** [comment]
I think it might be clearest to make it about who ought to be registering prefixes. I'm not sure we've ever directly addressed this question – yet somehow, we haven't had any issues arise! Maybe another admonition like "Who can issue OCID prefixes?" but "Who can register an OCID prefix?"

> In principle, anyone can register an OCID prefix. In practice, it is primarily governments and public institutions, as well as businesses and civil society organizations.
>
> There can be multiple government publishers in a jurisdiction. For example, if local governments can procure independently, then each might publish, using its own OCID prefix. On the other hand, if the national government centralizes procurement authority, then it might be the only government to publish in that jurisdiction, using a single OCID prefix.

**Comment by duncandewhurst** [comment]
>  For example, if local governments can procure independently, then each might publish, using its own OCID prefix. On the other hand, if the national government centralizes procurement authority, then it might be the only government to publish in that jurisdiction, using a single OCID prefix.

I think a common case that falls between these two examples is local governments can procure independently (run their own contracting processes) but must either use or report via a centralized system. How about:

>  For example, if local governments can procure ~~independently~~ using their own systems, then each might publish, using its own OCID prefix. On the other hand, if the national government ~~centralizes procurement authority~~ provides a central procurement system, then it might be the only government to publish in that jurisdiction, using a single OCID prefix.

**Comment by jpmckinney** [comment]
Hmm, I don't think we can express the full variety (e.g. a presidential order that requires ministries to share procurement information internally, to be published by an open data team within the president's office). But, I guess we're getting closer in terms of control of procurement -> control of systems -> centralization of data.

> For example, if the national government centralizes data about contracting processes, then it might be the only government to publish in that jurisdiction, using a single OCID prefix. On the other hand, if subnational governments have the authority to procure, control procurement systems, and/or collect procurement data, then they might also publish, using their own OCID prefixes.
