### ISSUE TITLE
Pre-qualification guidance notes

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1342]
In https://standard.open-contracting.org/latest/en/guidance/map/pre-qualification/, one of the notes says 

>The European Union’s restricted procedure, competitive procedure with negotiation, competitive dialog procedure and innovation partnership all permit the use of pre-selection (see Article 65, Directive 2014/24/EU).

while another one says 

> The European Union’s restricted procedure (see Article 28, Directive 2014/24/EU) uses pre-qualification.

I think the former is correct and consequently the latter would be more comprehensive if it said: 

> The European Union’s restricted procedure, competitive procedure with negotiation, competitive dialog and innovation partnership use pre-qualification (see Articles 28-31, Directive 2014/24/EU).

**Comment by jpmckinney** [comment]
+1 Easy fix :)
