### ISSUE TITLE
Field order across award and contract, possibly elsewhere

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1349]
`award` and `contract` have very similarly ordered fields (e.g. they start with `title`, `description`, `status`.) The exception to that pattern are `award.date` (5th position) and `award.contractPeriod` (9th) vs. `contract.Period` (6th) and `contract.dateSigned` (9th). Here, the semantically similar fields (award date and signature date; contract period and period) are in opposite places. For easier navigation and readability, shouldn't we switch the fields in `Contract`? 

The path to these fields would be the same, but I'm still not sure whether this would be a backwards compatible or incompatible change.

Would it make sense to look for similar anomalies also across the rest of OCDS?

**Comment by jpmckinney** [comment]
This change is fine, as it has no impact on the data.

I agree that grouping and ordering fields in a logical order is better - across the whole schema.

**Comment by JachymHercher** [comment]
I skimmed the schema and didn't notice any other ordering issues. I'll prepare the mini-PR.

The only other question I have concerns fields such as `tender.procuringEntity`, `tender.tenderers`, `.buyer`. My take was that now that we have `parties`, the use of these fields could effectively be discouraged, e.g. by putting them at the end of their relevant sections. However, as far as I'm aware they are not intended for deprecation, so I guess we actually don't want to discourage their use?

**Comment by jpmckinney** [comment]
They persist for a few (potential) reasons.

1. Arrays. For an award, we need to be able to point to a supplier – unlike procuring entity and buyer, which can simply be listed in the parties array without ambiguity, as they relate to the entire procedure.
1. Forwards compatibility. An application that understood OCDS 1.0 can accept OCDS 1.1 data and still extract the names and IDs of parties (but not the other fields, which in OCDS 1.1 is moved to the parties array).
1. Flattening behavior. Several design decisions were based on how the data would look when converted to spreadsheet formats, although in my opinion these decisions were based too heavily on how ODS' Flatten Tool works. At any rate, keeping these fields means that there will be columns for the party name and ID in the relevant context (tender, award, etc.). I think the same outcome could have been achieved with an OCDS-specific flattening tool.

Their persistence does create the opportunity for inconsistency across the party fields and the parties array.

**Comment by JachymHercher** [comment]
Ahh, right. Especially 1) is interesting and requires plenty of thinking: similar use cases as for suppliers could probably also be for buyers/procuringEntities that would be buying only some lots (or items?); interaction with lots in general; what happens if there can be multiple `tender` blocks in the future... plenty of fish to fry, thanks.
