### ISSUE TITLE
releaseTag: 'awardAmendment' maybe missing

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1350]
_/ This issue is a detail, definitely not a priority. Noting it down just because I stumbled upon it when thinking about other things. /_

https://standard.open-contracting.org/latest/en/guidance/map/amendments/#contract-amendment explains that amendments to contracts are done via releases with `tag` having the code 'contractAmendment' and using the `Contracts` block. The `Awards` block is not used. 

I'm wondering whether there isn't an exception to this approach: suppliers changing without a new award (e.g. because the supplier changes its name or is acquired by someone). This could be solved by changing the `organization` (e.g. changing the name), or by introducing a new party and changing the `organisationReference` in `award`. I'm not sure which approach is better. If we wanted users to do the latter though, we would need to add an 'awardAmendment' code in `releaseTag` (because this change has legal meaning and thus shouldn't be under 'awardUpdate').

**Comment by jpmckinney** [comment]
I suppose a contract management system would track such changes, but it is less common for a procurement system to do so. (Of course, if the procurement system is end-to-end, then there is no distinction.)

If it is just a name change, then the entity has not changed, and so just the party name (and reference name) should be updated (if at all – the organization identifier would still function as the best way to identify the company).

If there is an acquisition, I suppose it depends on the terms of the contract (e.g. some contracts have clauses to handle the reassignment of the contract). If the buyer needs to re-sign a new contract, then there would have to be a new party, but it would also get messy, e.g. is the old contract cancelled and a new contract added, etc. If the contract is reassigned per the contract's clauses, I don't know that this is necessarily reflected in procurement disclosures.

Anyhow, until we witness a need or demand from implementers, I would not add awardAmendment, as it might truly be covered by contract (sign new contract) plus contractUpdate (cancel old contract) or contractAmendment (change the names on the existing contract).
