### ISSUE TITLE
Worked example: Update framework agreement guidance to use OCDS 1.2 fields

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1358]
@JachymHercher wrote the following in https://github.com/open-contracting/standard/issues/896#issuecomment-888948114

This should only be done once the OCDS 1.1 guidance is finalized in #1301, to avoid merge conflicts between OCDS 1.1 and OCDS 1.2 development.

----

I think the following changes should be made in https://standard.open-contracting.org/latest/en/guidance/map/related_processes/. They are not included in the PR, because I need help with some branching / PRing wizadry: 
- In the "Invitation to participate in the first stage of a framework agreement procedure" section, after "In the tender section, set:" add a bullet with _"`tender.maximumValue` to the maximum value of the framework agreement and / or `tender.value` to the estimated value of the framework agreement (the values may be different e.g. if the budget for the framework agreement contains a reserve in case of an unforseen situation, but the situation is unlikely to occur)"_.
- In a section on the "Award of a framework agreement" (proposed in point 10 of https://github.com/open-contracting/standard/issues/1301#issuecomment-888908989) add
    - _"in the `award` section, set `award.maximumValue` to the maximum value of the framework agreement and / or `award.estimatedValue` to the estimated value of the framework agreement"_. 
    - _"in the `contract` section, set `contract.maximumValue` to the maximum value of the framework agreement and / or `contract.estimatedValue` to the estimated value of the framework agreement"_.
 - (Approach to `award.value` and `contract.value` is already covered by https://github.com/open-contracting/standard/issues/1301#issuecomment-888935699.)

**Comment by duncandewhurst** [comment]
@jpmckinney now that https://github.com/open-contracting/standard/issues/1301 is closed, can a PR be prepared for this issue?

**Comment by jpmckinney** [comment]
Yes!
