### ISSUE TITLE
Add link to data registry after launch

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1366]
For the Primer, we can add it to either:

1. In this paragraph on the Primer landing page as a part of the "other relevant resources."

    > Beyond the Primer, the OCDS provides detailed documentation to guide you in implementing the standard. It provides you with access to the latest authoritative version of the data standard, guidance on data publication, and other relevant resources.

2. in the last paragraph on the "What is OCDS and why use it?" page as a part of the list of who is using OCDS starting with the phrase, "More than 50 countries..."

**Comment by dulceareco** [comment]
Hi @jpmckinney @yolile 

Two questions about this issue just to make sure:

1. _In this paragraph on the Primer landing page as a part of the "other relevant resources."_
Would it be adding [this link](https://data.open-contracting.org/) in [this section](https://standard.open-contracting.org/latest/en/primer/), as a new point under the Data Review Tool item?  

2. _in the last paragraph on the "What is OCDS and why use it?" page as a part of the list of who is using OCDS starting with the phrase, "More than 50 countries..."_
Would it be adding [this link](https://data.open-contracting.org/) in [this section](https://standard.open-contracting.org/latest/en/primer/what), as a new point under the "A free global helpdesk" with a little description of the data registry?

Thanks!

**Comment by yolile** [comment]
Yes, but as the data registry hasn't been launched yet, this issue is not ready to be done.

**Comment by jpmckinney** [comment]
Closed by #1608

Noting that the link was added to the main menu, and to docs/guidance/build/hosting.md, since search results for relevant keywords (ocds data downloads) included that page.
