### ISSUE TITLE
Basic publication criteria (Asessing data quality) orphaned

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1371]
With the release of the primer, it seems like the [Assessing data quality page](https://standard.open-contracting.org/latest/en/guidance/publish/quality//#assessing-data-quality) has been orphaned.

I can still find the page via [a search](https://standard.open-contracting.org/latest/en/search/?q=quality&check_keywords=yes&area=default). However, it doesn't seem to be indexed/linked from anywhere and it renders incorrectly.

The page is referenced from the helpdesk's basic publication criteria feedback template.

**Comment by yolile** [comment]
It is now under Guidance->Publish->Perform final checks->Assessing data quality:
https://standard.open-contracting.org/latest/en/guidance/publish/quality/#assessing-data-quality

(It seems that the link you shared has an extra /, maybe this is why it is not being rendered correctly)

**Comment by duncandewhurst** [comment]
Great, thanks,

The link I shared is the one returned by the search: https://standard.open-contracting.org/latest/en/search/?q=quality&check_keywords=yes&area=default (first result)

It's also the link you get redirected to if you follow the old link to the page: https://standard.open-contracting.org/latest/en/getting_started/quality/#basic-criteria

**Comment by yolile** [comment]
Hmm interesting, maybe there is a bug indeed but in the redirection from the old pages! I will take a look at it tomorrow, thanks for reporting!

**Comment by jpmckinney** [comment]
The redirection from the old URL is fixed. To fix a 404 reported in [this comment](https://docs.google.com/document/d/1fFe_WbIQnrMrvZiHt7_yHroR7ffkns5ypRJvUmcrgHk/edit?disco=AAAANf5eAWY) (caused by the WBG omitting a trailing slash in a PDF at http://www.eprocurementtoolkit.org), I had removed a slash from the pattern, but this then caused double slashes to appear, causing CSS to not load.
