### ISSUE TITLE
Guidance suggestions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1379]
Whilst reviewing the publisher checklist in CRM-3919, I noticed a few areas in which we could improve or add to the implementation guidance:

1. [Split up the work](https://standard.open-contracting.org/latest/en/guidance/map/#split-up-the-work): Rename to **Complete your mapping** or **Document your mapping**. Otherwise, we have a step for completing the technical assessment ([Identify your data sources](https://standard.open-contracting.org/latest/en/guidance/map/#identify-your-data-sources)) but no step for actually completing the field-level and codelist mappings.
2.  [Perform final checks](https://standard.open-contracting.org/latest/en/guidance/publish/#perform-final-checks): Add 'Check that your package metadata conforms to the schema'. Publishers frequently populate the package metadata incorrectly, or forget to update placeholder values, so we should include a prompt here.
3. [Finalize your publication policy](https://standard.open-contracting.org/latest/en/guidance/publish/#finalize-your-publication-policy): Add 'a description of any differences in the contracting processes and fields available via different access methods and formats'. This point was prioritised in the work around the original publisher checklist and is not covered elsewhere in the documentation.

**Comment by yolile** [comment]
Additionally, we have a [Desgin->Build your team](https://standard.open-contracting.org/latest/en/guidance/design/#build-your-team) section, and then a [Map->Involve the right people](https://standard.open-contracting.org/latest/en/guidance/map/#involve-the-right-people) section, do we need both? If so, should the second reference the first?

**Comment by yolile** [comment]
In the [Establish your publication formats and access methods](https://standard.open-contracting.org/latest/en/guidance/build/#establish-your-publication-formats-and-access-methods) section or in the [Determine your system architecture](https://standard.open-contracting.org/latest/en/guidance/build/#determine-your-system-architecture) section, should we add a paragraph like "determine where to publish your data" eg, in an existing gov open data portal, in a brand new page, etc?

**Comment by jpmckinney** [comment]
> Additionally, we have a [Desgin->Build your team](https://standard.open-contracting.org/latest/en/guidance/design/#build-your-team) section, and then a [Map->Involve the right people](https://standard.open-contracting.org/latest/en/guidance/map/#involve-the-right-people) section, do we need both? If so, should the second reference the first?

We need both. Every step involves a different combination of people. We can maybe align the names of the roles (data expert / technical expert, policy expert / procurement expert), but otherwise the sections are fine.

> In the [Establish your publication formats and access methods](https://standard.open-contracting.org/latest/en/guidance/build/#establish-your-publication-formats-and-access-methods) section or in the [Determine your system architecture](https://standard.open-contracting.org/latest/en/guidance/build/#determine-your-system-architecture) section, should we add a paragraph like "determine where to publish your data" eg, in an existing gov open data portal, in a brand new page, etc?

I don't know whether this has been a specific stumbling block - implementers seem to do this task without specific guidance. If there's a problem, we can address it in the documentation; otherwise, it's better to keep the content to the minimum.

**Comment by jpmckinney** [comment]
> 1. [Split up the work](https://standard.open-contracting.org/latest/en/guidance/map/#split-up-the-work): Rename to **Complete your mapping** or **Document your mapping**. Otherwise, we have a step for completing the technical assessment ([Identify your data sources](https://standard.open-contracting.org/latest/en/guidance/map/#identify-your-data-sources)) but no step for actually completing the field-level and codelist mappings.

The first following sentence uses "complete the mapping" so I'll use that as the heading.

> 2. [Perform final checks](https://standard.open-contracting.org/latest/en/guidance/publish/#perform-final-checks): Add 'Check that your package metadata conforms to the schema'. Publishers frequently populate the package metadata incorrectly, or forget to update placeholder values, so we should include a prompt here.

We intend to deprecate all package metadata in 1.2 #1084, so this will be fairly short-lived. My preference is to leave it out.

> 3. [Finalize your publication policy](https://standard.open-contracting.org/latest/en/guidance/publish/#finalize-your-publication-policy): Add 'a description of any differences in the contracting processes and fields available via different access methods and formats'. This point was prioritised in the work around the original publisher checklist and is not covered elsewhere in the documentation.

I'll add this bullet after the format/access method bullet, so that it's in context.
