### ISSUE TITLE
Items beneficiaries: distribution among schools

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1388]
In Paraguay, some municipalities and other entities that tender items using a specific fund called FONACIDE, need to specify in their tender items how much of each item will be for each (and which) school in their localities. 

## Example
For example, in this [tender](https://contrataciones.gov.py/licitaciones/convocatoria/394462-construccion-refaccion-instituciones-educativas-dentro-distrito-capitan-meza-1.html#itemSolicitados), the municipality of Capitan Meza wants to build bathrooms (among other things) for their schools. For the item "Instalaciones sanitarias" in lot number 2, the total available amount is PYG 75.000.000. But they also need to specify: 
- The code of each school will be beneficial with the bathrooms
-  For each school, the total amount that will be investment 
- A list of areas of investment (that comes from a closed code list)

Eg:
- Instalaciones sanitarias
    - School code: ABC
        - amount: PYG 37.500.000
        - areas: infrastructure: bathrooms
    - School code: BCD
        - amount: PYG 37.500.000
        - areas: infrastructure: bathrooms

## Proposal

One option could be to create a local extension that adds an array field to the Item object, a list of Schools, each School object, could have a code, Value, and areas

Another option could somehow reuse the existing [valueBreakdown extension](https://github.com/open-contracting-extensions/ocds_valueBreakdown_extension), and add an object inside the value breakdown list for each school. We will need an additional field for the areas of investment, though.

 cc @rparrapy @micayael

**Comment by jpmckinney** [comment]
This is similar to https://github.com/open-contracting-extensions/public-private-partnerships/issues/235 (and https://github.com/open-contracting/infrastructure/issues/335)

I think a generic `benefits` or `beneficiaries` array might be best, in which the beneficiary objects specify the type of beneficiary (a school), its identifier (the code), the value they benefit by (amount and currency), and then any other classifications (the areas).

**Comment by yolile** [comment]
Makes sense. From the user point of view a single array of `beneficiaries` could be easier to use, as `items` is already an array and with `benefits` we will have 2 more nested arrays, so it could be something like:

```json
{
  "items": {
    "id": "1",
    "description": "Instalaciones sanitarias",
    "quantity": 1,
    "unit": {
      "name": "Unidad Medida Global",
      "id": "GL",
      "value": {
        "amount": 75000000,
        "currency": "PYG"
      }
    },
    "beneficiaries": [
      {
        "identifier": {
          "id": "ABC",
          "scheme": "PY-MEC-INSTITUCIONES-EDUCATIVAS",
          "uri": "https://datos.mec.gov.py/doc/establecimientos/1701006"
        },
        "benefit": {
          "value": {
            "amount": 37500000,
            "currency": "PYG"
          }
        },
        "classification": {
            "scheme": "PY-MEC-FONACIDE-AREA-INVERSION",
            "description": "Infraestructura:sanitarios; Infraestructura:mobiliarios"
        }
      }
    ]
  }
}
```
I'm omitting the "type" for "identifier/scheme"

**Comment by jpmckinney** [comment]
Sounds good. If a single primary classification is expected, then using a singular `classification` object would also make the model simpler.

**Comment by yolile** [comment]
Sadly an array of classifications is expected. I edited the example to also include the URI of the school, as they also have that. We agreed on this model with the DNCP and the extension will be drafted.

**Comment by yolile** [comment]
After testing it with the users and with the flattened version, a singular `classification` object is indeed simpler, so we would use a single object, but we will concatenate the different areas in the `classification.description`, and won't use a `classification.id`

**Comment by rparrapy** [comment]
Extension drafted here: https://gitlab.com/dncp-opendata/ocds_beneficiaries_extension

**Comment by yolile** [comment]
Closing this issue as there is an extension drafted
