### ISSUE TITLE
Inconsistent use of 'supplier' in guidance and codelist

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1398]
'Supplier' is defined as an organization that has already been awarded a contract, both in OCDS 1.1 ("An entity awarded or contracted to provide goods, works or services.", https://standard.open-contracting.org/1.1/en/schema/codelists/#party-role) and in OCDS 1.2 ("An entity with which a buyer or a procuring entity decided to conclude a contract.
", https://github.com/open-contracting/standard/pull/1232). 

However, it is currently sometimes used in the sense of a company (that has not yet submitted a bit, that is submitting a bid). I have found this in the following instances:  
- https://standard.open-contracting.org/1.1/en/schema/codelists/#method (all codes)
- https://standard.open-contracting.org/1.1/en/schema/codelists/#document-type ('tenderNotice')
- https://standard.open-contracting.org/1.1/en/guidance/map/pre-qualification/ (many places)
- https://standard.open-contracting.org/latest/en/guidance/map/buyers_suppliers/#consortia-suppliers (few places)

We should change this to a correct term. There are several options: "potential supplier" (simple, but inelegant), "company" (common, but undefined in `partyRole`), organization (widely used, but too broad), economic operator (popular in the EU, but terribly ugly).

I would suggest replacing it with "potential supplier". It is understandable and concrete, we stick to the terminology defined in `organizationRole`, we don't need to add any new terms.

**Comment by jpmckinney** [comment]
I see you put issues in the 1.1 project, but nothing at all in the Reference section can change in 1.1 without creating a new release, which we are not planning to do. So, in general, prefer the 1.2 project when in doubt :)

**Comment by jpmckinney** [comment]
I agree on "potential supplier". It is inelegant, but clear and simple.

**Comment by JachymHercher** [comment]
The PR is ready. Few notes:
1) Above, we did not consider "potential tenderers". Theoretically, the expression is better than "potential suppliers", because a "potential supplier" is also a tenderer, which is not the intended meaning. At first, I was inclined to stick to "potential supplier" anyway, because I thought "supplier" seemed like less jargon than "tenderer", but on second thought, I think "potential tenderer" might be better. Opinions?  
2) An organization party to a framework agreement is a "supplier", not a "potential supplier". This is in line with the definitions (you are a supplier if there was a decision to conclude a contract, i.e. an award), but might be (very slightly) counter-intuitive, because (i) the supplier might not have been awarded a contract to supply anything yet; (ii) just being qualified/selected in a two-stage procedure, which is some sense comparable to becoming a member of a FA, does not make you a supplier. I think this is ok.

I also changed these details:

3) I removed "awarded" from "awarded supplier", as it is redundant.
4) When spotted in the files I was already changing, I changed "procuring entity" to "buyer or procuring entity". We should search for such cases more broadly, I've noted it in https://github.com/open-contracting/standard/issues/850#issuecomment-923987799.

**Comment by jpmckinney** [comment]
1. I think "potential tenderer" is typically used in the context of a "likely" tenderer ([example definition](https://www.lawinsider.com/dictionary/potential-tenderer)), e.g. where they have joined the process (like purchasing access to bidding documents) but not yet submitted a bid. In other words, "tenderer" implies that there is some reason to believe they might submit a bid. On the other hand, "supplier", in this case, implies that they are a supplier of the goods/services within the broader market, with "potential" clarifying that there is no further relationship with the buyer.
2. Yes, I think these organizations are conventionally referred to as "suppliers" even if they haven't (and might never) supply anything within the FA.

3. Good catch. I used the regex `(?<!\b(different|potential))(?<! (identify|multiple))(?<! single)(?<! (other|these|which))(?<!\b(each|like|more|same|with))(?<!\b(and|for|new|one|the|two))(?<!\b(as|no|of|on|or|to))(?<! a)(?<!,) supplier` (excluding PO files) and the remaining occurrences seem fine.
4. Noted.
