### ISSUE TITLE
Extension: make selectionDetails structured 

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#140]
From Mihaly Fazekas:

> selectionDetails: break down into selection criteria text and selection criteria weight (it is often shown in a table format in Europe). These should be explicit and clearly broken down per selection criteria item. This is crucial for bidders to clearly see what they are evaluated against and it is very useful for the researcher to see corruption risks in subjective evaluation criteria for example.

This is a good suggestion, though I suggest we consider this as a good candidate for an extension (it would need a new object type, and probably new property for structuredSelectionDetails, or selectionDetailBreakdown) and we've not had examples of this in supply side published data yet.

(I.e. a third-party is encouraged to work up a schema definition for this based on existing example data)

**Comment by timgdavies** [comment]
Covered in #36. `selectionDetails` was an earlier property name for the concept picked up in `evaluationCriteria`. Through the features extension we may be able to find a good structured way to capture this information.
