### ISSUE TITLE
Guidance on awards and contracts: when to fill in one and/or the other

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1400]
The section https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts/#id1 starts with a general introduction and then, in the last three paragraphs, covers three different scenarios:

> If the data in the source system relates only to contract awards, then only the `award` section of OCDS ought to be populated, unless the law governing procurement permits no changes between award and signature of a contract, in which case the `contract` section can be populated.

> If the data in the source system relates only to the signed contract and no changes are permitted between the award and signature of a contract, then: 
> * Add an `Award` object to `awards` and a `Contract` object to `contracts`
> * Set `awards.id` and `contracts.id` to the same value
> * Populate the `awards.value`, `awards.contractPeriod` and `awards.items` fields with the initial contract value, period and items respectively
> * If the contract value, period or items are subsequently updated, populate the `contracts.value`, `contracts.period` and `contracts.items` fields with the updated value

> The above approach is also applicable to direct call-offs from framework agreements with multiple suppliers, since the call-off is, conceptually, an award.

Questions: 
1) In the middle paragraph, if they have data just about the signed contract, why should the users populate `awards` and not `contracts`? My reflex would be that if it's about a contract, then put it in `contracts` (as far as you can) (or both `awards` and `contracts`).  
2) In the last paragraph, why would all contracts in a direct call-off be treated the same way as "systems with signed contracts are no changes permitted between the award and the signature of a contract"? My reflex would be to treat an award and a contract within a call-off pretty much the same as any other award and contract. In the EU, there is a difference that contracts within framework agreements are not subject to a (mandatory) standstill period, but that might be different elsewhere; there can be a voluntary standstill period; and the awards and contracts could still be different as a result of amendments. 

    If awards and contracts are the same within call-offs as normally, then I would remove this paragraph and perhaps add a mention of this scenario in the "normal case", see point 4). 

3) The same issue as above is also replicated in https://standard.open-contracting.org/latest/en/guidance/map/related_processes/#add-an-award-contract-and-supplier, as briefly discussed in https://github.com/open-contracting/standard/issues/1301#issuecomment-891176354. 

4) There are no instructions for a scenario "If the data in the source system relates to both the signed contract and the award". 

    I assume this is because this is the "default" situation and thus does not require any treatment in the guidance, it should be obvious from the descriptions of the fields. Is that correct? It might be worth an intro sentence anyway.

5) There are no instructions for a scenario "If the data in the source system relates only to the signed contract and ~~no~~ changes are permitted between the award and signature of a contract

    Isn't this an omission? My guess is that such systems do exist (e.g. "contract registers" in the stricts sense of systems that just contain digitized contracts might not have any information about awards; eForms also don't really worry about awards, but rather about contracts). Furthermore, there are non-obvious instructions to give - along the lines of "i) even though you're just taking information from your contract, in OCDS, you'll need to put some information in `awards` (e.g. `suppliers`;  ii) (?) for fields that are both in `awards` and `contracts` (e.g. `value`, `items`), leave the ones in `awards` empty.

**Comment by jpmckinney** [comment]
1. There needs to be at minimum the `suppliers` in Award, as they can go nowhere else, and the award needs an `id` so that it can be referenced from the contract. I agree that the initial concluded contract's values should also appear in the Contract; we can replace the 3rd bullet with a statement to that effect. Then, we can move the condition "If no changes are permitted between the award and signature of a contract," to a paragraph after the bullets, in which we describe the option to populate initial awarded values.
2. I suggest removing the paragraph, as we have an entire separate page to explain frameworks and call-offs.
3. I'm not sure why we have the contracts section here at all. It is not integral to understanding frameworks. I would suggest just leaving it to parties, tender, and awards. The rules about contracts are the same as for non-FAs. cc @yolile 
4. I think it is clear, but happy to add a sentence to be clearer.
5. See 1. This scenario would have no special-case paragraph; it would only follow the new bullets.

**Comment by JachymHercher** [comment]
> 3. I'm not sure why we have the contracts section here at all. It is not integral to understanding frameworks. I would suggest just leaving it to parties, tender, and awards. The rules about contracts are the same as for non-FAs. cc @yolile

I agree - the rules about FA contracts are the same as for non-FAs. However, since (1) ("initial concluded contract's values should also appear in the Contract") and (4), this means that there _should_ be a mention of contract, no? It is as relevant as mentioning awards. In particular, since we want to give fairly complete instructions of what people should do, it should say what https://github.com/open-contracting/standard/issues/1301#issuecomment-888935699 proposes, no?

**Comment by jpmckinney** [comment]
Yes, if we want a fuller example (fine with me), we can include contracts as you suggest.

**Comment by JachymHercher** [comment]
I've prepared PR https://github.com/open-contracting/standard/pull/1451 which should close this issue. When working on it, I concluded the section can be made much simpler, but quite possibly I misunderstood something. @yolile and @duncandewhurst you might also want to have a look?

List of main changes below, but looking at the PR might in this case be more straightforward. 

___

1) @jpmckinney states in https://github.com/open-contracting/standard/issues/1400#issuecomment-911130527

    > There needs to be **at minimum** the suppliers in Award, as they can go nowhere else, and the award needs an id so that it can be referenced from the contract.

    In the PR, I have interpreted this as, if there is only data about the contract, we should store it in `contracts` and use `awards` only if the field does not exist in `contracts`. In other words, we use it for suppliers (and id), but nothing else. 

2) Removed
3) We'll resolve this in https://github.com/open-contracting/standard/issues/1301. 
4) I've added an intro sentence of 

    > "If the data in the source systems relates: 
    > * to both awards and contracts, then both `awards` and `contracts` ought to be populated."

5) Resolved by 1). 

Additionally, 

6. I would propose to remove the text below, as it seems as an infrequent (?) "hack" of sorts rather than a principle? Essentially, it is an example of "if you know something is true in advance, you can fill it sooner than that thing actually happens"? 

    > If the data relates only to contract awards, then only the `award` section of OCDS ought to be populated. ~~, unless the law governing procurement permits no changes between award and signature of a contract, in which case the `contract` section can be populated.~~

6. I have reorganized the field-level descriptions. In particular I have removed "Populate the `awards.value`, `awards.contractPeriod` and `awards.items`" as they seem as unnecessary examples of "populate `awards`. I have reformulated and moved the general "`Award` objects (within `awards`) and `Contract` objects (within `contracts`) are connected by setting `awards.id` and `contracts.id` to the same value." into a general introductory paragraph, but it might be worth just removing as well.

7. I did not change the sentence below, in a different section of the same document, as I assume that will be the outcome of https://github.com/open-contracting/standard/issues/914#issuecomment-877878615.

    > The model also allows for the possibility that there is a difference between the award and the signed contract, either in value, duration, items or otherwise.

**Comment by duncandewhurst** [comment]
Thanks, @JachymHercher. The changes look good to me.

> I would propose to remove the text below, as it seems as an infrequent (?) "hack" of sorts rather than a principle? Essentially, it is an example of "if you know something is true in advance, you can fill it sooner than that thing actually happens"?

Implementers frequently populate both the awards and contracts sections with the same data even though their data source only contains data about awards. This guidance was originally included in our data feedback template to address a possible reason when that would be OK. For the sake of simplicity, I think it's fine to remove.
