### ISSUE TITLE
schema/merging and reference/build/merging: repeated example, joining

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1402]
The worked example in https://standard.open-contracting.org/latest/en/schema/merging/ is also in https://standard.open-contracting.org/latest/en/guidance/build/merging/#example-1-updates. My reflex is that we do not want to have the same information in multiple places of the standard, as it makes things unnecessary long and might feel confusing.

Shouldn't we remove this example from one of the webpages or, since the guidance page contains little besides the three worked examples, perhaps merge schema/merging into guidance/build/merging?

**Comment by jpmckinney** [comment]
We need to keep schema/merging as it is normative and belongs in the Reference section.

We should instead replace the worked example in schema/merging with:

````
```{seealso}
* Guidance: [Updates and deletions](../guidance/build/merging)
```
````

**Comment by JachymHercher** [comment]
> We should instead replace the worked example in schema/merging with:

That would be better than the current state. 

Still, wouldn't it be best to merge guidance/build/merging into schema/merging? (I accidentally switched the order in my previous post, sorry). Currently, guidance/merging starts by referencing schema/merging (and has essentially just one paragraph of non-example text) and then schema/merging would refer back to guidance/merging for the examples, which sounds unnecessarily complex. In other words, would readers ever want to read the documents separately? If not, let's merge them. 

If we want to make sure readers think about merging when they are going through guidance/build (assuming they read it start to finish or something like that), then we could concentrate just on that. For example, the whole guidance/merging page could just be a link to schema/merging and say "read the normative page on merging and figure out how it works for you". 

(I double-checked whether we include examples in the reference and we do, so that shouldn't be a problem either.)

**Comment by jpmckinney** [comment]
On my screen, each of those pages is 7 screens long (excluding the example within the reference page), and a 14-screen long page is just very long. I'd rather have two well-scoped 7 screen pages.

The two pages have different use cases. The guidance is about how to take advantage of the merging routine to make updates and deletions to data.

The reference page – honestly – no one needs to read, unless they are brave enough to re-implement the merge routine, which is quite complex and easy to do incorrectly.

**Comment by JachymHercher** [comment]
Ok. I've made a mini-PR with the replacement you mention in https://github.com/open-contracting/standard/issues/1402#issuecomment-911109993. (Failing a test though :-(, not sure why.)
