### ISSUE TITLE
Style Guide: Add rules on the use of articles in descriptions

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1406]
If I'm not mistaken, https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/index.html does not give rules on the use of definite/indefinite/no articles in field and code descriptions. The standard seems to use them sometimes inconsistently, so it would be useful to have them.

**Comment by jpmckinney** [comment]
I guess there are two issues: coming up with the rule, and then applying it. What rule do you suggest?

**Comment by jpmckinney** [comment]
Moving to 1.2 since we can't change field and code description without a new release, and no new release is scheduled for 1.1

**Comment by JachymHercher** [comment]
In eForms, articles depend on the data. Specifically: 
- Business groups that only contain other fields have no article (and typically start "Information about...") 
- Fields that can have multiple values start with "A"
- Fields that can only have a single value start with "The", except those that are booleans which start with "Whether".  

We could do it along the same lines for OCDS?

**Comment by jpmckinney** [comment]
For fields with multiple values, I think we currently often use "The" but with a plural noun phrase. However, if the value is an array of objects, then the *object*'s description typically uses "A"/"An". A special case is `tag`, which has weak semantics, so it's "One or more values from the closed releaseTag codelist".

I've made this and other changes in this commit: https://github.com/open-contracting/standard-development-handbook/commit/3fd619f

I figure we will need to add more as we review more descriptions.

**Comment by duncandewhurst** [comment]
Is the task here to go through the field descriptions and apply the updated style guide?

Edit: Related issue https://github.com/open-contracting/standard/issues/850

**Comment by jpmckinney** [comment]
Closing as this issue is now a subset of #850.
