### ISSUE TITLE
Decide what to do about orphaned/unreferenced examples

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1408]
Whilst working on https://github.com/open-contracting/standard/pull/1380 I came across the following JSON files in `docs/examples` which aren't referenced from anywhere in the documentation:

- `extended.json`: added in https://github.com/open-contracting/standard/commit/ff9a3a7d7e7544dd0328a80def0772ff29e6da48 but never referenced. I think we can just remove this file.
- `minimal_updates/award.json`, `minimal_updates/tender.json` and `minimal_updates/tenderUpdate.json`: previously referenced on `releases_and_records.md` as part of guidance on repeating data in releases until orphaned by 616145c3608922a12ffe3c95507ca31e655c3c53.
- `record.json`: previously referenced on `building_blocks.md` to provide examples of building blocks until orphaned by 616145c3608922a12ffe3c95507ca31e655c3c53

**Comment by jpmckinney** [comment]
I think we can remove `minimal_updates` as the point is made in the examples in the Build section, if I remember correctly.

For examples of building blocks, see #1348.

**Comment by yolile** [comment]
`extended.json` and `record.json` were deleted as part of #1475. For the `minimal_updates` examples, I see that we mention the option to repeat everything or just publish the changes at https://standard.open-contracting.org/latest/en/schema/reference/#release-handling, and then in the [Change History](https://standard.open-contracting.org/latest/en/guidance/build/change_history/) worked example, the releases repeat previous information, so the minimal updates are not covered there. I guess we could update that example to use minimal updates instead (or maybe include both, repetition and then minimal updates in the same example?) or write a new one to include that.

**Comment by jpmckinney** [comment]
https://standard.open-contracting.org/latest/en/guidance/build/change_history/ doesn't repeat everything (e.g. the contract release doesn't have a tender section), but it does repeat more than the minimum (which is more realistic, anyway). So, I think it's fine to delete the minimal updates examples.
