### ISSUE TITLE
numberOfBids (Submitted or valid)

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#141]
From Mihaly Fazekas:

> 1.5) Number of bids and number of bidders: do these two fields refer to submitted bids or valid bids. Often bids and bidders are excluded by the issuing authorities for administrative and other reasons (high corruption risk is when many bidders are excluded due to minor issues such as missing page numbers!). I suggest including both as they tell a lot about the tendering process both from efficiency and corruption perspectives.

Would this require four fields overall? 

numberOfBids
numberOfValidBids
numberOfBidders
numberOfValidBidders

Or is there some better way to model this? 

See also #78

**Comment by ekoner** [comment]
Re-opening this issue as Mexico airport have a need to report number of disqualified tenderers as well as numberOfTenderers. This looks similar to the issue raised by Myroslav.

Have invited team to elaborate their use case.

**Comment by timgdavies** [comment]
This is being taken forward in #379
