### ISSUE TITLE
Consortium suppliers, multiple suppliers and supplier share

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#142]
From Mihaly Fazekas:

> 2.1) suppliers: did you make it explicit whether a supplier is a consortia or not and if yes which companies are part of it (the same may go for buyers as they might buy together which is nevertheless much less frequent). In case of multiple companies winning together as a consortia, it is essential to list later on which company won how much. I am not sure if your organisation allows for this and how.

At the moment the Supplier array assumes that all suppliers are legally identified entities, so would require all members of a consortium to be listed. 

It does not currently provide a way to indicate the share that each organisation has in the overall award, although this could be captured to some extent in individual contracts then issued to suppliers against a given award if they are each party to a different contract. 

Suggestions for how best to capture the scenario Mihaly describes? What about when a publisher does not hold details of all the consortium members and so wants to describe the consortium as an entity?

**Comment by timgdavies** [comment]
Continued in #370
