### ISSUE TITLE
Document type codelist: Add a code for early engagement notices

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1425]
The UK Cabinet Office's Contract Finder system includes an early engagement notice, which is described as being:

> used for inviting feedback from industry on early procurement ideas (also known as ‘pre-procurement dialogue)

In the EU this type of activity is known as a preliminary market consultation (Article 40, Directive 2014/24/EU). Other terms for the same type of activity include market engagement and information gathering (https://github.com/open-contracting/standard-development-handbook/issues/278).

The Cabinet Office wants to include a link to the HTML notice from `planning.documents`. The document type codelist lacks a code for this type of notice so they plan to use the code 'planningNotice' in order to align with the 'planning' code in the tender status codelist.

**Proposal**

Add the following code to the document type codelist. The description is based on the EU directive.

Code | Title | Description
-- | -- | --
planningNotice | Planning notice | A notice published by the procuring entity to consult with the market with a view to preparing the procurement and informing suppliers of their procurement plans and requirements. This type of activity is also known as market engagement, early engagement, pre-procurement dialogue and information gathering.

**Comment by jpmckinney** [comment]
Assigning @JachymHercher as he has recently reviewed codes for notices for 1.2.

**Comment by JachymHercher** [comment]
I agree we should add such a document, there is currently nothing equivalent in the [`documentType` codelist](https://standard.open-contracting.org/staging/1.2-dev/en/schema/codelists/). 

______

I wouldn't call it Planning Notice, as I think the term is overloaded/ambiguous/unnecessarily broad. For example:
- 'plannedProcurementNotice' has "planning notice" listed as one the synonyms:
    > Notice published by the buyer or procuring entity regarding their plans for future procurement. This notice is called a notice of planned procurement (for example, in the WTO's General Procurement Agreement), a future opportunity notice, **a planning notice**, a prior information notice or a periodic indicative notice (for example, in the EU). In some cases, the buyer or procuring entity can use the notice of planned procurement as a tender notice.
 
- eForms use "planning form" as the form that is filled in to get a prior information notice, periodic indicative notice, or, hopefully, a prior market consultation notice. (The last should be an "informal" notice, in the sense of not having its use and content directly prescribed by EU legislation but yet be publishable on TED. The contents should be roughly in line with https://github.com/eForms/eForms/issues/81#issuecomment-509251440).


____

Instead, I'd suggest "Consultation notice" (or, alternatively, "Market consultation notice", "Engagement notice", "Market engagement notice"). 

Concerning the description, I'd propose

> A notice published by the **buyer or procuring entity** to consult with the market with ~~a view~~ **the aim** to ~~preparing~~ **prepare** the ~~procurement~~ **contracting process** ~~and informing suppliers of their procurement plans and requirements~~. This type of activity is also ~~known~~ called ~~as~~ market engagement, early engagement, pre-procurement dialogue and information gathering.

Main points: 
- Should we include "informing suppliers of their procurement plans and requirements"? On one hand, I agree this might offen happen; on the other hand, this is mainly the purpose of the 'plannedProcurementNotice'. What makes the 'consultationNotice' different is the consultation, so I'd perhaps just stick to that?
- Tweaks in line with https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/style_guide.html#word-choice and standardizing phrasing with 'plannedProcurementNotice'. 
- (Also, I would propose replacing "a view to" with "the aim of". Probably splitting hairs here, but it seems less idiomatic and thus more understandable for non-native speakers.)

**Comment by duncandewhurst** [comment]
Thanks, @JachymHercher.

> 'plannedProcurementNotice' has "planning notice" listed as one the synonyms:

Good spot! I'm happy with your proposed alternatives (I don't have a preference between them).

For the description, I took the wording from the EU directive, including the part about procurement plans and requirements, but your updates and reasoning sound good to me.

**Comment by jpmckinney** [comment]
Description looks good to me! For code/title, I prefer "marketEngagementNotice" to "marketConsultationNotice".

I don't like "consultationNotice" as one can consult stakeholders, etc, but the description doesn't match that scenario.

**Comment by JachymHercher** [comment]
Great. PR ready. Further changes:
- This type of activity is also called market ~engagement~ _consultation_. (To reflect the change of name.)
- To consult ~with~ the market with the aim... (To avoid repeated "with"`; gramatically _probably_ ok according to a [random article](https://blog.harwardcommunications.com/2012/02/07/how-to-use-the-word-consult/), which I would interpret as our case being able to fall both in scenario 1 and 2.)
