### ISSUE TITLE
Add guidance on linking releases from different publications

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1430]
We should provide guidance since this issue has come up a couple of times recently

* In the UK, where Contracts Finder, Find a Tender Service and Public Contracts Scotland all publish releases about the same contracting processes (see CRM-7250, CRM-7262, CRM-7304 and CRM-7512)
* In Colombia, where Colombia Compra and ANI publish releases about the same contracting processes (see CRM-7263)

Unless the publications use consistent mappings, reusing the same OCIDs across publications could result in unpredictable and nonsensical results. For example, unless they use an identical approach to assigning local identifiers to objects in arrays, then awards, contracts etc. will overwrite and/or duplicate each other in nonsensical ways.

Roughly, the guidance can be:

* If the publications are distinct (e.g. they cover disjoint sets of fields, different stages, different procedure types etc.) then they should use the same OCID so that users can merge releases.
* If the publications use a consistent mapping, including the approach to assigning local identifiers to objects in arrays, they should use the same OCID so that users can merge releases.
* If the publications don't use a consistent mapping, they should use the `Links` field (added in https://github.com/open-contracting/standard/issues/928) so that users can identify that contracting processes are the same, whilst avoiding incorrect merging of releases.

We can also include some of the content from CRM-7250 around the governance and technical considerations for coordinating publications.

cc @yolile

**Comment by jpmckinney** [comment]
Yes, the discussion in the CRM could serve as a worked example.

**Comment by yolile** [comment]
Thanks, Duncan for opening this issue. 

> If the publications don't use a consistent mapping, they should use the Links field

With the "prev" link type, I assume?

**Comment by duncandewhurst** [comment]
Yes, if linking to an individual release I think that would be most appropriate.
