### ISSUE TITLE
Clean up examples directory to follow consistent structure

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1435]
All related files should be in a directory, with no unrelated files.

Once organized, the approach should be documented in the handbook.

Currently, some files like `unsuccessful-tender*.json` use a filename prefix instead of being organized into a directory.

Similarly, the `tender.json`, `award.json`, etc. files are related, but have neither a prefix nor a specific directory.

Related: #1408

**Comment by yolile** [comment]
I think we can follow the same pattern that we have now for [images](https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/style_guide.html#images), that's it:

- Use a descriptive, lower-case filename, with underscores between words.

- Store the exported version in the _docs/examples_ directory in the standard’s repository. Create a sub-directory to group related _examples_, as needed, rather than using a common prefix to the filename.

**Comment by jpmckinney** [comment]
Sounds good!

**Comment by yolile** [comment]
I'm not sure about what to do with some examples used in multiple places. For example, `merging/versioned.json `is used in `schema/merging.md`, `records_reference.md` and `build/merging.md`. Should we place them in the root example folder instead of in the folder of a particular section?

**Comment by yolile** [comment]
Or maybe duplicate them so each corresponds to their own example/reference?

**Comment by yolile** [comment]
The current `examples/merging` directory contains examples used by `build/merging` and `schema/merging.` The title of `build/merging` is actually "Updates and deletions" so I will change `build/merging.md` to `build/updates_deletions.md` as part of the PR and create a separated `examples/updates_deletions` directory and separate its examples here.

**Comment by jpmckinney** [comment]
We shouldn't rename Markdown files as it causes links to break. We can set up redirects in Apache, but it's an unnecessary extra step.

I think it's good for pages to share the same example files. That way, when we need to change the example, we don't need to duplicate edits. We can just name the directory according to the theme, rather than matching the page name.

**Comment by yolile** [comment]
Then, the examples from https://standard.open-contracting.org/latest/en/guidance/map/amendments/ are in the `_static/json/amendments` folder. However, only one of them is downloadable (`amendments-tender-example.json`). Should we move the non-downloadable ones into the `docs/examples` directory? We could also remove the Hint about downloading the file and move all the files into the regular directory. Also, there is one file that is from that example that currently is at `docs/examples`: `amendments-contract-notice.csv`

**Comment by yolile** [comment]
Edit: the three of them can be downloaded. However, as this is the only place where this feature is available I'm still wondering if we should keep the examples as downloadables or not.

**Comment by jpmckinney** [comment]
We should move all example files to the `examples` hierarchy. To allow downloads, we just use the download role, e.g.:

```
{download}`link text <path/to/file>`
```

Or we can do it in Markdown:

```
[link text](path/to/file)
```

See https://myst-parser.readthedocs.io/en/latest/syntax/syntax.html#markdown-links-and-referencing
