### ISSUE TITLE
Subcontracting Information

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#144]
Subcontracting has been raised in a number of items of feedback, and is discussed also in #130.

> subcontracting: I haven't seen anything on subcontracting. It is a mayor way for hiding money, corruption, and collusion. I would consider adding fields on it.

The current suggestions point towards including subcontracting information in the 'implementation/performance' phase, with an option to list:

* Subcontracts
* The ID of the party subcontracted
* The value of the subcontract
* The OCID of the subcontract

Given the amount of work to do on this, I would suggest it is for after 1.0 RC, but open to discussion....

**Comment by timgdavies** [comment]
Note that the approach proposed in #72 [here](https://github.com/open-contracting/standard/issues/72#issuecomment-139874773) could be adapted to also work for pointing at subcontracts.

**Comment by duncandewhurst** [comment]
The National Council for Voluntary Organisations raised a question to the helpdesk regarding support for subcontracting (specifically payments to subcontractors) in OCDS and made the following comment:

"charities (and SMEs more widely) increasingly deliver public services as sub-contractors so the availability of payment data with unique identifiers etc is crucial. I’d like to better understand to what extent the implementation of the OCDS would address this."

**Comment by timgdavies** [comment]
Updated EU forms may capture list of known subcontractors in an award release. 

When their are lots, it is important to know which lot has been subcontracted to which subcontractor

**Comment by duncandewhurst** [comment]
This is continued in #371
