### ISSUE TITLE
`Tender`: add `mainProcurementCategoryDetails` field

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1445]
We have a `*details` field for almost all of our codelists to allow the publisher to disclose their local name of a particular codelist value in the standard. However, we don't have one for the `mainProcurementCategory`. Paraguay developed an extension for including that field in https://gitlab.com/dncp-opendata/ocds_mainProcurementCategoryDetails_extension however, we should consider adding it to the standard itself.  

We have the [Tender classification extension](https://extensions.open-contracting.org/en/extensions/tenderClassification/master/), but I think that one is more appropriate for when there is a classification eg CPV, etc, but if the text is just a free text or an internal codelist, maybe having a simple free text field is better.

**Comment by jpmckinney** [comment]
Hmm, isn't this what `additionalProcurementCategories` can be used for? For example, the extendedProcurementCategory codelist already contains 'consultingServices', which is a subset of 'services'. I suspect any local category would be a subset of the big ones ('goods', 'works', 'services').

**Comment by yolile** [comment]
Aha, but that is a codelist, not a free text field. For example, in Paraguay the existing values are:

- Food products,
- Agricultural and forestry goods and inputs,
- Machinery, Equipment and Major Tools
- Computer, office, educational, printing, communication and signaling equipment, accessories and programs
- Military and Security Equipment. Security Service
- Consultancies, Advisors and Investigations. Investment studies and projects,
- Publicity and propaganda,
- Ceremonial, gastronomic and funeral services,
- Textiles, clothing and footwear,
- Cleaning elements and supplies,
- Construction, Restoration, Reconstruction or Remodeling and Repair of Real Estate,
- Cleaning Services, Maintenance and minor and major repairs of Installations, Machinery and Vehicles,
- Trainings,
- Insurance,
- Fuels and lubricants,
- Minerals,
- Tickets and Transportation,
- Technical services,
- Kitchen and dining utensils, Porcelain Products, glass and earthenware,
- Chemical products,
-  Electrical, metallic and non-metallic materials and supplies, Plastics, rubbers. Spare parts, tools, cameras and covers.,
- Acquisition and Location of real estate. Furniture rental,
- Office supplies, Paper and cardboard products and printed matter,
- Medical and Laboratory Equipment, Products and Instruments. Health care services,
- Furniture and fixtures

They are used as the main category of the tender, so the potential bidders can subscribe to a specific category and get notifications when a new tender of that category is open, etc. However, maybe the now existing [tender classification extension](https://extensions.open-contracting.org/en/extensions/tenderClassification/master/) could be used for this use case.

**Comment by jpmckinney** [comment]
I think a list of 25+ items is no longer a "main category". I agree that tender classification is more appropriate (where codes like CPV can be used to match these same types of items). If a publisher uses their own codelist, they can use a scheme prefixed with the country code like `PY-`.
