### ISSUE TITLE
Rename and clarify Guidance/Map/Amendments

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1446]
Looking at https://standard.open-contracting.org/1.1/en/guidance/map/amendments/, I have two suggestions:

1) Shouldn't it be renamed to Updates and amendments, since it deals with both and these are the terms used in `releaseTag`? 
2) When publishing updates, different eProcurement systems have different approaches to what should be published when amending information: (i) just the amendment (i.e. just the new information) or (ii) unamended information and the amendment (i.e. everything that is still valid after the amendment). According to point (2) in https://github.com/open-contracting/standard/issues/1160#issuecomment-970610262, both approaches are acceptable in OCDS. Shouldn't we state this explicitly in the guidance? 

    Currently, the closest we get to this is the second bullet of https://standard.open-contracting.org/1.1/en/guidance/map/amendments/#record, but it is within a worked example and refers only to the approach for amendments, not updates. The update example itself follows approach (ii).

**Comment by jpmckinney** [comment]
1. Sound good!
2. Yes, this can be stated explicitly for clarity.
