### ISSUE TITLE
Feedback to Draft Bidding Documents

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1447]
The Digital Agency for Public Innovation (ADIP) of Mexico City is developing a module for obtaining feedback on procurement processes (the “Draft Bidding Documents Module”) (Pre Bases in Spanish) prior to the formal start of a contracting procedure.

Through this tool, interested parties will be able to propose modifications or clarifications to the draft bidding documents and have the opportunity to bring their suggestions about the best way to carry out the tender and thus define the best terms and conditions of the technical specifications. Then, the procuring entity can decide to change the technical specifications or not.

The city is interested in measuring if the processes are more efficient after using the tool (eg having fewer enquiries during the actual tender stage, more interested bidders, etc). For doing that, the city wants to disclose, as part of their OCDS Implementation: 
- The max date for submitting enquires
- If the following tender used this new module
- The general statistics of the use of the module, eg: number of received questions, suggestions, etc.

## Modeling Proposal
In OCDS anything that comes before the tender process is considered a planning process. Therefore, the information related to this new module should be part of the planning process. The modeling proposal is to:
- Create a "planningUpdate" release using the same ocid as the prior planning release
- Include the max date for submitting enquires as a `planning.milestone` and use a custom milestone code to identify that the milestone is related to the new module
- Include the process statistics at the process level using this existing [extension](https://github.com/sdd1982/processStatistics)
- Set the `tender.status` to "planning" and include any planned information about the tender eg the expected tender procurement method and procuring entity.
- If the OCDS 1.2 approach is followed, then if there is a tender, relate that tender with the planning process using the `relatedProcesses` array, with  "planning" as the type and also a custom one, for example, "prebases" to easily identify that the "prebases" module was used prior that tender.

If we see that other publishers have similar needs to this, we can consider creating a worked example to include this into the standard documentation.

cc @SantiShalom @dramirezc511

**Comment by jpmckinney** [comment]
Thank you for documenting the proposed model.

Closing as the issue has not garnered additional interest in a couple years.
