### ISSUE TITLE
Codelists for unitOfMeasure

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#145]
At the moment we allow a string for ```unitOfMeasure```. We should move towards a recommended codelist for this. 

[This thread](https://groups.google.com/forum/#!topic/publishing-statistical-data/gMojBEtvHqQ) provides a good summary of the options, which include:

* [UCUM](http://unitsofmeasure.org/) - very comprehensive, but license terms are slightly restrictive (e.g. from quick interpretation I think it makes it impossible to locally extend should a unit required not be covered - although this is unlikely given comprehensive nature) 
* [UN/CEFACT Recommendation 20](http://www.unece.org/cefact/recommendations/rec20en.htm) - providing detailed spreadsheet, and potentially already in use in trading contexts.
* [NASA QUDT Unit Ontology](http://www.qudt.org/qudt/owl/1.0.0/unit/index.html) - a smaller set of properties, but seems to include major ones, and under a Creative Commons license. 

Ideal approach to work out what codelists might be valid here would be to go to our existing data and see if any existing codelists are in use, or to check if there are units of measure in use in existing data which will not map well to one or more of these lists.

**Comment by ekoner** [comment]
Prozorro are using Recommendation N°. 20 - ready for evaluation.

**Comment by akuckartz** [comment]
I would prefer links to `skos:Concept`s instead of strings.

**Comment by akuckartz** [comment]
... but the QUDT ontology might be even better.

**Comment by ekoner** [comment]
Links to:
1. QUDT ontology http://www.qudt.org/
2. SKOS primer https://www.w3.org/TR/skos-primer/

**Comment by timgdavies** [comment]
A full proposal is now given in #366
