### ISSUE TITLE
Add awards.datePublished field

### ISSUE THREAD

**Issue by Ben-Hickling** [open-contracting/standard#1456]
Branching off from the discussion on adding a `tender.datePublished` field (#892), the UK also has a need to add an `awards.datePublished` field.

This will capture the date that the award was published. We will create a new extension if necessary. This will allow this information to be included in awardUpdate releases where it wouldn't be otherwise. We need to cater for analysis tools that only hold the latest release for each procurement (so the awardUpdate overwrites the award, for example).

**Comment by jpmckinney** [comment]
Rephrasing Duncan's comment: https://github.com/open-contracting/standard/issues/892#issuecomment-557968381

The PhilGEPS data also includes a published date for the award notice.

One use case is understanding how timely publication of the award notice was (after the actual date of the award).

**Comment by jpmckinney** [comment]
#261 discusses two options:

> (1) Publishing releases & records 
> (2) Including a document with a `documentType` of `tenderNotice` and with a `publishedDate`. 

(1) isn't great for users that only use the compiled release (most users). (2) would work, but a document with only metadata (`documentType` and `publishedDate`) and no document is kind of weird and confusing.

So, I think it makes sense to add this field.
