### ISSUE TITLE
`documentType`: clarify 'evaluationCriteria' and 'evaluationReports', add new codes

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1463]
In `Tender`, we have fields for `exclusionGrounds`, `selectionCriteria` and `awardCriteria`. 

In `documentType`, we have codes for 'exclusionGrounds', 'selectionCriteria' and 'evaluationCriteria' as well as 'evaluationReports' with the last two being described as: 

> Documentation on how bids will be evaluated.

> Documentation on the evaluation of the bids and the application of the evaluation criteria, including the justification for the award.

The semantics of "evaluation criteria/reports" is ambiguous: is it just another term for award criteria or is it an umbrella term? Do we have an idea of what use is most common or could we have a look into the data as @pindec did in https://github.com/open-contracting/standard/issues/901#issuecomment-700059533? 

My impression, based on a quick search, is that "evaluation reports about award criteria" is more common, but "evaluation reports about all criteria" also exists. (Random [UK](https://councillors.herefordshire.gov.uk/documents/s50046023/001%20Appendix%202%20Short%20breaks%20Market%20Support%20Tender_Evaluation_article_84.pdf), [AU](https://www.hpw.qld.gov.au/__data/assets/pdf_file/0018/3348/procurementguideevaluatingoffers.pdf) and most [CZ](https://www.google.com/search?q=P%C3%8DSEMN%C3%81+ZPR%C3%81VA+O+HODNOCEN%C3%8D+NAB%C3%8DDEK) evaluation reports do the former, but a [PK](https://eproc.punjab.gov.pk/EvaluationReport/50485049/4950/2212202110072800316370.pdf) and a few CZ do the latter.)

If we wanted to cater to both uses, then I would propose:
1. Clarifying the meaning of 'evaluationCriteria' and 'evaluationReport', probably in the direction of an umbrella term. 
2. Adding a code for 'awardCriteria' to complement the existing 'exclusionGrounds' and 'selectionCriteria'.
3. ~Add codes for 'exclusionSelectionCriteriaReport' and 'awardCriteriaReprort' (and possibly also for 'economicSelectionCriteriaReport' and 'technicalSelectionCriteriaReport').~

**Comment by jpmckinney** [comment]
'evaluationCriteria' is "here is how we **will** evaluate you". (ex-ante) It is the same as award criteria. It would have been better to be consistent, but at this stage it is preferable to not deprecate a code just because its name is badly chosen.

'evaluationReport' is "here is how we **did** evaluate you". (ex-post)

I do not see much evidence for sub-types of evaluation reports. The examples you linked to do not correspond to the sub-types you list (reports for exclusion grounds, economic selection criteria, etc.)

**Comment by JachymHercher** [comment]
The difference between 'evaluationCriteria' and 'evaluationReport' is clear - I list both of them here just because changes concerning the scope of "evaluation" concern both.

Concerning deprecation, I guess that's not strictly necessary - clarification and addition may be enough.

 Indeed, the examples are only about "evaluation reports about award criteria" and "evaluation reports about all criteria". However, if award criteria have their separate reports, then selection criteria presumably also do have them (as they are recorded _somewhere_), no? I'll look around for examples.

**Comment by JachymHercher** [comment]
So I did a bit more research and realized I overlooked an important part of the story: Art. 84 of Directive 2014/24/EU ("Individual reports on procedures for the award of contracts") actually prescribes what a summary report for a procurement procedure should contain. In particular, it mentions "results of the qualitative selection" and "reasons why its tender was selected" which should correspond to exclusion grounds/selection criteria and award criteria, respectively. In Czechia, this paragraph is transposed into national law practically verbatim (cf. §217 of ZZVZ, the Czech procurement law) and corresponds to the information published in practice.

Anecdotally, the reason why these "overall" reports might look as actually just dealing with award criteria is that meeting exclusion grounds / selection criteria is much more banal. In particular, since it is fairly predictable whether a company will meet them or not, their main impact is that companies that don't meet them don't even bid, which can be summarized with a laconic "All tenderers met all selection criteria". (This might particularly be the case in countries with a lower tradition of verifying evidence that companies submit with their offer.) 

Based on the above, I have removed suggestion 3 from the first post here (@jpmckinney), since even the "award criteria reports" seem to rather be "all criteria reports... with almost all the emphasis on award criteria". I think 1) would still be useful; 2) probably also.

**Comment by jpmckinney** [comment]
I'm happy to go with (1). For (2), isn't 'awardCriteria' going to be the same as the existing 'evaluationCriteria'?

**Comment by JachymHercher** [comment]
Well, there are several options, see below. (I have a slight preference for 3, but I don't have a feel for how much it would disturb existing OCDS practice).

| # |                                                                                                                                                                                                                                  Approach |                                                              Pro |                                                                                                              Con | Consequence                   |
|--|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|-------------------------------|
| 1 | Clarify that "evaluation" in 'evaluationCriteria' concerns just award criteria (as you mention in https://github.com/open-contracting/standard/issues/1463#issuecomment-999734728), while in 'evaluationReport' it concerns all criteria (as seems to be the general approach according to the law). |                             We stick with established OCDS usage. | We have a discrepancy between 'evaluationCriteria' and 'evaluationReport' concerning the meaning of "evaluation". | We don't need 'awardCriteria'. |
| 2 |                                                                                                                                           Clarify that "evaluation" in 'evaluationCriteria' and 'evaluationReport' concerns just award criteria. | We stick with established OCDS usage and don't have a discrepancy. |                                      The definition of 'evaluationReport' doesn't quite fit with the law. | We don't need 'awardCriteria'. |
| 3 |                                                                                                                                  Clarify that "evaluation" in 'evaluationCriteria' and 'evaluationReport' concerns all types of criteria. |                                                      Consistency |                                                                           A break with established usage in OCDS. | We need 'awardCriteria'.       |

**Comment by jpmckinney** [comment]
Thanks for explaining! Let's go with 3 and explain in the deprecation note the inconsistency in the word "evaluation".

**Comment by JachymHercher** [comment]
I've prepared a [PR](https://github.com/open-contracting/standard/pull/1508). (Note: I don't think we need to deprecate any codes). 

1. Clarified codes:

|                    | Old                                                                                                                                    | New                                                                                                                                    |
|--------------------|----------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| evaluationCriteria | Documentation on how bids will be evaluated.                                                                                           | Documentation on how bids will be evaluated. This includes exclusion grounds, selection criteria and award criteria.                   |
| evaluationReports  | Documentation on the evaluation of the bids and the application of the evaluation criteria, including the justification for the award. | Documentation on the evaluation of the bids. This includes the evaluation of exclusion grounds, selection criteria and award criteria. |

2. New code

`tender,awardCriteria,Award criteria,Documentation that describes the award criteria used to select the winning bid. `

(Additionally, foreshadowing https://github.com/open-contracting/standard/issues/1198, I've also slightly reordered the codes in question, so that they are chronologically/thematically close to each other.)
