### ISSUE TITLE
Documentation on updating final value and completion date

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#147]
From Mihaly:

> I would recommend introducing 'double accounting' for the most crucial bits of information prone to error and corruption. Final value and completion date are two obvious candidates. So having them visibly there rather than implicitly among transactions and milestones makes hiding more difficult in addition to allowing for cross-checking records.

**Comment by timgdavies** [comment]
This should be worked up as a proposal for new fields in the 1.1 upgrade process.

**Comment by timgdavies** [comment]
Upon reviewing this, I don't think any field updates are required. 

The release and records model means that publishers should provide an updated release at the end of a process, updating the `contract.value` and `contract.period` for example.

We may want to improve worked examples and documentation on this in 1.1 or associated materials.
