### ISSUE TITLE
Release schema: Set omitWhenMerged = true on publisher field

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1483]
https://github.com/open-contracting/standard/pull/1376 adds a release-level `publisher` field. However, `omitWhenMerged` is not set so in a compiled release the publisher of the most recent release will always appear as the publisher.

**Comment by duncandewhurst** [comment]
Ah, I see there is a different approach in a [PR](https://github.com/CompraNet/ocds_releasePublisher_extension/pull/1) on Compranet's releasePublisher extension: instead of `publisher` make `publishers` an array, so that the compiled release will have a list of all the publishers.

One challenge to that approach is that if a one publisher sets `publishers` and another doesn't, then in the compiled release it will look like there is only one publisher.

As such, I think sticking to a single `publisher` field and setting `omitWhenMerged` to `true` is a better solution. Sound good?

**Comment by jpmckinney** [comment]
Yes, I think `publisher` is only useful at release-level, but perhaps @yolile remembers some discussion about making it an array?

**Comment by yolile** [comment]
The specific need was to determine who published a release from the compiled release without checking the original releases. But as Duncan mentioned, following the array approach could lead to incomplete information in the compiled release anyway (when one publisher doesn't use the field) (unless we make the field required, but we can't do that). So yes, we should set `omitWhenMerged` to `True` and for compiled releases, the users will need to check the original releases. (unless we add the publisher field to the linked releases as well?)

**Comment by jpmckinney** [comment]
I'm not sure that many publishers are using linked releases – and when they do, they are typically linking to their own releases, rather than third-party releases.

**Comment by duncandewhurst** [comment]
Thanks, both. I've opened an issue on CompraNet's extension. @yolile do you want to close your PR?

**Comment by yolile** [comment]
Thank you, and done!
