### ISSUE TITLE
Merge the Project and Location extension to encourage implementers to publish infrastructure project identifiers

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1484]
Currently, the field for disclosing an infrastructure project identifier is part of the [Project](https://extensions.open-contracting.org/en/extensions/project/master/) extension, which is referenced from the OCDS docs on the page about [linking to other standards](https://standard.open-contracting.org/latest/en/guidance/map/linked_standards/?highlight=infrastructure#open-contracting-for-infrastructure-data-standards).

To increase the chances of OCDS publishers including infrastructure project ids in their OCDS data, even when they aren't implementing OC4IDS, we could merge the extension (or at least the `planning/project/id field`) into the main schema. That way, it would be visible to OCDS implementers as part of the mapping process.

We could also document a worked example/guidance page on publishing infrastructure project identifiers, which could reuse some of the content from the project identifiers guidance in the OC4IDS documentation.

**Comment by duncandewhurst** [comment]
@jpmckinney can a PR be prepared for this issue?

**Comment by jpmckinney** [comment]
The project extension depends on the location extension, and I think we had some change to make to it before merging the location extension: https://github.com/open-contracting/standard/issues/1179#issuecomment-988983174

**Comment by duncandewhurst** [comment]
Ah, yes. We already made some changes in https://github.com/open-contracting-extensions/ocds_location_extension/pull/34 and I've commented on the remaining open issues for the location extension.

**Comment by jpmckinney** [comment]
I made a PR to close the last Location issue in ocds-extensions.

When merging into OCDS, we should review field titles/descriptions against the style guide (as part of #850).

Noting that Location extension is the most used extension according to https://github.com/open-contracting/standard/issues/1179#issuecomment-966765110 so it makes sense to merge.

**Comment by jpmckinney** [comment]
There's an open issue on the Project extension: https://github.com/open-contracting/ocds-extensions/issues/135

**Comment by odscjen** [comment]
no open issues on either the Location or Project extension so this is now good to go

**Comment by odscjen** [comment]
> We could also document a worked example/guidance page on publishing infrastructure project identifiers, which could reuse some of the content from the project identifiers guidance in the OC4IDS documentation. 

I'm not convinced this is necessary. The other OCDS identifiers guidance pages are for identifiers that use the `scheme` plus `id` configuration, where as the `project.id` is a free string field. I think the description of the field is enough.

@jpmckinney do you think we need a guidance page on this?

**Comment by jpmckinney** [comment]
Agreed, not necessary. We can maybe find a place to link to https://standard.open-contracting.org/infrastructure/latest/en/guidance/identifiers/
