### ISSUE TITLE
Update `planning/budget/project` description

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1485]
The current description for the `planning/budget/project` field is:

> The name of the project through which this contracting process is funded (if applicable). Some organizations maintain a registry of projects, and the data should use the name by which the project is known in that registry. No translation option is offered for this string, as translated values can be provided in third-party data, **linked from the data source above**.

However, the `planning/budget/source` field was deprecated in 1.1.

**Comment by jpmckinney** [comment]
Let's delete that text :)

**Comment by yolile** [comment]
Closed by #1487
