### ISSUE TITLE
Semi-structured tenders' terms and conditions publication

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1491]
In Paraguay DNCP, they are now including in their eGP system information about the tenders'  terms and conditions as semi-structured information. For example https://www.contrataciones.gov.py/licitaciones/convocatoria/403580-implementacion-sistema-envio-correos-electronicos-masivos-1.html#pliego (This information was previously published as a PDF document and now at least the text and sections are made available as semi-structured information.)

Each tender uses a standard terms and conditions template. Each template has 7 sections, including amendments, tender information, qualifications and selection criteria, items technical specifications, contract terms, contract template, and template forms (for example, guarantee compliance declaration form, etc.). 

The content of each section contains different subsections, and each of them contains a free text value. The free text values can be long (for example, see "Suministros requeridos - especificaciones técnicas" and "Detalles de los productos y/ servicios con las respectivas especificaciones técnicas  - CPS"). Some of the content is always the same and cannot be changed. For the content that can be changed can vary, DNCP stores the different versions of each term and condition for each tender, for example, see https://www.contrataciones.gov.py/licitaciones/convocatoria/403580-implementacion-sistema-envio-correos-electronicos-masivos-1/pliego/versiones.html.

The question is how to publish this semi-structured information in OCDS. Should it be published as part of OCDS as an extension, or should it be linked from OCDS but published as a separate (JSON) document?

cc @dreese17

**Comment by jpmckinney** [comment]
From what I understand, there are many relevant existing fields and extensions:

- amendments: `tender/amendments` with accompanying changes to `tender` fields
- tender information: `tender` fields
- qualifications and selection criteria: https://extensions.open-contracting.org/en/extensions/selectionCriteria/master/
- items technical specifications: https://extensions.open-contracting.org/en/extensions/itemAttributes/master/
- contract terms: https://extensions.open-contracting.org/en/extensions/contractTerms/master/
- contract template, and template forms: `tender/documents`  
 
What is different about DNCP's data that would prevent using the above?

**Comment by yolile** [comment]
> there are many relevant existing fields and extensions

Yes, and they are already using many of these when they have structured information. 

>What is different about DNCP's data that would prevent using the above?

This new section is basically the info that was formerly in PDF terms of reference documents now collected and published as key/value or section/free text fields. Some sections and free texts are already covered by existing structured fields, however, others are not. And for example, again for "Suministros requeridos - especificaciones técnicas" and "Detalles de los productos y/ servicios con las respectivas especificaciones técnicas - CPS" (items specifications), they are not linking that info with each item.  The other thing to consider is some text length and format, as the content could be long and include tables, formated text. etc. 

So I think this info could be linked as `tender/documents`, and only when they standardize more fields should these be mapped to specific OCDS fields.

The other option is to do a mix of both things, as you suggested, publish the information as a document and also map the different subsections of each section that can be mapped already. For example, for each subsection of "Condiciones contractuales" (contract terms) create a new field (or map each sub-section to an existing field) in https://extensions.open-contracting.org/en/extensions/contractTerms/master/. But some sub-sections can have additional (free text) sub-sub sections, and in these cases the mapping could be harder to do. 

But, I'm slightly concerned about 1. how big the final JSON file will be and 2. as this is all free text, how useful it is to publish this info as it is. If an app consuming the API wants this additional info, it can follow the link to the document. If I'm an advanced user who wants to apply natural language IA techniques, I can also follow the link and download the full info, but only if it is needed.

**Comment by jpmckinney** [comment]
OCDS is a plain-text format – I don't anticipate developing any sort of layout options for values (whether HTML or otherwise). As such, if content includes tables and formatted text, it is better to link to it, rather than publish it in OCDS files. So, I think `tender/documents` is the way to go for this content.

**Comment by yolile** [comment]
I will close this issue as Paraguay will publish this information as an additional tender/document linked to a JSON document.

**Comment by jpmckinney** [comment]
Out of curiosity, could you provide a sample JSON document?

**Comment by dreese17** [comment]
Hello!

Sorry for the delay.
I am attaching the first version of the JSON files. Taking into account that it is only for our use (for now) the fields are in Spanish, we will also adjust them over time as the need arises.

[pliegos_json.zip](https://github.com/open-contracting/standard/files/9888483/pliegos_json.zip)

**Comment by yolile** [comment]
Thanks, @dreese17, @jpmckinney you can see 3 sample JSON documents in David's comment. Some of the fields are already published as OCDS fields, but a lot of them are not. If these fields become more standardized, we can add them to OCDS itself, as discussed.

**Comment by jpmckinney** [comment]
Ah, yes, I see. This would be quite substantial to standardize.
