### ISSUE TITLE
Add guidance on preparing test data

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1494]
A common challenge for the helpdesk is that implementers share fictional test data that is incoherent. This leads to false positives and missed issues. This problem is more common when implementers are developing new systems to collect and publish data. The helpdesk often advises that the implementer should work with stakeholders to collect enough real data to populate all the fields for one contracting process.

I think that we should add some guidance on preparing test data to the [check your data](https://standard.open-contracting.org/latest/en/guidance/build/#check-your-data) section of the build guidance, e.g.

> You ought to use real data for testing, wherever possible. Using fictional data can lead to false positives and missed errors in your data pipeline: for example, if your test data includes incoherent values for the award date and the contract signature date, it won't be possible to identify issues with how these fields are mapped in your OCDS data.
> 
> If your data source doesn't contain any data yet, because you are developing a new system to collect and publish data, for example, then you ought to work with stakeholders to collect enough real data to populate all the data elements for at least one contracting process.
> 
> If you can't collect enough real data for testing, then you ought to create realistic and coherent test data:
>  * use real entities, products, and services
>  * use plausible dates and values
>  * avoid using placeholder values
>  * avoid setting multiple data elements to the same value.

cc @Ravf95 @odscrachel

**Comment by jpmckinney** [comment]
👍
