### ISSUE TITLE
Guidance: include a reference to best practices for open contracting portals guide

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1506]
https://www.open-contracting.org/resources/best-practices-open-contracting-portals/

We can add it as a resource as part of https://standard.open-contracting.org/latest/en/guidance/build/#establish-your-publication-formats-and-access-methods
Or, we can add a new section about "Determine where to publish" with a sentence about thinking about where the data will be published, a new portal, an existing open data portal, etc, and put the link to the guide as a resource in case the decision is to build a new portal.

**Comment by jpmckinney** [comment]
I think this is more https://standard.open-contracting.org/latest/en/guidance/publish/#publish-and-share-your-data no?
