### ISSUE TITLE
Tracking Tender state/status

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#151]
In #143 there is notion of `awardStatus`, `contractStatus`. In our case we still have more broader need of general `status` or `state` field for tenders.

Our tender has following states:
- `clarifications` - within `clarificationPeriod`
-  `tendering` - within `tenderingPeriod`
- `auction` - while reduction is held
- `qualification` - while Qualification committee is evaluating tendering proposals
- `awarded` - while award is issued, and can be disputed
- `contract-signed` - after contract awarded is signed (no disputes allowed)
- `paused` - during active dispute.

While clarifications and tendering periods are known in advance, and state can be calculated by matching current date with the corresponding periods, the other states are no so well known in advance, and happen as the corresponding events happen in Tender lifetime.

As an added bonus, it would be good to record the periods, when Tender was in corresponding state.

**Comment by jpmckinney** [comment]
There is now an extension to implement @myroslav's codelist: https://github.com/openprocurement/ocds_currentStage_extension
