### ISSUE TITLE
Change "tender process" to "tender stage"

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1514]
In a few places, such as `Tender.id`, `Tender.hasInquiries` and https://standard.open-contracting.org/staging/1.2-dev/en/schema/reference/#tender we speak about a "tender process". For consistency's and clarity's sake, I think we should only have two types of processes: planning and contracting. For activities linked to data published in `plannning`, `tender`, `award` and `contract`, I would stick to calling them "stages". Consequently, I would suggest replacing "tender process" with "during the tender stage". 

(We do not have "award processes" nor "contract processes", there we also only speak about stages.)

**Comment by jpmckinney** [comment]
Agreed!
