### ISSUE TITLE
Clarify `id` (Release ID) use in releases and compiled releases

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1515]
The description of Release ID is 

> "The identifier of the release. The release ID must be unique within the scope of the contracting (or planning) process, for a given version of OCDS. In other words, a publisher may publish datasets for different versions of OCDS, and repeat releases within each dataset. The release ID must not contain the number sign (#). For a compiled release, the `ocid` and the maximum `date` among the individual releases used to create the compiled release, separated by a hyphen: {ocid}-{date}.",

If I understand correctly, the field must be filled in according to two different sets of rules, depending on whether it is in a release or a compiled release. If that is the case, I would suggest a small rephrasing to improve its readability: 

> "The identifier of a release or a compiled release. For a release, the release ID must be unique within the scope of the contracting (or planning) process, for a given version of OCDS. In other words, a publisher may publish datasets for different versions of OCDS, and repeat releases within each dataset. The release ID must not contain the number sign (#). For a compiled release, the release ID consists of an `ocid` and the maximum `date` among the individual releases used to create the compiled release, separated by a hyphen: {ocid}-{date}.",

____ 

This matches our use of "for a" in, for example, `tender`

> "Information about, for example, the needed items and their estimated value, procurement method, award criteria, and various deadlines. This information concerns either the contracting process or the planning process. For a contracting process, this information typically concerns the period starting with the publication of procurement documents and ending with the bid submission deadline. For a planning process, this information typically concerns the period before the publication of procurement documents.

____ 

I searched "for a" in the schema and didn't find any other fields that needed a similar update.

**Comment by jpmckinney** [comment]
To make the line even brighter, we can use "individual release" instead of "release".

#1315 added the last clause to close #834, which is missing a verb. https://github.com/open-contracting/standard/commit/4919a8f42ba25df1bb6ff26b22f3b07aadcdef36#diff-8ede12936d49b6f0107d60beaef0abe845f548e91d78acc0c430cf6c1516d183

I think the wording ought to be "the release ID should be the `ocid` ...". I think we can't make it "must", as that would invalidate some existing data.
