### ISSUE TITLE
Align wording of `budget.project` and `budget.projectID` 

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1517]
The description of `budget.project` 

> The name of the project through which the eventual contracts will be funded (if applicable). Some organizations maintain a registry of projects, and the data should use the name by which the project is known in that registry.

The description of `budget.projectID` 

> An external identifier for the project that the future contracting process will be part of, or will be funded via (if applicable). Some organizations maintain a registry of projects, and the data should use the identifier from the relevant registry of projects. Although an integer is allowed, it is recommended to use a string.

Shouldn't the descriptions, especially the first sentence, be more similar? I would expect them to be practically identical, just the former with a textual name and the latter with an identifier (for example, the first sentence of the project could be changed to "The identfier of the project through which the eventual contracts will be funded."). 

(I would also remove the "if applicable")

**Comment by jpmckinney** [comment]
Agreed!

**Comment by JachymHercher** [comment]
Done within https://github.com/open-contracting/standard/pull/1513 (mainly https://github.com/open-contracting/standard/pull/1513/commits/756b5202b2cea363b576b7618d186e281d01b554).
