### ISSUE TITLE
`procurementCategory` and `extendedProcurementCategory`: align and improve codes

### ISSUE THREAD

**Issue by JachymHercher** [open-contracting/standard#1525]
The `procurementCategory` codes are 

> goods,Goods and supplies,The primary object of this contracting (or planning) process are physical or digital goods or supplies.
works,Works,"The primary object of this contracting (or planning) process is the construction, repair, rehabilitation, demolition, restoration or maintenance of some asset or infrastructure."
services,Services,"The primary object of this contracting (or planning) process are professional services of some form, generally contracted for on the basis of measurable outputs or deliverables."

The `extendedProcurementCategory` codes are 

> goods,Goods and supplies,This contracting (or planning) process is for physical or electronic goods or supplies.
works,Works,"This contracting (or planning) process is for construction, repair, rehabilitation, demolition, restoration or maintenance of some asset or infrastructure."
services,Services,"This contracting (or planning) process is for professional services of some form, generally contracted for on the basis of measurable outputs or deliverables. When the consultingServices code is also available or in use for data from a particular dataset, the service code must only be used for non-consulting services."
consultingServices,Consulting services,This contracting (or planning) process is for professional services provided on a consultancy basis.

1) Shouldn't we align them more closely? E.g. by changing the extended codes to "The additional objects of..." ? 
2) Shouldn't we improve the codes? In particular, 'services' sounds strange to me, with the filler of "of some form" as well as the formulation "on the basis of measurable outputs or deliverables". I would assume everything contracted will have measurable outputs and deliverables.

**Comment by jpmckinney** [comment]
Noting that the `extendedProcurementCategories` field that uses the `extendedProcurementCategory` codelist was added in #376.

I think the common codes should be 100% the same, except substituting "additional objects ... are" for "primary object ... is".

I guess we need to retain the caveat about 'services' in the extended list (viz its use in datasets that contain 'consultingServices'), though I'm not entirely sure about it.

**Comment by JachymHercher** [comment]
> I guess we need to retain the caveat about 'services' in the extended list (viz its use in datasets that contain 'consultingServices'), though I'm not entirely sure about it.

By "caveat" you mean the "on the basis of measurable outputs or deliverables"? If yes, why?

**Comment by jpmckinney** [comment]
I mean:

> When the consultingServices code is also available or in use for data from a particular dataset, the service code must only be used for non-consulting services

**Comment by odscjen** [comment]
1) So `procurementCategory` will remain unchanged and `extendedProcurementCategory` will become:
>goods,Goods and supplies,The additional objects of this contracting (or planning) process are physical or digital goods or supplies.
works,Works,"The additional objects of this contracting (or planning) process are the construction, repair, rehabilitation, demolition, restoration or maintenance of some asset or infrastructure."
services,Services,"The additional objects of this contracting (or planning) process are professional services of some form, generally contracted for on the basis of measurable outputs or deliverables. When the consultingServices code is also available or in use for data from a particular dataset, the service code must only be used for non-consulting services."
consultingServices,Consulting services,This contracting (or planning) process is for professional services provided on a consultancy basis.

2) is there a reason some of the Descriptions are in " " and some aren't?

**Comment by jpmckinney** [comment]
1. The description of 'services' should be changed (in both CSVs) to tidy the problems described in (2) of the issue description.
2. The [`test_csv.py`](https://github.com/open-contracting/standard-maintenance-scripts/blob/main/tests/test_csv.py) script that checks the format of CSV files uses the default CSV "dialect" which uses minimal quoting (i.e. only if the cell value contains commas or quotes). Python doesn't have a way to, say, always quote one of the columns - it's all columns or nothing. The minimal quoting dialect produced the fewest changes to the CSVs, when the script was introduced.

**Comment by odscjen** [comment]
> 1. The description of 'services' should be changed (in both CSVs) to tidy the problems described in (2) of the issue description.

Looking for other definitions I found a relevant [EU definition for Contract nature](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/contract-nature) where services are defined as "Provision of services other than works and supplies." which if used as a basis could give us 

"The additional objects of this contracting (or planning) process are services other than goods or works. When the consultingServices code is also available or in use for data from a particular dataset, the service code must only be used for non-consulting services." 

I've removed the word "professional" from the description based on the common use of professional services as being those that require specialist skills or training and which excludes many services public bodies procure for, e.g. cleaning, catering, etc.

>  2. The [`test_csv.py`](https://github.com/open-contracting/standard-maintenance-scripts/blob/main/tests/test_csv.py) script that checks the format of CSV files uses the default CSV "dialect" which uses minimal quoting (i.e. only if the cell value contains commas or quotes). Python doesn't have a way to, say, always quote one of the columns - it's all columns or nothing. The minimal quoting dialect produced the fewest changes to the CSVs, when the script was introduced.

Ah, thanks

**Comment by jpmckinney** [comment]
Hmm, the EU definition is not very inspiring as it's just saying "anything that's not the other two". Can we research some other options?

Edit: We can also follow the pattern in `documentType.csv` of adding "This category is also called supplies." to include some synonyms that might be more familiar depending on the jurisdiction.

**Comment by jpmckinney** [comment]
Noting that the codelist was authored in #376 (continued from #204). "goods" was edited in #828. Other changes to the codelist are not especially notable.

The descriptions are currently:

> **Goods**: The primary object of the contracting (or planning) process are physical or digital goods or supplies.
> **Services**: The primary object of the contracting (or planning) process are professional services of some form, generally contracted for on the basis of measurable outputs or deliverables.
> **Works**: The primary object of the contracting (or planning) process is the construction, repair, rehabilitation, demolition, restoration or maintenance of some asset or infrastructure.

The UNCITRAL model law's [glossary](https://uncitral.un.org/sites/uncitral.un.org/files/media-documents/uncitral/en/glossary-e.pdf) has:

> **Goods**: Objects of every kind and description including raw materials, products and equipment and objects in solid, liquid or gaseous form, and electricity, as well as services incidental to the supply of the goods if the value of those incidental services does not exceed that of the goods themselves (the enacting State may include additional categories of goods)
> **Services**: Services of intellectual and consulting nature and any other services not covered by the terms “goods” and “construction”.
> **Construction**: All work associated with the construction, reconstruction, demolition, repair or renovation of a building, structure or works, such as site preparation, excavation, erection, building, installation of equipment or materials, decoration and finishing, as well as services incidental to construction such as drilling, mapping, satellite photography, seismic investigations and similar services provided pursuant to the procurement contract, if the value of those services does not exceed that of the construction itself 

The World Bank's [Procurement Regulations for Investment Project Financing (IPF) Borrowers November 2020](https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework#framework) has:

> **Goods**: A category of procurement that includes: commodities, raw material, machinery, equipment, vehicles, Plant, and related services such as transportation, insurance, installation, commissioning, training, and initial maintenance,
> **Consulting Services**: Covers a range of services that are of an advisory or professional nature and are provided by Consultants.
> **Non-consulting Services**: Services which are not Consulting Services. Non-consulting Services are normally bid and contracted on the basis of performance of measurable outputs, and for which performance standards can be clearly identified and consistently applied. Examples include: drilling, aerial photography, satellite imagery, mapping, and similar operations.
> These Services typically involve providing expert or strategic advice e.g., management consultants, policy consultants or communications consultants. Advisory and project related Consulting Services include, for example: feasibility studies, project management, engineering services, finance and accounting services, training and development.
> **Works**: A category of procurement that refers to construction, repair, rehabilitation, demolition, restoration, maintenance of civil work structures, and related services such as transportation, insurance, installation, commissioning, and training.

Relevant to works, I also had a look at the EU's [EEC 3037/90](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A01990R3037-20080101) (Section F), which makes it ways into the UK's [Schedule 2](https://www.legislation.gov.uk/uksi/2015/102/schedule/2/made).

See also https://en.wikipedia.org/wiki/Goods_and_services. The [WTO's GPA](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm) is not helpful.

To avoid overlong definitions, I might suggest:

> goods: The primary object of the contracting (or planning) process are tangible items or, depending on local legislation, digital items or electricity. This category includes services incidental to the supply of the goods, if the value of those services does not exceed that of the goods. This category is also called supplies.
> services: The primary object of the contracting (or planning) process are activities not covered by the codes 'goods' and 'works'.
> works: The primary object of the contracting (or planning) process is the construction, repair, rehabilitation, demolition, restoration or maintenance of a structure. This category includes services incidental to the works, if the value of those services does not exceed that of the works. This category is also called infrastructure.

For goods, as mentioned in #376 and on Wikipedia, electricity is a good in the EU but a service in the US. Similarly, digital items are sometimes goods (if focusing on its consumption) and sometimes services (if focusing on how it is licensed and delivered, e.g. via a streaming service).

For services, I maintained something like the EU definition for services, while adding a sentence to goods and works, since services occur in the supply of goods and works, but we don't want the definition to be interpreted as over-broad.

For works, I kept the list (as before) from the World Bank, which is a longer version of the UNCITRAL list, plus it includes "repair, rehabilitation, restoration, maintenance", which is otherwise not present in the EU. The EU hierarchy includes some specifics like site preparation, installation, and completion, but I think these can be interpreted as part of a perhaps expansive interpretation of "construction".

**Comment by odscjen** [comment]
Those definitions look good to me. I'll hold off making the PR until #1530 has been merged
