### ISSUE TITLE
update mediaType.csv with latest IANA codelist

### ISSUE THREAD

**Issue by odscjen** [open-contracting/standard#1536]
In version 1.1 we're pointing publishers to the template column in the IANA list for `document.format` codes, but in 1.2 we're using the `mediaType.csv` codelist where the codes appear to be taken from this template column. The [IANA media type codes](https://www.iana.org/assignments/media-types/media-types.xhtml) have been updated (latest update 2022-07-14) and the OCDS 1.2 codelist `mediaType.csv` is now out of date containing codes that no longer feature in the template column of the IANA list. 

Should we be updating `mediaType.csv` so that it always reflects what is in the IANA list or are we fine with it deviating over time?

**Comment by jpmckinney** [comment]
Before any release, we run these steps, which update all external codelists, including IANA Media Types. https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment.html#perform-periodic-updates
