### ISSUE TITLE
How to capture 'Remittance Order'

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#154]
From Josef re: trial conversion of Indonesia data. It was not possible to render:

> Remittance Order: related to payment arrangement that is agreed upon the contract execution.

@johardi could you give an example of this data?

In theory I think this could be captured in milestones (i.e. a milestone for each payment date) or alternatively also through transactions, by following the IATI model of having a transaction type to indicate commitments.

**Comment by timgdavies** [comment]
This has not come up again. Closing but can re-open if still and issue for anyone.
