### ISSUE TITLE
Classify tenders and lots as Sustainable Public Procurement (SPP)

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1543]
Recently has been more interest in measuring and identifying tenders, lots, and contracts that incorporate sustainable aspects. To facilited the identification of this type of process, we can consider adding a new field to classify the process as SPP-related. 

From a discussion call with @jpmckinney:

We can consider adding a field to tender and lot (field name TBD), that is an array of strings, using an open codelist based of the [EU’s strategic procurement codelist](https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/strategic-procurement). We discussed using additionalClassifications, which is also an appropriate model to describe the tender/lot as a whole (NB: CRM-7628), but given the priority we are giving to sustainability work, this information should be promoted to a separate field.
Concurrently, publishers should model the selection and award criteria using the extensions that allow a breakdown. That way, an analyst can determine the weight assigned to SSP criteria. (OCDS doesn’t currently have a way to model in detal the technical specifications or contract performance conditions, and we don’t presently see a way to incorporate this.) At present, we don’t have a proposal for how to standardize selection or award criteria, and we are not sure whether it is possible to standardize across jurisdictions.

[Buenos Aires example](https://www.buenosairescompras.gob.ar//PLIEGO/VistaPreviaPliegoCiudadano.aspx?qs=BQoBkoMoEhyCT9GYwqvYH3Q/jfMEFwaVjeuEhmi2hZk%7C1CvTkC627eJnmy2n/vuG): Discussed one idea being to have the additional boolean questions as sub-codes to our proposed field above, e.g. environmental.minimalPackaging

## Proposal

Field name suggestions: sustainableBenefits, sustainableAspects, sustainablePillars (from the [SPP toolkit](https://openspp.super.site/what-is-spp-and-open-spp)), sustainableAreas, sustainableImpacts, sustainableGoals, sustainableCriteria

Definition: One or more sustainable aspects that this process incorporates, from the [codelistName] codelist. More detailed breakdown information can be provided using the pattern [code].[subcode]. Where sub-codes are used the parent code should also be included, e.g. ['environmental', 'environmental.carbonReduction']

Codes: From the EU: enviromental, innovation, social , economical (from the toolkit)

We could add already some subcodes based on the EU subcodes and the elements listed in the toolkit.

**Comment by jpmckinney** [comment]
I think the EU uses the term "strategic procurement" because innovation is not necessarily about sustainability. Ideally, we'd avoid the term "procurement" to allow this field to have broader semantics. We can research what term other jurisdictions use for combining these aspects/benefits/goals.

**Comment by yolile** [comment]
If this field goes beyond SPP, what will its definition be? (just asking so I can search for the correct term in other jurisdictions)
#736 may be related

**Comment by jpmckinney** [comment]
The EU defines strategic procurement as "Use of a technical specification, selection criterion, award criterion, or contract performance condition aims to reduce the environmental impacts of the procurement, fulfil social objectives and/or buy an innovative work, supply or service."

**Comment by yolile** [comment]
In Paraguay we use the term "Sustainable Public Procurement" and also include innovation as part of it: https://www.contrataciones.gov.py/dncp/compras-publicas-sostenibles.html

_Paraguay has a Sustainable Public Procurement Policy, updated in 2020 through Resolution No. 922/2020, which expressly declares the commitment of the National Directorate of Public Procurement, as the regulatory institution of state purchases, of promoting sustainable development in the environmental, social and economic dimensions.
In addition to contemplating the three dimensions of sustainability, the DNCP includes the principle of value for money and concepts such as; circular economy, innovative public procurement and responsible business conduct._

https://www.contrataciones.gov.py/dncp/compras-publicas-sostenibles.html

**Comment by yolile** [comment]
For the term "strategic procurement/purchase" the definition in Paraguay is "the goods, works, and consultancy services to guarantee the continuity of the production of goods or services provided by Public enterprises or Public Limited companies with Majority Participation of the State because of the special characteristics of the goods, services or work." This applies for example, to buy fuel from a state-owned supplier

**Comment by yolile** [comment]
In Colombia, they also use "COMPRAS PÚBLICAS SOSTENIBLES"  and mention that Sustainable Public Procurement incentives innovation https://www.colombiacompra.gov.co/colombia-compra/compras-publicas-sostenibles-cps

_A purchase is sustainable when it satisfies the need and contributes to the protection of the environment, the reduction in the consumption of resources, or inclusion and social justice during the development of a public purchase process.
Sustainable Public Procurement generates value for money, since the state entities that develop them: (i) satisfy the need (efficiency); (ii) reduce the costs associated with the life cycle of the good or service (economy); (iii) decrease the use of resources (effectiveness); (iii) include companies or populations with difficulties to participate in the public procurement system, and (iv) **promote innovation in the private sector**._

**Comment by yolile** [comment]
So, in Latam, innovation is included as a economic benefit of SPPs. See this report from RIGC https://www.iisd.org/system/files/publications/iisd-handbook-ingp-en.pdf (page 9):

_Economic benefits: SPP can create demand for sustainable goods and services, supporting new, efficient industries and sectors and fostering innovation._ 

I guess the question is, if you want to buy innovative but not for SPP goals, why do you want to buy something innovative? E.g., If we call this field benefits (for say a name), what are the benefits you seek with buying innovations?

**Comment by jpmckinney** [comment]
Aha, Colombia also covers the "fulfil social objectives" part of the EU definition:

> include companies or populations with difficulties to participate in the public procurement system

So it seems common to combine sustainability, social objectives, and innovation.

Innovation is separate from SPP. Making innovative purchases is a market method of funding R&D (innovative products/services typically cost more than commodity products/services). Funding R&D is typically about economic growth. That said, the R&D might also be in support of sustainability (new energy, etc.).

So this grouping covers environmental, social and economic benefits/focuses/concerns. However, I think we should try to stick to the sustainability/social objectives/innovation framing rather than forcing a mapping to environmental/social/ economic, because the relationship I described above might not always hold (e.g. there's always an economic benefit).

**Comment by yolile** [comment]
FYI in the [SPP toolkit](https://openspp.super.site/what-is-spp-and-open-spp), Market innovation is indeed inside the "Economic" pillar
![image](https://user-images.githubusercontent.com/6834122/185398725-a6738e17-9403-4371-8d6e-669705773d07.png)

And from the SPP definition used in the toolkit as well:

_The most common definition of Sustainable Public Procurement comes from [UNEP:](https://wedocs.unep.org/bitstream/handle/20.500.11822/37045/SPPWSG.pdf), “a process whereby public sector organizations meet their needs for goods, services, works and utilities in a way that achieves value for money on a whole life basis in terms of generating benefits not only to the organization, but also to society and the economy, whilst minimizing, and if possible, avoiding, damage to the environment.”_

So, if with your purchase, you are meeting your needs but also helping the society/economy/environment, that is a sustainable purchase.  But yes, I agree that "innovation" shouldn't be part of the "economic" category always, but I think we could use "sustainable" as part of the name of this new field.

**Comment by jpmckinney** [comment]
Thanks for your research on this – I agree it's looking like "sustainable" is the most common word for this concept.

**Comment by yolile** [comment]
The United Nations Environment Programme (UNEP) has an Excel [questionnaire](https://wedocs.unep.org/handle/20.500.11822/36673) to assess "B: The public procurement regulatory framework is conducive to SPP" and "D: SPP purchasing criteria / buying standards / requirements" for scoring SPP progress in countries, which include the sections/aspects mentioned by the EU definition (technical specifications, award criteria, etc.)

And they describe their methodology [here](https://wedocs.unep.org/bitstream/handle/20.500.11822/37332/SPPICMG.pdf?sequence=3&isAllowed=y) where they say on page 5 under "WHAT IS SPP?": _"In this manner, SPP is considered a **strategic** policy instrument that can be leveraged in support of national and international sustainable development objectives"_

So the word "strategy" also appears here, same as the EU.

[SDG 12](https://sdgs.un.org/goals/goal12): Is about ensuring sustainable consumption and production patterns.

And SDG target 12.7: Promote public procurement **practices** that are sustainable, in accordance with national policies and priorities.

So maybe `sustainablePractices` or `sustainableStrategies` could be other options

**Comment by yolile** [comment]
The UK [Procuring the Future: Sustainable Procurement National Action Plan: Recommendations from the Sustainable Procurement Task Force](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/69417/pb11710-procuring-the-future-060607.pdf) in page 13 also includes a section about "Helping UK business competitiveness and innovation". The terms "sustainability benefits" "sustainability practices" are also used in this guide.

**Comment by yolile** [comment]
So, from a Google search from an incognito window, I got:

| keyword                   | number of results |
|---------------------------|-------------------|
| sustainability goals      | 1,610,000,000     |
| sustainable impacts       | 1,450,000,000     |
| sustainability strategies | 1,230,000,000     |
| sustainability impacts    | 1,380,000,000     |
| sustainable benefits      | 1,390,000,000     |
| sustainability practices  | 1,090,000,000     |
| sustainability benefits   | 1,040,000,000     |
| sustainable strategies    | 918,000,000       |
| sustainable practices     | 790,000,000       |
| sustainable goals         | 543,000,000       |
| sustainable aspects       | 516,000,000       |
| sustainability aspects    | 508,000,000       |

Note that "sustainability goals" is the number one but for obvious reasons: https://www.un.org/sustainabledevelopment/sustainable-development-goals/

**Comment by yolile** [comment]
Thinking about indicators and use cases, maybe another useful field to add is how the goal is implemented in this procurement process. Using the EU definition again and the [toolkit](https://openspp.super.site/implement/set-sustainable-criteria), these strategies can be: technical specification, selection criterion, award criterion, or contract performance condition

So maybe we can have a `sustainability` object with two strings arrays fields: `goals` and `strategies`, e.g.:

```json
{
  "sustainability": {
    "goals": [
      "environmental.carbonReduction"
    ],
    "strategies": [
      "techinicalSpecification"
    ]
  }
}
```

With that, data users can easily measure the different strategies used in a given country. For example, if the sustainable related technical specifications are disclosed in documents only, users can know that they can manually check for them in documents.

**Comment by jpmckinney** [comment]
Hmm, until we have evidence that publishers can supply the `strategies`, we might stick to `sustainability.goals`.

**Comment by yolile** [comment]
I think that we have some evidence, for instance, the Buenos Aires case listed in the issue description and, for example, Chile includes SPP-related award criteria, e.g. https://www.mercadopublico.cl/Procurement/Modules/RFB/DetailsAcquisition.aspx?qs=yudEhSt2Mx443fcqmguqTg==  (see section "6. Criterios de evaluación") and the [regulation](https://www.chilecompra.cl/wp-content/uploads/2016/11/directiva-n20.pdf) behind it. So in Chile, they could use award criteria breakdown and use `strategies: ["awardCriteria"]`, as they know they will incorporate the SPP aspect there. Similar for Buenos Aires.

**Comment by jpmckinney** [comment]
I'm looking at https://www.mercadopublico.cl/Procurement/Modules/RFB/DetailsAcquisition.aspx?qs=yudEhSt2Mx443fcqmguqTg== but it's not clear to me that this information can be used to automatically determine that one of the `strategies` is awardCriteria.

For Buenos Aires, yes, the questions under "Sustentabilidad" are enough to automatically determine whether the strategies include technicalSpecification (the questions about energy efficiency and packaging) and awardCriteria (the questions about gender equality and women-owned businesses).

**Comment by yolile** [comment]
>  but it's not clear to me that this information can be used to automatically determine that one of the strategies is awardCriteria.

So in section "6. Criterios de evaluación" all the items are award criteria. If the `Ítems` names are selectable and not free text, then if you chose, for example, "Contratación Inclusiva" that will automatically mean something like:

``` json
{
  "sustainability": {
    "goals": [
      "social.womanInclusion"
    ],
    "strategies": [
      "awardCriteria"
    ]
  }
}

**Comment by jpmckinney** [comment]
Aha, yes, assuming the Ítem is from a codelist that would work.

**Comment by jpmckinney** [comment]
Going back to your comment in https://github.com/open-contracting/standard/issues/1543#issuecomment-1221010145, do we know (e.g. from the SPP guide) that there is a use case for the `strategies` field (for users, not publishers)?

**Comment by yolile** [comment]
For calculating indicators such as:
"Share of tenders which reference SPP criteria within specifications"
"Value share of tenders which reference SPP criteria within specifications"
"Share of tenders that reference SPP criteria within scoring"

And others. Of course, if the publisher discloses detailed information in requirements, award criteria breakdown, etc., documents related to SPP in their publication policies, etc., the user could still calculate these indicators without a specific field. This proposal is to ease these calculations. 

Of course, an issue with this approach is if there are multiple strategies and multiple goals, as with the current proposal, the user won't be able to know which goal corresponds to which strategy

**Comment by jpmckinney** [comment]
Perhaps the model then is:

```json
{
  "sustainability": [
    {
      "goal": "social.womanInclusion",
      "strategies": [
        "awardCriteria"
      ]
    }
  ]
}

**Comment by yolile** [comment]
Yes, that model makes more sense. I think that with this model, we will also be somehow resolving this issue:

> (OCDS doesn’t currently have a way to model in detail the technical specifications or contract performance conditions, and we don’t presently see a way to incorporate this.) At present, we don’t have a proposal for how to standardize selection or award criteria, and we are not sure whether it is possible to standardize across jurisdictions.

At least, there will be a standardized way to indicate that award criteria or technical specifications related to SPP exist.

**Comment by yolile** [comment]
Another example from Lithuania, from the [toolkit](https://openspp.super.site/2a761699c5bd4a6696bf2b6ed43b2057)

> The PPO collects data on technical specifications, award criteria, and clauses. Using digital forms to capture structured machine-readable data before and after the procurement process, they ask buyers (on a central e-procurement system) if GPP criteria were applied. If yes, procurers submit declaration reports on green criteria used, and this data is added to the scoreboard.

And with that they built this dashboard https://vpt.lrv.lt/lt/svieslente

So the goal/strategies model will work for them as well.

**Comment by yolile** [comment]
And in Lithuania innovation is also under SPP https://vpt.lrv.lt/lt/darnieji-pirkimai

**Comment by yolile** [comment]
Note: @jpmckinney also suggested adding a `tender/hasSustainability` boolean field in case the publisher doesn't know the goals or strategies and only that the process is SPP related. This enables the calculation of basic indicators such as "Share of contracts that are classified as SPP".

**Comment by yolile** [comment]
Extension drafted https://github.com/open-contracting-extensions/ocds_sustainability_extension

**Comment by yolile** [comment]
Note that we ended up adding two more strategies: `marginOfPreference` (that is different from award criteria) and `reservedParticipation` (different from selection criteria).  Some related issues are https://github.com/open-contracting/standard/issues/574 and https://github.com/open-contracting/standard/issues/1102

**Comment by yolile** [comment]
Closing as the extension was created.
