### ISSUE TITLE
Rename buyer

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#156]
The terms seems to create confusion, since a "procuring entity" *is* the one doing the buying, the one appearing on contracts, so it's also the buyer. CoST uses "Project owner" instead of buyer to relieve this confusion.

Feedback:

>"buyer" probably is not the correct name for this field ("endUser"/"Customer" as suggestions)

**Comment by timgdavies** [comment]
The issues here can be taken forward in #368 which provides more flexibility in the labelling of the parties to a contract should 'buyer' not capture the key relationships to be monitored. 

It does not, however, currently propose at this stage changing the definition of buyer, as we have not seen major issues in practice with use of the buyer field.
