### ISSUE TITLE
documentType codelist: remove "bidders" and "bid" section reference

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#1560]
The documentation says the "bidders" `documentType` belongs to the "tender, bidder" sections, however, there is no "bidder" section in OCDS. I guess it should be "bid"?

**Comment by jpmckinney** [comment]
We can remove it, because, in any case, bids is not in OCDS core.

**Comment by yolile** [comment]
In that case, we should also remove "bid" from 'illustration' and 'submissionDocuments'

**Comment by jpmckinney** [comment]
Yes, sounds good.

**Comment by jpmckinney** [comment]
If #1179 merges the bid extension, then we can review the Section column for which codes are relevant to bids.
