### ISSUE TITLE
Question about best practice when mapping a suitable code for award criteria

### ISSUE THREAD

**Issue by Kenneth-Chau** [open-contracting/standard#1577]
Hello,

What would be the best practice when we cannot find a suitable mapping (or the mapping was depreciated) to OCDS for existing award criteria? 

It seems like the award criteria itself is an open code list. As the code list documents mentioned that if a publisher cannot find a suitable code, they may use a new code outside those in the code list. We are wondering what should be considered when creating new codes for the open code list. If there are better practices than creating new code, what are the recommendations from The Open Contracting Partnership? It would be great if your team could provide examples for the recommendation.

Thank you,
Kenneth

**Comment by jpmckinney** [comment]
Hi @Kenneth-Chau, can you describe the criterion that is not in the list? It'll make it easier to explain.

**Comment by Kenneth-Chau** [comment]
Hello James, 

So we have multiple of those. For instance, there are some award criteria that can best be represented by the codes bestValueToGovernment and singleBidOnly, which are depreciated in v1.1 of the OCDS codelist. We also have some criteria for special consideration for the environment and others that cannot be represented by what is on the list. 

Hopefully, this provides more context on the issue we are facing.

Cheers,
Kenneth

**Comment by jpmckinney** [comment]
How much information do you have about each criterion? If you have more than just the general category, then you can consider using this extension: https://extensions.open-contracting.org/en/extensions/awardCriteria/master/

Also, for these types of questions, it is best to contact the Data Support Team at data@open-contracting.org

**Comment by Kenneth-Chau** [comment]
Sounds good, I will reach out to the Data Support Team.

Thanks James!
