### ISSUE TITLE
Date of final state change

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1582]
Splitting from #1160 

Copying some discussion from CRM-8486.

A publisher wants to disclose the date on which the process reached its final state. This date might differ from the date on which the notice is published (`date`).

We can either have:

1. One field for each state (`dateCancelled` and `dateWithdrawn` – presumably, `dateUnsuccessful` is not needed, as this occurs simultaneously with the `tenderPeriod/endDate` if there are no qualified bids)
2. One field for the final state (since the final states are disjoint – i.e. a process can't be both cancelled and withdrawn, etc. – we only ever have one date to model). The field name would follow whatever name we choose for the status.

I would go with 2.

**Comment by duncandewhurst** [comment]
To be done at the same time as #1583. Blocked until #1160 is done.

**Comment by jpmckinney** [comment]
Unblocked

**Comment by odscjen** [comment]
Based on the advice given in the CRM issue, which was taking into account the new `finalStatus` fields in 1.2, we should use `finalStatusDate` as the single field name, an use this in every object that has a `finalStatus` field.
