### ISSUE TITLE
Planning final status codelist

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1583]
Related: #1160 CRM-8486

A buyer can publish a notice about a future procurement, and then later decide to not follow through on that future procurement.

The model needs to be able to disambiguate whether it's the planning process itself that is cancelled, or the future (non-existent) process. The tricky part is that it's hard to make a statement about something that doesn't exist; we can't mint an OCID for the contracting process and then set its `tender/status` to 'cancelled', because that implies that the contracting process had at least a minimal existence.

After #1160 and #1582, we can add `planning/finalStatus` and `planning/finalStatusDate`, with one code being 'cancelled' (as in the buyer didn't go ahead with the planning process, e.g. to hold consultations for a new recreational facility, which it then decided not to go ahead with) and 'unsuccessful' (as in the planning process didn't yield a contracting process).

**Comment by duncandewhurst** [comment]
Blocked until #1160 is done. Can be done at the same time as #1582

**Comment by jpmckinney** [comment]
Unblocked
