### ISSUE TITLE
Make tender.selectionCriteria and tender.exclusionGround objects with .description fields

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1607]
In OCDS 1.2, there’s a string `tender.selectionCriteria` field (previously discussed in #1120). For OCDS 1.1's EU profile, we created [the selection criteria extension](https://extensions.open-contracting.org/en/extensions/selectionCriteria/master/), which uses the same field name, but breaks it down into an object with a `.description` field and a `.criteria` array for structured data.

Similarly, in OCDS 1.2, there's a string `tender.exclusionGrounds` field (previously discussed in #901). For OCDS 1.1's eForms profile, we need to create an extension for structured data on exclusion grounds.

The proposal for this issue is to take the approach suggested in https://github.com/open-contracting/standard/issues/901#issuecomment-758129475 of making both `tender.selectionCriteria` and `tender.exclusionGround` objects with `.description` fields. Extensions can then add other fields to the objects for structured data.

```json
{
  "tender": {
    "selectionCriteria": {
      "description": "unstructured data",
      "criteria": [
        // structured data
      ]
    },
    "exclusionGrounds": {
      "description": "unstructured data",
      "criteria": [
        // structured data
      ]
    }
  }
}
```

**Comment by jpmckinney** [comment]
Agree!

**Comment by odscjen** [comment]
Just tried adding a field to the `SelectionCriterion` in the selection criteria field and it's giving an error "unexpectedly overwrites /definitions/Tender/properties/selectionCriteria/title /home/jen/extensions/ocds_selectionCriteria_extension/release-schema.json". 

@jpmckinney you've assigned yourself to this issue but I'm guessing it's not that high on your to do list? Can I create a PR to address it and so unblock https://github.com/open-contracting-extensions/ocds_selectionCriteria_extension/pull/8

**Comment by jpmckinney** [comment]
I forgot this issue existed 😅 

I created https://github.com/open-contracting/ocds-extensions/issues/221 about the conflict. I think you can just delete Tender.selectionCriteria from the extension, as it's only used by the old EU profile as suggested there.

**Comment by jpmckinney** [comment]
That said, feel free to also work on this issue – but if you want to unblock https://github.com/open-contracting-extensions/ocds_selectionCriteria_extension/pull/8, changing the extension as suggested above is the quickest route.

**Comment by odscjen** [comment]
> but if you want to unblock https://github.com/open-contracting-extensions/ocds_selectionCriteria_extension/pull/8, changing the extension as suggested above is the quickest route.

I'm assuming that's referring to the suggestion

> I think you can just delete Tender.selectionCriteria from the extension, as it's only used by the old EU profile as suggested there.

so suggestion 3 in https://github.com/open-contracting/ocds-extensions/issues/221?

I'll move discussion of the options to https://github.com/open-contracting/ocds-extensions/issues/221 but simply removing `Tender.selectionCriteria` from the extension might not be a suitable unblock for the blocked PR as the new field being added to `Criterion` might be needed at `tender` level.
