### ISSUE TITLE
CPV Supplementary Vocabulary

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#161]
CPV besides primary vocabulary offers supplementary one, and the lot can have one or more supplementary codes assigned. Quote from [guide](http://simap.europa.eu/codes-and-nomenclatures/codes-cpv/cpv_2008_guide_en.pdf):

> Example: A procurement entity interested in buying passenger car
> will choose the following codes to describe its object:
> 34110000-1 Passenger cars
> MB02-8 Right-hand-drive
> CA36-8 Euro 5 (fuel)

Should we put supplementary CPV classifiers in `additionalClassification`? If yes, what is the `scheme` in the case? Should we use `CPV` as well and analyze the length of identifier to differentiate primary from supplementary?

**Comment by jpmckinney** [comment]
In EU, a tender has a 'main CPV code', and the object of procurement (whether represented as lots or not) can have multiple CPV codes, each of which can have multiple CPVS codes. However, a CPVS code is only interpretable in the context of a CPV code:

> For instance, if the user wants to buy tables, he will choose the code ‘39121200-8 Tables’ in the Main Vocabulary to define the basic product. The Supplementary Vocabulary may be used to describe the product further:
> * Using the code ‘FA02-9 For kindergarten use’ would mean that the tables would be suitable for children in an educational area.
> * Using the supplementary code ‘FG19-6 For camping’ could mean that the tables would be light and/or foldable for this specific use.
> * If the tables are needed for a special event, and if the contracting authority does not want to buy them, the code ‘PA01-7 Hire’ would meet this particular need.
> * The material of which the tables should be made, for instance for aesthetic reasons, can be defined using Section A of the Supplementary Vocabulary.

— from [CPV 2008 Explanatory Notes](https://simap.ted.europa.eu/documents/10184/36234/cpv_2008_explanatory_notes_en.pdf)

> The supplementary codes are generic and are not designed to fit a specific code in the Main Vocabulary. Users are advised to use the closest attribute in the Supplementary Vocabulary to fit their need, provided that it belongs to a section coherent with the meaning of the Main Vocabulary code.

— from [CPV 2008 Supplementary Codes Explanatory Notes](https://simap.ted.europa.eu/documents/10184/36234/cpv_sv_2008_explanatory_notes_en.pdf)

Having multiple CPV and CPVS codes in `additionalClassifications` is uninterpretable. Some possible solutions:

1. Model subclassifications, such that a CPV classification can have multiple CPVS subclassifications
1. Suffix CPV codes with CPVS codes, if provided. This would either require a change to the description of either the 'CPV' and/or 'CPVS' scheme, or the addition of a new scheme. This is not how the data is stored in TED. The operation is reversible, so information and structure aren't lost, but it does make it marginally more difficult to determine the CPVS codes.

My preference is (2), which I'll propose in https://github.com/open-contracting-extensions/european-union

**Comment by jpmckinney** [comment]
Proposal is at http://standard.open-contracting.org/profiles/eu/master/en/F01/#/OBJECT_CONTRACT/CPV_MAIN/CPV_SUPPLEMENTARY_CODE

Contribute to issue at https://github.com/open-contracting-extensions/european-union/issues/16
