### ISSUE TITLE
Remove content that does not conform to the style guide from schema descriptions

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1610]
From review comments in https://github.com/open-contracting-extensions/ocds_lots_extension/pull/41. 

In particular:

* `Item.additionalClassifications`:
> A~~n array of a~~dditional classifications for the item.
* `Tender.enquiryPeriod`:
> The period during which potential bidders may submit questions and requests for clarification to the buyer or the procuring entity. ~~Details of how to submit enquiries should be provided in attached notices, or in submissionMethodDetails. Structured dates for when responses to questions will be made can be provided using tender milestones.~~
* `Planning.milestones`:
> ~~A list of~~ milestones associated with the planning process.
* `Tender.milestones`:
> ~~A list of~~ milestones associated with the tender.
* `Contract.milestones`:
> ~~A list of~~ milestones associated with the finalization of this contract.

At the same time, we can search for other occurrences of 'An array' or 'A list'.

**Comment by jpmckinney** [comment]
Subset of #850 (which is very large, so fine to do a bit at a time)

**Comment by jpmckinney** [comment]
I'll leave the wording as-is in 1.0-deprecated fields.
