### ISSUE TITLE
Schema browser is broken

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1614]
On https://standard.open-contracting.org/latest/en/schema/release/, I see the following:

![image](https://github.com/open-contracting/standard/assets/19265814/cdec6466-1415-4c80-a1f3-0d3cdc1ad7bb)

Same for https://standard.open-contracting.org/latest/en/schema/release_package/

**Comment by jpmckinney** [comment]
Ah, thanks - I had excluded some docson files, but accidentally that included index.html

**Comment by jpmckinney** [comment]
Fixed on profiles and OC4IDS (might still be rebuilding), so just waiting for standard PRs (#1615)
