### ISSUE TITLE
Merge the Organization classification extension

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1622]
Broken off from #1179

https://github.com/open-contracting/standard/issues/1179#issuecomment-1106827861

Prioritized as it supports a priority use case (inclusion).

**Comment by jpmckinney** [comment]
The extension has an open issue: https://github.com/open-contracting/ocds-extensions/issues/171

If the extension is merged, we can transfer that issue to this repository.

**Comment by jpmckinney** [comment]
The extension also has 1.1 and 1.2 branches. The 1.2 branch moves the COFOG code to OCDS. The 1.2 branch is the one to merged into OCDS.

If merged, the 1.1 branch should be renamed back to master.

**Comment by odscjen** [comment]
https://github.com/open-contracting/ocds-extensions/issues/171 is now closed

**Comment by jpmckinney** [comment]
In the extension: Renamed 1.1 back to master, and also merged some changes from the 1.2 branch (removing the legal context and updating EU code titles and descriptions).
