### ISSUE TITLE
DISCUSSION: Is the a concept of a "network" that can be defined on a tender to indicate eligibility for viewing/responding?

### ISSUE THREAD

**Issue by weilandia** [open-contracting/standard#1636]
It's common for many tenders in the US to be scoped to "contract vehicles" which are essentially groups of predefined, eligible suppliers. When tenders for these contract vehicles are released, only those suppliers have visibility. Is there a recommendation for modeling this with OCDS?

Further, within these contract vehicles, there are ofter sub-groups (sometimes known as set-asides) that further restrict eligibility and visibility of tenders. Curious if these concepts are already modeled in OCDS and I'm just missing them and/or if there has been discussion around them

Thanks!

**Comment by jpmckinney** [comment]
Thank you for opening your first issue, @weilandia!

Do you have a link to an example or any documentation of these "vehicles"?

They sound like what are internationally known as "framework agreements" https://standard.open-contracting.org/latest/en/guidance/map/framework_agreements/

At the federal level in the US, these terms correspond to framework agreements:

* indefinite-delivery/indefinite quantity (ID/IQ) contract a.k.a. call contract
* Multiple Award Schedules (MAS): managed by GSA
* delivery-order contract: "a contract for supplies that does not procure or specify a firm quantity of supplies (other than a minimum or maximum quantity) and that provides for the issuance of orders for the delivery of supplies during the period of the contract"
* task-order contract: "a contract for services that does not procure or specify a firm quantity of services (other than a minimum or maximum quantity) and that provides for the issuance of orders for the performance of tasks during the period of the contract"
* requirements contract: "for filling all actual purchase requirements of designated Government activities for supplies or services during a specified contract period (from one contractor), with deliveries or performance to be scheduled by placing orders with the contractor"

*Federal Acquisition Regulation, Code of Federal Regulations (CFR) Title 48, Subpart 16.5, FAR 2005-83/07-02-2015*

----

To determine whether these vehicles are framework agreements (or something else), we'd need to know more, like:

* Is the list of suppliers closed, or open?
* How do suppliers join the list?
* Do the suppliers compete for those tenders?
* Are the set-asides rule-based? (i.e. the buyer has no discretion as to which eligible suppliers can bid?)

**Comment by weilandia** [comment]
Yep, I'm talking both IDIQs and MAS.

- Is the list of suppliers closed, or open?
  - Open to look at, closed to participate (application process)
- How do suppliers join the list?
  - There's a bid/application process 
- Do the suppliers compete for those tenders?
  - Yes
- Are the set-asides rule-based? (i.e. the buyer has no discretion as to which eligible suppliers can bid?)
  - The buyer typically has the discretion to both choose which set-aside to use and can often choose specific suppliers within that group, but may need to provide rationale

**Comment by weilandia** [comment]
Thank you for your response. I'll dig into the framework agreements
