### ISSUE TITLE
Merge "Publisher namespace" section into instructions on selecting internal identifiers

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#1653]
Follow-up to #1524.

Right now there is mysterious language of:

> **Earlier versions of this documentation imposed a stricter pattern on how internal identifiers ought to be combined with the ocid prefix, including a requirement for local namespaces. This requirement has been relaxed in practice and can be considered deprecated.**
>
> However, publishers are encouraged to consider whether there are any risks of clashes in local identifiers (e.g. the possibility that two parts of the publishing body might use the same identifier for different contracting or planning processes) and to plan to mitigate this when establishing their own patterns to generate their `ocid`

This language was introduced in 2016 in [this commit](https://github.com/open-contracting/standard/commit/42b42089ca968e004359c41cd5a743f7cf0b051f#diff-bfcc5e7c96c1fdb89762c132ef58874889f3e48df7039fb88ee8a56da0cf973d), without a PR or issue or any discussion that I can discover. It appeared in [1.0.1](https://github.com/open-contracting/standard/blob/1__0__1/standard/docs/en/schema/identifiers.md). There is no changelog entry, as 1.0.1 didn't have any entries until 1.1.2 (presumably, the very large commit with the message "Updated documentation structure" made it difficult to discover this change).

The original language was drafted in #73 and [appeared in 1.0.0](https://github.com/open-contracting/standard/blob/1__0__0/standard/docs/en/02_key_concepts/04_identifiers.md#publisher-namespace).

The deprecated content is so ancient – and has only ever been indirectly referenced – that I think we can pretend it never existed and just redraft the second paragraph into the guidance on this page on selecting identifiers.

----

Noting that this was also added in that commit:

> The registered prefixes are dumb identifiers. They are not intended to carry any semantics, and their sole purpose is to turn internal identifiers into globally unique identifiers which can be cross-referenced between systems.

**Comment by jpmckinney** [comment]
Language suggested as part of #1524. cc @duncandewhurst

**Comment by duncandewhurst** [comment]
Sounds good to me!
