### ISSUE TITLE
Add OCDS extensions to the publication policy guidance?

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard#1687]
The [latest publication policy guidance](https://github.com/open-contracting/standard/blob/1.2-dev/docs/guidance/publish.md#finalize-your-publication-policy) doesn't explicitly specify that the OCDS extensions used in the data should be documented in the publication policy.

Is it implied? Or is it enough that the extensions are referenced in the data itself?

**Comment by ColinMaudry** [comment]
The document "Support Process: Review a publication policy" states that extensions should be listed alongside the codelists and codes.

![image](https://github.com/open-contracting/standard/assets/3747136/7e4383cf-1b75-493f-8d1f-deaf0e64895b)

**Comment by jpmckinney** [comment]
I think it’s enough for the extensions to be listed in the data. If we like, we can make this change in the publication policy template instead.

**Comment by yolile** [comment]
> If we like, we can make this change in the publication policy template instead.

It is part of the publication policy template already.
