### ISSUE TITLE
Framework agreements: Remove planning stage from diagram

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1698]
The diagram under [modelling framework agreements in OCDS](https://standard.open-contracting.org/staging/1.2-dev/en/guidance/map/framework_agreements/#modelling-framework-agreements-in-ocds) shows contracting processes that include a planning stage:

![image](https://github.com/open-contracting/standard/assets/19265814/86831919-159b-49e6-b3ad-c628c83307d6)

However, according to the schema, `planning` (only?) concerns the planning process:

> Information about, for example, needs identification, budget planning and market research. This information concerns the planning process. This information typically concerns the period before contracting documents (for example, procurement documents) are available to potential suppliers.

**Comment by jpmckinney** [comment]
Agreed, we should remove it.
