### ISSUE TITLE
Framework agreements: Should the contracts array be populated in the first-stage contracting process?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#1699]
The [guidance for modelling the first-stage selection and addition of suppliers to a framework agreement](https://standard.open-contracting.org/staging/1.2-dev/en/guidance/map/framework_agreements/#first-stage-selection-and-addition-of-suppliers-to-the-framework-agreement) does not populate the `contracts` array:

![image](https://github.com/open-contracting/standard/assets/19265814/8321c961-9366-4d69-8cef-9457b30642c2)

However, the definition of `Contract` in the schema includes framework agreements:

> "Information regarding the contract, typically between the buyer and supplier. This includes contracts describing all the contractual conditions (e.g. item, quantity, price, payment terms, time and place of delivery), **as well as contracts only describing the general contractual conditions (such as a framework agreement)** and those only describing the specific contractual conditions (such as a contract within a framework agreement). Communication between contractual parties that consists of minor specifications of conditions agreed previously (e.g. specifying the time or place of delivery) is not considered a contract. Amendments are considered as part of the contract that is being amended. Contracts are also used when giving prizes or other rewards (e.g. a follow-up contract) resulting from a design contest."

**Comment by jpmckinney** [comment]
I think it's fine. The guidance is not concerned with the contracts array.

> It does not describe how to model the contract (using the contracts array), because the modeling is the same for a framework agreement as for other types of contracts.

**Comment by duncandewhurst** [comment]
Ah, I missed that we'd added that sentence.

What is confusing me is the diagram, in which contracts are greyed out in the first stage, but not in the second stage.

![image](https://github.com/open-contracting/standard/assets/19265814/bb4af313-43e1-4165-a61d-5fe08d38fa72)

**Comment by jpmckinney** [comment]
Hmm, perhaps we don't gray them out then.

**Comment by duncandewhurst** [comment]
Sounds good.

For posterity, I also questioned whether a single framework procedure can include *both* direct call-offs and mini-competitions, as the diagram suggests. That is indeed possible, as explained in the CCS [guidance on framework agreements](https://assets.publishing.service.gov.uk/media/5a7f4bb8ed915d74e33f58de/Guidance_on_Frameworks_-_Oct_16.pdf) (page 5).
