### ISSUE TITLE
Сlassification-like unit structure

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#177]
At the moment we have single `string` field for `Item.unit`.

Having reviewed [CODES FOR UNITS OF MEASURE USED IN INTERNATIONAL TRADE Revision 9" (UNECE/CEFACT Trade Facilitation Recommendation No.20)] (http://www.unece.org/fileadmin/DAM/cefact/recommendations/rec20/rec20_Rev9e_2014.xls) there are following fields of interest:
* `Common Code`
* `Name`
* `Symbol`

Which of the fields is expected to be used in `unit` of `Item`? `Common Code` is looking like code that is unique, but sometimes too cryptic for average human to understand (for example `MTK` stands for "square metre").

Should we turn that field into something similar to `classification`? I.e. provide the unit scheme id (UNCE20), unit id (MTK), and unit description (square metre)?

**Comment by timgdavies** [comment]
From co-working session today: 

* Codelist in use in Russia: http://www.classbase.ru/okei

**Comment by ElenaMinina** [comment]
I suppose it's not full one. The full one could be found there http://base.consultant.ru/cons/cgi/online.cgi?req=doc;base=LAW;n=167465;fld=134;dst=1000000001,0;rnd=0.38406801223754883 (National Classification units "(app. Resolution of the State Standard of Russia from 26.12.1994 N 366) (Ed. By 28.03.2014)

**Comment by timgdavies** [comment]
Another possible source of units from the XBRL registry of units: http://www.xbrl.org/utr/utr.xml

**Comment by myroslav** [comment]
Unfortunately I do not see pieces, bottles, pallets, packs and boxes. Other
more exotic but used in procurement units are manmonth, manweek, etc.

On Tuesday, 6 October 2015, timgdavies <notifications@github.com> wrote:

> Another possible source of units from the XBRL registry of units:
> http://www.xbrl.org/utr/utr.xml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-contracting/standard/issues/177#issuecomment-145852945>
> .
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by mireille-raad** [comment]
This question on units re-surfaced recently in one of the missions with Marcela. Let me know if you need help researching this topics with colleagues and see if there best practices.

**Comment by timgdavies** [comment]
@dc-coder Support on looking into this would be great.

**Comment by timgdavies** [comment]
A full proposal has now been developed and is in issue #366
