### ISSUE TITLE
Contract review date

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#179]
This issue was under consideration for the 1.1 milestone. Not change was made in 1.1 and so it continues to need development. 

## The issue

Some jurisdictions require procuring entities to state when the contract will next be reviewed; this might be at a breakpoint, at the start of a possible extension period or just a certain period before expiry.
## What we are proposing

Introducing a **contract.reviewDate** field which can be used to indicate when the contract will next be reviewed.

Introducing a **reviewType** field and codelist which can be used to indicate the type of review with the following codes:

| Code | Title | Description |
| --- | --- | --- |
| breakpoint | Breakpoint | A review that takes place before the end of the initial contract period with the possible outcome of terminating the contract } |
| extension | Extension | A review that takes place at the end of the initial contract period with the possible outcome of extending the contract |
| expiry | Expiry | A review that takes places prior to the end of the initial contract period to determine whether a further contract is required |
## Example

``` json
"contracts": [
    {
        "reviewDate": "2017-12-31T00:00:00Z",
        "reviewType": "extension"
    }
]

```
## Outstanding questions

Are there any scenarios where a contract has more than one review date?

Are there any other codes that should be included in the **reviewType** codelist?
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

Please provide feedback on the outstanding questions in a comment.
## History

This issue was originally opened with the comment that:

From #171 

Add “ReviewDate” property to “Contract”

> we have to state when the contract will next be reviewed - this might be at a break point or at the start of a possible extension period, or just a certain period before expiry

**Comment by timgdavies** [comment]
A bit of research is needed to take this forward to understand examples of contracts with review dates, and:
- whether a contract only ever has one review date, or might have multiple review dates;
- how review dates might be used in analysis of contracts;

This _might_ be related to discussions on #200 about extensions to contracts.

**Comment by timgdavies** [comment]
The open corporates license schema discussed in #207 uses the property 'renewal_date'

**Comment by duncandewhurst** [comment]
Feedback from consultation with the Alexandre Borges de Oliveira, World Bank:

* The World Bank language for contracts that can be extended is 'stages' or 'phases'
* This is very rare and does not exist in legislation for most countries
* This type of extension tends to be more applicable to works contracts, e.g. a 5 year road maintenance contract awarded in stages upon successful completion of each year
* Details of stages/phases will typically be found in the bidding documents and contract forms

Consultations to date have not surfaced any existing codelists or definitions for contract review types.

**Comment by timgdavies** [comment]
Following the OCDS 1.1 peer review, this proposal was left out of 1.1 on grounds of available time, and as it will be possible to add as a community extension at a later date.

Removing 1.1 milestone.

**Comment by jpmckinney** [comment]
Just noting that in terms of nomenclature we may need to be careful distinguishing reviews of contracts from review procedures for awards as in EU and UNCITRAL.

**Comment by jpmckinney** [comment]
As mentioned in https://github.com/open-contracting/standard/issues/179#issuecomment-264183974, structured data about such reviews is very rare. The EU, for example, has only a checkbox and free-text field. GPA has nothing.

I'll close this issue as having insufficient participation and evidence for standardization. Originally raised by @AlCollier in #171, mentioned in #200 and #184, and survived by #375.
