### ISSUE TITLE
rel header for HTML pages for discovery of machine-readable version?

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#183]
A though from browsing various contracts portals which don't appear to currently provide machine-readable versions of notices.

It might be good for them to include a link value in the HTML or headers to point to machine-readable versions if available.

We might want to think about proposing a common approach for this.

**Comment by timgdavies** [comment]
This may relate to the API discussions. Closing, but tagging @kindly who might want to take note of this for API issue tracker.
