### ISSUE TITLE
Linking contracts nearing expiry with the process for procuring their replacements

### ISSUE THREAD

**Issue by AlCollier** [open-contracting/standard#184]
Going through the field list for our contract register, we've realised that we have a gap. Many contracts are cyclical: a service is delivered for a few years, then re-tendered.

A business scanning our contract register for opportunities, or a user group wishing to influence the specification for the successor contract, will want to look forward to the process for replacing the contract.

So it would be helpful if we could have something like successor.ocid to link from a contract to the process for its replacement.

**Comment by timgdavies** [comment]
Potentially related to #179 and #200  - and also to work on related contracts in #130

**Comment by timgdavies** [comment]
Renewal is also an issue in relation to licenses (see #207)

**Comment by duncandewhurst** [comment]
This is continued in #371
