### ISSUE TITLE
Document property names

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#185]
For simplicity and consistence, please consider following [Document](https://github.com/open-contracting/standard/blob/master/standard/schema/release-schema.json#L503) changes:
* `dateModified` -> `modified`
* `datePublished` -> `published`
* `documentType` -> `type`

**Comment by timgdavies** [comment]
I'm looking at things that might need to be cleaned up in the 1.0 RC - > 1.0 shift.

Right now in documents we have:

```dateModified```
and
```documentType```

Are these alright to continue with, or is there a strong reason to change? 

@myroslav - have you got an example of data already using documents live? We've not yet got any other publishers exposing documents right now, but I think some planning to work on this in the next few weeks, so keen to check we've got this section right.

**Comment by myroslav** [comment]
We'd included both into our ProZorro system, however `documentType` is not used yet, but I'm putting some efforts to push it to use.

`dateModified` is automatically calculated by our OpenProcurement software, i.e the first time document is uploaded into the system both `datePublished` and `dateModified` are the same, and when one updates the document - i.e. uploads newer version, that new version inherits the same `datePublished` as the first version had, but `dateModified` is updated to reflect the latest version upload time.

**Comment by timgdavies** [comment]
Great. So I don't think any further changes required here, so I'll close the issue - but we'll definitely need to come back to the document type codelists in future.
