### ISSUE TITLE
Deprecation Policy

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#189]
It's anticipated that properties will someday be deprecated and then renamed/removed. To serialize deprecation, we should use a new `deprecated` keyword in the schema files, which is a simple boolean. If not present, it's assumed to be `false`.

As there will be multiple versions of OCDS, its necessary for implementations to declare which version they are implementing.

>A new, required `conformsTo` property should be added to the `Release`, `ReleasePackage` and `RecordPackage` schema with the definition “the version of the Open Contracting Data Standard to which this resource conforms.” Its value should be the URL of a version of the schema, e.g. “http://ocds.open-contracting.org/standard/r/1__0__RC/”.

Given the possibility of extending the schema, it's necessary to allow implementations to refer to a non-canonical, extended schema:

>A new, required `describedBy` property should be added to the `Release`, `ReleasePackage` and `RecordPackage` schema with the definition “the schema against which this resource should be validated.” Its value should be an Open Contracting Data Standard schema, e.g. “http://ocds.open-contracting.org/standard/r/1__0__RC/release-schema.json”. If the canonical schema has been extended, implementations may reference a schema that includes those extensions.

A section of the documentation should list canonical values for `conformsTo` and `describedBy` for easy reference.

Note the above is based on https://project-open-data.cio.gov/v1.1/schema/

**Comment by timgdavies** [comment]
We're currently working on updated write-up of extensions process. Assigning to @kindly to consider in initial draft - and will then share things here for further discussion.

**Comment by timgdavies** [comment]
A proposal on the deprecating policy can be found in #367 

Our updated approach to handling extensions, which aims to build upon the points raised in this thread, can be found at #335
