### ISSUE TITLE
Amendment number

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#19]
Canadian data Tenders (and other) has an amendment number documenting how many amendments there have been.

**Comment by timgdavies** [comment]
We are thinking for 1.1 about wider updates to amendment which this may form part of.

In Canada's current data, they include semi-structured information in the rationale field for amendments, providing a single release with a history of past changes, as in the example below from a `contract` block:

``` json
[
"amendment": {
            "date": "2014-02-24", 
            "rationale": "amendmentNumber: 001, awardDate: 2009-07-02, expiryDate: 2008-03-31, value: 261000.00 | amendmentNumber: 002, awardDate: 2010-03-26, expiryDate: 2008-03-31, value: 0.00 | amendmentNumber: 003, awardDate: 2011-02-23, expiryDate: 2008-03-31, value: 0.00 | amendmentNumber: 004, awardDate: 2012-03-20, expiryDate: 2008-03-31, value: 0.00 | amendmentNumber: 005, awardDate: 2013-03-27, expiryDate: 2008-03-31, value: 0.00 | amendmentNumber: 006, awardDate: 2014-02-24, expiryDate: 2008-03-31, value: 0.00"
          }
]
```

**Comment by timgdavies** [comment]
A discussion of amendment handling is continued in #357. 

Work on the full proposal will take into account this issue.
