### ISSUE TITLE
Add a RDF OWL file as a linked data alternative to JSON Schema

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#190]
Requested by Paraguay.

If an OWL file is available, adopters would be able to use JSON-LD to swap local language terms for OCDS' English terms, solving #77.
#76 is maybe related.

**Comment by elf-pavlik** [comment]
Hi, I try to help friends from http://openoil.net to express their data in RDF, currently working with @jmatsushita on the data they use in this prototype https://data.openoil.net | https://github.com/iilab/openoil
Happy to join efforts :smiley:

**Comment by practicalparticipation** [comment]
Thanks Elf. What's your timeline for the Open Oil project? I know the Open Oil team have been looking at OCDS a bit - so would be great to explore how RDF model of their data could generate learning for a JSON-LD rendering of OCDS.

**Comment by akuckartz** [comment]
:smile:

**Comment by juanpane** [comment]
has there been any advances on this? 
We are in conversations with some Engineering students that could take on this task as the thesis

**Comment by timgdavies** [comment]
I don't believe there has been any progress around this - so if you had willing volunteers that would be absolutely fantastic.

**Comment by timgdavies** [comment]
@juanpane Many thanks for this. Sounds fantastic.

There might be some interesting relationships as well to the work we're just starting on mapping between OCDS and the [European TED](http://ted.europa.eu/TED/main/HomePage.do) schemas. 

Happy to provide input as useful as the project develops.

**Comment by ColinMaudry** [comment]
@juanpane May I be in the loop of the work you plan to undertake to create this JSON-LD context? I was planning to do it myself, but I could give a hand to an existing initiative. I do it in the frame of a pre-study to open public contracting data in France.

From a 5-minute study I did of the existing JSON Schema, I really think using OWL is overkill and that RDFS would do the job just fine, without the all the complex (though powerful) logic features carried by OWL and its flavours.

**Comment by patxiworks** [comment]
Based on work we're doing on [Budeshi](http://www.budeshi.org) and similar projects, there are suggestions to deploy RDFS/OWL (JSON-LD is also a possibility) to link datasets more coherently. I've gone through the discussions here and it doesn't look that there's been a lot of traction so far. I'll be happy to join forces with anyone interested in this – or have someone join me on it.

I only just started exploring the above specifications so I have a bit of catching up to do. Nevertheless, I found these existing ontologies [using the Falcons search tool](http://ws.nju.edu.cn/falcons/ontologysearch/result.jsp?query=contracting). For creating a sample ontology, I'll be experimenting with [Protege](http://protege.stanford.edu/) or some other, preferably, online tools.

Ideas are welcome!

**Comment by timgdavies** [comment]
Just spotted @ColinMaudry's repository at https://github.com/ColinMaudry/open-contracting-ld as an initial workspace on this. 

@ColinMaudry How is progress? Still something you are actively working on? Perhaps we can help by hosting a community call in June/July around this?

**Comment by ColinMaudry** [comment]
It is something I definitely want to do, but I ideally would like to develop a tool that creates a JSON-LD context from a JSON Schema. This way, that would work with any JSON SChema.

OCDS JSON Schema is quite big, and I consequently think it's smarter to spend time making a tool.

I also may get funded for it. I will know more on Monday.

**Comment by timgdavies** [comment]
@ColinMaudry Thanks for the update. Generating this programatically from the schema sounds like a really good approach. 

I believe (though we might need to check carefully) that where OCDS re-uses terms with the same name as e.g. schema.org or dcterms our semantics are similar, which might mean a tool could look for matches of term names against well known vocabularies and suggest re-use of these where relevant. 

OCDS also re-uses common building blocks throughout, so there might be ways a tool could be guided in mapping by some defaults.

**Comment by ColinMaudry** [comment]
@timgdavies Also, I don't expect this tool to make a 100% JSON-LD context. As you say, one has to set his preferred ontologies, etc. However, that would save a lot of time.

I've set up a repo and added you as a collaborator, so that you can create issues and stuff (feel free to reject if irrelevant).

https://github.com/ColinMaudry/schema2context

**Comment by ColinMaudry** [comment]
@patxiworks I just read your comment more carefully, and I think there is some confusion in the concepts, opposing JSON-LD and OWL/RDFS:
- RDF is the standard data model, with triples, properties, etc.
- OWL and RDFS are two possible schemas to base an RDF ontology, OWL being anchored on more powerful (and more complex) logic rules
- JSON-LD is just a possible serialization for any RDF data (be it based on an OWL or RDFS ontology), so are Turtle, RDF/XML, N-Triples, etc.

**Comment by patxiworks** [comment]
@ColinMaudry thanks a lot for the clarification. I think I'm getting to understand the concepts better, thanks also in part to my playing around with different tools.

I'm trying to put together an OWL ontology that matches the OCDS schema (including field descriptions as comments). It's mostly manual work at the moment but that's probably what I need to get my hands dirty with this stuff.

Per your proposed work on JSON-LD, I'm really keen on following up closely with it.

**Comment by yank07** [comment]
Hello @timgdavies . We are Software Engeeniering students(with @camilobaezcamba ) of @juanpane. We are working in an ontology for OCDS based in the PPROC Ontology, and other experiences like PC, LOTED and LOTED2. We have already made a research of the state of art, and now we are working with the conceptualization of the domain of OC.

We will be glad if you can give us a hand with the work. Our plan is to finish at least the core of the work before the end of the year.

**Comment by timgdavies** [comment]
@yank07 @camilobaezcamba Great to hear about this. How can we best help? We're happy to take a look at any work in progress, or if you think useful, to convene a community conversation around this.

**Comment by ColinMaudry** [comment]
@yank07 @timgdavies @camilobaezcamba Same here, I would be happy to give a hand.

**Comment by timgdavies** [comment]
With the growing interest in developing a Linked Data representation of OCDS we thought it would be useful to have a community call when all of those working on linked-data related OCDS topics can get together to share their work, and discuss possible ways forward.

We propose to hold this in late July/early August. There is a poll to find at time for that here: 

https://doodle.com/poll/t8xz6uvfcpbtb2nu

If you are interested in taking part, please register there. Once times are confirmed, call details will be circulated on the standard-discuss@open-contracting.org list and in this thread.

**Comment by jalbertbowden** [comment]
is it too late to sign up and lurk? poll is closed, so i don't see anywhere that i can add my name/edit the content...

**Comment by duncandewhurst** [comment]
@jalbertbowden not at all, the call is scheduled for July 29th 10am EST / 3pm BST, please join the standard-discuss@open-contracting.org mailing list and we'll circulate the agenda and WebEx details nearer the time, you can also leave a comment on the doodle poll if you wish.

**Comment by ColinMaudry** [comment]
Hi all,

I made a productive use of my free time and translated the OCDS JSON Schema into an RDF ontology.

It's all here:
https://github.com/ColinMaudry/open-contracting-ld

I have written down a bunch of thoughts and general comments at the top of the Turtle file, so that you get a feeling of the choices I had to make, what could be improved, what I didn't understand, etc..

If you have suggestions and comments, PR and issues are welcome.

Next step is to make a JSON-LD context out of it, so that a simple line added in a compliant JSON turn it into RDF.

See you in the call on Friday!

**Comment by timgdavies** [comment]
You can find a recording of Friday's call here: https://drive.google.com/file/d/0BwlGJL2-b9HBUjJSRmV2Ry1fV0k/view?usp=sharing

**Comment by jpmckinney** [comment]
I can't tell that there's been any specific follow-up from the call or the other proposals in this thread, so I am closing it as inactive. It seems the most progress has been made on https://github.com/ColinMaudry/open-contracting-ld which is where further work can be pursued.

**Comment by akuckartz** [comment]
👎 on closing this issue.

**Comment by ColinMaudry** [comment]
For the record, @jindrichmynarz made a phD thesis entitled [Matchmaking of bidders and public contracts using linked open data](http://mynarz.net/dissertation/), which I think partly connects the dots between open contracting and linked data. It's on my reading list.
