### ISSUE TITLE
Procurement method does not differentiate between limited tendering and direct contracting

### ISSUE THREAD

**Issue by chriscrownagents** [open-contracting/standard#194]
The field procurementMethod has three records: open, selective, and limited which includes direct contracting. It could be beneficial to split the last record so that its possible to record separately procurement exercises that involve inviting a limited number of suppliers to quote, and therefore involve some competition, and direct contracts where only one supplier is invited and there is no competition at all.

This would improve transparency and visibility on how often direct contracting is being used and for what,and combined with the value of the transaction, might improve accountability for a part of procurement spend which is often open to abuse and corruption.

**Comment by practicalparticipation** [comment]
Thanks @chriscrownagents. Could you suggest updated definitions for the split codelist. As http://ocds.open-contracting.org/standard/r/1__0__RC/en/schema/codelists/#method details - at the moment we had deferred to definitions from the WTO GPA, but if there is a good widely adopted set of definitions, and data in existing systems, that might help us use a better categorisation then really happy to see this considered in the next iteration of the standard.

**Comment by timgdavies** [comment]
I've been [looking at the codelist again](http://standard.open-contracting.org/latest/en/schema/codelists/#method), which includes: 
- Selective - Selective tendering means a procurement method whereby only qualified suppliers are invited by the procuring entity to submit a tender
- Limited - Limited tendering means a procurement method whereby the procuring entity contacts a supplier or suppliers of its choice

I can see two options here:

(1) Remove the words _'or suppliers'_ from the definition of `limited`. This would then define the direct award process under limited, any any cases of inviting a small number of suppliers would fall under 'selective'.

However, I can envisage processes that invite a small number of suppliers taking place which do not only invite 'qualified' suppliers, and so this may also require rewording of 'selective', taking us further away from the GPA definitions.

(2) Add a new code for `direct` defined as 'the award of the contract to a single supplier without any competition' 

This would appear to overlap with `limited` slightly - in that both could be used to define a process inviting a single supplier. 

Is this a problem?

In making any changes here we need to consider the implications for analysis of data, and whether existing systems record information in a way that would allow them to make a meaningful distinction here. 

@lindseyAM may have thoughts on this.

**Comment by joshuacpowell** [comment]
Reviewing Vietnam data, there is a specific category for "appointed contractor" which would match to sole source/single supplier. This is distinct from pre-qualified or other selective/limited bidding. Would tend to favor the second proposal (I believe USG, World Bank, and others also track instances of sole sourcing, distinct from other types of limited/selective bidding).

**Comment by chrisalexsmith** [comment]
I also prefer the 2nd option and would redefine Limited as follows - "Limited tendering means a procurement method whereby the procuring entity contacts a number of suppliers of its choice".
Sole sourcing is distinct from the other two in that there is no competition at all and the award is totally at the discretion of the procuring entity with no inbuilt checks from a competitive exercise. This risks of corruption are therefore higher but the visibility of such single contracts will be lost if they are lumped in with competitive exercises.

**Comment by chrisalexsmith** [comment]
The UNCITRAL Model Law on Public Procurement distinguishes single source procurement from other methods of procurement which involve some form of competition.

This is also the case with the WB Guidelines as follows:
Direct Contracting 
http://go.worldbank.org/F405XROF00
3.7 ... Direct contracting without competition (single source) may be an appropriate method under the following circumstances: 
(a) An existing contract for goods or works, awarded in accordance with procedures acceptable to the Bank, may be extended for additional goods or works of a similar nature. The Bank shall be satisfied in such cases that no advantage could be obtained by further competition and that the prices on the extended contract are reasonable. Provisions for such an extension, if considered likely in advance, shall be included in the original contract.
(b) Standardization of equipment or spare parts, to be compatible with existing equipment, may justify additional purchases from the original supplier. For such purchases to be justified, the original equipment shall be suitable, the number of new items shall generally be less than the existing number, the price shall be reasonable, and the advantages of another make or source of equipment shall have been considered and rejected on grounds acceptable to the Bank.
(c) The required equipment is proprietary and obtainable only from one source.
(d) The contractor responsible for a process design requires the purchase of critical items from a particular supplier as a condition of a performance guarantee.
(e) In exceptional cases, such as in response to natural disasters.

Similarly for Consultancy Services page 27 Single-Source Selection (SSS)
http://siteresources.worldbank.org/INTPROCUREMENT/Resources/278019-1308067833011/Consultant_GLs_English_Final_Jan2011.pdf

**Comment by AlCollier** [comment]
I agree. The distinction between a direct award with no competition, and a
limited competition, is an important one.

**Comment by timgdavies** [comment]
Continued in #380 for the upgrade.
