### ISSUE TITLE
Clarify definition of hasEnquiries 

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#196]
The current definition of 'hasEnquiries' is not terribly clear. We should look back and use cases and more clearly define this:

* hasEnquiries - A Yes/No field to indicate whether enquiries were part of tender process - boolean

**Comment by timgdavies** [comment]
@lmarchessault could you suggest an improved definition for hasEnquiries?

**Comment by robredpath** [comment]
This is a duplicate of #259 , I think.

**Comment by timgdavies** [comment]
Agreed. We can close this ticket and pick up definition issues in #259.
