### ISSUE TITLE
Improve Documentation of Unit

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#198]
The 'Unit' object appears to be missing from the Schema documentation.

It should be linked from 'Item': http://ocds.open-contracting.org/standard/r/1__0__RC/en/schema/reference/#item so that those browsing the tabular version can see that a value per single unit can be given.

**Comment by timgdavies** [comment]
Address in recent commit 623ddcef5221b54031b5299a3f029f872b42bfc6
