### ISSUE TITLE
Introduce Award Period

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#199]
The 1.0 RC standard does not include a 'Period' in the Award section.

This appears to be an oversight (?) - as other important fields such as items, and documents, are duplicated between award and supplier. 

Case such as the UK Contracts Finder record details of awards, with a period assigned to this, but do not currently capture details of the contract.

At present this means the options are either to:

* Drop the period information from the Award;
* Create a simulated contract section - but this implies we know about a contract when we don't

I propose inclusion of 'Period' as a valid property of award. 

Is there any reason not to do this?

**Comment by jpmckinney** [comment]
There is an `awardPeriod` in Tender that refers to the period over which awards will be made (i.e. when suppliers will be notified that they received an award). The `date` on Award refers to the specific date on which the award was made.

The `period` property that you define really refers to the period of the contract, so it should appear on the contract even if there are no other details. If a property were added to Award, it should be named `contractPeriod` to be clear that it's not an award period like on Tender.

**Comment by practicalparticipation** [comment]
Thanks. This is really useful. I'll review with the UK Contracts Finder team the exact semantics of their 'Award Period' - but which I think on my reading so far equates to the anticipated ```contractPeriod```, but it is set in advance of the contract actually being signed, so it would be theoretically possible for the award ```contractPeriod``` and contract's ```contractPeriod``` to vary.

**Comment by jpmckinney** [comment]
Cool, we would then have a pattern of Tender#awardPeriod, and Award#contractPeriod, which makes sense - along with an Award#date and Contract#period which may not line up with the anticipated dates/periods.

**Comment by AlCollier** [comment]
Sorry if stating the obvious, but does this accommodate:
Contract start date being some time after award (so contractPeriod doesn't start immediately)
Extension options built into contract from the beginning.

The standard for English local government ended up as:
Contract start date
Contract end date
Contract maximum extension date.

Cheers

Al

-----Original Message-----

**Comment by jpmckinney** [comment]
Yes, the periods/dates of award and contract are independent.

For contract maximum extension date, that's not yet modeled in OCDS, so that use case will have to be further developed and compared to other governments' processes.

**Comment by timgdavies** [comment]
I would like to propose then introducing ```award/contractPeriod``` using the ```period``` object in the 1.0 Release - as it appears to me a quite major omission from the Release Candidate, and does not break any existing data.

We're just working up process for finalising 1.0, but I would hope we can release a list by mid-April of minor changes proposed, with a comment period, before finalising 1.0 in May, and then starting on collecting suggested additions in 1.1 (which might include the Maximum Extension Date) example. 

Does this sounds alright as an outline plan?

**Comment by AlCollier** [comment]
Makes sense thanks Tim

-----Original Message-----
