### ISSUE TITLE
Different kinds of tender notice

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#20]
What types of notice should we capture. From the canadian dataset (expired notices):

* Advance Contract Award Notice (ACAN)
* Invitation to Tender (ITT)
* Letter of Interest (LOI)
* Notice of Proposed Procurement (NPP)
* Price and Availability (P&A)
* Request for Information (RFI)
* Request for Proposal (RFP)
* Request for Quotation (RFQ)
* Request for Standing Offer (RFSO)
* Request for Supply Arrangement (RFSA)

**Comment by timgdavies** [comment]
We've not found further demand for structured data to distinguish different process types. 

The original proposal in this issue of using free text in the titles/descriptions appears to work. 

Closing - but can re-open if future demand.
