### ISSUE TITLE
Codelist updates: Introduce a 'planningUpdate' releaseTag and 'withdrawn' tenderStatus

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#201]
From UK Contracting Finder use cases:

> At any stage of a Contracting Process, the process might be 'withdrawn'.

I.e. a Contracting Process might have a `planning` release, but a decision is made not to move from planning to tendering. Rather than 'cancelling' the planning process, in the UKCF system, this is recorded as being 'withdrawn'. 

Similarly, a tender could be 'withdrawn' from the system in which it is being published, which does not _necessarily_ imply that the tender has been cancelled. 

There are a couple of broad options for modelling here:

**1. Using existing `tenderStatus` values**

So that a withdrawn planning release would include:
- `releaseTag: planning`
- `tender/status: cancelled`

**2. Introduce new 'withdrawn' `releaseTag` and/or `tender/status`**

So that a withdrawn planning or tender would be:
- `releaseTag: withdrawn`
- `tender/status: withdrawn`

With the definition of withdrawn as:
- This contracting process has been withdrawn. This may be due to a decision not to proceed with a full contracting process after early engagement or planning, or, in the case of a tender or contract, may be due to some factors that mean information on this contracting process can no longer be provided through this publishers platforms. 

**3. Introduce 'planningUpdate' `releaseTag`, and some relevant `tender/status` for post-planning***

It seems we should probably have a 'planningUpdate' release tag in any case. However, we would still need a status for the tender to move into when a decision is made not to proceed from planning to an actual tender or set of tenders. 

Possibilities include:
- Suspended
- PlanningClosed 
- Plan Not Pursued

But I'm not sure any of these quite capture the right semantics. Suggestions welcome...

(Depending on the solution here, it might be possible to consider a minor codelist adjustment for 1.0, or otherwise this will have to develop into a proposal for version 1.1)

**Comment by ekoner** [comment]
Asked for thoughts from the wider community in discussion groups and via twitter.

**Comment by woodbine** [comment]
This is a tricky one, market engagement for research purposes does not necessarily mean that there will be a tender to follow. So you could argue that there's no need to have a follow-up to a planning document as there was no tender to cancel. Having said that, it would be good to know more about the outcomes of a planning project. So I think that a mixture of 2 & 3, 2 would cover the withdrawal of a tender and 3 would cover a planning updated that didn't progress to tender.

**Comment by timgdavies** [comment]
By way of an updated proposal, I would suggest we introduce two new codes to `tenderStatus`:
- `withdrawn` - This contracting process has been withdrawn. This may be due to a decision not to proceed with a full contracting process after early engagement or planning, or, in the case of a tender or contract, may be due to some factors that mean information on this contracting process can no longer be provided through this publishers platforms.
- `planningComplete` - A planning process has been completed. This may be followed by a tender as part of this contracting process, but may also have no further action taken, or may result in a range of separate contracting processes. 

And we also introduce an updated to `releaseTag` to add:
- `planningUpdate`

For the final draft in 1.1 an updated version of the logic above should be added to the documentation.

**Comment by timgdavies** [comment]
Based on the discussions in #410 and above, I've staged an updated tenderStatus codelist as follows:

| Code         | Title        | Description                                                                                                                                           |                                                                                                                         | 
|--------------|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------| 
| pipeline     | Pipeline     | A tender process has been proposed or a potential tender is being explored. There is no guarantee that this process will proceed.                   |                                                                                                                         | 
| planned      | Planned      | A tender process is planned but is not yet taking place.                                                                                            |                                                                                                                         | 
| active       | Active       | A tender process is currently taking place.                                                                                                           |                                                                                                                         | 
| cancelled    | Cancelled    | The tender process has been cancelled.                                                                                                                |                                                                                                                         | 
| unsuccessful | Unsuccessful | The tender process was unsucessful.                                                                                                                   |                                                                                                                         | 
| complete     | Complete     | The tender process is complete.                                                                                                                       |                                                                                                                         | 
| withdrawn    | Withdrawn    | This tender process has been withdrawn. This may be due to a decision not to proceed with a full tender process after the pipeline or planning stage, or may be because subsequent contracting stages will no longer be managed through this particular information system. | 

I've suggested use of ```pipeline``` as opposed to the ```proposed``` code suggested in #410 and have updated the definition of ```planned```, to remove language about 'proposed' processes. 

I've refined the previously suggested definition of ```withdrawn```. 

I've then added ```planningUpdate``` to the ```releaseTag``` codelist, and refined definitions as follows:

| Category | Code           | Title           | Description |
|----------|----------------|-----------------|-------------|
| planning | planning       | Planning        | A contracting process is proposed or planned. Information in the tender section describes the proposed process. The tender.status field should be used to identify whether the planning is at an early pipeline stage,  or whether there are detailed plans for a tender developed.    |
| planning | planningUpdate | Planning Update | Details of a proposed or planned contracting process are being updated. This may include addition of information and documents from consultation engagement activities, revised details or timelines for a proposed contracting process,   or a tender.status update to indicate that a pipeline proposal has been withdrawn. | 

I've started a stub 'worked examples' documentation page which will address the specific case of withdrawing a planned contracting process.

**Comment by duncandewhurst** [comment]
Proposing an update to the description for the ```planning``` release tag to align with tender status descriptions:

> A contracting process is **proposed, planned or being explored**. Information in the tender section describes the proposed process. The tender.status field should be used to identify whether the planning is at an early pipeline stage, or whether there are detailed plans for a tender developed.

**Comment by woodbine** [comment]
Would it be worth considering "proposed" rather than "pipeline" and would it be worth using "scheduled" rather than "planned". Obviously there's a clear difference here, where a tender is given  a scheduled time, which is a useful piece of information that ought to be added.

**Comment by duncandewhurst** [comment]
@woodbine, thanks - your point on making the difference clear is really useful, however using ```scheduled``` rather than ```planned``` would involve deprecating the existing code in V1.1 and introducing the new code before removing ```planned``` in a future version, in addition to which we'd need to consider the impact on data publishers and users who are already using ```planned```. Making semantic changes to the definition of ```planned``` would also present the same issue, so ideally we'd look to address making the difference clear through the naming and definition of the ```pipeline```/```proposed``` code.

@LindseyAM suggested using ```consultation``` instead of ```pipeline``` or ```proposed```

@andrewlorien interested in your thoughts here

**Comment by woodbine** [comment]
+1 for @LindseyAM's suggestion.

Not too fussed about semantics, so don't want to see any deprecating or
recoding of the existing standard. The addition of a time-stamp detailing
the expected commencement of a procurement in the planned item, would
improve the distinction between an item that is open for consultation and
an item that has a specific schedule for implementation.

Ian

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> I am not 100% sure that the distinciton between "planned" and "pipeline" is clear and important enough to be distinguished - no opinion. However, if they are used, the descriptions should be a bit clearer: 
> 
> - "A tender process has been proposed or a potential tender is being explored." could for instance be changed to "A tender process is being considered" or "A tender process is being considered, but not yet planned." 
> 
> - "There is no guarantee that this process will proceed." - since a project can be withdrawn after the pipeline as well as planned stages, I think "There is no guarantee that this process will proceed." should be added also to the planned stage. (Moreover, since a tender process can always be cancelled, it could be easily argued that there is no guarantee even for an active tender, so perhaps the phrasing should be different altogether.)
> 
> - Furthermore, the description for withdrawn should be also changed - or perhaps the code split into two (see description in the paragraph below). 

> "This may be due to a decision not to proceed with a full tender process after the pipeline or planning stage, or may be because subsequent contracting stages will no longer be managed through this particular information system." I'm not sure how the second part of the sentence ("or may be because...") is relevant. Even if a system changes, another OCDS release could still be published through another system, which would have no impact on the data, so I would think there is no need to publish information about it. If anything, the sentence should read "subsequent contracting stages will not lead to publication of OCDS releases". If this is the case, I would move it into a separate code though, because it's very different than intentional withdrawal. (This information is interesting to only a very limited degree - it essentially says "we don't know what happened to the procurement process". However, such an explicit declaration may be useful from a data quality point of view to know that the expected relases did not just get lost somewhere.)

**Comment by timgdavies** [comment]
Withdrawn was introduced initially as an alternative to 'cancelled' for pipeline/planned projects. 

Whereas a publisher should always be explicit about the status of a tender that was active - and should come back to a system to say if it was cancelled, with planned/proposed projects it is less clear that this can be required - and in practice systems like Contracts Finder in the UK have, as I understand from last time I discussed this, been unable to track which of the two options contained within the 'withdrawn' code apply. 

Essentially, withdrawn is designed to capture cases where no further information about the process is available from the current system. 

We might simply update the definition to: 

> "No further information about this process is available." 

For pipeline, the suggestion above to rename this to 'consultation' is worth exploring, although I'm not sure it captures cases where an authority wishes to state they are likely to procure something next year, but are not consulting on it. 

Sticking with the current terms, but suggested updated definitions, would give us:

* **pipeline** - "A future contracting process is being considered. Early information about the process may be provided in the tender section. A process with this status may provide information on early engagement or consultation opportunities, during which the details of a subsequent tender can be shaped."
* **planned** - "A contracting process is scheduled, but is not yet taking place. Details of the anticipated dates may be provided in the tender block." 
* **withdrawn** - "No further information on this process is available under this ocid." 

Feedback on these alternatives welcome.

**Comment by LindseyAM** [comment]
I think 'consultation' could work because we would hope that consultation notices would go out as part of planning & the needs assessment/market research process...

the other potential option could be a 'planning' notice versus a 'planned' notice.  Planned means its basically a draft or a preview of the upcoming opportunity and Planning means its a notice forming part of the planning process (ie a consultation or flagging an identified need to the market).

**Comment by timgdavies** [comment]
Ok - based on @LindseyAM's comment - I think 'planning' and 'planned' could work. 

That would give us:

* **planning** - "A future contracting process is being considered. Early information about the process may be provided in the tender section. A process with this status may provide information on early engagement or consultation opportunities, during which the details of a subsequent tender can be shaped."
* **planned** - "A contracting process is scheduled, but is not yet taking place. Details of the anticipated dates may be provided in the tender block." 
* **withdrawn** - "No further information on this process is available under this ocid."
