### ISSUE TITLE
Cancelled Tenders - add entry to documentType codelist

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#202]
There is `Tender.status = cancelled ` for a cancelled tender, but where other details of cancellation are expected to be recorded? Is that common to have some document in `Tender.documents` with the cancellation protocol? If yes, what is expected `Document.documentType` for such protocol?

**Comment by practicalparticipation** [comment]
This wasn't a case we came across in early development, but if having a
cancellationProtocol document type would be useful, I think that could be
easily added to the documentType codelist.

**Comment by myroslav** [comment]
Probably that extra Tender document type can be good starting point. Later some analysis of such cancellationProtocols can reveal some structured way to record the cancellation reasons facilitation further analysis.

**Comment by timgdavies** [comment]
Question for community: are there any suggestions for codelists that could be used for cancellation reasons?

**Comment by timgdavies** [comment]
An additional code in documentType is proposed.

Based on limited feedback, no structured cancellation reasons codelist is currently proposed for the 1.1 upgrade process.

**Comment by myroslav** [comment]
We have strict list of reasons to cancel tender in our public procurement law, but we hadn't moved them to dedicated field in ProZorro yet.

**Comment by timgdavies** [comment]
Captured in #386
