### ISSUE TITLE
Proposal: Introduce contract/procurement type field

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#204]
Feedback from Alexandre Borges de Oliveira:

>On the tender/initiation section, I would suggest to consider adding the following data fields: “type of procurement (goods/works/services)”, “award criteria (lowest price, quality, quality and cost etc)”, “procurement method”, and complaint handling data. I would place the first three on the basic bin and the complaint data on the advanced bin. In addition, for the implementation section, I would suggest to include data fields about physical and financial implementation progress.

We currently handle awardCriteria, and procurementMethod, but do not have an explicit field for whether a contract is for goods, works or services.

Questions:

* Is there a clear use case for this being made explicit?
* Could this be inferred from CPV codes etc. in a way that would make this redundant?
* If included, what level should this live at?
* If included, what should the codelist cover?

**Comment by timgdavies** [comment]
This is required for the TED mapping.

It appears to exist in TED at the contracting notice level (rather than line-item level).

The TED codelist includes: 

* Supplies
* Services
* Works

Which I am assuming maps to:

* Goods
* Services
* Works

TED uses the term ```NATURE``` for this field.

**Comment by AlCollier** [comment]
Hi Tim

Supplies includes, for example, electricity as well as physical goods.

Regards

Al

**Comment by timgdavies** [comment]
Josh Powell at Development Gateway has flagged this as an important issue also.

**Comment by joshuacpowell** [comment]
Based on the Vietnam data, I would add "Mixed" to the codelist, as a single procurement may include both goods/services. This seems reasonably applicable across countries/contexts.

**Comment by AlCollier** [comment]
Practice in the EU is that the contract is classified as either supplies, works or services - whichever element is the highest value. The term 'supplies' is used rather than 'goods' to encompass the supply of electricity, etc.

-----Original Message-----

**Comment by timgdavies** [comment]
In #65 @jpmckinney pointed to classification of contracts as "subsidy, a professional services contract, property-related etc. in Montreal"

**Comment by jpmckinney** [comment]
For the full quote:

> A process can be categorized as a subsidy, a professional services contract, property-related, etc. There's no way to classify the process as a whole. [In OCDS] You can only classify items, which are fairly granular, and granular data is not always available - plus items only first appear in the tender stage.

**Comment by timgdavies** [comment]
Continued in #376
