### ISSUE TITLE
Review Open Corporates License Schema

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#207]
In the near future we will be exploring whether licenses can be represented using OCDS. 

@countculture has pointed us to the Open Corporates JSON Schema for licenses to look at in doing this work. 

https://github.com/openc/openc-schema/blob/master/schemas/licence-schema.json

**Comment by CountCulture** [comment]
Thanks @timgdavies 
Just a couple of words of explanation. The schema we currently had has gone through multiple iterations, based on having to handle a large number of different licence types – from business and professional licences (e.g. licence to operate a casino, sell alcohol or tobacco, operate as a pharmacist or accountant) and also financial and banking licences. We've not tried to represent extractives licences, for example, using this, but given that we will in the future be ingesting these, we would obviously like to be able to. 

The other_attributes field is something that allows arbitrary additional attributes to be captured without restriction or explicit schema. We've found this a useful pattern, as it means data is not lost, which is useful not just in itself, but it also allows us to have evidence of where the schema needs to be extended in the future. Hope this helps. C
