### ISSUE TITLE
Rebuilding OCDS Documentation Website

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#208]
Feedback suggests we need to improve the structure, layout and functionality of the OCDS Documentation website. 

Some suggestions for ways to improve:

* Add simple entry points for different users;
* Incorporate search function that will look across the website, GitHub and other spaces;
* Add display of field **titles** as well as field names;
* Work on translation of the standard;

**Comment by kindly** [comment]
This is essentially complete. Any issues from new documentation should be raised in separate ticket.
