### ISSUE TITLE
Documentation - releases / records references

### ISSUE THREAD

**Issue by stevieflow** [open-contracting/standard#209]
In

https://github.com/open-contracting/standard/blob/master/standard/docs/en/03_schema/04_record_package.md

> The release package schema describes the container document for publishing records. The contents of a record are based on the release schema. The package contains important meta-data.

Should this really be:

> The *record* package schema describes the container document for publishing records. The contents of a record are based on the release schema. The package contains important meta-data.

?

There are other references to releases on this page, which could/should also be records

**Comment by timgdavies** [comment]
Well spotted. 

I've correct this on master: http://ocds.open-contracting.org/standard/r/master/en/schema/record_package/
