### ISSUE TITLE
Handling open ended procurements

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#211]
Exploring http://www.scms.pfscm.org/scms/working/rfp I've come across a number of Request for Proposals which are labelled as Open Ended (i.e. no closing date given).

How should these be handled in OCDS? Should publishers just leave the end date of the tender blank? Or does this need some sort of special flag or approach? 

Considerations:
- How should consuming applications distinguish between invalid data (missing end date), and a case where there is no specific end-date for a tendering process?
- How can we ensure such tenders do end up closed at the point they are complete (e.g. guidance to publishers to issue an amended tender with the date that the process finally closed?)

**Comment by timgdavies** [comment]
As we look at 1.1 upgrade process, feedback on this issue would be appreciated.

**Comment by timgdavies** [comment]
No feedback has been received on this issue, so closing.

**Comment by JachymHercher** [comment]
This seems similar to what could happen in EU law with qualification systems (essentially a particular type of "technique" in the sectoral procurement directive) and possibly also dynamic purchasing systems. In EU forms, both of these cases are explicitly declared when the call for competition is being published and then need to be "closed" by another notice, saying something like "No further contracts will be awarded within this dynamic purchasing system".

(Note that for no good reason that I would know of, "qualification system" is declared in EU forms as a "type of notice", while "dynamic purchasing system" as a technique.)

(This could be interesting for @siwhitehouse.)
