### ISSUE TITLE
About contract models, there are some plan or initiative?

### ISSUE THREAD

**Issue by ppKrauss** [open-contracting/standard#215]
Considering contracts as documents, *contract models* are "contracts with placeholders" (contract forms)...  Perhaps public *contract models* are the only objective and secure way of *public consultation* (public notice and comment) for contracts: for minimize transation risks, maximize reliability, participation and judicial review.

Open Contracting Data Standard "2015 work plan"  include any kind of study/review/recommendation of *contract models*?  

-----
Example of potential issues (similar ones for *contract models*?):
* identify contract models: like [lex urn](https://en.wikipedia.org/wiki/Lex_(URN)) or opaque id.
* metadata and XML schema: like [Akoma Ntoso](http://www.akomantoso.org/), [LexML](https://en.wikipedia.org/wiki/LexML_Brasil) and others.

**Comment by timgdavies** [comment]
We don't currently have any plans within the Data Standard to look at template or model contracts - though if there were some potential demonstration projects or use cases that could explore this I suspect it would be of interest.

The core focus of OCDS is on describing the contracting process, rather than the contents of contracts themselves - so we do deal with identifier issues around linking tenders, awards, contracts etc. together, for which we adopt models not dissimilar to lex:urn of namespaced identifiers.

**Comment by ppKrauss** [comment]
@timgdavies thanks a lot your reply and explanations.   Well, I need to do my homework...  

-----
(notes and digressing)

(no homework yet) I was only reading  something about OCDS objectives and general perspectives... Maybe we can go ahead a discussion. 

I'm understanding that a "general aim" of OC is to **change the culture** of [informality](https://en.wikipedia.org/wiki/Informal_sector) and low use of contracts in [development countries](https://en.wikipedia.org/wiki/Developing_country)... Only big companies in countries like Brazil can be suppliers of government. Little business and formal freelancers never have a real chance, despite being (occasionally) "formally invited". This is a kind of "legalized corruption", and a barrier to "market concentration reduction"...

The [transaction costs](https://en.wikipedia.org/wiki/Transaction_cost) of "real use" (not only a symbolic use) of contracts are very high in developing countries...  Is easy to a big organization contest or break a contract,  that was signed with a little business... Is expensive, to a little business, to pay a lawyer to check (and/or interpret) your contracts.
There are *fear* and cost to assigning contracts, even with government, for little business.

By other hand, in this scenario, the experience show that *"simple, reliable and stable contract models"* can be used. 

We not need that Open Contracting create a complex XML model or a big database of samples and "well-done contracts"... Each country, each place, need to construct their little [Wiki](https://www.mediawiki.org/)  or database of *(simple, reliable) contract models for little business*... But we need a help to standardize protocols: the sucess of iniciatives like  [LexML](http://projeto.lexml.gov.br/documentacao/resumo-em-ingles) (an adaptation for contract models) may be recommended by OpenContracting... Perhaps a site like [DOI resolver](http://dx.doi.org) (**resolving IDs or URNs of _contract models_**) is suficient for developing countries, as "first step" and global iniciative ...

**Comment by timgdavies** [comment]
I would see increasing small companies access to public procurement opportunities as one of the aims of Open Contracting, but I'm not sure this has been articulated as a primary use case so far. More emphasis has been on transparency and accountability, and being able to monitor where public funds are spent - including through large firms.

However, the idea of focussing more on model contracts is an interesting one. The better place to generate discussion around this might be the Open Contracting Partnership's Community of Practice at http://pro-act.org/ where there is a wider community of procurement specialists - and this kind of early stage discussion would probably get richer feedback. 

If a discussion there surfaces clear use cases that the Data Standard should work with, then we can look at how to bring a discussion back over here with technical proposals.

**Comment by timgdavies** [comment]
Closing this issue. Not action required at this stage.
