### ISSUE TITLE
Use of RDFa

### ISSUE THREAD

**Issue by ppKrauss** [open-contracting/standard#217]
There are some "classic standards" like [vCard](https://en.wikipedia.org/wiki/VCard), that ensures *open data-interchange*... Nowadays vCard can be expressed with [RDFa](https://en.wikipedia.org/wiki/RDFa) with *classes* like [`Person`](http://schema.org/Person) and [`Organization`](http://schema.org/Organization)... And some contracting aspects with *classes* and *properties* like [`Offer`](http://schema.org/Offer) and [`award`](http://schema.org/award)... So, all these formal definitions resembles [OCDS fields](http://ocds.open-contracting.org/standard/r/1__0__RC/en/schema/reference/).

I think we can, in fact, to use OCDS as RDFa, seems simple ... There are a working group for it?

**Comment by timgdavies** [comment]
This relates to issue #190.

We would be keen to collaborate on a Linked Data / RDF rendering of OCDS, but would definitely need a clear use case and pilot to work on this with - and would want to make sure that any such process involved creating tooling to convert data from RDFa / JSON-LD into the canonical JSON form of OCDS. 

We've not yet got a working group structure established, but again - very open to this.

**Comment by timgdavies** [comment]
As I understand, this depends upon the development of an ontology to work, so is blocked by #190. Closing for now, as any work on this would emerge from the onotology work.
