### ISSUE TITLE
DocumentType codelist - Contract summary

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#220]
From @antnrueh:

In extractives contracts, a Contract Summary can be a very useful/important document. 

There are many kinds of contract summary.

For some stock exchanges, companies do not have to disclose full contracts, but they do have to disclosure contract summaries - and with regulations setting out what they should disclose. 

Consider for inclusion in the DocumentTypes codelist.

**Comment by anderspeders** [comment]
+1 on adding this to the DocumentTypes codelist

**Comment by timgdavies** [comment]
Proposal is to add this to the documentType codelist in 1.1

**Comment by timgdavies** [comment]
Captured in #386
