### ISSUE TITLE
Missing field: procurementMethodDetails

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#221]
From https://github.com/open-contracting/implementation-and-extensions/issues/2

At the moment `procurementMethod` is a closed codelist, with values for open, selective and limited. 

Any implementation should attempt to map the classifications of contract awards to this codelist - as knowing when things are open, selective or limited is important to many users.

However, many countries have much more detailed lists of procurement types, usually country-specific. 

Adding a new `procurementMethodDetails` would seem like a natural property for us to add, to parallel `awardMethodDetails` for this information.

**Comment by timgdavies** [comment]
`procurementMethodDetail` already [exists in the 1.0 docs](http://standard.open-contracting.org/latest/en/getting_started/). It appears it was a schema error that it's not in the schema.

**Comment by agm3dc** [comment]
@timgdavies do you mean procurementMethodRationale? We are not aware of procurementMethodDetail in the 1.0 docs, but we agree with the rationale and support its creation. We often run into cases where the procurementMethod's closed codelist lacks sufficient specificity for our government cases.

**Comment by timgdavies** [comment]
Sorry - I used the wrong docs link. At the [bottom of this page](http://standard.open-contracting.org/latest/en/getting_started/building_blocks/) you find procurementMethodDetails mentioned, and disambiguated from procurementMethodRationale.

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
