### ISSUE TITLE
Represent multiple and multi-year budgets

### ISSUE THREAD

**Issue by ElenaMinina** [open-contracting/standard#222]
At the moment there is only one budget slot in the Planning. 

But, in our contracting data, there are some contracts where the money comes from multiple budgets. We represent this as budget and extrabudget.

At the open contracting workshop in Berlin we have thought of two possible representations:
* Make budget a list of budgets
* Add an additional field `additionalBudgets` which is a list of budgets.

We looked at our data and it was only a small percentage ~4% that had this issue, so we think maybe the second option is better, especially as it is just an addition, not a change to the current standard. But that 4% is over 500,000 contracts, so it is important for us to represent this.

**Comment by timgdavies** [comment]
The approach of using ```additionalBudgets``` for now makes good sense.

I've added a 1.1 tag, as this is something we should look at during the 1.1 upgrade, as I imagine there will be a number of other publishers wanting to express multiple budgets into the future. For example, breaking down budget by year.

**Comment by timgdavies** [comment]
This is also an issue in #293 around multi-year budgets, where the publishers want to provide a more detailed breakdown to budget over years.

In the case of EU data, we also see interest in knowing whether a project has been funded by EU funds. 

In version 1.0 of the standard, we anticipated that budget information would be handled primarily by separate standards, such as the [fiscal data package](http://fiscal.dataprotocols.org/). However, this has taken a different route in it's development right now as far as I understand, so we could consider much more detailed budget information in OCDS 1.1.

Views are welcome on:

(a) How much budget information OCDS should aim to include in the planning stage;

(b) How this could be modelled effectively;

**Comment by duncandewhurst** [comment]
There is also an issue in [#352](https://github.com/open-contracting/standard/issues/352) around multiple budgets funding a framework contracting process in which an additionalBudgets array is proposed. We should consider how these issues fit together for the 1.1 upgrade.

**Comment by timgdavies** [comment]
Developed in #377
