### ISSUE TITLE
Digital signatures for documents

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#224]
_From discussions with @myroslav re: the [ProZorro platform](http://prozorro.org/en/)._
## Overview

A contracting process may have many attached documents. Checking the authenticity of these documents, and ensuring they have not been tampered with, is often important.

[Digital signatures](https://en.wikipedia.org/wiki/Digital_signature) offer a means of asserting and checking the authenticity of a document, and asserting who authored the document. 

There are two broad approaches to publishing signed documents:
- **Container based** - when the document and signature are bundled together. Special tools are needed to extract the document from the container and check its authenticity against the signature.
- **Separate document and signature** - when the document and signature are hosted separately, but the document can be checked against the signature manually.

The ProZorro case seeks to make both container-based documents available, and to provide documents with a separate signature. This is important for usability as not all users will have the tools available to extract documents from their containers. 

It is important to note that containers can also be nested. For example:
- A bidder signs their documents and sends them into a platform;
- The receiving agency reads the documents, and then signs the container (creating a new container) in order to assert they have read and reviewed the docs;

And so-on, through the layers of review of a document.
## Current model:

Our current document block looks like this:

``` json
  "documents": [
                {
                    "id": "string",
                    "documentType": "string",
                    "title": "string",
                    "description": "string",
                    "url": "string",
                    "datePublished": "string",
                    "dateModified": "string",
                    "format": "string",
                    "language": "string"
                }
            ],
```
## Issues and questions
- How should we model support for signed documents in OCDS?
- What other use cases for signed documents exist?

**Comment by timgdavies** [comment]
As an initial proposal, how might the following work:

## Introduce a ```documentVerification``` block
For the separate document + signature use-case.

Working on the assumption that there are different kinds of signatures for a document (from a simple checksum, through to digitally signed by a given individual using a particular protocol), we could introduce a ```documentVerification``` block into ```documents``` which includes an array of verifications.

E.g.

```
"documents": [
                {
                    "id": "001",
                    "documentType": "contract",
                    "title": "Afghanistan AmuDarya Production Sharing Agreement",
                    "description": "Example file from OpenOil",
                    "url": "http://downloads.openoil.net/contracts/af/af_AmuDarya_20111211_PSC_CNPC.pdf",
                    "datePublished": "2011-12-11",
                    "format": "application/pdf",
                    "language": "en",
                    "verification":[
                            {
                                "type":"md5",
                                "value":"3b33edf64f9e47b761f4c9f51c9bacbd"
                            },
                            {
                                "type":"gpg",
                                "value":"-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - http://gpgtools.org

iQEcBAABCAAGBQJVu2idAAoJEPi8TwpZVqNHGYIH/1/h0CBcfm53Mu38Y2k6GtZ6
lf5sfUHpysz5BIMQ8vSAU0ZzBjodLpXTTD1B4nhI4lUXLhAlrRs+GEd8nuZ/tHWa
0zTA9xlpObDpdCu1tyTVrlL+L1PmijcuboAdhGZ1OUmWo21mntlBMI2ok4Z3mLfL
Bf84v1MTD6AhVdTBDoUmLbMtMSptGpIDR3SVNYtBQ+O4makvEVqS8S71KXMtG6vY
SL2mk8Z2QafEJ0arNo3JGt8zTU/bl43lS7qf9p4JnN+KFtDmd2e58ILdG9ymYD7I
Itwfh+3XJElRXjzF4YWH1uTUmJgkDFg0A3NJH8y+f9LEw64lwYhHee7/79gx4fc=
=EiW1
-----END PGP SIGNATURE-----
                                "
                            }
                    
                    ]
                }
            ],
```

(Note: needs more research into models of digital signature, and how to serialise gpg signatures etc. into a JSON document best. @Bjwebb is this something you could look into?) 

This has the advantage of not disrupting implementations that do not know about signed documents (they document is still directly accessible), but also providing users with the information they need to verify a copy of a document. 

## Introduce a signed documents URI

For the container signed case, we could introduce a 'signedDocumentURI' property, which would point to a container signed version of the relevant document.

Questions: 
* Do we need to provide any more than this in the JSON? Presumably, the nested containers then contain all that the user needs to check out who signed the docs etc?
* Or should we also include meta-data about the keyholders who signed the docs within the JSON?

**Comment by timgdavies** [comment]
See https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#page-6 for possible codelist of encryption / signing algorithms.

**Comment by Bjwebb** [comment]
Signing is a relatively complex problem, so it may be best to keep our immediate alterations to the standard as simple as possible. In Prozorro, our only current use case, there will be containers for signing (as they want to handle nested signatures). Maybe it would be best to focus on how to link to signed containers  for now, and leave the idea of signatures in the OCDS file for a later date? This means we don't have the complexity of describing signatures ourselves, this is the responsibility of the container format.

For signatures, it's fine to just have a uri, because cryptographic signatures have enough information to verify that they can be trusted. However, providing hashes (as you do in your example above) works differently, in that this is only useful if the hashes are included directly in the (trusted) OCDS file. If we do want hashes like this, we might want to consider them separately (in particular as to whether there is currently a use case, or not).

I also wonder whether providing both a signed container and a plain document is a specific case of a more general problem - supplying the same document in multiple file formats (which I think Prozorro may also want to do). I don't think this is currently possible, except to add the different formats as separate documents. However, if we did have a way to indicate links were to the same document in different formats, that might give us an obvious way to link to a signed container, by using the appropriate mime type.

**Comment by timgdavies** [comment]
Do you mean that simply linking to the container is enough? Or do we still need an extra field for the signature of the container?

In the case of the general problem of multiple versions of the same document, I can see two non-disruptive ways forward:

(1) Introducing a **convention** that document IDs can have a suffix indicating the filetype. 

I.e. you might have documents with the ``id``` values of 001.pdf, 001.signed, 001.html - and the consuming application could follow the convention to them recognise that these are copies of the same document.

(2) Introducing a new field for document group identifier, with a clearly written definition to say these files should be copies of one another, just in different formats.

The ```.signed``` convention based approach breaks the idea of dumb identifiers, but also helps slightly get around the problem of layered mime-types. I.e. should the mime-type of a link to a container be something for the container, or something for the contents.

I'm leaning towards option (2) - and could mock that up if it would be useful.

**Comment by Bjwebb** [comment]
I mean that simply linking to the container is enough.

**Comment by myroslav** [comment]
I'd vote for additional fields, I.e. Ability to specify that Document objects are alternatives would solve a lot of hassles.

But that solution should be in line with Document versioning. At the moment we have multiple documents with same ID. All of the instances are versions, and modification date defines the sequence of versions. This ID sharing approach is not cleanest one, but works for the time being.

**Comment by timgdavies** [comment]
Ok. I've opened a new issue at #243 to consider the specific changes to the Documents object. 

The ID sharing approach creates problems for merging (IDs are used to overwrite array elements, so two documents with the same ```document.id``` will cause problems when merging - so it would be good for us to find a solution that covers both cases well.

**Comment by timgdavies** [comment]
In terms of linking to the container, am I right in thinking that we can then completely defer to the [IANA Media Type list](https://www.iana.org/assignments/media-types/media-types.xhtml#multipart) to provide all the information a client would need to interpret the alternative format of a file.

E.g. the format would be either ```multipart/encrypted``` or ```multiparty/signed```, or perhaps ```application/pgp-encrypted``` and ```application/pgp-signed```? 

(These were the only relevant media types I could find in the list).

**Comment by myroslav** [comment]
As far as I understand, multipart/encrypted and multipart/signed is SMIME,
and nt the most popular container format. I'll share the other popular
formats when I have them on my list.

On Sunday, September 13, 2015, timgdavies <notifications@github.com> wrote:

> In terms of linking to the container, am I right in thinking that we can
> then completely defer to the IANA Media Type list
> <https://www.iana.org/assignments/media-types/media-types.xhtml#multipart>
> to provide all the information a client would need to interpret the
> alternative format of a file.
>
> E.g. the format would be either multipart/encrypted or multiparty/signed,
> or perhaps application/pgp-encrypted and application/pgp-signed?
>
> (These were the only relevant media types I could find in the list).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-contracting/standard/issues/224#issuecomment-139858648>
> .
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by timgdavies** [comment]
There have been no updated on this issue since 2015. Closing.
