### ISSUE TITLE
Discussion: Digital signatures and encryption within OCDS

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#226]
Issue #224 addresses digital signature information for documents referred to within OCDS files.

This issue addresses the issue of signing an OCDS, and encryption within OCDS documents:

There may be cases in which:
- The authenticity of a release needs to be assured;
- A release needs to contain information which should only become public at a given point in time (e.g. sealed bids);
## Considerations & issues
- Some governments may have specific requirements for digital signing of official notices and documents;
- Should signing operate at the level of an OCDS 'file', or should it operate at a more deeply integrated level, such that, providing the **contents** of a release has not changed, the order of JSON fields etc. could change with the signature remaining valid;
## Resources
- [Javascript Object Signing and Encryption (JOSE)](https://tools.ietf.org/wg/jose/) working group specifications for JWS (JSON Web Signatures) and JWE (JSON Web Encryption)
- [Secure Messaging 1.0](https://web-payments.org/specs/source/secure-messaging/) and the related blog post by [Manu Sporny](http://manu.sporny.org/2013/sm-vs-jose/) which argues that JWS/JWE is over-complicated
## Call for Input
- Do you have a need for digital signatures or encryption of OCDS data? 
- Do you know of examples of digitally signed JSON, or digital signing infrastructures in use in government procurement contexts, which should act as a reference point for this exploration?

**Comment by timgdavies** [comment]
@myroslav Any context you can add would be very welcome.

**Comment by elf-pavlik** [comment]
Please also consider http://opencreds.org [Linked Data Signatures](https://www.youtube.com/watch?v=QdUZaYeQblY) - compared to JOSE in http://manu.sporny.org/2013/sm-vs-jose/

**Comment by timgdavies** [comment]
@elf-pavlik Thanks for the pointer on this. From what I can understand:

* To use Linked Data Signatures effectively we would need to have a stable JSON-LD context for OCDS, in order that a normalized RDF graph can be created for signing;
* There are not many reference implementations of Linked Data Signatures available yet (I could only find https://github.com/digitalbazaar/jsonld-signatures)

The first of these gives us a dependency problem, as I don't think we'll have a JSON-LD context for OCDS for a while yet (unless a good community effort to create it). 

So far, neither JOSE or LDS quite seem to be the tech we're after here... though I'm open to arguments otherwise...

**Comment by elf-pavlik** [comment]
@timgdavies I would like to discuss (in other issue?) collaboration on creating JSON-LD context for OCDS. I already started some work wile ago in Linked Data direction with @jmatsushita who works on https://github.com/iilab/openoil and now on http://influencemapping.org/influence-mapping-toolbox/ Please direct me to your proffered online venue to discuss this possibility further.

**Comment by kinlane** [comment]
We were using JSON-LD as part of the federal government open data work (https://project-open-data.cio.gov/v1.1/schema/), using it to describe government services (https://s3.amazonaws.com/kinlane-productions/federal-government/government-services/RepresentingGovernmentServiceswithJSON-LD.pdf). I was working on building tooling like google spreadsheets that help anyone generate JSON-LD description of government services (https://github.com/department-of-veterans-affairs/government-services-schema-from-google-spreadsheet-javascript)

**Comment by akuckartz** [comment]
@elf-pavlik See #40

**Comment by Bjwebb** [comment]
As @timgdavies mentions above, the major problem of Secure Messaging 1.0 is that it requires JSON-LD, which we don't have an OCDS context for, and is a technology many publishers/users may not be comfortable with. It also requires RDF normalisation, which is complicated to understand/implement. These issues apply for both signing, and encryption.

JWS (Signing) on the other hand, does not implement any normalisation, and requires the data to be signed to be in a hex encoded binary blob. Whilst it is possible to have the content of this blob be the JSON we want to sign, we have a choice of either:
1) Breaking compatibility by having the hex blob instead of the normal JSON structure.
2) Adding the hex blob to duplicate the JSON data. In addition to more than doubling the size of files, there is also no  way of checking that the signed data in the blob matches the other data (without defining some sort of normalisation approach)!

JWE (Encryption) also supplies data in binary hex blob, but since this is encryption, there is no copy in the clear, and therefore no duplication problem.

Therefore, I think JWE may be a realistic option for encryption, but I don't think that JOSE or Secure Messaging are currently appropriate options for signing.

**Comment by Bjwebb** [comment]
Another consideration is that, whilst for encryption it's fairly clear what we want to sign (although there are some questions around this, see https://github.com/open-contracting/standard/issues/231), this isn't currently clear for signing.

If people want to sign an entire OCDS release (or record file), they can use general purpose file signing techniques (e.g. OpenPGP file signatures). Signing at the file level avoids the normalisation, as you just sign the exact representation of JSON you have produced. File level signing may not need to be part of the standard standard, although we probably would want to describe best practice.

However, as far as I'm aware, the biggest current use case for signing is the [ProZorro platform](http://prozorro.org/en/), where signing won't be done by the publisher of the OCDS files, so it's not necessarily appropriate to think about signing an entire file.

My understanding is that the biggest need for signing is of a single bid submitted to Prozorro. However, it is not sufficient to look at just signing the bid object, as the context where these are placed is also important (e.g. which tender the bid is for). Additionally, there may be some information in the bid object that it is appropirate for the central database to update.

One suggestion for this case, is a signing approach similar to [DKIM](https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail#How_it_works), where there is a statement of what fields are being singed. However, I've not been able to find anything like this for JSON (and writing our own crypto spec is a bad idea).

Additionally, in terms of context, we may want to be signing more than just the OCID or tender ID as context. We may want to sign that a bid is being placed against this exact OCDS record (which may have been signed by someone else). Depending on the requirements, this quite quickly becomes very complex.

I spoke with @myroslav about the needs of the Prozorro, and he hopes to get back to me with what the specific requirements of their use case are.

**Comment by timgdavies** [comment]
There have been no updates on this issue since 2015. Closing.
