### ISSUE TITLE
Proposal: Add milestoneType property and codelist to milestones

### ISSUE THREAD

**Issue by gabelula** [open-contracting/standard#227]
It is not clear if the milestones are associated with the ones we will have in the contract/implementation or the tender. It would be good to clarify that are the milestones that are going to expected in the contract/implementation.

**Comment by timgdavies** [comment]
Sorry for the slow reply on this. 

I believe during the drafting of the standard we found two potential uses to milestones:

(1) Describing deliverables expected in the contract/implementation

(2) Describing milestones during the tendering process itself (e.g. dates at which certain complex events as part of tendering may take place). 

At the moment our documentation within the schema itself states:

>"A list of milestones associated with the tender. See Milestone section for further details."

And then under the Milestones heading we have:

> "In the context of a tender block, milestones describe the key deliverables of a contract, or key points during the lifetime of the contract. These may have associated documentation."

We could modify the schema definition of tender/milestones to:

>"A list of key events and deliverables over the tender period, and anticipated events and deliverables the subsequent period of contract implementation."

And then in the documentation update it to read something like:

> "In the context of a tender block, milestones describe the key events and deliverables over the tender period, and anticipated events and deliverables the subsequent period of contract implementation. These may have associated documentation. 
>
>In the context of a contract implementation block, milestones are used to track progress towards those key events and deliverables set out in the tender. 
>
>Users may wish to compare the milestones in a tender block with those in contract implementation to see whether the contract covers all the timed deliverables tendered for, and with similar or changed deadlines."

Does this help clarify? Or do we need to drill down to more clarity?

**Comment by gabelula** [comment]
Yes. I understood that it was only related to (1) but now it is clear. How somebody would know if the tender/milestones that were added to the release are related to the tender or to the implementation?

**Comment by timgdavies** [comment]
Picking up on this issue, and reflecting more, I wonder if another option is to update milestones as of 1.1 of the standard to add a new property named '`milestoneType`` with a definition along the lines of "Used to distinguish milestones related to contract planning and formation, delivery and reporting".

And we then have a codelist with the following values:
- planning - For events during the planning phase of a process.
- engagement - For engagement milestones, such as a public hearing. 
- adjudication - For adjudication milestones, such as the meeting date of a committee.
- delivery - For delivery milestones, such as the date when a good or service should be provided.
- reporting - For reporting milestones, such as when key reports should be provided.

The goal of this would be to:
- Enable consuming applications to distinguish between the different kinds of milestones, whichever block they appear in;
- Allow publishers to be clearer about the kinds of milestones they are publishing;

**Comment by ekoner** [comment]
Added as a proposal - pending creating upgrade schema in fork of schema.

**Comment by timgdavies** [comment]
Developed into full proposal in #373
