### ISSUE TITLE
In schema documentation, format of 'Reference' is not clear

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#228]
In tables on the documentation, sometimes the format of a field is described as 'Reference'.

![screen shot 2015-08-15 at 09 37 40](https://cloud.githubusercontent.com/assets/342624/9288175/50fe2f9e-4331-11e5-9579-e7f4616d6def.png)

This appears to be the case when the field is actually an object, but which instead of being directly present there in the JSON schema, is pointed to via reference. 

This is not very intuitive for users, and should be changed to just say 'Object', perhaps linking to the relevant object at that point.

**Comment by timgdavies** [comment]
@bjwebb @kindly Could you have a glance at whether we can easily modify the scripts that generate these tables to address this issue?

**Comment by robredpath** [comment]
@Bjwebb mind if I take this for 1.0.2? I've looked through the code and think I can do this!

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
