### ISSUE TITLE
Managing codelists via JoinedUpData.org

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#230]
We are planning to improve how OCDS codelist management works this autumn (currently codes are maintained in a Google Spreadsheet, and imported into docs through a manual script). 

The Joined Up Data Alliance is offering use of a [SKOS Editor](http://www.w3.org/2004/02/skos/) at [http://joinedupdata.org/](http://joinedupdata.org/) which could be used to maintain an authoritative and versioned copy of our codelists. 

## Pros

* A ready made platform for managing codelists, including multi-language, and mapping between codes;
* OCDS codelists become available to map to other Joined Up Data codelists easily;
* SKOS is an open standard: we could port to other SKOS management tools in future;

## Cons

* PoolParty, which runs this, is proprietary;
* We're not in full control of the infrastructure

## Questions

* Could we alias http://codelists.open-contracting.org to allow us to serve all our codes with open-contracting.org URIs, and give us ability to port to other systems easily in future;
* Can we grant OCDS publishers access to their own sections of the system to record and map their own codelists (e.g. Mexico wanting their own list of procurement types)

@Bjwebb @caprenter @bill-anderson I would welcome your input on this. 

@bill-anderson: are you able to answer the questions above or point us to someone who could?

**Comment by timgdavies** [comment]
Implications of this are that we would need to:

- Import the codelists to PoolParty;
- Alias http://codelists. appropriately
- Update the Standard Collaborator to pull in the codelists from this new SSOT

**Comment by gabelula** [comment]
What about other open source options? I never used any of this SKOS but I'm looking at  http://openskos.org/ and http://protege.stanford.edu

**Comment by bill-anderson** [comment]
Poolparty allows for taxonomies (concept schemes) to be grouped in projects. You can have any number of Projects on the platform, and each project contain any number of concept schemes.

* Could we alias http://codelists.open-contracting.org to allow us to serve all our codes with open-contracting.org URIs, and give us ability to port to other systems easily in future;

I will check, but I'm pretty sure that all projects need to share the same base url. You can then set specific paths for projects and concept schemes which are used to generate concept uri's - but only beneath the base url

* Can we grant OCDS publishers access to their own sections of the system to record and map their own codelists (e.g. Mexico wanting their own list of procurement types)

Again I will check but I think users can be assigned to projects, but not to concept schemes or part thereof.

**Comment by timgdavies** [comment]
I've had a quick look at [OpenSKOS](https://github.com/CatchPlus/OpenSKOS) and it might be worth installing and assessing - particularly if there is a good way to import/export data to PoolParty to allow OCDS codes to be mapped against the others in the JoinedUpData platform.

Protege is good for ontologies in my experience, but not sure how well it works as a collaborative SKOS editor.

**Comment by akuckartz** [comment]
:+1: for using SKOS.

See also Skosmos and iQvoc.

**Comment by timgdavies** [comment]
For the time being we're not looking to take forward codelists in SKOS or via PoolParty, so closing this issue - but it might be something we can come back to in future.
