### ISSUE TITLE
How to specify sub-units within a unit

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#234]
Examples:
* Pads of paper bought in units of pads, but we also want to specify how many pages are in a pad
* Bottles of water bought in units of bottles, but we also want to specify what the volume of each bottle is

Currently this information can be placed in the description, but it might be good to have a common machine readable way of doing this.

This may relate to the "features" proposal - https://github.com/open-contracting/standard/issues/223#issuecomment-129429927

**Comment by timgdavies** [comment]
My sense is this would be dealt with well by the features property in #223

**Comment by LindseyAM** [comment]
@gabelula may be able to tell us if this is also an issue with the data in Mexico

**Comment by myroslav** [comment]
Here are the examples:
* 10 boxes containing 5 packs of paper each, 500 sheets of paper per pack
* 10 palettes containing 20 bottles each, 1.5l per bottle

This kind of details allow some calculations of what was bought and if price matched the subject.

Another goal is for tenderer to determine the amount of water needed if he has 1l water bottles, or number of boxes with 400 sheet packs.

**Comment by gabelula** [comment]
This is an issue for the Mexican case but I was recommending to just include it in the description of the item.

**Comment by timgdavies** [comment]
Closing as linked to #223 and will be handled there.
