### ISSUE TITLE
Lots

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#236]
A lot is a collection of one or more items which may be bid on / awarded within a tender. A tender may have multiple lots. One type of item may be split into multiple lots to encourage smaller bidders.

Different lots may have with different locations, delivery dates and times etc. 

There are a several possible options for implementing lots:
* Lots as a nested object within tenders (this breaks compatibility badly)
* A seperate lots array, that items then reference the relevant lot by ID (or lots reference items, but this way an item is only in in one lot is enforced)
* Each lot is represented as a subtender - as suggested for framework contracts - https://github.com/open-contracting/standard/issues/233

Are there any current examples of how lots appear in contracting data? Glancing through the TED XML schema, there's mention of lots, but I've not had chance to track down data using it yet (as not every TED tender does).

**Comment by timgdavies** [comment]
Resolving this is high priority for Paraguay and Ukraine. We should work up a proposed extension ASAP.

**Comment by timgdavies** [comment]
Based on the approach of a separate lots array, my proposal would be to include a ```lots``` array into ```tender```, ```award``` and ```contract``` which looks like this:

```json
{
  "lots":[
        {
           "id":"Lot-Identifier",
           "title":"Lot title",
           "description":"Lot description",
           "items":["array","of","item","identifiers"]
 ]
}
```

This model works without modifying the items array, by cross-referencing to items from within lots. 

Key questions:

**(1) Does this general model work?**

**(2) What else needs to be attached to lots?**

E.g. Do lots need delivery addresses? Does there need to be extra information about how many of each item are in a lot? 

**(3) Where are the examples of existing data using lots?**

I've not had good pointers shared yet - so any pointers to existing lots data would be useful to make sure we get this right as a proposed extension.


@myroslav @juanpane - your feedback would be particularly welcome here.

**Comment by myroslav** [comment]
We'd considered the approach you offer (`lots.items`), as well as `relatedLot` proerty approach. `relatedLot` approach appeared as better one, because with the `relatedLot` extra property items would belong to one and only one Lot (i.e. would be distributed among lots available). Additionally same property would be added to `Document`, `Award` (and our extensions: `Question`, `Appeal`, `Feature`, `Parameter`, `Bid.values`). Object without the `relatedLot` property would just relate to whole Tender. For `Contract` there should be different approach, since single contact can cover multiple lots, most probably the `Contract.relatedLots` should be array.

I.e. instead of "items" array for every lot (that allows same item to be allocate to different lots) we have reverse pointer from other objects back to Lot. This allows assignment of item to single lot only.

In our case every lot has `value` and `Tender.value` is sum of all lots. In our case every lot has `status` since every lot has its own awarding process and success/failure record. And in our case we are tracking auction parameters with Lot as well, i.e. `auctionPeriod`, `minimalStep`. Lot does not need separate delivery address, since item(s) belong to it and they have their deliveryAddress attached. Every item has quantity and unit attached, thus no need to have it attached to Lot. In fact we can have either identical or almost identical `items` array items belonging to different lots.

There are following examples of division of Tender into lots:
 1. The total amount of items to be delivered is split in progressive quantity amounts to facilitate participation of small and large participants allowing even small tendered to compete for a fraction of Tender.
 2. The items to be delivered can have different `deliveryAddress`-es, and with significant logistics expenses there can be sense to split them into lots just to allow different regional providers to have the tenders.
 3. The diversity of items to be delivered into Tender is quite big despite sharing the same CPV group. To enable participation of companies that specialize in areas more specific then CPV group, the Tender is split into lots on "lower" classification level (on CPV classes, or even CPV categories).

**Comment by timgdavies** [comment]
Thanks @myroslav. What you describe makes a lot of sense.

So - if I summarise for the moment:

* A tender may have a ```lots``` array, providing details of each of the lots, their values, and other key information about them;
* Items, Documents, Awards and Contracts may all have a ```relatedLot``` property, pointing to the lot identifier;
* For the purposes of OCDS, lot identifiers should should at least be unique within the contracting process they relate to; 

If this sounds like it captures things, then I suggest you continue developing based on this approach, and when we've got some sample data, and another lots use-case to work with, we review what a formal extension to OCDS should look like.

**Comment by timgdavies** [comment]
From Jiri via discussions on DigiWhist data model:

>the point on forum [thread above] is imho generally correct. However even TED has problems distinguishing multiple lots from multiple winners of framework agreement (which is essentially single lot). Thus we have 1:N contract-lot relation plus nested 1:N lot-winner relation, which is complicated but seems as only accurate alternative.
>
>Simplifying approach is to treat each lot as individual contract - in practice this however causes confusion for lawyers and additional problems, so we prefer the first approach.

**Comment by juanpane** [comment]
The proposed extentions seems to fit all the needs of the public contracting process in Paraguay related to "lots". We are producing some examples based on real data that we will share as soon as possible

**Comment by AlCollier** [comment]
Not sure I agree that contract:lot is a 1:N relationship - I think (at least in UK terminology) it's N:N. A framework agreement may have multiple lots, and multiple providers may be appointed to each lot. Each appointed provider will have a contract relating to that lot.

-----Original Message-----

**Comment by myroslav** [comment]
The only thing I'd like to highlight that Documents (and potentially other
objects, like Question, that we have in ProZorro) besides relatedLot
property are getting retatedTo property as well with possible values of
tender, tenderer, lot, item and corresponding relatedTenderer, relatedLot,
relatedItem properties.

On Monday, 5 October 2015, timgdavies <notifications@github.com> wrote:

> Thanks @myroslav <https://github.com/myroslav>. What you describe makes a
> lot of sense.
>
> So - if I summarise for the moment:
>
>    - A tender may have a lots array, providing details of each of the
>    lots, their values, and other key information about them;
>    - Items, Documents, Awards and Contracts may all have a relatedLot
>    property, pointing to the lot identifier;
>    - For the purposes of OCDS, lot identifiers should should at least be
>    unique within the contracting process they relate to;
>
> If this sounds like it captures things, then I suggest you continue
> developing based on this approach, and when we've got some sample data, and
> another lots use-case to work with, we review what a formal extension to
> OCDS should look like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-contracting/standard/issues/236#issuecomment-145529470>
> .
>


-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by timgdavies** [comment]
I've had a shot at a JSON Patch for the schema which captures the discussion above, and factors in a few extra fields required by TED.

The patch is below. Comments welcome on titles, terms and definitions used in here. I've essentially followed the [openprocurement API structure](http://api-docs.openprocurement.org/en/latest/standard/lot.html) structure, and tried to use definitions that make sense for TED also. 

We can work up some example data and a fully documented extension on this soon.  

```json
[    {
        "op": "add",
        "path": "/definitions/Tender/properties/lots",
        "value": { 
            "title": "Lots",
            "tedMapping":"LOTS",
            "description": "In some systems, a tender process may be divided into lots, where bidders can bid on one or more lots. Details of each lot can be provided here. Items, documents and other features can then reference their relatedLot.",
            "type": ["object", "null"],
            "properties": {
                "id": {
                    "title":"id",
                    "description": "A local identifier to reference this lot. Used in relatedLot references.",
                    "type": ["string", "integer"]
                },
                "title": {
                    "title":"Title",
                    "description":"A title for this lot",
                    "type":["string","null"]
                },
                "description": {
                    "title":"Description",
                    "description":"A description of this lot",
                    "type":["string","null"]
                
                },
                "status":{
                    "title": "Lot Status",
                    "description": "The current status of tendering related to this lot based on the [tenderStatus codelist](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists#tender-status)",
                    "type": ["string", "null"],
                    "enum": ["planned", "active", "cancelled", "unsuccessful", "complete", null]
                },
                "value":{
                    "title":"Lot value",
                    "description": "The maximum estimated value of this lot.",
                    "$ref": "#/definitions/Value"
                }
            }
        }
    },
    {
        "op": "add",
        "path": "/definitions/Item/properties/relatedLot",
        "value": {
            "title":"Related Lot",
            "description":"If this item belongs to a lot, provide the identifier(s) of the related lot(s) here.",
            "type":["array","null"],
            "items": {
              "type":["string","integer"]
            }
        }      
    },
    {
        "op": "add",
        "path": "/definitions/Document/properties/relatedLot",
        "value": {
            "title":"Related Lot",
            "description":"If this document relates to a particular lot, provide the identifier(s) of the related lot(s) here.",
            "type":["array","null"],
            "items": {
              "type":["string","integer"]
            }
        }      
    },
    {
        "op": "add",
        "path": "/definitions/Milestone/properties/relatedLot",
        "value": {
            "title":"Related Lot",
            "description":"If this milestone relates to a particular lot, provide the identifier(s) of the related lot(s) here.",
            "type":["array","null"],
            "items": {
              "type":["string","integer"]
            }
        }      
    },
    {
            "op": "add",
            "path": "/definitions/Tender/properties/lotDetails",
            "value":{
              "type":["object","null"],
              "title":"Lot Details",
              "description":"If this tender is divided into lots, details can be provided here of any criteria that apply to bidding on these lots. This extended property is currently focussed on fields required by the EU TED data standard",
              "properties":{
                 "maximumLotsPerSupplier": {
                     "type":["integer","null"],
                     "title":"Maximum lots per supplier",
                     "description":"The maximum number of lots that may be awarded to one supplier as part of this contracting process."
                 },
                 "combiningContractRight": {
                    "type":["string","null"],
                    "title":"Combining Contract Right",
                    "description":"The contracting authority reserves the right to award concessions combining lots and groups of lots as described in this field."
                 }
              }
            }
    }
]
```

**Comment by robredpath** [comment]
#317 is related - contract type/payment terms info will need to be added at the lot level

**Comment by timgdavies** [comment]
Continued in #381.
