### ISSUE TITLE
Contracts relating to more than one award

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#237]
In Zovnishtorgvydav data, some contracts relate to more than one award. This is generally because those awards are for different lots (see also issue for describing lots https://github.com/open-contracting/standard/issues/236).

In the short term, this could be implemented in OCDS by duplicating the contract block for each award. Longer term, might we want `awardID` to be an array?

**Comment by timgdavies** [comment]
We should give serious consideration to awardID being an array.

**Comment by timgdavies** [comment]
Views welcome on the implications of making awardID an array.

**Comment by timgdavies** [comment]
This would not be a backwards compatible change, and so will not be considered for 1.1.

The short term solution proposed by Ben appears to be a reasonable one.
