### ISSUE TITLE
CEN BII

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#238]
Stakeholders in Ukraine have mentioned that they are interested in using CEN BII for electronic documents in the eprocurement system. It would be good to work out how publication of these documents fits with the OCDS.

**Comment by timgdavies** [comment]
[CEN BII](http://www.cenbii.eu/) is focussed on 'Business Interoperability Interfaces' and involves a lot of detail on business processes (transactional exchange of procurement information) that goes beyond the focus of OCDS on disclosure of key information about a contracting process.

At some future point, a mapping between CEN BII data and OCDS to support disclosure by implementers of CEN BII standards may be relevant, but over the short-term, it looks to me like there is limited justification for strong OCDS engagement with CEN BII.

**Comment by timgdavies** [comment]
We recently participated in CEN-BII event and wrote up the learning here: http://www.open-contracting.org/2016/03/11/standards-eservices-and-open-contracting-in-the-eu/

Keeping an eye on CEN-BII developments, but no concrete action from this issue right now - so closing.
