### ISSUE TITLE
Improve documentation of releases vs records

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#239]
Releases vs records is still a major point of confusion, we probably want:
* To check if the standard documentation can be improved.
* Better worked examples of merging releases to form records. @timgdavies started working on this, but got stuck becasue the compiler is not up to date with 1.0. https://github.com/open-contracting/compiler/issues/3
* Better explanation in our slide deck, building on the above.

**Comment by timgdavies** [comment]
We definitely need a good reference implementation here - including not only compilation but also merging. 

Hoping @Bjwebb can find some time to work on the compiler and merge tool - and then I can work from there on some updated documentation using the worked examples...

**Comment by Bjwebb** [comment]
"including not only compilation but also merging" - I'm confused, I thought that compiling a record is the OCDS specific term for doing a JSON merge? https://github.com/open-contracting/compiler is the OCDS piece of software which calls https://github.com/open-contracting/jsonmerge, the generic one.

**Comment by timgdavies** [comment]
I don't see any jsonmerge requirements in the compiler, nor where it is running jsonmerge - so unless I'm missing something I don't think this is running the merge process.

**Comment by Bjwebb** [comment]
@timgdavies Yes, you're quite right, I must have got the wrong end of the stick.

**Comment by timgdavies** [comment]
We have now strengthened the documentation and in #218 are working on updates to the mapping spreadsheets to help clarify releases and records.

We will continue to work on this, but closing this issue for now as no specific action arising from it.
