### ISSUE TITLE
EU TED (Tenders European Daily) to OCDS mapping

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#240]
EU countries must publish tenders (and awards?) to TED, so there is interest in being able to convert this format to/from OCDS.

TED data is available in XML, see: http://ted.europa.eu/TED/misc/news.do and http://ted.europa.eu/TED/misc/legalNotice.do . The XML is available via FTP at ftp://ted.europa.eu/ (see previous links for contact address for password).

We may want to look at what others are doing with TED data, e.g. OpenTED http://ted.openspending.org/

**Comment by timgdavies** [comment]
+1 - I've dropped a line to the TED Web team to see if they are interested in exploring this too.

**Comment by LindseyAM** [comment]
+2 I think this is a priority and we should even put documentation on the standard site about how publishing OCDS can facilitate TED compliance

**Comment by akuckartz** [comment]
:+1:

**Comment by AlCollier** [comment]
Don't think we can "facilitate TED compliance". EU procurers are required to submit contract notices to TED, either by typing them into TED or more usually by submitting in XML format from their e-tendering system.

To get OCDS data out, we need to persuade TED to include a field for OCID. 

Now may be a good time as TED need to rework their forms to fit with the new EU procurement directive which member states are in the course of implementing.

-----Original Message-----

**Comment by timgdavies** [comment]
Agreed. I've been in touch with some of the TED team to see if we can set-up a workshop. Waiting to hear back at the moment. 

I think the ideal is that there is some alignment between OCDS and TED so that we're not asking people to use radically different data structures for each - even if there will be a need to serialise in distinct formats and map between the two at some level.

**Comment by timgdavies** [comment]
Quick update: we've talked with someone from the TED team. 

Working up a note on potential for collaboration / linkages between OCDS and TED with a view to doing some mapping work in November.

Let me know if you would be interested in contributing to the draft - I'll share here once in a coherent state...

**Comment by AlCollier** [comment]
Tim happy to take a look regards Al

-----Original Message-----

**Comment by timgdavies** [comment]
I've [worked up a draft note here](https://docs.google.com/document/d/1-bdDjSmfVsjwAm6-k_bRs3CRfibISrmhSz5z3rZTD4E/edit#). Comments on this before end of Tuesday would be very welcome - as we'll try and finalise copy to share with TED team then.

**Comment by timgdavies** [comment]
There is work underway on this mapping. Work to date is documented at https://timgdavies.github.io/ocds-ted/ and we'll be updating soon with more updates, and hopefully a full extension. 

@duncandewhurst is taking the next pass of mapping.

**Comment by timgdavies** [comment]
We now have a more developed OCDS <-> TED mapping which will be published in the next few months. Anyone in need of advanced access, please drop me a line via data@open-contracting.org
