### ISSUE TITLE
Schema.org extension proposal

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#242]
The idea is to propose OCDS-based [extension](https://schema.org/docs/extension.html) for schema.org, to enable web sites to mark up procurement information in HTML pages for data extraction by search engines and buildup of semantic web.

The closest initiative is schemaorg/schemaorg#448. The other issues that are already there and hosted by schema.org are:
- http://auto.schema.org/ - `auto`: Auto Extension, adds following childs to [Vehicle](https://schema.org/Vehicle): [BusOrCoach](http://auto.schema.org/BusOrCoach), [Motorcycle](http://auto.schema.org/Motorcycle), [MotorizedBicycle](http://auto.schema.org/MotorizedBicycle) objects
- http://bib.schema.org/ -  `bib`: Bibliographic Extension adds a lot of childs, grandchilds and other descendants to [CreativeWork](https://schema.org/CreativeWork) object.

Extension after adoption becomes part of the [full hierarchy, select "Core plus all extensions"](https://schema.org/docs/full.html) (note blue terms, they are from extensions).

The OCDS extension would allow search engines (and other data extraction and linking tools) extract information from sites publishing public procurement information. The stretch goal is to organize the extracted information into DBpedia, Freebase, etc. And the final goal is to have it all plugged into systems like Google Knowledge Graph, to increase accessibility of information.

**Comment by akuckartz** [comment]
I am interested in collaborating a bit in this effort.

**Comment by myroslav** [comment]
@akuckartz we have JSON Schemas. For instance see [standard/schema/release-schema.json](https://github.com/open-contracting/standard/blob/master/standard/schema/release-schema.json). Some of the objects already exist at schema.org, i.e. we'd have to reuse them. Is that possible to add extra properties to existing schema.org objects, or I'd have to generate descendant object and add the property there?

**Comment by timgdavies** [comment]
This is a really interesting idea - and would be really happy to support this. 

What would it take to get an activity around this started?

**Comment by myroslav** [comment]
Regarding my question about adding properties to core schema.org objects.

I'd seen already extra properties that [`auto` extension](http://auto.schema.org/) adds to [Vehicle](https://schema.org/Vehicle). See "Available properties in extensions" section and [accelerationTime](http://auto.schema.org/accelerationTime) property as an example.

**Comment by myroslav** [comment]
Additionally see following issues regarding process of development and publishing the `auto` extension:
 * schemaorg/schemaorg#509: Meta-Issue: Automotive Extension
 * schemaorg/schemaorg#704:  auto.schema.org final review tracking

**Comment by AlCollier** [comment]
+1

**Comment by timgdavies** [comment]
Ok. I had a brief chat with @jenit to get some insights into this, and the main take-away I had from that is that this could be a good path to go down, but we should:

(a) Think about the proposition for search engines or other consumers of this data, and make sure we have this clear. Which platforms might display contract information, and what is the key information they would want to display?

(b) Think carefully about how to frame this as a complement to, rather than replacement for, publishing comprehensive OCDS;

I suspect taking this issue forward might also link with #40 around JSON-LD support for OCDS, as that will also involve us mapping from OCDS to existing vocabularies.

**Comment by elf-pavlik** [comment]
:+1:  http://blog.schema.org/2013/06/schemaorg-and-json-ld.html

**Comment by timgdavies** [comment]
Has anyone been working on this? Any interest in future work on this?

**Comment by jpmckinney** [comment]
Closing as no strong or recent interest expressed.
