### ISSUE TITLE
Document Versions (temporal versioning and different formats)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#243]
The discussion in #224 has raised the need for a new property (or properties) for the `documents` object to:
- (A) Indicate when documents are subsequent versions of a past document (e.g. when a report is revised)
- (B) Indicate when documents are alternative format versions of a document;

Use case (B) is particularly important for digital signing of documents (the focus of #224) where a publisher may wish to link to an easily readable version of a document (e.g. PDF), and then to a copy of that same document within a signed container.

**Comment by timgdavies** [comment]
Some notes from looking at existing standards and schema:

## Schema.org

Under the [CreativeWorks](https://schema.org/CreativeWork) class (under which documents would probably fall), schema.org has:

* A ```version``` field for which can be used for version numbers;
* An ```encoding``` field which can be used to point to other works which are a different encoding of this entity.

## DCTerms

In Dublin Core terms, there is:

* [isVersionOf](http://dublincore.org/documents/dcmi-terms/#terms-isVersionOf) - defined as "A related resource of which the described resource is a version, edition, or adaptation." but with the comment "Changes in version imply substantive changes in content rather than differences in format."
* [isFormatOf](http://dublincore.org/documents/dcmi-terms/#terms-isFormatOf) - defined as "A related resource that is substantially the same as the described resource, but in another format."

**Comment by timgdavies** [comment]
Any solution will need to also incorporate recommendations as to whether versioning and formats should be based on:

* One master document, with subsequent versions and formats;
* A network of relationships;

A worked example should help illustrate. 

## Worked example

Imagine a document (```document-v1.doc```) which is then (a) converted into PDF format; and (b) revised twice. This results in 6 documents:

* document-v1.doc
* document-v1.pdf
* document-v2.doc
* document-v2.pdf
* document-v3.doc
* document-v3.pdf

It is clear that **document-v2.doc** ```isVersionOf``` **document-v1.doc**

It is also clear that **document-v1.pdf** ```isFormatOf``` **document-v1.doc**

And that **document-v2.pdf** ```isFormatOf``` **document-v2.doc**

*However*, when we get to **document-v3.doc** this can either be ```isVersionOf``` **document-v1.doc** or **document-v2.doc**. Which should be used? 

Similarly, the relationship that **document-v1.doc** ```isFormatOf``` **document-v1.pdf** is implicit - but should it be made explicit? 

And should **document-v2.pdf** ```isVersionOf``` **document-v1.pdf** be explicitly stated?

It appears to me that this has quite big consequences for tools that want to meaningfully interpret and display document information. 

The distinction in approach would be between a **Master Document** approach, in which for any versioning series, and any collection of formats, one document must be treated as the master document against which all references are made - and a **Document Network** approach, in which all the possible relationships could / should be stated.

**Comment by jpmckinney** [comment]
Flagging that this has come up with ResourceCountracts (the same document has a PDF version, Word version, text/html version on DocumentCloud, and plain text version as OCR).

**Comment by jpmckinney** [comment]
In terms of modeling, see also [DCAT](http://www.w3.org/TR/vocab-dcat/)'s distinction between Dataset and Distribution.

See also the [PROV Ontology](http://www.w3.org/TR/prov-o/) which is perhaps the most complete model for this.

**Comment by jpmckinney** [comment]
In an RDF system with entailments described by OWL, these questions can be answered without having to make all possible statements.

> However, when we get to document-v3.doc this can either be isVersionOf document-v1.doc or document-v2.doc. Which should be used?

"isVersionOf" is used to refer to [a former version](http://wiki.dublincore.org/index.php/User_Guide/Creating_Metadata#IsVersionOf). So, v3 should be a version of v2, assuming the versions are actually sequential and not branching. If we care deeply about not misleading people as to the actual sequence, then all later documents can be a version of the first document.

In most cases, I think we will not know the actual facts, so having everything as a version of a master document is simpler and likely more accurate.

> Similarly, the relationship that document-v1.doc isFormatOf document-v1.pdf is implicit - but should it be made explicit?

You could tag the property `isFormatOf` as `owl:SymmetricProperty` to avoid making it explicit.

> And should document-v2.pdf isVersionOf document-v1.pdf be explicitly stated?

It's possible to write an entailment rule so that all formats of a document are versions of all formats of another document. It's OK for a PDF to be a version of a DOC because the DC property is [defined](http://dublincore.org/documents/dcmi-terms/#terms-isVersionOf) as "Changes in version imply substantive changes in content rather than differences in format."

**Comment by jpmckinney** [comment]
See the ResourceContracts.org discussion at https://docs.google.com/document/d/1YskkbslvOfmrzL_PV7zngO23H6IXwn3RwosA39jhrjQ/edit#heading=h.sr6b2mk4h6l

**Comment by timgdavies** [comment]
Views on the importance of this for version 1.1 would be welcome

**Comment by timgdavies** [comment]
I've reviewed the Resource Contracts discussion - but did not find anything substantive to add to proposals here (the concept of whether or not a document should be counted in a tally is an interesting user requirement, but inclusion of a field for this feels application specific).

The proposal for 1.1 then is to create an **extension** which includes

* isFormatOf
* isVersionOf 

following the DCTerms semantics for these properties.

This extension is currently a low priority - and as it will be an extension, will only make it into the formal 1.1 process if ready in time. This does not prevent it getting included as a community extension easily post the formal 1.1 launch.

**Comment by timgdavies** [comment]
This was left out of 1.1 on grounds of available time, and as it will be possible to add as a community extension at a later date.

As there were no calls for a focus on this during the 1.1 process. I'm closing the issue. It could be re-opened if there was future demand.
