### ISSUE TITLE
Description of "changes" is now misleading

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#244]
> Comma-seperated list of affected fields.

But, changes should now be an array of objects.

**Comment by practicalparticipation** [comment]
Well spotted. This is a bug we will need to address.

**Comment by kindly** [comment]
Link to relevant description:
https://github.com/open-contracting/standard/blob/1.0/standard/schema/release-schema.json#L789

**Comment by timgdavies** [comment]
I suggest we stage this for fixing as soon as we start on edits to 1.0-dev schema

**Comment by Bjwebb** [comment]
We think that this issue should be included in 1.0.2, to be released in September, because it is a bug fix.

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
