### ISSUE TITLE
In what scope must a release ID be unique?

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#246]
According to http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/release/:

>  A releaseID must be unique within a release-package

Which implies that two release packages may re-use the same release ID. It would also be possible for these two releases with the same ID to belong to the same contracting process.
If so, it becomes difficult to interpret the versionedRelease within a record:

e.g. 

``` json
    "versionedRelease": {
        "ocid": "A",
        "tender": {
            "id": "A",
            "procurementMethod": [
                {
                    "value": "Selective",
                    "releaseDate": "2014-01-01",
                    "tag": "tender",
                    "releaseID": "1"
                },
                {
                    "value": "Open",
                    "releaseDate": "2014-01-02",
                    "tag": "tender",
                    "releaseID": "1"
                }
            ]
        }
    }
```

**Comment by practicalparticipation** [comment]
This is a good point. It should be: within a contracting process AND
release package.

This said, some publishers do appear to have difficulty updating release ID
when data changes (eg. When serving the current state of contracts from an
API and the underlying data does not have a version number) so a robust
merge algorithm may want to either warn when there are two items with the
same ocid and release id, and/or to additionally sort them by release date
when merging.

**Comment by akuckartz** [comment]
Can't a (unique) URL be used instead ?

**Comment by timgdavies** [comment]
A URI *can* be used, but we don't want to require that a URI *must* be used, as for some publishers this becomes a barrier to publication (they are concerned that such URIs must then exist and be functioning, and we get into URI policies of different countries).

So - in the schema most IDs are strings, but that would permit URIs (with some constraints).

The one constraint in the release id case, is that we suggest they should not contain #, as # is reserved for us as a fragment identifier when looking up a release within a release package (e.g. package_uri#release.id)

**Comment by timgdavies** [comment]
There seems to be an uncontroversial change here of updating the description to:

"A releaseID must be unique within the scope of it's related contracting process (ocid), and unique within any release package it appears in." 

in 1.1. This is in-line with the guidance we have been giving publishers, and I'm not aware of any data which does not respect this principle.

**Comment by timgdavies** [comment]
I've staged an update with the following updated description for ```release.id```

> An identifier for this particular release of information. A release identifier must be unique within the scope of it's related contracting process (defined by a common ocid), and unique within any release package it appears in. A release identifier must not contain the # character.

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> Just to make sure this was considered: could there be any interplay between releaseIDs and relatedProcesses? For example, if I want to work with data for an unsuccessful (cancelled) procurement process and a related procurement process which afterwards successfully bought the same thing, could there be any problems resulting from the fact that a same releaseID was used in both processes?

**Comment by jpmckinney** [comment]
The phoenix rises: https://github.com/open-contracting/standard/issues/455

**Comment by jpmckinney** [comment]
@JachymHercher To answer your question, release ID should be paired with the process ID (`ocid`) to form a unique key. Release IDs are not intended to be globally unique across processes.
