### ISSUE TITLE
releaseID vs id vs Release ID

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#247]
In different parts of the standard we have as field names `id` (if it's directly in a release) or `releaseID` (if it's some other context where we need to specify. In both cases we refer to it in English as "Release ID" (with a space).

However, sometimes the documentation uses one field name when we're talking about the other:
e.g. for `id` on http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/release/
> A releaseID must be....

Should we be using the English "Release ID" here instead?

**Comment by timgdavies** [comment]
The mis-use in question is found in the schema itself, so should be corrected there. 

I can look at tidying this up as part of the bug fixed schema.
