### ISSUE TITLE
statusDetails Field missing

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#248]
The documentation for the [Award Status](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#award-status) codelist entry for 'unsuccessful' states that: 

> "This award could not be successfully made. If items or supplier details are included within the award section, then these narrow the scope of the unsuccessful award (i.e. the award of noted items, or an award to the noted supplier, was unsuccessful, but there may be other successful awards for different items listed in the tender, or to different suppliers). The reason that the award did not suceed will be given in the statusDescription field."

Apart from the type in succeed, we also have the issue that no '`statusDescription`' field exists in the schema. 

This appears to be a bug - and such a field should have been created.

**Comment by timgdavies** [comment]
(statusDescription was proposed in #143 but it appears it was not incorporated into the final schema)

**Comment by jpmckinney** [comment]
It's not clear that #143 had any concensus about `statusDescription` - hence it wasn't added (I think you were the only person talking about it, Tim :) )

**Comment by jpmckinney** [comment]
But, FWIW, `statusDetails` would be more consistent with other field names.

**Comment by timgdavies** [comment]
See pull request: #257

**Comment by timgdavies** [comment]
Ok - renaming this to statusDetails and pushing to 1.1 discussions.

**Comment by timgdavies** [comment]
The phrase "The reason that the award did not suceed will be given in the statusDescription field." has been removed from the codelist in 1.0.1 bugfix release.

Views for, or against, inclusion of `statusDetails` in 1.1 are welcome. 

We would need to see interest in this field, and examples of data that would fill it, to take forward.

**Comment by timgdavies** [comment]
There have been no voices in favour of ```statusDetails```, nor further requests for this field. 

This will not be actioned as part of 1.1. Closing.
