### ISSUE TITLE
Documentation should indicate the case to use for external codelist entries

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#252]
We defer to [ISO_4217](https://en.wikipedia.org/wiki/ISO_4217) for currency codes.

Although these are generally written in uppercase, we do not make this explicit. 

Our validators and documentation should make this explicit.

**Comment by timgdavies** [comment]
This will go forward into the first round of 1.1 updates unless objections are raised. 

We will document which case we are recommending, so that any comments can be raised at that point.

**Comment by timgdavies** [comment]
#297 has addressed this for currency codes.

**Comment by timgdavies** [comment]
I've reviewed codelists in use, and the only other one needing case specified I could find was language codes.

This now specifies lowercase language codes.

**Comment by timgdavies** [comment]
Assigning to dev team to check if there are any implications for the validator from this.

I.e. does the validator check adequately for case of currency and language codelist entries?

**Comment by Bjwebb** [comment]
The validator currently doesn't check currency or language codelist entries.

We refer to BCP47 https://tools.ietf.org/html/bcp47 for our language fields, this says:
>    At all times, language tags and their subtags, including private use
>   and extensions, are to be treated as case insensitive: there exist
>   conventions for the capitalization of some of the subtags, but these
>   MUST NOT be taken to carry meaning.

Moreover these conventions are mixed case for some codes, e.g. en-GB
