### ISSUE TITLE
Should the standard permit negative amounts?

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#253]
This issue is under consideration for the 1.1 milestone. 
## The problem

The amount building block in OCDS currently has a validation rule setting the minimum to zero.
This means that negative values and transactions are not allowed.

However, negative values are possible:
- When the contract involves a concession payment from contractors to government;
- When an amendment reduces the overall value of a contract;
- When a transaction involves a refund;

and in other circumstances. 
## The proposal

We will remove the minimum value validation rule from the schema.

We will introduce guidance to state that:
- Where a minus value represents a payment from the contractor to the government, this payment should be explicitly declared in `contract.implementation.transactions`. 
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.
## History

This issue was originally opened with the comment that:

> Canada's data includes negative amounts for some contract values. 
> 
> This fails against validation at present.

It was updated on 13th Sept with a clear proposal for the upgrade.

**Comment by AlCollier** [comment]
Negative amounts are possible. For example, in letting a concession contract, where the winner gets the right to collect revenue from users, bids may range from positive amounts (where the bidder needs a subsidy in addition to its income from users) through to negative amounts (where the concession is lucrative enough for the bidder to pay for the privilege).

-----Original Message-----

**Comment by timgdavies** [comment]
We will look towards allowing negative values in Version 1.1. 

This should be included in the 1.1 consultation.

**Comment by mireille-raad** [comment]
We had the same issue/story in Moldova. For example: http://etender.gov.md/contracte

![moldova-neg-values](https://cloud.githubusercontent.com/assets/521705/16502491/ac8b1b4a-3edc-11e6-8b2b-8b8db82a8548.PNG)

It will be good to get some guidance on how those negative numbers affect the charts showing "total values" of contracts for example.

I hope this can be finalized in 1.1 :)

**Comment by timgdavies** [comment]
As we take this forward, I can envisage two cases:

**(1) Where negative amounts are as a result of adjustments** 

**(2) Where negative amounts are as a result of payments due to government** 

It strikes me we should try and make sure we are explicit about these different cases. 

@dc-coder In the Moldova examples above, how should the negative amounts be interpreted?

**Comment by chrisalexsmith** [comment]
Contracts may include a negative amount for a price discount.

**Comment by timgdavies** [comment]
I've made a number of schema changes [which can be seen here](https://github.com/open-contracting/standard/commit/c251c0bb21ace026c6b2232a1489efc1113cfaa2) to:

* Update value to allow negative amounts
* Document the logic of negative amounts in budget, tender, award and contract. 

This helps to address the issue of negative amounts as payments to government, and negative amounts in transactions as either refunds or corrections.

However, it does not explicitly address the case where a publisher mis-uses the releases model to provide the adjustment value in ```tender.value``` or ```award.value``` rather than providing the **revised value**. 

I think this might be possible to address through a worked example for #357 to focus on adjustments in values.

**Comment by duncandewhurst** [comment]
Re-opening and adding 1.0.3 bugfix milestone

**Comment by timgdavies** [comment]
In the 1.0.3 branch I'm planning to only update the schema, without the additional change to the documentation for each field. This means negative numbers will validate: but the clarification of the  semantics for negative numbers, as presented in 1.1, will not display in 1.0 docs.

This is in order to avoid needing additional translations of 1.0, or updates to other tools using 1.0.

**Comment by jpmckinney** [comment]
Fixed in #514.
