### ISSUE TITLE
Need to review Award Criteria Codelist re Most Economically Advantageous Tender

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#254]
Via @Myroslav

> is bestValueToGovernment
http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#award-criteria
the value to be used for MEAT tenders
http://www.felp.ac.uk/content/most-economically-advantageous-tender-meat?
>In a side note, if talking about information encoded in the value. Why
"Government" is mentioned there? What if procuringEntity is private company?

My thoughts: 

On BestValuetoGovernment v. BestProposal, I dont quite recall setting these distinctions and the origins in the reviewed data....Did we see examples of these distinctions in practice (My guess is that BestValue could imply a balance between technical and financial evaluation scores (80/20?) and BestProposal could technical evaluation only?)

MEAT seems to allow for best pricequality ratio AND lowest price to be the decisive criteria, among other considerations like green procurement, it seems to be a catch all (so I think we need to define the ones we have put on our documentation and then decide whether another cateogry is needed? This may benefit from some conversation with the EU TED or the UK team).  I am curious if MEAT is EU or UK specific

**Comment by myroslav** [comment]
In our case we have bid that consist of price and set of `Parameter`s that participate in predefined formula. From these so called "Normalized Price" is derived that all Tender participants are ranked with during qualification stage.

This is to reduce the ability of subjective decisions. And if there is still need to have any subjective decisions, that evaluation will still be performed on the `Parameter` level with subsequent Auction to give chances to participants to compete.

**Comment by timgdavies** [comment]
We discussed today the need for us to add better definitions to codelists (and review them to address the points you raise here Myroslav about 'Government' in the code which shouldn't really be there) for the upcoming 1.1 version. 

Given this is an open codelist (i.e. it is possible to for local extensions) I would not try and squeeze into an existing code if it doesn't capture the idea properly. 

I found [this explanation of MEAT useful](http://www.felp.ac.uk/content/most-economically-advantageous-tender-meat): 

>The most economically advantageous tender (MEAT) criterion enables the contracting authority to take account of criteria that reflect qualitative, technical and sustainable aspects of the tender submission as well as price when reaching an award decision.
>Any criteria used must be linked to the subject-matter of the contract in question.  The Regulations state that award criteria shall be considered to be linked to the subject matter of the contract where they relate to the works, supplies or services to be provided under that contract in any respect and at any stage of their life-cycle, including factors involved in:
>the specific process of production, provision or trading of those works, supplies or services; or
>a specific process for another stage of their lifecycle,
>even where those factors do not form part of their material substance.
>As early as possible in the process, preferably when the requirement is advertised in the OJEU, the criteria will be published and advised to the potential tenderers.
>The relative weighting of each criterion used to assess the submissions must be stated or, where this is not possible for objective reasons, they should be stated in descending order of importance.

I wonder whether something like ```weightedScores``` would capture the idea better? 

If you were not trying to map this to OCDS @myroslav what term would you use? 

I'm looking again for codelists of award criteria from other sources, but not turning up much...

**Comment by myroslav** [comment]
We call the other factors as "non-price criteria". And each criteria has "percent" weight, i.e. fraction of 100%.

Thus the winner being awarded has best price taking into consideration `Parameter`s of his bid weighted against weight of each `Feature` defined in tender conditions. Price weight is "leftover" from `Feature`s weight.

Thus the criteria is formula mixing `Price` and `Parameters`, according  to weights of these factors defined in tender conditions as `Features`.

**Comment by LindseyAM** [comment]
[Procurement Monitoring Guide - Final - Interactive PDF.pdf](https://github.com/open-contracting/standard/files/268334/Procurement.Monitoring.Guide.-.Final.-.Interactive.PDF.pdf)

See annex 1 page 94

**Comment by timgdavies** [comment]
Continued in #385
