### ISSUE TITLE
Tender.Item.Unit without Value [Mexico City]

### ISSUE THREAD

**Issue by gabelula** [open-contracting/standard#256]
Hi,

For the items in Tender we have all the name of the units considered but we don't have (and will never have) the value per unit. On one side it seems correct to remove the whole unit (because it does not validate to ocds) but on the other side we are loosing the name of the unit being considered and it seems wrong to loose information. Ideas?

**Comment by timgdavies** [comment]
Are the units just being used to distinguish between goods and services?

Or are the units you have things like: 'miles', 'barrels', 'boxes' etc?

**Comment by gabelula** [comment]
Actually, both of them. They have SER (as a code for services) and PKG (a code for packages) for example. They have a list of codes for units that can be published.

**Comment by timgdavies** [comment]
On further testing it looks like the Mexico use the fields is working and validating correctly.
