### ISSUE TITLE
Status description field

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#258]
See pull request: #257

**Comment by timgdavies** [comment]
From @gabelula:

> Would be useful to have an awardStatusDetails (as free text) to add information about why an award was unsuccessful or anything related with the status but so far we don't have it

**Comment by gabelula** [comment]
Related with https://github.com/open-contracting/standard/issues/248

**Comment by jpmckinney** [comment]
Seems to be exact duplicate of #248.

**Comment by timgdavies** [comment]
Good point. Closing this and moving to #248.
