### ISSUE TITLE
TED: Buyer type

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#262]
Via @olafveerman from the [Procurement Analytics](https://github.com/procurement-analytics/compranet-data) project:

> For procurement analytics it is useful to know the type of government entity involved in the procurement
> 
> Procurement Analytics added a `buyer/type` property for this

We should consider whether any relevant property or taxonomy could be added to 1.1.

**Comment by AlCollier** [comment]
There's a taxonomy of this sort inTED

-----Original Message-----

**Comment by timgdavies** [comment]
From a [TED standard form](http://simap.ted.europa.eu/documents/10184/49059/sf_001_en.pdf), I find 'Type of Contracting Authority' with entries for:

* Ministry or any other national or federal authority, including their regional or local sub-divisions
* National or federal agency/office
* Regional or local authority
* Regional or local agency/office
* Body governed by public law
* European institution/agency or international organisation
* Other: (please specify)

Considering (a) the interest from Ukraine in being able to submit TED data through OCDS, and (b) the procurement analytics use case, we should look at options for mapping this to a core taxonomy.

**Comment by timgdavies** [comment]
The TED 2.09 schema has the following code-list values:

* BODY_PUBLIC
* EU_INSTITUTION	
* MINISTRY	
* NATIONAL_AGENCY	
* REGIONAL_AGENCY	
* REGIONAL_AUTHORITY

This is clearly EU specific, so it would be useful to see if this can be broken down in a way that would have global relevance, but also map to the TED codelist.

As a starter, that could be along the lines of:

```
buyer.sector = public, private, ngo

buyer.level = group, national, regional, local

buyer.group = {identifier}
```

Where the identifier could draw upon the FAO Geopolitical ontology, or some other identifier scheme (to investigate).

To test out how this might allow mapping to the EU codelist:

| EU Code | Sector | Level | Group |
|-------------|-----------|---------|----------|
| BODY_PUBLIC        |  public | - | |
| EU_INSTITUTION	 | sector | group | EU |
| MINISTRY*	         | public | national | |
| NATIONAL_AGENCY	 | public | national |  |
| REGIONAL_AGENCY	 | public  | regional |  |
| REGIONAL_AUTHORITY | public | regional |  |

We don't get a great mapping - as we can't distinguish 'agency' from 'authority' and 'ministry'. 

We could add another classification type to deal with this, but that starts getting complicated.

Hmmm. Ideas and suggestions?

**Comment by timgdavies** [comment]
The other approach here may be to do away with the idea of a bi-directional mapping, and to suggest that:

OCDS includes ```buyer.sector``` and ```buyer.level``` which should support global comparability and analysis, and which allows a TED->OCDS mapping.

In workflows that generate TED data from OCDS, an extra property of ```buyer.TED.type``` can be added with explicit values from the TED schema codelist.

**Comment by timgdavies** [comment]
The more general approach to this may be to add ```organization/classifications``` and then a set of codelist schemes.

**Comment by timgdavies** [comment]
This issue is taken forward in #369

**Comment by jpmckinney** [comment]
Unresolved, but will be resolved with OCDS profile for EU.

**Comment by jpmckinney** [comment]
My proposal in https://github.com/open-contracting-extensions/european-union is to add `details.classifications` to `Organization`, and to have a 'TED' scheme for TED's "Type of the contracting authority", and a 'COFOG' scheme for TED's "Main activity".

**Comment by jpmckinney** [comment]
Closing here, as for now this will be in an extension, not core. In the next minor/major release, we can consider whether any extensions should become core.
