### ISSUE TITLE
Add Central Product Classification to codelists

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#265]
Used in Taiwan: https://en.wikipedia.org/wiki/Central_Product_Classification

Need to check on on how this relates to UNSPSC which is currently in our list of [Item Classification Schemes](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#item-classification-scheme).

**Comment by Bjwebb** [comment]
From looking at the two lists of codes there doesn't appear to be any relationship between the two. A quick google search for `"central product classification" unspsc` gives me only third party sources - there's no mention in the documentation of either of the other than I can see.

The CPC list (Central Product Classification) does have a mapping to HS 2007 and ISIC 4 though.

CPC 2.1 also has a mapping to CPC 2, so we may want to separate out versions on our Item Classification Schemes list. Not sure what version Taiwan use.

**Comment by timgdavies** [comment]
Summarised for 1.1 in #387
