### ISSUE TITLE
Notices in Document Type Codelist

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#267]
In [Document Type Codelist](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/codelists/#document-type) there are three different notice types with following codes:
 * `Tender notice`
 * `Award notice`
 * `Contract notice`

note that there is space in the code despite the fact that other document types has code in camelCase, for instance:
 * `evaluationCriteria`
 * `contractArrangements`

Is there a reason why mixed approach? Or it should be just same `notice` code but applicable to different types of objects?

**Comment by timgdavies** [comment]
This looks like a bug to me. 

I've flagged for correction.

**Comment by timgdavies** [comment]
As this is an open codelist, we don't enforce values here right now.

I would suggest using tenderNotice, awardNotice, contractNotice for consistency in your own data.

**Comment by myroslav** [comment]
thank you for suggestion

**Comment by Bjwebb** [comment]
This is now fixed: http://standard.open-contracting.org/latest/en/schema/codelists/#document-type
