### ISSUE TITLE
TED: Organisation main activity / classifications

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#269]
TED includes a field for the `MAIN_ACTIVITIES` or `CA_ACTIVITIES` (Contracting Authority Activities) of a buyer. 

This appears to use the top level of [COFOG](http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=4) (UN Classification of the Functions of Government), although with custom textual codes, rather than the numeric COFOG codes (I can't find actual codelists for TED anywhere, apart from within the XML Schema, where 2.09 appears to have different values from 2.08). 

We could address TED<->OCDS integration either by adding a:

`organization.cofog` property

although this wouldn't make much sense when the organization element is used for suppliers or non-governmental buyers.

Alternative, we could introduce a more abstract `organization.classifications` array, using the classifications model which would allow for different schemes to be used, such as [COFOG](http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=4), [ISIC](http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=27&Lg=1) (International System of Industry Classification), and multiple classifications per organisations, though at the cost of moving these off into sub-tables in the flattened serialisation. 

Comments welcome.

**Comment by timgdavies** [comment]
TED also has ```NUTS``` classifications for buyers (regional area classification).

See: [Nomenclature of Territorial Units for Statistics (NUTS)](http://simap.ted.europa.eu/web/simap/nuts)

This is requested both for Contracting Authorities and Suppliers, so would make sense as a explicit property of Organisation.

**Comment by timgdavies** [comment]
Alternatively, we could allow Location Information (#26) to be attached to organisations for NUTS codes, as this includes a way to have a gazeteer entry, for which NUTs could be the codelist used.

**Comment by timgdavies** [comment]
This issue is taken forward in #369

**Comment by jpmckinney** [comment]
Unresolved, but will be resolved with OCDS profile for EU.

**Comment by jpmckinney** [comment]
See https://github.com/open-contracting/standard/issues/262#issuecomment-415800266

**Comment by jpmckinney** [comment]
Closing here, as for now this will be in an extension (linked from above comment), not core. In the next minor/major release, we can consider whether any extensions should become core.
