### ISSUE TITLE
Add country code to organization/address 

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#270]
At the moment we only collect country name in the [organization/address block](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#address)

An explicit country code is required in TED data. 

Whilst in most cases, mappings from country name -> ISO 2-digit country code exist, we could add a property for the explicit statement of the ISO 2-digit code.

Is this important?

**Comment by robredpath** [comment]
Should this be in a TED extension so that core stays simple for everyone else?

**Comment by timgdavies** [comment]
There are no plans to work on this in version 1.1

**Comment by jpmckinney** [comment]
The phoenix rises: #524
