### ISSUE TITLE
Broken link in schema

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#271]
https://github.com/open-contracting/standard/blob/1.0/standard/schema/release-schema.json#L586
https://github.com/openspending/fiscal-data-package/blob/master/specification.md is a 404.

**Comment by timgdavies** [comment]
This should be updated to link to http://fiscal.dataprotocols.org/ 

However, there may be a wider discussion around how we handle budget in 1.1. - https://github.com/open-contracting/standard/issues/345

**Comment by Bjwebb** [comment]
We think that this issue should be included in 1.0.2, to be released in September, because it is a bug fix.

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
