### ISSUE TITLE
Transaction uri

### ISSUE THREAD

**Issue by gabelula** [open-contracting/standard#273]
Hi!

Any specific reason on why to have the field Implementation.Transactions.URI pointing to a record about the transaction?

**Comment by timgdavies** [comment]
This relates to the [transaction block in implementation](http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#transaction). 

It defines:

```uri``` - A URI pointing directly to a machine-readable record about this spending transaction.

The motivation for this was in cases where a publisher is also maintaining transaction spend data in some other open dataset. For example, published through [Open Spending](https://openspending.org/).

The uri field is then intended to help make a linkage between these two datasets.

In cases when no such budget data is published, then URI can be left blank. 

Does that address the question you were asking?

**Comment by gabelula** [comment]
Yes. Thanks!
