### ISSUE TITLE
New property of contract: extendsContractID

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#274]
This is under consideration for version 1.1 of OCDS.
## The issue

In [this comment](https://github.com/open-contracting/standard/issues/200#issuecomment-163581789) @woodbine has raised how extensions to a contract should be modelled.

Building on the [approach discussed for Paraguay](https://github.com/open-contracting/implementation-and-extensions/issues/8#issuecomment-157862724), the `extendsContractID` property is suggested as a way to link two entries in the contracts array together, showing that one is an extension of the other. 
## The proposal

An optional property `extendsContractID` will be added to contract, allowing a cross-reference within the contracts array. 
## Questions

Should this be in core or an extension
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
I've staged this for inclusion in core, as it appears relevant also to amendment cases (where we are seeing some (mistaken?) use of amendment to represent contract extensions).

**Comment by LindseyAM** [comment]
I would like to understand a little bit better this proposal as extending the duration of the contract is one way that the contract could be amended (contract amendment or change could be duration, amount, contractor - if contract is assigned - , or change of terms (eg the road is now one lane instead of two, or a combination of the above). Just curious if the proposal is suggesting modeling extensions differently than other types of changes.

**Comment by andrewlorien** [comment]
I second Lindsay's question.  I agree that a new contract could have a tag which points to the contract it amends.  But I'm not sure whether guidance is required to specify the difference between a new contract and an amendment - in some jurisdictions and cases it will be obvious (when there is a new physical contract), but not always.

**Comment by woodbine** [comment]
I didn't propose it to handle amendments,I wanted to be able to cope with
the fact that many contracts have options to extend included at the outset
and there's a need to know not only the planned end date, but also the end
date after the right to extend is over.

Here's an example:
https://procontract.due-north.com/ContractsRegister/ViewContractDetails?contractId=3c2cc92c-8f55-e611-8114-000c29c9ba21

**Comment by timgdavies** [comment]
You can see the proposal in context at http://standard.open-contracting.org/1.1-dev/en/schema/reference/#contract 

This is to deal with cases where a particular procurement system handles an extension through issuing a new contract. This is, as [the detailed linked discussion notes](https://github.com/open-contracting/implementation-and-extensions/issues/8#issuecomment-157862724) the case in Paraguay. 

If no new contract is signed/entered into, there would be no use of extendsContractID.

**Comment by mpostelnicu** [comment]
If possible, it would be really useful to see some examples on how to correctly map all these modes of linking/extending contract/release information by avoiding confusing one with the other, so the new properties:  `extendsContractID`, `relatedProcesses ` (#371) and `amendments` (#357)

Thanks!

**Comment by timgdavies** [comment]
We had a 'reject' comment on the peer-review for this,  

> I'm not sure this is necessary given the fact that it adds complexity while there are other existing options in the OCDS:
> - If the goal is to amend an existing contract (e.g. to increase value), then the amendment and contract sections should be used. 
> - If the goal is to replace an existing contract (e.g. to change the contract identifier and value), the the amendment and contract sections should be used. The fact that it replaces a contract is signaled by changing the contract ID, but could also be further specified via the amendment codelist, discussed above. 
> - If the goal is to ""amend a contract"" by ""adding a new contract"", then a new contract can be published within the same procurement process. Since it is a contract within the same contracting process, to the same supplier, the second being published later than the first, and probably concerning the same items and lots, to me this signals sufficiently that the latter ""extends"" the former."

As a consequence I would propose that we keep ```extendsContractID``` as an extension, rather than in core for the 1.1 version.

Views welcome.

**Comment by woodbine** [comment]
Well that's a fundamental misunderstanding of what I'm proposing. This
isn't about amendments, its a property of the original contract, and
nothing to do with any post award adjustment. Just because it is called
"extends" doesn't mean it happens post-award.

I'm happy with it being an extension, I just wish people would pay
attention.

Ian

**Comment by LindseyAM** [comment]
Is this proposal about modeling when there is an option to extend? or is it about modeling the actual extension of the contract? At first I thought it was the second one but after @woodbine 's comment 23 days ago I understood it to be the first one. But the proposal reads to me to be the second one (and that is what the reviewer is reacting to as well). @timgdavies can you clarify, is the proposal about showing in a tender opportunity or contract award whether there will be an option to extend the contract later on (and the details about that option) or if the proposal is about showing what happens when that option to extend is taken. Or is it both?

**Comment by timgdavies** [comment]
@woodbine @LindseyAM I think we might have some crossed wires here - partly due to my error of citation in the original description of this issue. 

```extendsContractID``` address when one contract is signed as an affective extension of another (as in the Paraguay case).

The [maxExtentDate](https://github.com/open-contracting/standard/issues/374#issuecomment-278743090) in #374 addresses **some** of @woodbine's original use case, but that was also taken up in #375 which proposes some fields to flag when extensions are allowed, and how many are allowed.

#375 is tagged to be a extension at the moment, and was one of the ones which we didn't get to for the 1.1 release, but plan to work on following 1.1.

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> I'm not sure this is necessary given the fact that it adds complexity while there are other existing options in the OCDS:
> - If the goal is to amend an existing contract (e.g. to increase value), then the amendment and contract sections should be used. 
> - If the goal is to replace an existing contract (e.g. to change the contract identifier and value), the the amendment and contract sections should be used. The fact that it replaces a contract is signaled by changing the contract ID, but could also be further specified via the amendment codelist, discussed above. 
> - If the goal is to "amend a contract" by "adding a new contract", then a new contract can be published within the same procurement process. Since it is a contract within the same contracting process, to the same supplier, the second being published later than the first, and probably concerning the same items and lots, to me this signals sufficiently that the latter "extends" the former.

**Comment by timgdavies** [comment]
This has been moved to a community extension. This means that:

* It is not presented as either part of the core standard, not recommended for use; **but**
* For publishers who do find a need to make this relationship explicit, there is a common approach available; 

In terms of @JachymHercher's comments above:

> - If the goal is to amend an existing contract (e.g. to increase value), then the amendment and contract sections should be used. 

The change is consistent with this. The recommended approach for increasing the value of an existing contract is via updates to the relevant contract, and explicit information in ```contract.amendments```

> - If the goal is to replace an existing contract (e.g. to change the contract identifier and value), the the amendment and contract sections should be used. The fact that it replaces a contract is signaled by changing the contract ID, but could also be further specified via the amendment codelist, discussed above. 

The change is consistent with this. And a simple replacement would not need to use an extendsContractID property.  

> - If the goal is to "amend a contract" by "adding a new contract", then a new contract can be published within the same procurement process. Since it is a contract within the same contracting process, to the same supplier, the second being published later than the first, and probably concerning the same items and lots, to me this signals sufficiently that the latter "extends" the former.

This requires the user to use a number of fields (date of contract, match of suppliers, match of items and lots) to infer that one contract extends another. In many procurement systems, this will be ok. 

The extension just adds support for those cases where a publisher wants, or needs, to explicitly declare the connection.
