### ISSUE TITLE
More than one Transactions.Date  [Implementation]

### ISSUE THREAD

**Issue by gabelula** [open-contracting/standard#276]
Hi,

CDMX has information on several dates for the transactions.

- date that the transaction was authorized
- date that the transaction was done (we already have this field in OCDS) 
- date that the transaction was finished

Any ideas on where we can save this other dates or how to publish this information if it is important?

**Comment by timgdavies** [comment]
I would suggest creating additional properties for each of these dates.

Ideally to propose these as general extensions would require clear definitions of each. Would you be able to put forward a definition of each?

For 'date that the transaction was authorized' ```authorizedDate``` seems like a natural field name.

For 'date that the transaction was finished' I'm not sure what the best field name would be without a more detailed definition. 

The one alternative for discussion here might be whether ```authorized``` should be a more detailed object allowing dates, details of who authorized and so-on. Are there any use-cases for this?

**Comment by gabelula** [comment]
Great! I will ask CDMX to get us a description for each one.

**Comment by timgdavies** [comment]
@gabelula Any update on what the CDMX data actually contains here? Do they now use multiple dates?

Others: any other use-cases for multiple dates?

**Comment by gabelula** [comment]
They are not using multiple dates. Depending of the payment method they are doing this:

Transfer - date that the transfer is being applied
Check - date that the check is being checked out

**Comment by timgdavies** [comment]
Given CDMX are selecting one of the dates to use, and we've not heard of use-cases that need to know all the possible dates, I'm closing this and removing the 1.1 milestone.
