### ISSUE TITLE
Delivery items in the milestone [Implementation]

### ISSUE THREAD

**Issue by gabelula** [open-contracting/standard#278]
Hi,

In the case that the milestone has items being delivered, where do we save that information on how many items and what are they?

**Comment by timgdavies** [comment]
OCDS doesn't have a structured way of representing this at present.

If the use-case is displaying information to users, then this could be done just in the title and description of the milestone that is flagged as complete. 

If there is a use case for more structured analysis of this information and the data exists in this structured form, then potentially you could extend OCDS by attaching an ```items``` block to ```milestone``` via a property such as ```relatedItems```.

**Comment by timgdavies** [comment]
Closing as a local implementation issue for now. If other use-cases for this we can re-open.

**Comment by yolile** [comment]
In Paraguay, the DNCP has the structured information about how many items were delivered by when. The proposal is to add `items` at the `milestone` level so that they can indicate which items and their quantities (and beneficiaries) were delivered. Note that the `relatedItems` won't be enough as they also need to indicate how many items were delivered, where, and who benefits. I will close the issue when the extension is drafted. FYI @fppenna

**Comment by jpmckinney** [comment]
Would the items in the Milestone be a subset of the Items in the main object? (e.g. Award)

**Comment by yolile** [comment]
Yes (in the purchase order in the case of Paraguay), but also with potentially different quantities

**Comment by jpmckinney** [comment]
We can have a call to discuss the model more quickly. Quick thoughts:

The items in the award are what was *procured*. The items in a milestone are what was (not sure the best descriptor) *delivered* or *ordered* or something. To avoid repeating many Item fields, I'm thinking the milestone can contain an array (name TBD, e.g. `deliveries`) where each object refers to a single item (or maybe an array of references, if the same delivery can cover many items but with the same location and beneficiaries). This object can override the quantities in the award, and would have other fields that aren't known at the time of the award (like specific beneficiaries and specific location).

Anyway, it'll be faster to work out any details and agree on a model on a call.

**Comment by jpmckinney** [comment]
It's sounding a little similar to a purchase order (it's not one, of course), which @fppenna modeled in Portland. Not sure if maybe some inspiration can be taken from there. (I don't quite remember the final model or the options we discussed).

**Comment by yolile** [comment]
The case is different from Portland because in Portland, they ended up modeling this as framework agreements. For this case, Paraguay will create an extension to add a "`deliveries`" array of `Delivery` in `Milestone`, with `relatedItem` and `quantity` fields.

**Comment by yolile** [comment]
Paraguay has drafted this extension https://gitlab.com/dncp-opendata/ocds_milestone_deliveries_extension
cc @locazho

**Comment by jpmckinney** [comment]
Aha, which depends on https://gitlab.com/dncp-opendata/ocds_beneficiaries_extension

I reviewed using our scripts:

https://gitlab.com/dncp-opendata/ocds_beneficiaries_extension/-/merge_requests/1
https://gitlab.com/dncp-opendata/ocds_milestone_deliveries_extension/-/merge_requests/1
