### ISSUE TITLE
ocdsOmit not defined.

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#284]
It is currently being used for the following fields:
- ocid
- id (release id)
- tag
- date

The compiledRelease in an ocdsRecord reuses the release schema and therefore requires all these fields to be present.
The versionedRelease keeps these fields also.

What you should put in these fields is not defined and the documentation alludes to excluding them apart from the tags and putting in ["compiled"] and keeping the ocid.

I suggest the following.
- For tags:
  - keep the compiled flag
- For ocid:
  - keep the ocid
- For id:
  -  Remove.  A list of release ids this versioned/merged release was made of is availible in the record
- For date:
  -  Remove. A list for release dates if available in the record schema.

To do this, we would need to create a new schema file i.e  merged-release-scema.json as we will not be able to reuse the release schema.

**Comment by timgdavies** [comment]
@kindly Is this relevant in our proposed replacement or mergeStrategies?

**Comment by timgdavies** [comment]
This will be taken forward via #287.
