### ISSUE TITLE
Stricter Validation on Strings and Lists

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#288]
This is under consideration for a core update in version 1.1 of OCDS.
## The issue

If a string or a list is a requiredProperty jsonschema only checks to see if the key is there.
So if there is an empty string or list against that key then it does not give you the errors you want.

Examples:
- ocid
- tags
- ids (all of them) 
## The proposal

We should check for length > 0 for these cases.

The schema should be updated to require this.

**Comment by timgdavies** [comment]
I would support this proposal.

**Comment by timgdavies** [comment]
The version 1.1 schema now includes minLength properties for required properties
