### ISSUE TITLE
Multi-source budgets

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#292]
In both PPP and infrastructure projects, we are seeing cases where users want to express multiple budget sources. For example, finance from government, private sector, and international development banks. 

Our current approach to budget does not adequately capture this.

**Comment by duncandewhurst** [comment]
We should consider how this fits with our approach to representing budgets from multiple government sources discussed in [#222](https://github.com/open-contracting/standard/issues/222) and [#352](https://github.com/open-contracting/standard/issues/352)

**Comment by timgdavies** [comment]
Developed in #377
