### ISSUE TITLE
Modelling multi-year contracts (budget, award, contract)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#293]
From @gabelula in at https://github.com/open-contracting/standard/issues/200#issuecomment-180020438 

> We are having the same discussion in the case of Mexico City data. The issue is that is not an extension of the contract but there are some contracts that are multianual(multi-year). The same contract is used for different years (with a maximum of 4 years). We know if the contract is multianual in the budget part. We need some fields to know if this contract is multianual and how many years. We also need fields for knowing how much budget per year and what is the maximum value of the contract for all the years.

Can you point to an example of existing data on a contract like this?

My first thought is to ask whether this could be modelled using multiple awards and contracts. 

For example, could it be represented such that:
- The buyer awards the right to receive the contract every year for up to four years, then four awards, one for each year, each with a value, would be created at that point.
- As a contract is issued each year to exercise the option to extend, a new contract would be issued with the actual value for that year;
- If the contract is not extended after n years, the awards which were made, would be updated as cancelled;
- The total value of the contract over all the years would exist in `planning/budget` or `tender/value`;

If this doesn't work, then it might be that some extension to budget is going to be required to capture the budget across years situation.

**Comment by gabelula** [comment]
The issue is that there is no new contract created every year. We have one contract that works for all the years (maximum four). 

CDMX is proposing:

```
 - the contract will be for the whole period
     - a field to show that is multi-year
     - a field to show what is the max value for all the years
 - budget
      - a field to show that is multi-year
      - a field to show how much for the whole period
```

**Comment by timgdavies** [comment]
I think these proposals can be accommodated. In terms of how to model this, some suggestions below.

## Contract

> - the contract will be for the whole period

So the `contract.period` should have startDate and endDate for the whole period

> - a field to show that is multi-year

An optional `"multiYear":true` field could be added to the `period` block (see below). 

> - a field to show what is the max value for all the years

This should be in the `contract.value` block.

If there is then a desire to show the break-down of amounts for each year, I would suggest considering whether this could be done with line-items. E.g., having a line-item for 2015, one for 2016 and so-on, each with the specific values for that year.

## Budget

Extend budget with a `period` block, which will give something like:

``` json
"planning": {
                "budget": {
                  "period": {
                        "startDate":"2015-11-04T00:00:00-06:00",
                        "endDate":"2019-11-04T00:00:00-06:00"
                    },
                    "amount": {
                        "amount": 7054250.52,
                        "currency": "MXN"
                    },
                    "project": "AUTORIZACION PRESUPUESTAL SPP/471/2015"
                }
            }
```

With the period **implicitly** indicating the multi-year nature of the budget (i.e. doing a difference between start and end dates, and rounding up to year, will give whether it is multi-year or not). If an explicit flag for multi-year is needed, then period could be extended so that this was:

``` json
"period": {
          "startDate":"2015-11-04T00:00:00-06:00",
          "endDate":"2019-11-04T00:00:00-06:00",
          "multiYear": true
}
```

**Comment by gabelula** [comment]
Great! The only other thing that CDMX wants to add is the value for all the years (in the budget and also for all the contracts)

`

```
        "planning": {
                 "budget": {
                     "amount": {
                         "amount": 7054250.52,  // budget assigned for that year
                         "currency": "MXN"
                     },
                     "multiYear": true ,
                       "amountMultiYear": {       
                         "amount": 20054250.52,  // budget for all the years
                         "currency": "MXN"
                         "reason":  "" // details
                     },
                     "project": "AUTORIZACION PRESUPUESTAL SPP/471/2015"
                 },
                 "documents": []
        }

        "contracts": [
                 {
                     "id": "1",
                     "awardID": "1",
                     "title": "CS-MA-009/2015",
                     "description": "SOLUCIÓN DE AUTENTICACIÓN BIOMÉTRICA POR VOZ",
                     "status": "active",
                     "multiYear": true
                     "period": {
                         "startDate": "2015-11-27T00:00:00-06:00",  
                         "endDate": "2016-12-31T00:00:00-06:00" 
                     },
                     "value": {
                         "amount": 403100.03,  // this is only for 2015
                         "currency": "USD"
                     },
                     "valueAllYears": {
                          "amount": 1209300.00,  //  total value for the contract for all the years
                          "currency": "USD"
                     },   
                     "items": [
                         {
                             "id": "1",
                             "description": "SOLUCION AUTENTIC BIOMETRICA X VOZ 2015",
                             "quantity": 347500,
                             "unit": {
                                 "name": "SER"
                             }
                         }
                     ],
                     "dateSigned": "2015-11-27T00:00:00-06:00",
                     "documents": []
                 }
        ]
```

`

**Comment by timgdavies** [comment]
If there is only one contract entry being produced, then I would suggest this should be handled the other way around:
- The largest value (valueAllYears) should go into `value`, and then a separate property created for the specific year value (same pattern with the budget)

This ensures that tools which are not aware of the extended property can understand the full commitment that has been made to a given supplier, even if they might not understand the temporal breakdown of that. 

I think to fully resolve this we might need to better articulate the use case that CDMX are aiming at. 
- How will the break-down of budget and value be displayed or used?
- Is this information set at the point the contract is signed, or is it updated over the lifetime of the contract?

Happy to set-up a call with the team to dig into this more if needed.

**Comment by timgdavies** [comment]
(Aside: some of this is reminding me of the '[planned disbursements](http://iatistandard.org/201/activity-standard/iati-activities/iati-activity/planned-disbursement/)' model in IATI, where planned future transactions can be mapped out... I wonder if an adaptation of [transactions](http://standard.open-contracting.org/latest/en/schema/reference/#transaction) might also be useful here?)

**Comment by gabelula** [comment]
```
   "planning": {
                 "budget": {
                     "amount": {
                         "amount": 20054250.52,  // budget for all the years
                         "currency": "MXN"
                     },
                     "multiYear": true ,
                       "amountPerYear": {       
                         "amount": 7054250.52,  // budget assigned for that year
                         "currency": "MXN"
                     },
                     "rationale": "",
                     "project": "AUTORIZACION PRESUPUESTAL SPP/471/2015"
                 },
                 "documents": []
        }

        "contracts": [
                 {
                     "id": "1",
                     "awardID": "1",
                     "title": "CS-MA-009/2015",
                     "description": "SOLUCIÓN DE AUTENTICACIÓN BIOMÉTRICA POR VOZ",
                     "status": "active",
                     "multiYear": true
                     "period": {
                         "startDate": "2015-11-27T00:00:00-06:00",  
                         "endDate": "2016-12-31T00:00:00-06:00" 
                     },
                     "value": {
                          "amount": 1209300.00,  //  total value for the contract for all the years
                          "currency": "USD"
                     },
                     "valuePerYear": {
                         "amount": 403100.03,  // this is only for 2015
                         "currency": "USD"
                     },   
                     "items": [
                         {
                             "id": "1",
                             "description": "SOLUCION AUTENTIC BIOMETRICA X VOZ 2015",
                             "quantity": 347500,
                             "unit": {
                                 "name": "SER"
                             }
                         }
                     ],
                     "dateSigned": "2015-11-27T00:00:00-06:00",
                     "documents": []
                 }
        ]
```

**Comment by gabelula** [comment]
Great! The only field that I'm not so sure about is the valuePerYear in the contract section. It needs to be there for the first release but it is redundant for when we start having the implementation released.

**Comment by timgdavies** [comment]
From what you are saying, and the example above, it seems to me that there is a suggestion that new `contract` blocks are going to be added each year, when the new year contracts are in place? My previous suggestion was only **if** you were not producing multiple contract blocks, updating it each year with a new entry in the contracts array. 

If that is the case, then the `contract.value` in any individual block should only be the value for that year. That way, applications can get the total contracted value by summing across all the `contract.value` entries. 

This would suggest switching to either include a `multiYearValue` property in each `contract` block just a convenience for the applications in Mexico, or preferably, reading the multi-year value off our of the award block.

Your extract above doesn't show the `award` block. Does the proposed data contain a single award for the whole contract value (over all the years), or an `award` block for each `contract` block?  (e.g. Award 1 for Contract 1 added in year 1; award 2 for contract 2 added in year 2).

There is an example below that models this with a single award, and multiple contracts, assuming this has been published in year 2 (e.g. in year 1, only the first contract block would be there). 

```
   "planning": {
                 "budget": {
                     "amount": {
                         "amount": 20054250.52,  // budget for all the years
                         "currency": "MXN"
                     },
                     "multiYear": true ,
                       "amountPerYear": {       
                         "amount": 7054250.52,  // budget assigned for that year
                         "currency": "MXN"
                     },
                     "rationale": "",
                     "project": "AUTORIZACION PRESUPUESTAL SPP/471/2015"
                 },
                 "documents": []
        }
        "awards": {
            "id":"1",
            "period": {
                         "startDate": "2015-11-27T00:00:00-06:00",  // Whole period over which contracts can be awarded
                         "endDate": "2019-12-31T00:00:00-06:00" 
                      },
            "value": {
                          "amount": 1209300.00,  //  total value for the contract for all the years
                          "currency": "USD"
                     }

        }

        "contracts": [
                 {
                     "id": "1",
                     "awardID": "1",
                     "title": "CS-MA-009/2015",
                     "description": "SOLUCIÓN DE AUTENTICACIÓN BIOMÉTRICA POR VOZ",
                     "status": "active",
                     "multiYear": true
                     "period": {
                         "startDate": "2015-11-27T00:00:00-06:00",  
                         "endDate": "2016-12-31T00:00:00-06:00" 
                     },
                     "value": {
                          "amount": 403100.03,  //  2015 value
                          "currency": "USD"
                     },
                     "items": [
                         {
                             "id": "1",
                             "description": "SOLUCION AUTENTIC BIOMETRICA X VOZ 2015",
                             "quantity": 347500,
                             "unit": {
                                 "name": "SER"
                             }
                         }
                     ],
                     "dateSigned": "2015-11-27T00:00:00-06:00",
                     "documents": []
                 },
                 {
                     "id": "2",
                     "awardID": "1",
                     "title": "CS-MA-009/2017",
                     "description": "SOLUCIÓN DE AUTENTICACIÓN BIOMÉTRICA POR VOZ",
                     "status": "active",
                     "multiYear": true
                     "period": {
                         "startDate": "2017-01-01T00:00:00-06:00",  
                         "endDate": "2018-12-31T00:00:00-06:00" 
                     },
                     "value": {
                          "amount": 403100.03,  // 2016/17 value
                          "currency": "USD"
                     },
                     "items": [
                         {
                             "id": "1",
                             "description": "SOLUCION AUTENTIC BIOMETRICA X VOZ 2015",
                             "quantity": 347500,
                             "unit": {
                                 "name": "SER"
                             }
                         }
                     ],
                     "dateSigned": "2016-11-27T00:00:00-06:00",
                     "documents": []
                 }
        ]
```

**Comment by gabelula** [comment]
> From what you are saying, and the example above, it seems to me that there is a suggestion that new contract blocks are going to be added each year, when the new year contracts are in place? My previous suggestion was only if you were not producing multiple contract blocks, updating it each year with a new entry in the contracts array.

We are trying to model the case when there is only going to be one contract for all the years (when the contract is multi-year). 

> If that is the case, then the contract.value in any individual block should only be the value for that year. That way, applications can get the total contracted value by summing across all the contract.value entries.

Yes. We are agreeing on not modifying the definition of the fields that are already present in the OCDS.

> This would suggest switching to either include a multiYearValue property in each contract block just a convenience for the applications in Mexico, or preferably, reading the multi-year value off our of the award block.
>  Your extract above doesn't show the award block. Does the proposed data contain a single award for the whole contract value (over all the years), or an award block for each contract block? (e.g. Award 1 for Contract 1 added in year 1; award 2 for contract 2 added in year 2).

In the case of multiyear there is only one award .

> There is an example below that models this with a single award, and multiple contracts, assuming this has been published in year 2 (e.g. in year 1, only the first contract block would be there).

There are case when there are many contracts for a multi-year but is not the one we are having trouble modeling.

I'm adding to this document the problem and solution we are agreeing with CDMX: https://github.com/gabelula/mx-ocds/blob/master/reviews/extensions.md

This is the proposal:

```
"planning": {
                "budget": {
                    "multiYear": true
                    "amount": {
                        "amount": 7054250.52,
                        "currency": "MXN"
                    },
                    "amountYear": {
                      "amount": 1000,
                      "currency": "MXN"
                    }
                    "project": "AUTORIZACION PRESUPUESTAL SPP/471/2015"
                }
            }
```

```
       "contracts": [
                {
                    "id": "1",
                    "awardID": "1",
                    "title": "CS-MA-009/2015",
                    "description": "SOLUCIÓN DE AUTENTICACIÓN BIOMÉTRICA POR VOZ",
                    "status": "active",
                    "multiYear": true
                    "period": {
                        "startDate": "2015-11-27T00:00:00-06:00",  
                        "endDate": "2019-12-31T00:00:00-06:00"
                    },
                    "value": {
                         "amount": 1209300.00,  //  total value for the contract for all the years
                         "currency": "USD"
                    },
                    "valueYear": {
                        "amount": 403100.03,  // this is only for 2015
                        "currency": "USD"
                    },   
                    "items": [
                        {
                            "id": "1",
                            "description": "SOLUCION AUTENTIC BIOMETRICA X VOZ 2015",
                            "quantity": 347500,
                            "unit": {
                                "name": "SER"
                            }
                        }
                    ],
                    "dateSigned": "2015-11-27T00:00:00-06:00",
                    "documents": []
                }
       ]
```

**Comment by gabelula** [comment]
Hi, here there is an example of a release that is using this new fields.

Validator's link: http://standard.open-contracting.org/validator/data/18c81e4d-a4af-4832-885b-ec828ff5ca88 

Release: https://github.com/gabelula/mx-ocds/blob/master/data/20160618/OCDS-87SD3T-SEFIN-DRM-AD-011-2015.json

**Comment by timgdavies** [comment]
Thanks @gabelula 

Two quick things to check:

(1) Could you use amountYear / valueYear instead of amountyear and valueyear 

This would be more consistent with the camelCase approach in OCDS files.

(2) Can you 

In the example I see that `amountYear` is a much higher value than `amount` and `valueYear` much higher than `value`.

I understood that `valueYear` would be the value of the contract in the current year, so would generally be less than the overall value?

**Comment by timgdavies** [comment]
Budget issue is picked up in #377. I think this is the main issue for the 1.1 upgrade - and the valueYear extension belongs right now in a Mexico specific extension.
