### ISSUE TITLE
Null values in enum for contract status and award status

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#295]
The schema does not current accept null values for contract or award status. What is the best way forward, taking into acount the use of null in the merge strategy?

**Comment by timgdavies** [comment]
The enum lists in the schema should be updated to allow null values.

**Comment by Bjwebb** [comment]
Many of the enum lists already allow null. Contract and award status don't so I've changed that in https://github.com/open-contracting/standard/commit/6427e3157646089bde9219b1976332562a4ae5bc

`tag` and `initiationType` also don't allow null, but they're required so don't have the same merging usecase. I suggest we leave those as they are.
