### ISSUE TITLE
Milestone Status is missing a description

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#296]
All codelists featured in http://standard.open-contracting.org/latest/en/schema/codelists/ except Milestone Status have a description. Is this an oversight?

**Comment by timgdavies** [comment]
I think this was because they were felt to be self-explanatory. But for consistency, descriptions would not harm.

**Comment by ekoner** [comment]
Proposal to either leave it blank as it is intuitive or add a description to Milestone status as:

> Contracting processes have significant stages or events that are tracked to manage the procurement. The milestone status tracks the overall status of the contracting process in addition to localised tracking available as part of the standard.

met:

> The milestone has passed and been completely met

notMet:

> The milestone has not yet passed or is not yet met

partiallyMet:

> The milestone has passed and was partially met

**Comment by timgdavies** [comment]
This is handled in the updates in #373
