### ISSUE TITLE
Method codelist description is inconsistent

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#298]
The [Method codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#method) is described as:

"The method codelist is based upon the GPA Definitions provided here."

Other codelists provide some context, for example:

"Release Tag

A contracting process may result in a number of releases of information over time. These should be tagged to indicate the stage of the contracting process they relate to."

Could we align the description of Method codelist with the more contextual descriptions in the rest of the document

**Comment by ekoner** [comment]
Proposed change to the definition:

> A contracting process aims to fulfil the requirements identified at the planning stage. The procurement method is the procedure used to purchase these works, goods or services. The method codelist is based upon the GPA Definitions provided here.

**Comment by timgdavies** [comment]
This will be picked up in #380.
