### ISSUE TITLE
Semantics and field values for ContactPoint.avalableLanguage extension

### ISSUE THREAD

**Issue by myroslav** [open-contracting/standard#302]
This ticket is about extension to OCDS in multilingual environments, and ability to specify language of communication for Organization Contact.

schema.org [ContactPoint](https://schema.org/ContactPoint) has [availableLanguage](https://schema.org/availableLanguage) field that contains [Language](https://schema.org/Language) explained as:

> Natural languages such as Spanish, Tamil, Hindi, English, etc...

I.e. the field contents is verbose name of language.

Since OCDS in [many](http://standard.open-contracting.org/latest/en/schema/reference/#language) [places](http://standard.open-contracting.org/latest/en/schema/reference/#document) uses "two-digit ISO 639-1", what recommendation would be for `ContactPoint.avalableLanguage` allowed field values? `en` vs `English`?

**Comment by ekoner** [comment]
My inclination would be towards consistency and to continue using the 2 character values. Other thoughts are around an array of availableLanguage rather than a single availableLanguage to model both mono and multi-lingual contacts. However, this needs a more in-depth think through, so I will raise it for review.

**Comment by timgdavies** [comment]
Good question. I notice that schema.org also has the [inLanguage](https://schema.org/inLanguage) property, which points to either [Text](https://schema.org/Text) or [Language](https://schema.org/Language) objects, but which has the description _"Please use one of the language codes from the IETF BCP 47 standard. Supersedes language."_

(ISO 639-1 is a sub-set of BCP 47)

That leads me to think that schema.org is not entirely opposed to use of codes, as opposed to names, and so it supports better use of OCDS across languages to use the ISO codes. Applications can then choose to render that in the users own language.

**Comment by timgdavies** [comment]
Related to #291

**Comment by timgdavies** [comment]
Checking against the Open Procurement API spec, and any other data we have, I've not seen use of 'additionalContactPoint' or 'availableLanguage' in any existing data.

The subject of this issue has been resolved by Schema.org updating to require language codes.

I don't see a change to 1.1 required here. 

A future extension for 'additionalContactPoint' and language support in contact points could be proposed separate from the upgrade process.

**Comment by myroslav** [comment]
You can see this in documentation to single procedure that has this extension: http://openeu.api-docs.openprocurement.org/en/latest/standard/organization.html

`Organization` has `additionalContactPoints` (array of `Contact`) and `Contact` has `availableLanguage` (2-letter string).

**Comment by timgdavies** [comment]
I've based the [additionalContactPoints extension](https://github.com/open-contracting/ocds_additionalContactPoints_extension) on this approach.
