### ISSUE TITLE
The versioned release schema should be consistently sorted

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#303]
This would allow more easily understood diffs of that schema.

**Comment by Bjwebb** [comment]
Looks like https://github.com/open-contracting/standard/issues/285#issuecomment-171366799 may also solve this.

**Comment by timgdavies** [comment]
@bjwebb Can you confirm if this is covered by #285, and if so, close this issue?

**Comment by Bjwebb** [comment]
No, there was still some more to do, but it's happened as part of https://github.com/open-contracting/standard/pull/412
