### ISSUE TITLE
Worked example of Framework Contracts for documentation

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#310]
Requested by a user.

**Comment by timgdavies** [comment]
@duncandewhurst has been working to identify the different kinds of framework, and how these can be modelled in OCDS. These are listed below for comment.

| Framework type | OCDS approach |
| --- | --- |
| Single supplier with direct call-offs | **A single contracting process** using award(s) to represent the framework agreement and contract(s) to represent the call-offs. |
| Multiple suppliers with direct call offs | **A single contracting process** using award(s) to represent the framework agreement and contract(s) to represent the call-offs. |
| Multiple suppliers with mini-competitions for call-offs | **Multiple contracting processes**: One process using awards to represent suppliers on the framework agreement; Multiple selective or limited processes to represent the mini-competitions linked to the framework agreement via relatedProcess (see #371). |
| Multiple suppliers with either direct call-offs or mini-competitions | **Multiple contracting processes**: One process using awards to represent suppliers on the framework agreement and contract(s) to represent the direct call-offs; Multiple selective or limited processes to represent the mini-competitions linked to the framework agreement via relatedProcess (see #371). |
| Dynamic Purchasing System | **Multiple contracting processes**: One process using awards to represent suppliers joining the DPS. `tender/status` should be active for the lifetime of the dynamic purchasing system with `tender/tenderPeriod` and `tender/awardPeriod` reflecting that suppliers can join the DPS at any time. Multiple selective or limited processes to represent competitions between suppliers on the DPS for individual contracts, linked to the DPS via relatedProcess (see #371). |

**Comment by duncandewhurst** [comment]
Feedback from the teams at Colombia Compra and Buenos Aires Compra:

> The _single supplier with direct call-offs_ and _multiple suppliers with mini-competitions for call offs_ framework types are in use in both jurisdictions. No other types of framework agreement are used.

Colombia Compra also suggested modelling the _single supplier with direct call-offs_ and _multiple suppliers with direct call-offs_ framework types using multiple contracting processes. This approach could also be used for direct awards in the _multiple suppliers with either direct call-offs or mini-competitions_ framework type.

This approach would be more consistent with the approach used for the other framework types, reducing overall complexity, but would also mean that information about these framework types could not be contained within a single OCID/release, increasing complexity for users interested in only those framework types.

This approach also raises the issue of extending the codelist for _initiationType_ to include a code for **framework call-off** so that this type of contracting process can be more easily distinguished from other contracting processes. We may also want to consider introducing a code for **dynamic purchasing system** to the _initiationType_ codelist.

This issue is also related to [linking related processes](https://github.com/open-contracting/standard/issues/371) where we should consider whether the _relatedProcess_ field should be an array to capture multiple relationships, e.g. a framework with multiple call-offs.

Please indicate support or opposition for these proposals using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by duncandewhurst** [comment]
Framework agreements were discussed on today's community call.

Eliza Niewiadomska from the European Bank for Reconstruction & Development directed us to the [UNCITRAL Model Law on Public Procurement (2011)](http://www.uncitral.org/uncitral/en/uncitral_texts/procurement_infrastructure/2011Model.html) which gives the following definition of framework agreements:

> "Framework agreement procedure” means a procedure conducted in two stages: a first stage to select a supplier (or suppliers) or a contractor (or contractors) to be a party (or parties) to a framework agreement with a procuring entity, and a second stage to award a procurement contract under the framework agreement to a supplier or contractor party to the framework agreement: 
> 1. “Framework agreement” means an agreement between the procuring entity and the selected supplier (or suppliers) or contractor (or contractors) concluded upon completion of the first stage of the framework agreement procedure; 
> 2. “Closed framework agreement” means a framework agreement to which no supplier or contractor that is not initially a party to the framework agreement may subsequently become a party; 
> 3. “Open framework agreement” means a framework agreement to which a supplier (or suppliers) or a contractor (or contractors) in addition to the initial parties may subsequently become a party or parties;
> 4.  “Framework agreement procedure with second-stage competition” means a procedure under an open framework agreement or a closed framework agreement with more than one supplier or contractor in which certain terms and conditions of the procurement that cannot be established with sufficient precision when the framework agreement is concluded are to be established or refined through a second-stage competition;
> 5. “Framework agreement procedure without second-stage competition” means a procedure under a closed framework agreement in which all terms and conditions of the procurement are established when the framework agreement is concluded;

We discussed what determines whether a framework agreement has **direct awards** and **competitive call-offs** which can depend on a threshold for procurement value defined either in trade agreements, national legislation or the discretion of the procuring entity.

We also discussed whether there is a **single buyer** for both the selection of suppliers for the framework and the **direct awards** or **competitive call-offs** resulting from the framework - in some jurisdictions (e.g. France) there is a single buyer but in other jurisdictions and depending government tooling and payment mechanisms there may be different buyers for each call-off.

We should also consider how [**lots**](https://github.com/open-contracting/standard/issues/381) and frameworks will interact in OCDS.

Finally Angelos Hatzikyriacos from European Dynamics raised the question of whether catalogue buying can be modelled in OCDS which we will investigate further alongside the broader question of whether purchase orders are within the scope of OCDS.

**Comment by duncandewhurst** [comment]
We gathered some useful feedback on frameworks terminology at Open Contracting Day at IODC:
- Rose Gill Hearn from Bloomberg Associates highlighted that in the US **call-offs** are known as **drawdowns**
- @jachymhercher and @myroslav confirmed that in the EU (and Ukraine specifically) the framework is known as an **agreement** whilst call-offs are known as **contracts**

We also heard about the UK government's [G Cloud framework](https://www.gov.uk/government/publications/g-cloud-8-framework-agreement/g-cloud-8-framework-agreement) which can involve an additional security assessment process for certain buyers/services.

**Comment by duncandewhurst** [comment]
The Chartered Institute of Procurement and Supply (CIPS) [knowledge summary on framework arrangements](https://www.cips.org/Documents/Resources/Knowledge%20Summary/Framework%20Arrangements.pdf) gives a useful overview of this area

**Comment by JachymHercher** [comment]
The CIPS note seems to be a bit out of date, see e.g. "(Note: The new consolidated Public Procurement Directive (currently - June 2003 - in its final stages in Brussels) does for the first time explicitly address the issue of framework agreements."

**Comment by duncandewhurst** [comment]
@JachymHercher well spotted - thank you

**Comment by duncandewhurst** [comment]
We should consider whether the [approach to modelling qualification processes](https://github.com/open-contracting/public-private-partnerships/issues/36) in the PPP extension could be reused for any types of framework agreement.

**Comment by jpmckinney** [comment]
Page resolving this issue is readable at http://standard.open-contracting.org/latest/en/implementation/related_processes/
