### ISSUE TITLE
OCDS Schema Bug Fixes: comment period

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#311]
Ahead of the [start of the 1.1 upgrade cycle, for OCDS](https://groups.google.com/a/open-contracting.org/forum/#!topic/standard-discuss/I20-s5_UCko), we are looking to address a couple of outstanding bugs in the schema which have come to light through documentation updates and recent use of the standard.

These are covered in the list below, and in [Pull Request 305](https://github.com/open-contracting/standard/pull/305). We plan to merge these into the schema in two weeks time, unless there are objections. 

(1) Notice Codes to camelCase
The documentType codelist had three values where the code was incorrectly normal case, rather than camelCase. These will be updated to be consistent with other codes. Our experience shows that users are adopting camelCase in their files for consistency, so this should not have a breaking-change impact.

The three codes affected are: 

Tender notice -> tenderNotice
Award notice -> awardNotice
Contract notice >contractNotice

(2) Updating publisher blocks
The publisher blocks in release and record packages were incorrectly documented, and were requiring schemes to be provided as URIs. This has been updated so that the publisher identifier schemes can be any string, and the documentation highlights the difference between Organisation Identifier blocks, and the identifiers for publishers.

The inconsistency between publisher and identifier blocks remains, as this would be a breaking change for consideration in 1.1 process (See https://github.com/open-contracting/standard/issues/245) 

(3) Minor documentation fixes
A small number of spelling mistakes have been made to the text in the schema, which is used to drive documentation. A codelist description referring to a missing field has also been amended.

(4) Versioned Release Schema
A new process has been put in place to generate the Versioned Release schema. This fixes a number of errors in this schema, and also substantially simplifies its presentation, through the use of #refs and re-usable blocks.

This should improve validation of versioned data, although a number of issues remain relating to properties not required in versioned data, so we do recommend consulting the support team regards validation of any versioned files.  

We are also aware there is more work to do on clarifying both the schema and documentation around versioning - and so hope this small step can provide a foundation for discussion of more substantive issues in the 1.1 upgrade process. 

(5) Null values: award and contract status
A number of enum lists were missing 'null' from the list of allowed values, causing validation failures when users wished to unset a status list value. Null values have been added to contract.status and award.status enum lists. 

An issue concerning allowing null objects (https://github.com/open-contracting/standard/issues/251) has not been included in the 1.0.1 bug fix process, but is under review for a later bug fix process after more extensive testing. 

---

Please add any comments on this issue by 13th March if you believe any of these bug fixes will create issues for your implementation of OCDS. 

For other issues, remember that you can submit to the OCDS issue tracker at any time.

**Comment by Bjwebb** [comment]
I've also added a small codelist description change (originally from https://github.com/open-contracting/standard/pull/307) to [Pull Request 305](https://github.com/open-contracting/standard/pull/305), and mentioned this in "(3) Minor documentation fixes" above.
