### ISSUE TITLE
Documentation error: broken link on merging

### ISSUE THREAD

**Issue by KrzysztofMadejski** [open-contracting/standard#312]
http://standard.open-contracting.org/latest/en/getting_started/releases_and_records/getting_started/schema/merging.md

is 404-ing on http://standard.open-contracting.org/latest/en/getting_started/releases_and_records/

**Comment by Bjwebb** [comment]
Looks like this should link to http://standard.open-contracting.org/latest/en/schema/merging/

I'll fix this next week, to go live with some other planned documentation fixes.

**Comment by Bjwebb** [comment]
This is now fixed on the dev copy of the standard site, which will be going live later this week. http://standard.open-contracting.org/1.0-dev/en/getting_started/releases_and_records/

**Comment by Bjwebb** [comment]
This is now fixed on the live site http://standard.open-contracting.org/latest/en/schema/merging/
