### ISSUE TITLE
Documentation Error: Ordered list

### ISSUE THREAD

**Issue by caprenter** [open-contracting/standard#313]
In this section:
http://standard.open-contracting.org/latest/en/schema/merging/?highlight=merge#merging-rules

I think we should have bullet points 1 - 4 instead of 1,2, 1,1

**Comment by timgdavies** [comment]
Assigning Ben to capture in other quick documentation fixes next week.

**Comment by Bjwebb** [comment]
This is now fixed on the dev site http://standard.open-contracting.org/1.0-dev/en/schema/merging/#merging-rules

**Comment by Bjwebb** [comment]
Now fixed on live http://standard.open-contracting.org/latest/en/schema/merging/#merging-rules
