### ISSUE TITLE
numberOfTenderers - No description of field name in standard

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#314]
The description of numberOfTenderers is blank here: http://standard.open-contracting.org/latest/en/schema/reference/?highlight=numberoftenderers

Other fields in this table are documented.

**Comment by Bjwebb** [comment]
Looks like this is because in the schema we have `definition` instead of `description` https://github.com/open-contracting/standard/blob/1.0/standard/schema/release-schema.json#L214

**Comment by Bjwebb** [comment]
We think that this issue should be included in 1.0.2, to be released in September, because it is a bug fix.

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
