### ISSUE TITLE
Tender: Payment terms

### ISSUE THREAD

**Issue by joshuacpowell** [open-contracting/standard#317]
Update from @timgdavies: We are looking to include an extension for these fields in OCDS 1.1, and are currently consulting on appropriate codelists. 
## Original post

(Apologies if missed elsewhere) Have been searching for an appropriate field to include details on payment terms and contract types (this may be best split into two tickets):

Payment Terms:
By milestone
By date
Lump sum
etc.

Contract Type:
Fixed price
Cost reimbursement
Cost reimbursement + fee
etc.

For example, in Viet Nam, there is:
Trọn gói                          =>   All in one (lump sum)
Theo đơn giá                  =>   According unit (price per item)
Theo thời gian                =>   By the time (cost reimbursement) 
Theo tỷ lệ phần trăm      =>   According percentage (seems to be cost + fee)
Hỗn hợp                         =>   Mixed

**Comment by timgdavies** [comment]
Sorry for the slow reply on this. I don't think we do have a good field for this now, so definitely something to discuss for 1.1 / extensions.

**Comment by AlCollier** [comment]
The NEC3 contract has the following options:

NEC3
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Option:
Engineering and Construction Contract Option A priced contract with
activity schedule
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Option
NEC3: Engineering and Construction Contract Option B: priced contract with
bill of quantities
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Opt-1
NEC3: Engineering and Construction Contract Option C: target contract with
activity schedule
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Opt-2
NEC3: Engineering and Construction Contract Option D: target contract with
bill of quantities
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Opt-3
NEC3: Engineering and Construction Contract Option E: cost reimbursable
contract
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Opt-4
NEC3: Engineering and Construction Contract Option F: management contract
https://www.neccontract.com/Products/Contracts/Engineering-Construction-Contract/NEC3-Engineering-and-Construction-Contract-ECC/NEC3-Engineering-and-Construction-Contract-Opt-5

I think this would need to be at a fairly low level - individual lots - and
even then one contract may well use multiple payment types. For example I
did a highways contract a couple of years ago that used options A, C and E
for different elements.

**Comment by ekoner** [comment]
Thanks Al for the clarification. I've added this to the agenda for extensions / version upgrade discussions.

All the best,

Edafe Onerhime
OCDS Helpdesk

**Comment by robredpath** [comment]
Next steps for me: 
- Work out what this would look like. Is there an existing codelist that I could use? 
- See if there is demand to decide if it's core vs extension

**Comment by robredpath** [comment]
So, there's two parts to this - 'payment terms' and 'contract type'

For 'payment terms', there's http://www.unece.org/trade/untdid/d07a/tred/tred4279.htm and http://www.unece.org/fileadmin/DAM/cefact/recommendations/rec17/rec17_1982_ecetrd142.pdf, but I'm not sure that's quite what we're looking for. It may be that we want to allow multiple codes to be provided to describe various aspects of the payment terms, or that we restrict it to just the type of term described above. 

For 'contract type', there's a handful of codelists of varying completeness - eg  https://www.fpds.gov/help/Type_of_Contract.htm , but that has single-letter codes. I'd suggest that we create and maintain a new codelist as part of v1.1, which incorporates common contract types as well as the NEC3 contracts and is open to suggestions of others. I'm open to the argument that the codelist should be more generic to aid interoperability across countries, though (so NEC3 contracts would be coded according to the best match)

**Comment by duncandewhurst** [comment]
We should also consider whether these fields sit only under _contract_ or whether they could also be specified at the _tender_ stage and what the use case for disclosure of structured information on payment terms and contract types at _tender_ stage would be

**Comment by joshuacpowell** [comment]
I think there is a use case for having @ tender stage, as it would enable M&E/analysis of how different payment terms/contract types attract competition, as well as if they impact the spread between estimated/reserve price and award value. I'd favor higher level codes for this, with the option to include more detailed custom codes e.g. through contractTypeDetails as with procurementMethod

**Comment by duncandewhurst** [comment]
Flagging a possible naming conflict with the **contractType** field poposed in #376 

Given that the contract types suggested here are all related to pricing could we use **pricingType** instead?

**Comment by duncandewhurst** [comment]
The following definitions were proposed at the codelists breakout session at IODC:

| Code | Definition |
| --- | --- |
| fixedPrice | Price indicated in signed contract does not change regardless of time expended or resources used. Any change requires an amendment to the contract. |
| costReimbursement | Actual cost of completing contract with no additional fees |

**Comment by duncandewhurst** [comment]
The [World Bank Procurement Regulations](https://policies.worldbank.org/sites/ppf3/PPFDocuments/4005Procurement%20Regulations_Final%20for%20publishing.pdf) defines the following contract types:

| Contract Type | Definition |
| --- | --- |
| Lump-sum | Under a lump-sum contract, the contractor/Consultant agrees to perform the scope of services for a fixed contract amount. Payment percentages or amounts may be linked to the completion of contractual milestones or determined as a percentage of the value of the work to be done. |
| Performance-based | In a performance-based contract, the payments are not made for inputs but for measured outputs that aim at satisfying functional needs in terms of quality, quantity, and reliability. |
| Admeasurement - based on Unit Prices | This type of contract is based on estimated quantities of items and contractual unit prices for each of these items, and is paid on the actual quantities and contractual unit prices. |
| Time-based | Under time-based contracts, the payment is made on the basis of agreed rates and time spent, plus reasonable incurred reimbursable expenses. |
| Reimbursable-cost | Under reimbursable-cost contracts, payments cover all actual costs, plus an agreed fee to cover overhead and profit. |

Thanks to Hunt La Cascia from the World Bank for the pointer to these definitions.

**Comment by joshuacpowell** [comment]
Would prefer the more detailed breakout from WB vs the binary of fixed/reimbursement.

**Comment by duncandewhurst** [comment]
@joshuacpowell looking at your example from Vietnam I think these are covered by the contract types from the WB procurement regulations.

Do you have an example of data supply where the payment terms you proposed in the original post are broken out separately? Or a user need for this?

Thanks!

**Comment by duncandewhurst** [comment]
Feedback from Alexandre Borges de Oliveira, World Bank:

Most contracts would fall into the buckets defined above in current World Bank Procurement Regulations, however there are several other options, including the following types from the previous version of the regulations:

Contract Type | Description
------|------------
Retainer and/or Contingency (Success) Fee Contract | Retainer and contingency fee contracts are widely used when consultants (banks or financial firms) are preparing companies for sales or mergers of firms, notably in privatization operations. The remuneration of the consultant includes a retainer and a success fee, the latter being normally expressed as a percentage of the sale price of the assets.
Percentage Contract | These contracts are commonly used for procurement and inspection service providers. Percentage contracts directly relate the fees paid to the consultant to the estimated or actual project construction cost, or the cost of the goods procured or inspected. The contracts are negotiated on the basis of market norms for the services and/or estimated person-month costs for the services, or competitively bid. It should be borne in mind that in the case of architectural or engineering services, percentage contracts implicitly lack incentive for economic design and are hence discouraged. Therefore, the use of such a contract for architectural services is recommended only if it is based on a fixed target cost and covers precisely defined services (but not, for example, works supervision).
Indefinite Delivery Contract (IDCs) or Price Agreement | IDCs are used when Borrowers need to have quick and continuing access to “on call” specialized advisory services for a particular activity, the extent and timing of which cannot be defined in advance. IDCs are commonly used to retain “advisers”, expert adjudicators, members of panels, or experts to participate in the design or implementation of sub-projects or complex tasks during the execution of Bank-financed projects (for example, dam panel, dispute resolution boards, institutional reforms, procurement advice, technical troubleshooting, evaluation of safeguard issues, and so forth), normally for a period of at least a year. The services are offered by qualified firms through a list of proposed experts they commit to make available in letters of intent in response to an REOI setting selection criteria focusing on the relevant qualifications and expertise of the required experts. Borrowers shall then establish a long list of qualified experts. The Borrower and the firms agree on pre- established fee rates to be paid for the experts and on standard conditions of contract, and payments are made on the basis of the time actually spent. Experts shall be selected from the long list on the basis of a “call off” request with specific TOR for the assignment, based on the qualitative evaluation/comparison of the CVs of the proposed experts or the fees level, and a specific contract is signed for each assignment.

Alexandre also recommended a white paper from the [Chartered Institute of Procurement and Supply](https://www.cips.org/en-gb/homepage/) on contract types in different jurisdictions.

**Comment by timgdavies** [comment]
As this will be an extension I'm not going to include it in the first round of 1.1 review - but we should be able to include it in the extensions documentation for 1.1.

@duncandewhurst would you be able to have a first shot at working this extension up? (Just the pricingType - the other contractType issues are handled now).

**Comment by timgdavies** [comment]
One part of this issue (contact type) is handled in the procurementCategory field. The Payment Terms field was left out of 1.1 on grounds of time, and will be explored as a community extension at a later date.

**Comment by sofiiashnyr** [comment]
In Ukraine (ProZorro), there is an idea to allow Buyer indicate, on the tender level, information regarding prospective payment terms for the contract so that Suppliers can filter out through it to choose which tender fits them best. 
As it was discussed with @timgdavies, we could have a _paymentTerms_ object, with 3 properties inside: _prepaymentPercentage_ (to indicate whether а prepayment is foreseen, with 0% - 100% as allowed values), paymentConditions (net10/15/30/60/other), and _paymentDetails_ (to provide an explanation if _other_ was chosen in _paymentConditions_).

**Comment by timgdavies** [comment]
## Background research

As requirements here are getting more complex, I've taken a look at any other precedents we should be drawing on. I see that [Universal Business Language has a PaymentTerms object](http://www.datypic.com/sc/ubl20/e-cac_PaymentTerms.html), but this looks more appropriate to use within invoices and billing, rather than announcing the anticipated payment terms for a contract.

I've also noted [this (non-authoritative) list of common invoicing and payment terms](https://www.nibusinessinfo.co.uk/content/payment-terms-commonly-used-invoice-payment-terms-and-their-meanings). 

I've checked (though not comprehensively) for anything in [CEN BII](http://cenbii.eu/) that might be drawn upon also. 

## Updated sketch

To offer a rough summary of this thread, we have a proposal emerging for a `paymentTerms` object, which might contain a range of properties, including

* `paymentCondition`, `invoiceTerms` or `creditTerms` (suggestions on best synonym welcome) with free text or codelist values such as net 10/net 15 etc. 
* `paymentDetails` - free text explanation
* `prePaymentPercentage` - a value from 0 to 1 (the precedent in the [PPP Profile](http://standard.open-contracting.org/profiles/ppp/latest/en/framework/) is to express percentage as a decimal from 0 to 1, which allows validation of max: 1; otherwise values can be ambiguous in data exchange between systems). 
* `paymentTrigger` - to capture whether milestone, lump sum, date etc. (this needs more work)

This would sit alongside to a `contractType` property, which would use a [codelist based on the above comments](https://github.com/open-contracting/standard/issues/317#issuecomment-261562191)

## Draft example

```json
{
  "tender": {
    "id": "01",
    "value": {
      "amount": 10000,
      "currency": "USD"
    },
    "contractType": "fixedPrice",
    "paymentTerms": {
      "invoiceTerms": "NET 30",
      "paymentDetails": "Invoices are paid within 30 days, on confirmation of milestone completion.",
      "prePaymentPercentage": 0.2,
      "paymentStructure": "milestone"
    }
  }
}
```

## Alternative / complementary approach

An alternative or complementary approach is to add a `paymentPercentage` property to milestones, and to optionally have a milestone type for `initiation`, such that for contracts paid by milestones, each milestone could have anticipated payments attached, with an initiation milestone used to indicate prepayment. 

```json
{
  "tender": {
    "id": "01",
    "value": {
      "amount": 10000,
      "currency": "USD"
    },
    "contractType": "fixedPrice",
    "paymentTerms": {
      "invoiceTerms": "NET 30",
      "paymentDetails": "Invoices are paid within 30 days, on confirmation of milestone completion.",
      "prePaymentPercentage": 0.2,
      "paymentStructure": "milestone"
    },
    "milestones": [
      {
        "id": "1",
        "type": "delivery",
        "title": "Project kick off",
        "paymentPercentage": 0.4
      },
      {
        "id": "2",
        "type": "delivery",
        "title": "Project completion",
        "paymentPercentage": 0.5
      }
    ]
  }
}
```

## Request for input

Feedback on the above draft modelling is welcome

**Comment by timgdavies** [comment]
@juanpane I'd welcome any thoughts you have on the above - and whether it may have any relationship to work on tracking payment delays by government.

**Comment by myroslav** [comment]
On reflection we propose to have the following three properties within the `paymentTerms` object: `prePaymentPercentage`; `invoiceTerms` (as discussed with @timgdavies); `invoiceTermsDetails` (especially important in the case of `“other”` invoiceTerms).

Since we are following “from simple to complex” design pattern, we are reevaluating idea of milestones introduction, that would render the system too complex. Given that we would like to keep the system as simple as possible in first iteration of implementation thus considering to abandon the idea of having milestones within the object.

**Comment by jpmckinney** [comment]
The new eForms regulation in the EU has only a free-text field for financing and payment terms: https://docs.ted.europa.eu/eforms/latest/schema/procedure-lot-part-information.html#termsFinancialSection

This modelling choice reflects the great diversity of payment terms, and the corresponding difficulty in coming up with a model to represent them all, in a way that is not overly complex.

There is not consensus on an appropriate (or even partial) model. Given the above factors, the outlook is not good that it will be achieved.

Closing in favor of using the [contract terms extension](https://extensions.open-contracting.org/en/extensions/contractTerms/master/), specifically its `financialTerms` field.
