### ISSUE TITLE
Geo-referencing concession contracts

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#318]
Related to #250 

AidData and the Concessions Working Group (a TrustAfrica-facilitated network of civil society organizations in Liberia that are engaged in efforts to monitor the activities of natural resource concessionaires) have worked together over the last twelve months to systematically identify and code the attributes of all known concession contracts (approved between 2006 and 2015) in Liberia, including the origin countries of the investors, reinvestment and revenue sharing commitments, and the types of natural resources in the concession areas.

AidData have georeferenced all concession areas through the digitization of maps and the manual construction of polygons based upon the field survey instructions contained in concession contracts. 

This issue tracks discussions around future location and extractive / concession extensions of OCDS.

**Comment by jpmckinney** [comment]
There is an open issue at https://github.com/open-contracting/ocds-extensions/issues/10

Otherwise, this issue contains no proposal or question, so closing.
