### ISSUE TITLE
submissionMethod: Deprecate codes

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#322]
Updates to the submission method codelist are proposed for version 1.1 of OCDS.
## The issue

Submission method is an open codelist which currently includes:
- electronicAuction
- electronicSubmission 
- written
- inPerson

This appears to mix up the mode of submission (online, post, in person), with the way the process is run (auction or otherwise)
## Proposal

This codelist should be updated based upon expert input and consultation
## Engagement

We are inviting suggestions for what the submissionMethod codelist should contain.
- What codes are required by key use cases? (e.g. Red Flag Analysis?)
- Are there existing codelists we can defer to here? 
## History

Comments from user:

> The inclusion of 'electronicAuction' in the [submissionMethod](http://standard.open-contracting.org/latest/en/schema/codelists/#submission-method) codelist appears odd - as use of an auction is a separate issue from submitting electronically.

**Comment by chrisalexsmith** [comment]
Electronic auction is already covered by electronic submission and electronic auction is a method of procurement.

**Comment by duncandewhurst** [comment]
Feedack from Alexandre Borges de Oliveira, World Bank:

* Agree with the proposal to remove electronicAuction since this is a procurement method rather than submission method
* In most legislation it is unusual for there to be a distinction between written and inPerson, most analysis would be based on online vs offline, where the latter could be either postal or inPerson
* written is an ambiguous code - does this mean postal?
* electronicSubmission could be further split into: email, portal, website etc. but this granularity may not yeild any further insights

**Comment by timgdavies** [comment]
In looking at the use-cases for this codelist:

* It does not appear to be used by any of the existing redFlag analysis approaches being explored (although I can see potential uses to detect cases where submission method is overly complex / an outlier - or where the method was more open to interference);
* In EU forms, the codes around electronic submission appear to have a policy reporting angle to them - with e-Procurement required unless there are particular exceptional reasons not to use it;

I agree that there is some confusion created by inclusion of electronicAuction, but as our 'procurementMethod' codelist focusses in 'open', 'limited', 'closed' rather than going into more structured depth about methodology used - to remove auction here, without re-introducing it elsewhere (which is now out of scope for 1.1) would potentially lose information from the standard. Whereas an analyst can just combine 'electronicSubmission' (other than auction) with 'electronicAuction' to analyse all the cases of electronic submission.

So, recognising there is a need for more work on this codelist in post 1.1, the proposed 1.1 change would be to add the following definitions to these codes:

| Code                 | Title                 | Description                                                                                                |                           |                             |                              | 
|----------------------|-----------------------|------------------------------------------------------------------------------------------------------------|---------------------------|-----------------------------|------------------------------| 
| electronicSubmission | Electronic Submission | Bids will be recieved through an electronic procurement platform.                                          |                           |                             |                              | 
| electronicAuction    | Electronic Auction    | Bids will be recieved through an electornic auction platform.                                              |                           |                             |                              | 
| written              | Written               | "Bids will be recieved via written documents, delivered as hard copies, via generic e-mail systems, or some similar mechanism." | 
| inPerson             | In Person             | "Bids will only be recieved if hand delivered at the time and place specified in submissionMethodDetails." |                           |                             |                              | 



Will be looking to stage these definition updates tomorrow.

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> It seems that everyone agrees that electronic auction should be removed from the codelist, yet it has been kept in. I would suggest taking it out an adding it as a separate true/false field "Electronic auction used". It's modeled the same way in the EU.
> 
> Also, e-mail should be separated from mail. It makes a big difference whether tenders, especially cross-border, can be submitted electronically or have to be physically mailed. In our opinion, e-mail is probably closer to Electronic Submission than paper (the main difference compared to an electronic submission system being the traceability and ensuring that a tender cannot be opened too early), but having e-mail as a separate value in the codelist would probably be the best.
> 
> Terminology-wise, for the elements of the list to be mutually exclusive, "written" could be changed to "mail".

Correction (2017-09-01): in the post above, I originally said "electronic submission" instead of "electronic auction" by accident.

**Comment by jpmckinney** [comment]
Noting that 1.1 added definitions, but otherwise did not edit the codelist (we would need to deprecate codes).

**Comment by jpmckinney** [comment]
With regard to electronic auctions, I propose (likely as an extension):

* deprecate the 'electronicAuction' code in the `submissionMethod` codelist
* add a new `procurementMethodModalities` field with an open `methodModalities` codelist, to avoid diluting or confusing the semantics of the `procurementMethod` field and its `method` codelist, which directly map to definitions in the GPA, with the exception of 'direct' whose justification is in #380 

----

The codes in `methodModalities` would include at least:

* `electronicAuction` for 'whether it will involve … electronic auction' from GPA
* a code for 'whether it will involve negotiation'  from GPA
* a code for '   ⃞  Joint procurement is involved' from EU forms
* a code for '+   ⃞  The buyer reserves the right to award the contract on the basis of the initial tenders without conducting negotiations' from EU forms
* a code for '+   ⃞  The number of solutions or tenders will be reduced in successive stages of the procedure.' from EU forms
* a code for '   ⃞  Accelerated procedure' from EU forms

The idea is that these modulate the procurement method without fundamentally changing the status of open/limited/selective/direct.

(Note that 'Type of procedure' in EU forms offers more disjoint options than the `method` codelist, and so an extension/profile for EU forms would likely modify the `method` codelist.)

With respect to other data about electronic auctions, the Revised GPA has:

> Article X:7(e) where the procuring entity will hold an electronic auction, the rules, including identification of the elements of the tender related to the evaluation criteria, on which the auction will be conducted;
> Article XIV:1(a) the automatic evaluation method, including the mathematical formula, that is based on the evaluation criteria set out in the tender documentation and that will be used in the automatic ranking or re-ranking during the auction;
> Article XIV:1(c) any other relevant information relating to the conduct of the auction.

From the EU forms, there is also:

> + Web address of electronic auction: [website]
> + Additional information about electronic auction:

For now, I anticipate the guidance will be to put this information into `tender/procurementMethodDetails`, but there may be a motivation to break it out into new fields.

**Comment by jpmckinney** [comment]
My proposal for a Procurement Method Modalities extension can be pursued in #695.

At this stage, it seems as though all codes should be deprecated:

* 'electronicAuction' is not a submission method
* 'electronicSubmission' is overly narrow ("through an electronic procurement platform"), and expanding it would cause overlap with 'written', which includes "generic e-mail systems"
* 'written' mixes paper and electronic (email) submission methods, which is an important distinction, as noted by Alexandre Borges de Oliveira and @JachymHercher 
* 'inPerson' has received little expressed interest: it's not clear that this is an important distinction from paper submissions

A recent eForms discussion https://github.com/eForms/eForms/issues/251#issuecomment-475255962 worked through some of the nuances of techniques (including those relating to submission), and the new eForms have a more robust Submission Terms business group, which we should review when replacing this codelist (which will have to occur in OCDS 1.2).

**Comment by JachymHercher** [comment]
FYI: In some EU countries, an in person or snail mail submitted USB drive (CD, etc.) is legally treated as "paper submission". This means there is "paper submission", but "electronic opening of tenders". (This is 99% pointless trivia, 1% it could perhaps influence the formulation of a definition somewhere.)

**Comment by jpmckinney** [comment]
The definition of 'written' might have been influenced by the GPA definition – though that definition isn't specific to submission methods and is used to solve different problems.

>  in writing or written means any worded or numbered expression that can be read, reproduced and later communicated.  It may include electronically transmitted and stored information;

**Comment by ColinMaudry** [comment]
Do we also deprecate the `tender.submissionMethod` field?

We could also remodel it following the approach taken by eForms with their Submission Terms business group (BG-102), partially implemented in the [Submission terms extension](https://github.com/open-contracting-extensions/ocds_submissionTerms_extension).

**Comment by jpmckinney** [comment]
Good question. We don't have any proposals for alternative codes. I think it is okay to deprecate this field. We can consider merging the submission terms extension into core. That extension supports the only clear use case from the above discussion, which is distinguishing opportunities for which electronic submission is required/allowed/not allowed.

**Comment by ColinMaudry** [comment]
I need to know the outcome of #1183 to write a fitting `Deprecated.description` for `tender.submissionMethod`.

**Comment by jpmckinney** [comment]
Can we write a description based on this issue, and then add a comment to #1183 to update the description if that issue is resolved?

**Comment by ColinMaudry** [comment]
I take a shot at a concise deprecation description:

> The field has been deprecated in version 1.2 because all the codes of the submissionMethod codelist have been considered to be either irrelevant or unclear.

All the other descriptions of deprecation contain guidance with alternative ways to publish the corresponding data. If we don't add the submissionTerms extension to core, there will be no guidance to write.

**Comment by ColinMaudry** [comment]
Does deprecating `submissionMethod` means deprecating `submissionMethodDetails`?

**Comment by jpmckinney** [comment]
> Does deprecating `submissionMethod` means deprecating `submissionMethodDetails`?

I'll reply in #1183 since `submissionMethodDetails` is fine on its own, but if the submissionTerms extension is merged, it'd make sense to move the field.

**Comment by jpmckinney** [comment]
> I take a shot at a concise deprecation description:
> 
> > The field has been deprecated in version 1.2 because all the codes of the submissionMethod codelist have been considered to be either irrelevant or unclear.
> 
> All the other descriptions of deprecation contain guidance with alternative ways to publish the corresponding data. If we don't add the submissionTerms extension to core, there will be no guidance to write.

We can leave it short, and defer to a "Deprecation note" column of the individual codes for specific guidance (codelists currently only have a "Deprecated" column to specify the version). For the field itself:

> This field is deprecated, because all codes from the submissionMethod codelist are deprecated. Refer to the Deprecation note of individual codes.

The version is given by `deprecated.deprecatedVersion`, so we don't need to repeat it in `deprecated.description`.

**Comment by ColinMaudry** [comment]
I suggest the following deprecation notes for the codes, based on your comment https://github.com/open-contracting/standard/issues/322#issuecomment-475380695:

- electronicSubmission: Use the submission terms extension instead.
- electronicAuction: Use  the techniques extension instead.
- written: This code mixed paper and electronic (email) submission methods.
- inPerson: ?

Don't we need alternative options for paper and email submissions?

**Comment by jpmckinney** [comment]
* electronicSubmission: This code distinguished electronic submission through a procurement platform from other forms of electronic submission. This distinction is not supported by use cases. Use the submission terms extension instead.
* electronicAuction: An electronic auction is a technique, not a submission method. Use the techniques extension instead.
* written: This code was based on a definition of "written" for communication between parties, which distinguished between verbal and written communication, rather than between paper and electronic communication. Use the submission terms extension instead.
* inPerson: This code distinguished paper submissions delivered in-person from paper submissions delivered by mail. This distinction is not supported by use cases.

> Don't we need alternative options for paper and email submissions?

electronicSubmissionPolicy in the submission terms extension can be used:

* notAllowed: paper only
* allowed: paper or electronic
* required: electronic only

**Comment by ColinMaudry** [comment]
Closed by #1200
