### ISSUE TITLE
Standard should specify use of UTF-8 for encoding JSON

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#323]
See https://github.com/OpenDataServices/cove/issues/344

**Comment by akuckartz** [comment]
Maybe you can require I-JSON conformance. See https://tools.ietf.org/html/rfc7493

**Comment by timgdavies** [comment]
+1 to using I-JSON.

**Comment by timgdavies** [comment]
This issue is under consideration for the 1.1 milestone. 

## The problem

We do not currently specify character encoding for JSON

## Proposal

We should require [I-JSON conformance](https://tools.ietf.org/html/rfc7493)

## Engagement

Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
I'm adding the following section to the serialization page:

> Valid JSON serializations of OCDS data MUST follow the [I-JSON (Internet JSON)specification from RFC7493](https://tools.ietf.org/html/rfc7493) which requires [UTF-8 encoding](https://en.wikipedia.org/wiki/UTF-8) and introduces a number of constrains and recommendations for handling numbers, objects and dates. 

I will raise an issue for the OCDS Validator to ensure it checks for I-JSON compliance.
