### ISSUE TITLE
Add publisher field (release schema)

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#325]
Optionally a record/release should be able to have embedded within it the following properties.
- packageURI
- publishedDate
- publisher
- license
- publicationPolicy

This is important for API usage where all the releases/records do not belong to the same package or even belong to the same publisher. This is important as the API user should have easy access to this information (especially things like the licence).

These items most likely should be under a new property called possibly "packageMetadata" 
An example release with this property would look like:

```
{   
    "language": "en",
    "ocid": "ocds-213czf-000-00001",
    "id": "ocds-213czf-000-00001-05-contract",
    "date": "2010-05-10T10:30:00Z",
    "tag": [
        "contract"
    ],
    "initiationType": "tender",
    ...
    "packageMetadata": {
         "uri":"http://a.com/ocds-213czf-001-01-planning.json",
         "publishedDate":"2009-03-15T14:45:00Z",
         "publisher": {
             "scheme": "GB-COH",
             "uid": "09506232",
             "name": "Open Data Services Co-operative Limited",
             "uri": "http://standard.open-contracting.org/examples/"
          },
         "license":"http://opendatacommons.org/licenses/pddl/1.0/",
         "publicationPolicy":"https://github.com/open-contracting/sample-data/"
}
```

These properties should be excluded from the merging process when creating the versionedRelease/compiledRelease, as it is possible for a record to have many source packages. Nonetheless, the record itself could have a "packageMetadata" property also.

This could be considered as an extension (but a standadized one) and not part of the core standard as it is optional.

**Comment by timgdavies** [comment]
This can be worked out outside of 1.1, more in relation to API standardisation.

**Comment by jpmckinney** [comment]
Noting a need for this was expressed in the context of a government having multiple authors of releases, and needing to trace back which entity authored a release within a package.

**Comment by jpmckinney** [comment]
Copying relevant parts of my comment at https://github.com/open-contracting/api-specification/issues/15#issuecomment-437423524

* `uri`: I don't think we should be putting the `uri` of the package in the release, as a release can be included in any number of packages, and releases are expected to be unique and immutable.
* `publishedDate`: Same reason as for `uri` – plus release has its own `date` already.
* `publicationPolicy`: It seems an overreach for data to declare the URL of the policy for its own publication, especially as this URL can change over time – and publishers shouldn't have to publish a new release to update it. This policy should be discoverable without looking at data.
* `license`: Same reason as for `publicationPolicy`. The pattern of declaring the license on the pages that provide access to data has been fine for data formats that have no way of declaring a license, which is the vast majority of open data (see [page 19 of this report](https://drive.google.com/file/d/0B739vUevKlPgUlZrcDlkd3QwdGc/view)).

So, we're just talking about `publisher`, which I think makes sense to have at the release-level, in core OCDS. (Publisher names and URLs change over time, but so do those of parties.)

Not discussed here are `extensions` and `version`, which are needed to interpret the data. Putting these in their current form would be very repetitive. We might explore alternatives like #426.

**Comment by jpmckinney** [comment]
Noting that, with respect to semantics, the release-level publisher should be the original publisher, and  should be immutable like the other fields in the release.

**Comment by jpmckinney** [comment]
Here is an extension implementing the field: https://github.com/CompraNet/ocds_releasePublisher_extension
