### ISSUE TITLE
schemaExtensions property to release/record

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#326]
At the moment there is no way you can tell if a particular extension is being used on a release/record.  This would be useful know for the data consumer and for any API interface to the data.

To solve this, we can add an extra property on a release/record, that specifies what extensions have been used.

A new schemaExtension definition could contain:
- jsonPatchUrl (This is useful as any consumer of the data can apply this patch to the schema before processing the data.  This will give a validator the possibility to validate extensions as well by applying the patch first)
- description
- documentationUrl

The JSON Schema changes for a release would look something like: 

```
"properties": {
     "schemaExtensions": {
            "title": "Schema Extensions",
            "description": "All extensions added to the release schema",
            "type": "array",
            "items": { "$ref": "#/definitions/schemaExtension" },
    }
}
"definitions": {
    "schemaExtension": {
        "type": "object",
        "properties": {
                "jsonPatchUrl": {
                    "title": "json patch url",
                    "description": "The path to the JSON patch that was used to extend this releases schema",
                    "type": "string",
                    "format": "uri"
                },
                "description": {
                    "title": "Description of extension",
                    "description": "Short description of what this extension does",
                    "type": "string",
                    "format": "uri"
                }
                "documentationUrl": {
                    "title": "Extensions Documentation",
                    "description": "Link to extensions complete documentation",
                    "type": "string",
                    "format": "uri"
                }
          }
     }
}

```

**Comment by kindly** [comment]
Another option to this could be to consider having extensions have their own JSON schema #327

This would mean we could simplify the definition in a release record to:

```
"properties": {
     "schemaExtensions": {
            "title": "Schema Extensions",
            "description": "links to OCDS extensions that have been applied to this release",
            "type": "array",
            "items": { "type": "string", "format": "uri"}
     }
}
```

**Comment by kindly** [comment]
closed because of #335

**Comment by Bjwebb** [comment]
I don't think this should be closed, because even with the new extension setup, we still need a way of linking to an extension from a release/record.

Since we can link to the extensions `extension.json`, the suggestion in https://github.com/open-contracting/standard/issues/326#issuecomment-218484653 should still work.

I've been moving the proposed location extension over to the new extension format. As an example, a release using that would contain:

```
"schemaExtensions": ["https://raw.githubusercontent.com/Bjwebb/proposed_location_extension/master/extension.json"],
```

**Comment by kindly** [comment]
@Bjwebb agreed yes this was exactly what was intended and forgot this was not recorded anywhere.

The only slight difference in my thinking was to link to the extension url path not the extension.json file
i.e

```
"schemaExtensions": ["https://raw.githubusercontent.com/Bjwebb/proposed_location_extension/master/"],
```

This gives people the option of not having an extension.json file.

**Comment by timgdavies** [comment]
Continued in #326

**Comment by Bjwebb** [comment]
> Continued in #326

@timgdavies  #326 is this issue, and I'm not sure what issue was meant to be linked to instead.

**Comment by timgdavies** [comment]
Sorry - this should be continued in #301
