### ISSUE TITLE
Update documentation with guidance on inclusion of check digit in CPV id

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#328]
The current documentation for Item Classification Schemes ([here](http://standard.open-contracting.org/latest/en/schema/codelists/#item-classification-scheme)) does not specify whether the check digit should be included when using CPV ids.

In the current sample data some examples include the check digit and some exclude the check digit (e.g. lines 53 and 60 [here](https://github.com/open-contracting/sample-data/blob/master/fictional-example/ocds-213czf-000-00001-02-tender.json))

Codes in the official documentation ([here](http://simap.ted.europa.eu/web/simap/cpv)) are given including the check digit.

Should the guidance be to include or exclude the check digit when using CPV codes?

**Comment by timgdavies** [comment]
I would suggest we follow the official guidance and include the check-digit. Proposal is to update the documentation accordingly.

**Comment by timgdavies** [comment]
We notice that TED data through the web interface does not display the check-digit. 

Need to check if underlying data contains the check-digit or not.

**Comment by timgdavies** [comment]
Exported data from TED does not appear to contain the check digit. 

It appears that practice is not terribly consistent around this, so I have updated the codelist entry to include what is essentially a warning for users that they need to parse these identifiers carefully:

"Codes may be provided with or without the check digit, and consuming applications should be aware of this when processing data with CPV codes."
