### ISSUE TITLE
Codelist properties in schema

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#336]
This is a proposal to add new properties in JSON Schema to point to relevant code list and specify if it is an open codelist.

Lets take [award criteria](http://standard.open-contracting.org/latest/en/schema/codelists/#award-criteria) as an example.  It is an open codelist.  The schema for it should then look like

```
{
                    "description": "Specify the award criteria for the procurement, using the [award criteria codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#award-criteria)",
                    "type": ["string", "null"],
                    "mergeStrategy": "ocdsVersion",
                    "openCodelist": true,
                    "codelist": "awardCriteria.csv"
}
```

So there should be two extra properties added to the JSON schema.  
- codelist (filename of the codelist - required if this field is a codelist)
- openCodelist (only required and set to true if an open codelist, otherwise assumed closed codelist)

The "codelist" property is the file-name of the file in the [codelist directory](https://github.com/open-contracting/standard/tree/1.0/standard/schema/codelists) in the standard repository. An extension should be able to overwrite a codelist and specify their own or add codelists as laid out in the [extension template](https://github.com/open-contracting/standard_extension_template) .

**Comment by timgdavies** [comment]
The rationale for this is that it would enable validators to more effectively validate data.

We considered including codes in the schema as enum lists, but this has issues around flexibility of the codelists, which may need to be updated outside the schema upgrade cycle, and challenges around validating open codelists from enum lists.

**Comment by Bjwebb** [comment]
For comparison, here's how IATI describes the mappings between fields and codelists https://github.com/IATI/IATI-Codelists/blob/version-2.02/mapping.xml, which is similar except that it's separate to the schema (mostly I think because we weren't sure of the best way of including it).

Possibly of interest is how fields that can have codes with different vocabularies are described: https://github.com/IATI/IATI-Codelists/blob/version-2.02/mapping.xml#L232

**Comment by kindly** [comment]
We need to think about we do about the existing closed codelists that have enums?

My suggestion, for version 1.1, is to keep them as they are.  

In another version, once we have the codelist files fully supported, (with deprecation warnings, working well with extensions and completely supported within validator) we can think about removing them then.

I think it will take time develop this tooling around them properly and that may not be ready for this version.

We can also "if needed" in the short term have the validator use the closed codelists to populate the enums when it is extending then validating against the schema.

For this release we should have the open codelists being picked up by the validator and checked (like additional field checks) if a non specified codelist value is present.

In the very long term we should think about removing as many open codelists as possible in favour of explicit extensions for all codelists.

**Comment by kindly** [comment]
First draft of patches can be found https://github.com/open-contracting/ocds_upgrade_1_1_patches/tree/master/336_codelist

**Comment by timgdavies** [comment]
The patch (and other codelists required by other updates) has been added to my staged copy. 

We still need to:

* [ ] Decide what happens to enum lists in the schema?
* [ ] Add a test to ensure all codelists referenced in the schema exist
* [ ] Add support for checking against codelists to CoVE
