### ISSUE TITLE
Change definition of "tenderer" to enhance clarity

### ISSUE THREAD

**Issue by agm3dc** [open-contracting/standard#337]
OCDS defines "tenderer" as "All entities who submit a tender."

This could refer to the agency that submits a tender to which the public responds. It could also refer to the bidder that bids on the call for proposals or whatever the opportunity may be. 

I'd propose clarifying the definition of "tenderer" so that it refers to "All entities who submit a bid on a tender." This seems to be the true intent of the "tenderer" in light of the other categories available in OCDS.

**Comment by timgdavies** [comment]
This is a good suggestion, and does, in my view, capture the correct intent of the category. 

Flagging for the 1.1 upgrade. 

Also logging in case useful for any discussion that the EU use the category "economic operator" as a super-set category that I believe includes buyer, bidders, and parties who have not bid, but may have expressed an interest in doing so. We might need to keep the abstraction level they have needed to go to in mind when defining or refining entity categories.

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> The word "tender" is not being used consistently. Comparing the two lines above each other in the documentation: "Tenderers: All entities who submit a bid on a tender." ; "Number of tenderers: The number of entities who submit a tender.". 
> 
> While in EU parlance "tender" means "bid", I think that in OCDS "tender" means "call for competition", so the first description is correct, the second one should be updated.
