### ISSUE TITLE
Adding extra explanation to the validator

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#338]
Some users have reported confusion over what the OCDS validator is doing.

We need to look at improving the explanation of the validator to explain that:
- It is checking whether **the fields that have been provided** are **technically valid** and formatted correctly;
- It is checking for a few mandatory fields, required for technical re-use of the data; 
- It is **not checking completeness** of the data;

**Comment by timgdavies** [comment]
Suggested language from Lindsey: "If you give us more complete data, you will get more complete feedback."

**Comment by jpmckinney** [comment]
Tracked in CoVE planning documents instead.
