### ISSUE TITLE
Add download option to Google Docs data tables in documentation

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#340]
Via @dc-coder 

> The data tables in the documentation can not be downloaded. They are not user friendly when doing basic row count, sort or filter. I am assuming those are embeds. Here is a sample table.

![image](https://cloud.githubusercontent.com/assets/342624/15991574/703c1290-3084-11e6-808d-1a50d57ce2b4.png)

> It would be great if you can add filtering/sorting/row counts or just enable a simple file download.

**Comment by timgdavies** [comment]
Good suggestion. Links to #339 which should see a new tool for managing these IDs in the longer-run, but over the short-run we should be able to add links to CSV versions of these sheets. 

Until the next round of docs updates, you can [fetch the sheet shown above at this URL](https://docs.google.com/spreadsheets/d/1Am3gq0B77xN034-8hDjhb45wOuq-8qW6kGOdp40rN4M/pub?gid=506986894&single=true&output=csv)

**Comment by mireille-raad** [comment]
Hey! - this is marked as "ready" - will pushing the change need to wait till 1.1 is over?

**Comment by timgdavies** [comment]
Nope. I'm hoping we can cover this off in some documentation updates at end end of August outside of the 1.1 process. We'll be scheduling that in over the next week.

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
