### ISSUE TITLE
Suggestion: Add mapping and assessment templates to docs

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#341]
From @dc-coder at https://github.com/open-contracting/open-contracting.github.io/issues/8

> Add a link or a page for the latest version of the templates used for assessment, mapping, reports etc.

**Comment by timgdavies** [comment]
We are looking to add the resources to the Open Contracting website resource library, and provide links across from here.

**Comment by mireille-raad** [comment]
Hey!  - I noticed that his was not assigned to 1.1 - the level of effort needed is just providing a hyperlink to the spreadsheets. (they can be google doc or direct download)

Given how important it is to have public access to assessment and mapping guides - would you consider nudging that into 1.1?

**Comment by timgdavies** [comment]
I've created a new milestone for Documentation Updates ahead of the 1.1 so we can get this covered before.

**Comment by mireille-raad** [comment]
Excellent! I was wondering if the upgrade will touch on all issues or only on the ones that affect the data structure of fields in OCDS. I then saw that the 1.1 had documentation stuff in it... this is why i was slightly confused and thought to ask.

**Comment by timgdavies** [comment]
Well asked - do flag any other you spot not in milestones. I'll do another pass through all the issues next week for this too.

**Comment by mireille-raad** [comment]
Well, the 1.1 release is solving 97 out of total 128 issues! i don't wanna add much to your workload :)
The good thing about open-source/open-standard is that others can pitch in, so let me know if i can help with anything, even if it is documentation/boring stuff :)

**Comment by KrzysztofMadejski** [comment]
Is there any other spreadsheet than the Mapping Spreadsheet? It would be great to include the whole blog post from http://www.open-contracting.org/2016/07/26/localising-ocds-translations-terminology-extension into the documentation. 

I think it would fit perfctly at [Building Blocks](http://standard.open-contracting.org/latest/en/getting_started/building_blocks/) as this page is mentioned in _Getting Started_ as "Map your data against the OCDS building blocks"

**Comment by timgdavies** [comment]
Thanks @KrzysztofMadejski 

Will see what extra we can include in the docs. We've been trying to find the balance of what lives in the main documentation (and so gets versioned, translated etc.) - and whether we need some sort of knowledge base.

Any pointers to other standards that do this well would be really welcome.

**Comment by timgdavies** [comment]
Fixed in 1.0.2 release which is now live.
