### ISSUE TITLE
Overall contracting process description (discussion)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#342]
This issue is being considered for updates to core in the 1.1 release of OCDS.
## The issue

In #65, @jpmckinney pointed to the case of Montreal Gazette in which it would be useful to have an overall `description` field at the individual release level (e.g. parallel to `planning`, `tender` etc.)

> There is no top-level "description" field in which to put a general description of the process. In the Montreal Gazette contracts database, the source data is principally one field that mentions the supplier, the contract value, the deliverables, etc. as free-text.
## The proposal

`release.description` and `release.title` fields should be added to allow for a free-text title and overall description of a contracting process.
## Discussion points

My sense is that whilst this could be useful for some contexts:
- It many cases it would not be populated, so consuming applications could not rely upon it'
- It most cases, `description` information can be provided at the planning, tender, award and contract level, which should be sufficient.

However, I would welcome other views on whether having an overarching contracting process `description` (and I suspect, also `title`) would be useful?
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by jpmckinney** [comment]
The Gazette database isn't the only source that mixes multiple descriptions into one field. Without a top-level description, this information would have to be manually broken out into descriptions for each stage - and for no particular gain. I don't see how it not being populated is a concern - that can be said for any optional field in OCDS.

**Comment by timgdavies** [comment]
There is an extension at https://github.com/open-contracting/ocds_upgrade_342 for this (we're using it in the PPP profile of OCDS, hence creating this before we start on the 1.1 schema).

Given the PPP use case, I am supportive of the proposal - and will just make sure we write documentation carefully so consuming applications have good guidance on how to find a title to use when displaying information.

**Comment by timgdavies** [comment]
Comment from Aura Martínez during the peer-review process: (marked with 'Reject' change)

>"Is it really necessary? Information for the contracting process may be obtained from different processes made by different ministries (and each may give an specific title to their process). In that given situation (which is not uncommon) you will have one of the following:
> - The tender title and description will be repeated.
> - A new title will have to be created for each process at the moment of its publication.
> - One will have to change the title and description of the release according to it's tag. This would produce that the same release ID has different title's and descriptions over time, which will be confusing to the user."

Based on this feedback, our options are to:

* Emphasise this is an optional field, but should exist in the core OCDS standard (just not assigned as required at any 'Basic', 'Intermediate' or 'Advanced' level);
* Move this to being an extension only;

I'll be aiming to make a call on this soon - so views either way would be helpful.

**Comment by timgdavies** [comment]
This was moved to a core extension and covered in 1.1. No further action planned.

**Comment by jpmckinney** [comment]
The core extension is https://github.com/open-contracting/ocds_process_title_extension
