### ISSUE TITLE
Transaction labels - providerOrganization receiverOrganization

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#343]
From a recent working with the World Bank Open Contracting Team:

> The terminology for [transactions](http://standard.open-contracting.org/latest/en/schema/reference/#transaction) of providerOrganization (the payer) and receiverOrganization (the payee) are not very intuitive, and potentially cause confusion.

**Comment by duncandewhurst** [comment]
The issue is the current naming convention could be interpreted as relating to the goods or services procured rather than the flow of funds. Possible alternatives could be::
1. payerOrganization and payeeOrganization 
2. fundingOrganization and recipientOrganization

**Comment by AlCollier** [comment]
Hi Duncan I'd be wary of "funding organisation". Often the contracting
authority is the payer, but is being funded by some other authority
So "funding organisation" is ambiguous - are they paying the contractor or
the purchaser?

Regards

Al

**Comment by timgdavies** [comment]
I've been looking at:
- The [Fiscal Data Package](http://fiscal.dataprotocols.org/spec/#suggested-dimensions-for-different-types-of-spending-data)
- The [Payments Ontology](https://data.gov.uk/resources/payments#example1) 

for some inspiration around terminology.

From this, I think 'payer' and 'payee' do seem to be the most general.

I think we could drop the 'Organization' part of our term name in an update, so that the properties would just be:
- payer
- payee

Running through the thought experiments, it seems to me this should work for cases of:
- Payments from government to a supplier
- Payments from a supplier to government
- Concession payments made as part of a license

etc. 

Are there any situations in which there would be a **transaction**, but the idea of representing this as a **payment** would be problematic?

**Comment by duncandewhurst** [comment]
Continued in #372
