### ISSUE TITLE
OCDS Version Number in OCDS Releases

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#344]
As a data analyst, the version number in the OCDS release would confirm which version of the schema the release was compiled against. It would allow me to distinguish between a release at a lower version from errors in a release at a higher version.

**Comment by Bjwebb** [comment]
Is this the same issue as https://github.com/open-contracting/standard/issues/301 ?

**Comment by timgdavies** [comment]
Yep - duplicate of #301
