### ISSUE TITLE
Review links with Budget Data Package / Fiscal Data Package

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#345]
In the current version of OCDS we have a very simple budget block, and which talks of linking out to the 'Budget Data Package' for more in-depth information.

However, Budget Data Package has been superseded by the [Fiscal Data Package](https://github.com/openspending/fiscal-data-package) which [does not currently have the concept of a transaction identifier](https://github.com/openspending/fiscal-data-package/issues/131), and where current publication approaches do not focus on providing data at a stable URI. 

This makes cross-linking between OCDS and FDP challenging - and raises the question of whether we should:

(a) Remove the cross-reference to Budget Data Package / Fiscal Data Package from 1.1
(b) Improve the internal modelling of budget data in OCDS;

Alternatively, we should improve the documentation to more concretely show how FDP links can be made.

I am not aware of any existing use of links out to budget source data in published OCDS datasets. 
## Related issues:
#44 discussing links to Budget Data Package during the development phase
#91, #293 and #292 on more sophisticated modelling of budgets.

**Comment by timgdavies** [comment]
If we do stick with Budget Data Package, we need to update links in the schema, as https://github.com/openspending/fiscal-data-package/blob/master/specification.md no longer exists.

**Comment by Bjwebb** [comment]
Previous issue about that link - https://github.com/open-contracting/standard/issues/271

**Comment by timgdavies** [comment]
Developed into proposal in #378
