### ISSUE TITLE
OCDS 1.1 Upgrade - Proposal cut-off date - 6th July

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#346]
Version 1.0 of the Open Contracting Data Standard (OCDS) was launched in November 2014. Over the last 18 months countries, cities and civil society groups across the world have worked on adopting OCDS, and as a community we've been learning even more about the kinds of structured disclosures of information that can increase understanding and engagement around the whole contracting process. 

OCDS is an open standard, which means it is open to periodic update and revision through an open governance process. The [governance document here](http://standard.open-contracting.org/latest/en/support/governance/) (and summarised in the image below) describes the process to be used for the upgrade from version 1.0 to 1.1. 

We manage the upgrade process through a [GitHub issue tracker](https://github.com/open-contracting/standard/issues). This works similar to a forum where there are discussion threads for particular topics. It is free to create a GitHub account and participate, and you can then subscribe to 'Watch' for new issues, and can respond to issues via e-mail. 
## **Next step: proposal cut-off - 6th July**

To start the 1.1 process, as of today 17th June we are announcing an upcoming cut-off date for new proposals of 6th July. This means that **if you want to guarantee that a substantive issue is addressed in this upgrade process, you should create an issue for it before that date**.

After 6th July we will produce a prioritised list of topics for the 1.1 upgrade, and will share this for a period of community review. 
## **Existing issues**

You can check if your issue is already being addressed by [searching the issue list](https://github.com/open-contracting/standard/issues?utf8=%E2%9C%93&q=is%3Aissue).

Over the last few weeks we have reviewed over 100 existing issues, to identify key themes emerging. 

If you think an issue is particularly important, or you have insights to add, please do add a comment to the relevant discussion thread. You can also use the reactions button in GitHub to add your support to a proposal (+1), or to reject an idea (-1). 

During prioritisation, community engagement with an issue will be a key factor in deciding whether it should be considered during 1.1
### **Summary by stage**

We have organised issues in this [Huboard](http://huboard.com/open-contracting/standard) which provides a visual presentation of whether issues are:
- In the **backlog**: there is not yet a clear course of action to progress this issue;
- In **discussion**: these are issues that would benefit from wider contributions from the community to identify a way forward;
- Being developed as clear **proposals** which can be considered for inclusion in the upgrade;
- **Ready** for changes to be made to the schema - either where they are a bug-fix, or where there appears to be consensus around a proposal;
- **In development** where the schema or document updated are actively happening at the moment;
- **In review** where schema or document updates are currently being tested;
### **Thematic summary**

We have clustered those issues we have currently in the tracker with a clear thematic focus as below. Each line links to associated GitHub issues where the current problems and proposals can be discussed. These clusters will be reviewed at the prioritisation stage after 1st July. 
- Taxes
  - Capturing structured information on taxes in values [112](http://github.com/open-contracting/standard/issues/112)
- Organisation and contact details
  - Representing consortiums or multiple suppliers for a single award [142](http://github.com/open-contracting/standard/issues/142)
  - Representing government parties other than buyer and procuringEntity [150](http://github.com/open-contracting/standard/issues/150) [156](http://github.com/open-contracting/standard/issues/156) [264](http://github.com/open-contracting/standard/issues/264) [275](http://github.com/open-contracting/standard/issues/275)
  - Allowing multiple contact points (additionalContactPoint vs. contactPoint as an array)  [266](http://github.com/open-contracting/standard/issues/266)
  - Adding country code to address  [270](http://github.com/open-contracting/standard/issues/270)
  - Classifying organisations (e.g. size, type etc.) [269](http://github.com/open-contracting/standard/issues/269) [181](http://github.com/open-contracting/standard/issues/181)
- Planning and projects
  - Relating multiple tenders to a single planning process [72](http://github.com/open-contracting/standard/issues/72)
  - Relating contracting processes to external project identifiers [130](http://github.com/open-contracting/standard/issues/130)
- Budgets 
  - Capturing multi-year budgets and contracts [222](http://github.com/open-contracting/standard/issues/222) [293](http://github.com/open-contracting/standard/issues/293)
- Procurement Type
  - Introduce a classification of procurement type [204](http://github.com/open-contracting/standard/issues/204)
- Lots
  - Handling contracts divided into lots [236](http://github.com/open-contracting/standard/issues/236)
- Units
  - Improving the classification of units of measure [145](http://github.com/open-contracting/standard/issues/145) [177](http://github.com/open-contracting/standard/issues/177)
  - Handling exchange rates in values [270](http://github.com/open-contracting/standard/issues/270)
- Information on bids and assessment 
  - Capture information on the number of bidders, including disqualified bidders and eligible/non-eligible bidders  [141](http://github.com/open-contracting/standard/issues/141)
  - Capture details on each bidder  [197](http://github.com/open-contracting/standard/issues/197)
  - Provide structured tender criteria, and collect structured information from bidders (using 'Features' extension) [223](http://github.com/open-contracting/standard/issues/223) [36](http://github.com/open-contracting/standard/issues/36) [140](http://github.com/open-contracting/standard/issues/140)
- Framework contracts
  - Handling frameworks with a mini-competition stage [233](http://github.com/open-contracting/standard/issues/233)
- Assessment and review information
  - Capture complaint information  [38](http://github.com/open-contracting/standard/issues/38) [205](http://github.com/open-contracting/standard/issues/205)
- Subcontracting 
  - Capturing sub-contracting information and contracting process relationships [144](http://github.com/open-contracting/standard/issues/144)
- Contract extension and renewal
  - Capturing contract maximum extension and review dates [179](http://github.com/open-contracting/standard/issues/179) [200](http://github.com/open-contracting/standard/issues/200)
  - Linking contracts nearing expiry with the process for procuring their replacements [184](http://github.com/open-contracting/standard/issues/184)
- Linked data
  - Developing an ontology and JSON-LD rendering of OCDS [190](http://github.com/open-contracting/standard/issues/190) [40](http://github.com/open-contracting/standard/issues/40)
- Language and definitions 
  - Clarify definition of tenderer  [337](http://github.com/open-contracting/standard/issues/337)
## **Looking ahead: process overview & timeline**

The [governance document here](http://standard.open-contracting.org/latest/en/support/governance/) sets out the minimum time periods for key stages of the upgrade process. At present, we anticipate:
- Proposals closed - 6th July 2016
- Prioritisation - by 22nd July 2016
- Review of priorities - by 5th August 2016
- Development of worked up proposals - by 30th September 2016
- Peer-review stage - October/November 2016
- Final revisions and review - December 2016

With delivery of the 1.1 version of OCDS by the end of 2016. 

No plans have yet been made for the 1.2 upgrade process, and any such process would respond to community demand, but would be very unlikely to take place earlier than Q3 2017. 

![image_0](https://cloud.githubusercontent.com/assets/342624/16154734/13223c46-34a4-11e6-89dc-9e09e72c26c6.png)

**Comment by mireille-raad** [comment]
Will there be an "upgrade guide" ? or any upgrade tool?
An upgrade tool can work like the validator: you give it an OCDS formatted json and it checks if there are fields in your data that you need to change or add to.
The goal would be to make the upgrade process more smooth and remove the steps of having to read tedious documentation. This will be useful since not everybody publishes all the fields.

**Comment by timgdavies** [comment]
@dc-coder This is definitely something we could consider developing.

**Comment by timgdavies** [comment]
We are now starting on prioritisation of issues. Over the next two weeks we'll be working to synthesise a proposed priority list to take forward in the upgrade process. This will then be fed back for comment.

**Comment by timgdavies** [comment]
I've broken out the upgrade guide issue in #363. Closing this issue as we'll have future progress updates in their own issues.
