### ISSUE TITLE
documentType codelist descriptions and examples

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#347]
The documentType codelist is currently missing descriptions for a number of documents. 

In 1.1 these descriptions should be provided.

We should also consider creating a supporting resource with examples of documents, or more information about the features that these documents might contain.

**Comment by ekoner** [comment]
Tracking suggestions here: https://docs.google.com/spreadsheets/d/1oLGD25LpOJMg5KG8Lh_BnvMgTZx2eRU6jBjvUjvKitg/edit?usp=sharing

**Comment by duncandewhurst** [comment]
Feedback from the codelists breakout session at IODC:

| Document type | Definition | Comments |
| --- | --- | --- |
| Procurement Plan |  | Add "works" to "goods, works and services" |
| Environmental Impact | Analysis of the negative effects of the project on the environment |  |
| Needs Assessment | Analysis of the demand for the project or investment by the affected communities or users |  |
| Feasibility Study | Study of the net benefits that the project will bring |  |
| Conflicts of Interest Uncovered | Declarations, or identification of, external interests beside the primary or mandated task |  |

**Comment by timgdavies** [comment]
The [spreadsheet here](https://docs.google.com/spreadsheets/d/1oLGD25LpOJMg5KG8Lh_BnvMgTZx2eRU6jBjvUjvKitg/edit#gid=662145505) has been updated with a revised list of definitions, drawing on the input above, and the approach to 'documentation' taken in the PPP extension.

It looks like getting examples together will be beyond the scope of 1.1, so suggest that is a post 1.1 issue.

**Comment by ekoner** [comment]
Reviewed: Now ready for peer review.
