### ISSUE TITLE
Making documentType an array

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#348]
At present the [documentType](http://standard.open-contracting.org/latest/en/schema/reference/#document) property is a string, with an [open codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#document-type). 

This means a single documentType can be given for each referenced document.

In looking at PPP use-cases, we are finding one single document may contain the information that might fall under the definition of more than one documentType.

**For example**, a single PDF might contain both `technicalSpecifications` and `evaluationCriteria`.

In the current model, either a single tag has to be chosen, so the document would need to be linked to multiple times with different tags to clearly show that both technical specifications and evaluation criteria documentation has been provided. 

We should consider making `documentType` into an array.

**Comment by Bjwebb** [comment]
The most obvious way of making change, switching from string to array is not backwards compatible.

**Comment by timgdavies** [comment]
We will not be pursuing this in the 1.1 upgrade.
