### ISSUE TITLE
Tenders as array for PQQ processes?

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#349]
Based on reflections from reading [PPP Disclosure Framework](http://www.worldbank.org/en/topic/publicprivatepartnerships/brief/a-framework-for-disclosure-in-public-private-partnership-projects) and looking at EU forms:

A procurement process may involve a Pre-Qualification stage in which parties are invited to participate in a qualification process, submitting documents by a particular date, and being evaluated. This is followed by an invitation to tender stage, to which the qualified bidders are invited. 

This feels like it should perhaps be modelled as two separate 'tender' processes within the same contracting process. However, this would break our description of a contracting process as that which involves a unique tender stage. 

It would also be a breaking change (so tricky for 1.1). 

What other modelling options are there for this scenario? Is it significant enough to warrant changes to the standard?

**Comment by AlCollier** [comment]
Hi Tim worth bearing in mind that there may be n stages, not just two. Open
procedure may involve the two stages you describe being compressed into one
exercise - with similar questions to those typically asked in a PQQ being
used to eliminate some candidates before the rest of the tender is
evaluated. Conversely a competitive dialogue in the EU involves a PQQ, then
may have multiple independent rounds of tendering with some tenderers being
eliminated in each round.

Simpler to model all such exercises as a single 'tendering process'?

**Comment by timgdavies** [comment]
We are not considering any changes here for 1.1

During work on a PPP extension we will look at modelling options for complex multi-stage procurement processes.

**Comment by akuckartz** [comment]
Can you assign such issues to Github milestones instead of closing them ?

**Comment by timgdavies** [comment]
Unless any requirement for this comes up through our further work on PPP extension, I've been the only person suggesting changes here, so not sure what the justification for keeping this open would be.
