### ISSUE TITLE
Bidder eligibility criteria

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#35]
Requirement generated from [User Research process](https://docs.google.com/spreadsheets/d/1m_Kr7I5XqM7PFcz75ZNmcdFCzLaike_IsEmAh5eN-WE/edit#gid=2035729003): R17

There is user demand for fields which would indicate the eligibility criteria in order to be able to bid for a tender.

This requirement was articulated in the context of anti-corruption use-cases, where those involved with contract scrutiny are interested in understanding the complexity of tender requirements as a means of assessing whether particular barriers to bidding are being put in place. 

They suggest analysis may look at *"Length of eligibility criteria: character length of text defining which bidders are eligible to bid;"*.

As yet, requirements from firms for structured data on this have not been identified.

**Comment by timgdavies** [comment]
Version 1.0 of the standard has an `eligibilityCriteria` field which is a free text field for describing the eligibility of bidders. This meets the original use-case from the standard for checking the length of eligibility criteria descriptions.

I've been looking through issues, and thinking over cases we've encountered, to find any other requirements for **structured** eligibility criteria date. 

The only two things I can think of are:

(1) Cases where only bidders on a given **framework** are eligible to bid;

(2) Cases where only national firms are eligible to bid (I seem to recall an issue on this from procurement analytics, but can't find this right now)

I suspect these are best handled as their own issues, so propose creating new issues for frameworks, and national-only eligibility issues, and closing this one.

**Comment by timgdavies** [comment]
Frameworks handling is addressed in #310. 

The proposed features extension in #223 will also allow criteria of bidders, such as 'national bidder only' to be captured in a structured form.
