### ISSUE TITLE
Including estimated contract dates/duration in tender block.

### ISSUE THREAD

**Issue by SimKennedy** [open-contracting/standard#350]
Apologies for the late submission.

I've noticed many tenders include contract start/end dates and/or duration which doesn't seem to have a place in the schema yet but is quite important information when available.

[Due North](https://procontract.due-north.com/Advert?advertId=d1f64f22-1537-e611-8114-000c29c9ba21&p=2241eb95-058a-e511-80f7-000c29c9ba21)

[Contracts Finder](https://www.contractsfinder.service.gov.uk/Notice/4821c192-1329-4a47-829c-43c22db0cfcb)

[TED](http://www.ted.europa.eu/udl?uri=TED:NOTICE:230643-2016:TEXT:EN:HTML&src=0) has section "II.3) Duration of the contract or time limit for completion" in the Contract Notice.

Simply adding these fields alongside the "tenderPeriod" and "awardPeriod" fields seems logical and clear.

> tender/estimatedContractPeriod/startDate
> tender/estimatedContractPeriod/endDate
> tender/estimatedContractDuration

Alternative solutions could be:
- Allow a prospective award and contract to be included with anticipated values.
  - Has benefit of allowing any fields available in these blocks to be populated with estimated values.
  - Could be misleading to believe the award/contract phase has been entered.
- Include a "contract" object in the tender block, perhaps under "predictedContract" or something
  - Also has benefit of populating any other expected contract details if desired.
  - Benefit of automatically including any changes to the contract block that may happen
  - Con perhaps that the tender block can become bloated with information not strictly relevant?

**Comment by timgdavies** [comment]
This is definitely needed in a number of cases, and I think would best belong in tender.

I would lean towards using simple `tender/contractPeriod` as the value, with either:
- An explanation that this should be interpreted as the estimated date, as it appears in the tender;

or
- Extending `period` to include some sort of `status` field with a codelist, such that you could have:

```
"contractPeriod": {
     "startDate":"2016-01-01T00:00:00Z",
     "endDate":"2016-10-01T00:00:00Z",
     "status":"estimated"
}
```

**Comment by timgdavies** [comment]
This is taken forward in #374
