### ISSUE TITLE
Provide full list of fields in documentation to support mapping

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#351]
I currently have [a script here](https://github.com/timgdavies/OCDS-mapping-sheet) which I use to generate a simple CSV file with a row for each possible field in OCDS, and columns for:
- jsonpath 
- title 
- description
- type
- instances
- validation
- further documentation

This is useful when constructing mappings between OCDS and other data structures, and is something we should provide as part of the documentation.

I believe flatten-tool now has features that head in this direction, which might be possible to adapt for this purpose.

**Comment by Bjwebb** [comment]
I think this issue can be closed in favour of https://github.com/open-contracting/mapping-sheet-generator/issues/6
