### ISSUE TITLE
Create field for congressional or legislative district

### ISSUE THREAD

**Issue by agm3dc** [open-contracting/standard#353]
There appears to be no clear field that could pertain to congressional or legislative district. Such a field could be included in: award.suppliers.address; buyer.address; tender.tenderers.address; tender.procuringEntity.address

**Comment by timgdavies** [comment]
Is the intention of this:
- The district of where the goods or services are to be supplied?
- The district where the suppliers are located?
- The district of the funding entity?

Can you give some examples of how this would be used, or cases where there is demand for it?

**Comment by agm3dc** [comment]
I've just been informed that there's a likely project location extension upcoming. I would move for the congressional district field to be included under that project location.

The most clear-cut use case would be determining geographic beneficiaries of government procurement. Imagine a map that shows wealthy congressional districts in the US receiving far higher procurement dollars than the poor districts next door. 

I could also see an interest in having a congressional field for award.suppliers.address. But it wouldn't be as strong an argument as a congressional location extension for project.

Thx

**Comment by timgdavies** [comment]
Yes - the [location extension (new format) can be found here](https://github.com/Bjwebb/proposed_location_extension) 

This includes a `deliveryLocation` at the `item` level which can have a gazetteer based classification of locations (e.g. treating list of congressional districts as a gazetteer) which would be appropriate for this.

The same location object could also be attached to suppliers - although I would assume in most cases the supplier district could be worked out by geocoding their address, so it might not be necessary to explicitly include this in the data (at least, in so far as the core standard is concerned - local implementation would be free to do this).

**Comment by timgdavies** [comment]
@agm3dc Hoping the location extension covers what you need. 

Closing this issue for now - but do re-open if you've not found you can do what you need with location extension.
