### ISSUE TITLE
Translation workflow

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#354]
At the moment we have a Spanish translation of OCDS, and a draft French translation.

We do not have a formal sign-off process for translations.

Is such a process necessary? What would it look like if so?

**Comment by jpmckinney** [comment]
Is this still unresolved?

**Comment by timgdavies** [comment]
This is still an active issue. We are planning some dialogues on translation later in the year which this could be addressed through.

**Comment by jpmckinney** [comment]
This issue has since been pursued in many places in many ways, so closing here. That other work will eventually get reflected in documentation.
