### ISSUE TITLE
Add a field tender/Bidprice

### ISSUE THREAD

**Issue by agm3dc** [open-contracting/standard#356]
I didn't see a ticket related to the lack of a field for bid prices. In regards to collusion detection, it's important to compare winning and losing bid prices. Additionally, it's expected that award/value/amount is negotiated and does not reflect the price of the winning bid. Incorporating a tender/Bidprice field is a high priority.

**Comment by timgdavies** [comment]
There is a proposal within #197 for having a value for each bid in the bid extension / new building block, but it is useful to have this ticket to make this an explicit issue and make sure it does not get missed. 

You can see an example of what we had been thinking about a `tender/bids` [array here](https://github.com/open-contracting/standard/issues/197#issuecomment-163581629).

**Comment by timgdavies** [comment]
Addressed in #379 for the upgrade.
