### ISSUE TITLE
Transaction amount vs value

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#359]
In the [transaction block](http://standard.open-contracting.org/latest/en/schema/reference/#transaction) we have transaction.amount 

Everywhere else in the standard we use `value` as the keyword for monetary amounts (pointing to the amount object which contains currency and amount). 

This appears to be an error, because even [IATI transactions](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/transaction/) on which this is modelled use `value`.

We should review usage of this property (c.f. #70) and consider whether we can afford to deprecate `amount` and switch to `value` for consistency in 1.1, or if this would need to wait until 2.0.

**Comment by timgdavies** [comment]
Flagging for consideration in 1.1 - not to guarantee it can be done as part of this process.

**Comment by duncandewhurst** [comment]
Continued in #372
