### ISSUE TITLE
Tender evaluation criteria - including price and non-price breakdown

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#36]
Requirement generated from [User Research process](https://docs.google.com/a/webfoundation.org/spreadsheets/d/1m_Kr7I5XqM7PFcz75ZNmcdFCzLaike_IsEmAh5eN-WE/edit#gid=2035729003): R20, R21 and R22.

User needs identified a demand for detail on the evaluation criteria of a tender, including:

* Evaluation criteria broken down between price and non price
* The weight given to different evaluation criteria

This is based on an anti-corruption use-case, where high weight given to certain kinds of evaluation criteria can indicate issues in need of further investigation.

R22 also asks for Scores from All Bidders - such that when bidder details are published it would be possible to know how they scored on assessments against bidding criteria.

**Comment by timgdavies** [comment]
This may be possible to handle with the proposed 'Features' extension from #223

**Comment by LindseyAM** [comment]
I think there was a related comment from myroslav in a different thread #254

**Comment by timgdavies** [comment]
This will be taken forward via features extension in #223
