### ISSUE TITLE
OCDS organisations have a complex id nested a level down

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/standard#361]
Instead of `id` they have `identifier/scheme` and `identifier/id`.

This causes problems for serialisations besides JSON, like spreadsheet. In particular organisation support is currently broken in flatten-tool https://github.com/OpenDataServices/flatten-tool/issues/103

**Comment by Bjwebb** [comment]
Note that for the spreadsheet serialization an ID is only needed for the parent object where an array is split out to a different sheet. This means the spreadsheet representation currently only has trouble with arrays within organization - ie. currently just the additionalIdentifiers array.

**Comment by timgdavies** [comment]
Addressed in the proposed updates to organisations - #368
