### ISSUE TITLE
Provide upgrade guide & tooling 

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#363]
Based on comment from @dc-coder in #346 

We should make sure the 1.1 upgrade is accompanied by:
- An upgrade guide - listing any changes that publishers will need to make to their data to be compliant with the updated schema;
- Upgrade tooling - to convert 1.0 data to 1.1 where properties have been deprecated etc.

**Comment by jpmckinney** [comment]
What's the progress on this?

**Comment by jpmckinney** [comment]
I'm unaware of an upgrade guide and the only upgrade tooling I'm aware of are scripts in `sample-data`.

**Comment by jpmckinney** [comment]
Closing as we've seen no demand for 1.0 to 1.1 support. We will work on upgrade support for 1.1 to X.X.
