### ISSUE TITLE
How should applications consuming OCDS data order documents?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#365]
@myroslav - further to our conversation on document ordering:

Currently the standard does not provide any guidance on how applications consuming OCDS data should order documents.

There are 3 properties of _document_ which are likely candidates for ordering:
- _id_
- _datePublished_
- _dateModified_

These properties could also be combined, e.g. order by **day** (rather than full date-time) of _datePublished_ then order by _id_

Should the standard provide a recommendation for how consuming applications should order documents and what should this be?

**Comment by myroslav** [comment]
In ProZorro, `Document.id` is auto-generated UUID, thus ordering by UUID is not proper option. We are versioning Documents by reusing the same `id`, and sequencing by `dateModified`, latest version is newest and considered actual.

`datePublished` is the same in all versions of a document, and is the date Document was registered in a system (i.e. published). Thus there is no way to change `Document.datePublished`.

`dateModified` is changed with each new version of Document being uploaded. This can potentially be used for ordering, but uploading same image once more just to make it jump to first position would make system use very "unpredictable" and "complex".

One of the options we'd discussed in a call was to add `index` (or `weight`, or `priority`) property, and have Documents to be ordered by index, items sharing the same index can be ordered by `datePublished` (natural upload order, that is also reflected into sequence of Document objects in array). This way in the case of omitting `index` altogether, the upload sequence will be preserved, and in the case many items will share the same index, they'll have same predictable upload order. The only question is how to treat objects with no index, is that 0, or is that infinity (to have all Documents without explicit index to be in the end of the list, not mixing with ones that took an effort to have the extra property).

**Comment by timgdavies** [comment]
Thanks @myroslav. 

This sounds like a good candidate for a simple extension.

[Schema.org](https://schema.org/ItemList) uses `position` as the property name for ordering elements in a list. 

I prefer this to `priority` and `index` (which could have multiple meanings), and I think it it more intuitive than `weight`.  

I would suggest no index value should be treated as infinity, with the option of publishers explicitly declaring items as 0 to get them at the top of the list.

Would the following rules work:
- Elements in an array may contain a `position` field with a numerical value;
- Elements in an array with a priority value should be displayed **above** elements that either omit the `position` value, or have it set to null. 
- Elements in the array should be sorted by their `position` value in ascending order (priority 0 at the top of the list, priority 1 below etc.) 
- If two elements have the same `position` value, then the following properties can be used to order them: `publishedDate` (Ascending), `modifiedDate` (Ascending)

This extension could be applied to milestones as well as documents, and possibly also allowed as an option for other areas in the standard.

**Comment by mireille-raad** [comment]
hmm... could we add page number to the equation? I believe OCDS 1.1 enables linking page numbers in documents with specific information. When creating a UI, it might be useful to show specific page of a document.. which means, we'd have to order that doc on a specific page. I am also wondering if wget or curl or other programming utilities now enable ordering only part of a document.... that would save a lot of bandwidth.
So, do you think page number or section number of a document is relevant to this discussion? or too far fetched as a use case?

**Comment by jpmckinney** [comment]
There are two conversations here: one about standard guidance on what order to present documents in, and another conversation about how to encode order (with a `position` field).

I don't think there is a single answer to the first question, as it depends on the consuming application's use cases. Some would prefer reverse chronological order. Some would prefer grouping by type. In general, however, I consider it over-reaching to standardize how consuming applications present standardized data.

For the second question, JSON arrays preserve order, as-is. However, the merging rules (at least as implemented in ocds-merge) don't preserve the order of the latest release (e.g. if a new release were publish with all documents in the preferred order, the compiled release wouldn't have that order). This is perhaps a special case to consider for ocds-merge.

The alternative of using a field is not without challenges; for example, if an item were inserted at the start of the list, the implementation would have to re-number all other items. In general, I'm not in favor of encoding presentation-level information in OCDS (i.e. I don't know any jurisdiction for which the order of documents is significant). We don't, e.g., specify number formatting.

Closing for reasons above.
