### ISSUE TITLE
Organisation details and classifications

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#369]
## Organisation details

This is under consideration for the 1.1 upgrade of OCDS. It builds on #368 on wider updates to organisation handling. 
## The issue

Publishers want to categorise organizations according to a range of nationally and globally defined schemes, and to flag whether an organization meets certain policy criteria, such as:
- SME
- Voluntary Sector
- Foreign owned

The EU, for example, classify the main activity of procuring entities according to COFOG codes. 
## The proposal

We will introduce a standard extension that provides a `details` object attached to the `organization` building block.

The page for this extension will list community extensions tagged with the `organizationDetail` tag in the extensions registry (see [https://github.com/open-contracting/extension_registry](https://github.com/open-contracting/extension_registry)) 

We will provide a demonstation extension for a flag to indicate whether or not a firm is an SME. 
### Worked example

This proposal, alongside the proposed changes or organization handling, would result in additional information in the top-level `entities` array such that a block describing two tendering firms - one that is an SME, and one that is not would contain:

``` json

"entities":[
{
               "id":"GB-COH-987654321",
               "roles": ["tenderer"],
               "identifier": {
                   "scheme": "GB-COH",
                   "id": "987654321",
                   "legalName": "MiniCorp Ltd",
                   "uri": "http://www.minicorp.example"
               },
               "name": "Mini Corporation",
               "details": {
                  "isSME":true
               }
           },
           {
                "id":"GB-COH-12345678",
                "roles": ["tenderer"],
                "identifier": {
                    "scheme": "GB-COH",
                    "id": "123456678",
                    "legalName": "MegaCorp Plc",
                    "uri": "http://www.megacorp.example/"
                },
                "name": "Mega Corporation Global",
                "details": {
                  "isSME":false
               }
          }
]
```
### Questions

What organisation classifications do you need?
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
The resolution to this issue should be reviewed againast #260 #181 #269 and #262 - and if relevant, draft extensions for each of these created.

**Comment by duncandewhurst** [comment]
The World Bank's [Public Procurement Indicators](http://www.eprocurementtoolkit.org/sites/default/files/2016-10/Public%20Procurement%20Indicators-Rapid_e-Procurement_Toolkit.pdf) for monitoring e-GP adoption and performance includes indicators based on the type of supplier (SME, large and foreign owned). The proposed extension would address these reporting requirements.

**Comment by siwhitehouse** [comment]
The EU has the following:

Is a central purchasing body
Type of buyer (COFOG code)
Main general activity (COFOG code)
Main sectoral activity (COFOG code)
Is an SME 

So, from what has already been discussed, I think that only leaves "Is a central purchasing body" as a possible addition.

**Comment by andrewlorien** [comment]
In Australia, NSW eTendering and AusTender have reporting rules (which may change from government to government) about types of suppliers - indigenous ownership and SME status are two important ones.

**Comment by JachymHercher** [comment]
Small correction @siwhitehouse - "Type of buyer" and "Main sectoral activity" do not correspond to the COFOG (functions of government) code, only the main general activity does. (The "type of buyer" classification is procurement form-specfic, the "Main sectoral activity" corresponds to the articles in the sectoral procurement directive.)

**Comment by siwhitehouse** [comment]
What we have done in the extensions for trade work is to use the [Ted Schema](http://formex.publications.europa.eu/ted/schema/). Tim built a more user friendly version and I used that to map what is in the forms to the schema.

Main Sectoral Activity provides a complete match, whereas for Type of Buyer there are quite a few values in the forms that I could not find in the schema. Where this is the case we have constructed a code from the description using the format of uppercase characters with words separated by an underscore.

The codelist files have a source value and so in there we have identified whether the value is from the Ted Schema or is one we have made up.

I've attached the codelist files so you can see what I have described and review for any errors if you choose. I've had to resave as txt from the original csv for them to be uploaded here.

Thanks for picking this up.

[typeOfBuyer.txt](https://github.com/open-contracting/standard/files/917814/typeOfBuyer.txt)
[mainSectoralActivity.txt](https://github.com/open-contracting/standard/files/917815/mainSectoralActivity.txt)

**Comment by JachymHercher** [comment]
Makes sense - since you are comparing a TED 2.0.9 schema (i.e. the current one, the one which corresponds to the forms on the right side of http://simap.ted.europa.eu/web/simap/standard-forms-for-public-procurement) with a eForms, a draft proposal, the new elements from eForms are not included.

I've had a quick look at the codelist. In typeOfBuyer, "other" and "internationalOrganisation" should already exist in the 2.0.9 schema, because they exist in the previous forms. Otherwise it seems ok.

**Comment by siwhitehouse** [comment]
Hi Jachym

Using [Tim's user friendly version](https://timgdavies.github.io/ocds-ted/docs/) I see the following under the ca_type attribute.

> <xs:attribute form="unqualified" name="VALUE" use="required">
>   <xs:simpleType>
>     <xs:restriction base="xs:string">
>       <xs:enumeration value="BODY_PUBLIC"/>
>       <xs:enumeration value="EU_INSTITUTION"/>
>       <xs:enumeration value="MINISTRY"/>
>       <xs:enumeration value="NATIONAL_AGENCY"/>
>       <xs:enumeration value="REGIONAL_AGENCY"/>
>       <xs:enumeration value="REGIONAL_AUTHORITY"/>
>     </xs:restriction>
>   </xs:simpleType>
> </xs:attribute> 

which gives some matches for typeOfBuyer, but not anything for "other" or "internationalOrganisation". I've tried looking across the whole file and can't find matches either.

I'm wondering if they aren't there or if I am making a simple error somewhere.

**Comment by JachymHercher** [comment]
With international organisations this is actually a bit complicated, because the XML is not quite in line with what you would expect from looking at the forms. Nominally, you would think the EU_institution code corresponds to "European institution/agency or international organisation". In reality, the "EU_institution" code corresponds only to "International organisations" concept, while the EU institution concept is encoded in a rather complicated way in the header of the notice. I'm not sure in what detail you want to go here...

Concerning "Other", apparently you can either use the codelist mentioned above, _or_ signal "Other" by giving a string as a name of the other. That's this part of the XSD:

```
-<xs:group name="authority">
-<xs:sequence>
-<xs:choice>
<xs:element name="CA_TYPE" type="ca_type"/>
<xs:element name="CA_TYPE_OTHER" type="string_200"/>
</xs:choice>
```

**Comment by jpmckinney** [comment]
By my understanding, this was resolved by adding `parties/details` (which doesn't provide fields for all the linked issues, instead allowing future extensions to provide those fields). A best practice is to describe why an issue is being closed when closing an issue.
