### ISSUE TITLE
Award: Consortium suppliers

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#370]
## Corsortium suppliers

This is under consideration for the 1.1 upgrade of OCDS. It builds on changes to organisation handling proposed in #368 
## The issue

Suppliers may be consortia. 

In some countries, a consortium is a legally registered organization. In others, they are simply a collection of firms.

In some countries, the Special Purpose Vehicle (SPV) for a consortium is only created after the contract is signed. 

Users may want to know who the consortium members are and their share in the consortium. 

Note: The model we adopt for this may also be possible to adapt to presenting shareholder and beneficial ownership information within the standard. 
## The proposal

Adding `consortium` and `consortiumMember` to the new organization role codelist (see Slide 17).

Introducing an extension to the organization building block to provide an `ownership` field with an array of objects containingN:
- id - an identifier for this record of shareholding
- shareholder
  - id and name of shareholder in the consortium;
- share - share held
- period - the period this shareholding applied for

The exact details of this extension should be developed over the coming months  through wider consultation, with particular reference to the Global Beneficial Ownership Register work. 
### Worked example

A consortium (The Consortium) made up of three shareholders, (Mr A, AnyCorp and Any State) is awarded a contract. The abbreviated example below shows how this coulde be modelled with the consortium, and each of the parties to the consortium, listed in the `entities` array. 

The share that each consortium member holds, and the period of that holding, is given in the `ownership` array of the consortium. 

``` json
{"releases":[{
       "ocid": "ocds-213czf-1.1-upgrade",
       "id": "ocds-213czf-1.1-upgrade-consortium",
       "tag":["award"],
       "entities": [
          {
                     "id":"XI-GUID-569949c5-2df4-4d9f-81ce-bb34dc134f7e",
                     "roles": ["tenderer","supplier","consortium"],
                     "identifier": {
                         "scheme": "XI-GUID",
                         "id": "569949c5-2df4-4d9f-81ce-bb34dc134f7e",
                         "legalName": "The Consortium",
                     },
                     "name": "The Consoritum",
                     "ownership":[
                        {
                            "id":"1",
                            "shareholder":{
                              "id":"XI-GUID-61a491d2-fc8b-4a91-b6bc-7bede34e466d",
                              "name":"Mr A"
                            },
                            "share":0.1,
                            "period": {
                              "startDate":"2016-01-01T00:00:00Z"
                            }
                        },
                        {
                            "id":"2",
                            "shareholder":{
                              "id":"GB-COH-12345567",
                              "name":"AnyCorp"
                            },
                            "share":0.51,
                            "period": {
                              "startDate":"2016-01-01T00:00:00Z"
                            }
                        },
                        {
                            "id":"3",
                            "shareholder":{
                              "id":"XR-NUTS-UK",
                              "name":"Any State"
                            },
                            "share":0.39,
                            "period": {
                              "startDate":"2016-01-01T00:00:00Z"
                            }
                        },
                     ]
                 },
                 {
                      "id":"XI-GUID-61a491d2-fc8b-4a91-b6bc-7bede34e466d",
                      "roles": ["consortiumMember"],
                      "identifier": {
                          "scheme": "XI-GUID",
                          "id": "61a491d2-fc8b-4a91-b6bc-7bede34e466d",
                          "legalName": "Mr A",
                      },
                      "name": "Mr A"                      
                },
                 {
                      "id":"GB-COH-12345567",
                      "roles": ["consortiumMember"],
                      "identifier": {
                          "scheme": "GB-COH",
                          "id": "12345567",
                          "legalName": "Any Corp Ltd",
                      },
                      "name": "AnyCorp"                      
                },
                 {
                      "id":"XR-NUTS-UK",
                      "roles": ["consortiumMember"],
                      "identifier": {
                          "scheme": "XR-NUTS",
                          "id": "UK",
                          "legalName": "AnyState",
                      },
                      "name": "AnyState"                      
                }
              ]
           }
      ],
      "awards":{
        "id":"ocds-213czf-1.1-upgrade-consortium-award",
        "suppliers":[{
          "name":"The Consortium",
          "id":"XI-GUID-569949c5-2df4-4d9f-81ce-bb34dc134f7e"
        }]
      }

}]}
```
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
We are proposing postponing this until post 1.1 to allow us to align the approach taken with the emerging [Beneficial Ownership Data Standard](https://github.com/openownership/data-standard), which will incorporate relevant modelling related to corporate structure.

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> I probably do not understand how consortia are handled in OCDS 1.0. Reading the supplier description of "The suppliers awarded this award. If different suppliers have been awarded different items of values, these should be split into separate award blocks. See Organization section for further details.", I assumed that multiple suppliers should be given only in the case of consortia. (It's also worth nothing that "awarded an award" is not that clear an explanation.)
> 
> This makes sense also from the point of view that no further information about suppliers is given at the contract level. It is not given, because there was only one contract with all the suppliers in a consortium, so there is no need for further specifications.
> 
> If my understanding above is not correct, and consortia are not covered currently in the OCDS, they definitely should be - already for version 1.1. It's an extremely common situation and if not covered, it causes problem with data (e.g. consortia often don't have VAT identifiers, members of the consortium do) and can cause quite a bit of confusion. 
> 
> (This need to cover it in 1.1 is only about the minimalist use case of a contract / award being given to a consortium instead of a simple supplier. Other use cases such as ownership and shareholders can wait.)

**Comment by timgdavies** [comment]
It is possible for a consortia to be recorded as the ```award.supplier``` in OCDS 1.0 and 1.1. 

In such cases, the publisher of the data would need to decide how to assign an identifier to the consortia, and how to describe it (e.g. what organisation name, legal name etc. to use)

The focus of this issue was on whether there should be a structured way of recording each of the companies that make up that consortia.

**Comment by JachymHercher** [comment]
Then it seems I have understood it correctly. In that case, I would really emphasize that this should be dealt with as soon as possible. If you have names and identifiers of multiple companies mixed up in one field, the data cannot really be analyzed without human intervention because each publisher of data will have a different strategy on how to give this information. This is not a negligible issue because bids by consortia are common (at least in the EU). 

(Also note that the current version of the EU procurement forms allows declaring members of consortia.)

**Comment by timgdavies** [comment]
This was not fully resolved in 1.1, although there is a community extension for [shareholders now available for OCDS 1.1](https://github.com/open-contracting/ocds-shareholders-extension) that can be tested for capturing consortium information, and the ongoing work on EU-related OCDS extensions will further contribute here.

**Comment by jpmckinney** [comment]
Note: Colombia adds a `parties.details.isGroup` boolean to indicate whether a party is a consortium or temporary union. @yolile

**Comment by mrshll1001** [comment]
Just adding some context from a recent interaction from the Helpdesk. In Italy a member of an association / consortium may bid on a procurement both as a member of the consortium and separately. Following the [proposal](https://github.com/open-contracting/standard/issues/370#issue-177186382) would it be reasonable to have both `consortiumMember` and `tenderer` as a role to distinguish between these?

e.g.

```json
{
  "parties": [
    {
      "id": "IT-CF-02426720302",
      "name": "SILCE SRL",
      "identifier": {
        "scheme": "IT-CF",
        "id": "02426720302"
      },
      "roles": [
        "consortiumMember"
      ]
    },
    {
      "id": "IT-CF-TNTGLN70C06C817K",
      "name": "TONEATTO GIULIANO",
      "identifier": {
        "scheme": "IT-CF",
        "id": "TNTGLN70C06C817K"
      },
      "roles": [
        "consortiumMember", "tenderer"
      ]
    }
  ]
}
```

Note: this implies that if a party is only applying through membership of a consortium that they are not given a `tenderer` role but I feel this matches the [definition of tenderer as given in the documentation](https://standard.open-contracting.org/latest/en/schema/codelists/#party-role) ie a party with a role of `consortumMember` did not submit a bid; the consortium did.

Furthermore if this approach is taken, when you declare suppliers through the references in the `awards/0/suppliers` array, the parties have enough details through the roles to determine the nature of how it was awarded ie:
* if the award is made to a single supplier which has roles of `consortiumMember` and `tenderer` then it's implied they won the process on their individual bid
* if the award is made to a group of suppliers where all have `consortiumMember` as a role then it's implied the bidding was won by a group even if all also have individual `tenderer` roles -- this means that despite all of them submitting individual bids the procurement was awarded to the group entity.

**Comment by jpmckinney** [comment]
Note that, for better or worse, in eForms (as described in the eForms Policy Implementation Handbook):

> “Consortia” can be used in an interface to group economic operators, even though in eForms they are only stored implicitly (as economic operators that are linked to the same Winning Tender).

**Comment by jpmckinney** [comment]
This guide from CCE might be helpful when exploring modelling options.

Spanish: 
https://www.colombiacompra.gov.co/sites/cce_public/files/cce_documents/cce_guia_asuntos_corporativos.pdf

English:
https://www.colombiacompra.gov.co/sites/cce_public/files/cce_documents/guia_asuntos_corporativos_ing2.pdf

**Comment by jpmckinney** [comment]
As part of 1.1.5, there is a worked example for consortia: https://standard.open-contracting.org/1.1-dev/en/guidance/map/consortia/

For posterity, linking to this internal document from an OCDS retreat in Feb 2020: https://docs.google.com/document/d/1EJDKDHnVnEK6n807GWHlqhEdnvRJpSqZ5tMPWLKPRxs/edit#heading=h.mfveqxtjjllb
