### ISSUE TITLE
Transactions terminology

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#372]
# Transactions terminology

This issue is under consideration for the 1.1 milestone.

It builds on previous discussions in #343 and #359
## The issue

The current naming convention of the parties to a transaction (**providerOrganization** and **receiverOrganization**) could be interpreted as relating to the goods or services procured rather than the flow of funds between the parties.

There is an inconsistency between our use of **transaction.amount** and the use of **tender.value**, **award.value** etc. For consistency we should be using **transaction.value**
## What we are proposing

Rename **providerOrganization** to **payer** and **receiverOrganization** to payee.

Rename **transaction.amount** to **transaction.value**

This would involve introducing the new fields, and deprecating the old fields
## Example

``` json
"contracts": [
    {
        "implementation": {
            "transactions": [
                {
                    "payer": {
                        ...
                    },
                    "payee": {
                        ...
                    },
                    "value": {
                        "amount": 50000,
                        "currency": "GBP"
                    }
                }
            ]
        }
    }
]
```
## Outstanding questions

Are there any situations in which there would be a transaction, but the idea of representing this as a payment would be problematic?
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

Please provide feedback on the outstanding question in a comment.

**Comment by mireille-raad** [comment]
For the Outstanding question:
Here is a case scenario I saw possible in PPP that can't be translated to payment:
Govt. gives "land-use" rights to a private sector company.

(not sure this is modeled as "transaction" - but thought to share)

**Comment by duncandewhurst** [comment]
There is draft schema [here](https://github.com/open-contracting/ocds_upgrade_372) which implements this proposal.

In addition to the proposed changes above the extension also updates the reference to "Budget Data Package" in the description of the transaction block to read "Fiscal Data Package" in line with the discussion in #378 

The extension follows the approach to deprecation described in #401 

Assigning to @ekoner to review

**Comment by duncandewhurst** [comment]
Draft schema updated to fix Budget Data Package references in the ```transaction.id``` and ```transaction.source``` field descriptions.

**Comment by ekoner** [comment]
`providerOrganization` and `receiverOrganization` use the `Identifier` block in the current schema. However there is an upgrade proposal Updates to organisation handling in OCDS #368 which impacts how we implement the change.

Everything else looks fine. Assigning to @duncandewhurst to align with #368

**Comment by timgdavies** [comment]
I've merged this into my staged copy of the schema, with a minor update to use OrganizationReference rather than Identifier for the cross-referencing.
