### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#373]
This issue is under consideration for the 1.1 milestone. 

This builds on prior discussions in #227
### The issue

The milestones block in OCDS was developed to provide a flexible space to capture date and process-related information that is not otherwise standardised. 

However, to date it has not been widely used, and it is not currently possible to distinguish between the different kinds of milestones that may exist during a procurement process. 

For example, is a milestone a delivery requirement of providers? Or a description of key deadlines during an engagement process during planning. 
## The proposal

We will introduce a milestone type field to:
- Enable consuming applications to distinguish between the different kinds of milestones, whichever block they appear in;
- Allow publishers to be clearer about the kinds of milestones they are publishing;

The proposed codelist for this is:

| Code | Title | Description |
| --- | --- | --- |
| planning | Planning milesones | For events during the planning phase of a process. |
| engagement | Engagement milestones | For engagement milestones, such as a public hearing |
| adjudication | Adjudication milestones | For adjudication milestones, such as the meeting date of a committee. |
| delivery | Delivery milestones | For delivery milestones, such as the date when a good or service should be provided. |
| reporting | Reporting milestones | For reporting milestones, such as when key reports should be provided. |

We will update the milestoneStatus code list to include an extra entry for **scheduled** milestones, and will add definitions, giving a codelist of:

| Code | Title | Description |
| --- | --- | --- |
| scheduled | Scheduled | This milestone has been scheduled for the date in milestone.dueDate. Progress towards the milestone has not yet been evaluated as of milestone.dateModified |
| met | Met | This milestone has been achieved. The data on which it was met should be placed in the milestone.dateMet field |
| notMet | Not Met | This milestone had not been met at the date it was last reviewed (see milestone.dateModified). |
| partiallyMet | Partially Met | This milestone was judged to have been partially met at the date it was last reviewed (see milestone.dateModified) |

We will add a `milestone.dateMet` field so that the data a milestone was met on can be explicitly declared.

In issue #355 we are also proposing deprecating milestone documents from core. This would be re-introduced in an extension, but to simplify the standard, we would not ask for documents attached to individual milestones. 
## Questions

`dateMet` does not follow our usual pattern of using 'Date' as the suffix rather than prefix. However, it feels more natural than `metDate`. Views on terminology here are welcome. 

(dateModified is an existing exception to the pattern, as we follow common terminology in use in other standards for this). 

Should we also consider adding a `code` field to milestones that would allow explicit cross-referencing between milestones in tender, award and contract - and that would allow cross-referencing to codelists of more detailed milestones for particular countries? 

(For example, there could be a code for the 'bid opening date' so that all EU contracts can clearly indicate this). 

Should we consider adding a `report` field for free-text information reporting on the milestones progress?
## Worked example

In the example below, a publisher is providing anticipated dates of the committee meeting in the tender block, along with details of when they took place. In the award they are specifying agreed delivery deadlines and reporting deadlines.

``` json
{
"uri":"http://standard.open-contracting.org/examples/releases/ocds-213czf-000-00001-04-award.json",
"publishedDate":"2010-05-10T09:30:00Z",
"publisher": {
        "scheme": "GB-COH",
        "uid": "09506232",
        "name": "Open Data Services Co-operative Limited",
        "uri": "http://standard.open-contracting.org/examples/"
    },
"license":"http://opendatacommons.org/licenses/pddl/1.0/",
"publicationPolicy":"https://github.com/open-contracting/sample-data/",
"releases":[{
        "language": "en",
        "ocid": "ocds-213czf-000-00001",
        "id": "ocds-213czf-000-00001-04-award",
        "date": "2010-05-10T09:30:00Z",
        "tag": ["award"],
        "initiationType": "tender",
        "entities": {
          "...":"..."
        },
        "buyer": {
            "id":"GB-LAC-E09000003",
            "name": "London Borough of Barnet",
        },
        "tender": {
            "id": "ocds-213czf-000-00001-01-tender",
            "title": "Planned cycle lane improvements",
            "description": "Tenders solicited for work to build new cycle lanes in the centre of town.",
            "status": "active",
            "items": [
                {
                    "id": "0001",
                    "description": "string",
                    "classification": {
                        "scheme": "CPV",
                        "id": "45233130",
                        "description": "Construction work for highways",
                        "uri": "http://cpv.data.ac.uk/code-45233130"
                    },
                    "additionalClassifications": [
                        {
                            "scheme": "CPV",
                            "id": "45233162-2",
                            "description": "Cycle path construction work",
                            "uri": "http://cpv.data.ac.uk/code-45233162.html"
                        }
                    ],
                    "quantity": 8,
                    "unit": {
                        "name": "Miles",
                        "value": {
                            "amount": 120000,
                            "currency": "GBP"
                        }
                    }
                }
            ],
            "minValue": {
                "amount": 600000,
                "currency": "GBP"
            },
            "value": {
                "amount": 1100000,
                "currency": "GBP"
            },
            "procurementMethod": "open",
            "procurementMethodRationale": "An open competitive tender is required by EU Rules",
            "awardCriteria": "bestProposal",
            "awardCriteriaDetails": "The best proposal, subject to value for money requirements, will be accepted.",
            "submissionMethod": [ "electronicSubmission" ],
            "submissionMethodDetails": "Submit through the online portal at http://example.com/submissions/ocds-213czf-000-00001-01/",
            "enquiryPeriod": {
                    "startDate": "2010-03-01T09:00:00Z",
                    "endDate": "2010-03-14T17:30:00Z"
            },
            "hasEnquiries": false,
            "tenderPeriod": {
                "startDate": "2010-03-01T09:00:00Z",
                "endDate": "2010-04-01T18:00:00Z"

            },
            "awardPeriod": {
                "startDate": "2010-06-01T00:00:00Z",
                "endDate": "2011-08-01T23:59:59Z"
            },
            "milestones": [{
                "id": "0001",
                "type":"adjudication",
                "title": "Bid Opening ",
                "description": "The data when the bid will be openned.",
                "dueDate": "2010-04-01T18:00:00Z",
                "status":"met",
                "dateMet": "2010-04-01T18:00:00Z",
                "dateModified":"2010-04-01T18:00:00Z"

            },
            {
                "id": "0002",
                "type":"adjudication",
                "title": "Review Committee Meeting ",
                "description": "The date when the review committee will meet to assess bids.",
                "dueDate": "2010-04-05T15:00:00Z",
                "status":"met",
                "dateMet": "2010-04-05T16:00:00Z",
                "dateModified":"2010-04-01T18:00:00Z"
              }]
        },
        "awards": [
               {
                   "id": "ocds-213czf-000-00001-award-01",
                   "title": "Award of contract to build new cycle lanes in the centre of town.",
                   "description": "AnyCorp Ltd has been awarded the contract to build new cycle lanes in the centre of town.",
                   "status": "pending",
                   "date": "2010-05-10T09:30:00Z",
                   "value": {
                       "amount": 11000000,
                       "currency": "GBP"
                   },
                   "suppliers": [
                       {
                           "id":"GB-COH-1234567844",
                           "name": "AnyCorp Cycle Provision",
                       }
                   ],
                   "items": "...",
                   "contractPeriod": {
                       "startDate": "2010-07-01T00:00:00Z",
                       "endDate": "2011-08-01T23:59:00Z"
                   },
                   "milestones": [
                      {
                        "id":"0003",
                        "type":"delivery",
                        "title":"Building work started",
                        "description":"Building work should start by this date.",
                        "dueDate":"2010-10-01T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      },
                      {
                        "id":"0004",
                        "type":"delivery",
                        "title":"Building work complete",
                        "description":"Building work should be complete by this date.",
                        "dueDate":"2011-06-01T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      },
                      {
                        "id":"0005",
                        "type":"reporting",
                        "title":"Project initiation report",
                        "description":"A report on project initiation should be provided by the end of 2010",
                        "dueDate":"2010-12-12T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      },
                      {
                        "id":"0006",
                        "type":"reporting",
                        "title":"Mid-term project report",
                        "description":"A mid-term project report should be provided by March 2011",
                        "dueDate":"2011-03-31T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      },
                      {
                        "id":"0007",
                        "type":"reporting",
                        "title":"Final project report",
                        "description":"The final project report should be provided by the end of the project.",
                        "dueDate":"2011-08-01T23:59:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      }
                   ]
                }
           ]

    }]
}
```
## Additional implications

To the best of our knowledge, few procurement systems have very detailed structured information on them on milestones, particularly delivery and reporting milestones. As a result, inclusion of delivery and reporting milestone blocks in the standard for tender and award is driven by user needs, more than existing data supply.

This means we that inclusion of this updated milestone block in the standard constitutes encouragement for improvements in the collection and management of this kind of information.

We should develop some interface guidance on:

(a) Collecting milestone information;

(b) Displaying milestone information;

To ensure that publishers and users have a clear understanding of the capababilities, and the limitations, of the milestone block.
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by duncandewhurst** [comment]
Currently _milestones_ only appear in the _tender_ and _implementation_ sections of the schema.

The worked example given by Tim includes a _milestones_ field in the _award_ section and based on the inclusion of _planning_ in the _milestoneType_ codelist we should also add a _milestones_ field to the _planning_ section of the schema. This would be useful for the PPP case where there are various approvals which may take place during the planning phase which could be represented be milestones.

**Comment by duncandewhurst** [comment]
Draft schema update staged as extension [here](https://github.com/duncandewhurst/ocds-milestones-update)

**Comment by timgdavies** [comment]
I've updated the draft extension, [forked into OCDS repository here](https://github.com/open-contracting/ocds-milestones-update). 

This draft:

* Only includes milestones on planning, tender and contract (the Readme contains an explanation of this)
* Uses slightly different type codes (preProcurement rather than planning) to avoid mixing milestone names with the names of OCDS sections

Comments welcome.

**Comment by timgdavies** [comment]
Suggested update to definition of milestone type definitions (for requirements of the PPP project)

| code | title | description |
|---------|------------|------------|
| adjudication |	Adjudication milestones |	For adjudication milestones, such as the meeting date of a committee. **Sometimes known as evaluation or assessment.** |
| delivery | Delivery milestones | For progress milestones covering delivery of the goods, works,  or services specified in the contract, including start or end-dates of the development period of works projects. |

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> I'm not sure whether the benefits of this field outweigh the added complexity.
> 
> - If I understand correctly, milestones are published in a tender section and then updated via the implementation section. In this case, I'm not sure the pre-tender milestones ("planning" and "engagement") are relevant, because they will always be already met at the time of publication of the tender section. Thus, it's essentially "this is what we did". Given how diversified planning and engagement actions could be, I'm not sure structuring them adds much. Is there a clear use case? 
> 
> - I wonder whether the distinction between "delivery" and "reporting" adds much and shouldn't perhaps be dropped. I have many questions: Isn't "reporting" simply a "delivery of a report"? Or is the point of "delivery" that it's essentially the completion of the contract? (If yes, I would say that it isn't too useful to have this in the codelist as a separate value, because we can assume that simply any last milestone corresponds to the completion of the contract.) If we think about different types of procurement, e.g. works, I can imagine that there is a milestone where the first layer of concrete for a road has been laid. Is that a delivery of an intermediate product, or is that a report on the progress made? Does the distinction matter?
> 
> - I'm thinking what's the relationship between the codelist and the stages of the procurement process. If there is a close matching (e.g. "planning and engagement" is always part of planning, "adjudication" is always part of award, "delivery" and "reporting" are always part of implementation), wouldn't it be simpler to just reuse the stage names (=section names) as the codelist?
> 
> (As discussed elsewhere, "adjudication" is a complicated word for which perhaps a simpler synonym could be found.)
