### ISSUE TITLE
Bid extension

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#379]
This is under consideration for the 1.1 upgrade of the standard.

We are proposing to create an extension for 1.1, with a view to it potentially be included in core in a future upgrade.

This builds on discussions in #197 #356 and #141
## The issue

Detailed bidding information was not included in the 1.0 RC due to a range of different proposals.

Under tender we currently have:
- An array of organizations for `tenderers`
- `numberOfTenderers`

There is demand for:
- More detailed information on each bid
- Statistic about bidders (unique organizations), bids (unique bids), valid bids, qualified bidders, etc. 
## The proposal

We will introduce a substantial new section to OCDS for `bid` to sit alongside `tender`, `awards` and `contracts`. 

The full details of this remain to be developed, and at this point we are looking for general feedback on the idea of an expanded bids section which would ask publishers to provide either:
- Key bid statistics, including
  - The number of unique qualified bidders
  - The number of unique disqualified bidders
  - The total number of bids
  - The number of valid bids

and/or
- Details of each individual bid, including:
  - The name and identifier of the bidder (who should also appear in the proposed top level `entities` array (#368))
  - Whether or not the bidder passed qualification requirements
  - The value of the bid
  - Whether or not the bid was valid
  - The status of the bid
  - Any associated bid documents

In prior discussions (see #197) we have looked to follow the model used in ProZorro for this extension
## Engagement

Views are invited on:
- Whether `bids` information should form part of core OCDS or an extension
- What it is reasonable to cover in the extension
- What kinds of statistics and categorisation of bids are required

**Comment by myroslav** [comment]
We'll develop `Bid` extension to OCDS 1.0 to cover information we collect in ProZorro. I.e. in addition to aspects above we are collecting `selfEligible` and `selfQualified` for bids in specific kinds of procedures requiring their presence. Additionally we're gathering `parameters` along with the `value` for MEAT tenders. And yet another data flavor is there for tenders that are split in lots

**Comment by duncandewhurst** [comment]
The World Bank's [Public Procurement Indicators](http://www.eprocurementtoolkit.org/sites/default/files/2016-10/Public%20Procurement%20Indicators-Rapid_e-Procurement_Toolkit.pdf) for monitoring e-GP adoption and performance includes several indicators based on the submission method for the successful bid, so we should consider including **submissionMethod** as a property of individual bids.

**Comment by duncandewhurst** [comment]
Some requirements for the bid extension are noted in the [EC TED eforms explanatory note](http://ec.europa.eu/DocsRoom/documents/20224):

![image](https://cloud.githubusercontent.com/assets/19265814/21841294/8a6c4f66-d7d9-11e6-8150-30bbc4efc38f.png)

**Comment by mpostelnicu** [comment]
Thanks, this looks very promising. 

Capturing the date of the bid can be very useful later, especially for corruption risk flagging. Not sure if you have that already in the draft, I saw it mentioned in previous (closed) issues, but not here, yet.

**Comment by timgdavies** [comment]
I've been working on a [draft bids extension here](https://github.com/open-contracting/ocds_bid_extension) which has two main sections:

* Bid Statistics - using the [bidStatistics](https://github.com/open-contracting/ocds_bid_extension/blob/master/codelists/bidStatistics.csv) codelist
* Bid Details - with a block for each bid

I've been drawing on the [Open Procurement API](http://api-docs.openprocurement.org/en/latest/bidding.html), and new EU Forms drafts.

There's still quite a bit to do, including:

* [ ] Demonstrate mapping between ```bid/details``` and statistics;
* [ ] Distinguish between bids for qualification, and bids at a later round of the process;
* [ ] Ensure all EU-required bidding parameters have been captured
* [ ] Add in support for requirements (e.g. structured bid information)
* [ ] Add in full support for lots

**Comment by duncandewhurst** [comment]
@timgdavies I've added ```bid.requirementResponses``` to the [requirements extension](https://github.com/duncandewhurst/ocds-requirements-extension) for the PPP extension so I think that can be ticked off.

**Comment by siwhitehouse** [comment]
Looking at the new TED Notice Forms, there are the following fields included when an award is announced:

Number of requests to participate received:
Number of tenders received: 
Number of tenders received from small or medium enterprises:
Number of tenders received from other EU Member States, Iceland, Liechtenstein or Norway
Number of tenders received by electronic means:
Tenders were excluded on the ground that they were abnormally low

Which is similar, but different, to those in the EC TED reforms explanatory note that @duncandewhurst posted.

**Comment by JachymHercher** [comment]
My comment from the 1.1 peer review:

> The description for foreignBidsFromEU is not quite correct. The EU field asks about all the members of the EU single market, i.e. "other EU countries, Iceland, Norway,or Liechtenstein". As this fields comes from the EU legislation, the OCDS description should be changed to correspond 100%.

**Comment by jpmckinney** [comment]
Noting that @JachymHercher's comment is reflected in the following commit.
