### ISSUE TITLE
Connect records of challenges to a contract

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#38]
Requirement generated from [User Research process](https://docs.google.com/a/webfoundation.org/spreadsheets/d/1m_Kr7I5XqM7PFcz75ZNmcdFCzLaike_IsEmAh5eN-WE/edit#gid=2035729003): R28

Users are interested in the ability to link 'Court records of award challenges' to tenders.

This was a requirement from the anti-corruption use cases. More generally, there are instances in which procurement portals include dispute mechanisms, and may be able to publish information about disputes over various aspects of the contract process and how they were resolved, potentially linking judgements to organisations.

**Comment by timgdavies** [comment]
This is not under consideration for 1.1

**Comment by jpmckinney** [comment]
Relevant to EU and UNCITRAL.

EU:

> An economic operator applied to the buyer for a review of the procedure ◯ yes ◯ no
> An economic operator or another party challenged the procedure before a review body or a court ◯ yes ◯ no
> \+ Identifier(s) of the review procedure(s):

UNCITRAL:

> Article 66.3 Application for reconsideration before the procuring entity. Promptly after receipt of the application, the procuring entity shall publish a notice of the application
> Article 67: 5(d) Promptly upon receipt of the application, the [name of the independent body] shall (d) Publish a notice of the application.

**Comment by jpmckinney** [comment]
My references to EU and UNCITRAL don't go as far as 'connect records of challenges to a contract'.

There has been no participation in this issue outside standard editors. Closing, but can be re-opened for discussion if interest is expressed.
