### ISSUE TITLE
Adding 'direct' to the procurement method codelist

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#380]
This issue is under consideration for a core update in version 1.1

It builds on discussions in #194
## The issue

The current procurement [method codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#method) is a closed code list and contains:
- open - Open tendering means a procurement method whereby all interested suppliers may submit a tender.
- selective  - Selective tendering means a procurement method whereby only qualified suppliers are invited by the procuring entity to submit a tender.
- limited - Limited tendering means a procurement method whereby the procuring entity contacts a supplier or suppliers of its choice.

This does not adequately distinguish between limited tendering and direct awards.
## The proposal

Adding a new code direct for direct awards with a new definition (to be drafted).

Updating the definition of limited to:
- “Limited tendering means a procurement method whereby the procuring entity contacts a number of suppliers of its choice” (draft wording)

This will result in a procurement method codelist of:

| Code | Title | Description |
| --- | --- | --- |
| open | Open | Open tendering means a procurement method whereby all interested suppliers may submit a tender. |
| selective | Selective | Selective tendering means a procurement method whereby only qualified suppliers are invited by the procuring entity to submit a tender. |
| limited | Limited | Limited tendering means a procurement method whereby the procuring entity contacts a number of suppliers of its choice. |
| direct | Direct | definition tbc |
## Engagement

We are looking for a good definition of 'direct' procurement to use here. Contributions and pointers are welcome. 

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by agm3dc** [comment]
The new wording of "limited" means that it would no longer pertain specifically to "sole-source" or "single-source" procurement. In many polities, sole-source contracting enables a PE to contract with a supplier directly and without competition, as long as the contract is under a certain threshold. A specific listing for sole-source is essential, as there are a number of red flags relating to this procurement method. Additionally, I propose to add a field specific to the threshold for sole-source contracts, as it is important to compare tender amounts to the threshold (to understand if PEs are providing contracts just below the amount to flout competitive procurement rules).

**Comment by agm3dc** [comment]
To be clear, we would propose a "sole-source" code be added to the list, along with a soleSource/Threshold field.

**Comment by timgdavies** [comment]
As far as I understand, **direct awards** (the proposed new code) and **sole-source** are synonyms.

However, some of what I read suggests this might not always be clear cut. Procurement expert input very welcome on this.

Do we need new codes for both:
- Direct; and 
- Sole-Source

And how would the definitions vary if we do?

**Comment by agm3dc** [comment]
Thanks. I think we also view direct awards and sole-source as synonyms.

**Comment by AlCollier** [comment]
Agree that the terms are synonymous.
Understand the rationale for including the threshold, but don't think it will be straightforward. 
In my organisation, for example, there are multiple thresholds depending on level of authority. Any senior manager can sign up to one threshold; anything over that  threshold also needs sign off by me as head of procurement; anything over my authority level goes to a committee; etc. So hypothetically one might see single source tenders clustering just below any of those levels.
Ultimately there is no threshold where there is a legal justification for going single source: technical compatibility, pre-existing intellectual property rights, natural disaster, etc.
So, 'threshold' would need to be defined very carefully. Perhaps something like "the highest value for which a single source procurement process is permitted by law, in the absence of exceptional circumstances". Carried to its logical extreme we might want a codelist for the reason for going single source and we might want to know the identity of the person or committee authorising a single source procurement.
Hope this helps.
Al

**Comment by duncandewhurst** [comment]
The [UNCITRAL model law on public procurement glossary](http://www.uncitral.org/pdf/english/texts/procurem/ml-procurement-2011/Glossary-e.pdf) gives the following definition of a direct solicitation:

>  Solicitation addressed directly to one supplier or contractor or 
> a restricted number of suppliers or contractors. This excludes 
> solicitation addressed to a limited number of suppliers or 
> contractors following pre-qualification or pre-selection 
> proceedings.

**Comment by duncandewhurst** [comment]
The [World Bank Procurement Regulations](https://policies.worldbank.org/sites/ppf3/PPFDocuments/4005Procurement%20Regulations_Final%20for%20publishing.pdf) includes a detailed breakdown of market approach, selection method and selection arrangement options:

![image](https://cloud.githubusercontent.com/assets/19265814/20436002/3bbbbe86-ada6-11e6-99d5-84f4e0eb5b8d.png)

**Comment by chrisalexsmith** [comment]
The concern I have regarding the definition in the UNCITRAL model law on public procurement glossary is that it does not seem to distinguish between a solicitation limited to a number of suppliers, which implies that there will be competition, and a solicitation to a single supplier where there is no competition.  Whilst the latter is justifiable in certain circumstances I think its important that the single supplier solicitations can be separated out from those where some competition is likely.

**Comment by duncandewhurst** [comment]
@chriscrownagents thanks and good point - the UNCITRAL definition would cover both **direct** and **limited** in our codelist. Are you aware of somewhere we could find a good definition for **direct** procurement?

Removing the reference to restricted/limited from the UNCITRAL definition would give:

>Solicitation addressed directly to one supplier or contractor. This excludes solicitation addressed to one supplier or contractor following pre-qualification or pre-selection proceedings.

Alexandre Borges de Oliveira, Lead Procurement Specialist (LATAM and Carribean), World Bank suggested the following definition:

> Award of a contract to a single supplier without competition.

**Comment by chrisalexsmith** [comment]
I think Alexandre's definition is good.

**Comment by andrewlorien** [comment]
NSW eTendering has a rarely-used "Single Invitation" type, which is defined as 

> This tender type refers to a procurement that entails request for response from a single supplier

But our "Pre-Qualified / Invited" type does not exclude single suppliers, and is more often used for direct tenders.  I think the new definition of "limited" covers this situation.

**Comment by timgdavies** [comment]
With the updated definition, and making the codes more concise and consistent, the code list will become: 

| Code | Title | Description |
| --- | --- | --- |
| open | Open | All interested suppliers may submit a tender. |
| selective | Selective | Only qualified suppliers are invited to submit a tender. |
| limited | Limited | The procuring entity contacts a number of suppliers of its choice. |
| direct | Direct | The contract is awarded to a single supplier without competition. |

And to address  #298 the definitions on the codelist page of this codelist will be updated to:

> A contracting process aims to fulfil the requirements identified at the planning stage. The procurement method is the procedure used to purchase the relevant works, goods or services. The method codelist draws upon the definitions of open, selective and limited provided by the WTO Government Procurement Agreement, and adds an additional 'direct' code for awards without competition.

**Comment by jpmckinney** [comment]
Noting that UNCITRAL does have a term matching the semantics of 'direct':

> **Single-source procurement**: A method of procurement of last resort which main distinct feature is the absence of competition since the invitation to present a quotation or proposal is addressed only to one supplier or contractor.
