### ISSUE TITLE
Lots

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#381]
This issue is under consideration for the creation of an extension for version 1.1 of OCDS.
## The issue

A lot is a collection of one or more items which may be bid on / awarded within a tender. A tender may have multiple lots. 

OCDS does not currently have any way of describing lots.
## The proposal
- Add a lots array to tender, providing details of each of the lots, their values, and other key information about them;
- Add a lotDetails object to tender for criteria for bidding on the lots.
- Add a relatedLot field to items, documents, and milestones all of which must reference a lot identifier.

Lot identifiers should should at least be unique within the contracting process they relate to.

A draft of a worked up extension is available here #236
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by timgdavies** [comment]
This was discussed on today's OCDS community call. 

@ColinMaudry described the choice in data modelling in France to take a lot-centric approach (treating lots of top-level objects). 

We discussed how this is compatible with generating an OCDS structure **if**:
- There is an overall process identifier shared between lots
- The field specified at tender level in OCDS do not vary between lots in the same process.

I.e. In the proposed OCDS model, all lots share the same:
- procurementMethod
- procurementMethodRationale
- awardCriteria
- awardCriteriaDetails
- submissionMethod
- submissionMethodDetails
- tenderPeriod
- enquiryPeriod
- eligibilityCriteria
- awardPeriod

etc. Checking against the French data, and other data that takes a lot-centric view, may help to validate or challenge the proposed OCDS model.

**Comment by siwhitehouse** [comment]
The following is taken from the new TED Notice Form:

> 3.1 Object of the procurement
> Lot identifier:
> Title: 
> Main CPV code
> Additional CPV code(s): 
> Description: 
> Quantity:[] 
> Unit: 
> Options exist
> Description of options:
> Variants will be accepted
> Further information about variants:
> The procurement is covered by the Government Procurement Agreement
> 

Options and variants in the above appear to be additional requirements that may need to be captured. I am not sure why a procurement level data item - whether it is covered by the Government Procurement Agreement - sits here.

> 4.12 Additional lot information
> Tenders may be submitted at most for the following number of lots: []
> Maximum number of lots that may be awarded to one tenderer: [] 
> The buyer reserves the right to award contracts combining the following lots: [group identifier] [lot
> identifiers] 

The above has been modelled in the  draft of the worked up extension in https://github.com/open-contracting/standard/issues/236, whereas 

> Maximum value of the procurement is lower than the sum of lot values. 
> Maximum total value of the following group(s) of lots: [Group identifier] [Lot identifiers]
> [Maximum value of all lots in the group]

may need to be included.

**Comment by timgdavies** [comment]
The updated lots extension [is now staged here](https://github.com/open-contracting/ocds_lots_extension). 

This includes a ```lotGroups``` array to help model the additional lot information in terms of combining lots, and total values across sets of lots. 

This model also uses 'relatedLot**s**' plural, with an array of lots whenever the linkage is there, as this is relevant for documents and milestones, and could, in some systems, be relevant for items (although in general I understand that items have a relatedLot, not lots). It felt better to be consistent with the use of plural and arrays, than to mix individual and array types for ```relatedLot``` and ```relatedLots``` to avoid confusion. 

Work remains on:

* [ ] Options
* [ ] Variants

but that might come from the EU specific extensions currently under development in work on OCDS for trade.

**Comment by timgdavies** [comment]
@myroslav note the point above re plural relatedLots. Would this cause any problem for your implementations and OCDS export?

**Comment by ColinMaudry** [comment]
@timgdavies I unfortunately don't have much test data yet.

What I have so far is fictitious and handcrafted, but valid against the schemas: https://github.com/etalab/format-commande-publique/tree/master/exemples/json

**Comment by timgdavies** [comment]
See https://github.com/open-contracting/ocds_lots_extension/issues/1 which proposes changing the item->lot relationship from one-to-many to one-to-one.

**Comment by JachymHercher** [comment]
In the section on lot groups, is there actually a need for the (lot group local) id? I'm thinking that the array of relatedLots together with the combine and value options would be enough by itself.

(In theory, something could link to the group ID (e.g. a document), but I think that's currently not the case. Nor am I convinced that would be useful - repeating the array in the few such cases that this could be used seems simpler than introducing an additional id to link to.)

**Comment by timgdavies** [comment]
The lotGroupID is essentially a technical artefact of the OCDS model, where each object in an array needs an ```id``` so that future releases can describe whether they are updating an existing array entry, or replacing the entire array.

**Comment by jpmckinney** [comment]
Closed with creation of https://github.com/open-contracting/ocds_lots_extension
