### ISSUE TITLE
Codelist updates: document type

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#386]
Updates to the document type codelist are under consideration for version 1.1 of OCDS.
## The issue

The [Document Type](http://standard.open-contracting.org/latest/en/schema/codelists/#document-type) codelist currently lacks definitions for a number of documents.

Additional codes have been requested, such as for 
- Cancellation Reasons - #202
- Contract Summary - #220
## The proposal

The document type codelist will be revised.
## Engagement

Please raise any other suggested additional codes, or definition updates, for the document type codelist.

**Comment by myroslav** [comment]
`illustration` - primarily used in reverse (selling) procedures to represent image of object to be sold, on allocation level document of this type to represent lot visually as thubmnail, or as photo gallery's hen number of Illustartion documents are present.

`virtualDataRoom` - URL to system providing access to confidential documents or documents with limited access.

`contractProforma` - template of contract (draft contract) to be signed with Tender winner.

`license` - part of the Bid that represents required licensing document of the bidder.

**Comment by timgdavies** [comment]
Thanks @myroslav 

Can you explain `license` a bit more. Would this be a licensing requirement for the supplier? I.e. 'You must have a banking license', or a copy of the license as submitted by the supplier?

**Comment by myroslav** [comment]
Yes, exactly the caseload financial institution able to participate, or insurance company able to participate. They have to provide their license as one of the documents.

Additional types of documents that I'd remembered are:

`guarantee` - document confirming guarantees required by buyer.

`paymentConfirmation` - some kind of document that confirms payment (we use this kind of document in Complaint process).

**Comment by duncandewhurst** [comment]
There is a typo in one of the existing codes in the [documentation](http://standard.open-contracting.org/latest/en/schema/codelists/#document-type):

physical**Process**Report should be physical**Progress**Report

**Comment by kfrauscher** [comment]
I suggest changing the name of the field from DocumentType to DocumentContent or something similar to this. We are entering OCP's contracts in OCDS in our new tool and we thought that DocumentType would be pdf, word, etc. Then we realized that this is Format and what is meant here is "award', amendment, etc.

**Comment by timgdavies** [comment]
@kfrauscher I think we would probably just want to cover this by improving documentation and interfaces. Any tools should be providing a list of options for Document Type, not just free text entry.

documentType is a widely used field, and there is already a `format` field for the document format.

**Comment by timgdavies** [comment]
I have staged five additions to the documentType codelist:

| Category     | Section                                 | Code                | Title_en                 | Description_en                                                                                                                                                                                                                                                                                                                                                                            | 
|--------------|-----------------------------------------|---------------------|--------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------| 
| intermediate | tender, award                           | contractDraft       | Contract draft           | A draft or pro-forma copy of the contract.                                                                                                                                                                                                                                                                                                                                                | 
| advanced     | tender, bid, contract, implementation   | illlustration       | Illustrations            | Images intended to provide supporting information. The url for images should generally be directly to an image file which applications can display as part of a gallery of images. At the tender stage, images may be illustrations of goods, works or services required or for sale. At the implementation stage, images may be illlustrations or visual evidence of physical progress.  | 
| advanced     | bid, award, contract                    | submissionDocuments | Bid Submission Documents | Documentation submitted by a bidder as part of their proposal.                                                                                                                                                                                                                                                                                                                            | 
| advanced     | contract                                | contractSummary     | Contract Summary         | Documentation providing an overview of the key terms and sections of the contract. Commonly used for large and complex contracts.                                                                                                                                                                                                                                                         | 
| advanced     | tender, award, contract, implementation | cancellationDetails | Cancellation Details     | Documentation the arrangements, or reasons, for cancellation of a contracting process, award or specific contract.                                                                                                                                                                                                                                                                        | 

@myroslav For the moment I've suggested 'submissionDocuments' as the overall category which would cover the licenses or guarantees requested from bidders. 

virtualDataRoom also looks to me like it would just be a variant of 'bidding documents' when mapped to a common OCDS codelist.

**Comment by ekoner** [comment]
Reviewed: Now ready for peer review.

@timgdavies is sample data required?

**Comment by timgdavies** [comment]
The draft of 1.1 defines 'contractSchedule' as "Documentation setting out key milestones and schedules. Structured versions of this information may be modelled using the milestones block." 

However, I think this is (my) in error. This codelist entry should be interpreting [schedule as 'annexe'](http://weagree.com/drafting-principles/4-structuring-the-transaction-documents/4-2-schedules-annexes-and-exhibits/) not timeline or calendar. 

An updated definition for this term will be needed.

**Comment by timgdavies** [comment]
Also: 

"finalAudit" is currently defined as "Documentation of a final audit carried out at the end of contract implementation." - however, it could also be used in the tender stage for an audit of the procurement process. 

Suggestions:

(1) Update the definition to "Documentation of an audit carried out at the end of the procurement process, or contract implementation." 

or 

(2) Rename code to 'audit' alone, and define as "Documentation of audits carried out of the planning process, contracting process or contract implementation." with the meaning interpreted from the section of OCDS the document is found within.

**Comment by timgdavies** [comment]
"evaluationReport" needs a typo fixed. "Documentation on the evaluation of the bids and the application of the evaluation criteria, including the justification **for** the award"

**Comment by duncandewhurst** [comment]
Flagging that the following change wasn't made in 1.1, we should address this in the next bugfix release:

> The draft of 1.1 defines 'contractSchedule' as "Documentation setting out key milestones and schedules. Structured versions of this information may be modelled using the milestones block." 
>
> However, I think this is (my) in error. This codelist entry should be interpreting [schedule as 'annexe'](http://weagree.com/drafting-principles/4-structuring-the-transaction-documents/4-2-schedules-annexes-and-exhibits/) not timeline or calendar. 
>
>An updated definition for this term will be needed.
