### ISSUE TITLE
API specification

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#389]
This issue is under consideration for the 1.1 version of OCDS.
## The issue

In #290 there were discussions of whether OCDS should develop an API standard. Building on the existing publication patterns guidance, an API specification has been developed and [is hosted in a separate repository here](https://github.com/open-contracting/api-specification). 

This specification could be merged into the main OCDS documentation in version 1.1.
## The proposal

The OCDS API Specification will be directly referenced in the 1.1 documentation
## Engagement

Please indicate support or opposition for this proposal using the +1 / -1 buttons or a comment. If opposing the proposal, please give clear justifications, and where possible, make an alternative proposals.

**Comment by jpmckinney** [comment]
Closing as additional work on a standard API specification isn't anticipated in the near future, though links to best practices can be considered.

Most of the issues with existing OCDS APIs are at the implementation level, not at the design level, and even at the design level, better APIs can be implemented by following common patterns and practices.

If I try to imagine OCDS-specific API details, they have to do with creating endpoints that serve particular contracting-related use cases – which is more about customization than standardization.
