### ISSUE TITLE
OCDS Upgrade - Issue Summary & Priority Review Update

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#390]
It's taken us a bit longer than planned to work through all the issues in the mix for the 1.1 Upgrade of OCDS, but I'm pleased to share the latest update on the upgrade 
## Priority review

We've prepared a [slide deck](https://docs.google.com/presentation/d/13x3dROHQ0QdEQsdZDkRoU0NVmN1447ES1lzeeNFcIlg/pub?start=false&loop=false&delayms=3000) with an overview of focus areas and proposals for the upgrade. This provides a high-level summary of some of the proposed changes. 

We have tried to consolidate GitHub issues and to summarise the proposals that are up for discussion. The consolidated issue are linked in the slide deck.

Below you will also find a summary of proposed changes and issue numbers, and we welcome input on:
- (a) Any key issues have been missed out;
- (b) Any issues that should receive more attention;
- (c) Any issues that should not be addressed in version 1.1;
### Next steps

We are currently at the **priority review** stage, and are moving into **development and documentation of upgrades**. 

This means we want to be sure we have all the right issues covered, and to gather insights and input to get the details of each proposed change right. 

Over September and early October a number of workshops will be taking place to check consensus on the priorities, and to dig into the details of proposed updates. 
- October 4th/5th - [International Open Data Conference](http://opendatacon.org/) - Madrid. The OCDS team will be present at the [Open Contracting](http://www.open-contracting.org/events/) day on 4th October, and during Data Standards Day fringe event, as well as throughout the main conference, to discuss upgrade plans.  
- 13th October 2016 - 9am EST / 2pm BST - English language WebMeeting. Looking out for a registration link, and details of how to vote on the issues to be discussed. 
- Date tbc - Spanish language WebMeeting - Translated materials will be provided in advance. 

If you would like to arrange additional workshops or meetings to discuss particular issues, the OCDS helpdesk team would be happy to work with you to schedule this.

Over October and November we will prepare fully worked up schema updates, staged for review, when a series of further discussions will take place. 
### Updated deadlines

With the extra time taken during the prioritisation stage, we have shifted our estimated timeline for the upgrade as below:
- Development of worked up proposals – by <strike>30th September</strike> 30th November 2016
- Peer-review stage – <strike>October/November 2016</strike> December 2016/January 2017
- Final revisions and review – <strike>December 2016</strike> January 2017
## Priority issues

This list summarises the outcome of the prioritisation phase for the OCDS 1.1 upgrade. Following this stage, detailed changes to the schema, codelists, extensions and documentation will be drafted for review (see updated timeline above)
### Proposals

**Core** OCDS should contain building blocks and fields that are useful to a wide range of data publishers and users. 

**Extensions** provide optional building blocks and fields that may not be relevant to all publishers and users, but where standard approaches are beneficial. All extensions proposed here would be standard extensions, with OCDS 1.1 pinned to particular versions of each extension. 

**Codelists** provide lookup values. They vary between 'closed' codelists which must be versioned with OCDS versions, and 'open' codelists which can have values added on an ongoing basis. 

**Associated** resources support implementation of OCDS
1.  (Core) **Deprecation Policy** - Updating the deprecation policy to allow deprecation in decimal releases - #367 
2.  (Core) **Meta-data** - Adding standard version and extension properties to release and record packages. - #301
3.  (Core) **Encoding** - Requiring the provision of UTF-8 encoded I-JSON for JSON, and UTF-8 or Windows-1252 for CSV. - #323 / #166 
4.  (Core) **Amendment handling** - Deprecating use of amendment.changes, and documenting the use of releases and records to provide information of what has changed in an amendment. - #357
5.  (Core) **Negative amounts** - Removing the minimum value on amount to allow negative values. - #253
6.  (Core) **Item quantity** - Switching item.quantity from integer to number to allow fractional amounts to validate.  - #329 
7.  (Core) **Organisations** - Restructuring organisation handling to (a) introduce a top-level 'entities' section where detailed organisation information should be given; (b) creating an organisations role codelist, and role property for organisations; (c) replacing embedded organisation details with a simple identifier cross-reference to entries in the entities block; (d) describing a common approach to extend organisations with classification and additional descriptive information. - #368 #369 #370 
8.  (Core) **Estimated contract dates** - Allowing tender.contractPeriod to contain estimated dates of the contract. - #374
9.  (Core) **Procurement Type** - Introducing a field to indicate whether a tender is for supplies, works or services. - #376
10.  (Core) **Related processes** - Introducing a relatedProcess object to cross-reference between processes for complex frameworks, planning resulting in multiple tenders and contract renewals. Introducing a codelist for relationship types. - #371
11.  (Core) **Milestone Type** - Creating a new property for milestones to indicate whether milestones relate to contract planning, formation, delivery or reporting. - #373 
12.  (Core) **Milestone documents** - Deprecating the nesting of documents at the milestone level. - #355
13.  (Core) **Transactions** - Renaming providerOrganisation to payer, and receiverOrganisation to payee, and amount to value to increase consistency and intelligibility of naming. - #372
14.  (Core) **Enquiries** - Updating the definition of enquiryPeriod and hasEnquiries fields. - #259
15.  (Core) **Overall description** - Introducing a field at the release level for a high-level description of the contracting process. - #342
16.  (Core/Documentation) **Frameworks** - Improving the documentation of how to represent different kinds of frameworks using OCDS. - #310
17.  (Core/Extension) **Budgets** - Removing reference to the Budget Data Package. Developing a budgetBreakdown extension to support multi-year budgets and multi-source budgets. - #378 and #377
18.  (Core/Extensions) **Bids** - Creating a comprehensive bids extension which will add a new 'bids' section between tender and award. Updating documentation on providing tenderer information. - #379
19.  (Core/Extension) **Suppliers in contract** - Exploring options for inclusion of suppliers in the contract object - either in core or an extension. - #249
20.  (Core/Extension) **Contract extension and renewal** - Introducing fields to cross-reference between extensions and their prior contracts in a single contracting process, and to capture information about the potential renewal options for a contract. - #375 #179
21.  (Core) **String validation** - Adding minimum length (non-zero) requirements to certain fields, including ocid, tag and all ids. - #288
22.  (Core/Codelist) **Unit of Measure** - Identifying a codelist to use for unit of measurement, and updating the units building block to include an identifier and name of each unit. - #366
23.  (Extension) **Lots** - Creating an extension to add lots to tender, and allow items, documents and milestones to be associated a lot. - #381
24.  (Extension) **Location** - Finalising the location extension with minor updates to terminology and GeoJSON versions. - #250
25.  (Extension) **Consortia** - An extension to handle consortium members with shareholding and control information. - #370
26.  (Extension) **Multiple buyers** - An extension to allow buyers to be specified at the contract level (used for frameworks open to multiple buyers). - #382
27.  (Extensions) **Taxes in values** - Creating a tax extension to provide taxesIncluded and taxRate entries, and a codelist of tax types. - #383
28.  (Extensions) **Exchange rate** - Creating an extension to provide exchange rates and alterative currency values. - #384
29.  (Extensions) **Tender and bid features** - Allowing specification of criteria required from bids, and the values for those criteria provided by bidders. - #223
30.  (Extension) **Participation fees** - Capturing whether fees are due to access bid documents or submit a tender - #33
31.  (Codelist) **Procurement Method** - Adding a code for direct awards to the procurement method codelist, and updating the definition of 'limited'. Reviewing all descriptions. - #380
32.  (Codelist) **Award Criteria** - Producing a fully updated codelist based on a review of existing categorisations. Reviewing all descriptions. - #385 
33.  (Codelist) **Submission Method** - Producing a revised codelist based upon wider input. Reviewing all descriptions. - #322
34.  (Codelist/Documentation) **Document Type**  - Adding new codes for cancellationDocuments and contractSummary, and adding guidance on documents that should be included for certain tender status values. Improving guidance on documents with multiple types. Reviewing all descriptions. - #386
35.  (Codelist) **Item Classification Scheme** - Adding a number of new codes to itemClassificationScheme - #387
36.  (Codelist) **Codelist case** - Explitly stating the required case (UPPERCASE vs lowercase) for each external codelist - #252
37.  (Codelist) **Withdrawn process** - Explitly stating the required case (UPPERCASE vs lowercase) for each external codelist - #202
38.  (Documentation) **Escaping strings** - Providing guidance on how markup should be included, or escaped, in JSON strings. - #268
39.  (Documentation/Associated) **API specification** - Including details of the proposed API specification in the documentation. - #389
40.  (Core/Associated) - **Codelists in schema** - Including information in the schema on where codelists are found, and on open/closed status, to aid in data validation. - #336
41.  (Core/Associated) - **Merge Strategies** - Removing or reducing the use of merge strategies within the schema. - #287
42.  (Core/Associated) - **Removed objects - merge behaviour** - Documenting a revised approach to removal of objects in merged releases. - #232 
43.  (Documentation) **Basic, Intermediate, Advanced** - Updating the basic, intermediate and advanced guidance, and/or developing a new maturity model for OCDS.  - #388

Issues for development, but with no clear proposal:
- (Core) **Handling open ended procurement** - #211 
- (Extension) **Payment type** - Creating a field and codelist to capture the payment terms of a contract (e.g. per-milestone, lump sum, cost-plus) - #317
- (Core/Extension) **Document versioning** - #243
- (Core) **Status Details Field** - #248

Issues where no change is proposed: 
- (Core) **Address country code** - #270
- (Core) **Status Details** - #248
- (Core) **Arrays in place of single values** - #237, #266, #348, #349
- (Documentation) **Recommending double counting of key properties** - #147

(p.s. I'll send this update out to the mailing list early next week. Posting to GitHub today, as last time I had a post with this many links in, our account was temporarily suspended as we triggered a GitHub spam bot.... so don't want that to coincide with a mail-out if it happens again).

**Comment by agm3dc** [comment]
@timgdavies  I don't believe 32 award criteria is related to #285. Can you confirm?

**Comment by timgdavies** [comment]
@agm3dc Thanks for the spot - that should have been #385. I've updated accordingly.

**Comment by timgdavies** [comment]
A reminder that we have a call on Thursday 13th October - 9am EST / 2pm BST / 3pm CET to discuss the OCDS Upgrade. You can register for WebEx details here: https://goo.gl/forms/LBvhLNuRrqbiEapG3
