### ISSUE TITLE
1.0.2 Bug Fix release staged

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#398]
A bug-fix and documentation update release of OCDS is now staged for review at http://standard.open-contracting.org/1.0.2/en/

Unless objections to this update are raised in the next two weeks, this version will become the live latest version, accessible at http://standard.open-contracting.org/

The [changelog](https://github.com/open-contracting/standard/blob/1.0.2/changelog.md) can be found here, and below. 

This release fixes a number of small issues in preparation for the 1.1 release, for which development is ongoing. 
### Fixed

Added titles to all fields in the documentation (#362)
Missing field procurementMethodDetails added to schema (#221)
Typo fix in releaseTag (#391)
Fixing links to Fiscal Data Package (#271)
Description for numberOfTenderers (#314)
Fixed definition of changes (#244)
Updated documentation to refer to 'Object' not 'Reference' for object fields (#228)
### Other updates

Added CSV download links for registered OCIDs, and publication levels (#340)
Added links to mapping templates in building blocks and getting started sections (#341)
Removed the old Spanish documentation translations folders from standard/docs/es
Updated publication levels spreadsheet to reflect version 1.0.2

**Comment by Bjwebb** [comment]
Pull request for this at https://github.com/open-contracting/standard/pull/402

This is now live at http://standard.open-contracting.org/ and permalinks to the 1.0.2 schema at http://standard.open-contracting.org/schema/1__0__2/
