### ISSUE TITLE
JSON-LD mapping for schema

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#40]
We have carried out some initial analysis of how a JSON-LD context may be provided for Open Contracting data. 

Completing this work is not currently a priority for the 1.0 release, but could be carried out in partnership with the community if there was interest.

**Comment by timgdavies** [comment]
@elf-pavlik @akuckartz @cgueret As there is renewed interest in this from #226 perhaps we can start mocking up a bit of JSON-LD context for OCDS.

The main questions I've encountered when looking to do this are:

(a) How do we best maintain a JSON-LD context alongside the main JSON schema? Is there some tooling that could help generate this programatically?

(b) Should we be minting URIs for each OCDS field (e.g. http://ocds.opencontracting.org/vocab/1.0/description etc.) or trying to map to existing vocabularies (e.g. http://purl.org/dc/terms/description )

We could use this thread to start mocking up how a JSON-LD context for OCDS JSON would look. The sample data here might be helpful for testing: https://github.com/open-contracting/sample-data

**Comment by elf-pavlik** [comment]
> (b) Should we be minting URIs for each OCDS field (e.g. http://ocds.opencontracting.org/vocab/1.0/description etc.) or trying to map to existing vocabularies (e.g. http://purl.org/dc/terms/description )

I would encourage reuse of terms from existing, maintained and adopted vocabularies whenever possible!

**Comment by elf-pavlik** [comment]
http://ocds.open-contracting.org/standard/r/1__0__0/en/schema/reference/#language

```json
{
    "language": "en",
	"tender": {
	    "item": {
    			"description":"Software consultancy services",
    			"description_es":"Servicios de consultoria en software",
    		    "description_fr":"Services de conseil en logiciels"
    	}
    }
}
```

JSON-LD seems to handle it in much nicer way
http://www.w3.org/TR/json-ld/#string-internationalization

```json
{
    "@context": { "@language": "en" },
	"tender": {
	    "item": {
    	      "description": {
                "en" :"Software consultancy services",
    	        "es": "Servicios de consultoria en software",
    	        "fr": "Services de conseil en logiciels"
    	}
    }
}
```

**Comment by Bjwebb** [comment]
Looks to me like JSON-LD can also handle the current OCDS structure, using an expanded term definition, see Example 33 of http://www.w3.org/TR/json-ld/#string-internationalization - OTOH, this looks like it requires enumerating every language you want to use in the `@context` - not sure how much of a problem that is.

**Comment by timgdavies** [comment]
Related to #190 and #217

**Comment by jpmckinney** [comment]
Merging with #190 as this issue is not sufficiently distinct.
