### ISSUE TITLE
Tender: Award value variability

### ISSUE THREAD

**Issue by ColinMaudry** [open-contracting/standard#407]
In France, we have a property for tenders (may be set on the award too) that defines whether the set value is :

- fixed (the value cannot be changed ever once awarded)
- modifiable (the value can be changed after award if buyer and supplier agree)
- fixed and adaptable (the value may evolve based on external factors defined in the tender)

There is apparently no such field in OCDS. How would you suggest this data to be included in OCDS data?

**Comment by timgdavies** [comment]
## Questions

(1) Firstly, a question for our procurement experts:

* To what extent does this concept (modifiability) relate to the concept of 'options' in EU procurement forms? 

I notice that the EU forms include simply a tickbox for 'options'  and then free text to describe them, and then ask that the ```value```:

> For all procurement procedures, including for framework agreements and dynamic purchasing systems, the estimated value should be the maximum value, i.e. inculding options and renewals.
>
> For more information, see 2014/24/EU Art. 5."

So we might need to think about guidance when using a flag for modifiability about what value should be set at. 

(2) Second, a question for @ColinMaudry: To what extent would changing the value of the contract be considered an amendment? 

Could we use a more general concept of 'amendment allowed' and then indicate which fields amendment is anticipated for? (E.g. there could be cases where changes in the items supplied are also permitted quite easily). 

## Initial proposal

I'm not sure what the right field name will be, but I think we might want to handle this with a boolean field, and a details field. E.g.

```fixedValue```: yes/no
```valueDetails```: free text for either detailed descriptions, or for individual implementation to choose use of a structured codelist based on national requirements. 

Thoughts?

**Comment by chrisalexsmith** [comment]
Quite often a tender will include a clause that permits the purchaser to amend up or down the quantities within predefined % limits at the contract award stage, thereby allowing the purchaser some flexibility on the value of the awarded contract. This is particularly useful if the purchaser has a limited budget and offers a practical alternative to cancelling the tender if sufficient funds are not available to award a contract for the full quantities tendered for.
It can also be useful if an accurate cost of the requirement is not available when preparing the tender.
If such an adjustment is done at the contract award stage it does not constitute an amendment as such.

**Comment by ColinMaudry** [comment]
Thanks @chriscrownagents, I didn't know about this case.

Now the French decree is about to be published, the different cases for the changeability of the award value are stable. Here are the possible values:

- **fixed**: the awarded value will not change
- **modifiable**: the awarded value may change, typically through post-award renegotiation
- **fixed but can be updated**: the awarded value may evolve according to certain factors agreed beforehand. Typically, the value may follow certain economic or social indicators, such as inflation.

Regarding @timgdavies proposal, I like that it's very versatile, as it boils down to the most common denominator: can the award value change after the contract is awarded, or not? In just two testimonies (Chris's and mine), we found out about several reasons for an award value to change. Having a list of values doesn't look like a good idea at this stage.

I upvote your initial proposal Tim :+1:

**Comment by chrisalexsmith** [comment]
Thanks @ColinMaudry 
World Bank Standard Bidding Document for Goods 2016 includes following:
"42.	Purchaser’s Right to Vary Quantities at Time of Award 	
42.1  	At the time the Contract is awarded, the Purchaser reserves the right to increase or decrease the quantity of Goods and Related Services originally specified in Section VII, Schedule of Requirements, provided this does not exceed the percentages specified in the BDS, and without any change in the unit prices or other terms and conditions of the Bid and the bidding document"

**Comment by timgdavies** [comment]
Comments from Isabel-Maria Da-Rosa at the EC:

> Any change on the contract value* after the signature of the contract* is an information that will be associated with the contract amendments. As you refer in OCDS, you will have the type of amendment, the new value (the one the original contract is not updated), a field indicating if the contract foresees any value modification (y/n) and the justification. Usually when there are such changes there is also and contract addenda that is uploaded to the amendment record.

**Comment by ColinMaudry** [comment]
@timgdavies attn: Isabel-Maria Da-Rosa

Whether the awarded value is modifiable or not, its modification is indeed registered in the OCDS data with a new release. This is not in the scope of this issue.

The topic of this issue is 

> How to reflect the theoretical modifiability (or non-modifiability) of the awarded value, **at the time of the award**

In other words:

> At the time of the award, do the buyer and contractor agree on allowing a modification of the awarded value during the execution of the contract (= after the contract has been awarded), or not.

**Comment by ColinMaudry** [comment]
Is there any progress on this topic? That's the last missing bit for the [French format](https://github.com/etalab/format-commande-publique) to have all its fields [neatly matching OCDS](https://framacalc.org/france-vs-ocds).

**Comment by jpmckinney** [comment]
@chriscrownagents describes the case of the purchaser varying the quantities at time of award, within percentage limits predefined at the tender stage.

@ColinMaudry describes a three-value codelist describing whether the award value can change. This can't be represented as a boolean, because a boolean is two-value. The [JSON schema](https://github.com/etalab/format-commande-publique/blob/370ed2f9d9b38d67584efee57d2c205be6a0247a/schémas/json/marchés.json#L124) has:

```json
    "formePrix": {
      "title": "Forme du prix",
      "description": "Ferme : le prix est fixé pour toute la durée marché. Ferme et actualisable : le prix peut évoluer périodiquement selon des conditions prévues dans le contrat initial (ex: variation d'indice. Révisable : l'acheteur et le titulaire peuvent s'entendre sur une modification du prix après la signature du marché.)",
      "type": "string",
      "enum": [
        "Ferme",
        "Ferme et actualisable",
        "Révisable"
      ]
    },
```

I don't believe we have sufficient evidence in order to standardize a field like `formePrix`, so I recommend a local extension with field `Tender.awardValueModalities` (and field `Award.valueModalities` if necessary) that is an array of strings with an open codelist, with the initial codes potentially being `fixed`, `indexBased`, and `revisable`.

**Comment by jpmckinney** [comment]
My thinking around an array of strings is that it would allow the field to be promoted to a community or core extension, by leaving open the possibility of additional award value modalities. However, keeping it as a simple single-string field would ensure that data doesn't use multiple disjoint codes like `["fixed", "revisable"]`. That validation advantage may be sufficient reason to instead have a field like `Tender.awardValueModifiability`.

Regarding the original proposal, I don't know if tracking 'fixed' versus 'anything else' is so important a use case that we would want a boolean for that.

**Comment by ColinMaudry** [comment]
@jpmckinney I'm glad you could find the bit that is at stake here in the French format :)

I'm all for a solution that can serve as many countries as possible. I liked the boolean option because it works for everybody: either the value can change after the award, or it can't.

I don't like the array of strings, as it can get complex to analyze certain combinations of values.

**My favorite option is the single-string field (`tender.awardValueModifiability` and `award.valueModifiability`) with an open code list**. It's like the boolean option, but with extra room for semantics. Ideally, any other value than `fixed` would mean that the value may change after the award stage.

**Comment by jpmckinney** [comment]
Sounds good. We know we need at least the string codelist field to model the French data. If at a later date we realize that it is critical to know for certain whether a price is fixed or not, we can consider adding a boolean in addition to the codelist.

I had a quick look around, and I might prefer `awardValueVariability` instead of `…Modifiability`. It seems that word might be more common, but I haven't done a thorough analysis.

**Comment by ColinMaudry** [comment]
What's the plan to integrate this field?

Added to the core schema or via an extension?

Thanks.

**Comment by joelgombin** [comment]
Hello all, I'd be interested in knowing more in the plans to tackle this issue too.
FWIW, I think designing a local extension sounds like a better idea than modifying the core schema, but that's only my 2 cents.

**Comment by jpmckinney** [comment]
I recommend creating an extension using the [template](https://github.com/open-contracting/standard_extension_template), based on the discussion here. It's unlikely to become part of the core schema, but in any case, you will have to create an extension first, as the core schema is not expected to add new fields in the short term.

**Comment by ColinMaudry** [comment]
I wonder if this field shouldn't take place in the `contract` rather than in the `award`.

To summarize my dilemna: the variability is decided at award stage, but it's about the value of the contract, not the value of the award.

I think the award value never change by definition, since it's a punctual decision, it doesn't "live" like the contract does.

Thoughts? @jpmckinney @chrisalexsmith

**Comment by ColinMaudry** [comment]
Alpha 0.1.0 is out! https://github.com/ColinMaudry/value-variability-extension

Based on the award for now.

Edit: the data sample is buggy, but you release-schema.json and the CSV code list give a good idea of what it does.

**Comment by jpmckinney** [comment]
I think the variability of the contract value is part of the award decision, so if an Award object is meant to be an award decision, then it makes sense to have it there.

**Comment by jpmckinney** [comment]
Thanks for publishing the extension, @ColinMaudry!

We have not heard from other jurisdictions with similar use cases, so I will close the issue here.

**Comment by ColinMaudry** [comment]
It's currently not implemented in France, as the improvement of the OCDS export has stopped. You can track it here: https://github.com/139bercy/decp-rama/issues/10
