### ISSUE TITLE
Conditional fields based on what extensions exist

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#408]
There are two independent extensions.  ExtensionA and ExtensionB.

ExtensionA does not depend on ExtensionB and vice versa, and they are both extensions that can be used independently.

However, ExtensionA has added a definition i.e
```
{
 "definitions": {
    "extensionADefinition" {
      "type": "object",
      "properties": { many properties here }
   }
}
```

ExtensionB wants to add a property to "extensionADefinition" but clearly only if ExtensionA is enabled.

So ExtensionB has something like the following in release-schema.json
```
{
 "definitions": {
    "extensionADefinition" {
      "properties": {"extensionBNewProperty": {"type": "string"} }
   }
}
```
So how do we make sure that this only happens if ExtensionA is enabled?

**Comment by kindly** [comment]
I see two solutions to this.

1. **We do not care that ExtensionA is enabled**

This will not cause any errors just make the resulting patched jsonSchema look a bit odd. It will look like
```
{
 ...
 "definitions": {
    "extensionADefinition" {
      "properties": {"extensionBNewProperty": {"type": "string"} }
   }
}
```
This is perfectly valid JSON schema (even without the type field information). This definition will never be used as only ExtentionA should reference extensionADefinition.
The only issue I see is that will only work if extensions a strict about putting any nested properties (sub-arrays or sub-objects) in "definitions" and not nesting them directly, however it should mostly work even if you do that.

2. **Have some special property that says only add a property on some condition**

This case we add some special rules to JsonMergePatch to say something along the lines of, only add if some other field exists (or some other rule) i.e
```
{
 ...
 "definition": {
    "extensionADefinition" {
      "properties": {"extensionBNewProperty": {"type": "string", "addIfExists": "/definitions/extensionADefinition"} }
   }
}
```

I prefer 1, as it requires not changing anything, but it does require some kind of "schema standards" to be assessed in extensions but I think we will need those standards at some point anyway.  Option 2 is a lot of work and it means inventing something new, but is ultimately more flexible.

**Comment by timgdavies** [comment]
Thanks @kindly. @myroslav Your thoughts on the above really welcome.

**Comment by myroslav** [comment]
@kindly you are describing simple case when you have extension to extension. We have more complex cases, when an extensions are independent of each other, but only if both of them are installed some specific properties/values are added to OCDS Schema, including the fact that these so called "intersectional exceptions" should automatically be added, and there can be no case when one adds just two independent extension without adding the intersection. See illustration:
![intersectional extension](https://cloud.githubusercontent.com/assets/883905/21205040/dc2aebd2-c262-11e6-8247-67d300c51ac1.png)

**Comment by kindly** [comment]
My understanding is that I am describing exactly the inter-sectional extension case above.  An extension to an extension is simple and I ignored that case completely and is covered by the idea of "dependant" extensions outlined [here.](https://github.com/open-contracting/standard_extension_template#optional-fields)

I have outlined the two solutions to the "Intersectional" case above.

Solution 2, will definitely covers the case, as it gives logic, for each property, to say when it should be added. 
Solution 1 has a few restrictions but as long as you are put all sub-arrays and sub-objects into their own "definitions" nothing needs to be done.  It also has the benefit of not needing to worry about the order the extensions are added. 

I think the confusion here maybe that you are considering patches as "JSON Patch" and not "JSON Merge Patch".  With "JSON Patch" you need to consider ordering more carefully.  With "JSON Merge Patch" you are putting the properties in the schema waiting for them to be used.  So when adding "extensionBNewProperty" you are adding the relevant schema anyway even if extensionA is not there.  The new schema will be useless unless extensionA is added but as soon as it is then the new property will be there waiting.  It is lucky that the jsonSchema metaschema is not very strict about what needs to be in the schema otherwise this would not work.

The only usecase I see "Solution 1" not covering is that when extensionA and extensionB are there then you want add some properties in a completely different part of the schema (outside the definitions that either extensionA and extensionB create).  However, I am not sure I can imagine a use case for this.

**Comment by jpmckinney** [comment]
I'm not clear on the motivation for this issue. It seems to me like if you have complex interdependencies and rules-based logic depending on which combination of extensions you have, then you probably want to author your own 'extension builder' that implements all that logic. It's extremely unlikely that we will author a domain-specific language for extensions with which to express that inter-dependent logic.

We can re-open if there is a specific, real-world example of the sort of logic we want to express in extensions schema.
