### ISSUE TITLE
Remove references to the OCDS Mapper tool 

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#409]
The OCDS Mapper tool  is referenced here http://standard.open-contracting.org/latest/en/implementation/serialization/#generating-json

It is no longer maintained and can be removed from documentation. If the repo can be archived without any issues, I'd also suggest that.

**Comment by Bjwebb** [comment]
Our approach to archiving repos it to move them into https://github.com/open-contracting-archive

**Comment by timgdavies** [comment]
I've moved the mapper to the archive, and staged an updated in 1.1 that removes the reference.

**Comment by jpmckinney** [comment]
As @dc-coder [reported](https://github.com/open-contracting/standard/issues/521#issuecomment-322109913), there is still one link to mapper in levels.md

**Comment by timgdavies** [comment]
Final reference will be removed by https://github.com/open-contracting/standard/pull/600
