### ISSUE TITLE
Tender status: planned vs proposed

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#410]
In the NSW eTendering platform there is a distinction between a [planned procurement](https://tenders.nsw.gov.au/?event=public.app.view&appuuid=AECF4364-FC8D-BE96-0DCF1CF2FAF86C4C) and a [proposed tender](https://tenders.nsw.gov.au/?event=public.rftproposed.list).

In OCDS it is not possible to distinguish between these notices because the ```tender/status``` code list only has a single ```planned``` code.

Should we introduce a ```proposed``` code to the ```tender/status``` codelist?

**Comment by duncandewhurst** [comment]
This may be relevant to the upgrade discussion in #201

**Comment by andrewlorien** [comment]
The Australian Federal Government has a similar structure.  Agencies publish [Planned Procurements](https://www.tenders.gov.au/?event=public.APP.list&tab=List%20By%20Agency) on an annual basis which map reasonably well to OCDS tenders despite having very little detail.  They also publish tenders
with the status [Notice](https://www.tenders.gov.au/?event=public.atm.showClosed&ATMUUID=95207D50-99F1-6498-9CD5D017F88C8C60) which are also referred to as drafts, which are designed to inform the market of an upcoming tender.

**Comment by chrisalexsmith** [comment]
Most multilateral development banks will require borrowers to issue a general procurement notice at the outset of a new project and then publish specific notices for each package either as a request for expressions of interest for consultancy services or as an invitation to tender.

**Comment by timgdavies** [comment]
This is carried forward in #201.
