### ISSUE TITLE
Guidance on OCIDs for re-publishers

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#413]
We are seeing a number of organisations re-publishing data from others.

We need to work further on guidance around how OCIDs should be constructed and managed in these cases. 

(Internal reference to helpdesk issue 1543)

**Comment by mireille-raad** [comment]
are they re-publishing as is? or are they adding data as well? any links you can share?

you might want to add to the guidance on OCID some guidance on mentioning the dates for when the dataset was re-published. (I can't imagine everyone is already doing real time integration/republishing)

**Comment by jpmckinney** [comment]
Having read the mentioned issue, there are a few scenarios we've seen, in which the original source is not in OCDS format:

1. A CSO publishes data in OCDS format, using available data from a government source that includes process identifiers.
1. A CSO publishes data in OCDS format, authoring new data based on a government source that has no structured data or process identifiers.
1. An aggregator publishes data in OCDS format, using data aggregated from many sources that are not in OCDS format, and that may not have process identifiers.

Going through each case:

1. There is the choice of (1) issuing a prefix representing the CSO as publisher or (2) issuing a prefix representing the source as 'ideal' or 'formal' publisher. The latter might mean that, if the source adopts OCDS, then its OCIDs might match the CSO's – an advantage in terms of interoperability. However, there's no guarantee that the mapping to OCDS would be identical, which is a larger barrier to interoperability. The government source might, also, want to avoid any confusion or issues around a CSO publishing data that is not guaranteed to be identical to its own, under the same prefix.
1. There's no opportunity to promote interoperability in a way similar to 1, so a prefix is issued for the re-publisher only.
1. There's limited opportunity to promote interoperability in a way similar to 1, so a prefix is issued for the re-publisher only.

Given the issues with 1(2), I think a simpler way to promote interoperability, in such cases, is for data users to use the common process identifier to match each publisher's data.

The CRM issue only considers scenarios where the source publisher isn't using OCDS. There may be different considerations if the source is in OCDS format, for which a new issue can be opened.

I'm closing this issue as the answer, when the original publication is not in OCDS format, is to simply issue an OCID prefix for the downstream publisher alone.

**Comment by jpmckinney** [comment]
Related issue is https://github.com/open-contracting/standard/issues/364
