### ISSUE TITLE
Pinning extension versions

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#416]
For 1.1-dev I'm planning pulling in core extensions to the documentation, drawing on the extension registry for this. 

However, I anticipate that we will need to pin the 1.1-dev docs to particular versions of core extensions. 

Input on approaches to do this welcome. Tagging @kindly and @Bjwebb

**Comment by kindly** [comment]
The plan for this was to make a branch in the extension_registry with the pinned versions for the 1.1 docs.

And then change this variable to point to that branch.
https://github.com/open-contracting/standard/blob/1.1-dev/standard/docs/en/conf.py#L328

**Comment by timgdavies** [comment]
Ah-ha. Makes perfect sense. Great.
