### ISSUE TITLE
Duplicate key 'title' in release-schema.json 1.0.2

### ISSUE THREAD

**Issue by edugomez** [open-contracting/standard#417]
Duplicate key 'title' in lines 855 and 857 of the release schema:  

`"Amendment": { "title":"Amendment", "type": "object", "title": "Amendment information", ...`

**Comment by timgdavies** [comment]
Thanks for flagging this. It looks like the 2nd 'title' should be 'description'.

I've fixed in this the work for 1.1. 

Not sure whether we should bug-fix in a 1.0.3 or not.
