### ISSUE TITLE
Removing minItems constraint from release package and record package

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#419]
In this [API spec issue](https://github.com/open-contracting/api-specification/issues/5) we are exploring whether release and record packages could contain an empty set of releases. 

This is helpful for an API returning a query response.

## Proposal

The ```minItems``` constraint is removed from release and record package, so that they can contain an empty set of releases.

## Process

Please indicate support or opposition for this proposal.

**Comment by yolile** [comment]
From https://github.com/open-contracting-archive/api-specification/issues/5#issuecomment-278967789 : 

>  It probably makes more sense for the minItems constraint to be removed in the extension not in the core schema.

Should we close this issue and open a new one to update the [extension](https://github.com/open-contracting/api_extension/)?

**Comment by jpmckinney** [comment]
~~That extension~~ The old API extension (to which that issue refers) should not be used.

And I disagree. It makes more sense to remove the constraint in the core schema.

**Comment by yolile** [comment]
closed by #1374
