### ISSUE TITLE
Clarify role of publisher and definition of publisher name

### ISSUE THREAD

**Issue by ekoner** [open-contracting/standard#420]
**publisher name** is currently defined as:

> The name of the organisation or department responsible for publishing this data.

It would be clearer if it explicitly defined the role of the **publisher**, for example:

> The name of the organisation or department responsible for publishing this OCDS data.

This has raised questions in a jurisdiction where the buyers are legally responsible for publishing their information to a central platform. A separate body is then responsible for outputting to OCDS.

**Comment by jpmckinney** [comment]
This is a quick fix, but as it changes the description of a field, leaving for 1.2.

**Comment by martinszy** [comment]
Hello, I'm coming from the 1.1.4 announcement from a month ago I just read. And scrolling trough the list of issues I see that publisher is going to get a refresh and I think this might be the right spot to raise this:
We are a CSO re-publisher, we convert older contracts to OCDS and publish them, along with newer ones, we are also in the process of merging several versions of the same contract from different systems and publishing compiled releases of them, with the same or more information than the government published ones, and covering a longer timescale (20 years, vs 2 years for gov).
We are not the publisher of this data, we are a re-publisher.
Is it alright to say that we need a republisher extension to convey this information, or can we adapt the standard to include a way to specify original publisher and "aggregator" or something.

What do you think?

**Comment by jpmckinney** [comment]
For now, we recommend using [this extension](https://extensions.open-contracting.org/en/extensions/releasePublisher/master/), which adds a `publisher` block on the release. Then:

1. For a release originally published by another publisher, add a `publisher` block to their release and copy the `publisher` block from their package. Make no other changes to their release.
1. For a release for which you are the original publisher,  add a `publisher` block to the release with your details.
1. When creating a compiled release, replace the `publisher` block with your details.

That way, information about the original publisher is always available.
