### ISSUE TITLE
Planning: Budget line title and programme

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#423]
The description for the '''budget.description''' field is

> A short free text description of the budget source. May be used to provide the **title of the budget line**, or the **programme** used to fund this project.

In Mexico contracting processes have **both** an associated budget line title **and** and budget programme

[example programme](http://nptp.hacienda.gob.mx/programas/jsp/programas/fichaPrograma.jsp?id=11E047) - drilling down until there is 5 digits shows the budget title.

**Comment by jpmckinney** [comment]
@duncandewhurst The link isn't working for me, but is there any issue with simply having both the budget line title and budget programme in the same field? In many implementations, the `*Details` fields are a concatenation of fields in source systems; we would need a strong use case for separating the two (and in that case, we'd probably want a new field for each, leaving `budget.description` as a more generic free-text field).

**Comment by jpmckinney** [comment]
@duncandewhurst Is this now handled by one of the budget extensions?

**Comment by jpmckinney** [comment]
I believe this can be handled by https://github.com/open-contracting-extensions/ocds_budget_and_spend_extension
