### ISSUE TITLE
Building docs on Windows

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#433]
build_docs.sh fails on Windows due to line 478 in conf.py:

```py
path_split = self.state.document.attributes['source'].split('/')
```

Replacing `split('/')` with `split('\\')` fixes this - should I update the script or will that break on Linux? If so can we replace it with something more universal?

**Comment by robredpath** [comment]
I'll have a crack at this

**Comment by Bjwebb** [comment]
What branch should @robredpath be working on to fix this? Whilst it looks like `ppp-extension` is the branch you're currently working on, `1.1-dev` also has the problem, and looking at the diffs, it will be easier to merge all the conf.py changes from `1.1-dev` into `ppp-extension` than the other way around (assuming that's what we want to do).

**Comment by timgdavies** [comment]
Change on 1.1-dev and we can merge into ppp-extension

**Comment by robredpath** [comment]
I've switched to using `pathlib`'s `PurePath` for path operations in conf.py and it seems to still work on Linux. @duncandewhurst - can you see if it works on Windows?

**Comment by robredpath** [comment]
@duncandewhurst have you had a chance to try this?

**Comment by duncandewhurst** [comment]
@robredpath I pulled the latest version of the ```ppp-extenion``` branch and build_docs.sh ran ok without me having to change anything

**Comment by robredpath** [comment]
@duncandewhurst that's interesting - I made the change on 1.1-dev!
