### ISSUE TITLE
Rename tenderPeriod to submissionPeriod

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#434]
A suggestion from @jachymhercher in 1.1 peer-review to rename ```tender.tenderPeriod``` to ```tender.submissionPeriod``` to be more consistent with other terminology.

As this would be a backwards incompatible change, I'm adding it to the list for a future 2.0 version.

**Comment by jpmckinney** [comment]
Rather than keep many issues open about renaming fields in 2.0, I recommend reviewing all names as part of a 2.0 process – so closing.
