### ISSUE TITLE
Award criteria breakdown

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#443]
In #385 we discussed using the [requirements extensions](https://github.com/open-contracting/ocds_requirements_extension) to handle structured information about award criteria, namely:

* The balance of cost, price and quality considerations

However, discussions have pointed out:

(a) There is a distinction between **requirements** as qualification criteria; and 
(b) The award criteria on which a final award decision is made;

The later could be modelled with a relatively simple extension, which should be pursued after the 1.1 release.

**Comment by jpmckinney** [comment]
Removing from 'Post 1.1 tasks' milestone, as that milestone is more for 'cleanup'-type tasks.

**Comment by jpmckinney** [comment]
From #385, @JachymHercher's [comment](https://github.com/open-contracting/standard/issues/385#issuecomment-249439581) provides a [link](http://simap.ted.europa.eu/documents/10184/99173/EN_F03.pdf) to an EU form, to provide some real-world context for how award criteria are collected and represented.

![screen shot 2017-09-26 at 5 26 59 pm](https://user-images.githubusercontent.com/26463/30885064-e6e56f8a-a2df-11e7-9908-72d55f06410d.png)

**Comment by jpmckinney** [comment]
Extension drafted https://github.com/open-contracting-extensions/ocds_awardCriteria_extension cc @ColinMaudry

**Comment by ColinMaudry** [comment]
Yes, the extension focuses on compatibility with the [current (possibly moving) eForms structure](https://ec.europa.eu/transparency/regcomitology/index.cfm?do=search.documentdetail&Dos_ID=17796&DS_ID=62369&Version=1), while ensuring compatibility with TED forms ([screenshot above](https://github.com/open-contracting/standard/issues/443#issuecomment-332341368)).

**Comment by jpmckinney** [comment]
Now in Explorer: https://extensions.open-contracting.org/en/extensions/awardCriteria/master/
