### ISSUE TITLE
Adding support for language suffixes to address fields

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#451]
In Tunisia address fields are provided in multiple languages (FR, EN and AR).

Currently the OCDS ```address``` object only includes support for language suffixes for the ```country``` field.

Depending on the changes proposed in #229 we should consider extend multi-language support to the other fields in the address object as a post 1.1 task.

The pattern properties used in the current approach to multi-language support could be added via an extension.

**Comment by dc-coder** [comment]
I am looking at some procurement data in the world bank and a lot of pieces of information have to be provided in en, fr, es, ru and ar. This might be true for other international organizations.

I am not sure if this goes under a new issues or if this add to this issue and to broadening the scope of internationalization... just thought to flag it.

**Comment by jpmckinney** [comment]
Closing in favor of #229.
