### ISSUE TITLE
Mark required fields in ocds documentation

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#453]
Is very necessary mark more clearly and explicitly the required fields of the standard in the documentation page so these fields could be quickly recognized for the users

**Comment by timgdavies** [comment]
Thanks for suggesting this. Fortunately the latest version of the OCDS docs that @Bjwebb has been working on updates the layout to include just this: see http://standard.open-contracting.org/1.1-dev/en/schema/reference/ 

This will go live in 1.1 (but not 1.0 unless we do a retrofit  1.0.3 release)

This is just things which are explicitly marked as 'required' in the schema (not the basic, intermediate, advanced information) which is not in the schema right now.
