### ISSUE TITLE
Rename initiationType to processType

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#456]
The terminology of [initationType is not very intuitive](http://standard.open-contracting.org/1.1-dev/en/schema/codelists/#initiation-type).

It exists as part of a legacy from the development of 1.0,  where we started thinking about how to model lots of different types of contracting process, but then narrowed down to procurement. 

However, the terminology chosen does not really capture what we want. 

There is therefore a suggestion to rename ```initiationType``` to ```processType``` and to update the codelist value 'tender' to 'procurement' to reflect that fact that we would still use all the same modelling and codelist value for, for example, a direct award within a contracting process (for which saying it was 'initiated' via a 'tender' does not always make sense).

**Comment by jpmckinney** [comment]
Closing - see reason in #434.
