### ISSUE TITLE
Linking to profiles and OC4IDS from documentation

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/standard#459]
Currently the standard documentation shows the following 

<img width="331" alt="screen shot 2017-05-18 at 1 01 23 pm" src="https://cloud.githubusercontent.com/assets/521705/26214417/5d4b9bd6-3bca-11e7-8187-db25ca081548.png">

It would be neat to add the PPP extension there, since it is an official one. It means we don't have to remember the link by heart ;p

**Comment by timgdavies** [comment]
Adding this to post 1.1, but a good idea for something we can add soon. There's a revised version of the extension documentation pages coming up imminently.

**Comment by jpmckinney** [comment]
@duncandewhurst The OCP website now has https://www.open-contracting.org/data-standard/profiles-and-guidance/ to which we will presumably add Infrastructure.

We can either:

1. Link to that page from `extensions.md`
1. Repeat its content
1. Move that page to the standard docs

Option 1 would be the quickest to do for 1.1.4, but we might prefer another option for 1.1.5.

Which option do you prefer for 1.1.4 and/or 1.1.5?

**Comment by duncandewhurst** [comment]
For 1.1.4, let's link to the page from `extensions.md`.

For 1.1.5, I prefer moving the page to the standard docs and making the page on the OCP website a stub with a link to the docs. If we repeat the content then we'd need to make updates in two places if, for example, we refined the profile descriptions or found that it was useful to provide other information on that page. If we link to the page (long term) then there is a risk that future updates to the OCP website could break the link.

Regarding OC4IDS, I'm not sure we would want to put it on the profiles page as I think it is important to make it clear to users that it is more than an adaptation of OCDS. We can consider in 1.1.5 how best to link to it from the OCDS documentation.

**Comment by jpmckinney** [comment]
`extensions.md` will be gone in the `extensionexplorer` branch, but we can link from where that content moved to (`extensions/index.md`)

Regarding OC4IDS, we named the page "Profiles and guidance" such that "guidance" can cover OC4IDS (to avoid introducing yet another term like "expansion").

**Comment by jpmckinney** [comment]
Keeping issue open to address:

> For 1.1.5, I prefer moving the page to the standard docs and making the page on the OCP website a stub with a link to the docs. If we repeat the content then we'd need to make updates in two places if, for example, we refined the profile descriptions or found that it was useful to provide other information on that page. If we link to the page (long term) then there is a risk that future updates to the OCP website could break the link.

**Comment by jpmckinney** [comment]
Closed by #1016. I created a "Linked standards" section for OC4IDS and Open Fiscal Data Package.

**Comment by duncandewhurst** [comment]
Once OC4IDS 0.9.2 is deployed we should include a link to the [guidance on including project identifiers in OCDS](https://standard.open-contracting.org/infrastructure/0.9-dev/en/guidance/identifiers/#project-identifiers-in-ocds)

**Comment by jpmckinney** [comment]
Please create a new issue as it is sufficiently distinct, then re-close this one.

**Comment by duncandewhurst** [comment]
> Please create a new issue as it is sufficiently distinct, then re-close this one.

https://github.com/open-contracting/standard/issues/1020
