### ISSUE TITLE
Multiple Organizations publishing data about the same process (OCID prefix)

### ISSUE THREAD

**Issue by juanpane** [open-contracting/standard#461]
In the case of Paraguay, the National Procurement Agency (DNCP) publishes information for the planning, tender, award and contract for the whole procurement process. DNCP uses as OCID prefix "ocds-03ad3f".

We are now starting working with the Ministry of Finance in Paraguay and since they have the payment information they will publish the implementation information (payment transactions) in their portal (which is different from the one from DNCP). In this scenario, the Ministry of Finance should ask of a prefix too. Having 2 prefixes, would make it impossible to have the same OCID, even if both institutions use the same national process ID.

What would be the best approach for tackling this? Are there any other experiences for this?

Several other countries in Latin America have the same scenario, including Argentina, Guatemala y possibly Mexico.

**Comment by andrewlorien** [comment]
Similar problem in Australia - the Department of Finance handles all planning, tenders, and awards for the whole of government.  But contracts are between the individual agency and buyer, and not centralised at all.

**Comment by timgdavies** [comment]
I think the idea would be for DNCP and Ministry of Finance to both use 'ocds-03ad3f' providing they agree that they will (a) suffix onto this the same national process ID; (b) not use any other potentially clashing suffixes.

In terms of the standard, we should then look at how to improve the definition and guidance around prefixes, to be less about 'publisher prefixes' and more about being prefixes for an 'identifier series'.

**Comment by duncandewhurst** [comment]
Noting that a variation on this question has come up in France, where:

* a single national portal publishes contracting data from procuring entities nationwide
* individual procuring entities may also publish data directly

In this case the question was whether the national portal and individual procuring entities should use the same ocid prefix

@ColinMaudry here's an issue on improving documentation relating to your question yesterday

**Comment by ColinMaudry** [comment]
I agree with @timgdavies: it's about a consistent series of identifiers, not about who publishes.

PS: I love this identifier sh*t :nerd_face:

**Comment by akuckartz** [comment]
Can URLs be used as identifiers please?

**Comment by jpmckinney** [comment]
@akuckartz Please open a separate issue.

**Comment by jpmckinney** [comment]
Merging into #364.
