### ISSUE TITLE
documentType codelist update for 'contractSchedule' required

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#473]
From @duncandewhurst at https://github.com/open-contracting/standard/issues/386#issuecomment-300540709

> The draft of 1.1 defines 'contractSchedule' as "Documentation setting out key milestones and schedules. Structured versions of this information may be modelled using the milestones block."
>
> However, I think this is (my) in error. This codelist entry should be interpreting schedule as 'annexe' not timeline or calendar.
>
> An updated definition for this term will be needed.

**Comment by timgdavies** [comment]
I'm staging an update with the following definition:

* contractSchedule - **Contract schedules** - "The contract schedules (sometimes referred to as annexes, attachment or appendix) are generally prepared alongside the core terms of the contract, and may provide additional detail on the goods, services or works that the contract covers."

@LindseyAM @jpmckinney Please can you confirm you are happy with this language for the definition of the contractSchedule document type.

**Comment by jpmckinney** [comment]
Grammatically, "attachments" and "appendices" should also be pluralized. Otherwise, looks good to me.

**Comment by LindseyAM** [comment]
We would want to include the concepts of appendix, annex, attachment, schedule, addendum etc etc so would recommend to define as "Any document which contains additional terms, obligations or information related to the contract, such as a schedule, appendix, annex, attachment or addendum."

**Comment by timgdavies** [comment]
Ok - so I'm going with "Any document which contains additional terms, obligations or information related to the contract, such as a schedule, appendix, annex, attachment or addendum." as @LindseyAM suggests.
