### ISSUE TITLE
Update the submissionMethod codelist

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#474]
In OCDS 1.1 we gave [definitions to the entries in the submission method codelist](https://github.com/open-contracting/standard/issues/322) but did not update this list to reflect a better researched list of submission methods.

This should be addressed in the next iteration of OCDS.

**Comment by jpmckinney** [comment]
This issue is fairly underspecified. Closing as doing research without evidence of demand/issues is too low priority. I haven't come across submission methods in EU or GPA requirements that are not covered by OCDS, for example.

We can re-open if there is some specific evidence.

**Comment by jpmckinney** [comment]
#322 has far more information and context, so re-opening that instead.
