### ISSUE TITLE
Command-line validation of data

### ISSUE THREAD

**Issue by robredpath** [open-contracting/standard#481]
On the community call on 2017-06-21 there were a number of questions around validation of large files, validation of API output and command-line validation. This is something that's a priority for us to make happen, so I'd love to hear from anyone who would benefit from this feature so that I can make sure that we fully understand the needs.

**Comment by timgdavies** [comment]
We're looking for community feedback on [the proposal to allow the software that runs the validator (CoVE) to run at the command line](https://github.com/OpenDataServices/cove/issues/207#issuecomment-309018015) 

We are hoping to work on this over the next month, with the likely first option being to:

* Maintain the current dependencies on Django, but provide a headless version that can be run in a python virtual environment

Views on whether this would be usable for you, or whether you have particular use-cases or deployment contexts where this would not work would be useful to help set priorities.

**Comment by mireille-raad** [comment]
Def. useful suggestion/tool ;p 

If this was to be translated to a command line, what would be the flags or parameters that you can pass? it might be good to start doing this thought experiment :). Maybe you can start getting community feedback on that... like how to validate for specific things, what types of inputs/outputs are expected...

If you want to go a one step further, it might be useful to build just a dummy command line interface and think thru the details and ask people to use it and see if it is ok...you can also output randomized error messages....  it would help surface the famous user needs and people can give you more tangible feedback and you think it through a little bit more.

**Comment by timgdavies** [comment]
There is work-in-progress on allowing the online validator to also run on the command line [in this branch of the underlying CoVE tool](https://github.com/OpenDataServices/cove/blob/749-command-line/README.rst#command-line-interface) 

More on draft output that will give soon....

**Comment by Bjwebb** [comment]
This is now merged into the master branch - https://github.com/OpenDataServices/cove/blob/master/README.rst#command-line-interface

**Comment by jpmckinney** [comment]
Merged and therefore closed.
