### ISSUE TITLE
Should duplicate entries be permitted in the tenderers array?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#491]
Currently the schema doesn't specify whether duplicate entries are permitted in the ```tender/tenderers``` array. 

This question arises when a single organization submits multiple bids.

The bids extension allows details of individual bids (with associated tenderers) to be disclosed, however it's not clear how ```tender/tenderers```, which is part of the core standard, should be populated in this scenario.

It's worth bearing in mind that counting the entries in ```tender/tenderers``` doesn't give an accurate view of the number of bids, since multiple organizations could submit a single bid.

Seeking views from data users on whether duplicate entries in the ```tender/tenderers``` would be preferable when a single organization submits multiple bids?

**Comment by timgdavies** [comment]
The definition of this field is currently:

> "All parties who submit a bid on a tender. More detailed information on bids and the bidding organisation can be provided using the optional bid extension."

It is paired with:

```numberOfTenderers``` defined as:

> "The number of parties who submit a bid."

I read from this that there should not be duplication in the ```tenderers``` array. 

Duplication would also not work when merging in OCDS 1.1, as the duplicated entries would have the same ```id```, and so would be collapsed into one when merging anyway.
