### ISSUE TITLE
Can we remove make_field_definitions.py

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#506]
I believe [make_field_definitions.py](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/utils/make_field_definitions.py) is no longer used in the build process, as our new sphinx directive removes the need to rely on intermediate CSV files.

However, it is still present in the builds scripts and babel process.

@Bjwebb Is it safe to remove this in the 1.1.1?

**Comment by Bjwebb** [comment]
Yes, should be safe to remove this.

**Comment by timgdavies** [comment]
Ok. I'll do that shortly.
