### ISSUE TITLE
have a friendly TLDR version of contributing.md

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/standard#507]
I was creating an issue and noticed the link for contributing... it is nice and necessary... but it would be great to create a TLDR; or maybe some user friendly bullet point list summarizing the legal jargon. 

Digital Ocean has some great example on how to do this on  https://www.digitalocean.com/legal/terms/ 

Here are some screenshots to demonstrate 

![screen shot 2017-07-23 at 10 38 53 am](https://user-images.githubusercontent.com/521705/28497575-49bb47b8-6f93-11e7-8094-b05494cefc99.png)

![screen shot 2017-07-23 at 10 39 33 am](https://user-images.githubusercontent.com/521705/28497578-64724aac-6f93-11e7-8c77-25f2510fe7ab.png)

**Comment by timgdavies** [comment]
Good idea. In practice the contributor agreement is really for code contributions - but the fact it is displaying for issues could be a bit off-putting. 

I've had an issue internally open to look at https://cla.github.com/ to see if we could even streamline our Contributor Agreement a bit more.

@jpmckinney might have thoughts on this.

**Comment by jpmckinney** [comment]
I think we can move `CONTRIBUTING.md` to another path (maybe `CONTRIBUTOR-AGREEMENT.md`), and instead add briefer language to `CONTRIBUTING.md` while referencing the agreement. This would also give an opportunity to give more direction as to what makes a good issue / bug report.

**Comment by mireille-raad** [comment]
Maybe use `Contributor-License-Agreement.md` or `CLA.md` (CLA seems to be the abbreviation of choice...) - a `legal.md` could also do.

The [contributing on tensorflow](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) is a good example imho... 

There is a CLA for corporate and another for individuals btw... I noticed this is the same for Apache, Google etc

Apache
https://www.apache.org/licenses/
https://www.apache.org/licenses/icla.pdf
https://www.apache.org/licenses/cla-corporate.pdf

Google
https://cla.developers.google.com/about/google-individual?csw=1
https://cla.developers.google.com/about/google-corporate?csw=1

funny how this quickly got complicated

**Comment by Bjwebb** [comment]
Very much in favour of moving the legal agreement to another path.

Our CoVE repo is another example of what a friendlier CONTRIBUTING.md could look like https://github.com/OpenDataServices/cove/blob/master/CONTRIBUTING.md.

**Comment by jpmckinney** [comment]
For now, I'm renaming the file to CLA.md in #785.

I haven't heard more demand from a CONTRIBUTING.md, and so far we haven't had a problem with the quality of the issues and PRs being submitted, so closing.
