### ISSUE TITLE
is search not working or is it me?

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/standard#508]
I tried to use search on standard.open-contracting.org 

i noticed it doesn't work from phone, laptop (2 browsers: chrome and opera) and from 2 different locations.

Is it me or something is up?

here is my console log:

![screen shot 2017-07-23 at 10 43 04 am](https://user-images.githubusercontent.com/521705/28497591-c2d4e8ac-6f93-11e7-891d-791805430f7f.png)

**Comment by timgdavies** [comment]
This seems to be an issue for me to. Tagging @Bjwebb to explore

**Comment by Bjwebb** [comment]
Fixed in the source repo, will be updated on the live site shortly.

**Comment by Bjwebb** [comment]
Fixed now on http://standard.open-contracting.org/latest/en/
