### ISSUE TITLE
Requirements for 1.1.1 to be ready

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#510]
* [x] Write changelog
* [x] Update schema id values to "id": "http://standard.open-contracting.org/schema/1__1__1/release-schema.json"

**Comment by timgdavies** [comment]
@Bjwebb I've hit the chicken-and-egg problem again with changing the schema id, as this breaks the documentation build (which wants to find a schema at "http://standard.open-contracting.org/schema/1__1__1/release-schema.json") to build docs for release-package-schema. 

Ideas for a good workaround?

**Comment by Bjwebb** [comment]
Does ref resloving need to work, or does it just need to not fail? (I think the sphinx docs don't actually display fields across ref boundaries, although the javascript widgets do). If it just needs to not fail, I can configure JSONRef to return empty dictionaries for remote refs.

**Comment by timgdavies** [comment]
I think you are right - let's try with it just not failing.

**Comment by Bjwebb** [comment]
This needs updating in sphinxcontrib-jsonschema. Here's a new commit to use for that: b7332e8fd5c788ee59b983396102ddc38967a3d0
