### ISSUE TITLE
Ensure versioned-release-validation-schema.json in extensions is up-to-date

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#517]
Either:

* delete the file if it's used for nothing
* document how to generate it manually, then automate and test for it like this repo does

Originally reported: https://github.com/open-contracting/ocds-riskAllocation-extension/issues/7

At least one extension (riskAllocation) has an out-of-date versioned-release-validation-schema.json that conflicts with the other schema.

**Comment by jpmckinney** [comment]
Unless it's used for nothing, I'd push the "document how to generate it manually" upward in priority (especially as I assume documenting an operation that has occurred many times shouldn't be long or difficult).

**Comment by timgdavies** [comment]
I've never generated a versioned-release-validation-schema for an extension when hand-writing extensions.

It's possible these come from the [extension creator tool though](https://open-contracting.github.io/extension_creator/) 

Tagging @kindly and @duncandewhurst for views. 

My understanding through is that no tools are then using versioned-release-validation-schema.json

**Comment by duncandewhurst** [comment]
Yes, the extension creator generates a versioned-release-validation-schema.

For some extensions, the release-schema will have subsequently been edited outside of the extension creator, so the versioned-release-validation-schema will be out of sync.

The extension creator could be used as part of a manual process to update the versioned-release-validation-schema after each update to the release-schema.

We could also do this as a one off process across all the extensions to get everything in sync and add the versioned-release-validation-schema where missing.

My understanding re: use of the versioned-release-validation-schema was the same as Tim's.

**Comment by jpmckinney** [comment]
Has anyone done this programmatically? It looks like I can rig something up in Node using https://github.com/open-contracting/extension_creator/blob/gh-pages/make_validation_schema.js

**Comment by timgdavies** [comment]
I've only use the python script in the main repo against the main schema. 

A node process across all the repos would be good stop-gap, but I guess we should review whether or not this should really be part of an extension before putting effort there? Perhaps a topic for 3rd August meeting?

**Comment by jpmckinney** [comment]
Sounds good - we can put this issue on the agenda.

**Comment by jpmckinney** [comment]
In general, I'd like to add to the agenda: starting an effort (if not existing already) to document all the maintenance/publication workflows leading to new versions of schema and documentation, and what tools we need/want to automate as much as possible.

**Comment by jpmckinney** [comment]
We didn't get around to chatting about this, but I'll add that if we choose to remove the file, we should also edit [standard_extension_template](https://github.com/open-contracting/standard_extension_template).

**Comment by jpmckinney** [comment]
Since we didn't get around to talking about this issue on Thursday, we should pick up the conversation here or in a scheduled call. I don't think we should be releasing incorrect `versioned-release-validation-schema.json` files in any extensions, so should either update them or delete them.

**Comment by timgdavies** [comment]
Pinging @kindly for a view on this and to confirm if there is any reason `versioned-release-validation-schema.json` should not be removed.

I think a wider call on next-step technical strategy for extensions in later August/early Sept would be useful.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/standard-development-handbook/issues/19
