### ISSUE TITLE
Add Milestone.period field (date interval)

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/standard#523]
I just saw a use case in which `tender/milestones/dueDate`  is actually a date interval (with startDate and endDate).

I wonder if this normal or if you ever saw it elsewhere. are there any recommendations on how to publish this? (my guess would be to use the biggest date as the OCDS dueDate)

**Comment by timgdavies** [comment]
I've not encountered this before. As dueDate is a simple date-time, and not a [period](http://standard.open-contracting.org/latest/en/schema/reference/#period) object, we unfortunately don't get the automatic benefit of the 1.1 distinction between ```endDate``` and ```maxExtentDate```.

Whether the earlier or later date (or a mid-point) should be used does depend on context I think.

For example, for a milestone about when a tender is going to be released, using the earliest date might make sense for people planning when they should prepare to review the tender and look at applying.  But for a delivery milestone, that an organisation will be penalised for exceeding, the latest date might be most appropriate.

The additional information that the date is a range could be placed in the milestone ```description``` field.

**Comment by mireille-raad** [comment]
ha! thanks a lot for the super detailed answer and clarification.

I'll try to get some more information on why the dueDate is this way... if there is some insight to be gained, i'll open/share in a ticket... closing the issue for now.

**Comment by jpmckinney** [comment]
`milestones` ends up being used for any date information that can't go in the other `date-time` and `Period` fields serving more common use cases like submission periods, etc.

In GPA, there is a "time-frame for delivery of goods or services", suggesting a period, and 'delivery' is indeed a `milestoneType` defined as "For delivery milestones, such as the date when a good or service should be provided." It indeed seems reasonable for delivery dates to be declared as periods.

**Comment by jpmckinney** [comment]
(Expanding on my earlier comment.)

## Motivation

The [Revised Agreement on Government Procurement](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm) (GPA) includes: "each notice of intended procurement shall include … e. the time-frame for delivery of goods or services or the duration of the contract".

The European Union is a [party](https://www.wto.org/english/tratop_e/gproc_e/memobs_e.htm) to the GPA, yet its [Directive 2014/24/EU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.094.01.0065.01.ENG) (Public contracts — setting out clear ground rules) has nothing regarding "the time-frame for delivery of goods or services" only "the duration of the contract". I suppose the EC considered the GPA requirement to be *either* the time-frame for delivery of goods or services *or* the duration of the contract, and not *and/or*.

Anyhow, the GPA allows for deliveries scheduled for periods. In OCDS, we have a `milestypeType` code of 'delivery' (Delivery milestones) defined as "For delivery milestones, such as the date when a good or service should be provided." So, there is a motivation for allowing periods in milestones.

## Proposal

Add a `period` field to `Milestone`. A technical note should say that a Period object MUST have at most one of the `dueDate` and `period` fields.

We can consider deprecating `dueDate`, but it's not an immediate concern. If there's initial agreement to the proposal, I will author an extension for 1.1, which would be scheduled for inclusion in 1.2.

**Comment by duncandewhurst** [comment]
Would the semantics of the new field be the period in which the milestone is due?

We have seen publishers use milestones to represent periods, for example, when a tender has more than one enquiry period, they disclose one period in `tender.enquiryPeriod` and use separate milestones to represent the start and end dates for the other period. Would we recommend they use the new field instead?

> Add a `period` field to `Milestone`. A technical note should say that a Period object MUST have at most one of the `dueDate` and `period` fields.

I think this should read "... a `Milestone` object MUST...".

**Comment by jpmckinney** [comment]
I think the semantics are when the milestone is due, specifically for the case of "time-frame for delivery of goods or services". 

For example, let's say you want weekly deliveries of milk, but are flexible whether they arrive Sunday or Monday, so you set a two-day window. You wouldn't want to set only a due date, as the supplier could deliver your annual shipment all at once.

Having said that, instead of a period, we can consider just adding a "not before" date (we can find an appropriate term), and that way we retain `dueDate`.

> I think this should read "... a Milestone object MUST...".

Indeed, though maybe not an issue if we change the proposal as above.

**Comment by duncandewhurst** [comment]
> I think the semantics are when the milestone is due, specifically for the case of "time-frame for delivery of goods or services".

That makes sense to me, so for the example from https://github.com/open-contracting/standard/issues/793#issuecomment-448226849 of disclosing the period of an auction, the guidance would be to use two milestones: one for the start of the auction and one for the end.

> Having said that, instead of a period, we can consider just adding a "not before" date (we can find an appropriate term), and that way we retain `dueDate`.

That would remove the need for the technical note and I think it would reduce the potential for confusion about using milestones to represent periods.

I looked for terms to reuse from [other standards](https://lov.linkeddata.es/dataset/lov/) and the [glossary crosswalk](https://docs.google.com/spreadsheets/d/1Nh_HjyYuNk8wuu_Tb0kcPDyV6j8pAMgXqJ3MgwpXZjQ/edit?skip_itp2_check=true#gid=1270974696) but I didn't find any. We could use `dueAfterDate` but I don't particularly like it.

As mentioned in your proposal, another option is to deprecate `dueDate` and add a period object its place, e.g. `due` or `duePeriod`. What do you think?

**Comment by duncandewhurst** [comment]
@jpmckinney do you have a preference between adding `dueAfterDate` or deprecating `dueDate` and adding a `Period` object in its place, e.g. `due` or `duePeriod`?

**Comment by jpmckinney** [comment]
I prefer `dueAfterDate` as having loads of deprecated fields is not great for standardization. We can have guidance that if there is a timeframe for delivery, the `dueAfterDate` and `dueDate` can be used as start/end – after which it is past due.

`dueDate` already has the semantics of "due before date" or "due on date", so `dueAfterDate` sounds like a good term.
