### ISSUE TITLE
Add Address.country field (with ISO3166-1 alpha-2 codelist)

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#524]
From workshop in Kiev:

We use address from schema.org - we need country code as well for some use cases.

Follow up with @myroslav.

**Comment by PaulBoroday** [comment]
Could something like this be considered as a solution to the problem of codifying and detailing string data in the address?

```
{
  "address": {
    "streetAddress": "",
    "postalCode": "",
    "country": {
      "scheme": "iso-alpha2",
      "id": "UA",
      "description": "Ukraine",
      "url": ""
    },
    "region": {
      "scheme": "iso-alpha2",
      "id": "UA-12",
      "description": "Dnipropetrovska oblast",
      "url": ""
    },
    "locality": {
      "scheme": "UN/LOCODE",
      "id": "UA-DNK",
      "description": "Dnipro",
      "url": "https://service.unece.org/trade/locode/ua.htm"
    }
  }
}
```

**Comment by jpmckinney** [comment]
The [location](https://github.com/open-contracting/ocds_location_extension) extension has the concept of a gazetteer, which might be relevant here.

We don't want to over-complicate the specification of addresses, but we could add a separate way to specify geographic codes and schemes.

Changing existing fields would be backwards-incompatible, and few systems presently use schemes to control possible values.

**Comment by PaulBoroday** [comment]
Yes It might works, but ASAICS this extension relates only for item and it’s place of delivery. And I’m mostly talking about parties addresses

**Comment by timgdavies** [comment]
Given ISO-Alpha2 is generally sufficient for most needs, I don't think we would need the option for multiple schemes, and so the simplest approach would be to include `countryCode` alongside `country` in the address. 

I note that schema.org [address country](https://schema.org/addressCountry) is agnostic as to whether their `addressCountry` field should be a code or string, but as we have use-cases for the OCDS `country` field where this might be used to generate the address on an envelope etc, we would want the separate code field. 

In terms of the region and locality break-downs given in the example:

(1) From the perspective of what OCDS might recommend that publishers provide in future, I can't imagine us recommending this information is included 'by default' in OCDS - as this should be information that can be extracted by geocoding a dataset;

(2) Where a publisher does want to include this information (e.g. to share geocoding they have already done), then I would suggest that this is explicitly flagged under a specific property (e.g. `location`) which could be based on the location object from the location extension.

For example:

```json
{

   "streetAddress": "",
    "postalCode": "",
    "country": "Ukraine",
    "countryCode":"UA",
    "location": [
        {
               "description":"Dnipropetrovska oblast",
               "gazetteer":{
                  "scheme":"iso-alpha2",
                  "identifiers":["UA-12"]
               }
         },
        {
               "description":"Dnipro",
               "gazetteer":{
                  "scheme":"UN/LOCODE",
                  "identifiers":["UA-DNK"]
               }
         }
     ]
} 
```

Notes

* I'm not sure 'location' is the correct name for this property. Would need to work on defining it more to make sure we have the right term.
* The schemes above would need entering into the gazeteer codelist, and codes might change.

**Comment by jpmckinney** [comment]
All sounds good.

@PaulBoroday If you want to pursue the idea of an extension for geographic identifiers, could you create a new issue? That way, we'll keep this issue narrowly scoped to just being about the country code.

**Comment by PaulBoroday** [comment]
@jpmckinney done: [addressDetails - the way to disclose more](https://github.com/open-contracting/standard/issues/739) ;)

**Comment by jpmckinney** [comment]
As part of this issue, we can add a codelist for ISO-3166-1 alpha-2.

**Comment by ColinMaudry** [comment]
I'm working on an extension that adds `countryCode` to `Address`.

@jpmckinney Do we want it to rely on an explicit codelist (ISO3166-1 alpha-2 list) or just document that the field expect a ISO3166-1 alpha-2 code?

Edit: ah I see you added the "Codelist - Open" label. It's consequently going to be an explicit codelist, but with the possibility to specify other codes (such as alpha-3 codes).

**Comment by ColinMaudry** [comment]
It's going to be here: https://github.com/open-contracting-extensions/ocds_countryCode_extension

**Comment by jpmckinney** [comment]
I left it open so that the codelist only contains the "officially assigned" codes, but users can still use user-assigned codes like XK for Kosovo.

Alternately, we can made it a closed codelist that includes only officially assigned and user-assigned codes.

**Comment by ColinMaudry** [comment]
Should the country codes be in capital letters? I see that OCDS codelist of currencies is in capital letters. Are lower-case values accepted?

We could close the list to make the data entry stricter, and update the list if we hear of the need to extend it. In this case, are there other codes than XK that I should be aware of that are not in the standard list?

**Comment by jpmckinney** [comment]
Yes, all-caps, like the ISO standard.

For the list, let's include all "officially assigned" and all "user-assigned" codes, as use of those is conformant with the ISO standard.

**Comment by jpmckinney** [comment]
Actually, let's keep it to officially assigned plus XK, as I can't find evidence of other user-assigned codes being consistently used to identify countries: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#User-assigned_code_elements

**Comment by fmatzdorf** [comment]
We support the inclusion of the countryCode field in 1.2.

**Comment by jpmckinney** [comment]
To avoid introducing a pattern of prefixing field names with object names (`countryCode`, `countryName`), we can either:

1. Add a `country` object with sub-fields like `code` and `name`
1. Add a `country` field whose value must be an ISO 3166-1 alpha-2 code, and deprecate `countryName`.

I prefer the second option, because OCDS isn't the place to annotate a country with additional information like its human-readable name. Rather, it should just provide the code, which can be looked up in other tables/systems for name translations, population counts, etc.

**Comment by fmatzdorf** [comment]
We are working on displaying contract information in multiple languages, so option 2 would work best for us.

**Comment by ColinMaudry** [comment]
eForms uses country codes for organizations address ([link to our glossary crosswalk](https://docs.google.com/spreadsheets/d/1Nh_HjyYuNk8wuu_Tb0kcPDyV6j8pAMgXqJ3MgwpXZjQ/edit#gid=202916689&range=25:25))

**Comment by duncandewhurst** [comment]
Reopening as I noticed that the description of `country` erroneously links to the language codelist.
