### ISSUE TITLE
Header in 1.1 documentation displays 1.0 on smaller viewports

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#525]
![image](https://user-images.githubusercontent.com/19265814/28880636-958bd4c0-779d-11e7-8db9-755bab03bba1.png)

**Comment by Bjwebb** [comment]
This is fixed now in the theme repo, and I've rebuilt these dev branches:
http://standard.open-contracting.org/1.1-dev/en/
http://standard.open-contracting.org/1.1.1-dev/en/
