### ISSUE TITLE
Implementation levels text is in need of review

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#527]
https://github.com/open-contracting-archive/mapper

I'd also like to review what in `open-contracting-archive` can be deleted (or in a few cases where there is just a README, backed up as historical in Google Drive), and what in `open-contracting` can be archived or deleted (we have some early work that doesn't belong).

**Comment by timgdavies** [comment]
The text in levels.md could do with a more thorough-going re-write, but that is blocked currently by decisions about publication levels etc. 

I'm generally against deleting from the archive - as the point of an archive is to make sure links stay active, and that anyone who does want to access that content can. It should just clearly be marked as outdated.

**Comment by timgdavies** [comment]
Updating title to reflect wider issue. 

Specific issue that led to issue was reference to https://github.com/open-contracting-archive/mapper in the levels.md file.

**Comment by jpmckinney** [comment]
I don't have admin on open-contracting-archive in order to see traffic graphs, but I'd be surprised if anything relevant links to ocdata-blend and some others. Anyway, I'm more keen on archiving more things from open-contracting (e.g. the historical ocds_upgrade_* repos, and any old and unused repos unchanged since 2014 or 2015) than on deleting anything.

**Comment by timgdavies** [comment]
I've just invited you to the archive repo. 

Yep - the ocds_upgrade_* repos can be archived safely I believe.

**Comment by jpmckinney** [comment]
Archival is continued in #529

**Comment by jpmckinney** [comment]
Fixing the link to mapper is continued in https://github.com/open-contracting/standard/issues/409

Updating this page's text is continued in https://github.com/open-contracting/standard/issues/388
