### ISSUE TITLE
Make publicationPolicy a required field

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#528]
Currently the ```publicationPolicy``` field in the [release package schema](http://standard.open-contracting.org/latest/en/schema/release_package/) is not a required field.

We advise all publishers to provide a publication policy to explain how they produce OCDS data and the choices they have made in doing so.

Is there any reason we shouldn't make ```publicationPolicy``` a required field so that it's absence is picked up by the validator?

**Comment by jpmckinney** [comment]
One reason would be backwards-incompatibility.

**Comment by timgdavies** [comment]
I think two issues here:

(1) Should it be a schema change? That would need to wait for 1.2 (as would any schema change... this is implied in the question)

(2) Should we get the validator to report on it (that could be an additional check we layer in)

My view is that we should look at (2) in any case, as (1) is further away, and we want to make sure we're picking up missing publication policies sooner (and possibly also checking the URL provide to be sure it does not 404)

**Comment by Bjwebb** [comment]
As a schema change, it would not be backwards compatible, so waiting for 2.0, rather than 1.2.

**Comment by jpmckinney** [comment]
Closing in favor of reconsidering more broadly, as part of 2.0, whether to move more toward a 'hard compliance' approach, and depending on how far we choose to go, to then decide which fields (like this one) ought to have additional validations.
