### ISSUE TITLE
JSON example formatting is degraded in 1.1

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#533]
We have a javascript library in the documentation which:

(a) Folds JSON examples, and then expands just the leaves of interest;
(b) Collects together multiple examples, and provides a drop-down box to choose between them;

This currently works in 1.0 by taking the contents of a custon JSONInclude directive as below:

```
.. jsoninclude:: docs/en/examples/contract.json
   :jsonpointer: /releases
   :expand: releases, tender, awards, contracts, period, value, items, tag, parties, documents
```

and then adding information to the class of the ```LiteralInclude``` block, which is then picked up by the 'json-example-format.js' script to apply the 'renderjson' plugin with appropriate folding to the block, and to enable to drop-down selector to choose which example to display.

In version 1.1, possibly due to an updated version of Sphinx, the classes set by the ```JSONInclude(LiteralInclude)``` module are not carried through into the generated HTML, meaning this enhancement no longer works.

This can be seen by comparing the example on the getting started page for [1.0](http://standard.open-contracting.org/1.0/en/getting_started/) (working) and [1.1](http://standard.open-contracting.org/latest/en/getting_started/) (not working)

I've looked to see if I can work out why this is, but I can't work it out. 

I think we either need to:

(a) Get the classes passing through as they were in 1.0;

(b) More substantially refactor this directive so that it puts out this information in "data-" attributes, and the script picks them up from there (as the class thing was a big of a hack)

Assigning to @Bjwebb in the first instance, as I think you made the upgrade to Sphinx and might have an idea of whether (a) is possible.

**Comment by Bjwebb** [comment]
Looks like we can use a container node to pass through the classes: https://github.com/open-contracting/standard/commit/520afec26ad3afc7164283df8bfe1af78c6e695d

1.1-dev now works http://standard.open-contracting.org/1.1-dev/en/getting_started/
