### ISSUE TITLE
Links in the schema viewer are displayed in an iframe

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#537]
When you click a link in the [schema viewer](http://standard.open-contracting.org/latest/en/schema/release/) the destination is displayed in an iframe:

![image](https://user-images.githubusercontent.com/19265814/29070214-32c0c98e-7c36-11e7-8bc4-cad063e960f2.png)

I think the correct behaviour here is to take you to the destination in the main browser window.

I believe this is a new issue in 1.1.1, since I previously noticed issue #501 by looking at what was displayed in the address bar which you can't do now that the links are displayed in an iframe.

**Comment by Bjwebb** [comment]
I can reproduce the issue for 1.0 also: http://standard.open-contracting.org/1.0/en/schema/release/

Is it possible you previously opened the links in a new tab?

**Comment by duncandewhurst** [comment]
> Is it possible you previously opened the links in a new tab?

I didn't think so, but I may well have done!

**Comment by duncandewhurst** [comment]
Fixed in https://github.com/open-contracting/standard/pull/540 (thanks @Bjwebb)
