### ISSUE TITLE
Move repositories to appropriate organizations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#541]
Move to OpenDataServices:

* [x] https://github.com/open-contracting/json-merge-patch

Move to open-contracting:

* [x] https://github.com/OpenDataServices/ocds-faker

Remove?

* [x] https://github.com/OpenDataServices/OCDSExtensionCreator

Continuing from #529

**Comment by timgdavies** [comment]
@kindly could you please move json-merge-patch to opendataservices, and check if (and update if true) https://github.com/OpenDataServices/OCDSExtensionCreator can be removed. 

@edugomez please could you take a look at moving ocds-faker to the open-contracting repo

Thanks both :)

**Comment by jpmckinney** [comment]
@kindly Please move https://github.com/open-contracting/json-merge-patch to the OpenDataServices GitHub organization. Just go to https://github.com/open-contracting/json-merge-patch/settings It should take 1 minute.

@timgdavies You suggested in #529 the removal of https://github.com/OpenDataServices/OCDSExtensionCreator from GitHub?

**Comment by timgdavies** [comment]
I've moved json-merge-patch and removed OCDSExtensionCreator.

**Comment by jpmckinney** [comment]
Hmm, I still see json-merge-patch at https://github.com/open-contracting/json-merge-patch but not at https://github.com/OpenDataServices/json-merge-patch ?

**Comment by timgdavies** [comment]
Sorry - my mistake. Missed confirming if when I looked this before.
