### ISSUE TITLE
How to know at what stage is a contracting process?

### ISSUE THREAD

**Issue by yank07** [open-contracting/standard#543]
Hello all!

We are using the API of the OCDS in Paraguay, we have a question of knowing the stage of a contracting process giving a compiled release of the contracting process.

We could, for sure, infer that if a compiled release has the tender object  not empty, the giving contracting process are at least in the tender stage. Querying all the other stage objects we could know the real stage of the contracting process.

There is a property _status_ in tender, award and contract so we can know the mid stage in the each stage individualy. 

It wil be great to have a status property for the compiled release or record package too.

**Comment by mireille-raad** [comment]
is the "Release Tag" field not helpful? 
http://standard.open-contracting.org/latest/en/schema/codelists/#release-tag

**Comment by duncandewhurst** [comment]
In a `compiledRelease` the `tag` field should be set to `compiled`, so this wouldn't indicate the current stage of the process.

However, you can use the [`releases`](http://standard.open-contracting.org/latest/en/schema/records_reference/#release-list) section of an OCDS record to determine the stage of the process from the most recent release by using the `tag` field.

For example, in [this record](https://github.com/open-contracting/sample-data/blob/master/real-examples/paraguay/sample/records/273637.json) from Paraguay the most recent release has the `contract` tag:

```json
  "records": [
    {
      "ocid": "ocds-03ad3f-273637",
      "releases": [
        {
          "date": "2015-02-09T14:22:32-05:00",
          "tag": [
            "planning"
          ],
          "url": "https://www.contrataciones.gov.py/datos/id/planning/273637-provision-montaje-equipos-rectificadores-accesorios.json"
        },
        {
          "date": "2015-02-17T11:22:57-05:00",
          "tag": [
            "tender"
          ],
          "url": "https://www.contrataciones.gov.py/datos/id/tender/273637-provision-montaje-equipos-rectificadores-accesorios-banco-bateria-acondici.json"
        },
        {
          "date": "2016-09-07T10:26:55-04:00",
          "tag": [
            "award"
          ],
          "url": "https://www.contrataciones.gov.py/datos/id/award/273637-provision-montaje-equipos-rectificadores-accesorios-banco-bateria-acondicionadores-1.json"
        },
        {
          "date": "2016-06-28T12:00:00-04:00",
          "tag": [
            "contract"
          ],
          "url": "https://www.contrataciones.gov.py/datos/id/contract/273637-infocenter-s-a-1.json"
        }
      ],
```

**Comment by jpmckinney** [comment]
Closing as the question seems to be answered.
