### ISSUE TITLE
Add more documentation tests

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#544]
We can add tests to ensure the following works:

* [x] Search box
* [x] Community [extensions](http://standard.open-contracting.org/latest/en/extensions/) table
* [ ] [Examples](https://standard.open-contracting.org/latest/en/getting_started/releases_and_records/) (expand tests for `json-example-format.js` in `test_docs.py`)
* [ ] Docson, e.g. [Release Schema](http://standard.open-contracting.org/latest/en/schema/release/)
* [ ] Tests for `extensions.js`
* [ ] Sphinx directives

All the above should work in all languages and be translated, in particular [Sphinx directives](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/technical/#test-translations). Schema and codelist files should be translated.

The following tests may be able to be implemented as Travis cron jobs against live URLs:

* [ ] Version switcher
* [x] Language switcher
* [ ] Alert for latest version of documentation

The Travis cron jobs have not been set up yet.

**Comment by Bjwebb** [comment]
Some of these can be tested against the Travis build:
- [x] Search box
- [x] Community [extensions](http://standard.open-contracting.org/latest/en/extensions/)
- Examples, e.g. [Getting Started](http://standard.open-contracting.org/latest/en/getting_started/)
- Docson, e.g. [Release Schema](http://standard.open-contracting.org/latest/en/schema/release/)

Some can only be tested against the actual deploy of the docs:
- Version and language switchers
- Alert for latest version of documentation

**Comment by jpmckinney** [comment]
Ok, let's make the issue about what's possible with the Travis build.

**Comment by Bjwebb** [comment]
I was most of the way through writing a test of the language switcher before I realised it wouldn't work.

I've commited the test, which will be skipped by default, but will run if you specify a live url to test, e.g.:
```shell
CUSTOM_SERVER_URL='http://standard.open-contracting.org/1.1/' py.test test_docs.py
```

We should be able to set up tests like that to be run with travis cron, against the live site.

**Comment by jpmckinney** [comment]
While more tests are always good, we haven't had failures related to these features in a long while – except for Docson not loading when I upgraded it, which is an obvious case to test manually. So, closing as the issue is unlikely to be worked on.
