### ISSUE TITLE
Asset building block after implementation stage

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/standard#564]
I was wondering how to model assets.

If at the end of the project, the contract results in a new "asset", is there a way to model this?

I looked at the building blocks again, the closest thing i could find is an item. An asset could be multiple items or things like a building, a website, a report which is the product of a consulting service. etc...

So is there any extension for assets? how do you recommend it is modeled ?

![screen shot 2017-09-07 at 12 07 24 pm](https://user-images.githubusercontent.com/521705/30146932-2c489d4c-93c5-11e7-96df-92990e29b616.png)

**Comment by LindseyAM** [comment]
In places that practice 'supply chain management', in addition to planning, procurement & contract management, there may be stages relating to asset management (logistics) and/or disposal. So, if the procurement results in eg vaccines, that there would be a system to track that those medicines are shipped/store/inventory managed properly and that they are used up/disposed of/sold properly. Currently, these aspects of SCM are outside the scope of OCDS, but it is possible that extensions could be developed. @dc-coder what is it that you/Bandung want to do with the 'asset' information?

**Comment by mireille-raad** [comment]
thank you @LindseyAM  for the other example you shared....it is a very interesting one.
As for what we want to do, after the system in the city of bandungs processes a contract, if there is an asset, 2 things need to happen:

- Information about the asset need to be sent to the national govt.
- There is an asset management system in bandung that takes over management of the data and further contracts like maintenance etc.

I do think that an extension would be ideal, simply because it is not a consistent block in all the contracting processes. 

If there is a quick suggested building blocks that the team has done already, I am happy to re-use. If not i will share in this issue what we end up modeling.

**Comment by LindseyAM** [comment]
Thanks @dc-coder !

**Comment by jpmckinney** [comment]
As @LindseyAM wrote, management of assets (e.g. snowplows) and supplies (e.g. computers) are somewhat orthogonal to contract management. In future, there can perhaps be links from contracting systems to asset/supply systems, but to my knowledge such links are rare, and assets/supply systems are much less frequently open. Closing until such links become a real possibility.
