### ISSUE TITLE
Structured amendment information

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#575]
#357 removed the limited structure from `amendments` in OCDS.

However, amendments exist as structured data in Kyrgyz's e-GP system, and this structured data is useful and valuable. In OCDS, if we were to use only what’s available in the core standard, we would need to transform Kyrgyz’s structured data into text and put it in the `description` field. Their structured data may be possible to rebuild by programmatically comparing the changed values (amounts, dates, etc.) across releases, but that would be an overly difficult process for recovering the structured data.

**Comment by timgdavies** [comment]
Can you give an example of the Kyrgyz structure data? 

The [updated approach to amendments](http://standard.open-contracting.org/latest/en/implementation/amendments/) narrows our model to just using publication of 'before' and 'after' values using multiple releases in a single package. 

For organisations who have only the delta stored, then they would need to reconstruct the before release. But I would suggest this is preferable to re-introducing a different way of presenting structured amendment information that puts the burden of reconstructive past values on the user.

**Comment by jpmckinney** [comment]
The system is at https://trade.okmot.kg/ but it requires a long, formal registration process.

There are at least two uses cases here, and each creates a burden on the user of the data.

If a user wants to answer, "What did the tender notice look like at time X?", then the current approach is the least work.

If a user wants to answer, "What is the history of amendments to the contracting process?", then the Kyrgyz system's modeling approach is the least work.

I tend to believe there are more cases of the latter.

**Comment by jpmckinney** [comment]
Anyhow, I would have to double-check whether Kyrgyz tracks additional data elements outside what is available in `amendments` or expressible as literal value changes over time. The extension would be to satisfy those additional requirements (if any), and would otherwise be a simultaneous and alternative way of expressing amendments.

Noting that the release process (and its interaction with amendments) should likely be incorporated into OCDS' conformance statement, as using releases properly is rather important.

**Comment by jpmckinney** [comment]
No interest has been expressed in this issue, so closing in favor of having a single means of expressing amendments.

**Comment by yolile** [comment]
Reopening this as DNCP from Paraguay showed interest. 

Currently another use case that is hard to resolve is answer the question "how much is the difference between the original contract amount and  the amendment contract amount?" 
And visualizations like this one:
![image](https://user-images.githubusercontent.com/6834122/77325134-29f28f80-6cee-11ea-9b19-0019f5eefc10.png)
https://www.mopc.gov.py/mopcweb.old/BM1/payviz/#/ 
Are also hard to do with releases as itself.

Currently if you want to answer that question you have to look at all the releases and contract.value and do the math, and if your system does'nt keep the history information you cannot do that, but if your system keeps the amounts and dates of the amendments (the amendments as structured data) you can add that information to the amendment block and the users can just sum all of the amendments value in a compiled release to answer the question.

Paraguay does that with the local extension https://gitlab.com/dncp-opendata/ocds_amendments_details_extension/-/blob/master/release-schema.json

**Comment by jpmckinney** [comment]
^ @ColinMaudry FYI

@yolile I think the better solution is #914, so that we have clear, distinct places for "original value" and "current value" – instead of relying on version history. In other words, moving towards an "append-only" format, rather than an "overwrite" format like we have now.

For the above visualization, can you make the award value the original value and the contract value the current value, that gets updated during implementation?

**Comment by yolile** [comment]
> @yolile I think the better solution is #914, so that we have clear, distinct places for "original value" and "current value" – instead of relying on version history. In other words, moving towards an "append-only" format, rather than an "overwrite" format like we have now.

I think that is good to have a "finalValue" field but also the value and date of each amendment (as the mentioned extension)

> For the above visualization, can you make the award value the original value and the contract value the current value, that gets updated during implementation?

Yes, I think that it is a good solution to keep de original value in award.value field and the updated one in the contract.value

**Comment by jpmckinney** [comment]
Sounds good, re: tracking each amendment's information. @ColinMaudry is working on a similar extension for the EU, whose forms are even less structured.

**Comment by ColinMaudry** [comment]
Yes, it will be here this week: https://github.com/open-contracting-extensions/ocds_unstructuredChanges_extension

**Comment by jpmckinney** [comment]
Now in registry: https://extensions.open-contracting.org/en/extensions/unstructuredChanges/master/

The other points raised can be continued in #914.
