### ISSUE TITLE
relatedProcess: Deprecate 'framework' code

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#577]
Per the decision in #371 which I suppose was accidentally not implemented.

**Comment by jpmckinney** [comment]
cc @JachymHercher

**Comment by duncandewhurst** [comment]
Noting that this would also require updating the documentation in http://standard.open-contracting.org/latest/en/implementation/related_processes/#frameworks-and-related-processes which recommends using `relatedProcess` to model frameworks.

Based on the discussion in https://github.com/open-contracting/standard/issues/440 it seems there isn't an alternative approach that is compatible with OCDS 1.1, so the update would likely mean removing the guidance on frameworks with competitive call-offs altogether.

**Comment by jpmckinney** [comment]
Ah, when I was reviewing all issues a year ago, the discussion in #371 didn't justify why the 'framework' code was kept (#440 explains why), so it seemed like an oversight.

We definitely need a better understanding of multi-stage procedures; I'm preparing a TOR for a researcher to do that. I'll close this issue in the meantime to preserve current functionality.
