### ISSUE TITLE
partyRole: Change description of 'buyer' code

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#578]
Originally reported by @timgdavies https://github.com/open-contracting/ocds_parties_extension/issues/5 and https://github.com/open-contracting/ocds-extensions/issues/12

The current definition of 'Buyer' is "The buyer is the entity whose budget will be used to purchase the goods."

This appears wrong on a number of levels.

(1) We now recognise (via an extension) multi-source budgets;

(2) OCDS does not only apply to 'goods'

An improved, but backwards compatible, definition of buyer is needed.

**Comment by timgdavies** [comment]
I would propose the following updated definition: 

> "A buyer is an entity whose budget will be used to pay for goods, works or services related to a contract."

**Comment by timgdavies** [comment]
I believe this should be a backwards compatible addition to an open codelist.

**Comment by jpmckinney** [comment]
Looks good to me.
