### ISSUE TITLE
Documentation of validation rules / Certification of validators

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#587]
* [x] We should author the additional validations performed by CoVE as prose acceptance tests, so that other validators know what to target.
* [ ] We should provide test files for each acceptance test (e.g. having a mismatch between `contracts/awardID` and `awards/id`). These should presumably already be in CoVE's test suite.
* [ ] (This requires more thought:) We should write instructions for authors of validators to self-certify by e.g. filling out a form or template that shows (in a way we can replicate) how the validator takes the input test file for each acceptance test and produces the correct output.

**Comment by jpmckinney** [comment]
cc @timgdavies @mpostelnicu

**Comment by robredpath** [comment]
There are three places I'm looking for this: 
- unit tests
- functional tests
- templates

**Comment by timgdavies** [comment]
We have been working on a set of MUST, SHOULD, MAY statements to guide the development and certification of validation tools. Comments are welcome on the proposed list below:

* Tools MAY accept input in any recognized OCDS serialization format. If non-JSON input is accepted, it SHOULD be converted to OCDS JSON for validation against the canonical JSON schema. 

* Tools MUST check that the document to be validated against the canonical JSON schema is a well-formed and UTF-8 encoded JSON file

* Tools MUST detect whether the supplied document is a release package or record package and use the appropriate schema. 

* Tools MUST perform schema validation against the latest released version of the OCDS schema, and MAY perform schema validation against previously released OCDS schema versions, or versions * currently in draft. 

* Tools MUST reject files that specify an invalid OCDS version

* Tools MUST assume that files without a version are to be validated against version 1.0n of the OCDS Schema

* Tools MUST report on the use of deprecated fields

* Tools SHOULD provide actionable feedback as a result of errors

* Tools SHOULD encourage users to use the fields within the standard and existing extensions wherever possible 

* Tools SHOULD automatically fetch and apply extensions specified in data, and inform the user of the resulting schema

* Tools SHOULD, if they support extended schema, also apply changes to codelists made by the extension

* Tools SHOULD warn users when additional fields are found that are not expected (either in the schema or application-specific), or additional values used for open codelists. 

* Tools MAY provide subjective assessment of data quality

* Tools MAY provide feedback on the contents of fields as well as their structure, beyond the validation provided by the OCDS schema

* Tools MAY provide warnings of properties of the data that will lead to incompatibility with future versions of OCDS

* Tools MUST NOT misrepresent modified versions of the OCDS schema as being OCDS


(For internal reference, background document [is here](https://docs.google.com/document/d/1Er0UAH-y6Mt3O-c6ue-uLrK94dfnb7cJFD2KlLzv8HA/edit#) and see CRM-3024)

**Comment by jpmckinney** [comment]
> Tools MUST NOT misrepresent modified versions of the OCDS schema as being OCDS

Extensions modify the schema, and the result is (at least loosely) still OCDS. What modifications are intended in this statement? Modifications by the tool itself (i.e. not by the input data)?

If the statement is intended to mean any modification (including by extensions), we might want more specific language than 'OCDS' (perhaps 'released versions of OCDS schema'), and/or provide sample language (e.g. the review tool has "Get a copy of the schema with extension patches applied").

**Comment by robredpath** [comment]
> If the statement is intended to mean any modification (including by extensions)

It's been a while since I last saw this, but I think that was the intention. How about "as being unmodified OCDS"?

**Comment by jpmckinney** [comment]
Any issue with 'released versions of OCDS schema'? 'unmodified OCDS' is still ambiguous about what counts as 'OCDS'.

**Comment by robredpath** [comment]
> Any issue with 'released versions of OCDS schema'? 

Nope, that's fine!

**Comment by jpmckinney** [comment]
From #581:

> We can also consider reducing the scope of the standard, so that it doesn't extend to saying what a validator or application ought to do – and to instead remain focused on the data itself (in which case the action is to delete the content).

Even if so, we can include the documented rules somewhere non-normative. Besides jOCDS Validator, we haven't seen any interest in new apps for validating OCDS (not that surprising).

**Comment by jpmckinney** [comment]
Making this a documentation issue on lib-cove-ocds: https://github.com/open-contracting/lib-cove-ocds/issues/108
