### ISSUE TITLE
PDF version of documentation

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#588]
@dc-coder produced a PDF version, attached and described in this discussion group message: https://groups.google.com/a/open-contracting.org/d/msg/standard-discuss/49fVlsEq0Gk/zbVdaxtxAwAJ

Of course, the PDF doesn't have an interactive schema viewer, a live-updating list of extensions, etc. but we can consider how some PDF version of the documentation (that will not be identical to what is available online) can be produced.

**Comment by Bjwebb** [comment]
That attached PDF looks pretty good, but some of the tables are cropped (tables in PDF are usually a pain!):
![image](https://user-images.githubusercontent.com/634/31076279-4860e5e2-a771-11e7-9610-fcd0db445216.png)

I've added my suggestion to that thread, but it suffers from the same problem.

A different way of generating a PDF of sphinx docs is via the latex output. I have tried this for the OCDS docs, but keep on running into problems. Additionally, a bunch of our included content only displays properly in HTML (e.g. the folding of JSON includes), and I suspect tables will also be problematic!

**Comment by Bjwebb** [comment]
I've created some PDFs of my own:
[OCDS_en.pdf](https://github.com/open-contracting/standard/files/1453567/OCDS_en.pdf)
[OCDS_es.pdf](https://github.com/open-contracting/standard/files/1453568/OCDS_es.pdf)
[OCDS_fr.pdf](https://github.com/open-contracting/standard/files/1453569/OCDS_fr.pdf)

Unfortunately, a couple of tables are still cropped (but only codelists, schema tables look okay). 
On the plus side, these PDFs have a table of contents (which also shows up in a sidebar), which should be useful for people to navigate through the doc.

@timgdavies @juanpane @ColinMaudry Could you take a glance through and see what you think?

These were produced with wkhtmltopdf:

```bash
#!/bin/bash
for lang in en es fr; do
wkhtmltox/bin/wkhtmltopdf --no-stop-slow-scripts --javascript-delay 5000 --disable-smart-shrinking --print-media-type toc http://localhost:8080/$lang/{,getting_started/{,use_cases/,contracting_process/,building_blocks/,releases_and_records/,publication_patterns/,validation/},schema/{,reference/,release/,release_package/,records_reference/,record_package/,merging/,identifiers/,codelists/,conformance_and_extensions/,deprecation/,changelog/},implementation/{,levels/,licensing/,publication_policy/,serialization/,hosting/,registration/,related_processes/,amendments/},extensions/{,developing/,community/,bids/,enquiries/,location/,lots/,milestone_documents/,participation_fee/,party_details/,process_title/},support/{,tools/,history_and_development,governance/,credits/}} OCDS_$lang.pdf
done
```

**Comment by jpmckinney** [comment]
Last steps to close issue (based on call):

- [x] Push print CSS styles
- [x] Generate the PDFs from the live site so that the links work
- [ ] Decide how and where to publish the PDFs
- [ ] @timgdavies had ideas about branding? (e.g. tool can insert cover page, header, footer)

**Comment by Bjwebb** [comment]
Here are some PDFs generated from the live site (so links should work correctly): 
[OCDS_en.pdf](https://github.com/open-contracting/standard/files/1496005/OCDS_en.pdf)
[OCDS_es.pdf](https://github.com/open-contracting/standard/files/1496006/OCDS_es.pdf)
[OCDS_fr.pdf](https://github.com/open-contracting/standard/files/1496007/OCDS_fr.pdf)

I used this script:
```bash
#!/bin/bash
for lang in en es fr; do
wkhtmltox/bin/wkhtmltopdf --no-stop-slow-scripts --javascript-delay 10000 --disable-smart-shrinking --print-media-type toc http://standard.open-contracting.org/latest/$lang/{,getting_started/{,use_cases/,contracting_process/,building_blocks/,releases_and_records/,publication_patterns/,validation/},schema/{,reference/,release/,release_package/,records_reference/,record_package/,merging/,identifiers/,codelists/,conformance_and_extensions/,deprecation/,changelog/},implementation/{,levels/,licensing/,publication_policy/,serialization/,hosting/,registration/,related_processes/,amendments/},extensions/{,developing/,community/,bids/,enquiries/,location/,lots/,milestone_documents/,participation_fee/,party_details/,process_title/},support/{,tools/,history_and_development,governance/,credits/}} OCDS_$lang.pdf
done
```
I'm currently waiting for a steer on what branding we want.

**Comment by jpmckinney** [comment]
I think @timgdavies had ideas for branding – otherwise, if I were to ask a non-technical person at OCP, what are the constraints in terms of the branding that can be integrated? Tim had suggested a cover page, header, and footer, so I can ask about a steer on those.

**Comment by timgdavies** [comment]
Thanks @Bjwebb - this is looking really good. 

## Markup 

In this [Documentation Mock-up](https://github.com/open-contracting/standard/files/1498707/Documentation.Mock-up.pdf) document I've put together some branding suggestions, which would:

(1) Have a cover page, with the logo, title, copyright statement and a few links - and then the version and generated datetime in YYYY-MM-DD HH:MM (e.g. 2017-11-23 12:34)

(2) Have a second page which takes [the content from here](http://standard.open-contracting.org/latest/en/support/) describing the helpdesk onto an inside cover. 

(3) Add a header to each page just including the logo

(4) Add a footer to each page with version number, generated datetime, and page number (if possible to do that - as handy when discussing docs with someone)

## A few other CSS issues

* Any way we can get rid of the scroll-bars on the examples? 

* Any way we can hide the docson widgets that don't display in the PDF version? Is there a CSS class we could wrap around things we want to hide from printed docs? 

## Ordering

Is there any way we can change the ordering in the PDF version - as it might be more natural, for example, for us to have the changelog as an appendix rather than in-line. 

Not a major issue if not: but a nice-to-have. 

## Generating process

If we can include the PDFs as part of the build process, and then link to them from within the docs, that would be good.

**Comment by jpmckinney** [comment]
@Bjwebb Can you transfer https://github.com/Bjwebb/ocds-pdf to the open-contracting organization?

You might need to transfer it to opendataservices and then @robredpath can transfer it to OCP.

**Comment by Bjwebb** [comment]
Looks like I can transfer it directly, which I've done.

**Comment by jpmckinney** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OCDS as PDF](https://trello.com/c/8pz5h4LH/30-ocds-as-pdf)

**Comment by jpmckinney** [comment]
@LindseyAM wrote:

> Since we will be updating the documentation, would the ability to download as a pdf remain if the documentation significantly changes? if it would be better to wait until after 1.1.5 that is ok too.

We have a script to generate a PDF from the documentation. I anticipate that it will continue to work without changes. If we make significant changes to the UI, I think we just need to remember to make corresponding changes to the print stylesheet. In any case, the script should not be difficult to update.

**Comment by robredpath** [comment]
@jpmckinney I recall that @Bjwebb had some concerns about the neatness and presentation of the PDF - that although it worked, it wasn't as nicely presented as if it had been designed as a paper document. Are we happy with the presentation that the script produces? If so, is the outstanding work just to automate it into the build process and link to it?

**Comment by jpmckinney** [comment]
I think we need to assess the demand for the PDF. At present, it seems to be fairly infrequent, which makes it lower priority. For now, since the presentation has issues, we can share it in response to an inquiry. In terms of presentation, I think the items in this earlier comment are still outstanding: https://github.com/open-contracting/standard/issues/588#issuecomment-346585536 Once the presentation is improved, we can consider making it part of the build process and linking to it.

**Comment by jpmckinney** [comment]
Closing in favor of https://github.com/open-contracting/ocds-pdf/issues/1
