### ISSUE TITLE
Region (global) vs Region (local)

### ISSUE THREAD

**Issue by mireille-raad** [open-contracting/standard#595]
Region can be global and mean something like "East Asia and Pacific" or "Latin America"
but also it can mean something that is one level below country.
For example

```json
"address": {
                        "streetAddress": "4, North London Business Park, Oakleigh Rd S",
                        "locality": "London",
                        "region": "London",
                        "postalCode": "N11 1NP",
                        "countryName": "United Kingdom"
                    }
```

Does OCDS treat these 2 regions differently? is there any way to support the "higher-level" region?

**Comment by jpmckinney** [comment]
Region here has the meaning as in [vCard](https://tools.ietf.org/html/rfc6350#section-6.3.1), [Schema.org](http://schema.org/addressRegion), etc. which is to say something like a state or province, which (in most cases) is the administrative level below the national level.

There is no support for the higher-level region, but this is derivable from the country.

**Comment by mireille-raad** [comment]
Thanks for the help. Before I close the issue, is there any interest in supporting a higher level structure for region? or out of scope/interest of OCDS?

**Comment by jpmckinney** [comment]
If there is a sufficiently strong or common use case, then it can be considered for inclusion. However, there are multiple inconsistent classification systems for higher-level regions. As the higher-level region is easily derivable from the country, I think it's suitable to leave this as a user operation to enrich a dataset, if they want to perform analysis that compares higher-level regions.

**Comment by timgdavies** [comment]
I'd support the view that higher level regional classification of **address** is out of scope for OCDS.

However, the [location extension](http://standard.open-contracting.org/1.1/en/extensions/location/) can be used to declare any sort of [location gazetteer](http://standard.open-contracting.org/latest/en/extensions/location/#example), so in theory you could re-use that to classify other objects in OCDS with regions as taken from some high-level geographical classification.
