### ISSUE TITLE
A link title is out of date on implementation/hosting.md

### ISSUE THREAD

**Issue by BobHarper1** [open-contracting/standard#601]
The link 'Data on the Web Best Practice #15' (to https://www.w3.org/TR/dwbp/#dataFormats on multiple file formats) is out of date - this is now number 14 on that list (it might have changed position in a recent version of the guidance). Might be best to just remove the number in case it changes again?

https://github.com/open-contracting/standard/blob/1.1-dev/standard/docs/en/implementation/hosting.md#L5

**Comment by jpmckinney** [comment]
We can remove the number, and change the link to either `https://www.w3.org/TR/dwbp/#MultipleFormats` or `https://www.w3.org/TR/dwbp/`.

**Comment by BobHarper1** [comment]
Thanks, probably https://www.w3.org/TR/dwbp/#MultipleFormats will be best, even if the anchor changes we go to the right page

**Comment by timgdavies** [comment]
A pull request with the fix is in #604 and translations ready in Transifex.
