### ISSUE TITLE
"patternProperties" accepts almost anything as a property name

### ISSUE THREAD

**Issue by edugomez** [open-contracting/standard#602]
This is related to this issue in Cove https://github.com/OpenDataServices/cove/issues/679

As long as you add an underscore, almost anything goes as a property name. e.g. ```whatever_name``` is not detected as an additional field in Cove OCDS (whilst ```whatevername``` is correctly identified as extra). I haven't inspected the regex in depth, but it clearly needs to be more restrictive.

I'd like to know how useful ```patternProperties``` are for publishers. If they are really useful, then they probably need better support than currently have. For example, [ocds-tabulate](https://github.com/open-contracting/ocds-tabulate) would require some extra work to include them in a database (as the field name is set by the publisher in the data itself). On the other hand, if they are very marginally used, they may potentially create more problems than they solve

**Comment by jpmckinney** [comment]
To reproduce at http://standard.open-contracting.org/validator/:

```json
{
    "version": "1.1",
    "uri": "http://www.example.com",
    "publishedDate": "2017-09-19T00:00:00Z",
    "publisher": {
        "name": "Open Data Services Co-operative Limited"
    },
    "releases": [
        {
            "ocid": "ocds-213czf-000-00001",
            "id": "ocds-213czf-000-00001-01-planning",
            "date": "2017-09-19T00:00:00Z",
            "initiationType": "tender",
            "tag": [
                "planning"
            ],
            "tender": {
                "id": "ocds-213czf-000-00001-01-planning",
                "whatever_name": "",
                "whatevername": ""
            }
        }
    ]
}
```

**Comment by jpmckinney** [comment]
I think this may be more a CoVE issue than a schema issue. The schema allows people to create new properties, regardless of `patternProperties`. If we wanted to enforce conformance to either explicit fields in `properties` or fields matching the patterns in `patterProperties`, we'd have to set `additionalProperties` to `false`.

**Comment by jpmckinney** [comment]
All `patternProperties` in the core schema allow adding BCP 47 language tags to properties like `title` (e.g. `title_en-GB`). So, there's a limit to what fields can be added that match the pattern.

I think that sufficiently clarifies the issue – and I don't think the intention is to prevent additional properties, which would be a major backwards-compatibility issue.

Will continue in OpenDataServices/cove#679
