### ISSUE TITLE
Juntas de aclaraciones | Clarification meetings [ES] [EN]

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#621]
_English version below_

# Versión en español

## Asunto
En México, es obligatorio realizar al menos una junta de aclaraciones con asistencia voluntaria por parte de los licitantes con el objetivo de responder dudas relacionadas con la convocatoria o  con las modificaciones que se le hayan realizado. Estas juntas se realizan en los procedimientos competitivos (licitación pública e invitación a cuando menos tres personas) y se realizan, generalmente, antes del periodo de recepción de proposiciones, en la etapa de licitación.

Los “Lineamientos técnicos generales para la publicación, homologación y estandarización de la información de las obligaciones establecidas en el título quinto y en la fracción IV del artículo 31 de la Ley General de Transparencia y Acceso a la Información Pública, que deben de difundir los sujetos obligados en los portales de Internet y en la Plataforma Nacional de Transparencia” (página 110), contemplan la obligación de publicar cierta información sobre las juntas de aclaraciones.
 
En particular, los lineamientos contemplan la publicación de la siguiente información:
- Fecha en la que se celebró la junta de aclaraciones
- Relación con los nombres de los asistentes a la junta de aclaraciones
- Relación con los nombres de los servidores públicos asistentes a la junta de
aclaraciones
- Incluir el cargo que ocupan los servidores públicos asistentes a la junta de aclaraciones

Es por ello que, con el objetivo de homologar el Estándar de Datos de Contrataciones Abiertas (EDCA) con las obligaciones de transparencia en México, y por ende, con los Sistemas de Portales de Obligaciones de Transparencia (SIPOT) administrados por el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI), consideramos necesario desarrollar una extensión que contemple la información relacionada con las juntas de aclaraciones.
 
## Propuesta
 
Agregar un arreglo al objeto de licitación (tender). Este arreglo debe contener los siguientes atributos:

Agregar opciones al codelist de “Funciones del integrante”

- Asistente a junta de aclaraciones
- Servidor público asistente a junta de aclaraciones

En la estructura, definir:
- Integrantes
  - Cargo (string)
- Licitación {object}
  - Juntas de aclaraciones [array]
    - Junta de aclaración {object}
      - Identificador (string)
      - Fecha {object}
        - Date
      - Asistentes a la junta de aclaraciones [array]
        - OrganizationReference
      - Servidores públicos asistentes a la junta de aclaraciones [array]
        - OrganizationReference

## Definición de textos

Nombre | Descripción
-- | --
Cargo | Cargo que ocupa el servidor público. Este campo se utiliza para definir el cargo que ocupan los servidores públicos asistentes a las juntas de aclaraciones.
Juntas de aclaraciones | Una lista de juntas de aclaraciones realizadas en la etapa de licitación.
Junta de aclaraciones | Una junta de aclaraciones se utiliza para resolver las dudas que los licitantes pudieran llegar a tener sobre aspectos relacionados con la convocatoria.
Identificador | Un identificador para esta junta de aclaraciones, único dentro de este bloque.
Fecha | La fecha en que se realizó esta junta de aclaraciones.
Asistentes a la junta de aclaraciones | Los licitantes u otros actores asistente a las junta de aclaraciones.
Servidores públicos asistentes a la junta de aclaraciones | Los servidores públicos asistentes a la junta de aclaraciones.

# English version

## Issue

In Mexico, it is mandatory to carry out at least one clarification meeting with voluntary assistance by the tenderers in order to answer questions related to the call for proposals or the modifications that have been made to it. These meetings are made in competitive procedures and are usually made before the period when the tender is open for submissions.

The "General technical guidelines for the publication, homologation and standardization of the information of the obligations established in the fifth title and in the fraction IV of article 31 of the General Law of Transparency and Access to Public Information, which must be disseminated by the subjects forced in the Internet portals and in the National Transparency Platform "(page 110), consider the mandatory publication of certain information related to clarification meetings.

In particular, the guidelines contemplate the publication of the following information:
- Date on which the clarification meeting was made
- Names of those attending the clarification meeting
- Names of the public servants attending the meeting of clarification
- Position occupied by the public servants attending the meeting of clarifications

Thus, with the aim of match the Open Contracting Data Standard (OCDS) with the transparency obligations in Mexico, and therefore, with the Transparency Obligations Portals System (SIPOT) administered by the National Institute of Transparency, Access to Information and Protection of Personal Data (INAI), we consider necessary to develop an extension that includes the information related to the clarification meetings.

## Proposal

Add an array within the tender object. This array must contain th following values:

Add new values to the partyRoles codelist
- Attendees
- Public Servants attendees

In the schema:
- Parties
  - position (string)
- Tender {object}
  - clarificationMeetings [array]
    - clarificationMeeting {object}
      - id (string)
      - date {object}
        - Date
      - attendees [array]
        - OrganizationReference
      - publicServantAttendees [array]
        - OrganizationReference

## Defining texts

Name | Description
-- | --
position | Position held by the public servant. This field is used to define the position occupied by the public servants attending the clarification meeting.
clarificationMeetings | A list of the clarifications meetings related to the tender section.
clarificationMeeting | A clarification meeting is used to solve the doubts that the tenderers may have about issues related to the call for proposals.
id | A local identifier for this meeting, unique within this block.
date | The date on which the clarification meeting is held.
attendees | The tenderers or other actors attending the clarification meeting.
publicServantsAttendees | The public servants attending the clarification meeting.

**Comment by JArielMG** [comment]
Worked example:

Add an array within the tender object. This array must contain th following values:

```
{
  "definitions": {
    "ClarificationMeeting": {
      "title": "Clarification meeting",
      "type": "object",
      "description": "A clarification meeting is used to solve the doubts that the tenderers may have about issues related to the call for proposals.",
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "title": "Meeting ID",
          "description": "A local identifier for this meeting, unique within this block.",
          "type": [
            "string",
            "integer"
          ],
          "minLength": 1
        },
        "date": {
          "title": "Date",
          "description": "The date on which the clarification meeting is held.",
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "attendees": {
          "title": "Attendees",
          "description": "The tenderers or other actors attending the clarification meeting.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/OrganizationRefence"
          }
        },
        "publicServantAttendees": {
          "title": "Public servant attendees",
          "description": "The public servants attending the clarification meeting.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/OrganizationRefence"
          }
        }
      }
    },
    "Tender": {
      "properties": {
        "clarificationMeetings": {
          "title": "Clarification meetings",
          "description": "A list of the clarifications meetings related to the tender section.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/ClarificationMeeting"
          }
        }
      }
    },
    "Organization": {
      "properties": {
        "position": {
          "title": "Position",
          "description": "Position held by the public servant. This field is used to define the position occupied by the public servants attending the clarification meeting.",
          "type": [
            "string",
            "null"
          ]
        }
      }
    }
  }
}
```
I would welcome views on this suggested modelling.

**Comment by timgdavies** [comment]
Thanks @JArielMG for such a clear description of the issue and proposed modeling. I've tagged this as a potential community extension - based on the generalizable nature, and possibility that other publishers might have similar data that would fit into this model.

I think your model makes very good sense: and agree this sits well within Tender.

The only question or suggestion I have is around the use of parties and parties terminology.

(1) Does the current business process of publishing details of attendees capture anything beyond their names? The parties section has scope for detailed data on registration numbers, identifiers and addresses and so-on - but if this is not currently collected, we would end up with very sparse entries in the parties array - or a pressure for increased data collection around these meetings.

Is the name collected the name of an individual? Or an organisation? Or both?

I can see that there might be use-cases for having company registration numbers, and other identifying information from the clarification meeting stage - but if this is not realistically going to be collected, you might want to consider a simpler model that just captures the names, organisations and roles, and optionally an identifier that can be cross-referenced to parties. 

(2) However, if you are using the parties array, I would suggest using a more explicit role value, such as 'clarificationMeetingAttendee' and 'clarificationMeetingOfficials'  - just so that if other extensions introduce the concept of an attendance role, there isn't a risk of a clash.

**Comment by antonioherrera** [comment]
Thanks @timgdavies for taking your time reviewing this extension.

I will try to solve your questions below.

1. The current process of publishing details of attendees capture only the information of their names and positions (in the case of officials), but in the short term it is expected to capture the identifiers data. As you mention, we previusly though to include a simpler model that captures the names, positions and roles. However, we considered that we could use the parties section, in order to mantain coherence thoughout the schema, but we are open for another purposes.

2. The name collected is the name of the organization, or when the tenderer is an individual, the name of it.

3. We will take into account your suggestion about the values of the partyRoles codelist and we'll publish the modifications soon.

Thank you again and we'll be aware of any other question or comment.

**Comment by jpmckinney** [comment]
@antonioherrera I did an initial review of the [extension](https://github.com/INAImexico/ocds_clarificationMeetings_extension), and @JArielMG merged the changes. Would you like this extension to be added to the [extension registry](https://github.com/open-contracting/extension_registry) as a community extension?

**Comment by antonioherrera** [comment]
Sure, go ahead.

**Comment by jpmckinney** [comment]
After further research, it is easy to find other examples of clarification meetings in other jurisdictions, so the concept is suitable for a community extension. However, it is relatively rare for individuals (attendees and officials) to be disclosed; also, the `OrganizationReference` is not the preferred object to model a natural person (except in the exceptional case of a sole trader). The only other metadata in the extension is the date, whereas it is very common to disclose: place, description, documents, URL.

I am therefore marking this as a local extension, though we can open a new issue if there is demand for a common extension that satisfies the broader set of use cases.

**Comment by yolile** [comment]
This extension can be reused in the case of the National Directorate of Public Procurement (DNCP) in Paraguay, but in this case only the date and place of the clarification meeting is available. Could the "address" field be added to the object "clarificationMeeting" as an optional data so that this extension can be used in Paraguay?

**Comment by jpmckinney** [comment]
I would instead propose drafting a smaller extension with just the date and place, since some of the other fields in the extension had questions/issues above.

Regarding the place, is that available as a structured address in Paraguay, or only as free text? In most jurisdictions I came across earlier, it seemed like the place was free-text.

**Comment by yolile** [comment]
It is a free text, normally fill in with the street address, so the new reduced extension could be modeled as 

```json

"tender": {
   "clarificationMeetings": [
    {
      "id": "1",
      "date": "2009-11-13T00:00:00Z",
      "address": {
           "streetAddress": "OLIVA C/ ALBERDI ED. EX. LAP 1ER PISO."
       }
    }
  ]
 }

```

In Paraguay there is only one clarification meeting per process, but to support other publications it could be an array. And the same for the address, is just a free text but in case there is another publisher that has more structured address we can keep the address block

**Comment by jpmckinney** [comment]
Good idea! So the extension readme can recommend using `streetAddress` if only free-text is available.

**Comment by antonioherrera** [comment]
> also, the `OrganizationReference` is not the preferred object to model a natural person (except in the exceptional case of a sole trader).

That's a very important issue that I think we should discuss apart. I really believe that `OraganizationReference` and the object `Organization ` doesn't match the current descripción of the Parties array. 

I understand the `Parties` section as the place to capture all the data related to the whole participants (individuals or organizations) involved with the contracting process. Nevertheless, it is strange that the object contained in the parties array is not "Party", but "Organization".

I really think that we should discuss a better way to organize all the actors who are related to the contracting process because I don't know why there is not a specific section to capture individuals.

So, if individuals should be registered in the Parties object, there is no place for an object called "Organization" nor "OraginzationReference", but `Party` and `PartyReference`.

**Comment by jpmckinney** [comment]
@antonioherrera I have created #883 to discuss that issue, and made a proposal.

**Comment by yolile** [comment]
drafted extension: https://gitlab.com/dncp-opendata/ocds_clarification_meetings_extension

cc @duncandewhurst

**Comment by jpmckinney** [comment]
Noting that I've also used `streetAddress` in the case of unstructured place/address information on the EU's TED form field for the place of opening of tenders.

**Comment by jpmckinney** [comment]
Closing as the extension is published.
