### ISSUE TITLE
milestoneType: Avisos a la población | Public notices [ES] [EN]

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#623]
# Versión en español

## Asunto

En México se solicita la publicación de información relacionada con las obras públicas que detalle el cierre de calles, cambio de circulación, etcétera.

## Propuesta
Agregar una opción a la lista de códigos “Tipo de hito”

- Avisos a la población

## Definición de textos

Título | Descripción
-- | --
Avisos a la población | Para hitos en los que se especifiquen aspectos relacionados con las obras públicas, como el cierre de calles, cambios de circulación, etcétera.

# English version

## Issue

In Mexico it is needed to publish information related with works detailing closure of streets, change of traffic, etc.

## Proposal
Add a new option to the “MilestoneType” code list.

- Public notices

## Defining texts

Title | Description
-- | --
Public notices | For milestones in which aspects related to public works are specified, such as the closure of streets, changes of traffic, etc.

**Comment by JArielMG** [comment]
The following example shows the location where a new option is added to the "MilestoneType" code list, called "publicNotices".

Worked example:

```
{
  "definitions": {
    "Milestone": {
      "properties": {
        "type": {
          "enum": [
            "preProcurement",
            "engagement",
            "approval",
            "assessment",
            "delivery",
            "reporting",
            "financing",
            "publicNotices",
            null
          ]
        }
      }
    }
  }
}
```

I would welcome views on this suggested modelling.

**Comment by timgdavies** [comment]
I've tagged this as a local extension - as it simply extends an open codelist in a way to meet a particular national or local requirement. This means I would suggest we don't create a formal extension in the extensions registry for it - but anyone who needs this is free to publish and use their own extension here.

For open codelists, you are free to use a new code without an extension: the only consequence of that is that the [validator](http://standard.open-contracting.org/validator/) will warn about the extra code. 

With a local extension declared, that warning would be suppressed.

**Comment by jpmckinney** [comment]
Closing as resolved.
