### ISSUE TITLE
Estatus de la ejecución | Implementation status [ES] [EN]

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#624]
# Versión en español

## Asunto

En México, cuando se trata de obras públicas o servicios relacionados con ellas es necesario publicar un conjunto de variables específicas sobre su ejecución. Una de ellas es la etapa de la obra pública o servicio relacionado con la misma. Se trata de una lista de códigos cuyos valores son: 

- en planeación
- en ejecución
- en finiquito

# Propuesta
Agregar el atributo “implementationStatus” en el objeto “Ejecución”.

- Ejecución {object}
  - status (string) (codelist)

Opciones de la lista de códigos:

Título | Descripción
-- | --
En planeación | El contrato ha sido firmado, pero la provisión o construcción de los bienes, servicios u obras públicas no han comenzado.
En progreso | La provisión o construcción de los bienes, servicios u obras públicas se encuentra en marcha.
En finiquito | La provisión o construcción de los bienes, servicios u obras públicas ha finalizado oficialmente.

# English version

## Issue

In Mexico, when talking about works and services related with them it is necessary to publish a set of specific variables about its implementation. One of them is the implementation status of the work or service related with it. It includes a code list whose values are the following:

- planning
- implementation
- terminated

# Proposal
Add a new field named “implementationStatus” in the “Implementation” object.

- Implementation {object}
  - status (string) (codelist) 

Code list options:

Title | Description
-- | --
planning | The contract has been signed, but the provision or construction of the goods, services or works has not started.
inProgress | The provision or construction of the goods, services or works is in progress.
terminated | The provision or construction of the goods, services or works has officially finished.

**Comment by JArielMG** [comment]
The following example shows the location where a new field named "ImplementationStatus" is added to the "Implementation" object.

Worked example:

```
{
  "definitions": {
    "Implementation": {
      "properties": {
        "status": {
          "title": "Implementation status",
          "description": "The current status of the contract implementation based on the implementationStatus codelist.",
          "type": [
            "string",
            "null"
          ],
          "enum": [
            "planning",
            "implementation",
            "terminated",
            null
          ],
          "codelist": "implementationStatus.csv",
          "openCodelist": true
        }
      }
    }
  }
}
```
I would welcome views on this suggested modelling.

**Comment by timgdavies** [comment]
This makes good sense to me, it is consistent with the standard conventions, and the descriptions are clear. 

I'm tagging this as a potential community extension - as I think it could have value to others.

**Comment by timgdavies** [comment]
@kaitlinccsi has highlighted the relationship to the outstanding issue #395 about the use of the term 'terminated' to cover completion of a contract. 

There is an outstanding suggestion there to use 'ended' rather than 'terminated' for cases where the contract has completed - without any implication that things ended early. Views on #395 would be welcome to help us guide whether this extension should use a newer terminology, or should remain consistent with the current 'terminated' code (albeit noting this *might* change in future).

**Comment by antonioherrera** [comment]
@timgdavies we agree with @KaitlinCCSI and we rename the las code with a `concluded` code as follows:


**Title** | **Description**
-- | --
`status` Implementation status | The current status of the contract implementation based on the implementationStatus codelist (url).
`planning` Planning | The contract has been signed, but the provision or construction of the goods, services or works has not started.
`ongoing` Ongoing | The provision or construction of the goods, services or works is in progress.
`concluded` Concluded | The provision or construction of the goods, services or works has officially ended.

**Comment by jpmckinney** [comment]
@antonioherrera I did an initial review of the [extension](https://github.com/INAImexico/ocds_implementationStatus_extension), and @JArielMG merged the changes. Would you like this extension to be added to the [extension registry](https://github.com/open-contracting/extension_registry) as a community extension?

**Comment by antonioherrera** [comment]
Sure, go ahead.

**Comment by jpmckinney** [comment]
The extension has now been added the registry!
