### ISSUE TITLE
Planning/Documents missing in documentation 

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#633]
In the docs page, the planning release reference section does'nt show documents array as part of the Planning object:
![image](https://user-images.githubusercontent.com/6834122/33190209-eefc4cee-d088-11e7-9585-dc03fca0df49.png)
But the documents array is actually in the planning object in the json:
![image](https://user-images.githubusercontent.com/6834122/33190280-cc638a34-d089-11e7-80ee-7c29ffc18e81.png)

**Comment by jpmckinney** [comment]
@Bjwebb @timgdavies Same bug as in https://github.com/open-contracting/standard/issues/596 Can we add the test I requested in https://github.com/OpenDataServices/sphinxcontrib-jsonschema/issues/1 ?
