### ISSUE TITLE
Improve descriptions of core, community, local extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#634]
Proposed text in bold:

* Core extensions are **maintained as part of the standard governance process,** documented as part of the standard and reviewed by the OCDS technical team with each version upgrade of OCDS. They are likely to be relevant to a large number of publishers and users.
* Community **and local** extension**s** are maintained by third-parties, or are maintained outside of the standard governance process. They may provide features required by only a small number of publishers or users, **or may be used to document a publisher's additional fields or codelist values.** 

**All core and community extensions are listed in the [extensions registry](https://github.com/open-contracting/extension_registry) and in the [documentation](http://standard.open-contracting.org/latest/en/extensions/). The [standard governance working group](http://standard.open-contracting.org/latest/en/support/governance/) approves extensions for inclusion in the registry (distinguishing community from local extensions) and for inclusion in the governance process (distinguishing core from community extensions).**

(Essentially, core extensions are in the registry and maintained within the governance process, community extensions are in the registry, and local extensions are neither. This also proposes a process for an extension to be included in the registry or governance process, which is undocumented.)

----

> Links to externally hosted local extensions may be included in the OCDS reference documentation, drawing on the extensions registry.

I'm not sure why the word 'local' occurs here. I think it should be removed.

----

Also, the following pages both have definitions of core and community extensions. We should probably promote one and have the other reference it, to avoid potential divergence of documentation:

* http://standard.open-contracting.org/latest/en/extensions/developing/
* http://standard.open-contracting.org/latest/en/extensions/

Moved https://github.com/open-contracting/extension_registry/issues/44 here.

**Comment by timgdavies** [comment]
I believe this guidance can be updated under 1.1.3, and constitutes a fix to de-duplicate the documentation - ahead of our wider outreach on extensions coming up through community call. 

I've staged the text above, with the exception of changing the line from "The standard governance working group approves" to "The standard technical team" which more accurately reflects current practice.

**Comment by jpmckinney** [comment]
👍
