### ISSUE TITLE
Paraguay extensions for financial implementation data

### ISSUE THREAD

**Issue by juanpane** [open-contracting/standard#635]
# Paraguay procurement process

## Background

Paraguay manages the information from its procurement processes in two institutions:

- **Dirección Nacional de Contrataciones Públicas (DNCP) [Public procurement agency]**: Manages, through its [e-procurement system](https://contrataciones.gov.py/), the information from the planning, tender, award and contract phases, up to the signature of the contract. The e-procurement system is used then by all the public institutions for buying good, services and public works.
- **Ministerio de Hacienda (MH) [Ministry of Finance]**: Manages, through SIAF system ([Sistema Integrado de Administración Financiera](http://www.hacienda.gov.py/web-presupuesto/index.php?c=147)),  the finantial information related to different contracting processes including the national budget and its assignment to the contracting processes, and the payment process for the contracts managed initially in the DNCP's e-procurement system. 

DNCP already publishes its information based on the Open Contracting Data Standard at its [public API](https://www.contrataciones.gov.py/datos/api/v2/#!/ocds) including planning, tender, award and contract data for all the procurement processes managed by its e-procurement system.

The Ministry of Finance is the responsible for publishing financial information related to:

- planning.budget
- contract.implementation.transaction

### Financial information related to procurement processes

In Paraguay, from a financial perspective,  these are the steps that are defined in the contracting process:

 1. **Define the expected budget (presupuesto previsto)**: When a planning is done (PAC: plan anual de contrataciones), and as a pre-requisite for issuing the tender, the contracting institution has to obtain from the SIAF system ([Sistema Integrado de Administración Financiera](http://www.hacienda.gov.py/web-presupuesto/index.php?c=147)), managed by the Ministry of Finance of Paraguay (Ministerio de Hacienda), a Certificate for Budget Availability (CDP: certificado de disponibilidad presupuestaria). This checks whether the institution still has money left for spending in the budget lines that are to be used in the procurement process. The CDP contains a reference to the budget line and the amount of money it is expected to be spent for this particular procurement process. Note that depending on the items expected to be procured, a CDP can reference several budget lines, for instance, because the procurement is for the construction of a new Datacenter, which requires construction, hardware, internet, etc, all belonging to different parts of the economic classification.
 2. **Commmit the budget (presupuesto comprometido)**: Once the procurement has been awarded and a contract signed, the exact amount of money from each budget line is said to be dedicated specifically for honoring the contract (as long as the provider honors its side for the contract). Note that the amounts for each budget line may vary from the CDP (the expected budget), because for example, the procurement process expected to spend 100 USD in hardware, but a cheaper bid was awarded. In the paraguayan case, the data from the CDP changes its status, from “expected” to “committed”. At this stage the SIAF system contains the relation between a particular contract and the budget lines to be used for paying the contract. The contract code (CC) is the one issued by the National Procurement Agency in Paraguay ([DNCP](https://contrataciones.gov.py/)). Note that without this CC no payment can be done for a contract, which means that if the payment has to be done via SIAF, the procurement process has to be done via DNCP. 
 3. **Financially commit to make a payment (obligación)**: When the provider starts delivering what is defined in the contract, they present a bill (and/or any other legal documentation) for getting paid, according to the payment modalities defined in the contract. Note that from this point forward, the amounts refer to what has to be paid, which normally is less that what is committed in the budget for the whole contract, for instance, because a contract has a monthly payments. This step adds extra information such as the bill number and other details. All these payment information is stored in the SIAF system in Paraguay.
 4. **Request the payment (solicitud de transferencia de recursos)**: When the provider delivers on the contract, and the proof of payment, say the bill, the receiving buyer has to request the corresponding payment using the SIAF system. Only once the buyer processes and authorizes this request for payment, the actual payment transaction can be done.
 5. **Transfer the money (órden de transferencia)**: In Paraguay all payments for procurement processes are done using a wire transfer from the bank account of the paying institution (buyer), to the bank account of the supplier. Paraguay plans to publish details of the wire transfers such as the dates when the transfer was ordered, and the date when the transfer was actually performed.

Note that the first two refer to the budget line or budget lines for the procurement process as a whole (and as such should be included in the planning.budget block), while the last three steps refer to the payment process (and as such should be included in the contract.implementation.transaction block).

## Extension fields

We propose to add a set of fields that are local to the Paraguayan context in a base Paraguayan extension, and then, all the budget and implementation information would be independent probable "community" extensions, that are to be referenced by the Paraguayan extension.

In what follows we list the new fields to be added in the local extension.

###Field 1: Link to the rest of the data
#### Issue 1
The Ministerio de Hacienda of Paraguay will publish now data about budget and implementation of a contracting process, however, details of the other phases are already been published by the Dirección Nacional de Contrataciones Públicas (DNCP). We propose adding a field to the Hacienda releases to reference where all the other information is published, for this particular OCID, pointing to DNCP's record package (note that in DNCP there is only one record package per OCID containing all the latest information).

#### Proposal 1
Add the field **dncpRecordURI** to realease
##### Example:
```javascript
"releases": 
    [
        {
            "ocid": "ocds-03ad3f-246807",
            "dncpRecordURI": "https://www.contrataciones.gov.py:443/datos/api/v2/doc/ocds/record-package/246807
"
            ...
        }
    ]
```
##### Patch:
```javascript
{
  "properties": {
    "dncpRecordURI": {
      "title": "Dncp Record URI",
      "description": "A URI pointing to the DNCP record package for this contracting process ",
      "format": "uri",
      "type": "string"
    }
  }
}
```
#### Issue 2
For each contract, the DNCP generates a contract code that differs from the id of the contractId it self, and this information is relevant because it helps users to link a contract in Hacienda with a contract in DNCP. Users are very used to working with this information in Paraguay, and as such it is needed for the Paraguayan users of the data.

#### Proposal 2
Add a **dncpContractCode** field at contract level. This field is already present also in the DNCP OCDS API.

##### Example:
```javascript
"contracts": [
    {
        "id": "246807-11-setiembre-srl-4",
        "awardID": "246807-adqusicion-guantes-otros-insumos-medicos",
        "dncpContractCode": "CD-13003-13-70684",
        ...
    }
]
```
##### Patch:
```javascript
  "definitions": {
    "Contract": {
      "properties": {
        "dncpContractCode": {
          "type": "string",
          "title": "DNCP contract Code",
          "description": "Contract code generated by DNCP"
        }
      }
    }
  }
```
Both patches together:

```javascript
{
  "properties": {
    "dncpRecordURI": {
      "title": "Dncp Record URI",
      "description": "A URI pointing to the DNCP record package for this contracting process ",
      "format": "uri",
      "type": "string"
    }
  },
  "definitions": {
    "Contract": {
      "properties": {
        "dncpContractCode": {
          "type": "string",
          "title": "DNCP contract Code",
          "description": "Contract code generated by DNCP"
        }
      }
    }
  }
}
```

## Companion extensions

Since the Ministerio de Hacienda also manages data from the budget related to a particular contracting process, and payment process details, we need to include extensions for the corresponding fields.

However, since the attributes for these extensions could be potentially reused by other publishers, these are to be treated as separate extensions, that would be "included" in the Paraguayan extension. The information in the following two subsection would probably be added as a different issue.

#### Issue
In Paraguay, a budget line have extra fields that the current budgetBreakdown extension doesnt have and that are relevant for the budget line. 
That fields are: 
- Estado del CDP: current state of the budget line
- monto comprometido: commited amount to spend in a contracting process
- número de certificado de disponibilidad presupuestaria: availability certificate number, the number of the document that ensure that the money for that contract exists and is available.

#### Proposal
Add a new fields named "status", "commitedAmount" and "availabilityCertificateNumber" to the "budgetBreakdown" object.
#### Example
```javascript
"budgetBreakdowns": 
[
    {
        "status": "COMPROMETIDO",
        "availabilityCertificateNumber": 168,
        "commitedAmount": {
            "value": 10.000.000
            "currency": "PYG"
        }
    }
]
```
#### Patch
```javascript
{
  "definitions": {
    "BudgetBreakdown": {
      "properties": {
        "status": {
          "type": "string",
          "title": "Status",
          "description": "The status of the certificate of budgetary availability."
        },
        "availabilityCertificateNumber": {
          "type": "integer",
          "title": "Availability Certificate Number",
          "description": "Number of Availability Certificate"
        },
        "commitedAmount": {
          "description": "Amount in the contract.",
          "$ref": "#/definitions/Value"
        }
      }
    }
  }
}
```

#### Final structure of the extended budgetBreakdown to be published

The budgetBreakdown block will contain the following information:

- id: 
- description: 
- amount:
  - value: 
  - currency:
- uri: 
- period:
  - startDate: 
  - maxExtendDate: 
- sourceParty
  - id: 
  - name: 
- **status**: 
- **commitedAmount**
  - value: 
  - currency:
- **availabilityCertificateNumber**: 

The attributes marked in bold are new extensions needed over the base budgetBreakdown extension

#### Issue
As explain above, in Paraguay, a payment process is compose by 3 differents stages, 
- **finantialObligation** (Obligación): when a supplier makes an invoice to receive the payment.
- **paymentRequest** (Solicitud de Transferencia STR): when the buyer makes the request to the Ministerio de Hacienda to do the payment on its behalf.
- **transaction** (Orden de Transferencia OT): when the payment is done by Ministerio de Hacienda and the money is deposited to the supplier's bank account.

The current transaction object only covers the last part of the process, and the other two stages are relevant for the process, too.

Also, the Orden de Transferencia OT in Paraguay have the extra fields that are not in the transaction object: description, requestDate and budgetSource.

#### Proposal
Add a new fields named description, requestDate and budgetSource in transaction and also a finantialObligation and paymentRequest arrays, described below

#### Patch

```javascript
{
  "definitions": {
    "FinantialObligation": {
      "title": "Finantial Obligation",
      "description": "Finantial Obligation  ",
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "title": "Obligation Id",
          "description": "Number of the document that represents the obligation."
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Brief description of the operation, referencing the documentations that support it."
        },
        "bill": {
          "title": "Bill",
          "description": "The end date for the period. When known, a precise end date must always be provided.",
          "$ref": "#/definitions/Bill"
        },
        "retentions": {
          "title": "Retentions",
          "description": "Retentions for the payment value.",
          "$ref": "#/definitions/Retention"
        },
        "creationDate": {
          "description": "It indicates the date of loading of the obligation",
          "format": "date-time",
          "title": "Creation Date",
          "type": [
            "string",
            "null"
          ]
        },
        "modificationDate": {
          "description": "Indicates the date that is detected and corrected an error in the obligation.",
          "format": "date-time",
          "title": "Modification Date",
          "type": [
            "string",
            "null"
          ]
        },
        "cancellationDate": {
          "description": "Indicates the date on which an obligation is left without effect for cause.",
          "format": "date-time",
          "title": "Modification Date",
          "type": [
            "string",
            "null"
          ]
        },
        "approvalDate": {
          "description": "It indicates the date of verification and approval of the obligation by the hierarchical level.",
          "format": "date-time",
          "title": "Approval Date",
          "type": [
            "string",
            "null"
          ]
        },
        "paymentRequestIds": {
          "title": "Payment Request Ids",
          "description": "Indicates the number of the payment request",
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "PaymentRequest": {
      "title": "Payment Request",
      "description": "Information about a Payment Request",
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "title": "Payment Request Id",
          "description": "It indicates the number of payment request"
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "It is a brief description in relation to the requested payment. It is loaded by the entities."
        },
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Indicates the status of the payment request"
        },
        "creationDate": {
          "description": "It indicates the date of loading of the payment request",
          "format": "date-time",
          "title": "Creation Date",
          "type": [
            "string",
            "null"
          ]
        },
        "modificationDate": {
          "description": "Indicates the date that is detected and corrected an error in the payment request.",
          "format": "date-time",
          "title": "Modification Date",
          "type": [
            "string",
            "null"
          ]
        },
        "treasuryReceptionDate": {
          "description": "Indicates the date that the STR was received in the General direction of the Treasury",
          "format": "date-time",
          "title": "Treasury Reception Date",
          "type": [
            "string",
            "null"
          ]
        },
        "authorizationDate": {
          "description": "Authorization Date of the payment request",
          "format": "date-time",
          "title": "Authorization Date",
          "type": [
            "string",
            "null"
          ]
        },
        "finantialObligationIds": {
          "title": "Finantial Obligation Ids",
          "description": "Listing numbers of obligations which are related to the payment request.",
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "requestedAmount": {
          "title": "Requested Amount",
          "description": "Amount of the payment request",
          "$ref": "#/definitions/Value"
        },
        "totalRetentionAmount": {
          "title": "Total Retention Amount",
          "description": "Amounts of deductions (E.g.. Withholding of taxes, guarantee agreement, fines, etc.)",
          "$ref": "#/definitions/Value"
        },
        "payedAmount": {
          "title": "Payed Amount",
          "description": "Transferred amount or liquid amount",
          "$ref": "#/definitions/Value"
        }
      }
    },
    "Bill": {
      "title": "Bill",
      "description": "Bill",
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "title": "Bill Id",
          "description": "It corresponds to the numbering of the document."
        },
        "type": {
          "title": "Bill Type",
          "description": "It corresponds to the description of the document class.",
          "type": "string",
          "codelist": "billTypeCodelist.csv",
          "openCodelist": true,
          "enum": [
            "invoice",
            "receipt"
          ],
          "minItems": 1
        },
        "description": {
          "type": "string",
          "title": "Bill Description",
          "description": "Brief description of the operation, referencing the documentations that support it.",
          "format": "date-time"
        },
        "date": {
          "description": "Indicates the date of issue of the document.",
          "format": "date-time",
          "title": "Bill Date",
          "type": [
            "string",
            "null"
          ]
        },
        "amount": {
          "title": "Amount",
          "description": "Indicates the amount of operation set forth in the document. (contains deductions)",
          "$ref": "#/definitions/Value"
        }
      }
    },
    "Retention": {
      "title": "Bill",
      "description": "Bill",
      "type": "object",
      "properties": {
        "type": {
          "title": "Retention Type",
          "description": "Type of the retention",
          "type": "string",
          "codelist": "retentionTypeCodelist.csv",
          "openCodelist": true,
          "enum": [
            "taxes",
            "fees",
            "penalties",
            "others"
          ],
          "minItems": 1
        },
        "name": {
          "type": "string",
          "title": "Retention Name",
          "description": "Retention Name",
          "format": "string"
        },
        "amount": {
          "title": "Amount of the Retention",
          "description": "Deduction for value",
          "$ref": "#/definitions/Value"
        }
      }
    },
    "Transaction": {
      "properties": {
        "finantialObligations": {
          "title": "Finantial Obligations",
          "description": "Information about the finantial obligations",
          "type": "array",
          "items": {
            "$ref": "#/definitions/FinantialObligation"
          },
          "uniqueItems": true
        },
        "paymentRequests": {
          "title": "Payment Request",
          "description": "Information about the payment request",
          "type": "array",
          "items": {
            "$ref": "#/definitions/PaymentRequest"
          },
          "uniqueItems": true
        },
        "budgetSource": {
          "title": "Budget Breakdowns Ids",
          "description": "Budget Breakdown Ids used in this payment",
          "type": [
            "string",
            "null"
          ],
          "format": "uri"
        },
        "description": {
          "title": "Description",
          "description": "Concept of the transfer",
          "type": "string"
        },
        "requestDate": {
          "title": "Request Date",
          "description": "Indicates the date of the transfer order generation",
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "uri": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      }
    }
  }
}
```
#### Final structure of the extended transaction block to be published
 
The contracts.implementation.trasactions block will contain the following information:

- id: 
- date: 
- value:
  - amount: 
  - currency: 
- payer:
  - name: 
  - id: 
- payee:
  - name: 
  - id: 
- uri: 
- **budgetSource**[]
  - **budgetBreakdownId**: 
- **description**: 
- **requestDate**: 
- **finantialObligation**: 
  - **id**: 
  - **bill**[]
     - **id**: 
     - **description**: 
     - **type**:  
     - **date**: 
     - **amount**:
          - value: 
          - currency: 
   - **retentions** []
          - **type**: one off(taxes, fees, penalties, other) as open codelist
          - **name**: 
          - **value**:
   - **creationDate**: 
   - **approvalDate**: 
   - **modificationDate**: 
   - **cancellationDate**: 
   - **description**: 
   - **paymentRequestIds**[]: 
 - **paymentRequest**[]: 
      - **id**: 
      - **description**: 
      - **status**: 
      - **creationDate**: 
      - **authorizationDate**: 
      - **modificationDate**: 
      - **treasuryReceptionDate**: 
      - **requestedAmount**:
          - value: 
          - currency: 
      - **totalRetentionAmount**
          - value: 
          - currency: 
      - **payedAmount**:
          - value: 
          - currency: 
      - **finantialObligationIds**[]: 

The attributes marked in bold are extensions needed over the transaction block.

# Final structure of the release

These are the attributes that will be used to publish the contract implementation data from Ministerio de Hacienda, using the release object:

- ocid: 
- dncpRecordURI:
- releaseID: 
- releaseDate: 
- releaseTag: [&quot;planning&quot;, &quot;implementation&quot;]
- initiationType: &quot;tender&quot;
- parties: (buyer, payee, payer, supplier)
  - identifier
  - scheme: PY-RUC, PY-PGN
- buyer:
  - id: 
  - name: 
- planning
  - rationale:
  - url:
  - documents
     - id: 
     - title: 
     - url: 
     - format: 
     - language: 
  - budget
     - id: 
     - amount: 
     - description: list of all the programs used to fund this contracting process, separated by comas
     - project: list of all the projects used to fund this contracting process
     - projectID: null. Details of this information will go into the budgetBreakdown array
     - uri: null. this information will go into the budgetBreakdown array
     - budgetBreakdown[] (as defined above)
- tender
  - name: 
  - id: 
  - procurementMethodDetails: 
  - Period
      - startDate: 
- contracts
  - id: 
  - awardId: 
  - dncpContractCode: 
  - documents
     - id:
     - title: 
     - url: 
     - format: 
     - language:
  - implementation
     - transactions[]: (as defined in the previous section)

**Comment by timgdavies** [comment]
Thanks @juanpane - this is a really clear issue. I've tried to work through point-by-point below with some responses. 

## Field 1:

- Will the record package created by DNCP also include the release(s) published by MH?

- With MH be publishing their own record packages?

- If only DNCP is publishing a record package, and it will contain MH's releases, then having a more generic 'recordPackageURL' might be appropriate, and could be useful across other publishers.

## Field 2: 

- Am I correct in understanding that both DNCP and MH will *also*, as the example shows, use the same `contract.id` value? Is there a reason for the duplicate identifiers for a contract (the current `contract.id` and the `dncpContractCode`?) 


## Budget Breakdown

I'm not sure I fully understand the interaction here between `amount`, `status` and `committedAmount`. 

From the OCDS docs, `budget.amount` is defined as "The value reserved in the budget for this contracting process." where the concept of reserved is not tightly defined - though it appears closer to the concept of 'committed' than to the idea of 'expected' or 'estimated' costs of a process. 

If the goal is to be able to compare expected budget (presupuesto previsto) and committed  budget (presupuesto comprometido) we should consider either (a) just adding status, and on the assumption that there will be two release, one with estimated, and the other with committed budget, relying on the ability to compare releases to let users understand any changes; or (b) adding `estimatedAmount` defined as "The estimated value of this contracting process. The presence of an estimate does not imply that budget has already been allocated to this process".

For the `availabilityCertificateNumber` the one existing general modelling space for this would be through the documents block, by having a document with a `document.type` of 'availabilityCertificate' and then the number in it's title. However, if there are good usability reasons for creating the specific property, I don't see any problems with this (albeit we would need to check other processes before including in the budgetBreakdown extension). 

## Transaction process details

Small spelling/english issue: finantialOblocation -> financialObligation

budgetSource should be an array following [the pattern explored in this issue](https://github.com/open-contracting/standard/issues/483#issuecomment-319714056) to allow inclusion of ID and amounts. 

On the other properties, I am cautious about OCDS having a community extension to cover this as:

(a) I'm concerned that this information is better linked out to, and modelled in financial systems that take a payment-centric view of the world;
(b) We have some wider work to do on thinking about transactions, which are currently used to describe actual financial flows, but where there is interest in using them more broadly, and which needs decisions on whether to expand `transactions` or create neighbouring blocks for `accruals` etc. 
(c) We have previously looked at linking milestones and transactions as a way of indicating the periodicity of payments, and providing more details about the documents supplied to trigger a payment. I'm worried that we're duplicating some information in this block that could live in documents or milestones. 

If there is an immediate need for this, I would suggest it is take forward as part of the local Paraguay extensions, but that we pay attention to this as part of wider work on OCDS, budgets and payments, including further work on #483.

**Comment by juanpane** [comment]
Thanks @timgdavies for you reply:

> ## Field 1: dncpRecordURI
> 
> - Will the record package created by DNCP also include the release(s) published by MH?

no, the only ones updating their publication is the Minitry of Finance, there is no inmediate plan to update DNCP data

> -  With MH be publishing their own record packages?

there is no plan for this

> -  If only DNCP is publishing a record package, and it will contain MH's releases, then having a more generic 'recordPackageURL' might be appropriate, and could be useful across other publishers.

as mentioned before, there is no plan to update DNCP´s publication, but the point is valid, perhaps naming the field 'recordPackageURL' is more appropriate in order to allow DNCP to include others record packages

> ## Field 2: dncpContractCode
> - Am I correct in understanding that both DNCP and MH will also, as the example shows, use the same contract.id value? Is there a reason for the duplicate identifiers for a contract (the current contract.id and the dncpContractCode?)

the values for both contract.id and dncpContractCode are differente among themselves, but both publishers will use the same values. The reason for having to identifiers is that developers are used to using the contract.id value to match contracts, but users such as providers are used to seeing the dncpContractCode and look for contracts using that code, so we decided to keep both in order to easily support both types of users.

> ## Budget breakdown
>
> I'm not sure I fully understand the interaction here between amount, status and committedAmount.
>
> From the OCDS docs, budget.amount is defined as "The value reserved in the budget for this contracting process." where the concept of reserved is not tightly defined - though it appears closer to the concept of 'committed' than to the idea of 'expected' or 'estimated' costs of a process.

I'll try to explain better these concepts:
- the 'amount' attribute is the expected (or reserved if you wish) amount for this particular budget line for this particular process. This derives from the fact that the government signed a contract with a provider, and as such, the government has to "reserve" this money to be paid, when the bills are due, hopefully, because the goods and services have been delivered. So a procurement process can have several entries in the budget Breakdown array.
- the 'committedAmount' (perhaps the word committed is not the right one here, please help me out with this) is the sum of all the money that will be paid using a particular budget line. So basically, this tells you how much of your reserved amount you have actually used, so far.

- the 'status' field is part of the budget line, because for some reasons the budget line might be droped, changed, cancelled, be active, pending, etc.

> If the goal is to be able to compare expected budget (presupuesto previsto) and committed budget (presupuesto comprometido) we should consider either (a) just adding status, and on the assumption that there will be two release, one with estimated, and the other with committed budget, relying on the ability to compare releases to let users understand any changes; or (b) adding estimatedAmount defined as "The estimated value of this contracting process. The presence of an estimate does not imply that budget has already been allocated to this process".

I think that the amount attribute works well and there is no need for the estimatedAmount field

> For the availabilityCertificateNumber the one existing general modelling space for this would be through the documents block, by having a document with a document.type of 'availabilityCertificate' and then the number in it's title. However, if there are good usability reasons for creating the specific property, I don't see any problems with this (albeit we would need to check other processes before including in the budgetBreakdown extension).

I'd include this here, since this is very important in the payment process for the users, for the suppliers side, the procuring entity, and the ministry of finance too.

> ## Transaction process details
> Small spelling/english issue: finantialOblocation -> financialObligation

Great, will fix this

> budgetSource should be an array following the pattern explored in this issue to allow inclusion of ID and amounts.

Great, will fix this

> On the other properties, I am cautious about OCDS having a community extension to cover this as:
> ...
> If there is an immediate need for this, I would suggest it is take forward as part of the local Paraguay extensions, 

Great, understood, will treat these as local extensions.

Many thanks

**Comment by timgdavies** [comment]
@juanpane My understanding is that this is all complementary/compatible with the [ocds_budget_and_spend proposals](https://github.com/open-contracting/standard/issues/483#issuecomment-421423087), and as local extensions will just be something for us to be aware of in next upgrade process / if in future someone want to do the same as Paraguay (in which case it could move to be community extension). 

As result, I'm proposing closing this issue: but if you think it should be kept open for future community extension or OCDS upgrade work, do please re-open.
