### ISSUE TITLE
Name fragmentation

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#637]
## Issue

In Mexico it is usual to capture the first name (with middle name when applicable) and the surname (with the father’s surname and the mother’s surname) in a separate way. In the case of transparency obligations, it is mandatory to publish these data in separate fields. Likewise, we need to maintain the name of an organization in another separate field, in order to diference them with individuals.

We would be publishing the information of individuals that need this fragmentation in the case of `possibleSuppliers` `tenderers` `clarificationMeetingAttendee` `suppliers` `payee` and some others. 

>**Update:** 
>This individuals participate in the contracting process by themselves, not as a part of an organization.

At this time, we have not found a simple solution for this. The only proposal that we have it is to add these new fields in the organization section as follows:

## Proposal

- Parties [array]
  - Organization {object}
    - name (mapping as exclusive field to capture the name of an organization instead of individuals)
    - firstName (string, null)
    - fathersSurame (string, null)
    - mothersSurname (string, null)

Do you think these fields need to be within the indentifier section or have another proposal?

> UPDATE: You can access to this extension at INAI's [repository](https://github.com/contratacionesabiertas/ocds_nameBreakdown_extension).

**Comment by timgdavies** [comment]
The place we anticipate individuals' information appearing is within `parties.contactPoint`

This is currently defined as:

> "A person, contact point or department to contact in relation to this contracting process." 

and has a `name` field.

In terms of where to locate the data, is this sufficient for your needs? Or do you need different semantics in terms of the nature of the people identified? 

In terms of the break-down of name parts, there is an approach in the [draft Beneficial Ownership Data Standard here](http://beneficial-ownership-data-standard.readthedocs.io/en/master/schema.html#alternatename) that uses:

* `fullName` - The full name contains the complete name of a person as one string.
* `givenName`  - the same as 'firstName' above
* `familyName` - 'mothersSurname' in the Spanish context
* `patronymicName` - 'fathersSurname' in the Spanish context

which was selected based on existing standards, and aiming to have something with global relevance.

**Comment by timgdavies** [comment]
I'm not sure yet if this should be considered for a community extension. I'd welcome views from other data creators or users who capture names as to whether they would be able to map names to this pattern, or whether they collect names according to a different pattern.

**Comment by jpmckinney** [comment]
I agree with `givenName`, `familyName`, `patronymicName` which are used by Schema.org, W3C, EU ISA, etc. but I'm not sure that having both a `name` and a `fullName` is very clear. Why not just a `name`?

**Comment by antonioherrera** [comment]
@timgdavies I would like to revisit the issue about which individuals would be captured in the cases mentioned above. I think I didn't explain that we are considering this extension for the individuals that will be `tenderers` `suppliers` or `payees` by themselves, not as a part of the contact point of an organization.

In this case, do you think that this fragmentation/breakdown should be incuded as a part of the indentifier section or should be included within the `parties.contactPoint` object?

@jpmckinney I just review the references that you mentioned and I agree with using this approach, but I'm not sure if `familyName` can be related as the "mother's surname" in the hispanic context. I think that `familyName` would be the whole surname of an hispanic person (Gomez Rivera).

I recon this should be a local extension, given that it is a very specific need for hispanic countries. However, I think some other latin american contries could be interested in it.

**Comment by timgdavies** [comment]
Thanks @antonioherrera. If the use of this breakdown is as part of identifying the individual, then I can see a strong case for including it was part of the `parties.identifier` block. 

I'm reviewing the definitions from the [Person Vocabulary](https://www.w3.org/ns/person) and the notes at https://www.w3.org/International/questions/qa-personal-names to see if there is wider consensus on how `familyName` and `patronymicName` are used in Hispanic contexts. I had assumed that as this was in an EU backed vocabulary, where Hispanic context would be important, they would have established an approach to this.

**Comment by jpmckinney** [comment]
If it is mandatory to split the parts into different fields, we can simply add a `matronymicName` field to the above proposal, which would match the pattern of `patronymicName`. I agree that `familyName` is intended to include both parts and not just one.

I think W3C and EU didn't add additional properties, because if a `familyName` has at most two parts, then whatever is not the `patronymicName` would be the mother's surname. Alternately, if the order of names is consistent (e.g. paternal+maternal), then having both in `familyName` would be sufficient.

The `Identifier` object seems an appropriate place to add these fields for this use case. Either that, or the `Organization` object itself.

**Comment by ScatteredInk** [comment]
Based on https://en.wikipedia.org/wiki/Naming_customs_of_Hispanic_America, it looks like the ordering of paternal-maternal can't be guaranteed in all jurisdictions (although, at this stage, we may only be talking about children). The legal obligation to name children this way may change in the future in other jurisdictions.

Given that, the separate `matronymicName` and `patronymicName` fields seems like the most robust suggestion to me.

But, I would also want a `fullName`, or equivalent, field in there as well. Spain requires all citizens, including naturalised citizens, to adopt two surnames using the paternal-maternal pattern. It's not clear to me that this is the case here or would be universally applicable. I've spotted a thread of people being naturalized in Mexico with their birth or passport names and the OECD suggests that ["most"](http://www.keepeek.com/Digital-Asset-Management/oecd/taxation/global-forum-on-transparency-and-exchange-of-information-for-tax-purposes-peer-reviews-mexico-2014_9789264217751-en#page71) individuals have paternal and maternal surnames. And, while this is more relevant for cross-border use-cases, that OECD source also notes that identification/matching can be unreliable if two incompatible naming systems are in use.

**Comment by jpmckinney** [comment]
To my knowledge, the existing `name` field is sufficient for the use cases for `fullName` – please correct me if otherwise!

**Comment by timgdavies** [comment]
Just a quick note that from January through April 2018 the EU are inviting change requests to the Core Vocabularies, including the Core Person Vocabulary

From a recent e-mail, they say: 

> "we are also inviting you to contribute change requests for any of the Core Vocabularies which will allow us to plan future releases of the vocabularies. These change requests will be treated according to the maintenance process described in the document Description of a change management release and publication process for structural metadata specifications developed by the ISA Programme at  https://joinup.ec.europa.eu/node/155875."

An issue tracker for the Core Person Vocabulary is here https://github.com/SEMICeu/Core-Person-Vocabulary/issues

This might give us an opportunity to discuss the issues arising here with others who have experience of implementing name-based fields and data management across Europe.

**Comment by jpmckinney** [comment]
@antonioherrera I did an initial review of the [extension](https://github.com/INAImexico/ocds_nameBreakdown_extension), and @JArielMG merged the changes. Would you like this extension to be added to the [extension registry](https://github.com/open-contracting/extension_registry) as a community extension?

**Comment by antonioherrera** [comment]
Sure, go ahead.

**Comment by jpmckinney** [comment]
`contactPointType` should be abbreviated to `type` (we don't repeat the object name in the field name), though I think the term `role` might better fit the concept here.

I'm not sure that `juridicalPersonhood` is the correct term, as a "juridical person" means an artificial person. I'm not sure this concept belongs in the `Identifier`.

To add this extension as a community extension, it might be easiest to keep it narrow, and focused on the `givenName`, `patronymicName` and `matronymicName` fields.

**Comment by antonioherrera** [comment]
I just reviewed this extension and removed `contactPointType` field and codelist, because they are defined in another [extension](https://github.com/INAImexico/ocds_contactPointType_extension). I changed the `juridicalPersonhood` term to `legalPersonality.` I think this is helpful to differentiate between organizations and individuals in the parties array.

Or maybe this could be a separate extension?

**Comment by jpmckinney** [comment]
@antonioherrera I am not sure that givenName, patronymicName and matronymicName belong in the `Identifier` object. That object is presently defined as an organization identifier. We can consider changing that, but it would be a change for OCDS 1.2.0, at least.

We might want to pursue that discussion in #801 (about identifiers for natural persons) and in #883 (about how to describe natural persons in OCDS).

If the extension were split in two, we could add an extension that only modified the ContactPoint object to the Extension Registry.

**Comment by jpmckinney** [comment]
Continuing in #801 and #883.
