### ISSUE TITLE
extendedProcurementCategories: Add 'worksRelatedServices' code

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#638]
From the email that I sent to the helpdesk:

> We have a question about the categorization that must have the services related to works that are done in Mexico. Related to the translation process of the codelist, specifically in “procurementCategory” we see three options: goods, works and services. In Mexico, there are two laws in order to regulate the contracting process: the Law of Acquisitions, Leases and Services of the Public Sector (LAASSP) and the Law of Public Works and Services related to them (LOPSRM).
>  
> This means that the goods and services (contemplated by the LAASSP) and the public works and services related to them (contemplated by the LOPSRM) are considered separately. With this, the question is how to categorize services related to public works, which generally refer to "works designed to conceive, design and calculate the elements that make up a public works project; research, studies and consultancy.”
>  
> In particular, should services related to public works be categorized as works or as services?

And, form the Tim's answer:

> Note though that in OCDS 1.1 we have two fields that can be used:
>  
> mainProcurementCategory - which must be one of goods, works or services as Marcella describes
>  
> additionalProcurementCategories - which can be an array (multiple options), and which is an open codelist, that means if there was a specific need in Mexico to additionally classify these cases as 'services related to public works'  then that information could go **in the additionalProcurementCategories array, with an appropriately invented code**.

This is fundamental in order to categorize this kind of services.

**Comment by timgdavies** [comment]
As the `tender.additionalProcurementCategories` codelist ([extendedProcurementCategory](http://standard.open-contracting.org/latest/en/schema/codelists/#extended-procurement-category) [[es](http://standard.open-contracting.org/latest/es/schema/codelists/#extended-procurement-category)]) is an open codelist, you are free to add to this without needing a change to the standard.

If you would like to see a code for `worksRelatedServices` to this list you are free to do so as part of a local extension. We would generally not expect to have a community extension to just add to an open codelist. 

I would welcome views from other data publishers or users on whether this code should also be included in the open ([extendedProcurementCategory](http://standard.open-contracting.org/latest/en/schema/codelists/#extended-procurement-category) codelist as part of the next version of OCDS (1.2)

The proposed definition for this from above would be: 

> "works designed to conceive, design and calculate the elements that make up a public works project; research, studies and consultancy.”

**Comment by jpmckinney** [comment]
[This local extension](https://github.com/INAImexico/ocds_extendedProcurementCategory_extension/blob/master/codelists/%2BextendedProcurementCategory.csv) adds codes to the codelist.

**Comment by jpmckinney** [comment]
As I am unclear on the general applicability of this code, and given that no other publisher has participated in this issue, I will close, though we can reconsider inclusion at a later date if the code is reused by others.
