### ISSUE TITLE
Buyer name required in OrganizationReference

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#639]
In OCDS 1.1 the OrganizationReference block has two non-deprecated properties:

* `id`
* `name`

It currently specifies that `name` is a required property, which causes data without a `name` to fail validation. 

This appears to be a bug as:

* (a) We generally require `id` values, but not strings;
* (b) There are legitimate cases where no `name` can be provided;

Following investigation to confirm that this is a bug, and check if there was any rationale for the original requirement being introduced that we've overlooked here, we should look at addressing this in a patch release. 

Removing the required property from `name` is anticipated to have minimal impact on existing applications.

**Comment by timgdavies** [comment]
Tagging @kindly who worked on required properties for OCDS 1.1, and @bjwebb who might have a quicker way than I do to work out how to 'git blame' and work out when we (I?) introduced this.

**Comment by jpmckinney** [comment]
It was done in #368.

On the other hand, it's not clear to me that requiring `id` was backwards-incompatible, as `id` was introduced to `Organization` in 1.1 and doesn't exist in 1.0 (whereas `name` already existed in 1.0). The evidence in #484 for the backwards-incompatibility of requiring `id` seems to be spurious?

**Comment by jpmckinney** [comment]
Wait – I had the logic backwards. Since `id` didn't exist in 1.0, it can't be required in 1.1! So that's fine.
