### ISSUE TITLE
Fix letter case of schema definitions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#641]
Change the case of the `record` definition in `record-package-schema.json` to `Record`.

(Noting that, among properties, `former_value` doesn't follow the lowerCamelCase pattern, but it's deprecated anyhow.)

**Comment by jpmckinney** [comment]
Actually, we can do this in 1.x, as changing the case won't invalidate 1.x data.

**Comment by jpmckinney** [comment]
Related #330

**Comment by yolile** [comment]
closed by #1241
