### ISSUE TITLE
Guidance: Improving milestone documentation and usage

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#644]
The milestone block is poorly documented, and publication of milestone information remains limited.

This issue describes the current situation and a number of issues arising - and invites input for future standard development.

## The current situation

The `Milestones` object can currently be used in the following places (listed with their schema definitions):

* `planning` - 'A list of milestones associated with the planning stage.' (Introduced in 1.1 - #373) 
* `tender` - 'A list of milestones associated with the tender.'
* `contract` - 'A list of milestones associated with the finalization of this contract.` (Introduced in 1.1 - #373)
* `contract.implementation` - 'As milestones are completed, milestone completions should be documented.'

In 1.1 we introduced `Milestone.type` and the [milestoneType](http://standard.open-contracting.org/latest/en/schema/codelists/#milestone-type) codelist. 

Version 1.1 also deprecated `Milestone.documents`.

## issues

There are a number of weaknesses of the current situation. Namely:

### Definitions

The object definitions lack detail. It's not clear from the definitions which block different milestones should be contained in. 

### Documentation

There is a lack of documentation of how milestone information should be used and displayed.

There are no reference examples of milestones in use. 

## Call for input

* Do you use milestones in your data? If so - which milestone blocks are you using, and how?
* Are you using milestone types or other features in your data? 
* What could be done to improve milestones?

**Comment by timgdavies** [comment]
I've [reviewed past issues on milestones](https://github.com/open-contracting/standard/issues?utf8=%E2%9C%93&q=is%3Aissue+milestones) and have found limited discussion of the intended semantics of milestones in different blocks.

However, I believe that:

* Milestones set out at the point a tender is issued should go into `tender.milestones`
* Delivery milestones agreed in the contract should go in `contract.implementation.milestones` and should be kept updated as things progress. (At the point of contract signature, a comparison between `tender.milestones` and `contract.implementation.milestones` with a `Milestone.type` of 'delivery' or 'reporting' should reveal how the negotiated contract differs from what was set out at tender time).
* The reference in `contract.milestones` to "finalization of this contract" comes from the PPP Profile, an was intended to cover key events preceding the signing of the contract, rather than those events involved in the actual **delivery** of the contract.

**Comment by jpmckinney** [comment]
As I remember from some helpdesk requests, milestones have been recommended to fairly flexibly express a variety of date-based facts. We can perhaps collect some use cases that way.

**Comment by timgdavies** [comment]
In #603 a definition for the `Milestone` object is introduced to the schema as:

> The milestone block can be used to represent a wide variety of events in the lifetime of a contracting process. The milestone type codelist is used to indicate the nature of each milestone.

The following additional text was not added there but could form the basis of guidance to be added to the schema or documentation in future.

> Milestones can be included within the planning, tender, contract and contract implementation blocks. The planning and tender milestone blocks may describe anticipated milestones during the proposed delivery of a contract, as well as key dates from the process of tendering and awarding the contract. The contract milestone block should be used for events related to the signing of the contract documents, with any milestones related to delivery of the contract placed in the contract implementation milestones block.

**Comment by timgdavies** [comment]
A definition for Value has been added [based on the current text in the reference documentation](http://standard.open-contracting.org/latest/en/schema/reference/#value).

> "Financial values should always be published with a currency attached."

**Comment by duncandewhurst** [comment]
> The planning and tender milestone blocks may describe anticipated milestones during the proposed delivery of a contract, as well as key dates from the process of tendering and awarding the contract. 

We should clarify this guidance further, to explain whether `planning/milestones` or `tender/milestones` should be used in the scenario where a planning system includes information on planned milestones during the tender process (e.g. the date on which responses to enquiries will be published).

I've been working on the assumption that this type of information should be provided in `tender/milestones` (even at the planning stage) however, if that's the case we should make it explicit, since the above guidance is unclear.
