### ISSUE TITLE
Schema definition of address

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#645]
Working on #603 and https://github.com/open-contracting/ocds-extensions/issues/40 has surfaced that we have definitions the wrong way around for the `Address` object and `Organization.address` property (previously missing). 

The `Address` object is currently defined as "An address. This may be the legally registered address of the organization, or may be a correspondence address for this particular contracting process."

The draft definition for `Organization.address` is "A physical or contact address for this party."

However, the `Address` object is also referenced by the location extension, in the context of `Location.deliveryAddress`, such that reference to 'organization' in `Address` is over-specific. 

I believe then the correct bug-fix I should have applied for #603 was to:

* Move the definition from `Address` to `Organization.address`, and add simply "An address." as the value of the description for the `Address` object

**Comment by jpmckinney** [comment]
That seems reasonable to me.

**Comment by jpmckinney** [comment]
Should the milestone be 1.1.x Cleanup (1.1.3, mostly bug fixes) or 1.1.x Clarifications (likely the release after that).

**Comment by timgdavies** [comment]
Cleanup - have updated.
