### ISSUE TITLE
Contracts database use cases

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#65]
Fields that could potentially be used:

* ocid
* language
* buyer name
* Planning budgetAmount
* Tender totalValue
* Tender method
* Tender procuringEntity name
* Award awardDate
* Award awardValue
* Award suppliers name
* Contract contractID

## Process
* There is no top-level "description" field in which to put a general description of the process. In the [Montreal Gazette contracts database](http://documents.montrealgazette.com/), the source data is principally one field that mentions the supplier, the contract value, the deliverables, etc. as free-text.
* Our source data says which decision-making body a process relates to. This is not the same as the buyer or the procuring entity.
* A process can be categorized as a subsidy, a professional services contract, property-related, etc. There's no way to classify the process as a whole. You can only classify items, which are fairly granular, and granular data is not always available - plus items only first appear in the tender stage.

## Planning

* We only know the date on which a call for tender was authorized and its selection criteria approved; we don't know the tender period.

## Award

* The award should have an attachments property so that I can link to the source document.
* The contract period may be known without knowing any other detail for the contract, e.g. I know that the City will subsidize an organization over 2010-2012. Perhaps a field should be added to Award.

## Budget

* As mentioned in #44, the important parts of the Budget Data Package should be imported into OCDS, so that I can say which program a process is funded by, e.g. "Programme de restauration de cénotaphes et de monuments".
* Processes can be related to e.g. "Développement et des opérations, Culture et patrimoine", a part of the administration. This relates to budget data, so perhaps it is covered by Budget Data Package.

**Comment by timgdavies** [comment]
Reviewing these issues for 1.1.

> There is no top-level "description" field in which to put a general description of the process. In the Montreal Gazette contracts database, the source data is principally one field that mentions the supplier, the contract value, the deliverables, etc. as free-text.

Opening an issue for this at #342

> Our source data says which decision-making body a process relates to. This is not the same as the buyer or the procuring entity.

This is picked up in #150 and #264

> A process can be categorized as a subsidy, a professional services contract, property-related, etc. There's no way to classify the process as a whole. You can only classify items, which are fairly granular, and granular data is not always available - plus items only first appear in the tender stage.

This is picked up in #204. 

> Planning
> We only know the date on which a call for tender was authorized and its selection criteria approved; we don't know the tender period.

This appears to me to be an edge case - and one that could be modelled with milestones. 

> Award
> The award should have an attachments property so that I can link to the source document.

Awards can have documents

> The contract period may be known without knowing any other detail for the contract, e.g. I know that the City will subsidize an organization over 2010-2012. Perhaps a field should be added to Award.

Award now contains a `contractPeriod` property. 

> Budget
> As mentioned in #44, the important parts of the Budget Data Package should be imported into OCDS, so that I can say which program a process is funded by, e.g. "Programme de restauration de cénotaphes et de monuments".
> Processes can be related to e.g. "Développement et des opérations, Culture et patrimoine", a part of the administration. This relates to budget data, so perhaps it is covered by Budget Data Package.

We have work planned on budget modelling.
