### ISSUE TITLE
Guarantees extension

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#651]
## Issue

Some procurement processes consider the specification of guarantees in order to ensure compliance with the terms of a contract.

There are many types of guarantees, so we consider the creation of a new extension based on the formats that are required for the Federal Treasury (Mexico).

**Guarantee type:**
- Bail
- Deposit slip
- Letter of credit
- Surety bond
- Check

**Guaranteed obligations**
- Fulfillment
- Prepaid
- Latent defects
- Confidenciality
- Quality

## Proposal

Add an array named "guarantees" with the following fields:

- Contract {object}
  - Guarantees [array]
    - Guarantee {object}
      - Id (string, integer)
      - Guarantee type (string, null) (codelist)
      - Guarantee date
        - Date [object]
      - Guaranteed obligations {array} (codelist)
      - Guarantee value
        - Value [object]
      - Guarantor
        - OrganizationReference [object]
      - Guarantee period
        - Period [object]

### Defining texts:

**Title** | **Description**
-- | --
`guarantees` Guarantees | A list of the guarantees given for this contract.
`guarantee` Guarantee | Information of the guarantee used to ensure compliance with the terms of a contract.
`id` Guarantee ID | A local identifier for this guarantee, unique within this block.
`guaranteeType` Guarantee type | Specify the guarantee type for this contract using the guaranteeType codelist (url).
`bail` Bail | A bail bond is a written promise by which a person agrees with the creditor to pay for the debtor, if he does not.
`depositSlip` Deposit slip | The deposit slip is an instrument used to establish cash guarantees available to judicial or administrative authorities.
`letterOfCredit` Letter of credit | Letters of credit are used to guarantee that a supplier will receive a specified amount of money within a specified time providing strict terms.
`suretyBond` Surety bond | A surety bond is an instrument through which the surety is obliged to compensate the obligee for the damages suffered in the event that the principal fails to comply with the terms of the contract.
`check` Check | A certified check as a form of guarantee.
`date` Guarantee date | The date of the guarantee. This is the date on which the guarantee is issued.
`guaranteedObligations` Guaranteed obligations | Specify the type of obligations that are guaranteed, using the obligationType codelist. (url).
`fulfillment` Fulfillment | Guarantees fulfillment in time with the conditions stipulated in the contract.
`prepaid` Prepaid | Guarantee by which the supplier requests a prepayment from the procuring entity.
`latentDefects` Latent defects | Guarantee on the possible defects that a good may have that are not discoverable through general inspection at the time of delivery.
`confidentiality` Confidentiality | Guarantee that commits the supplier to safeguard the confidential information that has been granted.
`quality` Quality | Commitment from the supplier to deliver the goods and services in the quality specified in the contract.
`value` Guarantee value | Total amount of the guarantee.
`guarantor` Guarantor | Name of the organization that issues the guarantee.
`guaranteePeriod`  Guarantee period | The period on which this quote is valid.

We'll appreciate all your views and comments.

**Comment by jpmckinney** [comment]
@antonioherrera I did an initial review of the [extension](https://github.com/INAImexico/ocds_guarantees_extension), and @JArielMG merged the changes. Would you like this extension to be added to the [extension registry](https://github.com/open-contracting/extension_registry) as a community extension?

**Comment by antonioherrera** [comment]
Sure, go ahead.

**Comment by yolile** [comment]
Honduras is going to use this extension now, could it be added as community extension? @jpmckinney

**Comment by jpmckinney** [comment]
Note: Ukraine also has a guarantees extensions: https://github.com/openprocurement/ocds_guarantee_extension

**Comment by jpmckinney** [comment]
In Ukraine's extension, the Guarantee is just a value. This extension is more complete.

@antonioherrera To include the extension as a community extension, I recommend removing the `guarantee` prefix from all `Guarantee` fields, and to remove the unused `patternProperties`. In OCDS, we avoid repeating the object's name on all its fields. Once that's done, I can add it to the registry.

@yolile In Honduras, I would recommend using a version of the extension that includes my changes. We can add that extension to the registry, if so.

**Comment by jpmckinney** [comment]
Noting that the changes were made: https://github.com/INAImexico/ocds_guarantees_extension/pull/2

I've now included the extension in the Extension Explorer: https://extensions.open-contracting.org/en/extensions/guarantees/master/

I notice a few rendering issues that we should fix. Mainly: GitHub-style Markdown tables are not supported by the Extension Explorer, but we can remove the table since this information is now available automatically at https://extensions.open-contracting.org/en/extensions/guarantees/master/schema/ and https://extensions.open-contracting.org/en/extensions/guarantees/master/codelists/

**Comment by jpmckinney** [comment]
Closing as the extension is now in the registry. This still needs to be fixed on the extension itself:

> I notice a few rendering issues that we should fix. Mainly: GitHub-style Markdown tables are not supported by the Extension Explorer, but we can remove the table since this information is now available automatically at https://extensions.open-contracting.org/en/extensions/guarantees/master/schema/ and https://extensions.open-contracting.org/en/extensions/guarantees/master/codelists/

**Comment by jpmckinney** [comment]
[UNCITRAL glossary](http://www.uncitral.org/pdf/english/texts/procurem/ml-procurement-2011/Glossary-e.pdf) defines:

ID | Term | Definition | Reference
-- | -- | -- | --
75 | Security for the performance of the procurement contract | Security against the breach of the procurement contract by the supplier or contractor concluding the procurement contract with the procuring entity, presented to the procuring entity by that supplier or contractor in the form and the amount and in accordance with other requirements (such as with respect to the nature of the security and the issuer) specified by the procuring entity in the solicitation documents. For the explanation of the terms “procurement contract” and “procuring entity”, see ## 59 and 62 above. For the explanation of the terms “supplier or contractor” and “solicitation document”, see ## 85 and 80 below. | performance security (the World Bank procurement guidelines)
87 | Tender security | Defined in the Model Law as: “Security required from suppliers or contractors by the procuring entity and provided to the procuring entity to secure the fulfilment of any obligation referred to in paragraph 1 (f) of article 17 of this Law and includes such arrangements as bank guarantees, surety bonds, standby letters of credit, cheques for which a bank is primarily liable, cash deposits, promissory notes and bills of exchange. For the avoidance of doubt, the term excludes any security for the performance of the contract.” For the explanation of the terms “supplier or contractor”, “procuring entity” and “security for the performance of the procurement contract”, see ## 85, 62 and 75 above. | bid security (the World Bank procurement guidelines)

[EBRD glossary](https://www.ppi-ebrd-uncitral.com/index.php/en/procurement-glossary) relates Tender security to Bid bond (US).
