### ISSUE TITLE
Surveillance mechanisms extension

### ISSUE THREAD

**Issue by antonioherrera** [open-contracting/standard#652]
## Issue:

In Mexico there are different surveillance mechanisms that testify the transparency and legality through all the contracting process.

## Proposal:

Add a new array field

_Codelist:_
- Social witness
- Citizen comptroller
- Internal control unit
- External auditor

_Schema:_
- Contract {object}
  - surveillanceMechanisms [array]

### Defining texts:

**Title** | **Description**
-- | --
`surveillanceMechanisms` Surveillance mechanisms | The surveillance mechanisms used in this contracting process. The mechanisms should be taken from the surveillanceMechanisms codelist (url).
`socialWitness` Social witness | Specialized citizens who participate in the surveillance of this contracting process.
`citizenComptroller` Citizen comptroller | Surveillance mechanism by beneficiaries to verify the works progress and the correct expending of public resources.
`internalControlUnit` Internal control unit | Body in charge of preventing, detecting, sanctioning and eradicating corrupt practices that may arise in this contracting process.
`externalAuditor` External auditor | Institution outside the public administration that performs an audit of this contracting process.

We'll appreciate all your views and comments.

**Comment by jpmckinney** [comment]
@antonioherrera I did an initial review of the [extension](https://github.com/INAImexico/ocds_surveillanceMechanisms_extension), and @JArielMG merged the changes. Would you like this extension to be added to the [extension registry](https://github.com/open-contracting/extension_registry) as a community extension?

**Comment by antonioherrera** [comment]
Sure, go ahead.

**Comment by jpmckinney** [comment]
After more research, I can't find evidence for this use case from other jurisdictions, so I've marked it as a local extension for now. If there is new demand for this extension from other jurisdictions, we can review again for inclusion in the extension registry. Thanks for submitting the extension for others to contribute to over time.
