### ISSUE TITLE
Bug in versioned-release-validation-schema.json

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#660]
.@kindly has identified a bug in [versioned-release-validation-schema.json](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/versioned-release-validation-schema.json#L10) which is omitting the object type from each versioned property. 

As JSON Schema validators only check for properties of objects, this means the fields of each versioned object have not been correctly checked. 

I.e., in the example below, the schema has correctly checked that `amount` is a property within the schema, but it has not validated the `releaseDate`, `releaseID`, `releaseTag` and `value` properties, such that an implementation that had, for example, misspelled these properties, or otherwise omitted them, would incorrectly be evaluated as valid. 

```json
{
  "amount": [
    {
      "releaseDate": "2016-01-01T09:30:00Z",
      "releaseID": "ocds-213czf-000-00002-01-tender",
      "releaseTag": [
        "tender"
      ],
      "value": 1000
    }
  ]
}
```

This is a result of a missing line in the [make_validation_schema.py](https://github.com/open-contracting/standard/blob/1.1-dev/standard/schema/utils/make_validation_schema.py#L14) script - which has been the case since the first version.

version-release-validation-schema.json is used within record-package-schema.json for publishers who provide `versionedRelease`.  

The impact of correcting this bug would be that record packages containing `versionedRelease` would be more strictly validated than has been the case to date. 

We are not aware of any currently published `versionedRelease` data. 

Our options here are to:

* **Fix versioned-release-validation-schema.json generation as part of a bug fix release (1.1.3)**. On a strict interpretation, this would involve a backwards incompatible change, as it would mean data that was incorrect against the documentation, but valid against 1.1.2 schema, could now become invalid against the schema also. However, it is still clearly a bug fix. 

* Fix versioned-release-validation-schema.json generation as part of an integer release (i.e. wait until 2.0). In this instance, we should introduce a warning to the OCDS validator for this edge case in the meantime. 

I'm leaning towards fixing in 1.1.3 - given *in practice* we don't think this will have any backwards compatibility issues for existing publishers, and any publisher who followed the documentation and guidance should not have data that would be invalid against the corrected schema. 

@jpmckinney thoughts?

**Comment by jpmckinney** [comment]
We've had some schema bugs that are non-obvious to implementers (e.g. not requiring `id` fields on objects in arrays), and which we therefore postponed to 2.0.

But this bug should be obvious, and we've diligently checked with affected publishers (which is none to our knowledge), so I consider it correctable in a patch release.

**Comment by jpmckinney** [comment]
I'd like to have a look at the fix in a PR before it's merged, though.

**Comment by kindly** [comment]
The fix is here:
https://github.com/open-contracting/standard/pull/663

However, travis is failing and I am not able to work out why.  It is not due to anything in this branch but a general failure with chrome webdriver which I have failed to fix.

**Comment by jpmckinney** [comment]
> As JSON Schema validators only check for properties of objects, this means the fields of each versioned object have not been correctly checked.

Really? This fails validation, yet there is no `"type": "object"`:

```python
from jsonschema.validators import Draft4Validator as validator
list(validator({"properties":{"foo":{"type":"string"}}}).iter_errors({"foo":1}))
```

**Comment by jpmckinney** [comment]
I can't find anything in the [spec](https://tools.ietf.org/html/draft-fge-json-schema-validation-00) that suggests that `"properties"` can be ignored if `"type"` doesn't contain `"object"`, so I'd consider a validator that does so to be non-conformant to JSON Schema. (The Python jsonschema package appears to be conformant in that respect.)

**Comment by kindly** [comment]
Phew, Yes you are right.  That is great news. This was due my misreading of the python jsonschema code here
https://github.com/Julian/jsonschema/blob/master/jsonschema/_validators.py#L295
it just checks the data not the schema for being type `object`.

Anyway it is good that we do not allow any type as a version block now.

**Comment by timgdavies** [comment]
Good to know it was only a false alarm. Are we good to just close this issue then and leave as-is. Or do you think we should still update the schema to be explicit with the object property?

**Comment by kindly** [comment]
I think @jpmckinney already merged it. I think it should be added as it means that you have to put an object in at these points At the moment you can put in any type and it will still be valid. 

I think this ticket can be closed.
