### ISSUE TITLE
Change the milestone icon

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#671]
Our current milestone icon 

![](https://raw.githubusercontent.com/open-contracting/standard/1.1-dev/docs/_static/svg/green_milestone.svg)

doesn't really represent milestones that well. 

A suggestion has been made we should update this using a flowchart symbol. 

This might form part of a wider update of our image and icon set.

**Comment by myroslav** [comment]
We can try to have something that is used in Gantt charts:

![039ee6ea-b034-43ce-8d2f-3403a5a0e514](https://user-images.githubusercontent.com/883905/36152218-27bc95a6-10c2-11e8-824b-3ec3cb6b5cef.jpeg)

**Comment by yolile** [comment]
what about something like: 

![image](https://user-images.githubusercontent.com/6834122/95986929-1b400700-0dfd-11eb-8154-df2906b5d0f1.png)

**Comment by jpmckinney** [comment]
Yes! Looks good.

**Comment by yolile** [comment]
Noticing that the first one is indeed the icon for milestones in Github eg
![image](https://user-images.githubusercontent.com/6834122/96014521-ddeb7180-0e1c-11eb-8cd7-61e8b53a6728.png)

**Comment by jpmckinney** [comment]
We don't use this icon anywhere anymore, so closing.
