### ISSUE TITLE
How should government leases be represented in OCDS?

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#672]
At least one OCDS user is exploring how to model cases of government leasing property to the private sector. 

This is raising a number of issues:

**(1) How to indicate that an contracting process relates to leasing of government property?**

In #638 which discusses `mainProcurementCategory` and `additionalProcurementCategories` there is some mention of leases. It would be possible to use `mainProcurementCategory` = 'services' and `additionalProcurementCategories` = 'Property Lease'. 

However, use of the term "procurement" implies that the government party is seeking to take a lease, rather than that the government party is offering a lease. 

An alternative may be to introduce properties at the top level of the release to indicate the case of a lease such as `release.procedureType` with an appropriate codelist. 

Views on this are welcome.

**(2) How to model particular features of a lease?**

Whilst the property being leased can be described using `items`, there may be features of a lease that need special description, such as:

* Lease duration;
* Break points;
* Points at which rates may be reviewed;
* Tax holidays offered.

There is also a suggestion that our `Period.durationInDays` property is not suitable to cases where durations are specified in months. This may provide grounds for an optional `durationInMonths` property for use with leases. 

There were discussions in #200 of how to handle potential break points or extensions, which resulted in `Period.maxExtentDate` in OCDS 1.1, but this does not handle the question of periodicity of contract review, such as contracts that specify the cost of the lease may be reviewed every six months. 

Views on the importance of standardising properties relative to tax holidays, or 'contract escalation' (which I've interpreted as the point at which rent levels can be reviewed and increased), are welcome, as well as examples of data from existing systems that could inform design work here.

**Comment by antonioherrera** [comment]
Actually, we are implementing this codes:

- goodsAcquisition
- goodsLease
- services
- worksRelatedServices
- works

In our legal framework, we have a classification like this.

**Comment by jpmckinney** [comment]
@antonioherrera Makes sense – if we hear from other jurisdictions, we can open an issue to add codes to extendedProcurementCategory.csv. Noting the extension with the new codes here: https://github.com/contratacionesabiertas/ocds_extendedProcurementCategory_extension/blob/master/codelists/%2BextendedProcurementCategory.csv

For the first question from the issue description, I think we are trying to describe the type of contracting process, not the type of procedure. The unused `initiationType` field might be suitable for indicating the type of contracting process.

(With respect to the procedure, our guidance is to use `procurementMethodDetails` to indicate the procedure and `procurementMethod` to indicate its high-level competitive conditions. `procedureType` is likely to be confused with these.)

It also might have been better to have named the field `mainCategory` not `mainProcurementCategory`. We can deprecate and rename such fields if we get more demand for non-procurement categories. However, that's a separate issue.

There has been no engagement on the second question of particular features of a lease.

As such, I will close this issue, but am happy to split it into the component issues I identified.
