### ISSUE TITLE
Publish codelists with the standard

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#673]
We presently publish schemas at standard.open-contracting.org, but not codelists. Codelists are presently only accessible at GitHub URLs.

~~Core extensions’ codelists should be included among the published codelists.~~

**Comment by timgdavies** [comment]
Agreed that we should switch to deploying the codelists alongside the versioned schemas. 

I think we have also talked about potentially providing them in a zip file / a zip of schema + codelists for applications that want easy access this way.

**Comment by jpmckinney** [comment]
Assigning to myself to use same approach as for PPPs.
