### ISSUE TITLE
Minor issues in package schemas

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#677]
Missing title/description:

* [x] release-package-schema.json is missing /properties/releases/description
* [x] record-package-schema.json is missing /properties/publisher/title
* [x] record-package-schema.json is missing /definitions/record/description
* [x] record-package-schema.json is missing /definitions/record/properties/releases/oneOf/0/items/properties/url/title

Need to check whether it makes sense for these to be nullable, etc.:

* release-package-schema.json has optional but non-nullable array at /properties/extensions
* record-package-schema.json has optional but non-nullable array at /properties/extensions
* record-package-schema.json has optional but non-nullable array at /properties/packages
* record-package-schema.json has required but nullable ['string', 'null'] at /definitions/record/properties/releases/oneOf/0/items/properties/url
* record-package-schema.json has optional but non-nullable array at /definitions/record/properties/releases/oneOf/0/items/properties/tag

**Comment by duncandewhurst** [comment]
Whilst working on this I noted a typo in the record reference documentation which I fixed in https://github.com/open-contracting/standard/pull/713

**Comment by duncandewhurst** [comment]
I don't think that fields in the release and record packages should be nullable, since merging only applies to the fields in the release itself, not the package metadata. Maybe @kindly can confirm?

**Comment by jpmckinney** [comment]
@duncandewhurst Ah, yes, package schema follow different rules. I do notice that most of the fields are nullable or non-nullable based on whether they are required or not, with only the above exceptions. 

While on the topic, It's not clear to me that `null` should be a valid value for any of these, though it's not a significant issue (and we can't go back and change that now anyway).

I'll remove the nullability check from standard-maintenance-scripts for package schema – though if we want to follow rules for nullability going forward, I can restore that functionality.

**Comment by kindly** [comment]
@duncandewhurst @jpmckinney 
Yes I agree the release/record package fields should probably not be nullable as the merging does not happen to them.

**Comment by jpmckinney** [comment]
Resolved in #712.
