### ISSUE TITLE
Unnecessary blocks in templates?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#678]
If a block only calls `super()`, is it necessary?

In layout.html:

```
{% block extrahead %}
    {{ super() }}
{% endblock %}
```

In footer.html:

```
{% block extrafooter %}
    {{ super() }}
{% endblock %}
```

@Bjwebb I assume you know?

**Comment by Bjwebb** [comment]
Yes, these are not necessary.

**Comment by jpmckinney** [comment]
Removed in branches of standard and ppp profile, and remove from profile template.
