### ISSUE TITLE
Correct the explanation of 'unique' with respect to release IDs and tender, award and contract IDs

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#682]
http://standard.open-contracting.org/latest/en/schema/identifiers/

> The tender, award and contract IDs must be unique within the contracting process it is part of.

> For any given ocid, there should be no two tender, award or contract IDs that refer to different tender, award or contract sections respectively.

The second paragraph is confusing, because two (different) IDs can of course refer to two different sections.

The second paragraph either needs to be rephrased or removed.

Originally reported by @colinmaudry via Transifex.

**Comment by duncandewhurst** [comment]
I noticed the same issue with the explanation of uniqueness for the Release ID:

> Within any release or record package and for any given ocid, there should be no two release IDs that refer to different releases.

I've updated the issue title to reflect that.

**Comment by jpmckinney** [comment]
@duncandewhurst Can you suggest new wording, perhaps based on any improved wording in OC4IDS?

**Comment by duncandewhurst** [comment]
For tender, award and contract IDs:

> The tender, award and contract IDs must be unique within the scope of the contracting process they are part of: for example, this means that across all OCDS data published under a particular `ocid`, each contract ID refers to exactly one contract.

For releases:

> The release ID must be unique within the contracting process it is part of and within any given data package it is part of; this means that across all OCDS data published under a particular `ocid`, or as part of a particular release package, each release ID refers to exactly one release only.
