### ISSUE TITLE
Search in the docs doesn't support using quotes to find an exact match

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#683]
For example [this search](http://standard.open-contracting.org/latest/en/search/?q=%22compile+releases%22&check_keywords=yes&area=default) for

> "compile releases"

returns the same results as searching without the quotes for

> compile releases

rather than returning the [release reference](http://standard.open-contracting.org/latest/en/schema/reference/) page, which includes the exact text "compile releases", first.

**Comment by jpmckinney** [comment]
Sphinx compiles a `searchindex.js` file to perform search on client-side – which is clever, but severely limited. There is an upcoming documentation sprint to consider alternatives (perhaps an ElasticSearch backend).

**Comment by jpmckinney** [comment]
Fixed via referenced sprint.
