### ISSUE TITLE
Images display incorrectly when viewing the docs in a window

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#684]
For example, on the [identifiers](http://standard.open-contracting.org/latest/en/schema/identifiers/) page, when viewed in full screen the icon is small and right aligned

![image](https://user-images.githubusercontent.com/19265814/38649048-95b8e592-3e48-11e8-8658-29d7c96be981.png)

But when viewed in a window 960px wide:

![image](https://user-images.githubusercontent.com/19265814/38649082-c105722e-3e48-11e8-8786-49cc493171df.png)

**Comment by jpmckinney** [comment]
For me it occurs when narrower than 768px. We likely need to fix a media query for images.

**Comment by jpmckinney** [comment]
@duncandewhurst I can't seem to reproduce anymore. Can you test again, and provide steps to reproduce, and browser with version number?

**Comment by jpmckinney** [comment]
Nevermind – I underestimated how small I had to resize the window.

**Comment by jpmckinney** [comment]
Closed by https://github.com/open-contracting/standard_theme/commit/99f2e2f99a4c36d8c3056a5c849ec711e5dea3b2
