### ISSUE TITLE
Tender: Procurement Method Modalities extension

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#695]
## Motivation

The [Revised Agreement on Government Procurement](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm) (GPA) includes: "each notice of intended procurement shall include … f. the procurement method that will be used and whether it will involve negotiation or electronic auction".

The new EU eForms and [Directive 2014/24/EU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv:OJ.L_.2014.094.01.0065.01.ENG) have many requirements related to procurement method modalities (mostly taking the form of a tick box and sometimes one additional field), which will be described in the proposed extension to avoid an overlong motivation section here.

## Discussion

When building a form for people to fill out, it makes sense to use tick boxes, like in eForms. OCDS, however, is not a form template; as long as forms can translate to OCDS and back without information loss, we are free to pursue other modelling options.

Using a list with a large number of possible entries (as in the proposal below) instead of adding a large number of boolean fields lowers the complexity of the standard through encapsulation.

An initial list of procurement method modalities is described in https://github.com/open-contracting/standard/issues/322#issuecomment-325137100

The proposed extension would establish a new pattern (which will be used in other draft extensions) of `xModalities`. Like the existing `xDetails` pattern, it allows for the addition of additional detail to the base field (e.g. `procurementMethod`). Whereas `xDetails` are free-text fields, `xModalities` fields will be arrays of codes, indicating different 'modes' of the base field, e.g. for procurement method, two possible modes will be to involve 'negotiation' or 'electronicAuction'.

## Proposal

Example:

```json
{
  "tender": {
    "procurementMethodModalities": [
      "joint",
      "negotiated"
    ]
  }
}
```

[Earlier](https://github.com/open-contracting/trade/blob/master/draft_extensions/tender_JointProcurement) [proposals](https://github.com/open-contracting/trade/blob/master/draft_extensions/tender_AcceleratedProcedure) used boolean fields for some modalities and overloaded `procurementMethodDetails` with too much responsibility, which could lead to loss of machine-readability and to inconsistent or poor implementation.

**Comment by jpmckinney** [comment]
Draft extension: https://github.com/open-contracting-extensions/ocds_procurementMethodModalities_extension

**Comment by duncandewhurst** [comment]
Draft data from Belarus publishes a codelist in `procurementMethodDetails` with the following values:

* Request
* Auction
* Other
* Trade
* negotiations
* contractingTrades
* eTrade

Helpdesk feedback recommended to map this to the methodModality codelist and propose new codes where necessary.

**Comment by jpmckinney** [comment]
As it turns out, the particular modalities under consideration required more structure than simple codes in an array, and they were also not semantically related to each other. The codes in `methodModality.csv` are now served by:

* accelerated: https://github.com/open-contracting-extensions/ocds_procedure_extension
* electronicAuction: https://github.com/open-contracting-extensions/ocds_techniques_extension
* joint: the presence of multiple parties with a 'buyer' role
* negotiated: indicated in `procurementMethodDetails`
* optionally negotiated: https://github.com/open-contracting-extensions/ocds_secondStageDescription_extension
* staged: https://github.com/open-contracting-extensions/ocds_secondStageDescription_extension
