### ISSUE TITLE
Tracking implementation of properties

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#70]
As explained in #60, if there are no implementations for a property, that property may be a candidate for removal (other considerations as in @practicalparticipation's [comment](#issuecomment-55749988) may keep it in). Here's [a script](https://github.com/opennorth/ocds-conformance) to check which properties releases use. For brevity, not all unused fields are listed in this issue description.
- To do: Check use of codes in code lists (enum) as in [IATI Dashboard](http://dashboard.iatistandard.org/codelists.html)
## [Development Gateway](https://github.com/devgateway/ca-app-ocds-export)

The DG data doesn't have any planning, contracts or performance fields. Within buyer, formation and awards, there are some unused fields as well.
## [buyandsell.gc.ca sample](https://github.com/open-contracting/sample-data/tree/master/buyandsell/ocds_data)

(Note: Didn't process the full 1GB JSON.) No planning or performance fields. Within buyer, formation, awards, contracts, there are some unused fields as well. [Conformance issues](https://github.com/open-contracting/sample-data/issues/1)

**Comment by timgdavies** [comment]
@kindly Can you review this conversation - and consider if there is anything we can do with data from CoVE (OCDS Validator) or any other tools to analyse current usage of properties across the standard, and to identify properties currently heavily or lightly used.

This may also be something @ekoner could explore through a sprint of research on our existing data.

**Comment by timgdavies** [comment]
@ekoner has worked on a manual analysis of properties currently in use across a sample of files. This is something we will look to develop automated tooling for in future, particularly building on the new [API specification](https://github.com/open-contracting/api-specification) to support harvesting of data.

The [analysis is available here](https://docs.google.com/spreadsheets/d/1EGW9cZjpV8BD0mMWRoGk0PdDWovuyPS-OXg69AI_BsE/edit?ts=577f859e#gid=1532441756). 

This highlights:
- No use of documents at the contract implementation, and implementation milestone level
- No use of transaction fields in implementation to record actual payments
- Limited use of amendment fields
- Limited use of additional identifier fields

Specific fields that do not occur in our sample include:
- planning/budget/description
- planning/budget/id
- planning/budget/projectID
- planning/budget/source
- planning/budget/uri
- planning/rationale
- tender/awardCriteriaDetails
- tender/minValue/currency
- tender/submissionMethodDetails

However, we have encountered a number of planning blocks in draft data, not included in the analysis, so consider that planning should not be considered for deprecation.

We should investigate use of `awardCriteriaDetails` and `submissionMethodDetails` in more depth to see if these should be proposed for removal.

## Implications
- We should consider removing `documents` from `milestones`. This does not appear to be used, and adds an extra level of depth and complexity to the standard.
- We should consider the use cases for `transactions`. There is a case to say it remains early days to see integration of spend data into OCDS, but this remains desirable. However, if there is an indication that it is prohibitively complex, or could be better handled by revised engagement with the Fiscal Data Package we should consider this.

**Comment by LindseyAM** [comment]
@gabelula can you remind us - is there documents associated with milestones in the cdmx data?

**Comment by timgdavies** [comment]
A new phase of implementation research is currently planned and we'll open a new thread with results.
