### ISSUE TITLE
Links to core extension point to /1.1 not /latest

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#702]
In the [list of core extensions](http://standard.open-contracting.org/latest/en/extensions/#core-extensions) in the docs, the links to the extension documentation pages point to /1.1 not /latest, e.g.

http://standard.open-contracting.org/1.1/en/extensions/bids/ rather than http://standard.open-contracting.org/latest/en/extensions/bids/

This isn't a problem now since latest = 1.1 but will be a problem when the next minor or major update occurs

**Comment by duncandewhurst** [comment]
Assigning to @Bjwebb as seems similar to https://github.com/open-contracting/standard/issues/501

**Comment by Bjwebb** [comment]
This ultimately comes from https://github.com/open-contracting/extension_registry/blob/v1.1.3/bids/extension.json#L3 (which is then [compiled](http://standard.open-contracting.org/extension_registry/v1.1.3/extensions.json)).

I assumed the plan was to replace these with 1.2 when we come to pinning extensions.

@timgdavies How would you feel about replacing actual urls with templated ones, as we do for the schema?

**Comment by jpmckinney** [comment]
I think we can wait for the extension registry re-design, which may change the potential solution.

**Comment by jpmckinney** [comment]
Extensions are responsible for their `documentationUrl`. The use of `1.1` is correct for the deployed documentation, which is in the `1.1` minor series. When releasing core extensions for e.g. `1.2`, we will have to update the `documentationUrl` of core extensions accordingly (though it is likely to point to the separate extensions explorer website).
