### ISSUE TITLE
Notes on translation of OCDS Validator, Schema and Extensions

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#704]
This ticket is to log a number of issues that may subsequently be split into separate tickets for our work on improved extensions registry and documentation updates. 

## The current situation

* The OCDS Validator displays error messages based on the contents of the schema
* The OCDS Schema is used to generate documentation and mapping templates

The documentation generates a translated version of the schema at:

    http://standard.open-contracting.org/latest/[LANG]/release-schema.json

However, only the English language schema is provided in the folders at:

    http://standard.open-contracting.org/schema/1__1__3/

When users reference an extension, they use an absolute URL to the extension.json

    {
       "extensions":["https://raw.githubusercontent.com/open-contracting/ocds_bid_extension/v1.1.3/extension.json"],
    
    }

This points to a single language version of the extension. 

Whilst translation of the core schema [happens directly](https://github.com/open-contracting/standard/blob/1.1-dev/include/common.mk#L41) and prior to documentation being built, extensions contents is translated along with the rest of the documentation. 

## Issues

* When the validator draws upon the schema to provide error messages, it does not use the translated schema. 
* We cannot generate translated schema of extensions from the current workflow
* Extensions are brittle: if a file is removed from GitHub, existing data validation might break

## Suggestions

* We cache all extensions, and providing URLs for them at a standard location, such as standard.open-contracting.org/ext/[name]/[ver]

* We move translation for extensions **into the extensions repos themselves**, so that we can generate translated schema and documentation for extensions where translation is provided.

* We support **content negotiation for language** so that, when the validator is requesting schema files, it can request translated copies. 
  * This may have wider architectural consequences for the validator in terms of language switching?

**Comment by Bjwebb** [comment]
> When the validator draws upon the schema to provide error messages, it does not use the translated schema.

Note that validation error messages generally aren't translated (https://github.com/OpenDataServices/cove/issues/986), so using the translated schema is just one part of fixing this.

> We cannot generate translated schema of extensions from the current workflow

To get something rough and ready for this is a few hours work. I can look into that this week if that's useful.

> Extensions are brittle: if a file is removed from GitHub, existing data validation might break

Additionally if people link to a branch on GitHub, then data validation may break due to changes to the schema (this may be deliberate or accidental).

> We cache all extensions, and providing URLs for them at a standard location, such as standard.open-contracting.org/ext/[name]/[ver]

I understand this suggestion, as it's exactly what registries like PyPI do. However, I think this could be quite a bit of work to get right. It's probably useful for me and @kindly to spend a bit of time thinking about what the options here are.

> We move translation for extensions into the extensions repos themselves, so that we can generate translated schema and documentation for extensions where translation is provided.

This makes sense. Not sure how best to set this up with transifex.

> We support content negotiation for language so that, when the validator is requesting schema files, it can request translated copies.

This makes sense.

> This may have wider architectural consequences for the validator in terms of language switching?

The trickiest thing is generating the results page for the user's language. Do we need to bust the caches every time language changes? What about when two users with different languages loading the same page?

**Comment by timgdavies** [comment]
> > We cannot generate translated schema of extensions from the current workflow

> To get something rough and ready for this is a few hours work. I can look into that this week if that's useful.

This would be useful I believe to @duncandewhurst for work on updated mapping templates - yes please.

**Comment by timgdavies** [comment]
> The trickiest thing is generating the results page for the user's language. Do we need to bust the caches every time language changes? What about when two users with different languages loading the same page?

Good questions indeed. I would think the behaviour we would *like* would be something like:

* User A switches to Spanish interface, and loads a file to validate
* User A sees the results in Spanish
* User A shares the link with User B who visits the site in English
* User B can see results in English, whilst User A is still seeing Spanish

This might mean that some of the information needs caching in **both** languages. It depends I guess on whether we need to *revalidate* the file with the translated schema to get new messages for the interface, or whether we can fetch these out at a later stage.

**Comment by jpmckinney** [comment]
> We move translation for extensions into the extensions repos themselves, so that we can generate translated schema and documentation for extensions where translation is provided.

Maintaining dozens of extension repositories is already a pain I've only solved through lots of automation. Let's instead work on https://github.com/open-contracting/extension_registry/issues/86 which is to build a separate documentation website for all extensions (perhaps extensions.open-contracting.org). That website can have a single Transifex project for all versions of all extensions. It can also "cache all extensions, and providing URLs for them at a standard location".

**Comment by timgdavies** [comment]
> That website can have a single Transifex project for all versions of all extensions. 

I can see a couple of potential issues here that we might want to consider:

**Versioning of translations**

Transifex doesn't work that well for versioned content. We've had to create a new project for each version of the standard - and to have a process for copying past translations across to this. 

By contrast, if we were picking up translations committed into the repo with each tagged release of an extension, then the versioning of translations is handled in GitHub along with versioning of the extension. 

**Responsibility for translations**

We only want to be responsible for translation of core extensions - not community translations. It would be good if extension authors can have the option of maintaining their own translations.

We could offer to 'adopt' some community extensions in cases where the author is not interested in this, by, for example, being added as a maintainer for them, so we can merge in translations. 

**Re-usability of translations**

If translations are included along with the extension in a .po, then it's possible for systems working with the extensions directly to use their own tooling to generate translated schemas. 

If translations are all in one central repo, then things may be more brittle.

**Comment by jpmckinney** [comment]
To clarify the vision of the proposed new documentation website: There will be a page for v1.1 of the bids extension, for v1.1.1 and for v1.1.3. In other words, all releases of all extensions are all built in a single build.

One implementation option would be to create a 'profile' that pulls in the documentation for *each* release of *all* extensions. We currently do this in existing profiles for a *single* release of *some* extensions; it would not be challenging to do it for multiple releases. The repository might be structured as e.g. `docs/extensions/bids/v1.1.3/index.md` which will have a corresponding Transifex resource like `extensions--bids--v1.1.3--index`. Two resources will also be created for (1) schema and (2) codelists for each release of each extension. We already have scripts to build the POT files for those two resources for a *single release* of the standard; we would re-use and edit the scripts to build POT files for *each release* of each extension.

So:

* Versioning of translations: This is handled by having, in a single project, Transifex resources (corresponding to e.g. README.md, schema, and codelists) for each release of an extension. Past translations are easy to copy across within the project.  We wouldn't have to create a new Transifex project for each version of OCDS.
* Responsibility: We can follow the same process as for community translations of OCDS. Translators for community translations currently contribute to the same Transifex project that we use for supported translations. I don't see an issue with allowing translators to contribute in the same way to the Transifex project for the proposed new documentation website.
* Reusability of translations: I don't see how things may be more brittle, but I do see how it may take an extra step to work with the extension directly. There is presently very low demand for this, though.

If we were to instead have each extension manage its own translations, consider that the [extension template](https://github.com/open-contracting/standard_extension_template) would have to resemble something much closer to the [profile template](https://github.com/open-contracting/standard_profile_template) with files to pull in software requirements, instruct Babel on where to find schema and codelists, build POT files, ignore built files, store translations, configure Transifex if it is used, configure Sphinx if it is used, etc. I like the simplicity of the extension template.

Also, remember that we have about 33 extensions that we've authored ourselves, which will double if I end up having the same number of EU extensions as Simon, and I don't see how directing translators to dozens of Transifex projects is a desirable system. Having them all in one project, I think, is lower complexity in terms of managing and operating the translation process.

It's complicated enough for implementers to author an extension, even when it's just JSON, CSV and Markdown files that can be edited by hand. Expecting people to properly implement a gettext-based translation system, that we can then integrate into our documentation without error or issue, seems unreasonable.

Furthermore, it hasn't yet been articulated how we'll build an extensions documentation website (which was expressed in February as desirable) from all these independent pieces, but I suspect it is complicated or at least involves writing a lot of new code, whereas my above proposal involves a lot of reused code.

Anyhow, if we want to pursue a system in which each translation is responsible for its own translated text, then I would recommend that a member of the ODS tech team draft a note describing the advantages and disadvantages of different approaches, working out all the pain points.

**Comment by robredpath** [comment]
Warning: this may be a terrible idea. 

Is there scope for grouping extensions in some way that reduces the number of individual projects but still allows us to treat certain groups of extensions differently?

**Comment by jpmckinney** [comment]
@robredpath What would be the reason to group some extensions but not all extensions (as in my proposal)?

**Comment by jpmckinney** [comment]
This has largely been taken forward through tech work (https://github.com/open-contracting/extensions-data-collector, https://github.com/open-contracting/extension-explorer). Issues will be opened as appropriate when ready to make changes to the standard's documentation.
