### ISSUE TITLE
Bank Account Codes

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#705]
For one implementation of ProZorro Sale, there is a proposal to collect data on the account details of the state entity selling an asset, to facilitate payments at the end of the process. 

This raises a question of whether OCDS should have an extension or approach to representing bank account details. Whilst at present I don't see a strong use-case for bank account details being included in the OCDS extensions directory, I thought it would be useful to consider and document here the best idiomatic way to model bank account details.

## Research

[Financial Industry Business Ontology (FIBO)](https://spec.edmcouncil.org/static/glossary/production.html) describes a 'Bank Account' as "identified by at least one occurrence of account identifier", where an identifier is defined by "exactly one occurrence of identification scheme.". 

This suggests that account identification can be via a single value, or via the combination of multiple values (e.g. Bank code, Routing code, Account code)

The [Open Banking APIs](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/129040604/Accounts+v2.0.0) provides a single string for bank identification, along with a 'scheme', (with the codelist values of 'IBAN', 'PAN' and 
'SortCodeAccountNumber') such that it suggests a composite of sort code and account numbers into a single string. This would require the string to be parsed to extract information such as the bank sort code. 

The Open Banking APIs do, however, include a 'SecondaryIdentification' field, documented as "This can be used by building societies to additionally identify accounts with a roll number (in addition to a sort code and account number combination)." which suggests a single field is inadequate in some situations.

In Ukraine, three kinds of account codes were proposed:

* EDR ( ? )
* MFO ([Bank identification code](https://it.toolbox.com/question/ukraine-bank-key-022912))
* AccountNumber

 all of which appear relevant to the identification of an account.

## Idiomatic approach

The following is a proposal for an idiomatic representation of bank account details in OCDS, using the approach of:

* Explicit field names (`bankAccount` as opposed to `account`)
* Using an array of identification blocks with `scheme` and `identifier`

```json
{
   "bankAccount":{
        "description":"",
        "bankName":"",
        "accountIdentification":[
             {
                 "scheme":"UA-MFO",
                 "id":"300711"
             },
             {
                 "scheme":"accountNumber",
                 "id":"2600000625637"
             },
         ]
      }
}
```

As we're not proposing detailed standardisation now, unless there is greater demand, there is no intention here to create a codelist of the schemes, but rather to allow individual implementations to set these. 

**Update:** I've removed UA-EDR from the example above, as this is an [organisation identification code](http://org-id.guide/list/UA-EDR), not an account identification.

**Comment by PaulBoroday** [comment]
If we look a little broader, State Entity selling something - it’s just a participant of a process who launch this process (very similar to CA who launching contracting process to buy something, isn’t it?). From another hand on some step the second party appears in the process - buyer (in a sales case). This party defenetly have own requisites which they use for mutual settlements within the contracted contract (doesn’t matter - sales or procurement) and in some cases according to requirements of the process these data should also be disclosed. 

My point is that account details can be applied (and in fact already apply to the implementation of electronic contracts in Molodova, for example) and for other Entities involved in the process: not only Payer and Payee but also Review Body (in Prozorro, for example, there is a payment for submission of complain) or NEPP who charge participants to submit a bid or even CPB who charge CA for conducted FA. May be there are a lot more exotic examples, not sure at the moment. 

From that point of view it would be useful to be able to use a similar object as an attribute of ‘Organization’ that allows to describe account details for all participants of Process. Even more, in some cases it’s an array of such attributes (Entity can use several account to operate within responsibilities under contrac - again, seller or buyer - doesn’t metter).

Further, there is a real need to link the budget allocated for covering the concluded contract with the data on the accounts used by Parties and the breakdown of total amount of funds on these accounts. Given that the contract can be covered from budgets of different organizations (the buyer himself + donor, for example) - this task is not so simple :)

Next step from roadmap of implementation of electronic payments - transactions under contract should include information about the account (or accounts) used by Entity to provide such transaction. 

As you can see this topic more wider than just a possibility to describe 5 fields for needs of specific implementation. And from my point of view this issue deserves a deeper discussion and maybe as a result -  own extension

**Comment by timgdavies** [comment]
Thanks @PaulBoroday - this is really useful. I'm reading these are general reflections, rather than a specific demand for extensions right now?

As I understand from this:

* We might want to make `bankAccount` details a property of an `Organization` 
* There may be cases where `bankAcount` information is useful for tracking budgets (though in general we might address this through our planned budget extensions in the works, which could be used to relate payments to budget lines)

For the full workflow of electronic payments, this remains outside scope of OCDS at the moment - but something to keep under review. 

I still sense that, until there are a few more clearly articulated use-cases for `bankAccount` information, we should hold fire on extension development - but will keep this issue open.

**Comment by jpmckinney** [comment]
Noting that Kyrgyz also has bank information (`accountName`, `accountNumber`) (CRM-5594).

**Comment by myroslav** [comment]
I'd like to note that [Ukraine completed switch](https://bank.gov.ua/en/iban) to `IBAN` as primary `bankAccount` scheme on 2020-01-13. With this switch MFO "disappeared" as separate entity, and is embedded into IBAN now.

Additionally there is initiative to implement payment requests that are based upon QR codes. The format of the data encoded in the QR code is LF-separated info for Credit Transfer Initiation, somewhat following **[EPC069-12](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC069-12%20v2.1%20Quick%20Response%20Code%20-%20Guidelines%20to%20Enable%20the%20Data%20Capture%20for%20the%20Initiation%20of%20a%20SCT.pdf) - Quick Response Code: Guidelines To Enable Data Capture For The Initiation Of A SEPA Credit Transfer** issued by [Conseil Européen des Paiements AISBL](http://www.epc-cep.eu/). The primary difference of Ukrainian initiative is the use of `UCT` (Ukrainian Credit Transfer) as Identification code, instead of `SCT` (SEPA Credit Transfer) and introduction of additional Beneficiary identification field (usually already mentioned UA-EDR code). The requirement to include identification information of beneficiary is coming from law of Ukraine "[About Payment Systems and Funds transfer in Ukraine](https://zakon.rada.gov.ua/laws/show/2346-14)" (aticle 22, paragraph 22.6). This is the reason why identification code of organization should always accompany bankAccount information (without it transfer can be considered to be violating the Law of Ukraine).

The National Bank of Ukraine has not standardized the format yet, but it is being started to be used already (with couple of proprietary alternatives in use as well).

**Comment by jpmckinney** [comment]
I generally agree with the sentiment that this seems somewhat outside the scope of OCDS.

We also currently only have evidence from Ukraine (the account name/number for Kyrgyz in my earlier comment was of a treasury account), which makes it a challenge to standardize this concept globally.

As an intermediate solution, bank account numbers can either be added as additional identifiers for organizations, or can be disclosed through local extensions.

Closing as not having accumulated sufficient evidence for standardization after several years.
