### ISSUE TITLE
Should the standard recommend content negotiation for all uris?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#706]
Descriptions of `uri` fields in the schema aren't consistent about whether uris should point to machine readable and/or human readable resource.

Should `uri` field descriptions consistently state that uris should point to a machine and human readable resource?

**Example**

The description of the the `planning/budget/uri` field states:

> A URI pointing directly to a **machine-readable record** about the budget line-item or line-items that fund this contracting process. Information may be provided in a range of formats, including using IATI, the Open Fiscal Data Standard or any other standard which provides structured data on budget sources. **Human readable documents can be included using the planning.documents block**.

Whilst the description of the `contract/implementation/transaction/source` field states:

> Used to point either to a corresponding Fiscal Data Package, IATI file, or **machine or human-readable source** where users can find further information on the budget line item identifiers, or project identifiers, provided here.

**Comment by jpmckinney** [comment]
I don't think we can *require* content negotiation (even in 2.0), as I don't think implementers will have that capacity for a while. We can, however, describe content negotiation as a best practice in the 1.x series.

As I understand, there are few cases where we specifically require either machine- or human-readable resources, and I think for the time being we should stick with that, given that in many cases, when a procurement agency links out to another resource, they have no control over its format.

**Comment by jpmckinney** [comment]
I agree with my earlier comment. In terms of priority, I don't think a worked example for content negotiation is high priority for the reasons previously mentioned. Closing absent new demand.
