### ISSUE TITLE
documentType: Align tenderNotice definition with WTO GPA

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#714]
The WTO [GPA](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm#articleI) has the following definition for notice of intended procurement.

> **notice of intended procurement** means a notice published by a procuring entity inviting interested suppliers to submit a request for participation, a tender, or both

The OCDS `documentType` codelist has the following definition for 'tenderNotice':

> The formal notice that gives details of a tender. This may be a link to a downloadable document, to a web page, or to an official gazette in which the notice is contained.

Should the OCDS definition be more closely aligned with the GPA definition to make it clear the notice is the invitation to suppliers to participate in the process?

> The formal notice *giving details of a tender and inviting interested suppliers to submit a request for participation, a bid, or both.* This may be a link to a downloadable document, to a web page, or to an official gazette in which the notice is contained.

**Comment by jpmckinney** [comment]
OCDS glossary:
> Notice by which a procuring agency announces the beginning of the tender stage of a procurement process.

Where 'tender stage' is defined as:
> Stage in which the procuring agency calls and receives bids from interested parties, evaluates bids. During this stage the procuring agency may amends documents related to the call. 

e-Procurement Ontology:
> An announcement of the launch of a procurement procedure by a procuring entity.

Where 'procedure' is defined as:
> A series of legally defined administrative steps conducted to conclude one or more contracts.

GPA:
> a notice published by a procuring entity inviting interested suppliers to submit a request for participation, a tender, or both

OCDS code description (first clause only):
> The formal notice that gives details of a tender.

The ePO glossary is vague about the relevant steps that follow a tender notice, whereas the OCDS glossary is overly verbose about the relevant steps (if the additional definitions are integrated). The GPA definition gets to what matters without fuss (getting suppliers to bid).

**Proposal:**
* Adopt the GPA text for the first clause of the OCDS code description, using definite articles instead, and replacing "tender" with the unambiguous "bid"
* Remove "that gives details of a tender" as this (1) uses "tender" which is ambiguous even within the scope of OCDS (can mean a stage, an opportunity, etc.) and (2) is unnecessary as no one would imagine that the tender notice invites suppliers to bid, but fails to describe on what they are bidding.

**Comment by jpmckinney** [comment]
Closed by #725
