### ISSUE TITLE
Split out the record and record package schemas

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#716]
Currently the standard has the following schema files:

* release-schema.json
* release-package-schema.json
* record-package-schema.json

The record schema is embedded within the record package schema.

Since the structure of a record is an important concept and to make the distinction clearer between releases and records and their packages, I think it would be preferable if the record schema was split into a separate record-schema.json file.

The documentation could be updated too so that there are separate record schema and record package schema viewers, as with releases.

This would mean the docs and the schema files were consistently structured across both releases and records.

**Comment by jpmckinney** [comment]
An issue that should perhaps be resolved at the same time: #330

**Comment by duncandewhurst** [comment]
@jpmckinney are you still planning to action this issue or should I address it as part of https://github.com/open-contracting/standard/pull/1640?

**Comment by jpmckinney** [comment]
@duncandewhurst You can go ahead. Thank you!

**Comment by duncandewhurst** [comment]
> An issue that should perhaps be resolved at the same time: #330

Since #1640 now groups a bunch of package-related changes, I figure it makes sense to do #330 separately. Let me know if you think differently.

**Comment by jpmckinney** [comment]
Yes, we can do it separately
