### ISSUE TITLE
Guidance: 'Data protection by design' notes to ContactPoint and suppliers

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#720]
With the [EU General Data Protection Regulations](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) now in force we may want to consider updates to guidance on `ContactPoint` and other places where personal data could be included in a release, to highlight that publishers should carefully consider whether or not to include information here. The grounds to consider this would be:

* Making sure we have no blocks to implementation of OCDS in the EU due to a perception of conflict between out 'open by default' approach to **public data**, and a 'privacy by default' approach to **personal data**;
* Setting out clear guidance to avoid over-zealous application of a privacy default leading to loss of public data from OCDS publications;
* Taking the EU GDPR as good practice principles, and likely to influence global norms, and so a good basis for improving responsible data practice around OCDS;

[This slide deck](https://publications.europa.eu/documents/3841574/0/Wed_12_10_Work%28DT%29_Baryn_Privacy+policy.pdf/) highlights the main concerns may relate to personal names and name-containing e-mail addresses. In addition, I can see / we have seen potential issues around: 

* Name and address of sole-trader suppliers;
* Small businesses registered at home addresses;
* Inclusion of personal data in tender descriptions (e.g. purchase of air fares for specific named individuals when publishing direct award data);

There are also [suggestions on slide 5](https://publications.europa.eu/documents/3841574/0/Wed_12_10_Work%28DT%29_Baryn_Privacy+policy.pdf#page=5) that systems should keep track of who they have shared data with in order to notify those parties of changes to data / redactions. We should consider whether guidance around this issue will also be necessary.

**Comment by LindseyAM** [comment]
@JachymHercher under GDPR do TED or EU governments have any obligation to withhold any 'personal' data from procurement publications (or otherwise take special steps with regard to that data)?

**Comment by timgdavies** [comment]
The explanations from Aija Bilzena and Marcin Baryn (from the EU Publications Office) in session earlier today noted:

- The European Union institutions do not yet have to comply with GDPR as they are governed by separate regulations. However, there are reforms in progress that are likely to 'copy/paste' the GDPR principles, if not exact operation;
- There may be an obligation on authorities to remove / anonymise existing as well as future data and the number of requests for this have been increasing.

**Comment by jpmckinney** [comment]
I have not been able to validate a need for this content.

In terms of protecting privacy, Member States don't need to be reminded of their obligations. (Similar for privacy legislation in other jurisdictions.) They are already applying any obligations to their existing disclosures.

In terms of promoting disclosure (i.e. preventing over-cautious redaction), that is an advocacy goal that is unlikely to be accomplished through technical documentation (e.g. addressing the wrong audience).

(Related #1141)

**Comment by jpmckinney** [comment]
Some context from a recent eForms technical workshop: https://op.europa.eu/en/web/ted-eforms/minutes-4th-eforms

> Q: Why is the phone number and email address of the winner mandatory? There might be problems with privacy rules in our country. Is there a legal basis for making this fields required? 
> Answer: These are organization contact details which aren’t private unless the organization does not want to do business. This information is normally also available on the organization website as well at the trade office register. No personal contacts are to be included.  


> Q: What is difference Organization and Beneficial owner. It’s not very clear from the documentation in developer's doc when we need to add Beneficial owner. 
> Answer: Ultimate Beneficial Owner is an optional organisation role. Given recent court cases, it should only be used if the buyer is sure that they can collect and publish this personal data.
