### ISSUE TITLE
itemClassificationScheme: Add code for sale of assets

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#722]
The [ProZorro Sale](https://prozorro.sale/) team are exploring classification schemes to use as part of asset sales. 

The [Common Procurement Vocabulary (CPV)](https://simap.ted.europa.eu/cpv) doesn't provide the required codes, which need to cover things such as:

- Real Estate
- Residential Real Estate
- Apartment in a low-rise residential building
- Apartment
- Ealing
- Penthouse
- Multi-level apartment
- Communal apartment
- Cottage
- Industrial Property
- Manufacturing plant
- Integral Property Complex
- Land etc.

These codes would be used by a number of users:

- eMalls. Platforms implement these codes on the interface of their web sites making the list more user-friendly.
- Organizers. Having something to be privatized within the system, they should create that object within the Registry. By doing this, an organizer indicate what specifically is to be privatized. Apart from giving title, description, address etc., an organizer has to classify what actually this object is (e.g. factory, land area or sth else) by using a defined list of classifiers.
- Bidders & viewers. They use the classifiers implicitly by searching the property to be sold.
- Analysts. Classification codes are essential for data analysis (e.g. to indicate which objects are of the greatest demand).

The ProZorro Sale team have [created the 'CAV-PS' list as a stop-gap measure](https://github.com/openprocurement/standards/blob/master/classifiers/cav_v2/uk_pretty.yaml) to cover the categories they need in the short-term (only available in Ukranian right now, but Google Translate gives a good sense, an extract pasted below). 

However, they are interested in knowing if there are other established classifications they could use or map to? 

## Extract of CAV-PS (machine translated)

Selected codes from [CAV-PS](https://github.com/openprocurement/standards/blob/master/classifiers/cav_v2/uk_pretty.yaml) to give a sense of the list sought

04000000-8: Real estate
04100000-9: Residential Real Estate
04110000-2: Apartment in a low-rise residential building
04111000-9: Apartment
04112000-6: Townhouse
04123000-6: Multi-level apartment
04130000-8: Dormitory, residential building of the corridor, including gallery, hotel type (house for small families) and its parts
04131000-5: Communal apartment
04132000-2: Room in the hostel
04140000-1: Garden (cottage) house low-rise housing construction
04141000-8: House in a cottage cooperative
04142000-5: House in a garden cooperative
04150000-4: Manor (individual) house of low-rise housing construction
04151000-1: Cottage
04152000-8: House ownership
04200000-0: Commercial real estate
04210000-3: Industrial Property
04211000-0: Industrial factory, factory building and parts thereof
04212000-7: Building of a warehouse, a hangar, etc. and their parts
04213000-4: Garage, service station, vehicle washing, parking, gas station, etc., and parts thereof
04214000-1: Building for the maintenance of animals, for the preparation of feed and the like and their parts
05110700-6: Vegetable storage
05110800-7: Service Stations
05110900-8: Cafes, restaurants
05111000-6: Meat processing enterprises
05111100-7: Chemical industry enterprises
05111200-8: Enterprises of the machine-building industry
05111300-9: Enterprises of the woodworking industry
06000000-2: Land
06121000-6: Agricultural lands
06122000-3: Lands of natural reserve fund and other nature protection purposes
06123000-0: Lands for recreational purposes
06124000-7: Lands for recreational purposes
06125000-4: Lands of historical and cultural destination
06126000-1: Lands for forestry purposes
06127000-8: Earth Water Fund
06128000-5: Lands of industry, transport, communication, energy, defense and other purposes
06129000-2: Lands of land, reserve fund and general use
07000000-9: Rights requirements for loan agreements
07100000-0: Credits of Legal Entities
07110000-3: Credits Legal entities are unsecured
07120000-6: Loans Legal persons mortgages
07121000-3: Pawn - Real estate
07122000-0: Pledge - An integral property complex or property complex - a complex of assets of the enterprise
07123000-7: Pledge - Land
07124000-4: Zastava - Agricultural machinery
07125000-1: Pledge - Industrial Engineering

**Comment by JachymHercher** [comment]
Just a few pointers that could perhaps be useful - no idea whether they can acatually match ProZorro Sale's needs.

Public (EU's, UN's, etc.) classifications: 
- [Statistical classification of products by activity (CPA)](http://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Statistical_classification_of_products_by_activity_(CPA))
- The sub-classification of CPA, [PRODCOM](http://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:PRODCOM).

(We are considering using these to replace the CPV.)

Private classifications (used for example in electronic catalogues) such as https://www.eclass.eu/en.html

**Comment by jpmckinney** [comment]
My brief review of CPA suggests that it's for good, works and services – not for assets like cottages, etc. https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_NOM_DTL&StrNom=CPA_2008&StrLanguageCode=EN&IntPcKey=&StrLayoutCode=HIERARCHIC

Same for eCl@ss http://www.eclasscontent.com/index.php

My brief review of PRODCOM suggests that it's for manufacturing of goods: https://ec.europa.eu/eurostat/ramon/nomenclatures/index.cfm?TargetUrl=LST_NOM_DTL&StrNom=PRD_2017&StrLanguageCode=EN&IntPcKey=&StrLayoutCode=HIERARCHIC

As such, this issue contains no proposed code for a classification scheme for assets to add to the codelist. I am therefore closing it – though we will of course appreciate related proposals in the future.
