### ISSUE TITLE
relatedProcess: Add 'planned' code

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/standard#730]
The [relatedProcess](http://standard.open-contracting.org/latest/en/schema/codelists/#related-process) codelist has an entry for 'planning' to point *upwards* from a tender to the contracting process in which it was planned. But it does not have an entry for pointing from a planning process to the tenders that resulted from it. 

This would be important for cases where a publisher wants to show the procurement resulting from a particular planning process.

**Comment by timgdavies** [comment]
I propose 'planned' as the code to use in these cases, described as:

> The contracting process results from the planning that took place within this process.

**Comment by jpmckinney** [comment]
@duncandewhurst This issue seems very similar to #476. My understanding is that the codelist code suggested in each issue has the same semantics as the other. What's your opinion? If the same, we can close this issue.

**Comment by duncandewhurst** [comment]
Agreed, the semantics are the same.
