### ISSUE TITLE
Update the description of uri in the package metadata

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#735]
The current description for the `uri` field is

> The URI of this package that identifies it uniquely in the world. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.

Many implementations do not use the full releases and records implementation model and instead maintain a single release per contracting process, updating it whenever anything changes.

As such providing a URI which is a unique identifier and which is also a link to a persistent copy of the package containing a given release is not possible, since the package referenced at the URL will changes each time it's constituent releases are updated.

We should consider updating the description of `uri` to reflect the usage of the field, e.g.

> The URI from which this package was retrieved. Recommended practice is to use a dereferenceable URI, where a persistent copy of this package is available.

**Comment by jpmckinney** [comment]
My understanding was that packages can change, e.g. a paginated API (`http://example.com/packages?page=1`) or a bulk download (`http://example.com/packages.json`) can respond with a package – with both of these changing as more releases are published.

So, I'm not clear on the need to change the definition. "The URI of this package that identifies it uniquely in the world" remains true; such packages are uniquely identified, insofar as their URL is a URI, which is a unique identifier in the namespace of the web.

**Comment by duncandewhurst** [comment]
I had understood the uniqueness of the identifier to imply the immutability of the package identified by it, prompted by the NSW Australia implementation, where the field was left blank with that rationale.

I've advised the publisher to provide the url from which the package was retrieved in that field, so thought that might be a useful clarification to make in the description.

**Comment by jpmckinney** [comment]
Releases should be immutable, but I'm not aware of an intention for packages to be immutable (at least, I don't know where this is expressed).

In general, a unique identifier need not imply immutability, e.g. a social insurance number uniquely identifies an individual, though that individual nonetheless changes over time.

I'm unclear on "The URI from which this package was retrieved". If a package is generated and then made available at a URL, in what sense was it retrieved? Do you mean "can be retrieved" (though that would imply that the URI is a URL, which is not necessarily the case)?

**Comment by duncandewhurst** [comment]
Yes "can be retrieved" makes more sense, but since the intended clarification causes more problems than it solves I'll close the issue.
