### ISSUE TITLE
make_validation_schema.py creating different data for 1.1.2 vs 1.1.3

### ISSUE THREAD

**Issue by kindly** [open-contracting/standard#737]
Due to ```unit``` now having type ```["object", "null"]``` not just ```object``` the make_validation_schma.py is producing different schemas in 1.1.2 vs 1.1.3.
This is making the 1.1.3 version of versioned-release-validation-schema.json backwards incompatible with the 1.1.2 one.

**Comment by jpmckinney** [comment]
Closed by #738
