### ISSUE TITLE
Add links to canonical schema URLs from documentation pages

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#742]
e.g. http://standard.open-contracting.org/schema/1__1__3/release-schema.json

A quick search suggests there aren't any such links from documentation pages (except in the `id` properties of any rendered schema). At the very least, this issue is to make these URLs more prominent, to increase the likelihood that they are used instead of convenience schema URLs like http://standard.open-contracting.org/latest/es/release-schema.json, for which there are links from documentation pages ([example](
http://standard.open-contracting.org/latest/es/schema/release/)).

**Comment by jpmckinney** [comment]
@duncandewhurst From your recent work on OC4IDS, is there a recommended specific page (or pages) on which the canonical schema URLs should appear in the OCDS docs?

**Comment by duncandewhurst** [comment]
As with OCDS, in OC4IDS the canonical URLs are only used in the `id` properties of the schemas.

In OCDS, the [release schema](http://standard.open-contracting.org/latest/en/schema/release/) and [release package schema](http://standard.open-contracting.org/latest/en/schema/release_package/) pages seem like the best place to provide the canonical URLs.

I suggest adding an admonition below the 'download this version of the schema here' paragraph, along the lines of:

> Use the following canonical URL to link to the OCDS schema from any documentation, resources or tools that refer to specific elements or features of the schema: http://standard.open-contracting.org/schema/1__1__3/release-schema.json
>
> Using the canonical URL means that your links will always refer to the same version of the schema and the link will remain valid even if the structure of the OCDS documentation changes.
