### ISSUE TITLE
Clarify how release/id in a compiled record should be populated

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#745]
The schema for a compiled release includes the `release/id` property, but it's not clear whether this field should be provided and how it should be populated since `"omitWhenMerged": true` and the merging rules state

> These properties should be dropped from the merged record - as they only make sense in the context of a single release.

**Comment by jpmckinney** [comment]
My understanding is that it shouldn't be populated in `compiledRelease`.

**Comment by jpmckinney** [comment]
Marking duplicate of #330.
