### ISSUE TITLE
Extension - Parties detail - Legal entity type 

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#748]
There are many types of business entities defined in the legal systems of various countries. These include corporations, cooperatives, partnerships, sole traders, limited liability companies and other specifically permitted and labelled types of entities. The specific rules vary by country and by state or province. [1]

Colombia needs to publish the type of legal entity of each supplier, so the following partie/details/legalEntityType (as free text) extension  is proposed:

```javascript
{
"releases":[
    {
       "parties":[
          {
            "id": "GB-COH-1234567844",
            "name": "AnyCorp Cycle Provision",
            "details":{
               "legalEntityType":"Sociedad Anónima Cerrada Colombiana"
            }
          }
       ]
    }
]
}
```

Or determine a close codelist for the general types (legalEntityType) and have an extra field: legalEntityTypeDetail for the specific name of each country:

```javascript
{
"releases":[
    {
       "parties":[
          {
            "id": "GB-COH-1234567844",
            "name": "AnyCorp Cycle Provision",
            "details":{
               "legalEntityTypeDetail":"Sociedad Anónima Cerrada Colombiana",
               "legalEntityType":"company"
            }
          }
       ]
    }
]
}
```

Ref
[1] https://en.wikipedia.org/wiki/List_of_legal_entity_types_by_country

**Comment by jpmckinney** [comment]
For the EU context, I [propose](https://github.com/open-contracting-extensions/european-union/issues/10) adding `Organization.details.classifications` (an array of Classification objects). In the EU, it'd be used to describe the type (ministry, local authority, etc.) and main activity (health, education, etc.) of the organization, using the schemes 'TED_CA_TYPE' and 'COFOG' respectively. I think this proposed new field (which would be in an extension) can also be used to describe the type of legal entity. There is no global scheme for company types, so each country would need to use its own scheme.

I'm closing this in favor of #711, which I've renamed to accommodate the broader discussion.
