### ISSUE TITLE
Discovery mechanisms: APIs and .wellknown approaches

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#75]
Along with providing a method for representing Open Contracting data, we need to provide an approach for the discovery of data. This issue has been linked to discussions of whether there should be an API standard along with the data standard.

From conversations with @jenit and the initial technical scoping carried out by Jeni, the following approach seems likely to be useful:
- The [/.well-known/](http://tools.ietf.org/html/rfc5785) RFC offers a potential discovery mechanism
- An open-contracting file at  /.well-known/open-contracting on a server would contain a set of link-relations to point to URLs for getting:
  - A list of releases
  - A list of records
  - A specific release
  - A specific record
- These files should re-use existing standards for providing a list of records. One possible standard is [Atom](http://tools.ietf.org/html/rfc4287) (although this is XML based - may need to check for JSON based alternative?) which through [RFC5005](http://tools.ietf.org/html/rfc5005#section-3) already incorporates methods for pagination. 

This provides the very basic properties of a discoverable API (for lists at least), whilst allowing that publishers may use different URIs for access to data itself. We may need to add some basic recommended search parameters that list URIs should accept in the query string - but should check (a) these are vital for our use cases; and (b) whether any existing standards exist that we could defer to on this also.

**Comment by jpmckinney** [comment]
Copying comment from a translator in Transifex:

> regarding the data.json I really believe a more open approach should be used, especially if OCP is willing to deal with EU countries. For the discovery something more close to the DCAT-AP (https://joinup.ec.europa.eu/solution/dcat-application-profile-data-portals-europe) should be considered.
