### ISSUE TITLE
Make an XML serialisation (and schema) for the standard

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#76]
From the public discussion list, Willem van der Westhuizen wrote:

>I would suggest that JSON models also be consumable in XML. There are two primary motivations

>1. It is much easier for human reading, and the conversion can be fairly automated.
>2. There are fairly strong schema tools available to validate the structure of data provided. When you are dealing with data interchange formats, such as the one suggested, I believe that strong schema validation capabilities are critical for data integrity.

**Comment by timgdavies** [comment]
We have not had further demand for XML over the last year. Closing. Can re-open if requested.
