### ISSUE TITLE
Planning notice for sole source contract

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#760]
Sharing this Sidewalk labs example from Illinois. While there isnt much by way of structured data, you can see from the attached documents how there could be. Also good practice to publish planning information about direct contracts (interested to know how prevalent this is as a good practice) 

cc @jpmckinney https://webapps.dot.illinois.gov/WCTB/ConstructionSupportNotice/BulletinItem/0ff7ba88-81f7-4cd8-b24b-bc153d493725?page=1

Sharing as we might want to put more examples in the documentation to be more prescriptive in terms of emphasizing good practice and most useful publication.

**Comment by jpmckinney** [comment]
@LindseyAM Do you mean the Sole Source Justification Form? I think the rationale would be summarized in `tender.procurementMethodRationale` and then linked in `tender.documents`. We can show that as an example. If there were other things to consider, can you describe in more detail?

**Comment by jpmckinney** [comment]
I assume that answers the question, @LindseyAM.
