### ISSUE TITLE
Unit release reference documentation seems to be missing some data

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#761]
I think there's some info missing for [unit in the release reference docs](http://standard.open-contracting.org/latest/en/schema/reference/?highlight=unit#unit).

The tbody tag appears to be empty.

Should it list scheme, id, name, value, and uri fields?

**Comment by jpmckinney** [comment]
When I build the documentation locally with the latest version of sphinxcontrib-jsonschema, the rows are displayed, so it's possible that the bug was fixed by https://github.com/OpenDataServices/sphinxcontrib-jsonschema/pull/14

I'll close the issue when 1.1.4 eventually gets deployed.

**Comment by jpmckinney** [comment]
I tested again on 1.1-dev branch and it's indeed fixed. Closing, as I forgot that the process was to close issues as they are fixed – not wait until deploy.

**Comment by myroslav** [comment]
When do you plan to release? Im asking because we repetedly are hitting the missing `Unit` reference in `latest` version of docs.

**Comment by jpmckinney** [comment]
Hi @myroslav, I expect in the next month, but you can view the development version of the docs in the meantime: http://standard.open-contracting.org/1.1-dev/en/schema/reference/#unit
