### ISSUE TITLE
Add statusDetails field to Tender, Award, Contract

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#764]
Mentioned in #758, #430, #395, and the closed #616, #248, #197.

Additionally, when "The contract/lot is not awarded", the EU standard forms have a choice between:

◯ No tenders or requests to participate were received or all were rejected
◯ Other reasons (discontinuation of procedure)

These can be represented in an `Award.statusDetails` field, which was also suggested by [Data Unlocked](https://github.com/open-contracting-archive/trade/tree/master/draft_extensions/contract_statusDetails).

**Comment by jpmckinney** [comment]
Note: Ukraine adds tender.pendingCancellation (boolean) and tender.lots.pendingCancellation (boolean) in https://github.com/openprocurement/ocds_pendingCancellation_extension

**Comment by jpmckinney** [comment]
cc @yanakapatsila

**Comment by jpmckinney** [comment]
Dhangadhi has some statuses with local meanings, that would be useful to preserve.

cc @duncandewhurst

**Comment by yolile** [comment]
> Dhangadhi has some statuses with local meanings, that would be useful to preserve.

In Paraguay DNCP too

**Comment by yolile** [comment]
Extension that add these fields available here: https://gitlab.com/dncp-opendata/ocds_statusdetails_extension

**Comment by ColinMaudry** [comment]
@jpmckinney Shall we fork DNCP's extension (above) for the EU profile?

In the DNCP, the field definition is not quite fit for the EU context:

> The local name of the award status

...whereas in the EU context, it's about giving details on how the award got to the current `status` (examples in the first comment).

If we make a new extension, we could make the field's semantics broad enough to cover both use cases. For instance, mimicking the description of `procurementMethodDetails`:

> Additional detail on the status of the award. This field can be used to provide the local status name for award status.

**Comment by jpmckinney** [comment]
Can you make a PR on the DNCP's extension? For the description, to even more closely match the structure of `procurementMethodDetails`:

> Additional detail on the status of the award. This field can be used to provide the local name of the status.

**Comment by ColinMaudry** [comment]
MR opened on the DNCP extension: https://gitlab.com/dncp-opendata/ocds_statusdetails_extension/-/merge_requests/1

**Comment by jpmckinney** [comment]
@ColinMaudry I think there's extra text in Tender.statusDetails (unless GitLab's diff is bad) and an extra space in Award.statusDetails.

@yolile Can you review the PR?

**Comment by ColinMaudry** [comment]
Right! I'm trying to master Vim, and that creates this sort of problems. Fixing it.

**Comment by yolile** [comment]
Merged!

**Comment by jpmckinney** [comment]
I've now added the extension to the registry.

**Comment by jpmckinney** [comment]
We can do a worked example based on contract suspension (#758). #430 has some more elaborate proposed structure for suspensions. In the worked example, we can at least mention those details.

**Comment by ColinMaudry** [comment]
Created an [MR](https://gitlab.com/dncp-opendata/ocds_statusdetails_extension/-/merge_requests/2) with a more elaborate worked example.

**Comment by yolile** [comment]
@ColinMaudry could you create a new example instead of updating the existing one? As the existing one is the real example from Paraguay

**Comment by ColinMaudry** [comment]
@yolile Sorry about that. It's fixed: https://gitlab.com/dncp-opendata/ocds_statusdetails_extension/-/merge_requests/2/diffs?commit_id=60611322495e3241fed96eea1ff39f2e5f6cc4a4

**Comment by yolile** [comment]
@ColinMaudry thank you! merged!

**Comment by jpmckinney** [comment]
Re-opening the issue, as this would be resolved by merging the extension into OCDS.

**Comment by ColinMaudry** [comment]
OK, I'll work on a PR on dev-1.2.

**Comment by jpmckinney** [comment]
Closed by #1165

**Comment by duncandewhurst** [comment]
The topic of suspended contracts came up again in Nigeria, so it would be good to mention this somewhere in the 1.2 docs, now that the Status Details extension has been merged into the schema.

**Comment by jpmckinney** [comment]
@duncandewhurst Can you create a new, specific issue? This issue was about adding the fields, which is complete.

**Comment by jpmckinney** [comment]
Comments relevant to a worked example or other documentation:

https://github.com/open-contracting/standard/issues/430#issuecomment-660405607

All comments in https://github.com/open-contracting/standard/issues/758

**Comment by jpmckinney** [comment]
I've re-opened #758 instead.

**Comment by duncandewhurst** [comment]
Great, thanks!
