### ISSUE TITLE
Describe correspondence with e-Procurement Ontology (ePO)

### ISSUE THREAD

**Issue by akuckartz** [open-contracting/standard#765]
See https://eprocurementontology.github.io/

**Comment by jpmckinney** [comment]
The ePO is still under active development. That said, we will research the degree to which OCDS aligns with it, and identify opportunities for increased alignment.

**Comment by jpmckinney** [comment]
Noting that we authored a correspondence to eForms (to which ePO also has a correspondence) https://standard.open-contracting.org/profiles/eforms/latest/en/

We are working as part of the [Public Procurement Data Space](https://single-market-economy.ec.europa.eu/single-market/public-procurement/digital-procurement/public-procurement-data-space-ppds_en), which by my understanding will use the ePO. We will consider a correspondence as part of that.
