### ISSUE TITLE
Translation of the schema

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard#77]
We should allow that titles and description fields in the schema be expressed in multiple languages. 

In particular, translation into Spanish is likely to be very important for adoption. 

## Technical issues

At present, JSON Schema v4 does not support multilingual titles and descriptions, but [this is proposed for v5](https://github.com/json-schema/json-schema/wiki/multilingual-meta-data-%28v5-proposal%29) using a simple language map.

## Process issues

If we allow translation, we need a clear way to (a) keep language versions in sync; (b) warn users if they may not be.

This would involve a commitment to **always translate new releases of the standard** prior to release.

It would require explicit agreement on English as the authoritative version of the standard (or some other language version if appropriate...)

It would require any changes to the title or description of a field in the authoritative language to be be tracked, such that translations are flagged as requiring edits. 

## Short-term vs. Long-term

In the absence of JSON Schema v.5 available yet, we have a choice to make if we want to include translation in the release version. 

We could:

* Use the v.5 format for language maps internally, but process the schemas into v.4 style in different languages prior to publishing them. 
* Create a separate file of translated schema
* Simply translate a presentation version, without touching the schema (this is most risky in terms of schema moving ahead of e.g. Spanish language version, and leaving potential splits in the community of publishers)

@michaeloroberts might need to weigh in on this one in terms of the resources we have for translation and how in-depth we want to go on it.

**Comment by timgdavies** [comment]
There is now a translation framework in place for the documentation using Transifex: https://www.transifex.com/OpenDataServices/open-contracting-standard-1-0/

Spanish language is implemented at http://standard.open-contracting.org/latest/es/

Versioning issues have been addressed in the workflow. 

There is work-in-progress on the CoVE tool which should offer the ability to use translated column titles in CSV files, which would pick up on the CSV translation issue - but I think that is a separate issue, so closing this main translation issue for now.

**Comment by mireille-raad** [comment]
Can we add Romanian to the available translations on transifex? (for the Moldova project we are doing)

**Comment by ekoner** [comment]
@dc-coder that's done, I've emailed you.
