### ISSUE TITLE
tag should be omitWhenMerged

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#770]
The behavior of OCDS Merge is to set the tag to `compiled` for compiledRelease, and to move the tag onto the versioned object for versionedRelease. In other words, the original tag field is omitted.

Assigning to @kindly to confirm. The docs don't describe the first behavior, which we can fix as part of this issue.

**Comment by kindly** [comment]
@jpmckinney yes this is what I thought was expected behaviour.  Was not aware that was not in the docs.
We need to put something in `tag` at the `compiledRelease` level as it is a required field.

This relates to #330 (about making a `compiledRelease` schema) as we could validate this there.
