### ISSUE TITLE
Whether a contracting process originated from a procurement plan

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#774]
At the start of the year, the municipalities here in Kosovo make a procurement plan and they list all the projects that are planned to be implemented that year here (the example is for the contracts in 2018): 

[http://prishtinaonline.com/uploads/planifikimi_i_prokurimi_2018.pdf](http://prishtinaonline.com/uploads/planifikimi_i_prokurimi_2018.pdf)

If the contract is in this list we choose po (yes) from the codelist, if not we choose jo (no).

**Comment by jpmckinney** [comment]
Instead, this should be modelled as:

```json
  "planning": {
    "documents": [
      {
        "id": "set-an-identifier-here",
        "documentType": "procurementPlan",
        "title": "Planifikimi Përfundimtar i Prokurimit",
        "url": "http://prishtinaonline.com/uploads/planifikimi_i_prokurimi_2018.pdf",
        "datePublished": "2018-01-26T00:00:00Z",
        "format": "application/pdf",
        "language": "sq"
      }
    ]
  }
```

Or at minimum:

```json
  "planning": {
    "documents": [
      {
        "id": "set-an-identifier-here",
        "documentType": "procurementPlan"
      }
    ]
  }
```

The logic is that, if there is a document in the `planning` section with a `documentType` of 'procurementPlan', then this procurement is from the plan.
