### ISSUE TITLE
Whether a contracting process originates from an earlier unsuccessful process

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#776]
Here in Kosovo we use retender when a tender process ends without signing the contract.

For example nobody applies for the tender so a new procedure is opened with the term 'retender'.
If the retender is used we choose from the closed codelist yes(po), if not we choose no(jo).

**Comment by jpmckinney** [comment]
In OCDS, this is modeled as follows, on the new contracting process:

```json
  "relatedProcesses" [
    {
      "relationship": "unsuccessfulProcess"
    }
  ]
```

If possible, you should provide the values of additional fields to link to the earlier process. [See the documentation for Related Process.](http://standard.open-contracting.org/latest/en/schema/reference/#relatedprocess)

**Comment by jpmckinney** [comment]
Note: I made a correction to my earlier comment. I had incorrectly used the 'prior' code, when I meant to use the 'unsuccessfulProcess' code.
