### ISSUE TITLE
Procurement number

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#779]
The procurement number is unique for every contract. I'm currently using it to make the ocid, but I need it published separately from the ocid too.

The procurement number is made from:

- The identification of the contracting authority [3, 4 or 5 first numbers of the budget code]

- 2 last numbers of the year (18 of 2018)

- The serial number of the procuring activity (start with 1 every year)

- The code for the procurement type

- The code of the procurement procedure

- The code of the procurement value

**Comment by jpmckinney** [comment]
Use `tender.id` to publish it.
