### ISSUE TITLE
The expected number of transactions

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#781]
Other than the transactions itself we need to publish the total number of the transactions to be paid based on the contract.

**Comment by jpmckinney** [comment]
We don't have a field for the total number of transactions that are expected, at the time of a contract's signature, to be paid by the end of the contract. Is that a correct interpretation?

If so, we might consider an extension with a numeric `expectedNumberOfTransactions` field for `Contract`.

**Comment by leobaz** [comment]
Yes, that is the correct interpretation. Should we do a local extension for community extension?

**Comment by jpmckinney** [comment]
You can add this field to your data without describing it in an extension. However, we recommend creating an extension to document the additional field. We can then check whether others need this field, in which case it can be added to the extension registry as a community extension.

**Comment by jpmckinney** [comment]
Closing as no additional interest expressed in over a year. Can re-open if there is new interest.
