### ISSUE TITLE
Deduction from the contract

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#782]
Here in Kosovo, we have the amount of deduction from the contract due to the causes of the prohibitions.

**Comment by jpmckinney** [comment]
Can you give an example of the causes of the prohibitions?

We have a [contract completion](https://github.com/open-contracting-extensions/ocds_contract_completion_extension) extension, which can be used to provide the final value of the contract. A user could take the contract's initial value and subtract this final value to determine the difference. Would that be a way to calculate the deduction you mention? If not, can you give an example of a deduction?

**Comment by leobaz** [comment]
There are a lot of factors that cause the prohibitions. 

For example, if we are building a road from point A to point B and in the middle of that road, it's a building that prevents the road. Now in the contract, it is planned to destroy that building and if for any circumstance a new decision comes to not destroy the building but to go around it the amount from not destroying the building is the amount of deduction from the contract due to the causes of the prohibitions.

**Comment by jpmckinney** [comment]
I see, and in such cases, does the value of the contract always go down, or can it also go up?

Also, if there are multiple deductions, is each deduction disclosed separately, or is it only the total deduction that is disclosed?

**Comment by leobaz** [comment]
The value of the contract can go down and can go up based on the prohibition.

Only the total deduction is disclosed.

**Comment by jpmckinney** [comment]
Would the contract completion extension, as described above, suit your needs?

**Comment by leobaz** [comment]
I don't think this extension will suit my needs because it's for the final value and I need to publish the deduction amount, but I will use this extension for another field.

**Comment by jpmckinney** [comment]
As we don't intend to develop local extensions, I'll close, but we can re-open the issue if others express interest, as it might then be appropriate for a community extension.
