### ISSUE TITLE
The year of the contract

### ISSUE THREAD

**Issue by leobaz** [open-contracting/standard#786]
At [Open Contracts Prishtina](https://kontratatehapura.prishtinaonline.com/en) we take all the contracts from an importer and we convert them from csv to json. All contracts are grouped based on the year they were signed for example 2017.csv holds all the contracts signed in 2017. 
Sometimes some of the contracts don't have the signing date so we take the year based on the csv document they are.

We are proposing an extension for contract year (e.g. contract/year).

**Comment by jpmckinney** [comment]
Let's continue this discussion in #723, which proposes re-using `dateSigned`, but with more flexible validation.
