### ISSUE TITLE
Item country of origin

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#788]
Belarus draft data includes an additional `productCountry` field in `contract/items` for the country where goods were created. Helpdesk feedback suggested renaming to `countryOfOrigin`.

**Comment by yolile** [comment]
In Paraguay we also have the information about the country of origin for some items. This information is published using the [items attributes extension ](https://gitlab.com/dncp-opendata/ocds_item_attributes_extension)

**Comment by jpmckinney** [comment]
EU's eForms has BT-191 (Country Origin) "A country of origin of the product or the service." This applies to an entire bid, however. On current forms, this information is not intended for publication, so it doesn't appear in the OCDS for EU profile. The obligation to collection this information [seems to arise from the GPA](https://github.com/eForms/eForms/issues/35). The [GPA text](https://www.wto.org/english/docs_e/legal_e/rev-gpr-94_01_e.htm) doesn't specifically require such data collection, but presumably its collection supports the implementation of the GPA.

**Comment by jpmckinney** [comment]
This will be covered in our updates to the OCDS for EU profile for eForms, once the Publications Office publishes a mapping from TED to eForms. That work is tracked here: https://github.com/open-contracting-extensions/european-union/issues
