### ISSUE TITLE
Guidance: Preference for string over integer identifiers

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#789]
The schema allows both integers and strings for some `id` fields, and only strings for others. I believe this is because, during the supply-side research, it was found that some publishers used integers, and others used strings. However, this inconsistency can cause problems:

1. A publisher might have integers in their database, and therefore use integers for `id` fields, and then eventually encounter a structural error when they try to use an integer for an `id` field that only allows strings. This inconsistency could be surprising and frustrating.
1. A data user might look at data and see integers, and assume that all `id` values are integers. Their code or analysis then runs into trouble when it encounters string values. They then add extra code to either handle the inconsistency, or coerce all `id` values to strings.
1. A publisher might inconsistently use integers and strings for the same field. When making comparisons to check if two objects are the same, users will need to coerce both `id` values to string.

We can't remove integer as a possible value in 1.X, but we can strongly recommend the use of strings.

**Comment by ColinMaudry** [comment]
I suggest to add the following to the impacted fields' description:

Option 1:

> It is strongly encouraged to use a string instead of an integer.

Option 2:

> It is strongly encouraged to publish identifiers as strings and not as integers.

**Comment by jpmckinney** [comment]
We avoid words like "strongly". Otherwise, it's hard to disambiguate "strongly encouraged to" from "necessary to" or "strongly recommended to" from "required to".

In this case, we can use the normative word "recommended". So I suggest:

> Although an integer is allowed, it is recommended to use a string.

**Comment by ColinMaudry** [comment]
This is done right? @yolile

**Comment by yolile** [comment]
yes!
