### ISSUE TITLE
Release data sources

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#800]
## Problem

There are some publishers, as Honduras and Colombia, who have multiple databases/systems with differents type of process or different type of data in each one, generating a different release with different fields in each case. 
The differences in the data of each data base could be:

- Different covered times: in Colombia they have a new system called SECOP II that is alive from 2015 and the processes before 2015 are registered in other system called SECOP I

- Different type of processes (which involves different types of published fields): in Honduras they have a system for the framework agreements and ahother one for the traditional processes

- Different quality of data: in Honduras they have a system for the traditional processes, called Hondu Compras and another one that has the contracts without information about the tender stage, due a problem in their system itself, generating data loss or quality problems in the data. 

All these considerations maybe can be addressed by a notice in the publication policy in each case, but for the user point of view it could be much easier if the release itself has the information about where it comes from.

## Proposal

So the proposal is to add a field named "originSystems" that will be array of free text at release level in which the publisher can publish from which system(s) the data in the release come from

```json
{

...

"releases": [

   {

     "originSystems": ["HonduCompras"],
    "ocid": "ocds-213czf-000-00001",
    "id": "ocds-213czf-000-00001-05-contract",
    "date": "2010-05-10T10:30:00Z",
    "language": "es"
     ....
   }

]

...

}
```

The immediate user for this extension at least as local extension, will be Honduras.

REFS: Colombia Systems: https://www.colombiacompra.gov.co/compradores/secop-i
Honduras Systems: http://www.honducompras.gob.hn/

**Comment by jpmckinney** [comment]
Is it not possible to determine the source system based on the package's `publisher`?

If there's a challenge with using package metadata, could we instead put the `publisher` inside the release, instead of creating this `originSystems` field?

**Comment by yolile** [comment]
I don't think so, because in both cases the publisher is the same: Colombia Compra Eficiente for Colombia and ONCAE for Honduras. But in both cases each one manage multiples systems, like the ones that are listed in the "systems" sheet in the mapping template

**Comment by jpmckinney** [comment]
Ok, so we'll need a new field. What's the use case for having a list of strings instead of one string? Do we have a real example where one release is published by multiple systems?

**Comment by yolile** [comment]
Yes, we have it. In Honduras (ONCAE) there are some cases when they can link the data in the contracts database with the tenders and traditional processes database. In those cases they will have one release with information about the tender stage that comes from the traditional system and the contracts information that comes from the contracts system. Of course they can have two releases, one for each case, but anyway in the compile release they must put both

**Comment by duncandewhurst** [comment]
Belarus proposed adding an additional `source` field at `release` level with the following description:

> Procedures may take place of different electronic platforms. Field is used to have a possibility to download only releases from one electronic platform

Helpdesk feedback was to publish this in `tender/submissionMethodDetails` (which isn't otherwise mapped to) to make the information available to tools/methodologies which are only aware of core OCDS fields, however if multiple publishers have this need then a common approach which doesn't rely on the availability of `tender/submissionMethodDetails` may be better.

**Comment by jpmckinney** [comment]
I think a field like this makes sense, though we still need to agree on the best term. So far, the proposals are `originSystems` and `source`. Dublin Core also has `source`, which it defines as "A related resource from which the described resource is derived", with the comment "The described resource may be derived from the related resource in whole or in part. Recommended best practice is to identify the related resource by means of a string conforming to a formal identification system." I don't know if the semantics are the same (in Dublin Core, the source is more or less static, from which quotes or samples can be taken), but they're close.

We also need to agree on how to identify the source. @duncandewhurst What do the values look like for Belarus' data? I don't think strings like `"HonduCompras"` are ideal. On the other hand, I don't think we can use URLs to the systems, as this assumes the systems have a public-facing website and that their public URLs never change. We can perhaps explore a prefixed identifier. I think a reasonable prefix is the OCID prefix.

**Comment by jpmckinney** [comment]
Regarding compiled releases, the rule for merging lists of strings is to merge the list as a whole, so the value for `source` would be whatever was in the last release. In order to keep the full list of sources, we'd need an arrays of objects with `id` fields (or we'd need to invent a new rule, but that will be a greater burden on publishers when upgrading OCDS). That seems fine, as it allows to add a bit more metadata about the source systems, for which we might find use cases. So, something like:

```json
{
  "sources": [
    {
      "id": "ocds-213czf-sample-source",
      "name": "Sample Source",
      "url": "http://example.com"
    }
  ]
}
```

**Comment by duncandewhurst** [comment]
@jpmckinney great point on compilation which neatly addresses the issue with urls.

In Belarus, the values are the url of the electronic platform, e.g.

source
--
http://www.icetrade.by
www.zakupki.butb.by
http://www.goszakupki.by/

**Comment by yolile** [comment]
Honduras is about to publish their data should they create this extension already?

**Comment by jpmckinney** [comment]
That's fine – it'd be ideal to have wider discussion on the proposal, but if they need this urgently, then I think my proposal would be fairly close to the consensus.

**Comment by jpmckinney** [comment]
Honduras has drafted an extension: https://bitbucket.org/izelayas/ocds_releasesource_extension/src/master/

**Comment by jpmckinney** [comment]
On second thought, we don't recommend using OCID prefixes on any local identifiers to make them globally unique (except for the ocid itself), so I'll suggest changes to the extension's documentation.

**Comment by jpmckinney** [comment]
I made a pull request: https://bitbucket.org/izelayas/ocds_releasesource_extension/pull-requests/2 Once merged and added to the registry, we can close this issue.

**Comment by jpmckinney** [comment]
Done!
