### ISSUE TITLE
Public procurement regime

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#804]
## Problem

In Colombia, Paraguay and I guess that in each country, they have a law, norm or rule that indicate the procedures and norms that indicates how the public procurements process have to be managed. This norms and laws can vary between year and year, and can change the rules of the procurement process it self.

## Proposal

Add a field in tender to indicate the law, regime or norm from which the process is been development

## Example

```
{
   "tender": {
       "regime": {
             "id": "3",
             "name": "Estatuto General de Contratación"
        }
    }
}
```

Example from Colombia: https://www.datos.gov.co/Gastos-Gubernamentales/SECOP-I/nuxh-53y2

**Comment by duncandewhurst** [comment]
The [coveredBy extension](https://github.com/open-contracting-extensions/ocds_coveredBy_extension) was created for this purpose
