### ISSUE TITLE
Extension: Organization ownership details

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#805]
Draft data from Belarus proposes an additional field: `parties/details/organisationType`

This field is used to provide a free text description of the ownership of the organization, for example:

> Economic company with a share of the state in the authorized capital of the organization

Since this field is free text it can't be modelled as a classification using either `parties/details` or `parties/classifications`.

Helpdesk feedback was to add a field to the `organization` object as a local extension: `organization/ownershipDetails`.

This naming prefers 'ownership' since the 'type' of an organization could mean many things and uses the `Details` suffix to prevent clash with any future use of `organization/ownership` for structured data, or links to data, on ownership.

**Comment by jpmckinney** [comment]
Agreed, `organizationType` should be reserved for things like SA, PLC, LLC, etc. as in W3C [Registered Organization Vocabulary](https://www.w3.org/TR/vocab-regorg/#ref_rov_orgType).

**Comment by jpmckinney** [comment]
As we don't intend to develop local extensions, I'll close, but good to log here in case future interest is expressed by others.
