### ISSUE TITLE
Possible to navigate to PPP documentation from main documentation?

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#807]
I find it hard to find the PPP profile from the main docs.

I also tried googling and the old readthedocs came up.

So, the ppp profile is probably very hard for people to know about/stumble upon

**Comment by jpmckinney** [comment]
Duplicate #459 to be fixed in 1.1.4

**Comment by jpmckinney** [comment]
What Google terms did you use that brought up the readthedocs? (which just redirects to the correct docs)

**Comment by LindseyAM** [comment]
I googled public-private partnerships ocds  (and the readthedocs didnt
redirect)

**Comment by jpmckinney** [comment]
Hmm, https://ocds-for-ppps.readthedocs.io/ (and others) redirect, but not https://ocds-for-ppps.readthedocs.io/en/stable/extensions/ppp/

I'll just stop it from being indexed by search engines.

**Comment by jpmckinney** [comment]
Opened issue to do that: https://github.com/open-contracting-extensions/public-private-partnerships/issues/196
