### ISSUE TITLE
Add Tender.identifier(s) and Contract.identifier(s) fields

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#815]
https://github.com/gitMHOCDS/dncp-contract-code adds contracts.dncpContractCode (string)

> For each contract, the DNCP generates a contract code that differs from the id of the contractId it self, and this information is relevant because it helps users to link a contract in Hacienda with a contract in DNCP. Users are very used to working with this information in Paraguay, and as such it is needed for the Paraguayan users of the data.

https://github.com/openprocurement/ocds_contractNumber_extension adds contracts.contractNumber (string)

> This extension introduces one field that can be used to provide editable number of the contract.

The earlier discussion in #289 provides additional examples.

Rather than the approach in #289 – which is for each publisher to create their own very similar but different extension – the proposal here is to add to `Contract` either a `identifier` field for a single `Identifier`, or an `identifiers` field for an array of `Identifier`.

The two local extensions suggest only `identifier` is needed.

cc @yolile @duncandewhurst @myroslav

**Comment by jpmckinney** [comment]
cc @yanakapatsila

**Comment by jpmckinney** [comment]
OC4IDS has an `externalReference` field (for the contracting process), whose name we can also consider re-using.

**Comment by duncandewhurst** [comment]
The [Himachal Pradesh Govt Tenders Information System](https://hptenders.gov.in/nicgep/app) includes two identifiers for each tender: a tender id and a tender reference.

So we should look at adding a similar field to `tender`.

**Comment by odscrachel** [comment]
The Kyrgyz Republic currently have an additional field within contracts titled `contractNumber` which looks like they may be using it to capture an internal reference number. They also have `tenderNumber` with the tender section.

**Comment by duncandewhurst** [comment]
> The two local extensions suggest only `identifier` is needed.

It seems possible to me that, particularly in the case of contracts, different systems might assign different identifiers. For example, a contract might appear in a procurement system, a financial system, a contract management system etc. Ideally, those systems would share a common identifier, but in practice they might not.

Do we need to solicit more input on this issue before preparing a PR?

**Comment by jpmckinney** [comment]
These objects already have `id`, which should be enough for the primary identifier. As such, and unlike organizations (which have `id`, `identifier` and `additionalIdentifiers`, because `id` might just be for internal references, and `identifier` might not be globally unique), it's enough to have `id` and `identifiers` for tender and contracts.

Now, the `Identifier` definition is currently specific to organizations and contains a field that makes no sense in other contexts (`legalName`). As such, I think we should have a new definition that is almost identical to SimpleUnit (i.e. just an `id` and a `scheme`). The new definition can be `SimpleIdentifier` perhaps.

Once the new definition is agreed, there can be a PR.

**Comment by duncandewhurst** [comment]
Your proposal sounds good to me.

**Comment by odscjen** [comment]
Suggesting this as a definition of `SimpleIdentifier`

```json
"SimpleIdentifier": {
   "title": "Simple Identifier",
   "description": "A simple identifier consists of: a scheme, representing the list from which the identifier is taken, and the   identifier itself.”,
   "type": "object",
   "properties": {
      "scheme": {
        "title": "Scheme",
        "description": "The list from which identifiers are taken.",
        "type": [
          "string",
          "null"
        ]
      },
      "id": {
        "title": "ID",
        "description": "The identifier code taken from the scheme.",
        "type": [
          "string",
          "null"
        ],
        "versionId": true
      }
    },
  },
```

**Comment by jpmckinney** [comment]
I suggest:

> Simple identifier

Capitalization change. We aren't consistent, but in general we prefer sentence case.

> An unambiguous reference to a resource within a given context.

This is taken from Dublin Core: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/terms/identifier/

Otherwise, we're describing each field within the definition's description.

> The list, register or system from which the identifier is taken.

There may not be a true "list" for some identifier schemes.

> The identifier taken from the scheme.

"code" is not needed and could be confusing here.

**Comment by odscjen** [comment]
great, that all makes sense. Incorporating your comments:

"SimpleIdentifier": {
 "title": "Simple identifier",
 "description": "An unambiguous reference to a resource within a given context. A simple identifier consists of: a scheme from which the identifier is taken, and the identifier itself.”,
 "type": "object",
 "properties": {
   "scheme": {
     "title": "Scheme",
     "description": "The list, register or scheme from which identifiers are taken.",
     "type": [
       "string",
       "null"
     ]
   },
   "id": {
     "title": "ID",
     "description": "The identifier taken from the scheme.",
     "type": [
       "string",
       "null"
     ],
     "versionId": true
   }
 },
},

**Comment by jpmckinney** [comment]
Great! We can delete "A simple identifier consists of: a scheme from which the identifier is taken, and the identifier itself." since we should avoid describing the fields in the definition's description. (I know it's done in a few cases; they should be corrected separately.)

**Comment by odscjen** [comment]
Grand, that makes sense, so it'll be:
```json
"SimpleIdentifier": {
  "title": "Simple identifier",
    "description": "An unambiguous reference to a resource within a given context.”,
    "type": "object",
    "properties": {
      "scheme": {
        "title": "Scheme",
        "description": "The list, register or system from which identifiers are taken.",
        "type": [
          "string",
          "null"
        ]
      },
    "id": {
    "title": "ID",
    "description": "The identifier taken from the scheme.",
    "type": [
      "string",
      "null"
    ],
    "versionId": true
    }
  },
}
```

If everyone's happy with this I can create the PR?

**Comment by jpmckinney** [comment]
Looks good to me, just noticed a typo:

> The list, register or scheme

should be:

> The list, register or system

**Comment by yolile** [comment]
For the scheme name, should we suggest following a pattern such as {2-digits ISO country code}-{jurisdiction}-{system/register} name? Similar to the guidance for the [legalBasis extension](https://extensions.open-contracting.org/en/extensions/legalBasis/1.1/)

**Comment by jpmckinney** [comment]
Sure, let's create a new issue though. I'd probably just go {ISO 3166-1 alpha-2}-{system} or {ISO 3166-2}-system.

**Comment by duncandewhurst** [comment]
Looks like we missed adding `SimpleIdentifier` to the schema reference documentation.

**Comment by duncandewhurst** [comment]
> Sure, let's create a new issue though. I'd probably just go {ISO 3166-1 alpha-2}-{system} or {ISO 3166-2}-system.

In the eForms mapping, I authored the following guidance for BT-150-Contract:

> If the scope of the list, register or scheme from which the contract identifier is drawn is subnational, set the simple identifier's `.scheme` to `{ISO 3166-1 alpha-2}-{system}`. Otherwise, set it to `{ISO 3166-2}-{system}`.

**Comment by jpmckinney** [comment]
> Looks like we missed adding SimpleIdentifier to the schema reference documentation.

Ah, indeed. The links to SimpleIdentifier are constructed in the schema tables but lead nowhere.

**Comment by jpmckinney** [comment]
@duncandewhurst I think the guidance should be:

> If the scope of the list, register or **system**~~scheme~~ from which the contract identifier is drawn is subnational, set the simple identifier's .scheme to {ISO 3166-**2**~~1 alpha-2~~}-{system}. Otherwise, set it to {ISO 3166-**1 alpha-2**~~2~~}-{system}.

**Comment by duncandewhurst** [comment]
Ah, good spot. Not sure how they came to be reversed. I've updated the guidance.
