### ISSUE TITLE
Add Document.relatedItem field

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#816]
How frequently are documents related to a specific item?

https://github.com/openprocurement/ocds_linkedDocument_extension adds Document.relatedItem (string) and Document.documentScope (string). I am curious if other publishers need this, too.

Enquiry and Criterion from the enquiries and requirements extensions, respectively, already have a `relatedItem` field.

cc @yanakapatsila

**Comment by PaulBoroday** [comment]
1. Often document can be related not only on *item* or *tender* but also on *lot*.  
2. Maybe its better to use here same to as it is already in mentioned *requirements*? 
>relatesTo:
>relatedItem:
3. For mentioned *enquiry* I would suggest reconsidering an approach as well: *relatedItem* means the same there, but *relatedLot* is not consistent and no way to relate particular *enquiry* to all *tender*

**Comment by jpmckinney** [comment]
1. The lots extension already adds a [`relatedLots`](https://extensions.open-contracting.org/en/extensions/lots/master/schema/#document) field to Document.
2. `relatesTo` is needed because it's possible for a selection criterion to relate to the tenderer. However, in that case, the tenderer is anonymous, as this information is published before any bids are submitted, and there is no object to refer to.
3. I think the intention is that if `relatedLot` and `relatedItem` are omitted, then either it is an enquiry about the whole procurement, or it is unknown what the enquiry is about.

**Comment by duncandewhurst** [comment]
Can a document be related to more than one item, but less than a whole lot or tender?

If so, the field would need to be an array, e.g. `Document.relatedItems`.

**Comment by jpmckinney** [comment]
Since relatedLots is plural, I think it's reasonable for relatedItems to be plural.
