### ISSUE TITLE
documentType codelist: Update the description of the environmentalImpact code

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#818]
OC4IDS introduces an improved definition for this code:

> Documentation of assessments of the environmental impacts (e.g. impacts on flora, fauna & woodlands, areas of natural beauty, carbon emissions etc.) and mitigation measures (e.g. pollution control, low carbon solutions, sustainable timber etc.) for this contracting process or project.

**Comment by jpmckinney** [comment]
@duncandewhurst I assume we omit "or project" in OCDS, right?

**Comment by duncandewhurst** [comment]
Yes, that makes sense.
