### ISSUE TITLE
GPA alignment of closed codelist descriptions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#828]
Follow-up to #687 due to versioning policy, to align the `method.csv` and `procurementCategory.csv` code descriptions with GPA text, compared in [this spreadsheet](https://docs.google.com/spreadsheets/d/1X4nULP8nhYR_iXra0HjTy5n2v5z2kyzFFT7KTv2GZo0/edit?pli=1#gid=0).

Should also compare to [OCDS](https://docs.google.com/spreadsheets/d/1WGH9_mHYuF4JbK2tdyeckqsmj8v4HrRqDOEbKQ7CI4A/edit#gid=0) or [EU e-Procurement Ontology](https://docs.google.com/spreadsheets/d/1zw9aR8GDIDUiTDtSznMxDlZQEAGb8uNzib9KBZLf5yE/edit#gid=0) glossaries, to satisfy part of #827.

**Comment by ColinMaudry** [comment]
My attempt to improve the OCDS definitions using the GPA definitions.

### Electronic auction

GPA:

> an iterative process that involves the use of electronic means for the presentation by suppliers of either new prices, or new values for quantifiable non-price elements of the tender related to the evaluation criteria, or both, resulting in a ranking or re‑ranking of tenders

OCDS (`submissionMethod.electronicAuction`)

> Bids will be received through an electronic auction platform.

Proposal:

> Bids will be received through an electronic auction platform. Tenderers present new prices, or new values for non-price elements, resulting in successive rankings of the bids.

### Qualified supplier

GPA:

> a supplier that a procuring entity recognizes as having satisfied the conditions for participation

OCDS [Qualification extension](https://extensions.open-contracting.org/en/extensions/qualification/master/codelists/#+partyRole.csv) (`partyRole.qualifiedBidder`):

> Those parties invited to submit a proposal in response to a Request for Proposal (RFP) for a project in which the government only allows a limited number of pre-qualified bidders to proceed to the RFP phase.

FYI the definition of `qualifiedBidders` from the bidStatistics codelist:

> The total number of unique organizations or consortia passing the qualification stage of the evaluation process.

Proposal (not really relevant if `partyRole.qualifiedBidder` is deprecated):

> Parties having satisfied the conditions for participation, including, if applicable, the selection criteria.

cc @jachymhercher

**Comment by ColinMaudry** [comment]
@jpmckinney The `qualifiedBidder` party role doesn't seem to exist anymore. Do you know why?

The difficulty to make a good definition for `qualifiedBidder` comes from the lack of internal references we can make in OCDS to the qualification stage and evaluation process. The standard doesn't really cover these concepts.

**Comment by jpmckinney** [comment]
Can you update your comment to specify the precise OCDS fields/codes whose descriptions are being modified? Otherwise, I can't follow.

`qualifiedBidder` only exists on the Qualification extension, which is not recommended for use and will be removed: https://extensions.open-contracting.org/en/extensions/qualification/master/codelists/#+partyRole.csv

FYI, I created this tool for schema editors to easily look up fields/codes in registered extensions: https://open-contracting.github.io/editor-tools/

**Comment by ColinMaudry** [comment]
I've updated my comment.

Thanks, great tool, that will definitely help!

**Comment by jpmckinney** [comment]
`submissionMethod.electronicAuction` is also going away https://github.com/open-contracting/standard/issues/322#issuecomment-475380695

**Comment by ColinMaudry** [comment]
My bad, I first thought I had to study the terms that had an "Open" status.
* procurementCategory 'goods' and 'services':
  * The GPA combines goods and services in the same term.
  * It refers to things that are typically only sold or purchased "by non‑governmental buyers for non-governmental purposes". I find it surprising in a text that intends to rule **public** procurement.
  * In the OCDS definition of 'goods', that might be because English is not my native language, but the word 'electronic' could refer to electronic material (physical goods) if was not opposed to 'physical'
  * **Proposal:** There is nothing in the GPA text that may significantly improve the current OCDS definitions. We might replace 'electronic' with 'digital' to clarify the scope of 'goods' (software, data, sound, video, pictures, etc.).

**Comment by ColinMaudry** [comment]
@jpmckinney What's your view on this?

> Proposal: There is nothing in the GPA text that may significantly improve the current OCDS definitions. We might replace 'electronic' with 'digital' to clarify the scope of 'goods' (software, data, sound, video, pictures, etc.).

**Comment by jpmckinney** [comment]
I reviewed my old spreadsheet from the issue description: https://docs.google.com/spreadsheets/d/1X4nULP8nhYR_iXra0HjTy5n2v5z2kyzFFT7KTv2GZo0/edit?pli=1#gid=0

I think we might consider (the first two are in open codelists, so might be covered by #827):

GPA term | GPA ref | OCDS ref | OCDS text | GPA text
-- | -- | -- | -- | --
technical specification | Article I:u | documentType: technicalSpecifications | Detailed technical information about goods or services to be provided. | a tendering requirement that: i. lays down the characteristics of goods or services to be procured, including quality, performance, safety and dimensions, or the processes and methods for their production or provision; or ii. addresses terminology, symbols, packaging, marking or labelling requirements, as they apply to a good or service
notice of intended procurement | Article I:k | documentType: tenderNotice | The formal notice that gives details of a tender. This may be a link to a downloadable document, to a web page, or to an official gazette in which the notice is contained. | a notice published by a procuring entity inviting interested suppliers to submit a request for participation, a tender, or both
commercial goods or services | Article I:a | procurementCategory: goods <br/><br/>procurementCategory: services | The primary object of this contracting process involves physical or electronic goods or supplies.<br/><br/>The primary object of this contracting process involves professional services of some form, generally contracted for on the basis of measurable outputs or deliverables. | goods or services of a type generally sold or offered for sale in the commercial marketplace to, and customarily purchased by, non‑governmental buyers for non-governmental purposes

**Comment by ColinMaudry** [comment]
My understanding of the need is that OCDS definitions work as-is but you want them to be more anchored in a reference terminology. GPA has a worldwide scope and good definitions.

Let's give a "GPA touch" to the OCDS definitions:

- documentType: technicalSpecifications:

OCDS 1.1:

> Detailed technical information about goods or services to be provided.

GPA:

> a tendering requirement that: i. lays down the characteristics of goods or services to be procured, including quality, performance, safety and dimensions, or the processes and methods for their production or provision; or ii. addresses terminology, symbols, packaging, marking or labelling requirements, as they apply to a good or service

OCDS 1.2:

> *Long version* Detailed technical documentation that lays down the characteristics of goods or services to be procured, including quality, performance, safety and dimensions, or the processes and methods for their production or provision. They may also address terminology, symbols, packaging, marking or labelling requirements.

> *Short version* Detailed technical documentation that lays down the characteristics of goods or services to be procured. They may also address terminology, symbols, packaging, marking or labelling requirements.

**James' update:** To make it easier to compare versions without copying content, I'll add my suggestion here. I consider the "lays down" metaphor from GPA to be unnecessarily indirect. "Detailed" and "technical" from OCDS 1.1 is clear from the rest of the definition (and the code title). "Tendering requirement" from GPA just raises more questions (what is a "tendering requirement"?). "Documentation" from OCDS suggests the document is more descriptive than prescriptive. I suggest:

> A document that describes the characteristics of goods or services to be procured, including quality, performance, safety and dimensions, or the processes and methods for their production or provision; or that addresses terminology, symbols, packaging, marking or labelling requirements, as they apply to a good or service.

**Colin's update**

I find the "; or" not fluid:

> A document that describes the characteristics of goods or services to be procured, including quality, performance, safety and dimensions, or the processes and methods for their production or provision. The document can also address terminology, symbols, packaging, marking or labelling requirements, as they apply to a good or service.

**Comment by ColinMaudry** [comment]
- documentType: tenderNotice

OCDS 1.1:

> The formal notice that gives details of a tender. This may be a link to a downloadable document, to a web page, or to an official gazette in which the notice is contained.

GPA:

> a notice published by a procuring entity inviting interested suppliers to submit a request for participation, a tender, or both

Proposal:

> The formal notice that gives details of a tender, inviting interested suppliers to submit a bid, a request for participation, or both.

**James' update:** Sorry, the text above was from OCDS 1.1.4. OCDS 1.1.5 (#714, PR #725) already changed this to:

> The notice published by the procuring entity inviting interested suppliers to submit a request for participation, a bid, or both. This may be a link to a downloadable document, to a web page, or to an official gazette in which the notice is contained.

I don't know if #571 means that we should change this to "the buyer or the procuring entity". I'm also okay with removing the second sentence, since this can be said for almost any document

**Colin's update** new proposal:

>  The notice published by the buyer inviting interested suppliers to submit a request for participation, a bid, or both.

I have removed the second sentence, and replaced "procuring entity" with "buyer".

Can we use "supplier" for potential tenderers who haven't even submitted a bid (cf #1149)? We could replace it with "potential tenderers".

**Comment by ColinMaudry** [comment]
- procurementCategory: goods

OCDS 1.1:

> goods: The primary object of this contracting process involves physical or electronic goods or supplies.

> services: The primary object of this contracting process involves professional services of some form, generally contracted for on the basis of measurable outputs or deliverables.

GPA (commercial goods or services):

> goods or services of a type generally sold or offered for sale in the commercial marketplace to, and customarily purchased by, non‑governmental buyers for non-governmental purposes

OCDS 1.2:

> The primary object of this contracting process involves physical or digital goods generally sold or offered for sale in the commercial marketplace.

I don't really understand this part (bold) of the GPA definition:

> goods or services of a type generally sold or offered for sale in the commercial marketplace to, **and customarily purchased by, non‑governmental buyers for non-governmental purposes**.

I don't see how the GPA text could improve the definition of 'procurementCategory: services'.

**Comment by jpmckinney** [comment]
I guess GPA distinguishes "commercial" goods or services by adding that extra clause ("generally sold or ...") - which I agree is not relevant to our definition. As such, the entire definition is not helpful to us.

I think the only change is to switch "electronic" (which tends to be understood as laptops, etc. which are already "physical") to "digital". We should keep "or supplies" since that is an important synonym for "goods".

For your other two comments, I added content to your comment, so that all definitions can be read on the same screen for easier comparison.

**Comment by ColinMaudry** [comment]
That means we agreed on the following definition for procurementCategory:goods:

> The primary object of this contracting process involves physical or digital goods or supplies.

**Comment by jpmckinney** [comment]
>> I find the "; or" not fluid:
>
> A document that describes the characteristics of goods or services to be procured, including quality, performance, safety and dimensions, or the processes and methods for their production or provision. The document can also address terminology, symbols, packaging, marking or labelling requirements, as they apply to a good or service.

To preserve the same meaning as before, change "The document can also address" to "Or, a document that addresses"

>> The notice published by the buyer inviting interested suppliers to submit a request for participation, a bid, or both.
>
> I have removed the second sentence, and replaced "procuring entity" with "buyer".
> 
> Can we use "supplier" for potential tenderers who haven't even submitted a bid (cf #1149)? We could replace it with "potential tenderers".

I think it is clear in context. However, it'd be good to have a consistent style guide, e.g.:

- prefer "buyer" to "procuring entity" unless the issue is specifically about the procuring entity
- when to use suppliers, tenderers, interested suppliers, invited suppliers, participants, etc.

This might be for a new issue, in which case we might edit the wording again as part of that issue.

**Comment by ColinMaudry** [comment]
I saw guidelines on how field descriptions should be written. Where was it?

**Comment by ColinMaudry** [comment]
Found them: https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/style_guide.html

**Comment by jpmckinney** [comment]
@ColinMaudry Is this issue closed by #1280?

**Comment by ColinMaudry** [comment]
Closed by #1280 and #1209
