### ISSUE TITLE
Consider replacing language of "core" extensions universally

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#833]
"Core extensions" are somewhat an oxymoron. The Extension Explorer uses "recommended extensions" instead, following this discussion: https://github.com/open-contracting/extension-explorer/issues/19

The Extension Explorer's purpose is to help people to discover, use and create extensions; its use of "recommended" helps direct people to what we consider to be the most important extensions to use. Presently, these are the same as the core extensions.

As described in the mentioned issue, "core extensions" serves to distinguish extensions that follow the governance process from those that don't. It's not necessarily the case that all recommended extensions in the Extension Explorer will always be core extensions.

So, this issue is to determine how to name and distinguish extensions that follow the governance process.

**Comment by mrshll1001** [comment]
Agreed, core extensions as a term doesn't make sense.

"Key" extensions might be suitable. Semantically the term implies important and unlocking features. Alternatively "Primary" might be ok but carries implications of community and local extensions being Secondary and Tertiary (which may be true, but Community and Local are more descriptive).

**Comment by yolile** [comment]
I agree, too. And besides, I think that the "core" word is even more confusing translated into Spanish, and usually, we explain them as recommended extensions instead.

**Comment by mrshll1001** [comment]
I think "Recommended extensions" is definitely the way to go here for now, although we may generate confusion later. The reason for this is that we have existing materials which claim that recommended extensions are supported / versioned by our team along with the standard. If a third party creates an extension that turns out to be "recommended" by us; we need to then be able to distinguish between extensions that we recommend and extensions that we support directly and thus extensions that publishers/users may raise issues with us on.

**Comment by jpmckinney** [comment]
@mrshll1001 Indeed – we haven't found a word that everyone agrees communicates the idea clearly, but "recommended" seems least bad. We can maybe use the language of "promote" when we're recommending extensions in a social way via Helpdesk work.

**Comment by mrshll1001** [comment]
@jpmckinney Agree with "promote" throughout social interactions via helpdesk. I'd also be keen to avoid use of the term "supported" as it may be easy for someone to conflate this with it being technically compatible ie "Google Meet supports Firefox, Chrome, etc". As long as an extension is developed correctly OCDS data would "support" it.

An alternative that I've admittedly not thought through is just to admit that a single word might not capture what we want, and apply something like "OC Maintained" to the semantics that currently sit behind "Recommended". My understanding is that we're trying to convey the fact that *we're* the ones maintaining and developing these extensions, so we should just say that.

**Comment by jpmckinney** [comment]
@mrshll1001 Yes, I'm happy with that approach, too.

**Comment by mrshll1001** [comment]
@jpmckinney great! Broadening this slightly to clarify what the world looks like afterwards; would this change mean the presence of multiple "tags" on the Extensions Explorer? For example an extension that is currently "core" would then become "Recommended" and "OC Maintained" (or whatever we decide). That allows us the flexibility to apply "Recommended" to other, third party, extensions that are useful in the future.

**Comment by mrshll1001** [comment]
Potential terms for replacing "core":

* Maintained by Open Contracting or OC Maintained
* Maintained by the OCDS Team
* Developed by Open Contracting

Any other suggestions? I'm leaning towards supporting "Maintained by Open Contracting" which I feel is pretty clear-cut.

**Comment by yolile** [comment]
> Maintained by Open Contracting

Maintained by Open Contracting Partnership?

**Comment by jpmckinney** [comment]
OCP maintains about 60 extensions, but only 7 are "core" i.e. follow the governance process.

The Extension Explorer already has a "maintained by" statement.

We basically need a short form of "follow the governance process".

**Comment by mrshll1001** [comment]
> We basically need a short form of "follow the governance process".

I don't think that needs too much changing? Maybe "Follows OCDS Governance Process" or "Subject to OCDS Governance Process"

**Comment by ColinMaudry** [comment]
> We basically need a short form of "follow the governance process".

I thought "core" expressed it well, especially if that is not supposed to mean "Maintained by OCP". 

I wonder: what are the situations when people need to filter the extensions that follow the same release cycle and governance process than the core schema? Isn't it enough to have it indicated *in extenso* in the README of these extensions?

**Comment by ColinMaudry** [comment]
"Core extension" is an oxymoron, but having extensions that are tied to the core is unusual, even counter-intuitive. Using an oxymoron reflects well the situation.

We could also not call them "extension" but "optional module" or something else that shows they are special. But again, I wonder if that facet needs to be shown in the extension browser.

**Comment by jpmckinney** [comment]
I like that solution: abandon any distinction in the main documentation about "core", and each extension can describe its governance process.

Originally, I think the distinction between core vs community was desirable to indicate some quality threshold. But since then we've implemented a review process for any extension in the registry, so every "registered" extension is good quality.

**Comment by mrshll1001** [comment]
> I like that solution: abandon any distinction in the main documentation about "core", and each extension can describe its governance process.

I like this a lot too. It deals with the crux of the issue really. If we've got the review process to ensure quality I don't see the need to keep the distinction at all.

I'm unsure of the language around "module"; I think perhaps it just sits a little too close to 'building block' which is used in other OCDS documentation to describe the re-usable objects in the schema. And while extensions *may* add new objects, that's not all they do.

**Comment by jpmckinney** [comment]
@mrshll1001 Sounds good. Is there anything else you need before preparing the pull request?

**Comment by mrshll1001** [comment]
@jpmckinney  Don't think so, I'll comment if I need anything further!
