### ISSUE TITLE
`awardCriteria`: Codelist terms need descriptions/definitions

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/standard#84]
`Best Proposal` is likely to be the catch-all. 

From @jpmckinney #54

**Comment by timgdavies** [comment]
We have `awardCriteriaDetails` to allow more detailed local specifications of `awardCriteria`. However, our codelist currently lacks definitions for each term, giving only titles:
- lowestCost - Lowest Cost  
- bestProposal - Best Proposal  
- bestValueToGovernment - Best Value to Government  
- singleBidOnly- Single Bid Only

@LindseyAM Can you point us to a source for definitions against this code list, or propose initial definitions we should work with if there are no formally agreed definitions these map to.

**Comment by ekoner** [comment]
Tracking suggestions here: https://docs.google.com/spreadsheets/d/1lHAcfSBGZJevOjH33KOv-B13Z6AG8HfSdaU9sFc7uxU/edit?usp=sharing

**Comment by timgdavies** [comment]
This is now addressed in #385
