### ISSUE TITLE
Unclear rules on uniqueness of record

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#847]
At many locations, it's recommended that there be only one record per process. However:

* The records reference page at the same time says that publishers can consider publishing versioned and non-versioned copies of the record.
* If a record is updated each time a release is published, it's likely that old versions exist in e.g. ZIP files prepared on a daily, weekly or monthly basis.
* If a record is updated each time a release is published, it's likely that users, aggregators, etc. will have old copies of the record.

As such, it's clear that there isn't only one record per process.

What we really want is for it to be clear which record is the most up-to-date and complete. We should update the documentation to be clearer about this.

Need to update `releases_and_records.md` and `records_reference.md` among others.

**Comment by duncandewhurst** [comment]
Related to https://github.com/open-contracting/standard/issues/1264

**Comment by jpmckinney** [comment]
Merging #1264 into this issue:

The implications of this statement are unclear. For example, cases that are allowed:

* If a publisher creates a bulk download of all data on some schedule, and names the file according to the creation date, it is allowed for a contracting process to have a record in each bulk download.
* If a publisher has API endpoints for OCDS 1.0 and 1.1, it is allowed for a contracting process to have a record in each endpoint. (See #849 for similar discussion about release IDs.)
* If a publisher added an API method to view a record "as of" a user-defined date, this should be allowed.
* If an API endpoint allows the user to define which fields to return (like in GraphQL), this should be allowed.

Cases that we want to disallow:

* An API endpoint contains multiple records with the same OCID. (A given record, however, is allowed to be modified by user-defined arguments, like an "as of" date or GraphQL field selection.)
* A bulk download contains multiple records with the same OCID. 

As such, we might need a paragraph to explain that it is per contracting process **per distribution** (in the sense of [DCAT](https://www.w3.org/TR/vocab-dcat-2/)), where a distribution might be a specific API endpoint or a specific bulk download file.

**Comment by duncandewhurst** [comment]
I suggest updating the first sentence of https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/ to read:

> A record aggregates the releases related to a contracting process. There should be a single record per contracting process per [distribution](https://www.w3.org/TR/vocab-dcat-2/#Class:Distribution), where a distribution might be a specific API endpoint or a specific bulk download file.

To account for old records and API methods with an "as of" argument, we might need to clarify the following requirements:

* a record must provide a list of **all the existing** OCDS releases
* the compiled release contains the **current state** of all the fields
* A versioned release aggregates all values of all fields from **all releases**

Variations on those requirements appear in several places:

* Record package schema:
  * `description`
  * `definitions.Record.description`
  * `definitions.Record.properties.releases.description`
  * `definitions.Record.properties.compiledRelease.description`
* Record reference:
  * https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#record-structure
  * https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#compiled-release
  * https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#versioned-release
* https://standard.open-contracting.org/staging/1.2-dev/en/getting_started/releases_and_records/

One option is to add 'at the time of publication', which is already used to describe a compiled release in https://standard.open-contracting.org/staging/1.2-dev/en/schema/records_reference/#record-structure. @jpmckinney, what do you think?

We should also update the following sentence from https://standard.open-contracting.org/staging/1.2-dev/en/getting_started/releases_and_records/:

> While releases are never updated, records are updated each time there is a change.

to

> While releases are never updated, records can be updated each time there is a change.

**Comment by jpmckinney** [comment]
All sounds good. I think "at the time of publication" works well.
