### ISSUE TITLE
Release date must be unique within a contracting process

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#848]
The merging rules begin with:

> Order all the releases that share an `ocid` by their release `date`. Starting from the oldest release (old), compare it with the next oldest release (new), and apply the following rules...

But I don't think we state anywhere that two releases under the same `ocid` must not share the same `date` to make this ordering possible.

I suggest adding this uniqueness requirement to the description of `date` in the schema and implementing it as an additional check in the data review tool.

**Comment by jpmckinney** [comment]
Would 'must' be backwards-compatible, or do we need to relax to 'should' for OCDS 1.2?

Copying that this came up where a publisher "was updating the release date for all releases relating to a contracting process whenever anything changed."

Regarding the latter, that behavior is already blocked by the rule that releases are immutable and must not be changed (without a change in release `id`).

**Comment by JachymHercher** [comment]
> Would 'must' be backwards-compatible, or do we need to relax to 'should' for OCDS 1.2?

Philosophically, I'd say that if you want, you have some discretion in this. Since the definition of `releaseDate` is "The date on which the information contained in the release was first recorded in, or published by, any system.", I think you could argue that the "first" implies there is only one, because things never happen in precisely the same moment. 

More pragmatically, you could check a reasonable sample of OCDS-compliant data and see whether this type of things occurs. If it does, then we probably shouldn't treat it as backwards compatible, because adding such a condition into 1.2 would mean that some old releases would stop be OCDS compliant because of a version change.

**Comment by ColinMaudry** [comment]
> The date on which the information contained in the release was first recorded in

That rule also applies to cases where the releases have the same `ocid`, same `date` but different content.

> things never happen in precisely the same moment.

They do... in the world of software. For instance two releases could be generated at the same time, each describing part of a `tender`. It's not good programming, but it's possible.

**Comment by ColinMaudry** [comment]
Unless data shows that it doesn't happen, I would proceed with the change without breaking compatibility ("should").

**Comment by duncandewhurst** [comment]
I'm happy with a 'should' in the schema as long as we can include an additional check in the DRT to catch the type of error that prompted the issue.

**Comment by ColinMaudry** [comment]
I suggest the following description for `date`, using part of the description of `id`:

> The date on which the information contained in the release was first recorded in, or published by, any system. The release date should be unique within the scope of the contracting process identified by the Open Contracting ID (ocid), for a given version of OCDS.

**Comment by jpmckinney** [comment]
Okay, so the first sentence is identical to the current definition. The second sentence is based on:

> The release ID must **be unique within the scope of the contracting process identified by the Open Contracting ID (ocid), for a given version of OCDS**. In other words, a publisher may publish datasets for different versions of OCDS, and repeat releases within each dataset.

That looks good to me 👍
