### ISSUE TITLE
Describe the normative status of non-required fields in the schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#856]
Currently the [building blocks](http://standard.open-contracting.org/latest/en/getting_started/building_blocks/) page in the getting started section states:

> The OCDS schema sets out the fields that should be included in each section...

To avoid overfill that statement will come with a caveat of "where applicable" in 1.1.4

In 1.1.5 we should consider how the statement can be featured more prominently (e.g. in the schema reference section) and explained more fully to help users understand the normative status of non-required fields in the schema.

**Comment by jpmckinney** [comment]
Agreed – "where applicable" can be unpacked, and in general the [release handling](http://standard.open-contracting.org/latest/en/schema/reference/#release-handling) part of the schema reference page should either come first, or have its own page, as otherwise it's easily forgotten at the bottom of that page.

**Comment by jpmckinney** [comment]
09f4ccbb75a38e03ecf9d306efb3228859986ee7 moved release handling up the page.

**Comment by jpmckinney** [comment]
#1035 was closed in favor of not adding explicit language as to the requirement level for field presence.

If there is renewed interest in adding an "advocacy norm" to the reference section, that issue should engage the broader community, as we do not expect all stakeholders to be in agreement from the start on the requirement level for each field. This would be appropriate for version 1.2.0.

For clarity, other advocacy norms include the [Open Contracting Global Principles](https://www.open-contracting.org/what-is-open-contracting/global-principles/), the recommendations of the [Mythbusting Confidentiality in Public Contracting](http://mythbusting.open-contracting.org) report, and the (draft) [assessing data quality](https://standard.open-contracting.org/1.1-dev/en/guidance/design/levels/) guidance.
