### ISSUE TITLE
Add IANA Media Types codelist

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#857]
`Document.format` refers to the codelist, but the schema doesn't specify it. We would need a script like the one for the currency codelist.

http://www.iana.org/assignments/media-types/

**Comment by jpmckinney** [comment]
This would have to start as an open codelist in 1.2.0, then switch to a closed codelist in 2.0.0.

**Comment by duncandewhurst** [comment]
I've written a simple script, similar to `fetch_currency_codelist.py`, to fetch the media types from the CSV files on https://www.iana.org/assignments/media-types/media-types.

There's a couple of issues to address before making a PR:

**Missing values**

`Document/format` specifies the values in the IANA list's 'Template' column, which consist of the type and subtype (e.g. application/pdf), but some media types do not have a value in the template column. For example:

![image](https://user-images.githubusercontent.com/19265814/121975113-fb6e4200-cdd4-11eb-8dc6-0074eebb66c0.png)

I searched the various RFCs linked from the reference and notes sections of https://www.iana.org/assignments/media-types/media-types.xml, but I couldn't find an explanation for the missing template types.

However, the missing type/subtype codes (e.g. image/gif, image/jpeg) seem to be in common usage (e.g. the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types)), so it seems like they might simply be omissions from the IANA page. In which case, should I update the script to generate necessary values by combining the type and the subtype?

**Deprecated/Obsolete types**

Deprecated and obsolete types are noted in the 'Name' column. For example:

![image](https://user-images.githubusercontent.com/19265814/121975276-59028e80-cdd5-11eb-8047-c36801f8299c.png)

With one exception (vnd.geo+json), it should be possible to extract the notes into a separate column by splitting the Name column on ' - '.

Should I update the script to do that?

**Comment by jpmckinney** [comment]
Yes, please update the script in those ways.

FYI, all the scripts will be later consolidated into a single `manage.py` interface: https://github.com/open-contracting/standard_profile_template/issues/40
