### ISSUE TITLE
Add ISO639-1 language codelist

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#858]
The language fields allow BCP47 language tags, but we can at least have an open codelist containing the ISO639-1 language codes (which are the recommended values). We would need a script like the one for the currency codelist.

http://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by duncandewhurst** [comment]
+1

I came here via some publisher data which used 'english' in the language tag and wasn't flagged by the validator

**Comment by akuckartz** [comment]
Linked Data can be used. See http://id.loc.gov/vocabulary/iso639-1.html

**Comment by duncandewhurst** [comment]
It seems like the TSV file would be the easiest to integrate: http://id.loc.gov/vocabulary/iso639-1.tsv
