### ISSUE TITLE
Remove discouragement of UNSPSC

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#864]
i.e. remove "Machine-readable metadata for UNSPSC is not provided as open data; publishers are encouraged to consider alternative classification schemes that do provide open data lookup tables wherever possible."

There are other schemes/codelists/formats that we list that aren't open data either (e.g. anything ISO), yet they don't have this disclaimer.

**Comment by timgdavies** [comment]
There may be a relevant difference from the use-case perspective here between classifications and other codelist.

Although most ISO codelists are not formally openly licensed:

* (a) in practice they are accessible / usable without paying for the codelist;
* (b) their inclusion in a dataset does not generally lead to that dataset being provided under a non-open license (not sure of the exact legal position on this, but precedent certainly appears to be that using an ISO code in a dataset does not constitute IP infringement)

In the case of UNSPSC, at the time of originally writing that caveat, I recall we considered:

* (a) If a dataset only uses UNSPSC codes (without labels) then the user has to pay for access to interpret the data. Even low costs can be prohibitive for some users.
* (b) If the dataset includes codes and labels, and covers a large set of the overall UNSPCC scheme, then it may not be possible to use open license on the resulting OCDS dataset. 

I'm not sure on (b) - but mentioning as something that should perhaps be reviewed. 

If #864 is taken forward, I might suggest a related issue be opened to have policy advocacy from OCP for UNSPCC to be made available as a fully open dataset....

**Comment by jpmckinney** [comment]
We can certainly check (b), though I suspect that the answer is the same as for ISO and others, who don't aggressively pursue publishers about such publication. If so, then we can instead encourage publishers to include titles/descriptions of codes, rather than discourage UNSPSC entirely.

Regarding (a), there is a free PDF at http://www.unspsc.org/codeset-downloads A quick search for a snippet from the PDF ("This segment includes live, wild and domesticated, seeds and plants and animals. This segment also") suggests that many governments republish all or part of the UNSPSC. A [Google Search](https://www.google.com/search?q=%22This+segment+includes+live%2C+wild+and+domesticated%2C+seeds+and+plants+and+animals.+This+segment+also%22+filetype%3Axlsx) suggests that some even publish the XLSX, though only for the version they are using.

We can reach out to GS1 and the UNDP about ensuring easy access to the codes' metadata.

**Comment by otravers** [comment]
Yes, I have seen several OCDS publishers release their version of UNSPSC on the public internet, for instance Colombia. I know that copyright is weakened if you don't pursue its enforcement, that said it would indeed be great if OCP could reach out to organisations such as UNDP so that the use of their standards by publishers doesn't become a sort of poison pill in OCDS datasets.

Otherwise using these datasets would come with a legal liability for developers who want to build something on top of said OCDS datasets, especially for commercial applications.

**Comment by jpmckinney** [comment]
Indeed. As a separate issue, OCP can consider guidance on what IP issues to consider when licensing OCDS data and related documents (e.g. IP in linked documents or non-open codelists). I consider that issue distinct from compliance with the standard.

**Comment by jpmckinney** [comment]
Tagging @LindseyAM as FYI regarding licensing considerations for OCDS datasets that contain non-open data, and advocacy opportunities for UNSPSC to be openly licensed.

**Comment by jpmckinney** [comment]
Closed by #967 on 1.1.5-dev branch.
