### ISSUE TITLE
Final steps to deploy 1.1.4

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#874]
* [x] [Push and pull updated translations](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#push-and-pull-updated-translations)
* [x] Add date of release to changelog when merging
* [x] Merge the development branch onto the live branch
* [x] Create a tagged release
* [x] [Build and deploy](https://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/deployment/#build-and-deploy)

After merge:

* [x] Deploy redirects (CRM issue 4401)

After deploy:

* [x] Release new version of OCDS Merge #811
* [ ] Contact publishers (CRM issues 4438 and 4439)
* [x] Address TODOs in standard-maintenance-scripts
* [ ] Update public templates, etc. (CRM issue 4580)

**Comment by jpmckinney** [comment]
@robredpath I forget who we said would be available to deploy OCDS 1.1.4, so assigning to you in first instance. I've done all the checked tasks above. To do are the steps linked from 'Build and deploy'.

**Comment by robredpath** [comment]
@kindly is going to do the 'Build and deploy' part of the list above
@odscjames will then release the update to CoVE that's required to work with 1.1.4, and carry out the 'Deploy redirects' step. 

Do you need anything from us for the other steps?

**Comment by ghost** [comment]
Build and Deploy and redirects done

**Comment by jpmckinney** [comment]
Great, thanks! The remaining issues are in the CRM, so closing this issue.

**Comment by ghost** [comment]
Cove and Kingfisher Deployed with 1.1.4
