### ISSUE TITLE
Can we put 1.1.4 schema on http://standard.open-contracting.org/schema/1__1__4/ now?

### ISSUE THREAD

**Issue by ghost** [open-contracting/standard#876]
We are trying to test software in advance of the official release of 1.1.4 so that we can find and fix any problems early. 

We were using the schema at https://raw.githubusercontent.com/open-contracting/standard/1.1.4-dev/standard/schema/X.json to do that.

However we have hit a problem - those schema files have refs to http://standard.open-contracting.org/schema/1__1__4/release-schema.json which currently 404's.

So we are looking at solutions and we thought we would just check the easiest first - can we put  the 1.1.4 schema files on http://standard.open-contracting.org/schema/1__1__4/ now?

**Comment by jpmckinney** [comment]
Yes, please take the files from the `1.1.4-dev` branch. They will not change between now and being merged into the `1.1` branch.

**Comment by jpmckinney** [comment]
Related: https://github.com/OpenDataServices/cove/issues/1177

**Comment by ghost** [comment]
Just seen earlier comment, sorry! Thanks
