### ISSUE TITLE
HTTPS 

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#878]
Noticed that [https://standard.open-contracting.org](https://standard.open-contracting.org) gives ERR_CONNECTION_REFUSED. 

Should we consider providing the standard over https? Or at least provide a better error message?

**Comment by jpmckinney** [comment]
@odscjames or @robredpath: It should be fairly quick to add a Let's Encrypt cert?

**Comment by ghost** [comment]
Yes, we even have salt scripts that make this easy.

We even discussed this previously; our plan was to put on the cert in "serve both" mode at first, http and https. We would then put a warning out on the community list and leave it a month, to make sure there were no weird edge cases. We would then switch it so any http traffic was redirected to https. Does that sound good?

However I did actually previously try to put a SSL cert on the OCDS CoVE, and there are complications due to how the live site proxies some content through to the dev server and the OCDS CoVE server. I need to research and test some things around the proxy before we can go ahead with this.

What's the priority on this?

**Comment by jpmckinney** [comment]
It was listed as a bullet in the planning section of the sprint document, so it'd be good to figure out over this summer.

**Comment by ghost** [comment]
Ok. To start with, I have made the dev site serve both http and https. I don't think there is any harm in this; if people find the https version but find a problem, well, it is the dev site. And this is a test site where we can try some things.

**Comment by jpmckinney** [comment]
Not sure if related but URLs like http://standard.open-contracting.org/1.1-dev/en/ (proxy from live) 404 now, though http://dev.standard.open-contracting.org/1.1-dev/en/ (dev) loads.

**Comment by ghost** [comment]
It was because of SSL - just adding SSL messes up the host names proxing relies on. Turned SSL off for now.

**Comment by ghost** [comment]
Now we have testing sites, I can look into this. 

In the Apache config for Live, we need to set ProxyPreserveHost to off. Loading a file in the review tool works, looking at something that proxies to the staging server works.

However, this causes a bug with language switching in the review tool. If you try and switch language, you are redirected to the home page. If you then select the review tool again, you'll find the language switch has worked. 

So I'm looking into Django's I18N switching - https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#the-set-language-redirect-view describes where the redirect happens

**Comment by ghost** [comment]
That pull request is now live and the language switching bug seems fine, with ProxyPreserveHost off.

Next is to turn ProxyPreserveHost off and test again carefully on testing site.

If happy, change ProxyPreserveHost on live site.

**Comment by ghost** [comment]
Did some more testing with @pindec's help

* Search doesn't work - however looking at the code, and how the search server uses the base_url to find results I think this is expected and is nothing to do with ProxyPreserveHost.
* The Share link in the data review tool has the wrong hostname. I'll look into that.

**Comment by ghost** [comment]
Turned on USE_X_FORWARDED_HOST in OCDS CoVE, Share link now works. I'll have a final check today, and first thing tomorrow I may turn off ProxyPreserveHost on the live site.

**Comment by ghost** [comment]
I have now turned off ProxyPreserveHost on the live site. Let us know if you see any problems.

**Comment by ghost** [comment]
Cove server is now on SSL, and all traffic from live server to Cove server goes over SSL

**Comment by ghost** [comment]
Staging server is now on SSL, and all traffic from live server to staging server goes over SSL

**Comment by ghost** [comment]
The real live site is now available on both HTTP and HTTPS! 

Search is broken on HTTPS but not HTTP, looking at that.

**Comment by ghost** [comment]
https://github.com/OpenDataServices/standard-search/pull/4

**Comment by ghost** [comment]
That should be search fixed; I'll double check some other things now. SSL is available on staging and test sites too.

We would suggest that we post to the discussion list with something like the below. If no problems are reported in a month, then we'll turn on HTTP redirecting to HTTPS.



SUBJECT: Standard site now available with SSL! Please check for problems.

We want to add SSL to the standard site - this gives us added security for people using the site, and added peace of mind for us, and an SEO boost too!

https://standard.open-contracting.org/latest/en/ is now available.

At the moment, both the existing site http://standard.open-contracting.org/latest/en/ (non-SSL) and the new site https://standard.open-contracting.org/latest/en/ (with SSL) are available separately. The content and functionality should be the same on each one.

We would like to invite you to try out the new SSL site. In particular, if you have any scripts or apps that fetch the OCDS schema direct from the site, please test them to make sure they will work fine with SSL.

If you have any problems, please let us know at STANDARD-HELPDESK-EMAIL. 

If no-one reports any problems, in one month from today we will be setting up the non-secure site to redirect automatically to the secure SSL site. That will complete our move to SSL.

Thanks,

**Comment by jpmckinney** [comment]
Sent: https://groups.google.com/a/open-contracting.org/d/topic/standard-discuss/3zOUfY1LcyQ/discussion

**Comment by jpmckinney** [comment]
I've updated all URLs in all our tools to use the `https://standard…` URL (except CoVE and Flatten Tool – and the URLs in Kingfisher, which were only in tests or docs). I think the last thing to do is redirect from HTTP to HTTPS, for which I created https://github.com/OpenDataServices/opendataservices-deploy/issues/77
