### ISSUE TITLE
Favicon redirects

### ISSUE THREAD

**Issue by ghost** [open-contracting/standard#879]
While watching apache logs to check another problem, I just noticed 

http://standard.open-contracting.org/favicon.ico

redirects to 

http://standard.open-contracting.org/favicon.ico/en

**Comment by jpmckinney** [comment]
It no longer redirects. It now just 404s without redirection, which is fine. favicon is specified via meta tag. https://github.com/open-contracting/deploy/commit/1e69b643a9745edddf87af3ade8a65ebea855beb
