### ISSUE TITLE
Discussion: Move other blocks to top-level, similar to parties

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#893]
In https://github.com/open-contracting/standard/issues/888#issuecomment-513992335, we have a case where multiple items have the same delivery location. If this repetition is acceptable, there is no action here. Otherwise, we can consider moving locations to the top-level and using references, much like organization references to the top-level `parties` array.

There may be other objects that are frequently re-used that ought to be given the same treatment.

For comparison, the EU's [eForms](http://ec.europa.eu/transparency/regcomitology/index.cfm?do=search.documentdetail&Dos_ID=17796&DS_ID=62369&Version=1) have little hierarchy, with more references.

**Comment by mrshll1001** [comment]
I've sometimes thought that the Document blocks could be moved into a top-level array similar to parties, and referenced appropriately. However the flip side of this is that documents are often tied quite closely to the stage of procurements; so might not make as much sense to do this as I originally think. Keen to explore it as an option.

**Comment by jpmckinney** [comment]
@mrshll1001 Are documents frequently duplicated across the many arrays? If not, there is less of a motivation to make the change. (We can of course test for this in Kingfisher Process.)

**Comment by yolile** [comment]
what about the items? at least their description and classification/additional classifications etc and the in the "item reference" we can add the quantities, values. etc

**Comment by jpmckinney** [comment]
Hmm, it would be a somewhat different model, but it could work. In what cases are an item's description/classification/etc. duplicated? (Besides between tender, award and contract.)

**Comment by yolile** [comment]
I was thinking on #904 where we used items in auctions in the auction stage and also in [#126](https://github.com/open-contracting/ocds-extensions/issues/126) in the bid stage

**Comment by yolile** [comment]
an example from Paraguay where there is partial duplication between tender.items and award.items: https://contrataciones.gov.py/datos/api/v3/doc/ocds/record/ocds-03ad3f-331547-2

**Comment by duncandewhurst** [comment]
I haven't seen examples of the same document being duplicated across multiple arrays.

With regard to items and locations, we should consider the trade-off between reducing repetition, adding complexity for data users (joining to a top-level array), and introducing the risk of inconsistencies (between the `id` in a reference and the `id` in a top-level array).

**Comment by jpmckinney** [comment]
Items have values that can be different in each context (e.g. total quantity that a buyer wants to purchase, vs quantity a bidder is offering, vs the quantity awarded to a supplier).

I think a system of "partial" references doesn't have any promise. It would be confusing. We allow `name` in organization references, but it's expected to be consistent and is only provided for ease of use.

We haven't identified other candidates for promotion to the top-level, so closing.
