### ISSUE TITLE
Link to release schema from Release Package Schema.releases is broken

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#894]
In the [Release Package Schema browser](http://standard.open-contracting.org/latest/en/schema/release_package/), the releases field displays a text URL to 1_1_4 instead of a clickable button to the release schema.

**Comment by jpmckinney** [comment]
Hmm, that's a bug. Something to add to the checklist before deploying!

**Comment by jpmckinney** [comment]
It seems to have been fixed: https://standard.open-contracting.org/latest/en/schema/release_package/
