### ISSUE TITLE
Purchase orders

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#897]
Splitting from #396 and copying questions in issue description:

* Should purchase orders fall within the scope of OCDS?

Yes. They can provide important details on the fulfillment/implementation of the contract.

* How should purchase orders be modelled in OCDS, e.g. should these be modelled using `contract.implementation.transactions` or do they represent a contract in themselves?

Semantically, purchase orders are not transactions.

@georgneu wrote:

> A brief look at a purchase order seems to indicate that most of the information is covered in the contract data so it could be integrated there.

@chrisalexsmith wrote:

> Would suggest that purchase orders do represent contracts but are linked to the head contract.

Indeed, [the acceptance of a purchase order forms a legal contract](https://en.wikipedia.org/wiki/Purchase_order). However, per #896, they do not belong in the `contracts` array. The proposal is instead to author a purchase orders extension, e.g. `contracts.implementation.purchaseOrders`, and to include guidance on how to model the contract under which the purchase orders are issued, per the discussion in #896.

* What are the use cases for disclosure of purchase order level data?

@georgneu wrote:

> Just flagging that purchase orders (orden de pago) is information that Argentinean civil society would be looking for. They see this as the key document that provides them with the information on who and what.

* Is data on purchase orders typically captured in the same information systems as data on contracts (framework contracts in particular) or does it exist in separate systems?

@chrisalexsmith had indicated the integration of both types of data in some systems. However, as is often the case, this is not how e-GP systems are universally implemented.

**Comment by duncandewhurst** [comment]
> The proposal is instead to author a purchase orders extension, e.g. `contracts.implementation.purchaseOrders`, and to include guidance on how to model the contract under which the purchase orders are issued, per the discussion in #896.

From @yolile: Paraguay has a [purchase orders extension](https://gitlab.com/dncp-opendata/ocds_contract_implementation_purchaseOrder_extension) ([example data](https://www.google.com/url?q=https://contrataciones.gov.py/licitaciones/adjudicacion/contrato/361936-ambrosio-coronel-1.html%23ordenes&sa=D&ust=1580957262452000&usg=AFQjCNFIgXzGEW_BtXyagVUnPgYkdKgShQ))

**Comment by jpmckinney** [comment]
Closing as the extension is published.

**Comment by duncandewhurst** [comment]
Edit: Wrong issue

**Comment by yolile** [comment]
Note that now in Paraguay, they also have the information about how many items are required per purchase order, so they will update their extension to add `items` at the purchase order level. FYI @fppenna
