### ISSUE TITLE
Item Classification Scheme Versions

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#898]
One of the items classification scheme suggested (and used by many LATAM countries) by the standard is the UNSPSC scheme, but this scheme has [several different versions](https://www.unspsc.org/codeset-downloads). Maybe it is important to add the information about the version used too?

**Comment by jpmckinney** [comment]
What changes between versions?

If in one version a code means one thing and then in another version it means something else, then they are different schemes, and the version should form part of the scheme identifier.

If newer versions just add more classifications to older versions, then it might be better to treat them as the same scheme, and to put the version information in a separate field.

On the other hand, perhaps it's simplest to always include the version in the scheme identifier.

What do you think?

**Comment by yolile** [comment]
As far as I know the new versions only add more classifications. Another important thing is that some codes are availabe only for some languages, so maybe another thing to include in the schema identifier is the langague?

**Comment by jpmckinney** [comment]
Can you give an example re: languages? I'm not too familiar with UNSPSC.

If codes are only added, wouldn't it be prudent for data users to always try to use the newest version of UNSPSC? If they use an older version, and there are some codes from the newer version, then that's a reminder to them to upgrade.

**Comment by jpmckinney** [comment]
If codes are only added, then it is sufficient to simply indicate 'UNSPSC'. A data user would have to download the latest version of that codelist to be sure that they can interpret all codes.

I briefly searched UNSPSC's documentation, and couldn't find codes whose use is exclusive to a specific language. In any case, such restrictions on which codes are allowed from the full codelist are the responsibility of the data-entry systems, not of OCDS, which is concerned with interpretation, not with jurisdiction-specific validation.
