### ISSUE TITLE
Item: Sub Items

### ISSUE THREAD

**Issue by yolile** [open-contracting/standard#899]
In Paraguay, an item can have related sub items associated to it, here is an [example](https://contrataciones.gov.py/licitaciones/convocatoria/356694-lp1494-19-servicio-reparaciones-integrales-vehiculos-flota-ande-1/item-solicitado/ild4ZP92015g3mM07iELNw%253D%253D/sub-items.html) 
The common use of this is for tenders releated to, for example, the maintenance of vehicles, where the item is the services and the sub items are each part of the vehicle that need to be replaced/manteined (as the example)

The proposal is to add the field "relatedItem" to the "tender/item" field to indicate if that item is part of another one

**Comment by jpmckinney** [comment]
Two comments:

1. `relatedItem` doesn't clearly indicate the nature of the relationship (we might identify in future other ways in which items can be related, other than parent-child).
1. If we put sub-items at the same level of hierarchy as their parent items, then some use cases get more complicated. For example, I might want to compare the sum-product of item quantities and values to the tender value. If I do this naively on a dataset with sub-items, I'll end up with 2x the total than if sub-items were omitted (assuming the sum-product of sub-item quantities and values equals the total value of the item).

Given (2) I think it is better to have a `subItems` or `itemBreakdown` field on `Item`.

**Comment by yolile** [comment]
You are right, so I will go with 'subItems' array of Item objects inside Item

**Comment by yolile** [comment]
I forgot to mention that, at the subitem level there are some (not all) subitems that are just the "header" or parent of another subitems, example:
1. Item
1.1 SubItem -> just a header (number + name only)
1.1.1 Subsubitem -> the actual info

You can see that in the example. Should I put a field "parentSubItem" at subItem level?

**Comment by jpmckinney** [comment]
It might be simpler to just duplicate the header as an additional field on the sub-item. Otherwise, it is very strange to have 'empty' items. What do you think?

**Comment by yolile** [comment]
I talked with the technical people at DNCP and we agreed on having an extra field with the number and title of the subitem at the subitem itself for all the subitems. So if a subitem doesnt have a header, the header will be its self number and title to be consistent. So, for example if we have:
1. Item
1.1 Sub Item Header
1.1.1 Sub Item
2.2 Sub Item without header

The modeling approach will be:

```` json

{
  "items": [
    {
       "id": "1",
       "description": "Item",
       "subItems": [
         {
           "group": "1.1 - Sub Item Header",
           "id": "1.1.1",
           "description": "Sub Item" 
         },
         {
           "group": "1.2 - Sub Item without header",
           "id": "1.2",
           "description": "Sub Item without header" 
         }
       ]
    }
  ]
}
````

**Comment by jpmckinney** [comment]
Looks good to me, thanks for reporting back!

**Comment by yolile** [comment]
Extension available here: https://gitlab.com/dncp-opendata/ocds_items_subItems_extension
Note that the SubItem object is not a Item object, because the flatten tool gives a recursion error when the Item has a Item field inside itself.

**Comment by jpmckinney** [comment]
Closing as the extension is published.
