### ISSUE TITLE
Expand tender.contractPeriod description

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#902]
> The period over which the contract is estimated or required to be active. If the tender does not specify explicit dates, the duration field may be used.

The EU standard procurement forms use the construction "Duration of the contract, framework agreement or dynamic purchasing system", to avoid ambiguity around which contract this period refers to (as there can be many contracts over different periods, especially in the latter cases).

**Comment by jpmckinney** [comment]
@ColinMaudry Can you check if there are any other occurrences of "contract" that should similarly be substituted?

Also, in the PR, use "the contract, framework agreement or dynamic purchasing system" without repeating "the" (it's currently "the contract, the framework agreement or the dynamic purchasing system".

**Comment by JachymHercher** [comment]
Based on https://github.com/open-contracting/standard/issues/827#issuecomment-728036400, we probably do not need to expand definitions. (By contrast, we might want to look for opportunities to ~contract them~ remove unnecessary repetitions of the definitions.)

**Comment by jpmckinney** [comment]
I don't think we have many occurrences of repetition, but this should be covered while doing #827. I'll close this issue in favor of your linked comment.
