### ISSUE TITLE
Guidance: Explain when to use contract items

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#911]
The repetition of `items` on both `Award` and `Contract` leads to confusion.

The reason there is `items` on `Contract` is, according to earlier issues, because it was thought that it'd be possible for one supplier to be awarded multiple items, and that there might later be different contracts for each item (I don't know if this happens in reality): https://github.com/open-contracting/standard/issues/103#issuecomment-57624960

The description of `items` on `Contract` mentions:

> Note: If the items are the same as the award do not repeat.

This issue is about adding guidance to the documentation to describe real scenarios in which the items on the contract might differ from the items on the award. Initial ideas:

* The award is for an unspecified quantity, which is only determined at the contract stage
* The award is for a category of items (e.g. in the case of an electronic catalogue for data processing machines), and the specific items are only determined at the contract stage (#396)
* A framework agreement with direct call-offs (similar to the two above)

We might find other real scenarios where there is e.g.: a large quantity on the award, and then multiple contracts each with smaller quantities (not to be confused with purchase orders #897); or, an award with many items to one supplier, and then multiple contracts each with one item.

This breaks out from #249

**Comment by timgdavies** [comment]
I think we also envisaged the possibility that, in the negotiation between award and contract, there may be a variation in the items to be supplied.

Again - I'm not certain (a) how often this happens in practice; (b) if any existing systems capture the data in ways that could populate this.

**Comment by duncandewhurst** [comment]
> * The award is for an unspecified quantity, which is only determined at the contract stage

In what type of procurement procedure would this be the case? In the `secondStage` model proposed in #440, the `awards` section would be used for the award of call-offs etc. (when the quantity is known) and suppliers being awarded a place on the framework/list etc. (when the quantity isn't known) would be modelled elsewhere.

> * The award is for a category of items (e.g. in the case of an electronic catalogue for data processing machines), and the specific items are only determined at the contract stage (#396)

Are there examples of electronic catalogs which are established through a one-stage procedure? The discussion in #396 suggests these would be established through a two-stage procedure, in which case the considerations from #440 noted above would apply.

> * A framework agreement with direct call-offs (similar to the two above)

Based on #440 I think this would no longer apply.

**Comment by jpmckinney** [comment]
In short: I don't have a clear, real example of when to use contract items.

## Use cases for contract items

I think you're right that once we clarify how to model two-stage procedures in a way that is consistent (where appropriate) with how we model single-stage procedures, then the use cases for contract items become very narrow.

There was a related discussion starting from this comment https://github.com/open-contracting/standard/issues/896#issuecomment-517300154, but we either determined that quantities were specified at the award stage, or that the procedure had two stages. @yolile: Are there any cases in DNCP where quantities are unspecified at the award stage?

In the EU, a Modification Notice [refers to](https://standard.open-contracting.org/profiles/eu/latest/en/forms/F20/#section-iv) and modifies a Contract Award Notice. The EU profile [maps this](https://standard.open-contracting.org/profiles/eu/latest/en/forms/F20/#release-model) to an 'awardUpdate' and 'contractUpdate', and [sets `contracts.items`](https://standard.open-contracting.org/profiles/eu/latest/en/forms/F20/#section-vii), but in retrospect I'm not sure if perhaps it's just an 'awardUpdate' that should set `awards.items`.

## Contract items in OCDS 1.1

With OCDS 1.1 (and in the issue description), we're basically using contract items as a proxy for the second stage, which leads to inconsistent semantics. In OCDS 1.1, for two-stage procedures, `awards` indicates a supplier's progression to the second stage (e.g. being added to the list of qualified suppliers in a framework agreement), and `contracts` indicates their obligation to provide specific items (e.g. direct call-offs); for single-stage procedures, and for two-stage procedures where the second-stage isn't disclosed (e.g. a restricted procedure in the EU), `awards` indicates the obligation to provide specific items, and `contracts` reflects what follows (implementation, etc.).

With OCDS 1.2, we want to have more consistent semantics, so that (as much as possible) users can analyze the same fields in the same way, regardless of whether the procedure is two-stage.

That said, in terms of semantics, things might get a little fuzzy in the case of framework contracts, i.e. framework agreements with single suppliers. In that case, the progression to the second stage might already indicate an obligation to provide a minimum quantity of items; I'd have to double-check. Anyhow, I think that degree of fuzziness is acceptable.

**Comment by jpmckinney** [comment]
For this issue, in terms of OCDS 1.1, we can chose to provide guidance that is consistent with the current model, though we know it is likely to change in OCDS 1.2 – or wait for OCDS 1.2.

We might want to check the use of `contracts.items` to decide whether guidance is needed in the shorter term (i.e. check @pindec's OCDS 1.2 research).

**Comment by yolile** [comment]
> @yolile: Are there any cases in DNCP where quantities are unspecified at the award stage?

There are cases where the quantity is a range, eg https://contrataciones.gov.py/licitaciones/adjudicacion/contrato/373301-asismed-san-roque-s-a.html#itemsLote

**Comment by romifz** [comment]
The guidance in #974 seems to cover the use of `contracts/items` (Awards and contracts page). I'm not sure if there is anything to add there, but if not I think we can close this issue.

**Comment by jpmckinney** [comment]
Yes, I think https://standard.open-contracting.org/1.1-dev/en/guidance/map/mapping_awards_contracts/ is enough for 1.1. Per https://github.com/open-contracting/standard/issues/911#issuecomment-572174246, we don't really have other great examples for when to use contract items, and the model might change in future versions to leave less ambiguity, so I think okay to close.
