### ISSUE TITLE
Guidance: Explain when to have multiple suppliers per award

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#912]
Initial ideas:

* Consortia, where multiple suppliers put together a single bid, and are awarded as a group. In some countries, these suppliers only create a legal entity after the award, to sign the contract; or, they decide on a prime contractor, with the others being subcontractors. #370 #142

Noting that the current model for framework agreements has multiple suppliers (it stores the 'multi-use list' as suppliers on an award #909), though this might change per #440 and #909.

**Comment by yolile** [comment]
In the new guidance this is mentioned in: 
1) https://standard.open-contracting.org/latest/en/guidance/map/awards_contracts_buyers_suppliers/#id1
> Suppliers are modelled as relating to awards in OCDS and there can be multiple suppliers per award, i.e. all contracts relating to the same award share the same suppliers.

2) And then in https://standard.open-contracting.org/latest/en/guidance/map/consortia/
> In such cases, the Award object in OCDS can have multiple suppliers associated with it, one for each member of the consortium.

are those enough to close this issue or should we add the consortia reference in 1) ?

**Comment by jpmckinney** [comment]
Let's link to the consortia example from the Reference section, at https://standard.open-contracting.org/latest/en/schema/reference/#award e.g.

> There can be multiple suppliers for a single award: for example, in the case of [consortia]().

The description of `suppliers` is:

> The suppliers awarded this award. If different suppliers have been awarded different items or values, these should be split into separate award blocks.

We might add:

> There can be multiple suppliers for a single award if, for example, the award recipient is an unincorporated consortium.

**Comment by jpmckinney** [comment]
Ah, I forgot this was for 1.1. I think for 1.1 there is nothing more to do, so I'll change to 1.2.

**Comment by jpmckinney** [comment]
Once we settle on the framework agreements worked example, we can mention them the same as consortia.
