### ISSUE TITLE
Add recommendation to put hyphen after OCID prefix

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#917]
This is the practice in most implementations (and all examples), but it is not explicit. We can't make it a MUST rule, because that will be backwards-incompatible with at least Zambia.

**Comment by ColinMaudry** [comment]
Should the `description` of the `ocid` field in the schema be updated? It may be sufficient to only update the documentation, since neither the semantics, the structure nor the validation rules change.
