### ISSUE TITLE
releaseTag: Investigate / Deprecate tenderAmendment and contractAmendment

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#918]
## Background

The differences between 'tenderAmendment' and 'tenderUpdate' are:

* 'tenderAmendment' mentions "The term amendment has legal meaning in many jurisdictions."
* 'tenderUpdate' mentions "An update may add new information or make corrections to prior published information. It should not be used for formal legal amendments"

The differences between 'contractAmendment' and 'contractUpdate' are similar.

## Problem

1. What is the purpose of distinguishing between a 'tenderAmendment' and a 'tenderUpdate'?
1. Do publishers correctly distinguish the two when assigning tags to releases?
1. In my experience, there is no such thing as an 'informal' change, and all changes must be legal…

## Proposal

Unless there is a clear purpose to distinguishing the two codes, the proposal is to deprecate the '*Amendment' codes, and keep the '*Update' codes, which are more generic and which align with other codes in the codelist. The semantics would be such that older data using the '*Amendment' codes would be interpreted as using the '*Update' codes.

**Comment by duncandewhurst** [comment]
In AusTender, for contract notices, there is a distinction between:

* material changes, which cannot be made without issuing a contract amendment notice; and
* non-material changes, which can be made to existing contract notices

**Comment by duncandewhurst** [comment]
> What is the purpose of distinguishing between a 'tenderAmendment' and a 'tenderUpdate'?

When working with a release dataset it make it possible to answer questions like "How many contract amendments did the department of transport make in Q4 2019?" without having to compile releases.

> In my experience, there is no such thing as an 'informal' change, and all changes must be legal…

Whilst that may be true of the tenders and contracts themselves, other information may be provided during the life of a tender or contract in OCDS which could use the update tag, e.g. a 'tenderUpdate' release may be published which adds the answers to enquiries to `tender.documents`, or a 'contractUpdate' release may be published which updates the status of a milestone in `contracts.milestones`.

**Comment by jpmckinney** [comment]
CRM-5579 (not yet resolved) is potentially relevant.

**Comment by ColinMaudry** [comment]
> 1. What is the purpose of distinguishing between a 'tenderAmendment' and a 'tenderUpdate'?

The creation of certain release is triggered by formal events, while for others it's strictly about publishing data that is triggered by the mere opportunity or need to publish data. Use cases that I can think of:

- informal correction of values (e.g. for a typo)
- adding details about a party
- rephrasing informal content

> 2. Do publishers correctly distinguish the two when assigning tags to releases?

That's difficult to know. I **haven't** seen enough data to build an opinion on this matter. I believe that as long as legal experts have their say in how the data is published, they will determine which releases are updates and which are amendments. 

We could add a little guidance in the definition of the update codes:

> If you are unsure whether you should use a *Update or *Amendment code, use the *Update code.

> 3. In my experience, there is no such thing as an 'informal' change, and all changes must be legal…

That's right, but it only applies if:

- the publication of OCDS releases strictly follow the formal events
- the content of the fields comes 100% from formal documents

In the wild, I expect other releases to be published. See my answer to 1. above.

**Comment by jpmckinney** [comment]
Thanks! We have good answers from @duncandewhurst and @ColinMaudry to 1 and 3 from the issue description. Of course, the utility of the codes still depends on 2, but, for 2 to be a reason for deprecation on its own, we'd need evidence that data quality is very poor and not improving. As such, I retract my proposal. As follow-up, OCP can perhaps analyze the use of codes in order to assess the data quality, and determine appropriate actions.
