### ISSUE TITLE
tender.status incomplete list of values (during the period where the tenderPeriod end date already passed and the tender is not yet awarded)

### ISSUE THREAD

**Issue by daniel-clair** [open-contracting/standard#919]
During that period the tender status is no longer active. It's not complete because it's not awarded yet. It's not unsuccessful.

Could we add a status value for that period: "evaluating suppliers" or "expired" or "closed"?

**Comment by jpmckinney** [comment]
@daniel-clair Good point. I'm not immediately sure of the best code for this status. @yolile @duncandewhurst do you have suggestions?

**Comment by daniel-clair** [comment]
Good morning James,

The government of Canada uses "expired" when the tender pass the end date
"closing date". Based on those ideas, could  be "concluded", "closed" (I
don't like expired). These are terms when it passed the end date. If
someone think about this evaluation period I can use "assessment" or  maybe
"resolution".

Let me know what you think,

Regards,

Daniel

**Comment by yolile** [comment]
In Paraguay, we use "En Evaluación (Cerrada)" = In evaluation (Closed)
This period is the period indicated in the awardPeriod field, and the awardPeriod is: 

> The period for decision making regarding the contract award. The end date should be the date on which an award decision is due to be finalized. The start date may be used to indicate the start of an **evaluation** period.

So, I think that it could be "inEvaluation", "assessment" or "closed" (I prefer the ones that are more explicitly about the evaluation process)

**Comment by daniel-clair** [comment]
Did you add an extension to the schema to include your new value in the closed code list? Is it valid to do that with closed code lists? I'm very new with the extensions and I want to know how far I can go.

**Comment by duncandewhurst** [comment]
The period between the tender closing date and the contract being awarded could be comprised of both an evaluation period and a cooling off period - see the definition of 'pending' in the award status codelist:

> This award has been proposed, but is not yet in force. This can be due to a cooling off period, or some other process.

So, using 'evaluation', 'assessment' etc. might not be accurate.

The definition of `tender` in OCDS explicitly includes selecting a winner:

> Data regarding tender process - publicly inviting prospective contractors to submit bids for evaluation **and selecting a winner or winners**.

So, strictly following that definition the tender is still 'active' whilst the evaluation is taking place.

In that sense, it might be best to stick with the existing tender status codelist, and introduce a `statusDetails` free text field for systems which hold more granular source data.

> Did you add an extension to the schema to include your new value in the closed code list? Is it valid to do that with closed code lists? I'm very new with the extensions and I want to know how far I can go.

Extensions cannot change the values in a closed codelist, those changes need to be made as part of an upgrade to the standard.

**Comment by daniel-clair** [comment]
Thank you

**Comment by jpmckinney** [comment]
Per #1160, a tender is complete once "The bid submission deadline has passed.". So, it is not "active" during the evaluation.
