### ISSUE TITLE
Deprecate packages on record packages

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#920]
## Background

Only Chile, Paraguay and Zambia use `packages` in record packages, using this query in Redash:

```sql
SELECT DISTINCT(data->'publisher'->>'name') FROM package_data
WHERE data->'packages' IS NOT NULL;
```

## Discussion

It's not clear what real (not imagined) use cases this field serves.

## Proposal

Deprecate `packages` on record packages.

**Comment by aguilerapy** [comment]
Update: all these scrapers download record packages with the `packages` field:

chile_compra_bulk 
chile_compra_records 
mexico_nuevo_leon_records 
moldova 
nigeria_budeshi_records
paraguay_dncp_records 
portugal_records 
portugal 
zambia
