### ISSUE TITLE
Add Planning.id field

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#924]
Some countries, like Paraguay (and soon Honduras), have an identifier for the planning stage.

cc @yolile

**Comment by yolile** [comment]
Maybe the field can be called "identifier" instead of "id" because planning is not an array. (Just to avoid the confussion as happened with the tender.id field and the merging rules)

**Comment by jpmckinney** [comment]
Good point – I updated the issue title.

**Comment by yolile** [comment]
Extension available here: https://gitlab.com/dncp-opendata/ocds_planning_identifier_extension

**Comment by jpmckinney** [comment]
Hmm, in terms of confusion, we typically use `identifier` for `Identifier` objects, not simple strings. So, `id` might be better.
