### ISSUE TITLE
Publishing a document available in multiple languages

### ISSUE THREAD

**Issue by pindec** [open-contracting/standard#930]
Afghanistan has two official languages, and may therefore want to publish a document that is available in both languages at the same URL e.g. contracts. 

However, `document.language` is a string rather than an array of strings. 

For options now, @duncandewhurst suggested these alternatives:
- If one language is the primary language in any sense, then put this in the `.language` field and explain in the publication policy and/or `.description` field that the document is also provided in the secondary language.
- Add two entries to the `.documents` array, one for each language.

For the future, @jpmckinney suggested that one approach to avoid having two entries for the same document is to add `.languages` (array) and deprecate `.language` (string).

See also: CRM-5197.

**Comment by pindec** [comment]
Note that some publishers already treat document.language (string) as an array e.g. collection_id 197:
`"language": "deutsch, französisch, italienisch"`

**Comment by LindseyAM** [comment]
I think Canada also publishes in 2 languages. French& English

**Comment by jpmckinney** [comment]
Yes – this issue is about publishers who publish documents that contain multiple languages. In Canada, documents seem to be published in each language separately.

**Comment by jpmckinney** [comment]
Actually, re-opening since we probably want a bit in the docs to describe the use case.
