### ISSUE TITLE
Item Classification Scheme [x_ChileCompra_Clasificaciones_Productos ] 

### ISSUE THREAD

**Issue by nenita05leyla** [open-contracting/standard#931]
Hi! 
Please add ["x_ChileCompra_Clasificaciones_Productos"] to be considered and included in the code list of the item classification schemes. 

Example: 
```
"classification": {
"id": "73152101",
"scheme": "x_ChileCompra_Clasificaciones_Productos",
"uri": "http://apipre.mercadopublico.cl/APISOCDS/Productos/Categoria/73152101"
}
```
Thanks in advance. 
Greetings from Chile!

**Comment by jpmckinney** [comment]
Hi @nenita05leyla, thank you for creating the issue! We will need a Code, Title, Description, and Source for the new scheme. For example, an existing code has:

* Code: CUCOP
* Title: Mexican Single Classifier of Public Procurement
* Description: "The Single Classifier of Public Procurement (Clasificador Único de las Contrataciones Públicas) is a national scheme in Mexico for the classification of goods, works, services and leases."
* Source: https://sites.google.com/site/cnetcucop/

Can you provide these for the new scheme?

**Comment by nenita05leyla** [comment]
Hi! @jpmckinney thanks for your answer.
Please let me recopilate that information and I will give my feedback soon as I can. 
(please don't close this issue too soon :) )

Thanks in advance!

**Comment by nenita05leyla** [comment]
Hi again @jpmckinney 
We send you the information you requested, please check if this is enough,

- Code: [x_ChileCompra_Clasificaciones_Productos]
- Title: Chilean product classification code
- Description: The Chilean product classification code applies the level four UNSPSC (United Nations 
  Standardized Products and Services Code) to classify the products.
- Source: https://www.ungm.org/Public/UNSPSC  
- Example: http://api.mercadopublico.cl/APISOCDS/Productos/Categoria/73152101

Thanks in advance. 
Greetings! 
Leyla Pastén R.

**Comment by jpmckinney** [comment]
Thanks, @nenita05leyla. Does ChileCompra make changes to UNSPSC (e.g. add codes, or change the meaning of codes)? If not, then I believe the code to use is simply 'UNSPSC' which is already in the codelist.

**Comment by jpmckinney** [comment]
Closing in favor of using 'UNSPSC', per discussion via OCDS Helpdesk.

**Comment by nenita05leyla** [comment]
> Closing in favor of using 'UNSPSC', per discussion via OCDS Helpdesk.

Yes, we will use that, we talk about it with them. 
Thanks for your help..
Greetings! 
Leyla.
