### ISSUE TITLE
Update the description of `unit/id` to clarify which codelist to check

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard#938]
The description of `unit.id` is:

> The identifier from the codelist referenced in the scheme property. Check the codelist for details of how to find and use identifiers from the scheme in use.

This has caused confusion with publishers thinking they need to check the classification itself (e.g. UN/CEFACT) for how to find and use identifiers, when in fact the unitClassificationScheme codelist in OCDS has this information.

I suggest we update this to:

> The identifier from the codelist referenced in the scheme property. Check the unitClassificationScheme codelist for details of how to find and use identifiers from the scheme in use.

**Comment by jpmckinney** [comment]
Closed by #969 in 1.1.5-dev branch.
