### ISSUE TITLE
Green or sustainable procurement

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#939]
Potential resources on this topic: 

EU green public procurement criteria: https://ec.europa.eu/environment/gpp/eu_gpp_criteria_en.htm

EU library of use cases: https://ec.europa.eu/environment/gpp/case_group_en.htm

**Comment by jpmckinney** [comment]
eForms also has some modelling done for this.

**Comment by jpmckinney** [comment]
eForms has:
ID | Name | Description
-- | -- | --
BG-713 | Strategic Procurement | Information about strategic procurement. This information may differ per lot. In case of a prior information notice or a periodic indicative notice used only for information, this information may differ per part of the notice that may later become a lot or a self-standing procedure.
BT-06 | Strategic Procurement | Use of a technical specification, selection criterion, award criterion, or contract performance condition aims to reduce the environmental impacts of the procurement, fulfil social objectives and/or buy an innovative work, supply or service.
BT-777 | Strategic Procurement Description | Description of the use of a technical specification, selection criterion, award criterion, or contract performance condition aims to reduce the environmental impacts of the procurement, fulfil social objectives and/or buy an innovative work, supply or service.
BT-774 | Green Procurement | An approach to reducing the environmental impacts of the work, supply or service (e.g. requesting compliance with an environmental label)
BT-775 | Social Procurement | A social objective promoted by the works, supplies or services (e.g. fair working conditions)
BT-776 | Innovative Procurement | An indication that innovative works, supplies or services are being bought (e.g. the procured works, supplies or services being novel for the whole market).

Each has a short codelist:

BT-06:

- Reduction of environmental impacts
- Fulfilment of social objectives
- Innovative purchase

BT-774:

- Requesting compliance with an ISO 14024 Type I environmental label
- Requesting compliance with the eco-management and audit scheme (EMAS), established by Regulation (EC) No 1221/2009
- Requesting compliance with an ISO 14001 environmental management system, other than the eco-management and audit scheme (EMAS) established by Regulation (EC) No 1221/2009
- Requesting compliance with the highest energy efficiency class (as defined by various legislation such as, for example, Regulation (EU) 626/2011 on air conditioners)
- Requesting, for the majority of the relevant purchase, the compliance with Regulation (EC) 834/2007 on organic production and labelling of organic products

BT-775:

- Employment opportunities for the long-term unemployed, disadvantaged and/or for persons with disabilities 
- Accessibility for all
- Fair working conditions
- Human and workers' rights protection in global supply chains
- Gender equality
- Ethnic equality

BT-776:

- The procured works, supplies or services are novel for the organisation.
- The procured works, supplies or services are novel for the whole market.
- The technical specifications are primarily based on functional and performance requirements, not on describing the technical solution.
- The procured works, supplies or services involve research and development activities. 
- The procured works, supplies or services are likely to make the work of the buyer more effective. 

This will all be covered in our updates to the OCDS for EU profile for eForms, once the Publications Office publishes a mapping from TED to eForms. That work is tracked here: https://github.com/open-contracting-extensions/european-union/issues

**Comment by jpmckinney** [comment]
The [Maps glossary](https://www.mapsinitiative.org/methodology/MAPS-glossary.pdf) defines:

Term | Definition
-- | --
Sustainability | (a) Use of the biosphere by present generations while maintaining its potential yield (benefit) for future generations; and/or (b) non-declining trends of economic growth and development that might be impaired by natural resource depletion and environmental degradation.
Sustainable development | Development “that meets the needs of the present without compromising the ability of future generations to meet their own needs”, World Commission on Environment and Development (1987), Our Common Future, http://www.un-documents.net/our-common-future.pdf.
Sustainable Public Procurement (SPP) | A “process whereby organisations meet their needs for goods, services, works and utilities in a way that achieves value for money on a whole life basis in terms of generating benefits not only to the organisation, but also to society and the economy, whilst minimising damage to the environment”, Department for Environment, Food and Rural Affairs (2006), “Procuring the Future: Sustainable Action Plan: Recommendations from the Sustainable Procurement Task Force”, London, in: http://collections.europarchive. org/tna/20080530153425/http:/www.sustainable-development.gov.uk/publications/procurement-action-plan/documents/full-document.pdf.
