### ISSUE TITLE
Add guidance on OCDS publication in low tech environments

### ISSUE THREAD

**Issue by LindseyAM** [open-contracting/standard#942]
perhaps based on learning @duncandewhurst and others did with LA and challenges facing Nocopo in Nigeria?

**Comment by duncandewhurst** [comment]
The learning from LA was more around how spreadsheets can be used to prototype an OCDS implementation, but some of it could be adapted to describe how spreadsheets could be used as a general publication method. I've a half written up blog which could be used as the basis for a worked example of this.

**Comment by yolile** [comment]
Buenos Aires also published csv files and then use the flattening tool to publish json files.
INAI has a tool to capture and publish OCDS data: https://github.com/INAImexico/Contrataciones_abiertas_v2

**Comment by jpmckinney** [comment]
@yolile For the Airtable, is the appropriate link https://github.com/INAImexico/Contrataciones_abiertas_v2 or https://github.com/INAImexico/Contrataciones_abiertas ?

**Comment by yolile** [comment]
@jpmckinney sorry, they changed recently their repo to https://github.com/INAImexico/Contrataciones_abiertas_v2 that one is the correct one

**Comment by jpmckinney** [comment]
Thanks, I've updated the Airtable.

**Comment by sdopoku** [comment]
Some ideas worth exploring around these in future upgrades to the documentation are:

- Referencing [Budeshi](https://www.budeshi.ng/): using the search bar in the documentation to search for *Budeshi* pulls up 0 results so worth integrate this in future updates.  This meets the low infrastructure and low expertise criteria.
- Referencing the [OpenContractr](https://github.com/patxiworks/opencontractr) WordPress plug-in created by Patrick Enaholo through the OCDS Bounty Programme. This fits the low-tech criteria for publishers who do not have the resources and capacity to run a full e-GP system.

New Ideas
- [Open Data Kit](https://opendatakit.org/) and [Kobo Toolbox](https://www.kobotoolbox.org/) are two examples of mobile data collection tools for low technology contexts. As part of the offline monitoring approch in low-tech context, is there a way to develop an OCDS-complaint spreadsheet template that can capture data on the implementation stage?   This could build off the conversation started around @duncandewhurst's work.

**Comment by jpmckinney** [comment]
I think our experience has been that OCDS is not especially fit for low-tech environments, and we've been more successful starting with simple spreadsheets in direct support. This might eventually lead to an OCDS publication, but it relies heavily on our data support, so it isn't a good candidate for content to be added to static documentation.
