### ISSUE TITLE
itemClassificationScheme: New codes to consider

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#981]
* North American Industry Classification System (NAICS)
  * Canada, Mexico, United States
* Product and Service Codes (PSC)
  * at least United States
* Customs Cooperation Council Nomenclature (CCCN)
  * might no longer be extant, though some present classification systems might be based on it (e.g. Japan has a similar system for goods procured by central government)

**Comment by yolile** [comment]
Accordingly to https://thebusinessprofessor.com/knowledge-base/customs-cooperation-council-nomenclature-definition/ CCCN changed its name to Brussels Tariff Nomenclature and then to Harmonized Commodity Description and Coding System. Should we include it as CCCN or as HCDCS? https://www.foreign-trade.com/reference/hscode.htm

**Comment by jpmckinney** [comment]
Let's use Harmonized Commodity Description and Coding System, which seems to be most commonly abbreviated as HS. In the description, we can mention its history.
