### ISSUE TITLE
releaseTag: Add a tag for updates that fall outside the procedure's lifecycle

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#983]
For example, if a publisher adds address details to all its parties, there is no appropriate tag.

In the meantime, 'tenderUpdate' can be used for updates to the buyer and procuring entity parties, 'awardUpdate' for suppliers, 'implementationUpdate' for payees and payers, etc. These can of course be used in combination if a release updates all the parties.

**Comment by yolile** [comment]
Same for some extensions as: bids (tenderUpdate), auctions (tenderUpdate), complaints (tenderUpdate), secondStage (tenderUpdate? tender?)

**Comment by jpmckinney** [comment]
I think we should maybe start with a worked example about how to set tags in 1.1.5, and then through that process we'll identify other new tags we should add in OCDS 1.2.0.

**Comment by jpmckinney** [comment]
Merging into #792 so we discuss all related issues together.

**Comment by jpmckinney** [comment]
Noting that #792 is now #1184 (which pursues one of the two options considered in #792).
