### ISSUE TITLE
Add more images and diagrams to break up the text

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard#991]
General suggestion from OCDS retreat. Some specific suggestions:

* Add OCDS and e-GP diagram to the new implementation journey and/or primer section

**Comment by jpmckinney** [comment]
> Add OCDS and e-GP diagram to the new implementation journey and/or primer section

@duncandewhurst Do you know what diagram this refers to?

**Comment by duncandewhurst** [comment]
I think it's [this one](https://docs.google.com/presentation/d/1W47Ulx14HZRJ6GJisNNcXRQDHTj7tJinS0mlnbsC0BU/edit#slide=id.g5a4210352c_0_14)

**Comment by jpmckinney** [comment]
@LindseyAM suggested re-using the dog mascot (see #OCDS-dog thread for artist contact information). Example:

![image 3](https://user-images.githubusercontent.com/26463/99115217-0e5f3080-25c0-11eb-90e2-189c76ee6534.png)

**Comment by jpmckinney** [comment]
Attaching the image in case the link becomes inaccessible.

<img width="993" alt="Screenshot 2023-06-06 at 9 37 39 PM" src="https://github.com/open-contracting/standard/assets/26463/5d08a852-bd3d-479f-b1cf-a0fac934bb16">

I think this came up because, at least at the time, it was a common point of confusion.

Hopefully, with the primer and videos, we have addressed that confusion.

Additional images and diagrams have not been forthcoming. We can instead improve readability with a new theme https://github.com/open-contracting/standard_profile_template/issues/37
